sport = {'dota': {'5upjungz - recast gaming(favorit - https://www.favorit.com.ua/en/bets/#event=27144635&tours=2353988,2367757,2431631,2444138,2459582)': {'5upjungz will win': '3.55',
                                                                                                                                                   'draw will win': '2.00',
                                                                                                                                                   'recast gaming will win': '3.06'},
          'airgerlich - euronics(favorit - https://www.favorit.com.ua/en/bets/#event=27133753&tours=2353988,2367757,2431631,2444138,2459582)': {'airgerlich will win': '2.00',
                                                                                                                                                'draw will win': '2.15',
                                                                                                                                                'euronics will win': '7.00'},
          'beastcoast - thunder predator(favorit - https://www.favorit.com.ua/en/bets/#event=27144703&tours=2353988,2367757,2431631,2444138,2459582)': {'beastcoast will win': '4.30',
                                                                                                                                                        'draw will win': '2.33',
                                                                                                                                                        'thunder predator will win': '2.25'},
          'boom - new(favorit - https://www.favorit.com.ua/en/bets/#event=27126163&tours=2353988,2367757,2431631,2444138,2459582)': {'boom will win': '2.35',
                                                                                                                                     'draw will win': '2.15',
                                                                                                                                     'new will win': '4.60'},
          'cdec gaming - aster(favorit - https://www.favorit.com.ua/en/bets/#event=27126134&tours=2353988,2367757,2431631,2444138,2459582)': {'1-st map: aster first blood': '1.90',
                                                                                                                                              '1-st map: aster handicap +4.5 kills': '1.87',
                                                                                                                                              '1-st map: aster total kills over 20.5': '1.87',
                                                                                                                                              '1-st map: aster total kills under 20.5': '1.87',
                                                                                                                                              '1-st map: aster which will be the first to lose a barrack?': '1.59',
                                                                                                                                              '1-st map: aster will first destroy tower': '2.09',
                                                                                                                                              '1-st map: aster will win': '2.31',
                                                                                                                                              '1-st map: cdec gaming first blood': '1.84',
                                                                                                                                              '1-st map: cdec gaming handicap -4.5 kills': '1.87',
                                                                                                                                              '1-st map: cdec gaming total kills over 25.5': '1.98',
                                                                                                                                              '1-st map: cdec gaming total kills under 25.5': '1.77',
                                                                                                                                              '1-st map: cdec gaming which will be the first to lose a barrack?': '2.26',
                                                                                                                                              '1-st map: cdec gaming will first destroy tower': '1.69',
                                                                                                                                              '1-st map: cdec gaming will win': '1.57',
                                                                                                                                              '1-st map: total kills even': '1.90',
                                                                                                                                              '1-st map: total kills odd': '1.90',
                                                                                                                                              '1-st map: total kills over 45.5': '1.87',
                                                                                                                                              '1-st map: total kills under 45.5': '1.87',
                                                                                                                                              '1-st map: will there be megacreeps on the map no': '1.15',
                                                                                                                                              '1-st map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                              '2-nd map: aster first blood': '1.90',
                                                                                                                                              '2-nd map: aster handicap +4.5 kills': '1.87',
                                                                                                                                              '2-nd map: aster total kills over 20.5': '1.87',
                                                                                                                                              '2-nd map: aster total kills under 20.5': '1.87',
                                                                                                                                              '2-nd map: aster which will be the first to lose a barrack?': '1.59',
                                                                                                                                              '2-nd map: aster will first destroy tower': '2.09',
                                                                                                                                              '2-nd map: aster will win': '2.31',
                                                                                                                                              '2-nd map: cdec gaming first blood': '1.84',
                                                                                                                                              '2-nd map: cdec gaming handicap -4.5 kills': '1.87',
                                                                                                                                              '2-nd map: cdec gaming total kills over 25.5': '1.98',
                                                                                                                                              '2-nd map: cdec gaming total kills under 25.5': '1.77',
                                                                                                                                              '2-nd map: cdec gaming which will be the first to lose a barrack?': '2.26',
                                                                                                                                              '2-nd map: cdec gaming will first destroy tower': '1.69',
                                                                                                                                              '2-nd map: cdec gaming will win': '1.57',
                                                                                                                                              '2-nd map: total kills even': '1.90',
                                                                                                                                              '2-nd map: total kills odd': '1.90',
                                                                                                                                              '2-nd map: total kills over 45.5': '1.87',
                                                                                                                                              '2-nd map: total kills under 45.5': '1.87',
                                                                                                                                              '2-nd map: will there be megacreeps on the map no': '1.15',
                                                                                                                                              '2-nd map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                              'aster handicap +0.5 maps': '2.60',
                                                                                                                                              'aster handicap +1.5 maps': '1.50',
                                                                                                                                              'aster handicap -0.5 maps': '2.60',
                                                                                                                                              'aster handicap -1.5 maps': '5.30',
                                                                                                                                              'aster will win': '2.60',
                                                                                                                                              'cdec gaming handicap +0.5 maps': '1.46',
                                                                                                                                              'cdec gaming handicap +1.5 maps': '1.13',
                                                                                                                                              'cdec gaming handicap -0.5 maps': '1.46',
                                                                                                                                              'cdec gaming handicap -1.5 maps': '2.48',
                                                                                                                                              'cdec gaming will win': '1.46',
                                                                                                                                              'correct score 0-2': '5.30',
                                                                                                                                              'correct score 1-2': '4.50',
                                                                                                                                              'correct score 2-0': '2.48',
                                                                                                                                              'correct score 2-1': '3.05',
                                                                                                                                              'total maps over 2.5': '1.94',
                                                                                                                                              'total maps under 2.5': '1.80'},
          'cdec gaming - vici gaming(favorit - https://www.favorit.com.ua/en/bets/#event=27126667&tours=2353988,2367757,2431631,2444138,2459582)': {'1-st map: cdec gaming first blood': '1.87',
                                                                                                                                                    '1-st map: cdec gaming handicap +0.5 kills': '1.87',
                                                                                                                                                    '1-st map: cdec gaming total kills over 22.5': '1.87',
                                                                                                                                                    '1-st map: cdec gaming total kills under 22.5': '1.87',
                                                                                                                                                    '1-st map: cdec gaming which will be the first to lose a barrack?': '1.87',
                                                                                                                                                    '1-st map: cdec gaming will first destroy tower': '1.87',
                                                                                                                                                    '1-st map: cdec gaming will win': '1.87',
                                                                                                                                                    '1-st map: total kills even': '1.90',
                                                                                                                                                    '1-st map: total kills odd': '1.90',
                                                                                                                                                    '1-st map: total kills over 45.5': '1.87',
                                                                                                                                                    '1-st map: total kills under 45.5': '1.87',
                                                                                                                                                    '1-st map: vici gaming first blood': '1.87',
                                                                                                                                                    '1-st map: vici gaming handicap -0.5 kills': '1.87',
                                                                                                                                                    '1-st map: vici gaming total kills over 23.5': '1.98',
                                                                                                                                                    '1-st map: vici gaming total kills under 23.5': '1.77',
                                                                                                                                                    '1-st map: vici gaming which will be the first to lose a barrack?': '1.87',
                                                                                                                                                    '1-st map: vici gaming will first destroy tower': '1.87',
                                                                                                                                                    '1-st map: vici gaming will win': '1.87',
                                                                                                                                                    '1-st map: will there be megacreeps on the map no': '1.15',
                                                                                                                                                    '1-st map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                                    '2-nd map: cdec gaming first blood': '1.87',
                                                                                                                                                    '2-nd map: cdec gaming handicap +0.5 kills': '1.87',
                                                                                                                                                    '2-nd map: cdec gaming total kills over 22.5': '1.87',
                                                                                                                                                    '2-nd map: cdec gaming total kills under 22.5': '1.87',
                                                                                                                                                    '2-nd map: cdec gaming which will be the first to lose a barrack?': '1.87',
                                                                                                                                                    '2-nd map: cdec gaming will first destroy tower': '1.87',
                                                                                                                                                    '2-nd map: cdec gaming will win': '1.87',
                                                                                                                                                    '2-nd map: total kills even': '1.90',
                                                                                                                                                    '2-nd map: total kills odd': '1.90',
                                                                                                                                                    '2-nd map: total kills over 45.5': '1.87',
                                                                                                                                                    '2-nd map: total kills under 45.5': '1.87',
                                                                                                                                                    '2-nd map: vici gaming first blood': '1.87',
                                                                                                                                                    '2-nd map: vici gaming handicap -0.5 kills': '1.87',
                                                                                                                                                    '2-nd map: vici gaming total kills over 23.5': '1.98',
                                                                                                                                                    '2-nd map: vici gaming total kills under 23.5': '1.77',
                                                                                                                                                    '2-nd map: vici gaming which will be the first to lose a barrack?': '1.87',
                                                                                                                                                    '2-nd map: vici gaming will first destroy tower': '1.87',
                                                                                                                                                    '2-nd map: vici gaming will win': '1.87',
                                                                                                                                                    '2-nd map: will there be megacreeps on the map no': '1.15',
                                                                                                                                                    '2-nd map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                                    'cdec gaming handicap +0.5 maps': '1.87',
                                                                                                                                                    'cdec gaming handicap +1.5 maps': '1.28',
                                                                                                                                                    'cdec gaming handicap -0.5 maps': '1.87',
                                                                                                                                                    'cdec gaming handicap -1.5 maps': '3.50',
                                                                                                                                                    'cdec gaming will win': '1.87',
                                                                                                                                                    'correct score 0-2': '3.50',
                                                                                                                                                    'correct score 1-2': '3.50',
                                                                                                                                                    'correct score 2-0': '3.50',
                                                                                                                                                    'correct score 2-1': '3.50',
                                                                                                                                                    'total maps over 2.5': '1.87',
                                                                                                                                                    'total maps under 2.5': '1.87',
                                                                                                                                                    'vici gaming handicap +0.5 maps': '1.87',
                                                                                                                                                    'vici gaming handicap +1.5 maps': '1.28',
                                                                                                                                                    'vici gaming handicap -0.5 maps': '1.87',
                                                                                                                                                    'vici gaming handicap -1.5 maps': '3.50',
                                                                                                                                                    'vici gaming will win': '1.87'},
          'cr4zy - midas(favorit - https://www.favorit.com.ua/en/bets/#event=27144697&tours=2353988,2367757,2431631,2444138,2459582)': {'cr4zy will win': '1.21',
                                                                                                                                        'draw will win': '4.85',
                                                                                                                                        'midas will win': '13.50'},
          'esport rhein-neckar - kolossus(favorit - https://www.favorit.com.ua/en/bets/#event=27144636&tours=2353988,2367757,2431631,2444138,2459582)': {'draw will win': '2.00',
                                                                                                                                                         'esport rhein-neckar will win': '2.65',
                                                                                                                                                         'kolossus will win': '4.35'},
          'fnatic - geek fam(favorit - https://www.favorit.com.ua/en/bets/#event=27146241&tours=2353988,2367757,2431631,2444138,2459582)': {'draw will win': '2.15',
                                                                                                                                            'fnatic will win': '2.10',
                                                                                                                                            'geek fam will win': '6.00'},
          'fnatic - neon(favorit - https://www.favorit.com.ua/en/bets/#event=27146239&tours=2353988,2367757,2431631,2444138,2459582)': {'draw will win': '2.35',
                                                                                                                                        'fnatic will win': '1.75',
                                                                                                                                        'neon will win': '8.50'},
          'geek fam - t1(favorit - https://www.favorit.com.ua/en/bets/#event=27126157&tours=2353988,2367757,2431631,2444138,2459582)': {'draw will win': '2.25',
                                                                                                                                        'geek fam will win': '2.28',
                                                                                                                                        't1 will win': '4.40'},
          'geek fam - tnc predator(favorit - https://www.favorit.com.ua/en/bets/#event=27146244&tours=2353988,2367757,2431631,2444138,2459582)': {'draw will win': '1.95',
                                                                                                                                                  'geek fam will win': '4.00',
                                                                                                                                                  'tnc predator will win': '2.85'},
          'infamous - infinity(favorit - https://www.favorit.com.ua/en/bets/#event=27144701&tours=2353988,2367757,2431631,2444138,2459582)': {'draw will win': '2.33',
                                                                                                                                              'infamous will win': '2.31',
                                                                                                                                              'infinity will win': '4.05'},
          'infamous - midas(favorit - https://www.favorit.com.ua/en/bets/#event=27144693&tours=2353988,2367757,2431631,2444138,2459582)': {'draw will win': '2.50',
                                                                                                                                           'infamous will win': '1.74',
                                                                                                                                           'midas will win': '7.00'},
          'invictus gaming - aster(favorit - https://www.favorit.com.ua/en/bets/#event=27126141&tours=2353988,2367757,2431631,2444138,2459582)': {'1-st map: aster first blood': '1.89',
                                                                                                                                                  '1-st map: aster handicap +4.5 kills': '1.87',
                                                                                                                                                  '1-st map: aster total kills over 21.5': '1.98',
                                                                                                                                                  '1-st map: aster total kills under 21.5': '1.77',
                                                                                                                                                  '1-st map: aster which will be the first to lose a barrack?': '1.67',
                                                                                                                                                  '1-st map: aster will first destroy tower': '2.02',
                                                                                                                                                  '1-st map: aster will win': '2.16',
                                                                                                                                                  '1-st map: invictus gaming first blood': '1.85',
                                                                                                                                                  '1-st map: invictus gaming handicap -4.5 kills': '1.87',
                                                                                                                                                  '1-st map: invictus gaming total kills over 25.5': '1.87',
                                                                                                                                                  '1-st map: invictus gaming total kills under 25.5': '1.87',
                                                                                                                                                  '1-st map: invictus gaming which will be the first to lose a barrack?': '2.13',
                                                                                                                                                  '1-st map: invictus gaming will first destroy tower': '1.74',
                                                                                                                                                  '1-st map: invictus gaming will win': '1.65',
                                                                                                                                                  '1-st map: total kills even': '1.90',
                                                                                                                                                  '1-st map: total kills odd': '1.90',
                                                                                                                                                  '1-st map: total kills over 46.5': '1.87',
                                                                                                                                                  '1-st map: total kills under 46.5': '1.87',
                                                                                                                                                  '1-st map: will there be megacreeps on the map no': '1.15',
                                                                                                                                                  '1-st map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                                  '2-nd map: aster first blood': '1.89',
                                                                                                                                                  '2-nd map: aster handicap +4.5 kills': '1.87',
                                                                                                                                                  '2-nd map: aster total kills over 21.5': '1.98',
                                                                                                                                                  '2-nd map: aster total kills under 21.5': '1.77',
                                                                                                                                                  '2-nd map: aster which will be the first to lose a barrack?': '1.67',
                                                                                                                                                  '2-nd map: aster will first destroy tower': '2.02',
                                                                                                                                                  '2-nd map: aster will win': '2.16',
                                                                                                                                                  '2-nd map: invictus gaming first blood': '1.85',
                                                                                                                                                  '2-nd map: invictus gaming handicap -4.5 kills': '1.87',
                                                                                                                                                  '2-nd map: invictus gaming total kills over 25.5': '1.87',
                                                                                                                                                  '2-nd map: invictus gaming total kills under 25.5': '1.87',
                                                                                                                                                  '2-nd map: invictus gaming which will be the first to lose a barrack?': '2.13',
                                                                                                                                                  '2-nd map: invictus gaming will first destroy tower': '1.74',
                                                                                                                                                  '2-nd map: invictus gaming will win': '1.65',
                                                                                                                                                  '2-nd map: total kills even': '1.90',
                                                                                                                                                  '2-nd map: total kills odd': '1.90',
                                                                                                                                                  '2-nd map: total kills over 46.5': '1.87',
                                                                                                                                                  '2-nd map: total kills under 46.5': '1.87',
                                                                                                                                                  '2-nd map: will there be megacreeps on the map no': '1.15',
                                                                                                                                                  '2-nd map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                                  'aster handicap +0.5 maps': '2.33',
                                                                                                                                                  'aster handicap +1.5 maps': '1.42',
                                                                                                                                                  'aster handicap -0.5 maps': '2.33',
                                                                                                                                                  'aster handicap -1.5 maps': '4.65',
                                                                                                                                                  'aster will win': '2.33',
                                                                                                                                                  'correct score 0-2': '4.65',
                                                                                                                                                  'correct score 1-2': '4.10',
                                                                                                                                                  'correct score 2-0': '2.73',
                                                                                                                                                  'correct score 2-1': '3.15',
                                                                                                                                                  'invictus gaming handicap +0.5 maps': '1.56',
                                                                                                                                                  'invictus gaming handicap +1.5 maps': '1.17',
                                                                                                                                                  'invictus gaming handicap -0.5 maps': '1.56',
                                                                                                                                                  'invictus gaming handicap -1.5 maps': '2.73',
                                                                                                                                                  'invictus gaming will win': '1.56',
                                                                                                                                                  'total maps over 2.5': '1.99',
                                                                                                                                                  'total maps under 2.5': '1.76'},
          'invictus gaming - royal never give up(favorit - https://www.favorit.com.ua/en/bets/#event=27145891&tours=2353988,2367757,2431631,2444138,2459582)': {'1-st map: invictus gaming first blood': '1.87',
                                                                                                                                                                '1-st map: invictus gaming handicap -0.5 kills': '1.87',
                                                                                                                                                                '1-st map: invictus gaming total kills over 23.5': '1.98',
                                                                                                                                                                '1-st map: invictus gaming total kills under 23.5': '1.77',
                                                                                                                                                                '1-st map: invictus gaming which will be the first to lose a barrack?': '1.87',
                                                                                                                                                                '1-st map: invictus gaming will first destroy tower': '1.87',
                                                                                                                                                                '1-st map: invictus gaming will win': '1.87',
                                                                                                                                                                '1-st map: royal never give up first blood': '1.87',
                                                                                                                                                                '1-st map: royal never give up handicap +0.5 kills': '1.87',
                                                                                                                                                                '1-st map: royal never give up total kills over 22.5': '1.87',
                                                                                                                                                                '1-st map: royal never give up total kills under 22.5': '1.87',
                                                                                                                                                                '1-st map: royal never give up which will be the first to lose a barrack?': '1.87',
                                                                                                                                                                '1-st map: royal never give up will first destroy tower': '1.87',
                                                                                                                                                                '1-st map: royal never give up will win': '1.87',
                                                                                                                                                                '1-st map: total kills even': '1.90',
                                                                                                                                                                '1-st map: total kills odd': '1.90',
                                                                                                                                                                '1-st map: total kills over 45.5': '1.87',
                                                                                                                                                                '1-st map: total kills under 45.5': '1.87',
                                                                                                                                                                '1-st map: will there be megacreeps on the map no': '1.15',
                                                                                                                                                                '1-st map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                                                '2-nd map: invictus gaming first blood': '1.87',
                                                                                                                                                                '2-nd map: invictus gaming handicap -0.5 kills': '1.87',
                                                                                                                                                                '2-nd map: invictus gaming total kills over 23.5': '1.98',
                                                                                                                                                                '2-nd map: invictus gaming total kills under 23.5': '1.77',
                                                                                                                                                                '2-nd map: invictus gaming which will be the first to lose a barrack?': '1.87',
                                                                                                                                                                '2-nd map: invictus gaming will first destroy tower': '1.87',
                                                                                                                                                                '2-nd map: invictus gaming will win': '1.87',
                                                                                                                                                                '2-nd map: royal never give up first blood': '1.87',
                                                                                                                                                                '2-nd map: royal never give up handicap +0.5 kills': '1.87',
                                                                                                                                                                '2-nd map: royal never give up total kills over 22.5': '1.87',
                                                                                                                                                                '2-nd map: royal never give up total kills under 22.5': '1.87',
                                                                                                                                                                '2-nd map: royal never give up which will be the first to lose a barrack?': '1.87',
                                                                                                                                                                '2-nd map: royal never give up will first destroy tower': '1.87',
                                                                                                                                                                '2-nd map: royal never give up will win': '1.87',
                                                                                                                                                                '2-nd map: total kills even': '1.90',
                                                                                                                                                                '2-nd map: total kills odd': '1.90',
                                                                                                                                                                '2-nd map: total kills over 45.5': '1.87',
                                                                                                                                                                '2-nd map: total kills under 45.5': '1.87',
                                                                                                                                                                '2-nd map: will there be megacreeps on the map no': '1.15',
                                                                                                                                                                '2-nd map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                                                'correct score 0-2': '3.50',
                                                                                                                                                                'correct score 1-2': '3.50',
                                                                                                                                                                'correct score 2-0': '3.50',
                                                                                                                                                                'correct score 2-1': '3.50',
                                                                                                                                                                'invictus gaming handicap +0.5 maps': '1.87',
                                                                                                                                                                'invictus gaming handicap +1.5 maps': '1.28',
                                                                                                                                                                'invictus gaming handicap -0.5 maps': '1.87',
                                                                                                                                                                'invictus gaming handicap -1.5 maps': '3.50',
                                                                                                                                                                'invictus gaming will win': '1.87',
                                                                                                                                                                'royal never give up handicap +0.5 maps': '1.87',
                                                                                                                                                                'royal never give up handicap +1.5 maps': '1.28',
                                                                                                                                                                'royal never give up handicap -0.5 maps': '1.87',
                                                                                                                                                                'royal never give up handicap -1.5 maps': '3.50',
                                                                                                                                                                'royal never give up will win': '1.87',
                                                                                                                                                                'total maps over 2.5': '1.97',
                                                                                                                                                                'total maps under 2.5': '1.78'},
          'neon - adroit(favorit - https://www.favorit.com.ua/en/bets/#event=27126151&tours=2353988,2367757,2431631,2444138,2459582)': {'adroit will win': '3.65',
                                                                                                                                        'draw will win': '2.00',
                                                                                                                                        'neon will win': '3.00'},
          'psg.lgd - royal never give up(favorit - https://www.favorit.com.ua/en/bets/#event=27126142&tours=2353988,2367757,2431631,2444138,2459582)': {'1-st map: psg.lgd first blood': '1.85',
                                                                                                                                                        '1-st map: psg.lgd handicap -4.5 kills': '1.87',
                                                                                                                                                        '1-st map: psg.lgd total kills over 25.5': '1.87',
                                                                                                                                                        '1-st map: psg.lgd total kills under 25.5': '1.87',
                                                                                                                                                        '1-st map: psg.lgd which will be the first to lose a barrack?': '2.18',
                                                                                                                                                        '1-st map: psg.lgd will first destroy tower': '1.72',
                                                                                                                                                        '1-st map: psg.lgd will win': '1.62',
                                                                                                                                                        '1-st map: royal never give up first blood': '1.89',
                                                                                                                                                        '1-st map: royal never give up handicap +4.5 kills': '1.87',
                                                                                                                                                        '1-st map: royal never give up total kills over 21.5': '1.98',
                                                                                                                                                        '1-st map: royal never give up total kills under 21.5': '1.77',
                                                                                                                                                        '1-st map: royal never give up which will be the first to lose a barrack?': '1.64',
                                                                                                                                                        '1-st map: royal never give up will first destroy tower': '2.04',
                                                                                                                                                        '1-st map: royal never give up will win': '2.21',
                                                                                                                                                        '1-st map: total kills even': '1.90',
                                                                                                                                                        '1-st map: total kills odd': '1.90',
                                                                                                                                                        '1-st map: total kills over 46.5': '1.87',
                                                                                                                                                        '1-st map: total kills under 46.5': '1.87',
                                                                                                                                                        '1-st map: will there be megacreeps on the map no': '1.15',
                                                                                                                                                        '1-st map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                                        '2-nd map: psg.lgd first blood': '1.85',
                                                                                                                                                        '2-nd map: psg.lgd handicap -4.5 kills': '1.87',
                                                                                                                                                        '2-nd map: psg.lgd total kills over 25.5': '1.87',
                                                                                                                                                        '2-nd map: psg.lgd total kills under 25.5': '1.87',
                                                                                                                                                        '2-nd map: psg.lgd which will be the first to lose a barrack?': '2.18',
                                                                                                                                                        '2-nd map: psg.lgd will first destroy tower': '1.72',
                                                                                                                                                        '2-nd map: psg.lgd will win': '1.62',
                                                                                                                                                        '2-nd map: royal never give up first blood': '1.89',
                                                                                                                                                        '2-nd map: royal never give up handicap +4.5 kills': '1.87',
                                                                                                                                                        '2-nd map: royal never give up total kills over 21.5': '1.98',
                                                                                                                                                        '2-nd map: royal never give up total kills under 21.5': '1.77',
                                                                                                                                                        '2-nd map: royal never give up which will be the first to lose a barrack?': '1.64',
                                                                                                                                                        '2-nd map: royal never give up will first destroy tower': '2.04',
                                                                                                                                                        '2-nd map: royal never give up will win': '2.21',
                                                                                                                                                        '2-nd map: total kills even': '1.90',
                                                                                                                                                        '2-nd map: total kills odd': '1.90',
                                                                                                                                                        '2-nd map: total kills over 46.5': '1.87',
                                                                                                                                                        '2-nd map: total kills under 46.5': '1.87',
                                                                                                                                                        '2-nd map: will there be megacreeps on the map no': '1.15',
                                                                                                                                                        '2-nd map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                                        'correct score 0-2': '4.90',
                                                                                                                                                        'correct score 1-2': '4.25',
                                                                                                                                                        'correct score 2-0': '2.64',
                                                                                                                                                        'correct score 2-1': '3.10',
                                                                                                                                                        'psg.lgd handicap +0.5 maps': '1.52',
                                                                                                                                                        'psg.lgd handicap +1.5 maps': '1.15',
                                                                                                                                                        'psg.lgd handicap -0.5 maps': '1.52',
                                                                                                                                                        'psg.lgd handicap -1.5 maps': '2.64',
                                                                                                                                                        'psg.lgd will win': '1.52',
                                                                                                                                                        'royal never give up handicap +0.5 maps': '2.42',
                                                                                                                                                        'royal never give up handicap +1.5 maps': '1.45',
                                                                                                                                                        'royal never give up handicap -0.5 maps': '2.42',
                                                                                                                                                        'royal never give up handicap -1.5 maps': '4.90',
                                                                                                                                                        'royal never give up will win': '2.42',
                                                                                                                                                        'total maps over 2.5': '1.91',
                                                                                                                                                        'total maps under 2.5': '1.83'},
          'psg.lgd - sirius(favorit - https://www.favorit.com.ua/en/bets/#event=27126125&tours=2353988,2367757,2431631,2444138,2459582)': {'1-st map: psg.lgd first blood': '1.75',
                                                                                                                                           '1-st map: psg.lgd handicap -12.5 kills': '1.87',
                                                                                                                                           '1-st map: psg.lgd total kills over 29.5': '1.98',
                                                                                                                                           '1-st map: psg.lgd total kills under 29.5': '1.77',
                                                                                                                                           '1-st map: psg.lgd which will be the first to lose a barrack?': '3.80',
                                                                                                                                           '1-st map: psg.lgd will first destroy tower': '1.43',
                                                                                                                                           '1-st map: psg.lgd will win': '1.20',
                                                                                                                                           '1-st map: sirius first blood': '2.01',
                                                                                                                                           '1-st map: sirius handicap +12.5 kills': '1.87',
                                                                                                                                           '1-st map: sirius total kills over 16.5': '1.87',
                                                                                                                                           '1-st map: sirius total kills under 16.5': '1.87',
                                                                                                                                           '1-st map: sirius which will be the first to lose a barrack?': '1.24',
                                                                                                                                           '1-st map: sirius will first destroy tower': '2.71',
                                                                                                                                           '1-st map: sirius will win': '4.20',
                                                                                                                                           '1-st map: total kills even': '1.90',
                                                                                                                                           '1-st map: total kills odd': '1.90',
                                                                                                                                           '1-st map: total kills over 45.5': '1.87',
                                                                                                                                           '1-st map: total kills under 45.5': '1.87',
                                                                                                                                           '1-st map: will there be megacreeps on the map no': '1.15',
                                                                                                                                           '1-st map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                           '2-nd map: psg.lgd first blood': '1.75',
                                                                                                                                           '2-nd map: psg.lgd handicap -12.5 kills': '1.87',
                                                                                                                                           '2-nd map: psg.lgd total kills over 29.5': '1.98',
                                                                                                                                           '2-nd map: psg.lgd total kills under 29.5': '1.77',
                                                                                                                                           '2-nd map: psg.lgd which will be the first to lose a barrack?': '3.80',
                                                                                                                                           '2-nd map: psg.lgd will first destroy tower': '1.43',
                                                                                                                                           '2-nd map: psg.lgd will win': '1.20',
                                                                                                                                           '2-nd map: sirius first blood': '2.01',
                                                                                                                                           '2-nd map: sirius handicap +12.5 kills': '1.87',
                                                                                                                                           '2-nd map: sirius total kills over 16.5': '1.87',
                                                                                                                                           '2-nd map: sirius total kills under 16.5': '1.87',
                                                                                                                                           '2-nd map: sirius which will be the first to lose a barrack?': '1.24',
                                                                                                                                           '2-nd map: sirius will first destroy tower': '2.71',
                                                                                                                                           '2-nd map: sirius will win': '4.20',
                                                                                                                                           '2-nd map: total kills even': '1.90',
                                                                                                                                           '2-nd map: total kills odd': '1.90',
                                                                                                                                           '2-nd map: total kills over 45.5': '1.87',
                                                                                                                                           '2-nd map: total kills under 45.5': '1.87',
                                                                                                                                           '2-nd map: will there be megacreeps on the map no': '1.15',
                                                                                                                                           '2-nd map: will there be megacreeps on the map yes': '5.00',
                                                                                                                                           'correct score 0-2': '17.50',
                                                                                                                                           'correct score 1-2': '11.50',
                                                                                                                                           'correct score 2-0': '1.47',
                                                                                                                                           'correct score 2-1': '3.25',
                                                                                                                                           'psg.lgd handicap +0.5 maps': '1.07',
                                                                                                                                           'psg.lgd handicap -0.5 maps': '1.07',
                                                                                                                                           'psg.lgd handicap -1.5 maps': '1.47',
                                                                                                                                           'psg.lgd will win': '1.07',
                                                                                                                                           'sirius handicap +0.5 maps': '7.40',
                                                                                                                                           'sirius handicap +1.5 maps': '2.55',
                                                                                                                                           'sirius handicap -0.5 maps': '7.40',
                                                                                                                                           'sirius will win': '7.40',
                                                                                                                                           'total maps over 2.5': '2.90',
                                                                                                                                           'total maps under 2.5': '1.38'}}}
