sport = {'dota': {'4 zoomers - cr4zy': {'4 zoomers handicap -1.5 maps': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                '4 zoomers will win': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                'cr4zy handicap +1.5 maps': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                'cr4zy will win': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                'total maps over 2.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                'total maps under 2.5': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)']},
          '5upjungz - playing ducks': {'5upjungz will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-meisterschaft)'],
                                       'draw will win': ['2.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-meisterschaft)'],
                                       'playing ducks will win': ['9.00(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-meisterschaft)']},
          'adroit - geek fam': {'1-st map: adroit handicap +6.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '1-st map: geek fam handicap -6.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '1-st map: total kills over 47.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '1-st map: total kills under 47.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '2-nd map: adroit handicap +6.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '2-nd map: geek fam handicap -6.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '2-nd map: total kills over 47.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '2-nd map: total kills under 47.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                'adroit handicap +1.5 maps': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                'adroit will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                'geek fam handicap -1.5 maps': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                'geek fam will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                'total maps over 2.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                'total maps under 2.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '\xa0 adroit handicap +5.5 maps': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '\xa0 adroit handicap +7.5 maps': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '\xa0 geek fam handicap -5.5 maps': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '\xa0 geek fam handicap -7.5 maps': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '\xa0 total maps over 45.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '\xa0 total maps over 49.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '\xa0 total maps under 45.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                '\xa0 total maps under 49.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)']},
          'ancient apparition - phantom lancer': {'ancient apparition will win': ['3.00(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'],
                                                  'phantom lancer will win': ['1.36(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)']},
          'aspirations - sunrise': {'aspirations will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-red-star-cup)'], 'sunrise will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-red-star-cup)']},
          'aster.aries - blaze': {'aster.aries will win': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dspl-cda)'], 'blaze will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dspl-cda)']},
          'aster.aries - ocean': {'aster.aries will win': ['1.27(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-cn-qualifier)'],
                                  'ocean will win': ['3.54(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-cn-qualifier)']},
          'bad boys - blaze': {'bad boys will win': ['3.33(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-cn-qualifier)'], 'blaze will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-cn-qualifier)']},
          'beastcoast - quincy crew': {'beastcoast handicap +1.5 maps': ['2.29(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                       'beastcoast will win': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                       'quincy crew handicap -1.5 maps': ['1.58(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                       'quincy crew will win': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                       'total maps over 2.5': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                       'total maps under 2.5': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)']},
          'bounty hunter - dazzle': {'bounty hunter will win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'], 'dazzle will win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)']},
          'brave - cobra': {'brave will win': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asia-challenger-league)'], 'cobra will win': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asia-challenger-league)']},
          'business associates - infamous': {'business associates handicap -1.5 maps': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                             'business associates will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                             'infamous handicap +1.5 maps': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                             'infamous will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                             'total maps over 2.5': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                             'total maps under 2.5': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)']},
          'cignal ultra - vice': {'cignal ultra will win': ['2.40(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-world-elite-competition-sea)'],
                                  'draw will win': ['2.03(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-world-elite-competition-sea)'],
                                  'vice will win': ['4.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-world-elite-competition-sea)']},
          'destiny - recast': {'destiny will win': ['13.0(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-meisterschaft)'],
                               'draw will win': ['4.16(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-meisterschaft)'],
                               'recast will win': ['1.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-meisterschaft)']},
          'dragon knight - invoker': {'dragon knight will win': ['5.55(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'], 'invoker will win': ['1.12(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)']},
          'drow ranger - tidehunter': {'drow ranger will win': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'], 'tidehunter will win': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)']},
          'ehome - royal never give up': {'1-st map: ehome handicap +3.5 kills': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '1-st map: royal never give up handicap -3.5 kills': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '1-st map: total kills over 46.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '1-st map: total kills under 46.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '2-nd map: ehome handicap +3.5 kills': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '2-nd map: royal never give up handicap -3.5 kills': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '2-nd map: total kills over 46.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '2-nd map: total kills under 46.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          'ehome handicap +1.5 maps': ['1.33(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          'ehome will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          'royal never give up handicap -1.5 maps': ['3.15(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          'royal never give up will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          'total maps over 2.5': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          'total maps under 2.5': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '\xa0 ehome handicap +4.5 maps': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '\xa0 ehome handicap +5.5 maps': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '\xa0 royal never give up handicap -4.5 maps': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '\xa0 royal never give up handicap -5.5 maps': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '\xa0 total maps over 44.5': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '\xa0 total maps over 48.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '\xa0 total maps under 44.5': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                          '\xa0 total maps under 48.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)']},
          'five brothers - sunrise': {'five brothers will win': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-red-star-cup)'], 'sunrise will win': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-red-star-cup)']},
          'fnatic - tnc predator': {'1-st map: fnatic handicap -6.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '1-st map: tnc predator handicap +6.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '1-st map: total kills over 47.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '1-st map: total kills under 47.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '2-nd map: fnatic handicap -6.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '2-nd map: tnc predator handicap +6.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '2-nd map: total kills over 47.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '2-nd map: total kills under 47.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    'fnatic handicap -1.5 maps': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    'fnatic will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    'tnc predator handicap +1.5 maps': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    'tnc predator will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    'total maps over 2.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    'total maps under 2.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '\xa0 fnatic handicap -5.5 maps': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '\xa0 fnatic handicap -7.5 maps': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '\xa0 tnc predator handicap +5.5 maps': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '\xa0 tnc predator handicap +7.5 maps': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '\xa0 total maps over 45.5': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '\xa0 total maps over 49.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '\xa0 total maps under 45.5': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'],
                                    '\xa0 total maps under 49.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)']},
          'future.club - wolf': {'future.club will win': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-red-star-cup)'], 'wolf will win': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-red-star-cup)']},
          'immortal - panda': {'immortal will win': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asia-challenger-league)'], 'panda will win': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asia-challenger-league)']},
          'jakiro - storm spirit': {'jakiro will win': ['12.0(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'], 'storm spirit will win': ['1.01(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)']},
          'medusa - tiny': {'medusa will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'], 'tiny will win': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)']},
          'midas - thunder predator': {'midas handicap +1.5 maps': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                       'midas will win': ['6.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                       'thunder predator handicap -1.5 maps': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                       'thunder predator will win': ['1.10(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                       'total maps over 2.5': ['2.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)'],
                                       'total maps under 2.5': ['1.37(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)']},
          'neon - the new top': {'draw will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-world-elite-competition-sea)'],
                                 'neon will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-world-elite-competition-sea)'],
                                 'the new top will win': ['10.0(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-world-elite-competition-sea)']},
          'ocean - typhoon': {'ocean will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dspl-cda)'], 'typhoon will win': ['2.63(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dspl-cda)']},
          'pacific - spirits': {'draw will win': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)'],
                                'pacific will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)'],
                                'spirits will win': ['3.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)']},
          'pacific - vicious': {'draw will win': ['2.03(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)'],
                                'pacific will win': ['2.40(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)'],
                                'vicious will win': ['4.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)']},
          'sparking arrow - vici': {'1-st map: sparking arrow handicap +5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '1-st map: total kills over 45.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '1-st map: total kills under 45.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '1-st map: vici handicap -5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '2-nd map: sparking arrow handicap +5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '2-nd map: total kills over 45.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '2-nd map: total kills under 45.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '2-nd map: vici handicap -5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    'sparking arrow handicap +1.5 maps': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    'sparking arrow will win': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    'total maps over 2.5': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    'total maps under 2.5': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    'vici handicap -1.5 maps': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    'vici will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '\xa0 sparking arrow handicap +4.5 maps': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '\xa0 sparking arrow handicap +6.5 maps': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '\xa0 total maps over 43.5': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '\xa0 total maps over 47.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '\xa0 total maps under 43.5': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '\xa0 total maps under 47.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '\xa0 vici handicap -4.5 maps': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'],
                                    '\xa0 vici handicap -6.5 maps': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)']},
          'spirit breaker - ursa': {'spirit breaker will win': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'], 'ursa will win': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)']},
          'venomancer - witch doctor': {'venomancer will win': ['4.20(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'],
                                        'witch doctor will win': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)']}}}
