bets = {'4 zoomers - infinity': {'1-st map: handicap 4 zoomers -12.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                          '1-st map: handicap infinity +12.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                          '1-st map: total over 47.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                          '1-st map: total under 47.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                          '4 zoomers handicap -0.5 maps': {'1.30': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                          '4 zoomers will win': {'1.30': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                          'draw will win': {'3.78': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                          'infinity handicap +0.5 maps': {'3.30': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                          'infinity will win': {'12.0': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'}},
 '496 - neon': {'496 will win': {'4.50': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)'},
                'neon will win': {'1.18': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)'}},
 '496 - veteran': {'496 will win': {'2.55': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational)'},
                   'draw will win': {'2.05': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational)'},
                   'veteran will win': {'4.20': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational)'}},
 'adversity - army geniuses': {'adversity will win': {'16.0': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational)'},
                               'army geniuses will win': {'1.17': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational)'},
                               'draw will win': {'5.00': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational)'}},
 'anti-mage - tusk': {'anti-mage will win': {'1.05': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'},
                      'tusk will win': {'8.54': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'}},
 'army geniuses - nine': {'army geniuses will win': {'1.55': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational)'},
                          'draw will win': {'2.77': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational)'},
                          'nine will win': {'9.00': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational)'}},
 'beastcoast - infinity': {'1-st map: handicap beastcoast -11.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                           '1-st map: handicap infinity +11.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                           '1-st map: total over 46.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                           '1-st map: total under 46.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                           'beastcoast handicap -0.5 maps': {'1.52': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                           'beastcoast will win': {'1.52': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                           'draw will win': {'2.78': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                           'infinity handicap +0.5 maps': {'2.43': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                           'infinity will win': {'10.0': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'}},
 'bloodseeker - natures prophet': {'bloodseeker will win': {'3.54': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'},
                                   'natures prophet will win': {'1.27': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'}},
 'cdec - royal never give up': {'1-st map: handicap cdec +3.5': {'1.77': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: handicap cdec +4.5': {'1.72': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: handicap cdec -4.5': {'2.31': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: handicap royal never give up +4.5': {'1.57': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: handicap royal never give up -3.5': {'1.97': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: handicap royal never give up -4.5': {'2.05': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: total over 43.5': {'1.70': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: total over 45.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: total over 47.5': {'2.08': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: total under 43.5': {'2.08': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: total under 45.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                '1-st map: total under 47.5': {'1.70': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                'cdec handicap +1.5 maps': {'1.30': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                'cdec will win': {'2.01': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                'royal never give up handicap -1.5 maps': {'3.30': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                'royal never give up will win': {'1.75': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                'total over 2.5': {'1.90': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'},
                                'total under 2.5': {'1.85': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)'}},
 'clinkz - sniper': {'clinkz will win': {'10.1': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'},
                     'sniper will win': {'1.03': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'}},
 'cr4zy - thunder predator': {'1-st map: handicap cr4zy -4.5': {'2.15': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                              '1-st map: handicap thunder predator +4.5': {'1.65': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                              '1-st map: total over 45.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                              '1-st map: total under 45.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                              'cr4zy handicap -0.5 maps': {'3.45': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                              'cr4zy will win': {'3.45': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                              'draw will win': {'1.86': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                              'thunder predator handicap +0.5 maps': {'1.28': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'},
                              'thunder predator will win': {'3.45': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1)'}},
 'disruptor - timbersaw': {'disruptor will win': {'1.75': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'},
                           'timbersaw will win': {'2.01': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'}},
 'execration - veteran': {'execration will win': {'3.90': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)'},
                          'veteran will win': {'1.23': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)'}},
 'five brothers - space': {'five brothers will win': {'1.80': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)'},
                           'space will win': {'1.95': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)'}},
 'flytomoon - virtus.pro': {'1-st map: handicap flytomoon +4.5': {'1.57': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: handicap flytomoon -3.5': {'1.97': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: handicap flytomoon -4.5': {'2.05': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: handicap virtus.pro +3.5': {'1.77': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: handicap virtus.pro +4.5': {'1.72': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: handicap virtus.pro -4.5': {'2.31': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: total over 45.5': {'1.70': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: total over 47.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: total over 49.5': {'2.08': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: total under 45.5': {'2.08': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: total under 47.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            '1-st map: total under 49.5': {'1.70': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            'flytomoon handicap -1.5 maps': {'2.48': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            'flytomoon will win': {'1.75': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            'total over 4.5': {'2.63': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            'total under 4.5': {'1.45': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            'virtus.pro handicap +1.5 maps': {'1.50': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'},
                            'virtus.pro will win': {'2.01': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league)'}},
 'huskar - magnus': {'huskar will win': {'1.50': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'},
                     'magnus will win': {'2.48': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'}},
 'necrophos - vengeful spirit': {'necrophos will win': {'1.25': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'},
                                 'vengeful spirit will win': {'3.71': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'}},
 'neon - reckoning': {'neon will win': {'1.13': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)'},
                      'reckoning will win': {'5.42': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)'}},
 'neon - t1': {'1-st map: handicap neon +3.5': {'1.75': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: handicap neon +4.5': {'1.67': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: handicap neon -4.5': {'2.25': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: handicap t1 +4.5': {'1.60': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: handicap t1 -3.5': {'2.01': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: handicap t1 -4.5': {'2.10': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: total over 50.5': {'1.70': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: total over 52.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: total over 54.5': {'2.08': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: total under 50.5': {'2.08': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: total under 52.5': {'1.87': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               '1-st map: total under 54.5': {'1.70': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               'draw will win': {'1.90': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               'neon handicap +0.5 maps': {'1.30': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               'neon will win': {'3.45': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               't1 handicap -0.5 maps': {'3.30': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'},
               't1 will win': {'3.30': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league)'}},
 'riki - skywrath mage': {'riki will win': {'1.05': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'},
                          'skywrath mage will win': {'8.54': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'}},
 'rockets - space': {'rockets will win': {'1.95': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)'},
                     'space will win': {'1.80': 'parimatch(https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)'}},
 'templar assassin - viper': {'templar assassin will win': {'1.12': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'},
                              'viper will win': {'5.66': 'parimatch(https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)'}}}
