sport = {'dota': {'496 - execration(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)': {'496 will win': '1.30',
                                                                                                                                        'execration will win': '3.30'},
          '496 - pg.barracx(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)': {'496 will win': '1.35',
                                                                                                                                        'pg.barracx will win': '3.05'},
          'anti-mage - tusk(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)': {'anti-mage will win': '1.05',
                                                                                                                               'tusk will win': '8.54'},
          'aster - cdec(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)': {'1-st map: aster handicap +5.5 kills': '1.95',
                                                                                                     '1-st map: cdec handicap -5.5 kills': '1.80',
                                                                                                     '1-st map: total kills over 46.5': '2.05',
                                                                                                     '1-st map: total kills under 46.5': '1.72'},
          'aster - invictus gaming(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)': {'1-st map: aster handicap +6.5 kills': '1.75',
                                                                                                                '1-st map: invictus gaming handicap -6.5 kills': '2.01',
                                                                                                                '1-st map: total kills over 48.5': '2.05',
                                                                                                                '1-st map: total kills under 48.5': '1.72'},
          'aster - psg.lgd(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)': {'1-st map: aster handicap +7.5 kills': '1.95',
                                                                                                        '1-st map: psg.lgd handicap -7.5 kills': '1.80',
                                                                                                        '1-st map: total kills over 48.5': '2.05',
                                                                                                        '1-st map: total kills under 48.5': '1.72'},
          'bloodseeker - natures prophet(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)': {'bloodseeker will win': '5.00',
                                                                                                                                            'natures prophet will win': '1.15'},
          'clinkz - sniper(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)': {'clinkz will win': '10.1',
                                                                                                                              'sniper will win': '1.03'},
          'cobra - panda(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-masters-tournament)': {'cobra will win': '1.76',
                                                                                                                 'panda will win': '2.00'},
          'cr - neon(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)': {'cr will win': '2.80',
                                                                                                                                 'neon will win': '1.40'},
          'crossfire - ffyv2(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-lpl-pro)': {'crossfire will win': '2.75',
                                                                                                          'draw will win': '2.00',
                                                                                                          'ffyv2 will win': '3.90'},
          'disruptor - timbersaw(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)': {'disruptor will win': '1.82',
                                                                                                                                    'timbersaw will win': '1.92'},
          'egoboys - omega(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-2)': {'draw will win': '2.13',
                                                                                                                              'egoboys will win': '2.10',
                                                                                                                              'omega will win': '5.80'},
          'ehome - royal never give up(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-oga-dota-pit-cn)': {'1-st map: ehome handicap +5.5 kills': '1.92',
                                                                                                                            '1-st map: royal never give up handicap -5.5 kills': '1.82',
                                                                                                                            '1-st map: total kills over 46.5': '2.05',
                                                                                                                            '1-st map: total kills under 46.5': '1.72'},
          'execration - starluck.fly(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)': {'execration will win': '1.95',
                                                                                                                         'starluck.fly will win': '1.80'},
          'five brothers - rockets(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)': {'five brothers will win': '1.76',
                                                                                                                              'rockets will win': '2.00'},
          'five brothers - winning(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)': {'five brothers will win': '1.80',
                                                                                                                              'winning will win': '1.95'},
          'future.club - wolf(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)': {'future.club will win': '2.01',
                                                                                                                         'wolf will win': '1.75'},
          'goodfellaz - neon(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-libertango-cup)': {'goodfellaz will win': '4.00',
                                                                                                                 'neon will win': '1.22'},
          'honor - immortal(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-masters-tournament)': {'honor will win': '1.75',
                                                                                                                    'immortal will win': '2.01'},
          'hot pot brother - space(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)': {'hot pot brother will win': '1.97',
                                                                                                                              'space will win': '1.78'},
          'hot pot brother - winning(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)': {'hot pot brother will win': '2.01',
                                                                                                                                'winning will win': '1.75'},
          'huskar - magnus(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)': {'huskar will win': '1.40',
                                                                                                                              'magnus will win': '2.82'},
          'luxor - unknown(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-2)': {'draw will win': '2.17',
                                                                                                                              'luxor will win': '6.40',
                                                                                                                              'unknown will win': '2.00'},
          'luxor - vicious young(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-2)': {'draw will win': '2.09',
                                                                                                                                    'luxor will win': '2.20',
                                                                                                                                    'vicious young will win': '5.40'},
          'necrophos - vengeful spirit(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)': {'necrophos will win': '1.25',
                                                                                                                                          'vengeful spirit will win': '3.71'},
          'neet uprising - oracle.au(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-lpl-pro)': {'draw will win': '2.00',
                                                                                                                  'neet uprising will win': '2.80',
                                                                                                                  'oracle.au will win': '3.80'},
          'neon - reckoning(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)': {'neon will win': '1.13',
                                                                                                                                        'reckoning will win': '5.42'},
          'psg.lgd - royal never give up(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)': {'1-st map: psg.lgd handicap -6.5 kills': '2.01',
                                                                                                                      '1-st map: royal never give up handicap +6.5 kills': '1.75',
                                                                                                                      '1-st map: total kills over 46.5': '2.05',
                                                                                                                      '1-st map: total kills under 46.5': '1.72'},
          'psg.lgd - sirius(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda)': {'1-st map: psg.lgd handicap -10.5 kills': '1.80',
                                                                                                         '1-st map: sirius handicap +10.5 kills': '1.95',
                                                                                                         '1-st map: total kills over 47.5': '2.05',
                                                                                                         '1-st map: total kills under 47.5': '1.72'},
          'reckoning - veteran(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier)': {'reckoning will win': '2.48',
                                                                                                                                           'veteran will win': '1.50'},
          'riki - skywrath mage(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)': {'riki will win': '1.05',
                                                                                                                                   'skywrath mage will win': '8.54'},
          'sincere - vampire(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-masters-tournament)': {'sincere will win': '1.80',
                                                                                                                     'vampire will win': '1.95'},
          'templar assassin - viper(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote)': {'templar assassin will win': '1.12',
                                                                                                                                       'viper will win': '5.66'}}}
