bets = {'cream real betis - sws gaming': {'Match winner Full Time Cream Real Betis': '1.26',
                                   'Match winner Full Time SWS Gaming': '3.60',
                                   'url': 'https://www.favorit.com.ua/en/bets/#event=27096293&tours=1934600,2066945,2452749'},
 'd13 - bren esports': {'Match winner Full Time Bren Esports': '1.90',
                        'Match winner Full Time D13': '1.85',
                        'url': 'https://www.favorit.com.ua/en/bets/#event=27095779&tours=1934600,2066945,2452749'},
 'infinity esports - supremacy gaming': {'Correct Score Full Time 0:2': '7.40',
                                         'Correct Score Full Time 1:2': '5.75',
                                         'Correct Score Full Time 2:0': '2.01',
                                         'Correct Score Full Time 2:1': '3.10',
                                         'Handicap rounds Game 1 Infinity eSports (-3.5)': '1.81',
                                         'Handicap rounds Game 1 Supremacy Gaming (+3.5)': '1.94',
                                         'Handicap winner Full Time Infinity eSports (-1.5)': '2.01',
                                         'Handicap winner Full Time Supremacy Gaming (+1.5)': '1.75',
                                         'Match winner Full Time Infinity eSports': '1.33',
                                         'Match winner Full Time Supremacy Gaming': '3.15',
                                         'Odd / Even Game 1 Even': '1.71',
                                         'Odd / Even Game 1 Odd': '2.06',
                                         'Over/Under Games Full Time Over (2.5)': '2.30',
                                         'Over/Under Games Full Time Under (2.5)': '1.57',
                                         'Total rounds Game 1 Over (26.5)': '1.98',
                                         'Total rounds Game 1 Under (26.5)': '1.77',
                                         'Winner Game 1 Infinity eSports': '1.39',
                                         'Winner Game 1 Supremacy Gaming': '2.87',
                                         'url': 'https://www.favorit.com.ua/en/bets/#event=27093233&tours=1934600,2066945,2452749'},
 'mineros fc esports - estral e-sports': {'Correct Score Full Time 0:2': '9.50',
                                          'Correct Score Full Time 1:2': '7.00',
                                          'Correct Score Full Time 2:0': '1.62',
                                          'Correct Score Full Time 2:1': '3.20',
                                          'Handicap rounds Game 1 Estral E-Sports (+4.5)': '1.86',
                                          'Handicap rounds Game 1 Mineros FC Esports (-4.5)': '1.88',
                                          'Handicap winner Full Time Estral E-Sports (+1.5)': '2.21',
                                          'Handicap winner Full Time Mineros FC Esports (-1.5)': '1.62',
                                          'Match winner Full Time Estral E-Sports': '4.45',
                                          'Match winner Full Time Mineros FC Esports': '1.18',
                                          'Odd / Even Game 1 Even': '1.79',
                                          'Odd / Even Game 1 Odd': '1.95',
                                          'Over/Under Games Full Time Over (2.5)': '2.75',
                                          'Over/Under Games Full Time Under (2.5)': '1.42',
                                          'Total rounds Game 1 Over (26.5)': '2.06',
                                          'Total rounds Game 1 Under (26.5)': '1.68',
                                          'Winner Game 1 Estral E-Sports': '3.35',
                                          'Winner Game 1 Mineros FC Esports': '1.29',
                                          'url': 'https://www.favorit.com.ua/en/bets/#event=27093232&tours=1934600,2066945,2452749'}}
