bets =  {'avez - nexus gaming': {'    1st Map Result         AVEZ To Win   ': '1.57',
                         '    1st Map Result         Nexus Gaming To Win   ': '2.34',
                         '    2nd Map Result         AVEZ To Win   ': '1.57',
                         '    2nd Map Result         Nexus Gaming To Win   ': '2.34',
                         '    Correct Score          AVEZ     (2 - 0)  ': '2.54',
                         '    Correct Score          AVEZ     (2 - 1)  ': '3.10',
                         '    Correct Score          Nexus Gaming     (0 - 2)  ': '5.90',
                         '    Correct Score          Nexus Gaming     (1 - 2)  ': '4.60',
                         '    To Win 1st Map With Handicap By Rounds          AVEZ     (-2.5)  ': '1.78',
                         '    To Win 1st Map With Handicap By Rounds          Nexus Gaming     (+2.5)  ': '1.99',
                         '    To Win 2nd Map With Handicap By Rounds          AVEZ     (-2.5)  ': '1.78',
                         '    To Win 2nd Map With Handicap By Rounds          Nexus Gaming     (+2.5)  ': '1.99',
                         '    To Win Match With Handicap By Maps          AVEZ     (-1.5)  ': '2.54',
                         '    To Win Match With Handicap By Maps          Nexus Gaming     (+1.5)  ': '1.50',
                         '    Total Maps          Over     (2.5)  ': '1.97',
                         '    Total Maps          Under     (2.5)  ': '1.80',
                         '    Total Maps        Even ': '1.80',
                         '    Total Maps        Odd ': '1.97',
                         '    Total Rounds - 1st Map          Over     (26.5)  ': '1.79',
                         '    Total Rounds - 1st Map          Under     (26.5)  ': '1.98',
                         '    Total Rounds - 1st Map        Even ': '1.77',
                         '    Total Rounds - 1st Map        Odd ': '2.01',
                         '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.79',
                         '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.98',
                         '    Total Rounds - 2nd Map        Even ': '1.77',
                         '    Total Rounds - 2nd Map        Odd ': '2.01',
                         'avez will win': '1.46',
                         'nexus gaming will win': '2.72',
                         'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Nine+to+Five/Main+Event/Best+of+3+maps/AVEZ+vs+Nexus+Gaming+-+9757953'},
 'chiefs - vertex': {'    1st Map Result         Chiefs To Win   ': '1.21',
                     '    1st Map Result         VERTEX To Win   ': '4.20',
                     '    2nd Map Result         Chiefs To Win   ': '1.21',
                     '    2nd Map Result         VERTEX To Win   ': '4.20',
                     '    Correct Score          Chiefs     (2 - 0)  ': '1.50',
                     '    Correct Score          Chiefs     (2 - 1)  ': '3.44',
                     '    Correct Score          VERTEX     (0 - 2)  ': '16.50',
                     '    Correct Score          VERTEX     (1 - 2)  ': '11.50',
                     '    To Win 1st Map With Handicap By Rounds          Chiefs     (-5.5)  ': '1.90',
                     '    To Win 1st Map With Handicap By Rounds          VERTEX     (+5.5)  ': '1.86',
                     '    To Win 2nd Map With Handicap By Rounds          Chiefs     (-5.5)  ': '1.90',
                     '    To Win 2nd Map With Handicap By Rounds          VERTEX     (+5.5)  ': '1.86',
                     '    To Win Match With Handicap By Maps          Chiefs     (-1.5)  ': '1.50',
                     '    To Win Match With Handicap By Maps          VERTEX     (+1.5)  ': '2.54',
                     '    To Win Match With Handicap By Rounds          Chiefs     (-11.5)  ': '1.909',
                     '    To Win Match With Handicap By Rounds          VERTEX     (+11.5)  ': '1.87',
                     '    Total Maps          Over     (2.5)  ': '2.85',
                     '    Total Maps          Under     (2.5)  ': '1.41',
                     '    Total Maps        Even ': '1.41',
                     '    Total Maps        Odd ': '2.85',
                     '    Total Rounds          Over     (54.5)  ': '1.88',
                     '    Total Rounds          Under     (54.5)  ': '1.90',
                     '    Total Rounds        Even ': '1.90',
                     '    Total Rounds        Odd ': '1.90',
                     '    Total Rounds - 1st Map          Over     (26.5)  ': '2.13',
                     '    Total Rounds - 1st Map          Under     (26.5)  ': '1.68',
                     '    Total Rounds - 1st Map        Even ': '1.79',
                     '    Total Rounds - 1st Map        Odd ': '1.98',
                     '    Total Rounds - 2nd Map          Over     (26.5)  ': '2.13',
                     '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.68',
                     '    Total Rounds - 2nd Map        Even ': '1.79',
                     '    Total Rounds - 2nd Map        Odd ': '1.98',
                     'chiefs will win': '1.089',
                     'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/DreamHack+Open/Qualification/Best+of+3+maps/Chiefs+vs+VERTEX+-+9764201',
                     'vertex will win': '7.40'},
 'd13 - bren esports': {'    Correct Score          Bren Esports     (0 - 2)  ': '3.78',
                        '    Correct Score          Bren Esports     (1 - 2)  ': '3.62',
                        '    Correct Score          D13     (2 - 0)  ': '3.60',
                        '    Correct Score          D13     (2 - 1)  ': '3.52',
                        '    To Win Match With Handicap By Maps          Bren Esports     (+1.5)  ': '1.28',
                        '    To Win Match With Handicap By Maps          D13     (-1.5)  ': '3.60',
                        '    Total Maps          Over     (2.5)  ': '1.88',
                        '    Total Maps          Under     (2.5)  ': '1.88',
                        '    Total Maps        Even ': '1.88',
                        '    Total Maps        Odd ': '1.88',
                        'bren esports will win': '1.94',
                        'd13 will win': '1.86',
                        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Perfect+World+Asia+League+Summer/Main+Event/Best+of+3+maps/D13+vs+Bren+Esports+-+9764186'},
 'ex-smash - s-gaming': {'    1st Map Result         S-Gaming To Win   ': '2.52',
                         '    1st Map Result         ex-SMASH To Win   ': '1.50',
                         '    2nd Map Result         S-Gaming To Win   ': '2.52',
                         '    2nd Map Result         ex-SMASH To Win   ': '1.50',
                         '    Correct Score          S-Gaming     (0 - 2)  ': '6.80',
                         '    Correct Score          S-Gaming     (1 - 2)  ': '5.00',
                         '    Correct Score          ex-SMASH     (2 - 0)  ': '2.34',
                         '    Correct Score          ex-SMASH     (2 - 1)  ': '3.04',
                         '    To Win 1st Map With Handicap By Rounds          S-Gaming     (+3.5)  ': '1.81',
                         '    To Win 1st Map With Handicap By Rounds          ex-SMASH     (-3.5)  ': '1.952',
                         '    To Win 2nd Map With Handicap By Rounds          S-Gaming     (+3.5)  ': '1.81',
                         '    To Win 2nd Map With Handicap By Rounds          ex-SMASH     (-3.5)  ': '1.952',
                         '    To Win Match With Handicap By Maps          S-Gaming     (+1.5)  ': '1.58',
                         '    To Win Match With Handicap By Maps          ex-SMASH     (-1.5)  ': '2.34',
                         '    Total Maps          Over     (2.5)  ': '2.03',
                         '    Total Maps          Under     (2.5)  ': '1.76',
                         '    Total Maps        Even ': '1.76',
                         '    Total Maps        Odd ': '2.03',
                         '    Total Rounds - 1st Map          Over     (26.5)  ': '1.81',
                         '    Total Rounds - 1st Map          Under     (26.5)  ': '1.952',
                         '    Total Rounds - 1st Map        Even ': '1.77',
                         '    Total Rounds - 1st Map        Odd ': '2.01',
                         '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.81',
                         '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.952',
                         '    Total Rounds - 2nd Map        Even ': '1.77',
                         '    Total Rounds - 2nd Map        Odd ': '2.01',
                         'ex-smash will win': '1.39',
                         's-gaming will win': '3.00',
                         'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Nine+to+Five/Main+Event/Best+of+3+maps/ex-SMASH+vs+S-Gaming+-+9757952'},
 'fate esports - izako boars': {'    1st Map Result         FATE eSports To Win   ': '1.36',
                                '    1st Map Result         Izako Boars To Win   ': '3.04',
                                '    2nd Map Result         FATE eSports To Win   ': '1.36',
                                '    2nd Map Result         Izako Boars To Win   ': '3.04',
                                '    Correct Score          FATE eSports     (2 - 0)  ': '1.90',
                                '    Correct Score          FATE eSports     (2 - 1)  ': '3.02',
                                '    Correct Score          Izako Boars     (0 - 2)  ': '10.50',
                                '    Correct Score          Izako Boars     (1 - 2)  ': '6.60',
                                '    To Win 1st Map With Handicap By Rounds          FATE eSports     (-3.5)  ': '1.72',
                                '    To Win 1st Map With Handicap By Rounds          Izako Boars     (+3.5)  ': '2.07',
                                '    To Win 2nd Map With Handicap By Rounds          FATE eSports     (-3.5)  ': '1.72',
                                '    To Win 2nd Map With Handicap By Rounds          Izako Boars     (+3.5)  ': '2.07',
                                '    To Win Match With Handicap By Maps          FATE eSports     (-1.5)  ': '1.90',
                                '    To Win Match With Handicap By Maps          Izako Boars     (+1.5)  ': '1.87',
                                '    Total Maps          Over     (2.5)  ': '2.26',
                                '    Total Maps          Under     (2.5)  ': '1.61',
                                '    Total Maps        Even ': '1.61',
                                '    Total Maps        Odd ': '2.26',
                                '    Total Rounds - 1st Map          Over     (26.5)  ': '1.90',
                                '    Total Rounds - 1st Map          Under     (26.5)  ': '1.86',
                                '    Total Rounds - 1st Map        Even ': '1.77',
                                '    Total Rounds - 1st Map        Odd ': '2.01',
                                '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.90',
                                '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.86',
                                '    Total Rounds - 2nd Map        Even ': '1.77',
                                '    Total Rounds - 2nd Map        Odd ': '2.01',
                                'fate esports will win': '1.222',
                                'izako boars will win': '4.25',
                                'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Nine+to+Five/Main+Event/Best+of+3+maps/FATE+eSports+vs+Izako+Boars+-+9757950'},
 'frosty - kuusamo.gg': {'frosty will win': '1.27',
                         'kuusamo.gg will win': '3.76',
                         'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Finnish+Esports+League/Main+Event/Best+of+3+maps/Frosty+vs+KUUSAMO.gg+-+9764253'},
 'ground zero - rooster': {'    1st Map Result         Ground Zero To Win   ': '2.32',
                           '    1st Map Result         Rooster To Win   ': '1.58',
                           '    2nd Map Result         Ground Zero To Win   ': '2.32',
                           '    2nd Map Result         Rooster To Win   ': '1.58',
                           '    Correct Score          Ground Zero     (2 - 0)  ': '5.75',
                           '    Correct Score          Ground Zero     (2 - 1)  ': '4.55',
                           '    Correct Score          Rooster     (0 - 2)  ': '2.59',
                           '    Correct Score          Rooster     (1 - 2)  ': '3.08',
                           '    To Win 1st Map With Handicap By Rounds          Ground Zero     (+2.5)  ': '1.97',
                           '    To Win 1st Map With Handicap By Rounds          Rooster     (-2.5)  ': '1.80',
                           '    To Win 2nd Map With Handicap By Rounds          Ground Zero     (+2.5)  ': '1.97',
                           '    To Win 2nd Map With Handicap By Rounds          Rooster     (-2.5)  ': '1.80',
                           '    To Win Match With Handicap By Maps          Ground Zero     (+1.5)  ': '1.48',
                           '    To Win Match With Handicap By Maps          Rooster     (-1.5)  ': '2.59',
                           '    To Win Match With Handicap By Rounds          Ground Zero     (+5.5)  ': '1.93',
                           '    To Win Match With Handicap By Rounds          Rooster     (-5.5)  ': '1.85',
                           '    Total Maps          Over     (2.5)  ': '1.96',
                           '    Total Maps          Under     (2.5)  ': '1.81',
                           '    Total Maps        Even ': '1.81',
                           '    Total Maps        Odd ': '1.96',
                           '    Total Rounds          Over     (65.5)  ': '1.90',
                           '    Total Rounds          Under     (65.5)  ': '1.88',
                           '    Total Rounds        Even ': '1.90',
                           '    Total Rounds        Odd ': '1.90',
                           '    Total Rounds - 1st Map          Over     (26.5)  ': '1.79',
                           '    Total Rounds - 1st Map          Under     (26.5)  ': '1.98',
                           '    Total Rounds - 1st Map        Even ': '1.77',
                           '    Total Rounds - 1st Map        Odd ': '2.01',
                           '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.79',
                           '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.98',
                           '    Total Rounds - 2nd Map        Even ': '1.77',
                           '    Total Rounds - 2nd Map        Odd ': '2.01',
                           'ground zero will win': '2.65',
                           'rooster will win': '1.48',
                           'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/ESEA+Premier+Season/Main+Event/Best+of+3+maps/Ground+Zero+vs+Rooster+-+9764276'},
 'honoris - wizards': {'    1st Map Result         HONORIS To Win   ': '1.43',
                       '    1st Map Result         Wizards To Win   ': '2.74',
                       '    2nd Map Result         HONORIS To Win   ': '1.43',
                       '    2nd Map Result         Wizards To Win   ': '2.74',
                       '    Correct Score          HONORIS     (2 - 0)  ': '2.11',
                       '    Correct Score          HONORIS     (2 - 1)  ': '3.00',
                       '    Correct Score          Wizards     (0 - 2)  ': '8.30',
                       '    Correct Score          Wizards     (1 - 2)  ': '5.65',
                       '    To Win 1st Map With Handicap By Rounds          HONORIS     (-3.5)  ': '1.84',
                       '    To Win 1st Map With Handicap By Rounds          Wizards     (+3.5)  ': '1.92',
                       '    To Win 2nd Map With Handicap By Rounds          HONORIS     (-3.5)  ': '1.84',
                       '    To Win 2nd Map With Handicap By Rounds          Wizards     (+3.5)  ': '1.92',
                       '    To Win Match With Handicap By Maps          HONORIS     (-1.5)  ': '2.11',
                       '    To Win Match With Handicap By Maps          Wizards     (+1.5)  ': '1.70',
                       '    Total Maps          Over     (2.5)  ': '2.12',
                       '    Total Maps          Under     (2.5)  ': '1.69',
                       '    Total Maps        Even ': '1.69',
                       '    Total Maps        Odd ': '2.12',
                       '    Total Rounds - 1st Map          Over     (26.5)  ': '1.85',
                       '    Total Rounds - 1st Map          Under     (26.5)  ': '1.909',
                       '    Total Rounds - 1st Map        Even ': '1.77',
                       '    Total Rounds - 1st Map        Odd ': '2.01',
                       '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.85',
                       '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.909',
                       '    Total Rounds - 2nd Map        Even ': '1.77',
                       '    Total Rounds - 2nd Map        Odd ': '2.01',
                       'honoris will win': '1.30',
                       'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Nine+to+Five/Main+Event/Best+of+3+maps/HONORIS+vs+Wizards+-+9757955',
                       'wizards will win': '3.52'},
 'illuminar - wisla krakow': {'    1st Map Result         Illuminar To Win   ': '1.59',
                              '    1st Map Result         Wisla Krakow To Win   ': '2.30',
                              '    2nd Map Result         Illuminar To Win   ': '1.59',
                              '    2nd Map Result         Wisla Krakow To Win   ': '2.30',
                              '    Correct Score          Illuminar     (2 - 0)  ': '2.61',
                              '    Correct Score          Illuminar     (2 - 1)  ': '3.10',
                              '    Correct Score          Wisla Krakow     (0 - 2)  ': '5.70',
                              '    Correct Score          Wisla Krakow     (1 - 2)  ': '4.50',
                              '    To Win 1st Map With Handicap By Rounds          Illuminar     (-2.5)  ': '1.81',
                              '    To Win 1st Map With Handicap By Rounds          Wisla Krakow     (+2.5)  ': '1.952',
                              '    To Win 2nd Map With Handicap By Rounds          Illuminar     (-2.5)  ': '1.81',
                              '    To Win 2nd Map With Handicap By Rounds          Wisla Krakow     (+2.5)  ': '1.952',
                              '    To Win Match With Handicap By Maps          Illuminar     (-1.5)  ': '2.61',
                              '    To Win Match With Handicap By Maps          Wisla Krakow     (+1.5)  ': '1.47',
                              '    Total Maps          Over     (2.5)  ': '1.96',
                              '    Total Maps          Under     (2.5)  ': '1.81',
                              '    Total Maps        Even ': '1.81',
                              '    Total Maps        Odd ': '1.96',
                              '    Total Rounds - 1st Map          Over     (26.5)  ': '1.78',
                              '    Total Rounds - 1st Map          Under     (26.5)  ': '1.99',
                              '    Total Rounds - 1st Map        Even ': '1.76',
                              '    Total Rounds - 1st Map        Odd ': '2.02',
                              '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.78',
                              '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.99',
                              '    Total Rounds - 2nd Map        Even ': '1.76',
                              '    Total Rounds - 2nd Map        Odd ': '2.02',
                              'illuminar will win': '1.49',
                              'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Nine+to+Five/Main+Event/Best+of+3+maps/Illuminar+vs+Wisla+Krakow+-+9757951',
                              'wisla krakow will win': '2.62'},
 'infinity - supremacy': {'    Correct Score          Infinity     (2 - 0)  ': '2.08',
                          '    Correct Score          Infinity     (2 - 1)  ': '3.02',
                          '    Correct Score          Supremacy     (0 - 2)  ': '8.50',
                          '    Correct Score          Supremacy     (1 - 2)  ': '5.75',
                          '    To Win Match With Handicap By Maps          Infinity     (-1.5)  ': '2.08',
                          '    To Win Match With Handicap By Maps          Supremacy     (+1.5)  ': '1.72',
                          '    Total Maps          Over     (2.5)  ': '2.14',
                          '    Total Maps          Under     (2.5)  ': '1.68',
                          '    Total Maps        Even ': '1.68',
                          '    Total Maps        Odd ': '2.14',
                          'infinity will win': '1.29',
                          'supremacy will win': '3.60',
                          'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/La+Liga+Pro+Division/Main+Event/Best+of+3+maps/Infinity+vs+Supremacy+-+9764250'},
 'ldlc - cr4zy': {'    1st Map Result         CR4ZY To Win   ': '1.81',
                  '    1st Map Result         LDLC To Win   ': '1.952',
                  '    2nd Map Result         CR4ZY To Win   ': '1.81',
                  '    2nd Map Result         LDLC To Win   ': '1.952',
                  '    Correct Score          CR4ZY     (0 - 2)  ': '3.40',
                  '    Correct Score          CR4ZY     (1 - 2)  ': '3.44',
                  '    Correct Score          LDLC     (2 - 0)  ': '4.00',
                  '    Correct Score          LDLC     (2 - 1)  ': '3.72',
                  '    To Win 1st Map With Handicap By Rounds          CR4ZY     (-2.5)  ': '2.07',
                  '    To Win 1st Map With Handicap By Rounds          LDLC     (+2.5)  ': '1.72',
                  '    To Win 2nd Map With Handicap By Rounds          CR4ZY     (-2.5)  ': '2.07',
                  '    To Win 2nd Map With Handicap By Rounds          LDLC     (+2.5)  ': '1.72',
                  '    To Win Match With Handicap By Maps          CR4ZY     (-1.5)  ': '3.40',
                  '    To Win Match With Handicap By Maps          LDLC     (+1.5)  ': '1.30',
                  '    Total Maps          Over     (2.5)  ': '1.88',
                  '    Total Maps          Under     (2.5)  ': '1.88',
                  '    Total Maps        Even ': '1.88',
                  '    Total Maps        Odd ': '1.88',
                  '    Total Rounds - 1st Map          Over     (26.5)  ': '1.75',
                  '    Total Rounds - 1st Map          Under     (26.5)  ': '2.03',
                  '    Total Rounds - 1st Map        Even ': '1.76',
                  '    Total Rounds - 1st Map        Odd ': '2.02',
                  '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.75',
                  '    Total Rounds - 2nd Map          Under     (26.5)  ': '2.03',
                  '    Total Rounds - 2nd Map        Even ': '1.76',
                  '    Total Rounds - 2nd Map        Odd ': '2.02',
                  'cr4zy will win': '1.79',
                  'ldlc will win': '2.03',
                  'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Nine+to+Five/Main+Event/Best+of+3+maps/LDLC+vs+CR4ZY+-+9757954'},
 'lynn vision gaming - huat zai': {'huat zai will win': '3.26',
                                   'lynn vision gaming will win': '1.34',
                                   'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/ThunderFire+Asia+Championships/Main+Event/Best+of+3+maps/Lynn+Vision+Gaming+vs+Huat+Zai+-+9764237'},
 'mineros - estral': {'    Correct Score          Estral     (0 - 2)  ': '9.90',
                      '    Correct Score          Estral     (1 - 2)  ': '6.40',
                      '    Correct Score          Mineros     (2 - 0)  ': '1.94',
                      '    Correct Score          Mineros     (2 - 1)  ': '3.02',
                      '    To Win Match With Handicap By Maps          Estral     (+1.5)  ': '1.83',
                      '    To Win Match With Handicap By Maps          Mineros     (-1.5)  ': '1.94',
                      '    Total Maps          Over     (2.5)  ': '2.23',
                      '    Total Maps          Under     (2.5)  ': '1.63',
                      '    Total Maps        Even ': '1.63',
                      '    Total Maps        Odd ': '2.23',
                      'estral will win': '4.05',
                      'mineros will win': '1.24',
                      'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/La+Liga+Pro+Division/Main+Event/Best+of+3+maps/Mineros+vs+Estral+-+9764249'},
 'onethree - jmt': {'    Correct Score          JMT     (0 - 2)  ': '6.50',
                    '    Correct Score          JMT     (1 - 2)  ': '4.90',
                    '    Correct Score          OneThree     (2 - 0)  ': '2.40',
                    '    Correct Score          OneThree     (2 - 1)  ': '3.04',
                    '    To Win Match With Handicap By Maps          JMT     (+1.5)  ': '1.55',
                    '    To Win Match With Handicap By Maps          OneThree     (-1.5)  ': '2.40',
                    '    Total Maps          Over     (2.5)  ': '2.01',
                    '    Total Maps          Under     (2.5)  ': '1.77',
                    'jmt will win': '2.91',
                    'onethree will win': '1.41',
                    'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/ThunderFire+Asia+Championships/Main+Event/Best+of+3+maps/OneThree+vs+JMT+-+9764236'},
 'order - skyfire': {'    1st Map Result         ORDER To Win   ': '1.21',
                     '    1st Map Result         Skyfire To Win   ': '4.20',
                     '    2nd Map Result         ORDER To Win   ': '1.21',
                     '    2nd Map Result         Skyfire To Win   ': '4.20',
                     '    Correct Score          ORDER     (2 - 0)  ': '1.48',
                     '    Correct Score          ORDER     (2 - 1)  ': '3.48',
                     '    Correct Score          Skyfire     (0 - 2)  ': '17.25',
                     '    Correct Score          Skyfire     (1 - 2)  ': '12.00',
                     '    To Win 1st Map With Handicap By Rounds          ORDER     (-5.5)  ': '1.89',
                     '    To Win 1st Map With Handicap By Rounds          Skyfire     (+5.5)  ': '1.87',
                     '    To Win 2nd Map With Handicap By Rounds          ORDER     (-5.5)  ': '1.89',
                     '    To Win 2nd Map With Handicap By Rounds          Skyfire     (+5.5)  ': '1.87',
                     '    To Win Match With Handicap By Maps          ORDER     (-1.5)  ': '1.48',
                     '    To Win Match With Handicap By Maps          Skyfire     (+1.5)  ': '2.58',
                     '    To Win Match With Handicap By Rounds          ORDER     (-11.5)  ': '1.89',
                     '    To Win Match With Handicap By Rounds          Skyfire     (+11.5)  ': '1.89',
                     '    Total Maps          Over     (2.5)  ': '2.89',
                     '    Total Maps          Under     (2.5)  ': '1.40',
                     '    Total Maps        Even ': '1.40',
                     '    Total Maps        Odd ': '2.89',
                     '    Total Rounds          Over     (54.5)  ': '1.89',
                     '    Total Rounds          Under     (54.5)  ': '1.89',
                     '    Total Rounds        Even ': '1.90',
                     '    Total Rounds        Odd ': '1.90',
                     '    Total Rounds - 1st Map          Over     (26.5)  ': '2.15',
                     '    Total Rounds - 1st Map          Under     (26.5)  ': '1.67',
                     '    Total Rounds - 1st Map        Even ': '1.79',
                     '    Total Rounds - 1st Map        Odd ': '1.98',
                     '    Total Rounds - 2nd Map          Over     (26.5)  ': '2.15',
                     '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.67',
                     '    Total Rounds - 2nd Map        Even ': '1.79',
                     '    Total Rounds - 2nd Map        Odd ': '1.98',
                     'order will win': '1.084',
                     'skyfire will win': '7.70',
                     'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/DreamHack+Open/Qualification/Best+of+3+maps/ORDER+vs+Skyfire+-+9764198'},
 'rooster - mako': {'    1st Map Result         Mako To Win   ': '3.04',
                    '    1st Map Result         Rooster To Win   ': '1.36',
                    '    2nd Map Result         Mako To Win   ': '3.04',
                    '    2nd Map Result         Rooster To Win   ': '1.36',
                    '    Correct Score          Mako     (0 - 2)  ': '10.50',
                    '    Correct Score          Mako     (1 - 2)  ': '6.55',
                    '    Correct Score          Rooster     (2 - 0)  ': '1.90',
                    '    Correct Score          Rooster     (2 - 1)  ': '3.04',
                    '    To Win 1st Map With Handicap By Rounds          Mako     (+4.5)  ': '1.78',
                    '    To Win 1st Map With Handicap By Rounds          Rooster     (-4.5)  ': '1.99',
                    '    To Win 2nd Map With Handicap By Rounds          Mako     (+4.5)  ': '1.78',
                    '    To Win 2nd Map With Handicap By Rounds          Rooster     (-4.5)  ': '1.99',
                    '    To Win Match With Handicap By Maps          Mako     (+1.5)  ': '1.87',
                    '    To Win Match With Handicap By Maps          Rooster     (-1.5)  ': '1.90',
                    '    To Win Match With Handicap By Rounds          Mako     (+9.5)  ': '1.80',
                    '    To Win Match With Handicap By Rounds          Rooster     (-9.5)  ': '1.99',
                    '    Total Maps          Over     (2.5)  ': '2.25',
                    '    Total Maps          Under     (2.5)  ': '1.615',
                    '    Total Maps        Even ': '1.615',
                    '    Total Maps        Odd ': '2.25',
                    '    Total Rounds          Over     (58.5)  ': '1.89',
                    '    Total Rounds          Under     (58.5)  ': '1.89',
                    '    Total Rounds        Even ': '1.90',
                    '    Total Rounds        Odd ': '1.90',
                    '    Total Rounds - 1st Map          Over     (26.5)  ': '1.90',
                    '    Total Rounds - 1st Map          Under     (26.5)  ': '1.86',
                    '    Total Rounds - 1st Map        Even ': '1.78',
                    '    Total Rounds - 1st Map        Odd ': '1.99',
                    '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.90',
                    '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.86',
                    '    Total Rounds - 2nd Map        Even ': '1.78',
                    '    Total Rounds - 2nd Map        Odd ': '1.99',
                    'mako will win': '4.20',
                    'rooster will win': '1.23',
                    'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/DreamHack+Open/Qualification/Best+of+3+maps/Rooster+vs+Mako+-+9764200'},
 'saw - agf': {'    1st Map Result         AGF To Win   ': '2.64',
               '    1st Map Result         sAw To Win   ': '1.46',
               '    2nd Map Result         AGF To Win   ': '2.64',
               '    2nd Map Result         sAw To Win   ': '1.46',
               '    Correct Score          AGF     (0 - 2)  ': '7.70',
               '    Correct Score          AGF     (1 - 2)  ': '5.40',
               '    Correct Score          sAw     (2 - 0)  ': '2.19',
               '    Correct Score          sAw     (2 - 1)  ': '3.02',
               '    To Win 1st Map With Handicap By Rounds          AGF     (+2.5)  ': '2.20',
               '    To Win 1st Map With Handicap By Rounds          sAw     (-2.5)  ': '1.64',
               '    To Win 2nd Map With Handicap By Rounds          AGF     (+2.5)  ': '2.20',
               '    To Win 2nd Map With Handicap By Rounds          sAw     (-2.5)  ': '1.64',
               '    To Win Match With Handicap By Maps          AGF     (+1.5)  ': '1.65',
               '    To Win Match With Handicap By Maps          sAw     (-1.5)  ': '2.19',
               '    Total Maps          Over     (2.5)  ': '2.08',
               '    Total Maps          Under     (2.5)  ': '1.72',
               '    Total Maps        Even ': '1.72',
               '    Total Maps        Odd ': '2.08',
               '    Total Rounds - 1st Map          Over     (26.5)  ': '1.833',
               '    Total Rounds - 1st Map          Under     (26.5)  ': '1.93',
               '    Total Rounds - 1st Map        Even ': '1.77',
               '    Total Rounds - 1st Map        Odd ': '2.01',
               '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.833',
               '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.93',
               '    Total Rounds - 2nd Map        Even ': '1.77',
               '    Total Rounds - 2nd Map        Odd ': '2.01',
               'agf will win': '3.32',
               'saw will win': '1.33',
               'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Nine+to+Five/Main+Event/Best+of+3+maps/sAw+vs+AGF+-+9757948'},
 'sws - cream real betis': {'    1st Map Result         Cream Real Betis To Win   ': '1.43',
                            '    1st Map Result         SWS To Win   ': '2.74',
                            '    2nd Map Result         Cream Real Betis To Win   ': '1.43',
                            '    2nd Map Result         SWS To Win   ': '2.74',
                            '    Correct Score          Cream Real Betis     (0 - 2)  ': '2.12',
                            '    Correct Score          Cream Real Betis     (1 - 2)  ': '3.02',
                            '    Correct Score          SWS     (2 - 0)  ': '8.20',
                            '    Correct Score          SWS     (2 - 1)  ': '5.60',
                            '    To Win 1st Map With Handicap By Rounds          Cream Real Betis     (-3.5)  ': '1.85',
                            '    To Win 1st Map With Handicap By Rounds          SWS     (+3.5)  ': '1.909',
                            '    To Win 2nd Map With Handicap By Rounds          Cream Real Betis     (-3.5)  ': '1.85',
                            '    To Win 2nd Map With Handicap By Rounds          SWS     (+3.5)  ': '1.909',
                            '    To Win Match With Handicap By Maps          Cream Real Betis     (-1.5)  ': '2.12',
                            '    To Win Match With Handicap By Maps          SWS     (+1.5)  ': '1.69',
                            '    Total Maps          Over     (2.5)  ': '2.11',
                            '    Total Maps          Under     (2.5)  ': '1.70',
                            '    Total Maps        Even ': '1.70',
                            '    Total Maps        Odd ': '2.11',
                            '    Total Rounds - 1st Map          Over     (26.5)  ': '1.85',
                            '    Total Rounds - 1st Map          Under     (26.5)  ': '1.909',
                            '    Total Rounds - 1st Map        Even ': '1.77',
                            '    Total Rounds - 1st Map        Odd ': '2.01',
                            '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.85',
                            '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.909',
                            '    Total Rounds - 2nd Map        Even ': '1.77',
                            '    Total Rounds - 2nd Map        Odd ': '2.01',
                            'cream real betis will win': '1.31',
                            'sws will win': '3.45',
                            'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/CLUTCH/Main+Event/Best+of+3+maps/SWS+vs+Cream+Real+Betis+-+9764063'},
 'syman - adaptation': {'    1st Map Result         Adaptation To Win   ': '3.54',
                        '    1st Map Result         Syman To Win   ': '1.28',
                        '    2nd Map Result         Adaptation To Win   ': '3.54',
                        '    2nd Map Result         Syman To Win   ': '1.28',
                        '    Correct Score          Adaptation     (0 - 2)  ': '12.75',
                        '    Correct Score          Adaptation     (1 - 2)  ': '8.90',
                        '    Correct Score          Syman     (2 - 0)  ': '1.66',
                        '    Correct Score          Syman     (2 - 1)  ': '3.22',
                        '    To Win 1st Map With Handicap By Rounds          Adaptation     (+4.5)  ': '1.952',
                        '    To Win 1st Map With Handicap By Rounds          Syman     (-4.5)  ': '1.81',
                        '    To Win 2nd Map With Handicap By Rounds          Adaptation     (+4.5)  ': '1.952',
                        '    To Win 2nd Map With Handicap By Rounds          Syman     (-4.5)  ': '1.81',
                        '    To Win Match With Handicap By Maps          Adaptation     (+1.5)  ': '2.17',
                        '    To Win Match With Handicap By Maps          Syman     (-1.5)  ': '1.66',
                        '    Total Maps          Over     (2.5)  ': '2.51',
                        '    Total Maps          Under     (2.5)  ': '1.51',
                        '    Total Maps        Even ': '1.51',
                        '    Total Maps        Odd ': '2.51',
                        '    Total Rounds - 1st Map          Over     (26.5)  ': '2.01',
                        '    Total Rounds - 1st Map          Under     (26.5)  ': '1.77',
                        '    Total Rounds - 1st Map        Even ': '1.78',
                        '    Total Rounds - 1st Map        Odd ': '1.99',
                        '    Total Rounds - 2nd Map          Over     (26.5)  ': '2.01',
                        '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.77',
                        '    Total Rounds - 2nd Map        Even ': '1.78',
                        '    Total Rounds - 2nd Map        Odd ': '1.99',
                        'adaptation will win': '5.60',
                        'syman will win': '1.143',
                        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Nine+to+Five/Main+Event/Best+of+3+maps/Syman+vs+Adaptation+-+9757949'},
 'third impact - valkyrie': {'    Correct Score          Third Impact     (2 - 0)  ': '2.20',
                             '    Correct Score          Third Impact     (2 - 1)  ': '3.00',
                             '    Correct Score          Valkyrie     (0 - 2)  ': '7.60',
                             '    Correct Score          Valkyrie     (1 - 2)  ': '5.40',
                             '    To Win Match With Handicap By Maps          Third Impact     (-1.5)  ': '2.20',
                             '    To Win Match With Handicap By Maps          Valkyrie     (+1.5)  ': '1.65',
                             '    Total Maps          Over     (2.5)  ': '2.08',
                             '    Total Maps          Under     (2.5)  ': '1.72',
                             '    Total Maps        Even ': '1.72',
                             '    Total Maps        Odd ': '2.08',
                             'third impact will win': '1.34',
                             'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/WINNERS+League/Main+Event/Best+of+3+maps/Third+Impact+vs+Valkyrie+-+9752583',
                             'valkyrie will win': '3.26'},
 'tiger - vici gaming': {'    Correct Score          TIGER     (2 - 0)  ': '6.25',
                         '    Correct Score          TIGER     (2 - 1)  ': '4.75',
                         '    Correct Score          Vici Gaming     (0 - 2)  ': '2.46',
                         '    Correct Score          Vici Gaming     (1 - 2)  ': '3.05',
                         '    To Win Match With Handicap By Maps          TIGER     (+1.5)  ': '1.53',
                         '    To Win Match With Handicap By Maps          Vici Gaming     (-1.5)  ': '2.46',
                         '    Total Maps          Over     (2.5)  ': '1.99',
                         '    Total Maps          Under     (2.5)  ': '1.79',
                         '    Total Maps        Even ': '1.79',
                         '    Total Maps        Odd ': '1.99',
                         'tiger will win': '2.83',
                         'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Perfect+World+Asia+League+Summer/Main+Event/Best+of+3+maps/TIGER+vs+Vici+Gaming+-+9764188',
                         'vici gaming will win': '1.43'},
 'triumph - yeah!': {'    Correct Score          Triumph     (2 - 0)  ': '2.30',
                     '    Correct Score          Triumph     (2 - 1)  ': '3.02',
                     '    Correct Score          YeaH!     (0 - 2)  ': '7.00',
                     '    Correct Score          YeaH!     (1 - 2)  ': '5.10',
                     '    To Win Match With Handicap By Maps          Triumph     (-1.5)  ': '2.30',
                     '    To Win Match With Handicap By Maps          YeaH!     (+1.5)  ': '1.59',
                     '    Total Maps          Over     (2.5)  ': '2.04',
                     '    Total Maps          Under     (2.5)  ': '1.75',
                     '    Total Maps        Even ': '1.75',
                     '    Total Maps        Odd ': '2.04',
                     'triumph will win': '1.37',
                     'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/WINNERS+League/Main+Event/Best+of+3+maps/Triumph+vs+YeaH%21+-+9758011',
                     'yeah! will win': '3.10'},
 'truckers with attitude - ground zero': {'    1st Map Result         Ground Zero To Win   ': '1.52',
                                          '    1st Map Result         TRUCKERS WITH ATTITUDE To Win   ': '2.46',
                                          '    2nd Map Result         Ground Zero To Win   ': '1.52',
                                          '    2nd Map Result         TRUCKERS WITH ATTITUDE To Win   ': '2.46',
                                          '    Correct Score          Ground Zero     (0 - 2)  ': '2.375',
                                          '    Correct Score          Ground Zero     (1 - 2)  ': '3.04',
                                          '    Correct Score          TRUCKERS WITH ATTITUDE     (2 - 0)  ': '6.60',
                                          '    Correct Score          TRUCKERS WITH ATTITUDE     (2 - 1)  ': '4.95',
                                          '    To Win 1st Map With Handicap By Rounds          Ground Zero     (-3.5)  ': '1.98',
                                          '    To Win 1st Map With Handicap By Rounds          TRUCKERS WITH ATTITUDE     (+3.5)  ': '1.79',
                                          '    To Win 2nd Map With Handicap By Rounds          Ground Zero     (-3.5)  ': '1.98',
                                          '    To Win 2nd Map With Handicap By Rounds          TRUCKERS WITH ATTITUDE     (+3.5)  ': '1.79',
                                          '    To Win Match With Handicap By Maps          Ground Zero     (-1.5)  ': '2.375',
                                          '    To Win Match With Handicap By Maps          TRUCKERS WITH ATTITUDE     (+1.5)  ': '1.56',
                                          '    To Win Match With Handicap By Rounds          Ground Zero     (-6.5)  ': '1.86',
                                          '    To Win Match With Handicap By Rounds          TRUCKERS WITH ATTITUDE     (+6.5)  ': '1.92',
                                          '    Total Maps          Over     (2.5)  ': '2.02',
                                          '    Total Maps          Under     (2.5)  ': '1.76',
                                          '    Total Maps        Even ': '1.76',
                                          '    Total Maps        Odd ': '2.02',
                                          '    Total Rounds          Over     (63.5)  ': '1.89',
                                          '    Total Rounds          Under     (63.5)  ': '1.89',
                                          '    Total Rounds        Even ': '1.90',
                                          '    Total Rounds        Odd ': '1.90',
                                          '    Total Rounds - 1st Map          Over     (26.5)  ': '1.81',
                                          '    Total Rounds - 1st Map          Under     (26.5)  ': '1.952',
                                          '    Total Rounds - 1st Map        Even ': '1.77',
                                          '    Total Rounds - 1st Map        Odd ': '2.01',
                                          '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.81',
                                          '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.952',
                                          '    Total Rounds - 2nd Map        Even ': '1.77',
                                          '    Total Rounds - 2nd Map        Odd ': '2.01',
                                          'ground zero will win': '1.40',
                                          'truckers with attitude will win': '2.95',
                                          'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/DreamHack+Open/Qualification/Best+of+3+maps/TRUCKERS+WITH+ATTITUDE+vs+Ground+Zero+-+9764199'},
 'tyloo - beyond': {'    Correct Score          Beyond     (0 - 2)  ': '11.75',
                    '    Correct Score          Beyond     (1 - 2)  ': '7.10',
                    '    Correct Score          TyLoo     (2 - 0)  ': '1.82',
                    '    Correct Score          TyLoo     (2 - 1)  ': '3.04',
                    '    To Win Match With Handicap By Maps          Beyond     (+1.5)  ': '1.95',
                    '    To Win Match With Handicap By Maps          TyLoo     (-1.5)  ': '1.82',
                    '    Total Maps          Over     (2.5)  ': '2.33',
                    '    Total Maps          Under     (2.5)  ': '1.58',
                    '    Total Maps        Even ': '1.58',
                    '    Total Maps        Odd ': '2.33',
                    'beyond will win': '4.60',
                    'tyloo will win': '1.196',
                    'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Perfect+World+Asia+League+Summer/Main+Event/Best+of+3+maps/TyLoo+vs+Beyond+-+9764187'},
 'vitality - big': {'    2nd Map Result         BIG To Win   ': '2.41',
                    '    2nd Map Result         Vitality To Win   ': '1.54',
                    '    3rd Map Result         BIG To Win   ': '2.41',
                    '    3rd Map Result         Vitality To Win   ': '1.54',
                    '    Correct Score          BIG     (1 - 3)  ': '5.70',
                    '    Correct Score          BIG     (2 - 3)  ': '4.65',
                    '    Correct Score          Vitality     (3 - 0)  ': '3.32',
                    '    Correct Score          Vitality     (3 - 1)  ': '3.62',
                    '    Correct Score          Vitality     (3 - 2)  ': '4.80',
                    '    To Win 2nd Map With Handicap By Rounds          BIG     (+3.5)  ': '1.76',
                    '    To Win 2nd Map With Handicap By Rounds          Vitality     (-3.5)  ': '2.02',
                    '    To Win 3rd Map With Handicap By Rounds          BIG     (+3.5)  ': '1.76',
                    '    To Win 3rd Map With Handicap By Rounds          Vitality     (-3.5)  ': '2.02',
                    '    To Win Match With Handicap By Maps          BIG     (+1.5)  ': '1.93',
                    '    To Win Match With Handicap By Maps          BIG     (+2.5)  ': '1.30',
                    '    To Win Match With Handicap By Maps          BIG     (-1.5)  ': '5.65',
                    '    To Win Match With Handicap By Maps          Vitality     (+1.5)  ': '1.12',
                    '    To Win Match With Handicap By Maps          Vitality     (-1.5)  ': '1.83',
                    '    To Win Match With Handicap By Maps          Vitality     (-2.5)  ': '3.32',
                    '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.80',
                    '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.97',
                    '    Total Rounds - 2nd Map        Even ': '1.77',
                    '    Total Rounds - 2nd Map        Odd ': '2.01',
                    '    Total Rounds - 3rd Map          Over     (26.5)  ': '1.80',
                    '    Total Rounds - 3rd Map          Under     (26.5)  ': '1.97',
                    '    Total Rounds - 3rd Map        Even ': '1.77',
                    '    Total Rounds - 3rd Map        Odd ': '2.01',
                    'big will win': '2.91',
                    'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Summit/Grand+Final/Best+of+5+maps/Vitality+vs+BIG+-+9766362',
                    'vitality will win': '1.41'}}
