bets = {'ambush - tricked': {'1x2. 1 map. Ambush': '1.86',
                      '1x2. 1 map. Tricked': '1.89',
                      '1x2. 2 map. Ambush': '1.87',
                      '1x2. 2 map. Tricked': '1.88',
                      '1x2. Ambush': '1.87',
                      '1x2. Tricked': '1.9',
                      'Handicap. 1 map. Handiсap Ambush (+2.5)': '1.55',
                      'Handicap. 1 map. Handiсap Ambush (+3.5)': '1.43',
                      'Handicap. 1 map. Handiсap Ambush (+4.5)': '1.33',
                      'Handicap. 1 map. Handiсap Ambush (-2.5)': '2.35',
                      'Handicap. 1 map. Handiсap Ambush (-3.5)': '2.7',
                      'Handicap. 1 map. Handiсap Ambush (-4.5)': '3.14',
                      'Handicap. 1 map. Handiсap Tricked (+2.5)': '1.55',
                      'Handicap. 1 map. Handiсap Tricked (+3.5)': '1.43',
                      'Handicap. 1 map. Handiсap Tricked (+4.5)': '1.33',
                      'Handicap. 1 map. Handiсap Tricked (-2.5)': '2.35',
                      'Handicap. 1 map. Handiсap Tricked (-3.5)': '2.7',
                      'Handicap. 1 map. Handiсap Tricked (-4.5)': '3.14',
                      'Handicap. 2 map. ': '',
                      'Handicap. 2 map. Handiсap Ambush (+2.5)': '1.56',
                      'Handicap. 2 map. Handiсap Ambush (+3.5)': '1.44',
                      'Handicap. 2 map. Handiсap Ambush (-2.5)': '2.35',
                      'Handicap. 2 map. Handiсap Ambush (-3.5)': '2.7',
                      'Handicap. 2 map. Handiсap Ambush (-4.5)': '3.14',
                      'Handicap. 2 map. Handiсap Tricked (+2.5)': '1.55',
                      'Handicap. 2 map. Handiсap Tricked (+3.5)': '1.43',
                      'Handicap. 2 map. Handiсap Tricked (+4.5)': '1.33',
                      'Handicap. 2 map. Handiсap Tricked (-2.5)': '2.33',
                      'Handicap. 2 map. Handiсap Tricked (-3.5)': '2.66',
                      'Total Maps Even/Odd. Total Maps - Even': '1.85',
                      'Total Maps Even/Odd. Total Maps - Odd': '1.89',
                      'Total Maps Handicap. Ambush Handicap -1.5 Maps': '3.32',
                      'Total Maps Handicap. Ambush Handicap 1.5 Maps': '1.3',
                      'Total Maps Handicap. Tricked Handicap -1.5 Maps': '3.32',
                      'Total Maps Handicap. Tricked Handicap 1.5 Maps': '1.3',
                      'Total Maps. Total Maps Over 2.5': '1.89',
                      'Total Maps. Total Maps Under 2.5': '1.85',
                      'Total. 1 map. Total Over 24.5': '1.32',
                      'Total. 1 map. Total Over 25.5': '1.49',
                      'Total. 1 map. Total Over 26.5': '1.73',
                      'Total. 1 map. Total Over 27.5': '2.11',
                      'Total. 1 map. Total Over 28.5': '2.73',
                      'Total. 1 map. Total Under 24.5': '3.2',
                      'Total. 1 map. Total Under 25.5': '2.51',
                      'Total. 1 map. Total Under 26.5': '2.03',
                      'Total. 1 map. Total Under 27.5': '1.68',
                      'Total. 1 map. Total Under 28.5': '1.42',
                      'Total. 2 map. Total Over 24.5': '1.32',
                      'Total. 2 map. Total Over 25.5': '1.49',
                      'Total. 2 map. Total Over 26.5': '1.74',
                      'Total. 2 map. Total Over 27.5': '2.11',
                      'Total. 2 map. Total Over 28.5': '2.73',
                      'Total. 2 map. Total Under 24.5': '3.2',
                      'Total. 2 map. Total Under 25.5': '2.51',
                      'Total. 2 map. Total Under 26.5': '2.02',
                      'Total. 2 map. Total Under 27.5': '1.68',
                      'Total. 2 map. Total Under 28.5': '1.42',
                      'Win In Round. 1 map. Ambush Will Win In Round 1': '1.87',
                      'Win In Round. 1 map. Ambush Will Win In Round 16': '1.87',
                      'Win In Round. 1 map. Tricked Will Win In Round 1': '1.87',
                      'Win In Round. 1 map. Tricked Will Win In Round 16': '1.87',
                      'Win In Round. 2 map. ': '',
                      'Win In Round. 2 map. Ambush Will Win In Round 1': '1.87',
                      'Win In Round. 2 map. Tricked Will Win In Round 1': '1.87',
                      'url': 'https://1x-bet.com/en/line/Esports/2091676-CSGO-ESEA-Advanced-Season-34-Europe/78776229-Ambush-Tricked/'},
 'apeks - winstrike': {'. ': '',
                       '1x2. 1 map. Apeks': '2.125',
                       '1x2. 1 map. Winstrike': '1.68',
                       '1x2. 2 map. Apeks': '2.125',
                       '1x2. 2 map. Winstrike': '1.68',
                       '1x2. Apeks': '2.225',
                       '1x2. Winstrike': '1.632',
                       'Handicap. 1 map. Handiсap Apeks (+2.5)': '1.71',
                       'Handicap. 1 map. Handiсap Apeks (+3.5)': '1.56',
                       'Handicap. 1 map. Handiсap Apeks (+4.5)': '1.43',
                       'Handicap. 1 map. Handiсap Apeks (+5.5)': '1.32',
                       'Handicap. 1 map. Handiсap Apeks (+6.5)': '1.23',
                       'Handicap. 1 map. Handiсap Apeks (-2.5)': '2.7',
                       'Handicap. 1 map. Handiсap Apeks (-3.5)': '3.14',
                       'Handicap. 1 map. Handiсap Apeks (-4.5)': '3.7',
                       'Handicap. 1 map. Handiсap Winstrike (+2.5)': '1.43',
                       'Handicap. 1 map. Handiсap Winstrike (+3.5)': '1.33',
                       'Handicap. 1 map. Handiсap Winstrike (+4.5)': '1.25',
                       'Handicap. 1 map. Handiсap Winstrike (-2.5)': '2.06',
                       'Handicap. 1 map. Handiсap Winstrike (-3.5)': '2.33',
                       'Handicap. 1 map. Handiсap Winstrike (-4.5)': '2.7',
                       'Handicap. 1 map. Handiсap Winstrike (-5.5)': '3.2',
                       'Handicap. 1 map. Handiсap Winstrike (-6.5)': '3.88',
                       'Handicap. 2 map. ': '',
                       'Handicap. 2 map. Handiсap Apeks (-2.5)': '2.73',
                       'Handicap. 2 map. Handiсap Apeks (-3.5)': '3.14',
                       'Handicap. 2 map. Handiсap Apeks (-4.5)': '3.7',
                       'Handicap. 2 map. Handiсap Winstrike (+2.5)': '1.42',
                       'Handicap. 2 map. Handiсap Winstrike (+3.5)': '1.33',
                       'Handicap. 2 map. Handiсap Winstrike (+4.5)': '1.25',
                       'Total Maps Even/Odd. Total Maps - Even': '1.76',
                       'Total Maps Even/Odd. Total Maps - Odd': '1.99',
                       'Total Maps Handicap. Apeks Handicap -1.5 Maps': '4.22',
                       'Total Maps Handicap. Apeks Handicap 1.5 Maps': '1.43',
                       'Total Maps Handicap. Winstrike Handicap -1.5 Maps': '2.7',
                       'Total Maps Handicap. Winstrike Handicap 1.5 Maps': '1.2',
                       'Total Maps. Total Maps Over 2.5': '1.99',
                       'Total Maps. Total Maps Under 2.5': '1.76',
                       'Total. 1 map. Total Over 23.5': '1.2',
                       'Total. 1 map. Total Over 24.5': '1.32',
                       'Total. 1 map. Total Over 25.5': '1.49',
                       'Total. 1 map. Total Over 26.5': '1.75',
                       'Total. 1 map. Total Over 27.5': '2.12',
                       'Total. 1 map. Total Over 28.5': '2.77',
                       'Total. 1 map. Total Over 29.5': '3.88',
                       'Total. 1 map. Total Under 23.5': '4.22',
                       'Total. 1 map. Total Under 24.5': '3.2',
                       'Total. 1 map. Total Under 25.5': '2.51',
                       'Total. 1 map. Total Under 26.5': '2.01',
                       'Total. 1 map. Total Under 27.5': '1.67',
                       'Total. 1 map. Total Under 28.5': '1.41',
                       'Total. 1 map. Total Under 29.5': '1.23',
                       'Total. 2 map. ': '',
                       'Total. 2 map. Total Over 23.5': '1.2',
                       'Total. 2 map. Total Over 24.5': '1.32',
                       'Total. 2 map. Total Over 25.5': '1.5',
                       'Total. 2 map. Total Over 26.5': '1.75',
                       'Total. 2 map. Total Over 27.5': '2.12',
                       'Total. 2 map. Total Under 23.5': '4.22',
                       'Total. 2 map. Total Under 24.5': '3.2',
                       'Total. 2 map. Total Under 25.5': '2.48',
                       'Total. 2 map. Total Under 26.5': '2.01',
                       'Total. 2 map. Total Under 27.5': '1.67',
                       'Win In Round. 1 map. Apeks Will Win In Round 1': '1.9',
                       'Win In Round. 1 map. Apeks Will Win In Round 16': '1.9',
                       'Win In Round. 1 map. Winstrike Will Win In Round 1': '1.84',
                       'Win In Round. 1 map. Winstrike Will Win In Round 16': '1.84',
                       'url': 'https://1x-bet.com/en/line/Esports/2091676-CSGO-ESEA-Advanced-Season-34-Europe/78760631-Apeks-Winstrike/'},
 'avez - nexus gaming': {'. ': '',
                         '1x2. 1 map. AVEZ': '1.59',
                         '1x2. 1 map. Nexus Gaming': '2.28',
                         '1x2. AVEZ': '1.47',
                         '1x2. Nexus Gaming': '2.616',
                         'Handicap. 1 map. Handiсap AVEZ (+2.5)': '1.37',
                         'Handicap. 1 map. Handiсap AVEZ (+3.5)': '1.29',
                         'Handicap. 1 map. Handiсap AVEZ (+4.5)': '1.22',
                         'Handicap. 1 map. Handiсap AVEZ (-2.5)': '1.91',
                         'Handicap. 1 map. Handiсap AVEZ (-3.5)': '2.14',
                         'Handicap. 1 map. Handiсap AVEZ (-4.5)': '2.45',
                         'Handicap. 1 map. Handiсap AVEZ (-5.5)': '2.9',
                         'Handicap. 1 map. Handiсap AVEZ (-6.5)': '3.46',
                         'Handicap. 1 map. Handiсap Nexus Gaming (+2.5)': '1.83',
                         'Handicap. 1 map. Handiсap Nexus Gaming (+3.5)': '1.66',
                         'Handicap. 1 map. Handiсap Nexus Gaming (+4.5)': '1.51',
                         'Handicap. 1 map. Handiсap Nexus Gaming (+5.5)': '1.38',
                         'Handicap. 1 map. Handiсap Nexus Gaming (+6.5)': '1.28',
                         'Handicap. 1 map. Handiсap Nexus Gaming (-2.5)': '2.94',
                         'Handicap. 1 map. Handiсap Nexus Gaming (-3.5)': '3.38',
                         'Handicap. 1 map. Handiсap Nexus Gaming (-4.5)': '3.98',
                         'Total 1. 1 map. Individual Total 1 Over 11.5': '1.205',
                         'Total 1. 1 map. Individual Total 1 Over 13.5': '1.344',
                         'Total 1. 1 map. Individual Total 1 Under 11.5': '3.98',
                         'Total 1. 1 map. Individual Total 1 Under 13.5': '2.94',
                         'Total 2. 1 map. Individual Total 2 Over 10.5': '1.352',
                         'Total 2. 1 map. Individual Total 2 Over 11.5': '1.475',
                         'Total 2. 1 map. Individual Total 2 Over 12.5': '1.615',
                         'Total 2. 1 map. Individual Total 2 Over 13.5': '1.77',
                         'Total 2. 1 map. Individual Total 2 Over 14.5': '1.975',
                         'Total 2. 1 map. Individual Total 2 Over 9.5': '1.26',
                         'Total 2. 1 map. Individual Total 2 Under 10.5': '2.9',
                         'Total 2. 1 map. Individual Total 2 Under 11.5': '2.45',
                         'Total 2. 1 map. Individual Total 2 Under 12.5': '2.14',
                         'Total 2. 1 map. Individual Total 2 Under 13.5': '1.91',
                         'Total 2. 1 map. Individual Total 2 Under 14.5': '1.72',
                         'Total 2. 1 map. Individual Total 2 Under 9.5': '3.46',
                         'Total Maps Even/Odd. Total Maps - Even': '1.65',
                         'Total Maps Even/Odd. Total Maps - Odd': '2.152',
                         'Total Maps Handicap. AVEZ Handicap -1.5 Maps': '2.35',
                         'Total Maps Handicap. AVEZ Handicap 1.5 Maps': '1.18',
                         'Total Maps Handicap. Nexus Gaming Handicap -1.5 Maps': '4.48',
                         'Total Maps Handicap. Nexus Gaming Handicap 1.5 Maps': '1.544',
                         'Total Maps. Total Maps Over 2.5': '2.16',
                         'Total Maps. Total Maps Under 2.5': '1.65',
                         'Total. 1 map. Total Over 23.5': '1.23',
                         'Total. 1 map. Total Over 24.5': '1.36',
                         'Total. 1 map. Total Over 25.5': '1.55',
                         'Total. 1 map. Total Over 26.5': '1.82',
                         'Total. 1 map. Total Over 27.5': '2.23',
                         'Total. 1 map. Total Over 28.5': '2.9',
                         'Total. 1 map. Total Over 29.5': '4.1',
                         'Total. 1 map. Total Under 23.5': '3.88',
                         'Total. 1 map. Total Under 24.5': '2.99',
                         'Total. 1 map. Total Under 25.5': '2.35',
                         'Total. 1 map. Total Under 26.5': '1.92',
                         'Total. 1 map. Total Under 27.5': '1.61',
                         'Total. 1 map. Total Under 28.5': '1.38',
                         'Total. 1 map. Total Under 29.5': '1.21',
                         'Win In Round. 1 map. AVEZ Will Win In Round 1': '1.83',
                         'Win In Round. 1 map. AVEZ Will Win In Round 16': '1.83',
                         'Win In Round. 1 map. Nexus Gaming Will Win In Round 1': '1.91',
                         'Win In Round. 1 map. Nexus Gaming Will Win In Round 16': '1.91',
                         'url': 'https://1x-bet.com/en/line/Esports/2107656-CSGO-Nine-to-Five-Dawn/78698527-AVEZ-Nexus-Gaming/'},
 'cool - exploit esports': {'1x2. 1 map. Exploit Esports': '1.27',
                            '1x2. 1 map. cooL': '3.58',
                            '1x2. Exploit Esports': '1.28',
                            '1x2. cooL': '3.56',
                            'url': 'https://1x-bet.com/en/line/Esports/2109546-CSGO-Betano-Masters-Season-1-Europe/78805548-cooL-Exploit-Esports/'},
 'cool - unicorns of love': {'1x2. 1 map. Unicorns Of Love': '1.15',
                             '1x2. 1 map. cooL': '5.05',
                             '1x2. Unicorns Of Love': '1.152',
                             '1x2. cooL': '5.1',
                             'url': 'https://1x-bet.com/en/line/Esports/2109546-CSGO-Betano-Masters-Season-1-Europe/78805550-cooL-Unicorns-Of-Love/'},
 'evil geniuses - gen.g': {'. ': '',
                           '1x2. 2 map. Evil Geniuses': '1.53',
                           '1x2. 2 map. Gen.G': '2.42',
                           '1x2. Evil Geniuses': '1.21',
                           '1x2. Gen.G': '4.22',
                           'Handicap. 2 map. Handiсap Evil Geniuses (+2.5)': '1.33',
                           'Handicap. 2 map. Handiсap Evil Geniuses (+3.5)': '1.26',
                           'Handicap. 2 map. Handiсap Evil Geniuses (-2.5)': '1.81',
                           'Handicap. 2 map. Handiсap Evil Geniuses (-3.5)': '2.03',
                           'Handicap. 2 map. Handiсap Evil Geniuses (-4.5)': '2.31',
                           'Handicap. 2 map. Handiсap Evil Geniuses (-5.5)': '2.7',
                           'Handicap. 2 map. Handiсap Evil Geniuses (-6.5)': '3.2',
                           'Handicap. 2 map. Handiсap Evil Geniuses (-7.5)': '3.98',
                           'Handicap. 2 map. Handiсap Gen.G (+2.5)': '1.93',
                           'Handicap. 2 map. Handiсap Gen.G (+3.5)': '1.73',
                           'Handicap. 2 map. Handiсap Gen.G (+4.5)': '1.57',
                           'Handicap. 2 map. Handiсap Gen.G (+5.5)': '1.43',
                           'Handicap. 2 map. Handiсap Gen.G (+6.5)': '1.32',
                           'Handicap. 2 map. Handiсap Gen.G (+7.5)': '1.22',
                           'Handicap. 2 map. Handiсap Gen.G (-2.5)': '3.14',
                           'Handicap. 2 map. Handiсap Gen.G (-3.5)': '3.62',
                           'Total 1. 2 map. Individual Total 1 Over 12.5': '1.24',
                           'Total 1. 2 map. Individual Total 1 Over 14.5': '1.38',
                           'Total 1. 2 map. Individual Total 1 Under 12.5': '3.62',
                           'Total 1. 2 map. Individual Total 1 Under 14.5': '2.77',
                           'Total 2. 2 map. ': '',
                           'Total 2. 2 map. Individual Total 2 Over 8.5': '1.205',
                           'Total 2. 2 map. Individual Total 2 Under 8.5': '3.98',
                           'Total Maps Handicap. Evil Geniuses Handicap -1.5 Maps': '1.416',
                           'Total Maps Handicap. Evil Geniuses Handicap -2.5 Maps': '2.184',
                           'Total Maps Handicap. Evil Geniuses Handicap 1.5 Maps': '1.06',
                           'Total Maps Handicap. Gen.G Handicap -1.5 Maps': '7.9',
                           'Total Maps Handicap. Gen.G Handicap 1.5 Maps': '2.73',
                           'Total Maps Handicap. Gen.G Handicap 2.5 Maps': '1.63',
                           'Total Maps. Total Maps Over 3.5': '1.616',
                           'Total Maps. Total Maps Over 4.5': '3.54',
                           'Total Maps. Total Maps Under 3.5': '2.19',
                           'Total Maps. Total Maps Under 4.5': '1.27',
                           'Total. 2 map. Total Over 23.5': '1.24',
                           'Total. 2 map. Total Over 24.5': '1.37',
                           'Total. 2 map. Total Over 25.5': '1.56',
                           'Total. 2 map. Total Over 26.5': '1.84',
                           'Total. 2 map. Total Over 27.5': '2.25',
                           'Total. 2 map. Total Over 28.5': '2.94',
                           'Total. 2 map. Total Over 29.5': '4.22',
                           'Total. 2 map. Total Under 23.5': '3.78',
                           'Total. 2 map. Total Under 24.5': '2.94',
                           'Total. 2 map. Total Under 25.5': '2.33',
                           'Total. 2 map. Total Under 26.5': '1.9',
                           'Total. 2 map. Total Under 27.5': '1.6',
                           'Total. 2 map. Total Under 28.5': '1.37',
                           'Total. 2 map. Total Under 29.5': '1.2',
                           'Will There Be Overtime? - Yes/No. 2 map. Will There Be Overtime? - No': '1.08',
                           'Will There Be Overtime? - Yes/No. 2 map. Will There Be Overtime? - Yes': '6.9',
                           'Win In Round. 2 map. Evil Geniuses Will Win In Round 1': '1.82',
                           'Win In Round. 2 map. Evil Geniuses Will Win In Round 16': '1.81',
                           'Win In Round. 2 map. Gen.G Will Win In Round 1': '1.92',
                           'Win In Round. 2 map. Gen.G Will Win In Round 16': '1.93',
                           'url': 'https://1x-bet.com/en/line/Esports/2105034-CSGO-cs-summit-6-North-America/78803382-Evil-Geniuses-GenG/'},
 'ex-smash - ago': {'. ': '',
                    '1x2. 1 map. AGO': '1.78',
                    '1x2. 1 map. ex-SMASH': '1.975',
                    '1x2. AGO': '1.76',
                    '1x2. ex-SMASH': '2.025',
                    'Handicap. 1 map. Handiсap AGO (+2.5)': '1.49',
                    'Handicap. 1 map. Handiсap AGO (+3.5)': '1.39',
                    'Handicap. 1 map. Handiсap AGO (+4.5)': '1.3',
                    'Handicap. 1 map. Handiсap AGO (+5.5)': '1.22',
                    'Handicap. 1 map. Handiсap AGO (-2.5)': '2.17',
                    'Handicap. 1 map. Handiсap AGO (-3.5)': '2.45',
                    'Handicap. 1 map. Handiсap AGO (-4.5)': '2.85',
                    'Handicap. 1 map. Handiсap AGO (-5.5)': '3.32',
                    'Handicap. 1 map. Handiсap AGO (-6.5)': '3.98',
                    'Handicap. 1 map. Handiсap ex-SMASH (+2.5)': '1.64',
                    'Handicap. 1 map. Handiсap ex-SMASH (+3.5)': '1.51',
                    'Handicap. 1 map. Handiсap ex-SMASH (+4.5)': '1.39',
                    'Handicap. 1 map. Handiсap ex-SMASH (+5.5)': '1.3',
                    'Handicap. 1 map. Handiсap ex-SMASH (+6.5)': '1.22',
                    'Handicap. 1 map. Handiсap ex-SMASH (-2.5)': '2.51',
                    'Handicap. 1 map. Handiсap ex-SMASH (-3.5)': '2.85',
                    'Handicap. 1 map. Handiсap ex-SMASH (-4.5)': '3.32',
                    'Handicap. 1 map. Handiсap ex-SMASH (-5.5)': '3.98',
                    'Terrorists, Total. 1 map. ': '',
                    'Terrorists, Total. 1 map. Terrorists - Total Over 10.5': '1.22',
                    'Terrorists, Total. 1 map. Terrorists - Total Under 10.5': '3.98',
                    'Total 1. 1 map. ': '',
                    'Total 1. 1 map. Individual Total 1 Over 10.5': '1.28',
                    'Total 1. 1 map. Individual Total 1 Over 11.5': '1.36',
                    'Total 1. 1 map. Individual Total 1 Over 12.5': '1.475',
                    'Total 1. 1 map. Individual Total 1 Over 13.5': '1.595',
                    'Total 1. 1 map. Individual Total 1 Over 9.5': '1.205',
                    'Total 1. 1 map. Individual Total 1 Under 10.5': '3.32',
                    'Total 1. 1 map. Individual Total 1 Under 11.5': '2.85',
                    'Total 1. 1 map. Individual Total 1 Under 12.5': '2.45',
                    'Total 1. 1 map. Individual Total 1 Under 13.5': '2.17',
                    'Total 1. 1 map. Individual Total 1 Under 9.5': '3.98',
                    'Total 2. 1 map. Individual Total 2 Over 10.5': '1.205',
                    'Total 2. 1 map. Individual Total 2 Over 12.5': '1.36',
                    'Total 2. 1 map. Individual Total 2 Over 13.5': '1.456',
                    'Total 2. 1 map. Individual Total 2 Over 14.5': '1.575',
                    'Total 2. 1 map. Individual Total 2 Under 10.5': '3.98',
                    'Total 2. 1 map. Individual Total 2 Under 12.5': '2.85',
                    'Total 2. 1 map. Individual Total 2 Under 13.5': '2.51',
                    'Total 2. 1 map. Individual Total 2 Under 14.5': '2.21',
                    'Total Maps Even/Odd. Total Maps - Even': '1.69',
                    'Total Maps Even/Odd. Total Maps - Odd': '2.09',
                    'Total Maps Handicap. AGO Handicap -1.5 Maps': '2.85',
                    'Total Maps Handicap. AGO Handicap 1.5 Maps': '1.27',
                    'Total Maps Handicap. ex-SMASH Handicap -1.5 Maps': '3.54',
                    'Total Maps Handicap. ex-SMASH Handicap 1.5 Maps': '1.39',
                    'Total Maps. Total Maps Over 2.5': '2.085',
                    'Total Maps. Total Maps Under 2.5': '1.69',
                    'Total. 1 map. Total Over 23.5': '1.22',
                    'Total. 1 map. Total Over 24.5': '1.35',
                    'Total. 1 map. Total Over 25.5': '1.53',
                    'Total. 1 map. Total Over 26.5': '1.79',
                    'Total. 1 map. Total Over 27.5': '2.19',
                    'Total. 1 map. Total Over 28.5': '2.85',
                    'Total. 1 map. Total Over 29.5': '4.1',
                    'Total. 1 map. Total Under 23.5': '3.98',
                    'Total. 1 map. Total Under 24.5': '3.04',
                    'Total. 1 map. Total Under 25.5': '2.4',
                    'Total. 1 map. Total Under 26.5': '1.96',
                    'Total. 1 map. Total Under 27.5': '1.63',
                    'Total. 1 map. Total Under 28.5': '1.39',
                    'Total. 1 map. Total Under 29.5': '1.21',
                    'Win In Round. 1 map. AGO Will Win In Round 1': '1.86',
                    'Win In Round. 1 map. AGO Will Win In Round 16': '1.86',
                    'Win In Round. 1 map. ex-SMASH Will Win In Round 1': '1.88',
                    'Win In Round. 1 map. ex-SMASH Will Win In Round 16': '1.88',
                    'url': 'https://1x-bet.com/en/line/Esports/2108311-CSGO-Eden-Arena-Malta-Vibes-Cup-1/78796091-ex-SMASH-AGO/'},
 'fate esports - izako boars': {'. ': '',
                                '1x2. 1 map. FATE eSports': '1.34',
                                '1x2. 1 map. Izako Boars': '3.12',
                                '1x2. FATE eSports': '1.24',
                                '1x2. Izako Boars': '3.9',
                                'Counter Terrorists, Total. 1 map. ': '',
                                'Handicap. 1 map. Handiсap FATE eSports (+2.5)': '1.21',
                                'Handicap. 1 map. Handiсap FATE eSports (-2.5)': '1.56',
                                'Handicap. 1 map. Handiсap FATE eSports (-3.5)': '1.72',
                                'Handicap. 1 map. Handiсap FATE eSports (-4.5)': '1.94',
                                'Handicap. 1 map. Handiсap FATE eSports (-5.5)': '2.23',
                                'Handicap. 1 map. Handiсap FATE eSports (-6.5)': '2.63',
                                'Handicap. 1 map. Handiсap FATE eSports (-7.5)': '3.2',
                                'Handicap. 1 map. Handiсap FATE eSports (-8.5)': '3.98',
                                'Handicap. 1 map. Handiсap Izako Boars (+2.5)': '2.33',
                                'Handicap. 1 map. Handiсap Izako Boars (+3.5)': '2.05',
                                'Handicap. 1 map. Handiсap Izako Boars (+4.5)': '1.8',
                                'Handicap. 1 map. Handiсap Izako Boars (+5.5)': '1.61',
                                'Handicap. 1 map. Handiсap Izako Boars (+6.5)': '1.45',
                                'Handicap. 1 map. Handiсap Izako Boars (+7.5)': '1.32',
                                'Handicap. 1 map. Handiсap Izako Boars (+8.5)': '1.22',
                                'Handicap. 1 map. Handiсap Izako Boars (-2.5)': '4.1',
                                'Total 1. 1 map. Individual Total 1 Over 13.5': '1.195',
                                'Total 1. 1 map. Individual Total 1 Under 13.5': '4.1',
                                'Total 2. 1 map. ': '',
                                'Total 2. 1 map. Individual Total 2 Over 10.5': '1.568',
                                'Total 2. 1 map. Individual Total 2 Over 11.5': '1.744',
                                'Total 2. 1 map. Individual Total 2 Over 12.5': '1.975',
                                'Total 2. 1 map. Individual Total 2 Over 13.5': '2.235',
                                'Total 2. 1 map. Individual Total 2 Over 7.5': '1.205',
                                'Total 2. 1 map. Individual Total 2 Over 8.5': '1.296',
                                'Total 2. 1 map. Individual Total 2 Over 9.5': '1.42',
                                'Total 2. 1 map. Individual Total 2 Under 10.5': '2.23',
                                'Total 2. 1 map. Individual Total 2 Under 11.5': '1.94',
                                'Total 2. 1 map. Individual Total 2 Under 12.5': '1.72',
                                'Total 2. 1 map. Individual Total 2 Under 13.5': '1.56',
                                'Total 2. 1 map. Individual Total 2 Under 7.5': '3.98',
                                'Total 2. 1 map. Individual Total 2 Under 8.5': '3.2',
                                'Total 2. 1 map. Individual Total 2 Under 9.5': '2.63',
                                'Total Maps Even/Odd. Total Maps - Even': '1.49',
                                'Total Maps Even/Odd. Total Maps - Odd': '2.51',
                                'Total Maps Handicap. FATE eSports Handicap -1.5 Maps': '1.75',
                                'Total Maps Handicap. FATE eSports Handicap 1.5 Maps': '1.08',
                                'Total Maps Handicap. Izako Boars Handicap -1.5 Maps': '6.9',
                                'Total Maps Handicap. Izako Boars Handicap 1.5 Maps': '1.99',
                                'Total Maps. Total Maps Over 2.5': '2.51',
                                'Total Maps. Total Maps Under 2.5': '1.49',
                                'Total. 1 map. Total Over 23.5': '1.28',
                                'Total. 1 map. Total Over 24.5': '1.43',
                                'Total. 1 map. Total Over 25.5': '1.64',
                                'Total. 1 map. Total Over 26.5': '1.94',
                                'Total. 1 map. Total Over 27.5': '2.4',
                                'Total. 1 map. Total Over 28.5': '3.14',
                                'Total. 1 map. Total Under 23.5': '3.46',
                                'Total. 1 map. Total Under 24.5': '2.7',
                                'Total. 1 map. Total Under 25.5': '2.17',
                                'Total. 1 map. Total Under 26.5': '1.8',
                                'Total. 1 map. Total Under 27.5': '1.53',
                                'Total. 1 map. Total Under 28.5': '1.33',
                                'Win In Round. 1 map. FATE eSports Will Win In Round 1': '1.78',
                                'Win In Round. 1 map. FATE eSports Will Win In Round 16': '1.78',
                                'Win In Round. 1 map. Izako Boars Will Win In Round 1': '1.97',
                                'Win In Round. 1 map. Izako Boars Will Win In Round 16': '1.97',
                                'url': 'https://1x-bet.com/en/line/Esports/2107656-CSGO-Nine-to-Five-Dawn/78696540-FATE-eSports-Izako-Boars/'},
 'huat zai - bren': {'1x2. 1 map. Bren': '1.88',
                     '1x2. 1 map. Huat Zai': '1.87',
                     '1x2. 2 map. Bren': '1.88',
                     '1x2. 2 map. Huat Zai': '1.87',
                     '1x2. Bren': '1.88',
                     '1x2. Huat Zai': '1.89',
                     'url': 'https://1x-bet.com/en/line/Esports/2108135-CSGO-Development-League-Season-2/78804915-Huat-Zai-Bren/'},
 'kova esports - havu gaming': {'1x2. 1 map. HAVU Gaming': '1.36',
                                '1x2. 1 map. KOVA Esports': '3.01',
                                '1x2. 2 map. HAVU Gaming': '1.36',
                                '1x2. 2 map. KOVA Esports': '3.01',
                                '1x2. HAVU Gaming': '1.264',
                                '1x2. KOVA Esports': '3.7',
                                'Handicap. 1 map. Handiсap HAVU Gaming (-2.5)': '1.6',
                                'Handicap. 1 map. Handiсap HAVU Gaming (-3.5)': '1.76',
                                'Handicap. 1 map. Handiсap HAVU Gaming (-4.5)': '1.98',
                                'Handicap. 1 map. Handiсap HAVU Gaming (-5.5)': '2.29',
                                'Handicap. 1 map. Handiсap HAVU Gaming (-6.5)': '2.7',
                                'Handicap. 1 map. Handiсap HAVU Gaming (-7.5)': '3.26',
                                'Handicap. 1 map. Handiсap KOVA Esports (+2.5)': '2.25',
                                'Handicap. 1 map. Handiсap KOVA Esports (+3.5)': '1.99',
                                'Handicap. 1 map. Handiсap KOVA Esports (+4.5)': '1.77',
                                'Handicap. 1 map. Handiсap KOVA Esports (+5.5)': '1.58',
                                'Handicap. 1 map. Handiсap KOVA Esports (+6.5)': '1.43',
                                'Handicap. 1 map. Handiсap KOVA Esports (+7.5)': '1.31',
                                'Handicap. 2 map. ': '',
                                'Handicap. 2 map. Handiсap HAVU Gaming (-2.5)': '1.59',
                                'Handicap. 2 map. Handiсap HAVU Gaming (-3.5)': '1.75',
                                'Handicap. 2 map. Handiсap HAVU Gaming (-4.5)': '1.97',
                                'Handicap. 2 map. Handiсap HAVU Gaming (-5.5)': '2.25',
                                'Handicap. 2 map. Handiсap HAVU Gaming (-6.5)': '2.66',
                                'Handicap. 2 map. Handiсap KOVA Esports (+2.5)': '2.27',
                                'Handicap. 2 map. Handiсap KOVA Esports (+3.5)': '2.01',
                                'Handicap. 2 map. Handiсap KOVA Esports (+4.5)': '1.78',
                                'Handicap. 2 map. Handiсap KOVA Esports (+5.5)': '1.6',
                                'Handicap. 2 map. Handiсap KOVA Esports (+6.5)': '1.44',
                                'Total Maps Even/Odd. Total Maps - Even': '1.51',
                                'Total Maps Even/Odd. Total Maps - Odd': '2.45',
                                'Total Maps Handicap. HAVU Gaming Handicap -1.5 Maps': '1.78',
                                'Total Maps Handicap. HAVU Gaming Handicap 1.5 Maps': '1.08',
                                'Total Maps Handicap. KOVA Esports Handicap -1.5 Maps': '6.9',
                                'Total Maps Handicap. KOVA Esports Handicap 1.5 Maps': '1.93',
                                'Total Maps. Total Maps Over 2.5': '2.45',
                                'Total Maps. Total Maps Under 2.5': '1.51',
                                'Total. 1 map. Total Over 24.5': '1.42',
                                'Total. 1 map. Total Over 25.5': '1.63',
                                'Total. 1 map. Total Over 26.5': '1.93',
                                'Total. 1 map. Total Over 27.5': '2.38',
                                'Total. 1 map. Total Over 28.5': '3.09',
                                'Total. 1 map. Total Under 24.5': '2.73',
                                'Total. 1 map. Total Under 25.5': '2.19',
                                'Total. 1 map. Total Under 26.5': '1.81',
                                'Total. 1 map. Total Under 27.5': '1.54',
                                'Total. 1 map. Total Under 28.5': '1.34',
                                'Total. 2 map. Total Over 24.5': '1.43',
                                'Total. 2 map. Total Over 25.5': '1.64',
                                'Total. 2 map. Total Over 26.5': '1.94',
                                'Total. 2 map. Total Over 27.5': '2.4',
                                'Total. 2 map. Total Over 28.5': '3.14',
                                'Total. 2 map. Total Under 24.5': '2.7',
                                'Total. 2 map. Total Under 25.5': '2.17',
                                'Total. 2 map. Total Under 26.5': '1.8',
                                'Total. 2 map. Total Under 27.5': '1.53',
                                'Total. 2 map. Total Under 28.5': '1.33',
                                'Win In Round. 1 map. HAVU Gaming Will Win In Round 1': '1.79',
                                'Win In Round. 1 map. HAVU Gaming Will Win In Round 16': '1.78',
                                'Win In Round. 1 map. KOVA Esports Will Win In Round 1': '1.96',
                                'Win In Round. 1 map. KOVA Esports Will Win In Round 16': '1.97',
                                'Win In Round. 2 map. ': '',
                                'Win In Round. 2 map. HAVU Gaming Will Win In Round 1': '1.78',
                                'Win In Round. 2 map. KOVA Esports Will Win In Round 1': '1.97',
                                'url': 'https://1x-bet.com/en/line/Esports/2089224-CSGO-Finnish-Esports-League-Season-8/78797776-KOVA-Esports-HAVU-Gaming/'},
 'ldlc - cr4zy': {'. ': '',
                  '1x2. 1 map. CR4ZY': '1.88',
                  '1x2. 1 map. LDLC': '1.87',
                  '1x2. CR4ZY': '1.88',
                  '1x2. LDLC': '1.888',
                  'Handicap. 1 map. Handiсap CR4ZY (+2.5)': '1.56',
                  'Handicap. 1 map. Handiсap CR4ZY (+3.5)': '1.44',
                  'Handicap. 1 map. Handiсap CR4ZY (+4.5)': '1.34',
                  'Handicap. 1 map. Handiсap CR4ZY (+5.5)': '1.26',
                  'Handicap. 1 map. Handiсap CR4ZY (-2.5)': '2.31',
                  'Handicap. 1 map. Handiсap CR4ZY (-3.5)': '2.63',
                  'Handicap. 1 map. Handiсap CR4ZY (-4.5)': '3.04',
                  'Handicap. 1 map. Handiсap CR4ZY (-5.5)': '3.62',
                  'Handicap. 1 map. Handiсap LDLC (+2.5)': '1.57',
                  'Handicap. 1 map. Handiсap LDLC (+3.5)': '1.45',
                  'Handicap. 1 map. Handiсap LDLC (+4.5)': '1.35',
                  'Handicap. 1 map. Handiсap LDLC (+5.5)': '1.26',
                  'Handicap. 1 map. Handiсap LDLC (-2.5)': '2.33',
                  'Handicap. 1 map. Handiсap LDLC (-3.5)': '2.66',
                  'Handicap. 1 map. Handiсap LDLC (-4.5)': '3.09',
                  'Handicap. 1 map. Handiсap LDLC (-5.5)': '3.62',
                  'Terrorists, Total. 1 map. ': '',
                  'Total 1. 1 map. Individual Total 1 Over 10.5': '1.24',
                  'Total 1. 1 map. Individual Total 1 Over 11.5': '1.325',
                  'Total 1. 1 map. Individual Total 1 Over 12.5': '1.42',
                  'Total 1. 1 map. Individual Total 1 Over 13.5': '1.53',
                  'Total 1. 1 map. Individual Total 1 Over 14.5': '1.66',
                  'Total 1. 1 map. Individual Total 1 Under 10.5': '3.62',
                  'Total 1. 1 map. Individual Total 1 Under 11.5': '3.04',
                  'Total 1. 1 map. Individual Total 1 Under 12.5': '2.63',
                  'Total 1. 1 map. Individual Total 1 Under 13.5': '2.31',
                  'Total 1. 1 map. Individual Total 1 Under 14.5': '2.06',
                  'Total 2. 1 map. Individual Total 2 Over 10.5': '1.24',
                  'Total 2. 1 map. Individual Total 2 Over 11.5': '1.315',
                  'Total 2. 1 map. Individual Total 2 Over 12.5': '1.41',
                  'Total 2. 1 map. Individual Total 2 Over 13.5': '1.52',
                  'Total 2. 1 map. Individual Total 2 Over 14.5': '1.65',
                  'Total 2. 1 map. Individual Total 2 Under 10.5': '3.62',
                  'Total 2. 1 map. Individual Total 2 Under 11.5': '3.09',
                  'Total 2. 1 map. Individual Total 2 Under 12.5': '2.66',
                  'Total 2. 1 map. Individual Total 2 Under 13.5': '2.33',
                  'Total 2. 1 map. Individual Total 2 Under 14.5': '2.08',
                  'Total Maps Even/Odd. Total Maps - Even': '1.7',
                  'Total Maps Even/Odd. Total Maps - Odd': '2.08',
                  'Total Maps Handicap. CR4ZY Handicap -1.5 Maps': '3.2',
                  'Total Maps Handicap. CR4ZY Handicap 1.5 Maps': '1.32',
                  'Total Maps Handicap. LDLC Handicap -1.5 Maps': '3.2',
                  'Total Maps Handicap. LDLC Handicap 1.5 Maps': '1.32',
                  'Total Maps. Total Maps Over 2.5': '2.08',
                  'Total Maps. Total Maps Under 2.5': '1.7',
                  'Total. 1 map. Total Over 23.5': '1.22',
                  'Total. 1 map. Total Over 24.5': '1.35',
                  'Total. 1 map. Total Over 25.5': '1.53',
                  'Total. 1 map. Total Over 26.5': '1.79',
                  'Total. 1 map. Total Over 27.5': '2.19',
                  'Total. 1 map. Total Over 28.5': '2.85',
                  'Total. 1 map. Total Over 29.5': '4.1',
                  'Total. 1 map. Total Under 23.5': '3.98',
                  'Total. 1 map. Total Under 24.5': '3.04',
                  'Total. 1 map. Total Under 25.5': '2.4',
                  'Total. 1 map. Total Under 26.5': '1.96',
                  'Total. 1 map. Total Under 27.5': '1.63',
                  'Total. 1 map. Total Under 28.5': '1.39',
                  'Total. 1 map. Total Under 29.5': '1.21',
                  'Win In Round. 1 map. CR4ZY Will Win In Round 1': '1.87',
                  'Win In Round. 1 map. CR4ZY Will Win In Round 16': '1.87',
                  'Win In Round. 1 map. LDLC Will Win In Round 1': '1.87',
                  'Win In Round. 1 map. LDLC Will Win In Round 16': '1.87',
                  'url': 'https://1x-bet.com/en/line/Esports/2107656-CSGO-Nine-to-Five-Dawn/78699308-LDLC-CR4ZY/'},
 'ldlc - lilmix': {'. ': '',
                   '1x2. 1 map. LDLC': '1.55',
                   '1x2. 1 map. Lilmix': '2.37',
                   '1x2. 2 map. LDLC': '1.55',
                   '1x2. 2 map. Lilmix': '2.37',
                   '1x2. LDLC': '1.45',
                   '1x2. Lilmix': '2.69',
                   'Handicap. 1 map. Handiсap LDLC (+2.5)': '1.34',
                   'Handicap. 1 map. Handiсap LDLC (+3.5)': '1.27',
                   'Handicap. 1 map. Handiсap LDLC (+4.5)': '1.2',
                   'Handicap. 1 map. Handiсap LDLC (-2.5)': '1.84',
                   'Handicap. 1 map. Handiсap LDLC (-3.5)': '2.06',
                   'Handicap. 1 map. Handiсap LDLC (-4.5)': '2.35',
                   'Handicap. 1 map. Handiсap LDLC (-5.5)': '2.73',
                   'Handicap. 1 map. Handiсap LDLC (-6.5)': '3.26',
                   'Handicap. 1 map. Handiсap LDLC (-7.5)': '3.98',
                   'Handicap. 1 map. Handiсap Lilmix (+2.5)': '1.9',
                   'Handicap. 1 map. Handiсap Lilmix (+3.5)': '1.71',
                   'Handicap. 1 map. Handiсap Lilmix (+4.5)': '1.55',
                   'Handicap. 1 map. Handiсap Lilmix (+5.5)': '1.42',
                   'Handicap. 1 map. Handiсap Lilmix (+6.5)': '1.31',
                   'Handicap. 1 map. Handiсap Lilmix (+7.5)': '1.22',
                   'Handicap. 1 map. Handiсap Lilmix (-2.5)': '3.09',
                   'Handicap. 1 map. Handiсap Lilmix (-3.5)': '3.54',
                   'Handicap. 1 map. Handiсap Lilmix (-4.5)': '4.22',
                   'Handicap. 2 map. ': '',
                   'Handicap. 2 map. Handiсap LDLC (-6.5)': '3.26',
                   'Handicap. 2 map. Handiсap LDLC (-7.5)': '3.98',
                   'Handicap. 2 map. Handiсap Lilmix (+6.5)': '1.31',
                   'Handicap. 2 map. Handiсap Lilmix (+7.5)': '1.22',
                   'Total Maps Even/Odd. Total Maps - Even': '1.62',
                   'Total Maps Even/Odd. Total Maps - Odd': '2.21',
                   'Total Maps Handicap. LDLC Handicap -1.5 Maps': '2.23',
                   'Total Maps Handicap. LDLC Handicap 1.5 Maps': '1.16',
                   'Total Maps Handicap. Lilmix Handicap -1.5 Maps': '4.8',
                   'Total Maps Handicap. Lilmix Handicap 1.5 Maps': '1.61',
                   'Total Maps. Total Maps Over 2.5': '2.21',
                   'Total Maps. Total Maps Under 2.5': '1.62',
                   'Total. 1 map. Total Over 23.5': '1.24',
                   'Total. 1 map. Total Over 24.5': '1.37',
                   'Total. 1 map. Total Over 25.5': '1.56',
                   'Total. 1 map. Total Over 26.5': '1.83',
                   'Total. 1 map. Total Over 27.5': '2.25',
                   'Total. 1 map. Total Over 28.5': '2.94',
                   'Total. 1 map. Total Over 29.5': '4.22',
                   'Total. 1 map. Total Under 23.5': '3.78',
                   'Total. 1 map. Total Under 24.5': '2.94',
                   'Total. 1 map. Total Under 25.5': '2.33',
                   'Total. 1 map. Total Under 26.5': '1.91',
                   'Total. 1 map. Total Under 27.5': '1.6',
                   'Total. 1 map. Total Under 28.5': '1.37',
                   'Total. 1 map. Total Under 29.5': '1.2',
                   'Total. 2 map. ': '',
                   'Total. 2 map. Total Over 23.5': '1.24',
                   'Total. 2 map. Total Over 24.5': '1.38',
                   'Total. 2 map. Total Over 25.5': '1.57',
                   'Total. 2 map. Total Over 26.5': '1.84',
                   'Total. 2 map. Total Under 23.5': '3.78',
                   'Total. 2 map. Total Under 24.5': '2.9',
                   'Total. 2 map. Total Under 25.5': '2.31',
                   'Total. 2 map. Total Under 26.5': '1.9',
                   'Win In Round. 1 map. LDLC Will Win In Round 1': '1.82',
                   'Win In Round. 1 map. LDLC Will Win In Round 16': '1.82',
                   'Win In Round. 1 map. Lilmix Will Win In Round 1': '1.92',
                   'Win In Round. 1 map. Lilmix Will Win In Round 16': '1.92',
                   'url': 'https://1x-bet.com/en/line/Esports/2091676-CSGO-ESEA-Advanced-Season-34-Europe/78760359-LDLC-Lilmix/'},
 'mythic - ex-polar ace': {'1x2. 1 map. Mythic': '1.37',
                           '1x2. 1 map. ex-Polar Ace': '2.97',
                           '1x2. 2 map. Mythic': '1.37',
                           '1x2. 2 map. ex-Polar Ace': '2.97',
                           '1x2. Mythic': '1.27',
                           '1x2. ex-Polar Ace': '3.64',
                           'url': 'https://1x-bet.com/en/line/Esports/2098798-CSGO-Mythic-Invite-League-Season-1/78804069-Mythic-ex-Polar-Ace/'},
 'nexus gaming - thedice': {'. ': '',
                            '1x2. 1 map. Nexus Gaming': '1.65',
                            '1x2. 1 map. TheDice': '2.165',
                            '1x2. 2 map. Nexus Gaming': '1.65',
                            '1x2. 2 map. TheDice': '2.165',
                            '1x2. Nexus Gaming': '1.568',
                            '1x2. TheDice': '2.368',
                            'Handicap. 1 map. Handiсap Nexus Gaming (+2.5)': '1.41',
                            'Handicap. 1 map. Handiсap Nexus Gaming (+3.5)': '1.32',
                            'Handicap. 1 map. Handiсap Nexus Gaming (+4.5)': '1.24',
                            'Handicap. 1 map. Handiсap Nexus Gaming (-2.5)': '1.98',
                            'Handicap. 1 map. Handiсap Nexus Gaming (-3.5)': '2.23',
                            'Handicap. 1 map. Handiсap Nexus Gaming (-4.5)': '2.57',
                            'Handicap. 1 map. Handiсap Nexus Gaming (-5.5)': '2.99',
                            'Handicap. 1 map. Handiсap Nexus Gaming (-6.5)': '3.62',
                            'Handicap. 1 map. Handiсap TheDice (+2.5)': '1.77',
                            'Handicap. 1 map. Handiсap TheDice (+3.5)': '1.61',
                            'Handicap. 1 map. Handiсap TheDice (+4.5)': '1.47',
                            'Handicap. 1 map. Handiсap TheDice (+5.5)': '1.36',
                            'Handicap. 1 map. Handiсap TheDice (+6.5)': '1.26',
                            'Handicap. 1 map. Handiсap TheDice (-2.5)': '2.77',
                            'Handicap. 1 map. Handiсap TheDice (-3.5)': '3.2',
                            'Handicap. 1 map. Handiсap TheDice (-4.5)': '3.78',
                            'Handicap. 2 map. ': '',
                            'Handicap. 2 map. Handiсap Nexus Gaming (-4.5)': '2.57',
                            'Handicap. 2 map. Handiсap Nexus Gaming (-5.5)': '2.99',
                            'Handicap. 2 map. Handiсap Nexus Gaming (-6.5)': '3.62',
                            'Handicap. 2 map. Handiсap TheDice (+4.5)': '1.47',
                            'Handicap. 2 map. Handiсap TheDice (+5.5)': '1.36',
                            'Handicap. 2 map. Handiсap TheDice (+6.5)': '1.26',
                            'Total Maps Even/Odd. Total Maps - Even': '1.66',
                            'Total Maps Even/Odd. Total Maps - Odd': '2.14',
                            'Total Maps Handicap. Nexus Gaming Handicap -1.5 Maps': '2.51',
                            'Total Maps Handicap. Nexus Gaming Handicap 1.5 Maps': '1.2',
                            'Total Maps Handicap. TheDice Handicap -1.5 Maps': '4.22',
                            'Total Maps Handicap. TheDice Handicap 1.5 Maps': '1.49',
                            'Total Maps. Total Maps Over 2.5': '2.14',
                            'Total Maps. Total Maps Under 2.5': '1.66',
                            'Total. 1 map. Total Over 23.5': '1.23',
                            'Total. 1 map. Total Over 24.5': '1.36',
                            'Total. 1 map. Total Over 25.5': '1.54',
                            'Total. 1 map. Total Over 26.5': '1.81',
                            'Total. 1 map. Total Over 27.5': '2.21',
                            'Total. 1 map. Total Over 28.5': '2.85',
                            'Total. 1 map. Total Over 29.5': '4.1',
                            'Total. 1 map. Total Under 23.5': '3.88',
                            'Total. 1 map. Total Under 24.5': '2.99',
                            'Total. 1 map. Total Under 25.5': '2.38',
                            'Total. 1 map. Total Under 26.5': '1.93',
                            'Total. 1 map. Total Under 27.5': '1.62',
                            'Total. 1 map. Total Under 28.5': '1.39',
                            'Total. 1 map. Total Under 29.5': '1.21',
                            'Total. 2 map. ': '',
                            'Total. 2 map. Total Over 23.5': '1.23',
                            'Total. 2 map. Total Over 24.5': '1.36',
                            'Total. 2 map. Total Over 25.5': '1.55',
                            'Total. 2 map. Total Over 26.5': '1.82',
                            'Total. 2 map. Total Over 27.5': '2.23',
                            'Total. 2 map. Total Under 23.5': '3.88',
                            'Total. 2 map. Total Under 24.5': '2.99',
                            'Total. 2 map. Total Under 25.5': '2.35',
                            'Total. 2 map. Total Under 26.5': '1.92',
                            'Total. 2 map. Total Under 27.5': '1.61',
                            'Win In Round. 1 map. Nexus Gaming Will Win In Round 1': '1.84',
                            'Win In Round. 1 map. Nexus Gaming Will Win In Round 16': '1.83',
                            'Win In Round. 1 map. TheDice Will Win In Round 1': '1.9',
                            'Win In Round. 1 map. TheDice Will Win In Round 16': '1.91',
                            'url': 'https://1x-bet.com/en/line/Esports/2091676-CSGO-ESEA-Advanced-Season-34-Europe/78761138-Nexus-Gaming-TheDice/'},
 'oceanus gaming - new england whalers': {'1x2. 1 map. New England Whalers': '1.5',
                                          '1x2. 1 map. Oceanus Gaming': '2.5',
                                          '1x2. 2 map. New England Whalers': '1.5',
                                          '1x2. 2 map. Oceanus Gaming': '2.5',
                                          '1x2. New England Whalers': '1.42',
                                          '1x2. Oceanus Gaming': '2.78',
                                          'url': 'https://1x-bet.com/en/line/Esports/2098798-CSGO-Mythic-Invite-League-Season-1/78804072-Oceanus-Gaming-New-England-Whalers/'},
 'order - ground zero gaming': {'1x2. 1 map. Ground Zero Gaming': '3.28',
                                '1x2. 1 map. Order': '1.31',
                                '1x2. 2 map. Ground Zero Gaming': '3.28',
                                '1x2. 2 map. Order': '1.31',
                                '1x2. Ground Zero Gaming': '4.32',
                                '1x2. Order': '1.205',
                                'Handicap. 1 map. Handiсap Ground Zero Gaming (+2.5)': '2.63',
                                'Handicap. 1 map. Handiсap Ground Zero Gaming (+3.5)': '2.29',
                                'Handicap. 1 map. Handiсap Ground Zero Gaming (+4.5)': '2',
                                'Handicap. 1 map. Handiсap Ground Zero Gaming (+5.5)': '1.76',
                                'Handicap. 1 map. Handiсap Order (-2.5)': '1.425',
                                'Handicap. 1 map. Handiсap Order (-3.5)': '1.56',
                                'Handicap. 1 map. Handiсap Order (-4.5)': '1.745',
                                'Handicap. 1 map. Handiсap Order (-5.5)': '1.96',
                                'Handicap. 2 map. Handiсap Ground Zero Gaming (+2.5)': '2.45',
                                'Handicap. 2 map. Handiсap Ground Zero Gaming (+3.5)': '2.14',
                                'Handicap. 2 map. Handiсap Ground Zero Gaming (+4.5)': '1.88',
                                'Handicap. 2 map. Handiсap Ground Zero Gaming (+5.5)': '1.67',
                                'Handicap. 2 map. Handiсap Order (-2.5)': '1.51',
                                'Handicap. 2 map. Handiсap Order (-3.5)': '1.66',
                                'Handicap. 2 map. Handiсap Order (-4.5)': '1.86',
                                'Handicap. 2 map. Handiсap Order (-5.5)': '2.115',
                                'Total Maps Even/Odd. Total Maps - Even': '1.46',
                                'Total Maps Even/Odd. Total Maps - Odd': '2.6',
                                'Total Maps Handicap. Ground Zero Gaming Handicap -1.5 Maps': '7.9',
                                'Total Maps Handicap. Ground Zero Gaming Handicap 1.5 Maps': '2.11',
                                'Total Maps Handicap. Order Handicap -1.5 Maps': '1.68',
                                'Total Maps Handicap. Order Handicap 1.5 Maps': '1.06',
                                'Total Maps. Total Maps Over 2.5': '2.6',
                                'Total Maps. Total Maps Under 2.5': '1.46',
                                'Total. 1 map. Total Over 25.5': '1.67',
                                'Total. 1 map. Total Over 26.5': '1.99',
                                'Total. 1 map. Total Over 27.5': '2.45',
                                'Total. 1 map. Total Under 25.5': '2.12',
                                'Total. 1 map. Total Under 26.5': '1.76',
                                'Total. 1 map. Total Under 27.5': '1.51',
                                'Total. 2 map. Total Over 25.5': '1.68',
                                'Total. 2 map. Total Over 26.5': '1.99',
                                'Total. 2 map. Total Over 27.5': '2.48',
                                'Total. 2 map. Total Under 25.5': '2.11',
                                'Total. 2 map. Total Under 26.5': '1.76',
                                'Total. 2 map. Total Under 27.5': '1.5',
                                'Win In Round. 1 map. Ground Zero Gaming Will Win In Round 1': '1.98',
                                'Win In Round. 1 map. Ground Zero Gaming Will Win In Round 16': '1.98',
                                'Win In Round. 1 map. Order Will Win In Round 1': '1.765',
                                'Win In Round. 1 map. Order Will Win In Round 16': '1.77',
                                'Win In Round. 2 map. Ground Zero Gaming Will Win In Round 1': '1.98',
                                'Win In Round. 2 map. Ground Zero Gaming Will Win In Round 16': '1.98',
                                'Win In Round. 2 map. Order Will Win In Round 1': '1.77',
                                'Win In Round. 2 map. Order Will Win In Round 16': '1.77',
                                'url': 'https://1x-bet.com/en/line/Esports/2110829-CSGO-DreamHack-Open-Summer-2020-Oceania-Qualifier/78814033-Order-Ground-Zero-Gaming/'},
 'rooster - chiefs esports club': {'1x2. 1 map. Chiefs Esports Club': '1.575',
                                   '1x2. 1 map. Rooster': '2.315',
                                   '1x2. 2 map. Chiefs Esports Club': '1.57',
                                   '1x2. 2 map. Rooster': '2.325',
                                   '1x2. Chiefs Esports Club': '1.5',
                                   '1x2. Rooster': '2.53',
                                   'Handicap. 1 map. Handiсap Chiefs Esports Club (-2.5)': '1.89',
                                   'Handicap. 1 map. Handiсap Chiefs Esports Club (-3.5)': '2.12',
                                   'Handicap. 1 map. Handiсap Chiefs Esports Club (-4.5)': '2.43',
                                   'Handicap. 1 map. Handiсap Rooster (+2.5)': '1.85',
                                   'Handicap. 1 map. Handiсap Rooster (+3.5)': '1.656',
                                   'Handicap. 1 map. Handiсap Rooster (+4.5)': '1.52',
                                   'Handicap. 2 map. Handiсap Chiefs Esports Club (-2.5)': '1.87',
                                   'Handicap. 2 map. Handiсap Chiefs Esports Club (-3.5)': '2.11',
                                   'Handicap. 2 map. Handiсap Chiefs Esports Club (-4.5)': '2.4',
                                   'Handicap. 2 map. Handiсap Rooster (+2.5)': '1.87',
                                   'Handicap. 2 map. Handiсap Rooster (+3.5)': '1.68',
                                   'Handicap. 2 map. Handiсap Rooster (+4.5)': '1.53',
                                   'Total Maps Even/Odd. Total Maps - Even': '1.64',
                                   'Total Maps Even/Odd. Total Maps - Odd': '2.17',
                                   'Total Maps Handicap. Chiefs Esports Club Handicap -1.5 Maps': '2.33',
                                   'Total Maps Handicap. Chiefs Esports Club Handicap 1.5 Maps': '1.17',
                                   'Total Maps Handicap. Rooster Handicap -1.5 Maps': '4.64',
                                   'Total Maps Handicap. Rooster Handicap 1.5 Maps': '1.555',
                                   'Total Maps. Total Maps Over 2.5': '2.168',
                                   'Total Maps. Total Maps Under 2.5': '1.64',
                                   'Total. 1 map. Total Over 25.5': '1.55',
                                   'Total. 1 map. Total Over 26.5': '1.82',
                                   'Total. 1 map. Total Over 27.5': '2.23',
                                   'Total. 1 map. Total Under 25.5': '2.344',
                                   'Total. 1 map. Total Under 26.5': '1.92',
                                   'Total. 1 map. Total Under 27.5': '1.61',
                                   'Total. 2 map. Total Over 25.5': '1.56',
                                   'Total. 2 map. Total Over 26.5': '1.83',
                                   'Total. 2 map. Total Over 27.5': '2.25',
                                   'Total. 2 map. Total Under 25.5': '2.33',
                                   'Total. 2 map. Total Under 26.5': '1.91',
                                   'Total. 2 map. Total Under 27.5': '1.6',
                                   'Win In Round. 1 map. Chiefs Esports Club Will Win In Round 1': '1.825',
                                   'Win In Round. 1 map. Chiefs Esports Club Will Win In Round 16': '1.82',
                                   'Win In Round. 1 map. Rooster Will Win In Round 1': '1.91',
                                   'Win In Round. 1 map. Rooster Will Win In Round 16': '1.92',
                                   'Win In Round. 2 map. Chiefs Esports Club Will Win In Round 1': '1.82',
                                   'Win In Round. 2 map. Chiefs Esports Club Will Win In Round 16': '1.82',
                                   'Win In Round. 2 map. Rooster Will Win In Round 1': '1.92',
                                   'Win In Round. 2 map. Rooster Will Win In Round 16': '1.92',
                                   'url': 'https://1x-bet.com/en/line/Esports/2110829-CSGO-DreamHack-Open-Summer-2020-Oceania-Qualifier/78813238-Rooster-Chiefs-Esports-Club/'},
 'sangal esports - tikitakan': {'. ': '',
                                '1x2. 1 map. Sangal Esports': '1.6',
                                '1x2. 1 map. Tikitakan': '2.26',
                                '1x2. 2 map. Sangal Esports': '1.6',
                                '1x2. 2 map. Tikitakan': '2.26',
                                '1x2. Sangal Esports': '1.504',
                                '1x2. Tikitakan': '2.51',
                                'Handicap. 1 map. Handiсap Sangal Esports (+2.5)': '1.37',
                                'Handicap. 1 map. Handiсap Sangal Esports (+3.5)': '1.29',
                                'Handicap. 1 map. Handiсap Sangal Esports (+4.5)': '1.22',
                                'Handicap. 1 map. Handiсap Sangal Esports (-2.5)': '1.92',
                                'Handicap. 1 map. Handiсap Sangal Esports (-3.5)': '2.17',
                                'Handicap. 1 map. Handiсap Sangal Esports (-4.5)': '2.51',
                                'Handicap. 1 map. Handiсap Sangal Esports (-5.5)': '2.94',
                                'Handicap. 1 map. Handiсap Sangal Esports (-6.5)': '3.54',
                                'Handicap. 1 map. Handiсap Tikitakan (+2.5)': '1.82',
                                'Handicap. 1 map. Handiсap Tikitakan (+3.5)': '1.64',
                                'Handicap. 1 map. Handiсap Tikitakan (+4.5)': '1.49',
                                'Handicap. 1 map. Handiсap Tikitakan (+5.5)': '1.37',
                                'Handicap. 1 map. Handiсap Tikitakan (+6.5)': '1.27',
                                'Handicap. 1 map. Handiсap Tikitakan (-2.5)': '2.94',
                                'Handicap. 1 map. Handiсap Tikitakan (-3.5)': '3.38',
                                'Handicap. 1 map. Handiсap Tikitakan (-4.5)': '3.98',
                                'Handicap. 2 map. ': '',
                                'Handicap. 2 map. Handiсap Sangal Esports (-4.5)': '2.48',
                                'Handicap. 2 map. Handiсap Sangal Esports (-5.5)': '2.94',
                                'Handicap. 2 map. Handiсap Sangal Esports (-6.5)': '3.54',
                                'Handicap. 2 map. Handiсap Tikitakan (+4.5)': '1.5',
                                'Handicap. 2 map. Handiсap Tikitakan (+5.5)': '1.37',
                                'Handicap. 2 map. Handiсap Tikitakan (+6.5)': '1.27',
                                'Total Maps Even/Odd. Total Maps - Even': '1.69',
                                'Total Maps Even/Odd. Total Maps - Odd': '2.09',
                                'Total Maps Handicap. Sangal Esports Handicap -1.5 Maps': '2.4',
                                'Total Maps Handicap. Sangal Esports Handicap 1.5 Maps': '1.17',
                                'Total Maps Handicap. Tikitakan Handicap -1.5 Maps': '4.64',
                                'Total Maps Handicap. Tikitakan Handicap 1.5 Maps': '1.53',
                                'Total Maps. Total Maps Over 2.5': '2.09',
                                'Total Maps. Total Maps Under 2.5': '1.69',
                                'Total. 1 map. Total Over 23.5': '1.22',
                                'Total. 1 map. Total Over 24.5': '1.34',
                                'Total. 1 map. Total Over 25.5': '1.52',
                                'Total. 1 map. Total Over 26.5': '1.78',
                                'Total. 1 map. Total Over 27.5': '2.17',
                                'Total. 1 map. Total Over 28.5': '2.81',
                                'Total. 1 map. Total Over 29.5': '3.98',
                                'Total. 1 map. Total Under 23.5': '3.98',
                                'Total. 1 map. Total Under 24.5': '3.09',
                                'Total. 1 map. Total Under 25.5': '2.43',
                                'Total. 1 map. Total Under 26.5': '1.97',
                                'Total. 1 map. Total Under 27.5': '1.64',
                                'Total. 1 map. Total Under 28.5': '1.4',
                                'Total. 1 map. Total Under 29.5': '1.22',
                                'Total. 2 map. ': '',
                                'Total. 2 map. Total Over 23.5': '1.22',
                                'Total. 2 map. Total Over 24.5': '1.34',
                                'Total. 2 map. Total Over 25.5': '1.52',
                                'Total. 2 map. Total Over 26.5': '1.79',
                                'Total. 2 map. Total Over 27.5': '2.17',
                                'Total. 2 map. Total Under 23.5': '3.98',
                                'Total. 2 map. Total Under 24.5': '3.09',
                                'Total. 2 map. Total Under 25.5': '2.43',
                                'Total. 2 map. Total Under 26.5': '1.96',
                                'Total. 2 map. Total Under 27.5': '1.64',
                                'Win In Round. 1 map. Sangal Esports Will Win In Round 1': '1.83',
                                'Win In Round. 1 map. Sangal Esports Will Win In Round 16': '1.83',
                                'Win In Round. 1 map. Tikitakan Will Win In Round 1': '1.91',
                                'Win In Round. 1 map. Tikitakan Will Win In Round 16': '1.91',
                                'url': 'https://1x-bet.com/en/line/Esports/2091676-CSGO-ESEA-Advanced-Season-34-Europe/78761142-Sangal-Esports-Tikitakan/'},
 'saw - agf': {'. ': '',
               '1x2. 1 map. AGF': '2.685',
               '1x2. 1 map. sAw': '1.44',
               '1x2. AGF': '3.112',
               '1x2. sAw': '1.35',
               'Handicap. 1 map. Handiсap AGF (+2.5)': '2.08',
               'Handicap. 1 map. Handiсap AGF (+3.5)': '1.84',
               'Handicap. 1 map. Handiсap AGF (+4.5)': '1.65',
               'Handicap. 1 map. Handiсap AGF (+5.5)': '1.49',
               'Handicap. 1 map. Handiсap AGF (+6.5)': '1.36',
               'Handicap. 1 map. Handiсap AGF (+7.5)': '1.26',
               'Handicap. 1 map. Handiсap AGF (-2.5)': '3.46',
               'Handicap. 1 map. Handiсap AGF (-3.5)': '3.98',
               'Handicap. 1 map. Handiсap sAw (+2.5)': '1.28',
               'Handicap. 1 map. Handiсap sAw (+3.5)': '1.22',
               'Handicap. 1 map. Handiсap sAw (-2.5)': '1.7',
               'Handicap. 1 map. Handiсap sAw (-3.5)': '1.9',
               'Handicap. 1 map. Handiсap sAw (-4.5)': '2.16',
               'Handicap. 1 map. Handiсap sAw (-5.5)': '2.51',
               'Handicap. 1 map. Handiсap sAw (-6.5)': '2.99',
               'Handicap. 1 map. Handiсap sAw (-7.5)': '3.62',
               'Total 1. 1 map. Individual Total 1 Over 12.5': '1.205',
               'Total 1. 1 map. Individual Total 1 Over 14.5': '1.325',
               'Total 1. 1 map. Individual Total 1 Under 12.5': '3.98',
               'Total 1. 1 map. Individual Total 1 Under 14.5': '3.04',
               'Total 2. 1 map. Individual Total 2 Over 10.5': '1.456',
               'Total 2. 1 map. Individual Total 2 Over 11.5': '1.605',
               'Total 2. 1 map. Individual Total 2 Over 12.5': '1.78',
               'Total 2. 1 map. Individual Total 2 Over 13.5': '2.005',
               'Total 2. 1 map. Individual Total 2 Over 14.5': '2.235',
               'Total 2. 1 map. Individual Total 2 Over 8.5': '1.24',
               'Total 2. 1 map. Individual Total 2 Over 9.5': '1.336',
               'Total 2. 1 map. Individual Total 2 Under 10.5': '2.51',
               'Total 2. 1 map. Individual Total 2 Under 11.5': '2.16',
               'Total 2. 1 map. Individual Total 2 Under 12.5': '1.9',
               'Total 2. 1 map. Individual Total 2 Under 13.5': '1.7',
               'Total 2. 1 map. Individual Total 2 Under 14.5': '1.56',
               'Total 2. 1 map. Individual Total 2 Under 8.5': '3.62',
               'Total 2. 1 map. Individual Total 2 Under 9.5': '2.99',
               'Total Maps Even/Odd. Total Maps - Even': '1.57',
               'Total Maps Even/Odd. Total Maps - Odd': '2.31',
               'Total Maps Handicap. AGF Handicap -1.5 Maps': '5.65',
               'Total Maps Handicap. AGF Handicap 1.5 Maps': '1.76',
               'Total Maps Handicap. sAw Handicap -1.5 Maps': '1.97',
               'Total Maps Handicap. sAw Handicap 1.5 Maps': '1.12',
               'Total Maps. Total Maps Over 2.5': '2.3',
               'Total Maps. Total Maps Under 2.5': '1.57',
               'Total. 1 map. Total Over 23.5': '1.25',
               'Total. 1 map. Total Over 24.5': '1.39',
               'Total. 1 map. Total Over 25.5': '1.59',
               'Total. 1 map. Total Over 26.5': '1.87',
               'Total. 1 map. Total Over 27.5': '2.31',
               'Total. 1 map. Total Over 28.5': '2.99',
               'Total. 1 map. Total Under 23.5': '3.7',
               'Total. 1 map. Total Under 24.5': '2.85',
               'Total. 1 map. Total Under 25.5': '2.27',
               'Total. 1 map. Total Under 26.5': '1.87',
               'Total. 1 map. Total Under 27.5': '1.57',
               'Total. 1 map. Total Under 28.5': '1.36',
               'Win In Round. 1 map. AGF Will Win In Round 1': '1.94',
               'Win In Round. 1 map. AGF Will Win In Round 16': '1.94',
               'Win In Round. 1 map. sAw Will Win In Round 1': '1.8',
               'Win In Round. 1 map. sAw Will Win In Round 16': '1.8',
               'url': 'https://1x-bet.com/en/line/Esports/2107656-CSGO-Nine-to-Five-Dawn/78695966-sAw-AGF/'},
 'sprout - hard legion esports': {'. ': '',
                                  '1x2. 1 map. Hard Legion Esports': '2.375',
                                  '1x2. 1 map. Sprout': '1.55',
                                  '1x2. Hard Legion Esports': '2.616',
                                  '1x2. Sprout': '1.47',
                                  'Bomb Planted. 1 map. Bomb Planted In Round 1 - No': '2.25',
                                  'Bomb Planted. 1 map. Bomb Planted In Round 1 - Yes': '1.6',
                                  'Bomb Planted. 1 map. Bomb Planted In Round 16 - No': '2.25',
                                  'Bomb Planted. 1 map. Bomb Planted In Round 16 - Yes': '1.6',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (+2.5)': '1.89',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (+3.5)': '1.7',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (+4.5)': '1.54',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (+5.5)': '1.41',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (+6.5)': '1.3',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (+7.5)': '1.21',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (-2.5)': '3.04',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (-3.5)': '3.54',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (-4.5)': '4.1',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (-5.5)': '4.92',
                                  'Handicap. 1 map. Handiсap Hard Legion Esports (-6.5)': '5.9',
                                  'Handicap. 1 map. Handiсap Sprout (+2.5)': '1.35',
                                  'Handicap. 1 map. Handiсap Sprout (+3.5)': '1.27',
                                  'Handicap. 1 map. Handiсap Sprout (+4.5)': '1.21',
                                  'Handicap. 1 map. Handiсap Sprout (+5.5)': '1.19',
                                  'Handicap. 1 map. Handiсap Sprout (+6.5)': '1.14',
                                  'Handicap. 1 map. Handiсap Sprout (-2.5)': '1.85',
                                  'Handicap. 1 map. Handiсap Sprout (-3.5)': '2.08',
                                  'Handicap. 1 map. Handiсap Sprout (-4.5)': '2.38',
                                  'Handicap. 1 map. Handiсap Sprout (-5.5)': '2.77',
                                  'Handicap. 1 map. Handiсap Sprout (-6.5)': '3.32',
                                  'Handicap. 1 map. Handiсap Sprout (-7.5)': '4.1',
                                  'Method Of Win In Round. 1 map. ': '',
                                  'Method Of Win In Round. 1 map. Bomb Defused In Round 1': '3.5',
                                  'Method Of Win In Round. 1 map. Bomb Exploded In 1 Round': '15',
                                  'Round Total. 1 map. Total Frags In 1 Round Over 7.5': '2.25',
                                  'Round Total. 1 map. Total Frags In 1 Round Under 7.5': '1.6',
                                  'Round Total. 1 map. Total Frags In 16 Round Over 7.5': '2.25',
                                  'Round Total. 1 map. Total Frags In 16 Round Under 7.5': '1.6',
                                  'Total Maps Even/Odd. Total Maps - Even': '1.63',
                                  'Total Maps Even/Odd. Total Maps - Odd': '2.19',
                                  'Total Maps Handicap. Hard Legion Esports Handicap -1.5 Maps': '4.8',
                                  'Total Maps Handicap. Hard Legion Esports Handicap 1.5 Maps': '1.584',
                                  'Total Maps Handicap. Sprout Handicap -1.5 Maps': '2.25',
                                  'Total Maps Handicap. Sprout Handicap 1.5 Maps': '1.16',
                                  'Total Maps. Total Maps Over 2.5': '2.18',
                                  'Total Maps. Total Maps Under 2.5': '1.63',
                                  'Total. 1 map. Total Over 22.5': '1.2',
                                  'Total. 1 map. Total Over 23.5': '1.24',
                                  'Total. 1 map. Total Over 24.5': '1.37',
                                  'Total. 1 map. Total Over 25.5': '1.56',
                                  'Total. 1 map. Total Over 26.5': '1.83',
                                  'Total. 1 map. Total Over 27.5': '2.25',
                                  'Total. 1 map. Total Over 28.5': '2.9',
                                  'Total. 1 map. Total Over 29.5': '4.1',
                                  'Total. 1 map. Total Over 30.5': '9.6',
                                  'Total. 1 map. Total Under 22.5': '4.74',
                                  'Total. 1 map. Total Under 23.5': '3.78',
                                  'Total. 1 map. Total Under 24.5': '2.94',
                                  'Total. 1 map. Total Under 25.5': '2.33',
                                  'Total. 1 map. Total Under 26.5': '1.91',
                                  'Total. 1 map. Total Under 27.5': '1.6',
                                  'Total. 1 map. Total Under 28.5': '1.38',
                                  'Total. 1 map. Total Under 29.5': '1.21',
                                  'Total. 1 map. Total Under 30.5': '1.07',
                                  'Will There Be Overtime? - Yes/No. 1 map. Will There Be Overtime? - No': '1.06',
                                  'Will There Be Overtime? - Yes/No. 1 map. Will There Be Overtime? - Yes': '9.5',
                                  'Win In Round. 1 map. ': '',
                                  'url': 'https://1x-bet.com/en/line/Esports/2093139-CSGO-Hellcase-Cup-8/78789323-Sprout-Hard-Legion-Esports/'},
 'sws gaming - bravos': {'1x2. 1 map. Bravos': '1.75',
                         '1x2. 1 map. SWS Gaming': '2.015',
                         '1x2. 2 map. Bravos': '1.75',
                         '1x2. 2 map. SWS Gaming': '2.015',
                         '1x2. Bravos': '1.73',
                         '1x2. SWS Gaming': '2.06',
                         'url': 'https://1x-bet.com/en/line/Esports/2064339-CSGO-CLUTCH/78809388-SWS-Gaming-Bravos/'},
 'team frosty - kuusamo': {'1x2. 1 map. KUUSAMO': '2.915',
                           '1x2. 1 map. Team Frosty': '1.38',
                           '1x2. 2 map. KUUSAMO': '2.912',
                           '1x2. 2 map. Team Frosty': '1.38',
                           '1x2. KUUSAMO': '3.62',
                           '1x2. Team Frosty': '1.27',
                           'url': 'https://1x-bet.com/en/line/Esports/2095225-CSGO-Finnish-Esports-League-Season-8-Challenger-League/78733641-Team-Frosty-KUUSAMO/'},
 'team one - alcoholics anonymous': {'1x2. 1 map. Alcoholics Anonymous': '2.42',
                                     '1x2. 1 map. Team One': '1.53',
                                     '1x2. 2 map. Alcoholics Anonymous': '2.42',
                                     '1x2. 2 map. Team One': '1.53',
                                     '1x2. Alcoholics Anonymous': '2.752',
                                     '1x2. Team One': '1.43',
                                     'url': 'https://1x-bet.com/en/line/Esports/2098798-CSGO-Mythic-Invite-League-Season-1/78803943-Team-One-Alcoholics-Anonymous/'},
 'team secret - saw': {'1x2. 1 map. Team Secret': '2.125',
                       '1x2. 1 map. sAw': '1.68',
                       '1x2. 2 map. Team Secret': '2.125',
                       '1x2. 2 map. sAw': '1.68',
                       '1x2. Team Secret': '2.285',
                       '1x2. sAw': '1.605',
                       'Handicap. 1 map. Handiсap Team Secret (+2.5)': '1.71',
                       'Handicap. 1 map. Handiсap Team Secret (+3.5)': '1.56',
                       'Handicap. 1 map. Handiсap Team Secret (+4.5)': '1.43',
                       'Handicap. 1 map. Handiсap Team Secret (+5.5)': '1.32',
                       'Handicap. 1 map. Handiсap Team Secret (-2.5)': '2.7',
                       'Handicap. 1 map. Handiсap Team Secret (-3.5)': '3.14',
                       'Handicap. 1 map. Handiсap sAw (+2.5)': '1.43',
                       'Handicap. 1 map. Handiсap sAw (+3.5)': '1.33',
                       'Handicap. 1 map. Handiсap sAw (-2.5)': '2.06',
                       'Handicap. 1 map. Handiсap sAw (-3.5)': '2.33',
                       'Handicap. 1 map. Handiсap sAw (-4.5)': '2.7',
                       'Handicap. 1 map. Handiсap sAw (-5.5)': '3.2',
                       'Handicap. 2 map. ': '',
                       'Handicap. 2 map. Handiсap Team Secret (+2.5)': '1.72',
                       'Handicap. 2 map. Handiсap Team Secret (+3.5)': '1.56',
                       'Handicap. 2 map. Handiсap Team Secret (+4.5)': '1.43',
                       'Handicap. 2 map. Handiсap Team Secret (-2.5)': '2.73',
                       'Handicap. 2 map. Handiсap Team Secret (-3.5)': '3.14',
                       'Handicap. 2 map. Handiсap sAw (+2.5)': '1.42',
                       'Handicap. 2 map. Handiсap sAw (+3.5)': '1.33',
                       'Handicap. 2 map. Handiсap sAw (-2.5)': '2.05',
                       'Handicap. 2 map. Handiсap sAw (-3.5)': '2.33',
                       'Handicap. 2 map. Handiсap sAw (-4.5)': '2.7',
                       'Total Maps Even/Odd. Total Maps - Even': '1.76',
                       'Total Maps Even/Odd. Total Maps - Odd': '1.99',
                       'Total Maps Handicap. Team Secret Handicap -1.5 Maps': '4.22',
                       'Total Maps Handicap. Team Secret Handicap 1.5 Maps': '1.43',
                       'Total Maps Handicap. sAw Handicap -1.5 Maps': '2.7',
                       'Total Maps Handicap. sAw Handicap 1.5 Maps': '1.2',
                       'Total Maps. Total Maps Over 2.5': '1.99',
                       'Total Maps. Total Maps Under 2.5': '1.76',
                       'Total. 1 map. Total Over 24.5': '1.32',
                       'Total. 1 map. Total Over 25.5': '1.49',
                       'Total. 1 map. Total Over 26.5': '1.75',
                       'Total. 1 map. Total Over 27.5': '2.12',
                       'Total. 1 map. Total Over 28.5': '2.77',
                       'Total. 1 map. Total Under 24.5': '3.2',
                       'Total. 1 map. Total Under 25.5': '2.51',
                       'Total. 1 map. Total Under 26.5': '2.01',
                       'Total. 1 map. Total Under 27.5': '1.67',
                       'Total. 1 map. Total Under 28.5': '1.41',
                       'Total. 2 map. Total Over 24.5': '1.32',
                       'Total. 2 map. Total Over 25.5': '1.5',
                       'Total. 2 map. Total Over 26.5': '1.75',
                       'Total. 2 map. Total Over 27.5': '2.12',
                       'Total. 2 map. Total Over 28.5': '2.77',
                       'Total. 2 map. Total Under 24.5': '3.2',
                       'Total. 2 map. Total Under 25.5': '2.48',
                       'Total. 2 map. Total Under 26.5': '2.01',
                       'Total. 2 map. Total Under 27.5': '1.67',
                       'Total. 2 map. Total Under 28.5': '1.41',
                       'Win In Round. 1 map. Team Secret Will Win In Round 1': '1.9',
                       'Win In Round. 1 map. Team Secret Will Win In Round 16': '1.9',
                       'Win In Round. 1 map. sAw Will Win In Round 1': '1.84',
                       'Win In Round. 1 map. sAw Will Win In Round 16': '1.84',
                       'Win In Round. 2 map. ': '',
                       'Win In Round. 2 map. Team Secret Will Win In Round 1': '1.9',
                       'Win In Round. 2 map. sAw Will Win In Round 1': '1.84',
                       'url': 'https://1x-bet.com/en/line/Esports/2091676-CSGO-ESEA-Advanced-Season-34-Europe/78776230-Team-Secret-sAw/'},
 'team vitality - big': {'. ': '',
                         '1x2. 2 map. BIG': '1.85',
                         '1x2. 2 map. Team Vitality': '1.9',
                         '1x2. BIG': '2.71',
                         '1x2. Team Vitality': '1.44',
                         'Handicap. 2 map. Handiсap BIG (+2.5)': '1.55',
                         'Handicap. 2 map. Handiсap BIG (+3.5)': '1.42',
                         'Handicap. 2 map. Handiсap BIG (+4.5)': '1.32',
                         'Handicap. 2 map. Handiсap BIG (+5.5)': '1.23',
                         'Handicap. 2 map. Handiсap BIG (+6.5)': '1.21',
                         'Handicap. 2 map. Handiсap BIG (-2.5)': '2.384',
                         'Handicap. 2 map. Handiсap BIG (-3.5)': '2.775',
                         'Handicap. 2 map. Handiсap BIG (-4.5)': '3.26',
                         'Handicap. 2 map. Handiсap BIG (-5.5)': '3.88',
                         'Handicap. 2 map. Handiсap BIG (-6.5)': '4.66',
                         'Handicap. 2 map. Handiсap BIG (-7.5)': '5.7',
                         'Handicap. 2 map. Handiсap Team Vitality (+2.5)': '1.54',
                         'Handicap. 2 map. Handiсap Team Vitality (+3.5)': '1.41',
                         'Handicap. 2 map. Handiсap Team Vitality (+4.5)': '1.31',
                         'Handicap. 2 map. Handiсap Team Vitality (+5.5)': '1.23',
                         'Handicap. 2 map. Handiсap Team Vitality (+6.5)': '1.2',
                         'Handicap. 2 map. Handiсap Team Vitality (+7.5)': '1.15',
                         'Handicap. 2 map. Handiсap Team Vitality (-2.5)': '2.344',
                         'Handicap. 2 map. Handiсap Team Vitality (-3.5)': '2.72',
                         'Handicap. 2 map. Handiсap Team Vitality (-4.5)': '3.2',
                         'Handicap. 2 map. Handiсap Team Vitality (-5.5)': '3.88',
                         'Handicap. 2 map. Handiсap Team Vitality (-6.5)': '4.5',
                         'Total 1. 2 map. ': '',
                         'Total 1. 2 map. Individual Total 1 Over 10.5': '1.215',
                         'Total 1. 2 map. Individual Total 1 Over 11.5': '1.29',
                         'Total 1. 2 map. Individual Total 1 Over 12.5': '1.38',
                         'Total 1. 2 map. Individual Total 1 Under 10.5': '3.88',
                         'Total 1. 2 map. Individual Total 1 Under 11.5': '3.26',
                         'Total 1. 2 map. Individual Total 1 Under 12.5': '2.77',
                         'Total Maps Handicap. BIG Handicap -1.5 Maps': '5.8',
                         'Total Maps Handicap. BIG Handicap 1.5 Maps': '1.85',
                         'Total Maps Handicap. BIG Handicap 2.5 Maps': '1.29',
                         'Total Maps Handicap. Team Vitality Handicap -1.5 Maps': '1.848',
                         'Total Maps Handicap. Team Vitality Handicap -2.5 Maps': '3.38',
                         'Total Maps Handicap. Team Vitality Handicap 1.5 Maps': '1.11',
                         'Total Maps. Total Maps Over 3.5': '1.285',
                         'Total Maps. Total Maps Over 4.5': '2.47',
                         'Total Maps. Total Maps Under 3.5': '3.38',
                         'Total Maps. Total Maps Under 4.5': '1.5',
                         'Total. 2 map. Total Over 22.5': '1.2',
                         'Total. 2 map. Total Over 23.5': '1.29',
                         'Total. 2 map. Total Over 24.5': '1.29',
                         'Total. 2 map. Total Over 25.5': '1.45',
                         'Total. 2 map. Total Over 26.5': '1.69',
                         'Total. 2 map. Total Over 27.5': '2.05',
                         'Total. 2 map. Total Over 28.5': '2.66',
                         'Total. 2 map. Total Over 29.5': '3.78',
                         'Total. 2 map. Total Over 30.5': '9.4',
                         'Total. 2 map. Total Under 22.5': '4.74',
                         'Total. 2 map. Total Under 23.5': '3.66',
                         'Total. 2 map. Total Under 24.5': '3.38',
                         'Total. 2 map. Total Under 25.5': '2.63',
                         'Total. 2 map. Total Under 26.5': '2.09',
                         'Total. 2 map. Total Under 27.5': '1.72',
                         'Total. 2 map. Total Under 28.5': '1.44',
                         'Total. 2 map. Total Under 29.5': '1.24',
                         'Total. 2 map. Total Under 30.5': '1.07',
                         'Will There Be Overtime? - Yes/No. 2 map. Will There Be Overtime? - No': '1.09',
                         'Will There Be Overtime? - Yes/No. 2 map. Will There Be Overtime? - Yes': '6.55',
                         'Win In Round. 2 map. ': '',
                         'Win In Round. 2 map. BIG Will Win In Round 1': '1.87',
                         'Win In Round. 2 map. Team Vitality Will Win In Round 1': '1.87',
                         'url': 'https://1x-bet.com/en/line/Esports/2105037-CSGO-cs-summit-6-Europe/78793546-Team-Vitality-BIG/'},
 'third impact - valkyrie': {'1x2. 1 map. Third Impact': '1.43',
                             '1x2. 1 map. Valkyrie': '2.712',
                             '1x2. 2 map. Third Impact': '1.43',
                             '1x2. 2 map. Valkyrie': '2.712',
                             '1x2. Third Impact': '1.32',
                             '1x2. Valkyrie': '3.26',
                             'url': 'https://1x-bet.com/en/line/Esports/2097636-CSGO-Winners-League-Main-Division/78732240-Third-Impact-Valkyrie/'},
 'tiger - vici gaming': {'1x2. 1 map. Tiger': '2.56',
                         '1x2. 1 map. Vici Gaming': '1.48',
                         '1x2. 2 map. Tiger': '2.59',
                         '1x2. 2 map. Vici Gaming': '1.47',
                         '1x2. Tiger': '2.9',
                         '1x2. Vici Gaming': '1.392',
                         'Handicap. 1 map. Handiсap Tiger (+2.5)': '2.05',
                         'Handicap. 1 map. Handiсap Tiger (+3.5)': '1.83',
                         'Handicap. 1 map. Handiсap Tiger (+4.5)': '1.65',
                         'Handicap. 1 map. Handiсap Vici Gaming (-2.5)': '1.72',
                         'Handicap. 1 map. Handiсap Vici Gaming (-3.5)': '1.91',
                         'Handicap. 1 map. Handiсap Vici Gaming (-4.5)': '2.16',
                         'Handicap. 2 map. Handiсap Tiger (+2.5)': '2.01',
                         'Handicap. 2 map. Handiсap Tiger (+3.5)': '1.8',
                         'Handicap. 2 map. Handiсap Tiger (+4.5)': '1.62',
                         'Handicap. 2 map. Handiсap Vici Gaming (-2.5)': '1.75',
                         'Handicap. 2 map. Handiсap Vici Gaming (-3.5)': '1.94',
                         'Handicap. 2 map. Handiсap Vici Gaming (-4.5)': '2.21',
                         'Total Maps Even/Odd. Total Maps - Even': '1.6',
                         'Total Maps Even/Odd. Total Maps - Odd': '2.25',
                         'Total Maps Handicap. Tiger Handicap -1.5 Maps': '5.4',
                         'Total Maps Handicap. Tiger Handicap 1.5 Maps': '1.51',
                         'Total Maps Handicap. Vici Gaming Handicap -1.5 Maps': '2.09',
                         'Total Maps Handicap. Vici Gaming Handicap 1.5 Maps': '1.13',
                         'Total Maps. Total Maps Over 2.5': '2.216',
                         'Total Maps. Total Maps Under 2.5': '1.6',
                         'Total. 1 map. Total Over 25.5': '1.58',
                         'Total. 1 map. Total Over 26.5': '1.86',
                         'Total. 1 map. Total Over 27.5': '2.27',
                         'Total. 1 map. Total Under 25.5': '2.29',
                         'Total. 1 map. Total Under 26.5': '1.88',
                         'Total. 1 map. Total Under 27.5': '1.59',
                         'Total. 2 map. Total Over 25.5': '1.59',
                         'Total. 2 map. Total Over 26.5': '1.87',
                         'Total. 2 map. Total Over 27.5': '2.29',
                         'Total. 2 map. Total Under 25.5': '2.27',
                         'Total. 2 map. Total Under 26.5': '1.87',
                         'Total. 2 map. Total Under 27.5': '1.58',
                         'Win In Round. 1 map. Tiger Will Win In Round 1': '1.93',
                         'Win In Round. 1 map. Tiger Will Win In Round 16': '1.93',
                         'Win In Round. 1 map. Vici Gaming Will Win In Round 1': '1.81',
                         'Win In Round. 1 map. Vici Gaming Will Win In Round 16': '1.81',
                         'Win In Round. 2 map. Tiger Will Win In Round 1': '1.93',
                         'Win In Round. 2 map. Tiger Will Win In Round 16': '1.94',
                         'Win In Round. 2 map. Vici Gaming Will Win In Round 1': '1.81',
                         'Win In Round. 2 map. Vici Gaming Will Win In Round 16': '1.8',
                         'url': 'https://1x-bet.com/en/line/Esports/2106875-CSGO-Perfect-World-Asia-League-Summer-2020/78736264-Tiger-Vici-Gaming/'},
 'unicorns of love - exploit esports': {'1x2. 1 map. Exploit Esports': '2.715',
                                        '1x2. 1 map. Unicorns Of Love': '1.43',
                                        '1x2. Exploit Esports': '2.73',
                                        '1x2. Unicorns Of Love': '1.435',
                                        'url': 'https://1x-bet.com/en/line/Esports/2109546-CSGO-Betano-Masters-Season-1-Europe/78804927-Unicorns-Of-Love-Exploit-Esports/'},
 'yeah! - swedish canadians': {'1x2. 1 map. Swedish Canadians': '2.015',
                               '1x2. 1 map. YeaH!': '1.75',
                               '1x2. 2 map. Swedish Canadians': '2.015',
                               '1x2. 2 map. YeaH!': '1.75',
                               '1x2. Swedish Canadians': '2.09',
                               '1x2. YeaH!': '1.712',
                               'url': 'https://1x-bet.com/en/line/Esports/2098798-CSGO-Mythic-Invite-League-Season-1/78804066-YeaH-Swedish-Canadians/'},
 'yeah! - triumph': {'1x2. 1 map. Triumph': '1.41',
                     '1x2. 1 map. YeaH!': '2.79',
                     '1x2. 2 map. Triumph': '1.41',
                     '1x2. 2 map. YeaH!': '2.79',
                     '1x2. Triumph': '1.32',
                     '1x2. YeaH!': '3.28',
                     'Handicap. 1 map. Handiсap Triumph (-2.5)': '1.66',
                     'Handicap. 1 map. Handiсap Triumph (-3.5)': '1.84',
                     'Handicap. 1 map. Handiсap Triumph (-4.5)': '2.09',
                     'Handicap. 1 map. Handiсap Triumph (-5.5)': '2.43',
                     'Handicap. 1 map. Handiсap Triumph (-6.5)': '2.85',
                     'Handicap. 1 map. Handiсap YeaH! (+2.5)': '2.14',
                     'Handicap. 1 map. Handiсap YeaH! (+3.5)': '1.9',
                     'Handicap. 1 map. Handiсap YeaH! (+4.5)': '1.69',
                     'Handicap. 1 map. Handiсap YeaH! (+5.5)': '1.52',
                     'Handicap. 1 map. Handiсap YeaH! (+6.5)': '1.39',
                     'Handicap. 2 map. Handiсap Triumph (-2.5)': '1.66',
                     'Handicap. 2 map. Handiсap Triumph (-3.5)': '1.84',
                     'Handicap. 2 map. Handiсap Triumph (-4.5)': '2.08',
                     'Handicap. 2 map. Handiсap Triumph (-5.5)': '2.4',
                     'Handicap. 2 map. Handiсap Triumph (-6.5)': '2.85',
                     'Handicap. 2 map. Handiсap YeaH! (+2.5)': '2.14',
                     'Handicap. 2 map. Handiсap YeaH! (+3.5)': '1.9',
                     'Handicap. 2 map. Handiсap YeaH! (+4.5)': '1.7',
                     'Handicap. 2 map. Handiсap YeaH! (+5.5)': '1.53',
                     'Handicap. 2 map. Handiсap YeaH! (+6.5)': '1.39',
                     'Total Maps Even/Odd. Total Maps - Even': '1.55',
                     'Total Maps Even/Odd. Total Maps - Odd': '2.35',
                     'Total Maps Handicap. Triumph Handicap -1.5 Maps': '1.92',
                     'Total Maps Handicap. Triumph Handicap 1.5 Maps': '1.1',
                     'Total Maps Handicap. YeaH! Handicap -1.5 Maps': '6.2',
                     'Total Maps Handicap. YeaH! Handicap 1.5 Maps': '1.82',
                     'Total Maps. Total Maps Over 2.5': '2.35',
                     'Total Maps. Total Maps Under 2.5': '1.55',
                     'Total. 1 map. Total Over 24.5': '1.4',
                     'Total. 1 map. Total Over 25.5': '1.6',
                     'Total. 1 map. Total Over 26.5': '1.89',
                     'Total. 1 map. Total Over 27.5': '2.33',
                     'Total. 1 map. Total Over 28.5': '3.04',
                     'Total. 1 map. Total Under 24.5': '2.81',
                     'Total. 1 map. Total Under 25.5': '2.25',
                     'Total. 1 map. Total Under 26.5': '1.85',
                     'Total. 1 map. Total Under 27.5': '1.56',
                     'Total. 1 map. Total Under 28.5': '1.35',
                     'Total. 2 map. Total Over 24.5': '1.41',
                     'Total. 2 map. Total Over 25.5': '1.61',
                     'Total. 2 map. Total Over 26.5': '1.9',
                     'Total. 2 map. Total Over 27.5': '2.33',
                     'Total. 2 map. Total Over 28.5': '3.04',
                     'Total. 2 map. Total Under 24.5': '2.77',
                     'Total. 2 map. Total Under 25.5': '2.23',
                     'Total. 2 map. Total Under 26.5': '1.84',
                     'Total. 2 map. Total Under 27.5': '1.56',
                     'Total. 2 map. Total Under 28.5': '1.35',
                     'Win In Round. 1 map. Triumph Will Win In Round 1': '1.8',
                     'Win In Round. 1 map. Triumph Will Win In Round 16': '1.79',
                     'Win In Round. 1 map. YeaH! Will Win In Round 1': '1.94',
                     'Win In Round. 1 map. YeaH! Will Win In Round 16': '1.96',
                     'Win In Round. 2 map. ': '',
                     'Win In Round. 2 map. Triumph Will Win In Round 1': '1.8',
                     'Win In Round. 2 map. YeaH! Will Win In Round 1': '1.94',
                     'url': 'https://1x-bet.com/en/line/Esports/1842596-CSGO-Winners-League/78803938-YeaH-Triumph/'}}
