bets = {'ambush - tricked': {'1-st map: Total. 26.5. Over': '1.72',
                      '1-st map: Total. 26.5. Under': '2.05',
                      '1-st map: Win of the 1st team': '1.87',
                      '1-st map: Win of the 2nd team': '1.87',
                      '1-st map: ambush Handicap value. –2.5. Handicap coefficient': '2.11',
                      '1-st map: tricked Handicap value. +2.5. Handicap coefficient': '1.68',
                      'Total. 2.5. Over': '1.92',
                      'Total. 2.5. Under': '1.82',
                      'Win of the 1st team': '1.87',
                      'Win of the 2nd team': '1.87',
                      'ambush Handicap value. –1.5. Handicap coefficient': '3.55',
                      'tricked Handicap value. +1.5. Handicap coefficient': '1.27',
                      'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced'},
 'apeks - winstrike': {'1-st map: Total. 26.5. Over': '1.77',
                       '1-st map: Total. 26.5. Under': '1.97',
                       '1-st map: Win of the 1st team': '2.08',
                       '1-st map: Win of the 2nd team': '1.70',
                       '1-st map: apeks Handicap value. +2.5. Handicap coefficient': '1.85',
                       '1-st map: winstrike Handicap value. –2.5. Handicap coefficient': '1.90',
                       'Total. 2.5. Over': '2.00',
                       'Total. 2.5. Under': '1.76',
                       'Win of the 1st team': '2.25',
                       'Win of the 2nd team': '1.60',
                       'apeks Handicap value. +1.5. Handicap coefficient': '1.38',
                       'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced',
                       'winstrike Handicap value. –1.5. Handicap coefficient': '2.90'},
 'avez - nexus': {'1-st map: Total. 26.5. Over': '1.85',
                  '1-st map: Total. 26.5. Under': '1.90',
                  '1-st map: Win of the 1st team': '1.55',
                  '1-st map: Win of the 2nd team': '2.35',
                  '1-st map: avez Handicap value. –2.5. Handicap coefficient': '1.75',
                  '1-st map: nexus Handicap value. +2.5. Handicap coefficient': '2.01',
                  'Total. 2.5. Over': '2.01',
                  'Total. 2.5. Under': '1.75',
                  'Win of the 1st team': '1.45',
                  'Win of the 2nd team': '2.62',
                  'avez Handicap value. –1.5. Handicap coefficient': '2.42',
                  'nexus Handicap value. +1.5. Handicap coefficient': '1.52',
                  'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five'},
 'blinkal - qske': {'Win of the 1st team': '1.80',
                    'Win of the 2nd team': '1.95',
                    'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-a1-adria-league'},
 'cool - exploit': {'Win of the 1st team': '3.54',
                    'Win of the 2nd team': '1.27',
                    'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-betano-masters-eu'},
 'cool - unicorns of love': {'Win of the 1st team': '5.00',
                             'Win of the 2nd team': '1.15',
                             'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-betano-masters-eu'},
 'evil geniuses - gen.g': {'1-st map: Total. 25.5. Over': '1.57',
                           '1-st map: Total. 25.5. Under': '2.31',
                           '1-st map: Total. 26.5. Over': '1.85',
                           '1-st map: Total. 26.5. Under': '1.90',
                           '1-st map: Total. 27.5. Over': '2.20',
                           '1-st map: Total. 27.5. Under': '1.62',
                           '1-st map: Win of the 1st team': '1.55',
                           '1-st map: Win of the 2nd team': '2.35',
                           '1-st map: evil geniuses Handicap value. –2.5. Handicap coefficient': '1.75',
                           '1-st map: evil geniuses Handicap value. –3.5. Handicap coefficient': '2.00',
                           '1-st map: evil geniuses Handicap value. –4.5. Handicap coefficient': '2.35',
                           '1-st map: gen.g Handicap value. +2.5. Handicap coefficient': '2.01',
                           '1-st map: gen.g Handicap value. +3.5. Handicap coefficient': '1.76',
                           '1-st map: gen.g Handicap value. +4.5. Handicap coefficient': '1.55',
                           'Total. 3.5. Over': '1.62',
                           'Total. 3.5. Under': '2.21',
                           'Win of the 1st team': '1.20',
                           'Win of the 2nd team': '4.23',
                           'evil geniuses Handicap value. –2.5. Handicap coefficient': '2.20',
                           'gen.g Handicap value. +2.5. Handicap coefficient': '1.63',
                           'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-cs_summit-na'},
 'ex-smash - ago': {'1-st map: Total. 25.5. Over': '1.47',
                    '1-st map: Total. 25.5. Under': '2.55',
                    '1-st map: Total. 26.5. Over': '1.77',
                    '1-st map: Total. 26.5. Under': '1.97',
                    '1-st map: Total. 27.5. Over': '2.15',
                    '1-st map: Total. 27.5. Under': '1.65',
                    '1-st map: Win of the 1st team': '2.01',
                    '1-st map: Win of the 2nd team': '1.75',
                    '1-st map: ago Handicap value. +2.5. Handicap coefficient': '1.55',
                    '1-st map: ago Handicap value. –2.5. Handicap coefficient': '2.00',
                    '1-st map: ago Handicap value. –3.5. Handicap coefficient': '2.30',
                    '1-st map: ex-smash Handicap value. +2.5. Handicap coefficient': '1.76',
                    '1-st map: ex-smash Handicap value. +3.5. Handicap coefficient': '1.58',
                    '1-st map: ex-smash Handicap value. –2.5. Handicap coefficient': '2.35',
                    'Total. 2.5. Over': '1.95',
                    'Total. 2.5. Under': '1.80',
                    'Win of the 1st team': '2.15',
                    'Win of the 2nd team': '1.65',
                    'ago Handicap value. –1.5. Handicap coefficient': '3.05',
                    'ex-smash Handicap value. +1.5. Handicap coefficient': '1.35',
                    'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes'},
 'ex-smash - sg.pro': {'1-st map: Total. 26.5. Over': '1.92',
                       '1-st map: Total. 26.5. Under': '1.82',
                       '1-st map: Win of the 1st team': '1.40',
                       '1-st map: Win of the 2nd team': '2.80',
                       '1-st map: ex-smash Handicap value. –3.5. Handicap coefficient': '1.80',
                       '1-st map: sg.pro Handicap value. +3.5. Handicap coefficient': '1.95',
                       'Total. 2.5. Over': '2.25',
                       'Total. 2.5. Under': '1.60',
                       'Win of the 1st team': '1.30',
                       'Win of the 2nd team': '3.30',
                       'ex-smash Handicap value. –1.5. Handicap coefficient': '1.97',
                       'sg.pro Handicap value. +1.5. Handicap coefficient': '1.77',
                       'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five'},
 'fate - izako boars': {'1-st map: Total. 26.5. Over': '1.95',
                        '1-st map: Total. 26.5. Under': '1.80',
                        '1-st map: Win of the 1st team': '1.35',
                        '1-st map: Win of the 2nd team': '3.05',
                        '1-st map: fate Handicap value. –4.5. Handicap coefficient': '1.97',
                        '1-st map: izako boars Handicap value. +4.5. Handicap coefficient': '1.77',
                        'Total. 2.5. Over': '2.35',
                        'Total. 2.5. Under': '1.55',
                        'Win of the 1st team': '1.25',
                        'Win of the 2nd team': '3.75',
                        'fate Handicap value. –1.5. Handicap coefficient': '1.82',
                        'izako boars Handicap value. +1.5. Handicap coefficient': '1.92',
                        'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five'},
 'ground zero - rooster': {'1-st map: Total. 25.5. Over': '1.57',
                           '1-st map: Total. 25.5. Under': '2.31',
                           '1-st map: Total. 26.5. Over': '1.85',
                           '1-st map: Total. 26.5. Under': '1.90',
                           '1-st map: Total. 27.5. Over': '2.20',
                           '1-st map: Total. 27.5. Under': '1.62',
                           '1-st map: Win of the 1st team': '2.35',
                           '1-st map: Win of the 2nd team': '1.55',
                           '1-st map: ground zero Handicap value. +2.5. Handicap coefficient': '2.01',
                           '1-st map: ground zero Handicap value. +3.5. Handicap coefficient': '1.76',
                           '1-st map: ground zero Handicap value. +4.5. Handicap coefficient': '1.55',
                           '1-st map: rooster Handicap value. –2.5. Handicap coefficient': '1.75',
                           '1-st map: rooster Handicap value. –3.5. Handicap coefficient': '2.00',
                           '1-st map: rooster Handicap value. –4.5. Handicap coefficient': '2.35',
                           'Total. 2.5. Over': '2.01',
                           'Total. 2.5. Under': '1.75',
                           'Win of the 1st team': '2.62',
                           'Win of the 2nd team': '1.45',
                           'ground zero Handicap value. +1.5. Handicap coefficient': '1.52',
                           'rooster Handicap value. –1.5. Handicap coefficient': '2.42',
                           'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-au'},
 'honoris - wizards': {'1-st map: Total. 26.5. Over': '1.92',
                       '1-st map: Total. 26.5. Under': '1.82',
                       '1-st map: Win of the 1st team': '1.40',
                       '1-st map: Win of the 2nd team': '2.80',
                       '1-st map: honoris Handicap value. –3.5. Handicap coefficient': '1.80',
                       '1-st map: wizards Handicap value. +3.5. Handicap coefficient': '1.95',
                       'Total. 2.5. Over': '2.25',
                       'Total. 2.5. Under': '1.60',
                       'Win of the 1st team': '1.30',
                       'Win of the 2nd team': '3.30',
                       'honoris Handicap value. –1.5. Handicap coefficient': '1.97',
                       'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five',
                       'wizards Handicap value. +1.5. Handicap coefficient': '1.77'},
 'illuminar - wisla krakow': {'1-st map: Total. 26.5. Over': '1.85',
                              '1-st map: Total. 26.5. Under': '1.90',
                              '1-st map: Win of the 1st team': '1.55',
                              '1-st map: Win of the 2nd team': '2.35',
                              '1-st map: illuminar Handicap value. –2.5. Handicap coefficient': '1.75',
                              '1-st map: wisla krakow Handicap value. +2.5. Handicap coefficient': '2.01',
                              'Total. 2.5. Over': '2.01',
                              'Total. 2.5. Under': '1.75',
                              'Win of the 1st team': '1.45',
                              'Win of the 2nd team': '2.62',
                              'illuminar Handicap value. –1.5. Handicap coefficient': '2.42',
                              'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five',
                              'wisla krakow Handicap value. +1.5. Handicap coefficient': '1.52'},
 'imperium - eternal': {'Win of the 1st team': '1.95',
                        'Win of the 2nd team': '1.80',
                        'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-winners-league-na-main-division'},
 'kova - havu': {'Win of the 1st team': '3.33',
                 'Win of the 2nd team': '1.30',
                 'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-finnish-esports-league'},
 'ldlc - cr4zy': {'1-st map: Total. 26.5. Over': '1.75',
                  '1-st map: Total. 26.5. Under': '2.01',
                  '1-st map: Win of the 1st team': '1.92',
                  '1-st map: Win of the 2nd team': '1.82',
                  '1-st map: cr4zy Handicap value. –2.5. Handicap coefficient': '2.05',
                  '1-st map: ldlc Handicap value. +2.5. Handicap coefficient': '1.72',
                  'Total. 2.5. Over': '1.95',
                  'Total. 2.5. Under': '1.80',
                  'Win of the 1st team': '2.01',
                  'Win of the 2nd team': '1.75',
                  'cr4zy Handicap value. –1.5. Handicap coefficient': '3.30',
                  'ldlc Handicap value. +1.5. Handicap coefficient': '1.30',
                  'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five'},
 'ldlc - lilmix': {'1-st map: Total. 26.5. Over': '1.90',
                   '1-st map: Total. 26.5. Under': '1.85',
                   '1-st map: Win of the 1st team': '1.45',
                   '1-st map: Win of the 2nd team': '2.62',
                   '1-st map: ldlc Handicap value. –3.5. Handicap coefficient': '1.87',
                   '1-st map: lilmix Handicap value. +3.5. Handicap coefficient': '1.87',
                   'Total. 2.5. Over': '2.20',
                   'Total. 2.5. Under': '1.62',
                   'Win of the 1st team': '1.35',
                   'Win of the 2nd team': '3.05',
                   'ldlc Handicap value. –1.5. Handicap coefficient': '2.11',
                   'lilmix Handicap value. +1.5. Handicap coefficient': '1.68',
                   'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced'},
 'mythic - ex-polar ace': {'Win of the 1st team': '1.26',
                           'Win of the 2nd team': '3.62',
                           'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-invite-league'},
 'nexus - the dice': {'1-st map: Total. 26.5. Over': '1.77',
                      '1-st map: Total. 26.5. Under': '1.97',
                      '1-st map: Win of the 1st team': '1.70',
                      '1-st map: Win of the 2nd team': '2.08',
                      '1-st map: nexus Handicap value. –2.5. Handicap coefficient': '1.90',
                      '1-st map: the dice Handicap value. +2.5. Handicap coefficient': '1.85',
                      'Total. 2.5. Over': '2.00',
                      'Total. 2.5. Under': '1.76',
                      'Win of the 1st team': '1.60',
                      'Win of the 2nd team': '2.25',
                      'nexus Handicap value. –1.5. Handicap coefficient': '2.90',
                      'the dice Handicap value. +1.5. Handicap coefficient': '1.38',
                      'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced'},
 'oceanus - new england whalers': {'Win of the 1st team': '2.74',
                                   'Win of the 2nd team': '1.42',
                                   'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-invite-league'},
 'order - ground zero': {'1-st map: Total. 26.5. Over': '2.00',
                         '1-st map: Total. 26.5. Under': '1.76',
                         '1-st map: Win of the 1st team': '1.30',
                         '1-st map: Win of the 2nd team': '3.30',
                         '1-st map: ground zero Handicap value. +4.5. Handicap coefficient': '1.90',
                         '1-st map: order Handicap value. –4.5. Handicap coefficient': '1.85',
                         'Total. 2.5. Over': '2.42',
                         'Total. 2.5. Under': '1.52',
                         'Win of the 1st team': '1.20',
                         'Win of the 2nd team': '4.20',
                         'ground zero Handicap value. +1.5. Handicap coefficient': '2.08',
                         'order Handicap value. –1.5. Handicap coefficient': '1.70',
                         'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-dreamhack-open-oc-qualifier'},
 'rooster - chiefs': {'1-st map: Total. 26.5. Over': '1.82',
                      '1-st map: Total. 26.5. Under': '1.92',
                      '1-st map: Win of the 1st team': '2.25',
                      '1-st map: Win of the 2nd team': '1.60',
                      '1-st map: chiefs Handicap value. –2.5. Handicap coefficient': '1.80',
                      '1-st map: rooster Handicap value. +2.5. Handicap coefficient': '1.95',
                      'Total. 2.5. Over': '2.01',
                      'Total. 2.5. Under': '1.75',
                      'Win of the 1st team': '2.48',
                      'Win of the 2nd team': '1.50',
                      'chiefs Handicap value. –1.5. Handicap coefficient': '2.62',
                      'rooster Handicap value. +1.5. Handicap coefficient': '1.45',
                      'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-dreamhack-open-oc-qualifier'},
 'sangal - tikitakan': {'1-st map: Total. 26.5. Over': '1.87',
                        '1-st map: Total. 26.5. Under': '1.87',
                        '1-st map: Win of the 1st team': '1.50',
                        '1-st map: Win of the 2nd team': '2.48',
                        '1-st map: sangal Handicap value. –3.5. Handicap coefficient': '1.92',
                        '1-st map: tikitakan Handicap value. +3.5. Handicap coefficient': '1.82',
                        'Total. 2.5. Over': '2.08',
                        'Total. 2.5. Under': '1.70',
                        'Win of the 1st team': '1.40',
                        'Win of the 2nd team': '2.80',
                        'sangal Handicap value. –1.5. Handicap coefficient': '2.25',
                        'tikitakan Handicap value. +1.5. Handicap coefficient': '1.60',
                        'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced'},
 'saw - agf': {'1-st map: Total. 26.5. Over': '1.90',
               '1-st map: Total. 26.5. Under': '1.85',
               '1-st map: Win of the 1st team': '1.45',
               '1-st map: Win of the 2nd team': '2.62',
               '1-st map: agf Handicap value. +3.5. Handicap coefficient': '1.87',
               '1-st map: saw Handicap value. –3.5. Handicap coefficient': '1.87',
               'Total. 2.5. Over': '2.20',
               'Total. 2.5. Under': '1.62',
               'Win of the 1st team': '1.35',
               'Win of the 2nd team': '3.05',
               'agf Handicap value. +1.5. Handicap coefficient': '1.68',
               'saw Handicap value. –1.5. Handicap coefficient': '2.11',
               'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five'},
 'saw - nordavind': {'1-st map: Total. 25.5. Over': '1.46',
                     '1-st map: Total. 25.5. Under': '2.60',
                     '1-st map: Total. 26.5. Over': '1.72',
                     '1-st map: Total. 26.5. Under': '2.05',
                     '1-st map: Total. 27.5. Over': '2.12',
                     '1-st map: Total. 27.5. Under': '1.67',
                     '1-st map: Win of the 1st team': '1.90',
                     '1-st map: Win of the 2nd team': '1.85',
                     '1-st map: nordavind Handicap value. +2.5. Handicap coefficient': '1.65',
                     '1-st map: nordavind Handicap value. –2.5. Handicap coefficient': '2.08',
                     '1-st map: nordavind Handicap value. –3.5. Handicap coefficient': '2.42',
                     '1-st map: saw Handicap value. +2.5. Handicap coefficient': '1.70',
                     '1-st map: saw Handicap value. +3.5. Handicap coefficient': '1.52',
                     '1-st map: saw Handicap value. –2.5. Handicap coefficient': '2.15',
                     'Total. 2.5. Over': '1.87',
                     'Total. 2.5. Under': '1.87',
                     'Win of the 1st team': '1.95',
                     'Win of the 2nd team': '1.80',
                     'nordavind Handicap value. –1.5. Handicap coefficient': '3.45',
                     'saw Handicap value. +1.5. Handicap coefficient': '1.28',
                     'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes'},
 'secret - saw': {'1-st map: Total. 26.5. Over': '1.77',
                  '1-st map: Total. 26.5. Under': '1.97',
                  '1-st map: Win of the 1st team': '2.08',
                  '1-st map: Win of the 2nd team': '1.70',
                  '1-st map: saw Handicap value. –2.5. Handicap coefficient': '1.90',
                  '1-st map: secret Handicap value. +2.5. Handicap coefficient': '1.85',
                  'Total. 2.5. Over': '2.00',
                  'Total. 2.5. Under': '1.76',
                  'Win of the 1st team': '2.25',
                  'Win of the 2nd team': '1.60',
                  'saw Handicap value. –1.5. Handicap coefficient': '2.90',
                  'secret Handicap value. +1.5. Handicap coefficient': '1.38',
                  'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced'},
 'sprout - hard legion': {'1-st map: Total. 25.5. Over': '1.55',
                          '1-st map: Total. 25.5. Under': '2.35',
                          '1-st map: Total. 26.5. Over': '1.82',
                          '1-st map: Total. 26.5. Under': '1.92',
                          '1-st map: Total. 27.5. Over': '2.20',
                          '1-st map: Total. 27.5. Under': '1.62',
                          '1-st map: Win of the 1st team': '1.58',
                          '1-st map: Win of the 2nd team': '2.29',
                          '1-st map: hard legion Handicap value. +2.5. Handicap coefficient': '1.95',
                          '1-st map: hard legion Handicap value. +3.5. Handicap coefficient': '1.68',
                          '1-st map: hard legion Handicap value. +4.5. Handicap coefficient': '1.50',
                          '1-st map: sprout Handicap value. –2.5. Handicap coefficient': '1.80',
                          '1-st map: sprout Handicap value. –3.5. Handicap coefficient': '2.11',
                          '1-st map: sprout Handicap value. –4.5. Handicap coefficient': '2.48',
                          'Total. 2.5. Over': '2.01',
                          'Total. 2.5. Under': '1.75',
                          'Win of the 1st team': '1.47',
                          'Win of the 2nd team': '2.57',
                          'hard legion Handicap value. +1.5. Handicap coefficient': '1.45',
                          'sprout Handicap value. –1.5. Handicap coefficient': '2.62',
                          'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-hellcase-cup'},
 'sws - bravos': {'Win of the 1st team': '2.08',
                  'Win of the 2nd team': '1.70',
                  'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-clutch'},
 'syman - adaptation': {'1-st map: Total. 25.5. Over': '1.80',
                        '1-st map: Total. 25.5. Under': '1.95',
                        '1-st map: Win of the 1st team': '1.25',
                        '1-st map: Win of the 2nd team': '3.75',
                        '1-st map: adaptation Handicap value. +4.5. Handicap coefficient': '2.01',
                        '1-st map: syman Handicap value. –4.5. Handicap coefficient': '1.75',
                        'Total. 2.5. Over': '2.55',
                        'Total. 2.5. Under': '1.47',
                        'Win of the 1st team': '1.15',
                        'Win of the 2nd team': '5.00',
                        'adaptation Handicap value. +1.5. Handicap coefficient': '2.35',
                        'syman Handicap value. –1.5. Handicap coefficient': '1.55',
                        'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five'},
 'teamone - alcoholics anonymous': {'Win of the 1st team': '1.42',
                                    'Win of the 2nd team': '2.74',
                                    'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-invite-league'},
 'third impact - valkyrie': {'Win of the 1st team': '1.35',
                             'Win of the 2nd team': '3.04',
                             'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-winners-league-na-main-division'},
 'tiger - vici': {'1-st map: Total. 26.5. Over': '1.87',
                  '1-st map: Total. 26.5. Under': '1.87',
                  '1-st map: Win of the 1st team': '2.48',
                  '1-st map: Win of the 2nd team': '1.50',
                  '1-st map: tiger Handicap value. +3.5. Handicap coefficient': '1.82',
                  '1-st map: vici Handicap value. –3.5. Handicap coefficient': '1.92',
                  'Total. 2.5. Over': '2.08',
                  'Total. 2.5. Under': '1.70',
                  'Win of the 1st team': '2.80',
                  'Win of the 2nd team': '1.40',
                  'tiger Handicap value. +1.5. Handicap coefficient': '1.60',
                  'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league',
                  'vici Handicap value. –1.5. Handicap coefficient': '2.25'},
 'triumph - yeah': {'1-st map: Total. 26.5. Over': '1.92',
                    '1-st map: Total. 26.5. Under': '1.82',
                    '1-st map: Win of the 1st team': '1.40',
                    '1-st map: Win of the 2nd team': '2.80',
                    '1-st map: triumph Handicap value. –3.5. Handicap coefficient': '1.80',
                    '1-st map: yeah Handicap value. +3.5. Handicap coefficient': '1.95',
                    'Total. 2.5. Over': '2.25',
                    'Total. 2.5. Under': '1.60',
                    'Win of the 1st team': '1.30',
                    'Win of the 2nd team': '3.30',
                    'triumph Handicap value. –1.5. Handicap coefficient': '1.97',
                    'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-winners-league-na',
                    'yeah Handicap value. +1.5. Handicap coefficient': '1.77'},
 'twa - chiefs': {'1-st map: Total. 25.5. Over': '1.80',
                  '1-st map: Total. 25.5. Under': '1.95',
                  '1-st map: Total. 26.5. Over': '2.08',
                  '1-st map: Total. 26.5. Under': '1.70',
                  '1-st map: Total. 27.5. Over': '2.65',
                  '1-st map: Total. 27.5. Under': '1.44',
                  '1-st map: Win of the 1st team': '3.75',
                  '1-st map: Win of the 2nd team': '1.25',
                  '1-st map: chiefs Handicap value. –3.5. Handicap coefficient': '1.55',
                  '1-st map: chiefs Handicap value. –4.5. Handicap coefficient': '1.75',
                  '1-st map: chiefs Handicap value. –5.5. Handicap coefficient': '2.00',
                  '1-st map: twa Handicap value. +3.5. Handicap coefficient': '2.35',
                  '1-st map: twa Handicap value. +4.5. Handicap coefficient': '2.01',
                  '1-st map: twa Handicap value. +5.5. Handicap coefficient': '1.76',
                  'Total. 2.5. Over': '2.55',
                  'Total. 2.5. Under': '1.47',
                  'Win of the 1st team': '5.00',
                  'Win of the 2nd team': '1.15',
                  'chiefs Handicap value. –1.5. Handicap coefficient': '1.55',
                  'twa Handicap value. +1.5. Handicap coefficient': '2.35',
                  'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-au'},
 'tyloo - beyond': {'1-st map: Total. 26.5. Over': '2.00',
                    '1-st map: Total. 26.5. Under': '1.76',
                    '1-st map: Win of the 1st team': '1.30',
                    '1-st map: Win of the 2nd team': '3.30',
                    '1-st map: beyond Handicap value. +4.5. Handicap coefficient': '1.90',
                    '1-st map: tyloo Handicap value. –4.5. Handicap coefficient': '1.85',
                    'Total. 2.5. Over': '2.42',
                    'Total. 2.5. Under': '1.52',
                    'Win of the 1st team': '1.20',
                    'Win of the 2nd team': '4.20',
                    'beyond Handicap value. +1.5. Handicap coefficient': '2.08',
                    'tyloo Handicap value. –1.5. Handicap coefficient': '1.70',
                    'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league'},
 'unicorns of love - exploit': {'Win of the 1st team': '1.43',
                                'Win of the 2nd team': '2.70',
                                'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-betano-masters-eu'},
 'vitality - big': {'1-st map: Total. 25.5. Over': '1.45',
                    '1-st map: Total. 25.5. Under': '2.62',
                    '1-st map: Total. 26.5. Over': '1.72',
                    '1-st map: Total. 26.5. Under': '2.05',
                    '1-st map: Total. 27.5. Over': '2.12',
                    '1-st map: Total. 27.5. Under': '1.67',
                    '1-st map: Win of the 1st team': '1.85',
                    '1-st map: Win of the 2nd team': '1.90',
                    '1-st map: big Handicap value. +2.5. Handicap coefficient': '1.70',
                    '1-st map: big Handicap value. +3.5. Handicap coefficient': '1.52',
                    '1-st map: big Handicap value. –2.5. Handicap coefficient': '2.15',
                    '1-st map: vitality Handicap value. +2.5. Handicap coefficient': '1.65',
                    '1-st map: vitality Handicap value. –2.5. Handicap coefficient': '2.08',
                    '1-st map: vitality Handicap value. –3.5. Handicap coefficient': '2.42',
                    'Total. 4.5. Over': '2.62',
                    'Total. 4.5. Under': '1.45',
                    'Win of the 1st team': '1.35',
                    'Win of the 2nd team': '3.05',
                    'big Handicap value. +1.5. Handicap coefficient': '1.95',
                    'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-cs_summit-eu',
                    'vitality Handicap value. –1.5. Handicap coefficient': '1.80'},
 'yeah - swedish canadians': {'Win of the 1st team': '1.70',
                              'Win of the 2nd team': '2.08',
                              'url': 'https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-invite-league'}}
