sport = {'csgo': {'atrapa2 - hawks': {'Win of the 1st team': ['4.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)'], 'Win of the 2nd team': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)']},
          'berzerk - penta': {'Away win': ['2.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-99liga)'],
                              'Draw': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-99liga)'],
                              'Home win': ['3.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-99liga)']},
          'bluejays international - down2earth': {'Win of the 1st team': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-winners-league-eu-main-division)'],
                                                  'Win of the 2nd team': ['2.43(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-winners-league-eu-main-division)']},
          'coliseo dragons - atrapa2': {'Win of the 1st team': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)'], 'Win of the 2nd team': ['2.36(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)']},
          'coscu army - aion': {'Win of the 1st team': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)'], 'Win of the 2nd team': ['2.36(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)']},
          'endpoint - alternate attax': {'1-st map: Total. 26.5. Over': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         '1-st map: Total. 26.5. Under': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         '1-st map: Win of the 1st team': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         '1-st map: Win of the 2nd team': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         '1-st map: alternate attax Handicap value. +2.5. Handicap coefficient': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         '1-st map: endpoint Handicap value. –2.5. Handicap coefficient': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         'Total. 2.5. Over': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         'Total. 2.5. Under': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         'Win of the 1st team': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         'Win of the 2nd team': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         'alternate attax Handicap value. +1.5. Handicap coefficient': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                         'endpoint Handicap value. –1.5. Handicap coefficient': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)']},
          'fate - budapest five': {'1-st map: Total. 26.5. Over': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '1-st map: Total. 26.5. Under': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '1-st map: budapest five Handicap value. +2.5. Handicap coefficient': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '1-st map: fate Handicap value. –2.5. Handicap coefficient': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   'Win of the 1st team': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   'Win of the 2nd team': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '\xa0 Total. 25.5. Over': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '\xa0 Total. 25.5. Under': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '\xa0 Total. 27.5. Over': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '\xa0 Total. 27.5. Under': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '\xa0 budapest five Handicap value. +3.5. Handicap coefficient': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '\xa0 budapest five Handicap value. –2.5. Handicap coefficient': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '\xa0 fate Handicap value. +2.5. Handicap coefficient': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                   '\xa0 fate Handicap value. –3.5. Handicap coefficient': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)']},
          'furious - coliseo dragons': {'Win of the 1st team': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)'], 'Win of the 2nd team': ['3.33(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)']},
          'gambit youngsters - syman': {'1-st map: Total. 26.5. Over': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        '1-st map: Total. 26.5. Under': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        '1-st map: Win of the 1st team': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        '1-st map: Win of the 2nd team': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        '1-st map: gambit youngsters Handicap value. –4.5. Handicap coefficient': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        '1-st map: syman Handicap value. +4.5. Handicap coefficient': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        'Total. 2.5. Over': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        'Total. 2.5. Under': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        'Win of the 1st team': ['1.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        'Win of the 2nd team': ['3.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        'gambit youngsters Handicap value. –1.5. Handicap coefficient': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                        'syman Handicap value. +1.5. Handicap coefficient': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)']},
          'hard legion - avez': {'1-st map: Total. 26.5. Over': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 '1-st map: Total. 26.5. Under': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 '1-st map: Win of the 1st team': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 '1-st map: Win of the 2nd team': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 '1-st map: avez Handicap value. –2.5. Handicap coefficient': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 '1-st map: hard legion Handicap value. +2.5. Handicap coefficient': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 'Total. 2.5. Over': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 'Total. 2.5. Under': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 'Win of the 1st team': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 'Win of the 2nd team': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 'avez Handicap value. –1.5. Handicap coefficient': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                 'hard legion Handicap value. +1.5. Handicap coefficient': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)']},
          'hawks - wygers argentina': {'Win of the 1st team': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)'], 'Win of the 2nd team': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)']},
          'hellraisers - honoris': {'1-st map: Total. 26.5. Over': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '1-st map: Total. 26.5. Under': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '1-st map: hellraisers Handicap value. –3.5. Handicap coefficient': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '1-st map: honoris Handicap value. +3.5. Handicap coefficient': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    'Win of the 1st team': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    'Win of the 2nd team': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '\xa0 Total. 25.5. Over': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '\xa0 Total. 25.5. Under': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '\xa0 Total. 27.5. Over': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '\xa0 Total. 27.5. Under': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '\xa0 hellraisers Handicap value. –2.5. Handicap coefficient': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '\xa0 hellraisers Handicap value. –4.5. Handicap coefficient': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '\xa0 honoris Handicap value. +2.5. Handicap coefficient': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                    '\xa0 honoris Handicap value. +4.5. Handicap coefficient': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)']},
          'invictus gaming - d13': {'1-st map: Total. 26.5. Over': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    '1-st map: Total. 26.5. Under': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    '1-st map: Win of the 1st team': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    '1-st map: Win of the 2nd team': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    '1-st map: d13 Handicap value. +4.5. Handicap coefficient': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    '1-st map: invictus gaming Handicap value. –4.5. Handicap coefficient': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    'Total. 2.5. Over': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    'Total. 2.5. Under': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    'Win of the 1st team': ['1.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    'Win of the 2nd team': ['3.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    'd13 Handicap value. +1.5. Handicap coefficient': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                    'invictus gaming Handicap value. –1.5. Handicap coefficient': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)']},
          'lbs - coscu army': {'Win of the 1st team': ['3.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)'], 'Win of the 2nd team': ['1.36(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)']},
          "let's quit - zero": {'Win of the 1st team': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-farmskins-streamer-masters)'], 'Win of the 2nd team': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-farmskins-streamer-masters)']},
          'levitate - oceanus': {'Win of the 1st team': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-golden-league)'], 'Win of the 2nd team': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-golden-league)']},
          'malvinas - aion': {'Win of the 1st team': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)'], 'Win of the 2nd team': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)']},
          'next - nopainnogain': {'1-st map: Away win': ['2.21(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: Home win': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: Total. 25.5. Over': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: Total. 25.5. Under': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: next Handicap value. –2.5. Handicap coefficient': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: next Handicap value. –3.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: next Handicap value. –4.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: nopainnogain Handicap value. +2.5. Handicap coefficient': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: nopainnogain Handicap value. +3.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '1-st map: nopainnogain Handicap value. +4.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: Away win': ['2.21(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: Home win': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: Total. 25.5. Over': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: Total. 25.5. Under': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: next Handicap value. –2.5. Handicap coefficient': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: next Handicap value. –3.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: next Handicap value. –4.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: nopainnogain Handicap value. +2.5. Handicap coefficient': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: nopainnogain Handicap value. +3.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  '2-nd map: nopainnogain Handicap value. +4.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  'Away win': ['4.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  'Draw': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  'Home win': ['2.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  'next Handicap value. –0.5. Handicap coefficient': ['2.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                  'nopainnogain Handicap value. +0.5. Handicap coefficient': ['1.46(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)']},
          'next - royalty': {'1-st map: Away win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: Home win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: Total. 25.5. Over': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: Total. 25.5. Under': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: next Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: next Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: next Handicap value. –3.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: royalty Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: royalty Handicap value. +3.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '1-st map: royalty Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: Away win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: Home win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: Total. 25.5. Over': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: Total. 25.5. Under': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: next Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: next Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: next Handicap value. –3.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: royalty Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: royalty Handicap value. +3.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             '2-nd map: royalty Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             'Away win': ['3.43(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             'Draw': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             'Home win': ['3.44(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             'next Handicap value. –0.5. Handicap coefficient': ['3.44(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                             'royalty Handicap value. +0.5. Handicap coefficient': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)']},
          'nexus - big academy': {'Win of the 1st team': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-betano-masters-eu)'], 'Win of the 2nd team': ['2.63(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-betano-masters-eu)']},
          'nocturns - furious': {'Win of the 1st team': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)'], 'Win of the 2nd team': ['1.98(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)']},
          'nocturns - malvinas': {'Win of the 1st team': ['3.04(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)'], 'Win of the 2nd team': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)']},
          'nopainnogain - royalty': {'1-st map: Away win': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: Home win': ['2.21(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: Total. 25.5. Over': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: Total. 25.5. Under': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: nopainnogain Handicap value. +2.5. Handicap coefficient': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: nopainnogain Handicap value. +3.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: nopainnogain Handicap value. +4.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: royalty Handicap value. –2.5. Handicap coefficient': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: royalty Handicap value. –3.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '1-st map: royalty Handicap value. –4.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: Away win': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: Home win': ['2.21(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: Total. 25.5. Over': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: Total. 25.5. Under': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: nopainnogain Handicap value. +2.5. Handicap coefficient': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: nopainnogain Handicap value. +3.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: nopainnogain Handicap value. +4.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: royalty Handicap value. –2.5. Handicap coefficient': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: royalty Handicap value. –3.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     '2-nd map: royalty Handicap value. –4.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     'Away win': ['2.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     'Draw': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     'Home win': ['4.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     'nopainnogain Handicap value. +0.5. Handicap coefficient': ['1.46(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                     'royalty Handicap value. –0.5. Handicap coefficient': ['2.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)']},
          'pact - singularity': {'1-st map: Total. 26.5. Over': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '1-st map: Total. 26.5. Under': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '1-st map: pact Handicap value. –3.5. Handicap coefficient': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '1-st map: singularity Handicap value. +3.5. Handicap coefficient': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 'Win of the 1st team': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 'Win of the 2nd team': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '\xa0 Total. 25.5. Over': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '\xa0 Total. 25.5. Under': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '\xa0 Total. 27.5. Over': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '\xa0 Total. 27.5. Under': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '\xa0 pact Handicap value. –2.5. Handicap coefficient': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '\xa0 pact Handicap value. –4.5. Handicap coefficient': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '\xa0 singularity Handicap value. +2.5. Handicap coefficient': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                 '\xa0 singularity Handicap value. +4.5. Handicap coefficient': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)']},
          'rbg - revenant': {'Win of the 1st team': ['1.17(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-golden-league)'], 'Win of the 2nd team': ['4.66(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-golden-league)']},
          'sampi - brute': {'Win of the 1st team': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-winners-league-eu-main-division)'],
                            'Win of the 2nd team': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-winners-league-eu-main-division)']},
          'saw - nexus': {'1-st map: Total. 26.5. Over': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          '1-st map: Total. 26.5. Under': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          '1-st map: Win of the 1st team': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          '1-st map: Win of the 2nd team': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          '1-st map: nexus Handicap value. +2.5. Handicap coefficient': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          '1-st map: saw Handicap value. –2.5. Handicap coefficient': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          'Total. 2.5. Over': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          'Total. 2.5. Under': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          'Win of the 1st team': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          'Win of the 2nd team': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          'nexus Handicap value. +1.5. Handicap coefficient': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                          'saw Handicap value. –1.5. Handicap coefficient': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)']},
          'secret - agf': {'1-st map: Total. 26.5. Over': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           '1-st map: Total. 26.5. Under': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           '1-st map: Win of the 1st team': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           '1-st map: Win of the 2nd team': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           '1-st map: agf Handicap value. +2.5. Handicap coefficient': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           '1-st map: secret Handicap value. –2.5. Handicap coefficient': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           'Total. 2.5. Over': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           'Total. 2.5. Under': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           'Win of the 1st team': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           'Win of the 2nd team': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           'agf Handicap value. +1.5. Handicap coefficient': ['1.33(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                           'secret Handicap value. –1.5. Handicap coefficient': ['3.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)']},
          'secret - tricked': {'1-st map: Total. 26.5. Over': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               '1-st map: Total. 26.5. Under': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               '1-st map: Win of the 1st team': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               '1-st map: Win of the 2nd team': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               '1-st map: secret Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               '1-st map: tricked Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               'Total. 2.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               'Total. 2.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               'Win of the 1st team': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               'Win of the 2nd team': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               'secret Handicap value. –1.5. Handicap coefficient': ['3.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)'],
                               'tricked Handicap value. +1.5. Handicap coefficient': ['1.27(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)']},
          'spassion - next': {'1-st map: Away win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: Home win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: Total. 25.5. Over': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: Total. 25.5. Under': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: next Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: next Handicap value. +3.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: next Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: spassion Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: spassion Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '1-st map: spassion Handicap value. –3.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: Away win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: Home win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: Total. 25.5. Over': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: Total. 25.5. Under': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: next Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: next Handicap value. +3.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: next Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: spassion Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: spassion Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              '2-nd map: spassion Handicap value. –3.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              'Away win': ['3.43(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              'Draw': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              'Home win': ['3.44(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              'next Handicap value. +0.5. Handicap coefficient': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                              'spassion Handicap value. –0.5. Handicap coefficient': ['3.44(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)']},
          'spassion - nopainnogain': {'1-st map: Away win': ['2.21(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: Home win': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: Total. 25.5. Over': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: Total. 25.5. Under': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: nopainnogain Handicap value. +2.5. Handicap coefficient': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: nopainnogain Handicap value. +3.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: nopainnogain Handicap value. +4.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: spassion Handicap value. –2.5. Handicap coefficient': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: spassion Handicap value. –3.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '1-st map: spassion Handicap value. –4.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: Away win': ['2.21(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: Home win': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: Total. 25.5. Over': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: Total. 25.5. Under': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: nopainnogain Handicap value. +2.5. Handicap coefficient': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: nopainnogain Handicap value. +3.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: nopainnogain Handicap value. +4.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: spassion Handicap value. –2.5. Handicap coefficient': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: spassion Handicap value. –3.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      '2-nd map: spassion Handicap value. –4.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      'Away win': ['4.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      'Draw': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      'Home win': ['2.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      'nopainnogain Handicap value. +0.5. Handicap coefficient': ['1.46(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                      'spassion Handicap value. –0.5. Handicap coefficient': ['2.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)']},
          'spassion - royalty': {'1-st map: Away win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: Home win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: Total. 25.5. Over': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: Total. 25.5. Under': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: royalty Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: royalty Handicap value. +3.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: royalty Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: spassion Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: spassion Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '1-st map: spassion Handicap value. –3.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: Away win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: Home win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: Total. 25.5. Over': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: Total. 25.5. Under': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: Total. 26.5. Over': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: Total. 26.5. Under': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: Total. 27.5. Over': ['2.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: Total. 27.5. Under': ['1.54(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: royalty Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: royalty Handicap value. +3.5. Handicap coefficient': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: royalty Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: spassion Handicap value. +2.5. Handicap coefficient': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: spassion Handicap value. –2.5. Handicap coefficient': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 '2-nd map: spassion Handicap value. –3.5. Handicap coefficient': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 'Away win': ['3.43(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 'Draw': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 'Home win': ['3.44(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 'royalty Handicap value. +0.5. Handicap coefficient': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)'],
                                 'spassion Handicap value. –0.5. Handicap coefficient': ['3.44(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)']},
          'third impact - hyper': {'Win of the 1st team': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'], 'Win of the 2nd team': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)']},
          'thunder logic - rbg': {'1-st map: Total. 26.5. Over': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  '1-st map: Total. 26.5. Under': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  '1-st map: Win of the 1st team': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  '1-st map: Win of the 2nd team': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  '1-st map: rbg Handicap value. –2.5. Handicap coefficient': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  '1-st map: thunder logic Handicap value. +2.5. Handicap coefficient': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  'Total. 2.5. Over': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  'Total. 2.5. Under': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  'Win of the 1st team': ['2.12(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  'Win of the 2nd team': ['1.67(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  'rbg Handicap value. –1.5. Handicap coefficient': ['3.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)'],
                                  'thunder logic Handicap value. +1.5. Handicap coefficient': ['1.33(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-na-advanced)']},
          'tiger - beyond': {'1-st map: Total. 26.5. Over': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             '1-st map: Total. 26.5. Under': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             '1-st map: Win of the 1st team': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             '1-st map: Win of the 2nd team': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             '1-st map: beyond Handicap value. +3.5. Handicap coefficient': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             '1-st map: tiger Handicap value. –3.5. Handicap coefficient': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             'Total. 2.5. Over': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             'Total. 2.5. Under': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             'Win of the 1st team': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             'Win of the 2nd team': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             'beyond Handicap value. +1.5. Handicap coefficient': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                             'tiger Handicap value. –1.5. Handicap coefficient': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)']},
          'tyloo - divine vendetta': {'1-st map: Total. 25.5. Over': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      '1-st map: Total. 25.5. Under': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      '1-st map: Win of the 1st team': ['1.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      '1-st map: Win of the 2nd team': ['3.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      '1-st map: divine vendetta Handicap value. +4.5. Handicap coefficient': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      '1-st map: tyloo Handicap value. –4.5. Handicap coefficient': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      'Total. 2.5. Over': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      'Total. 2.5. Under': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      'Win of the 1st team': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      'Win of the 2nd team': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      'divine vendetta Handicap value. +1.5. Handicap coefficient': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                      'tyloo Handicap value. –1.5. Handicap coefficient': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)']},
          'vici gaming - lucid dream': {'1-st map: Total. 26.5. Over': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        '1-st map: Total. 26.5. Under': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        '1-st map: Win of the 1st team': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        '1-st map: Win of the 2nd team': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        '1-st map: lucid dream Handicap value. +4.5. Handicap coefficient': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        '1-st map: vici gaming Handicap value. –4.5. Handicap coefficient': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        'Total. 2.5. Over': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        'Total. 2.5. Under': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        'Win of the 1st team': ['1.18(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        'Win of the 2nd team': ['4.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        'lucid dream Handicap value. +1.5. Handicap coefficient': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)'],
                                        'vici gaming Handicap value. –1.5. Handicap coefficient': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)']},
          'woa - reckoning': {'Win of the 1st team': ['2.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esl-india-premiership)'], 'Win of the 2nd team': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esl-india-premiership)']},
          'wygers argentina - lbs': {'Win of the 1st team': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)'], 'Win of the 2nd team': ['2.16(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)']},
          'zero.tsg - tiger': {'Win of the 1st team': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-tf-asia-championships)'], 'Win of the 2nd team': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-tf-asia-championships)']}}}
