<<<<<<< HEAD
bets = {'avant - paradox gaming': {'Correct Score Full Time 0:2': '7.10',
                            'Correct Score Full Time 1:2': '6.00',
                            'Correct Score Full Time 2:0': '2.06',
                            'Correct Score Full Time 2:1': '2.95',
                            'Handicap rounds Game 1 AVANT (-3.5)': '1.85',
                            'Handicap rounds Game 1 Paradox Gaming (+3.5)': '1.89',
                            'Handicap winner Full Time AVANT (-1.5)': '2.06',
                            'Handicap winner Full Time Paradox Gaming (+1.5)': '1.71',
                            'Match winner Full Time AVANT': '1.27',
                            'Match winner Full Time Paradox Gaming': '3.50',
                            'Odd / Even Game 1 Even': '1.71',
                            'Odd / Even Game 1 Odd': '2.06',
                            'Over/Under Games Full Time Over (2.5)': '2.35',
                            'Over/Under Games Full Time Under (2.5)': '1.55',
                            'Total rounds Game 1 Over (26.5)': '1.93',
                            'Total rounds Game 1 Under (26.5)': '1.81',
                            'Winner Game 1 AVANT': '1.40',
                            'Winner Game 1 Paradox Gaming': '2.80'},
 'big - team vitality': {'Correct Score Full Time 0:2': '3.85',
                         'Correct Score Full Time 1:2': '3.60',
                         'Correct Score Full Time 2:0': '3.05',
                         'Correct Score Full Time 2:1': '3.45',
                         'Handicap rounds Game 1 BIG (+2.5)': '1.55',
                         'Handicap rounds Game 1 BIG (+3.5)': '1.38',
                         'Handicap rounds Game 1 BIG (-2.5)': '2.11',
                         'Handicap rounds Game 1 BIG (-3.5)': '2.48',
                         'Handicap rounds Game 1 BIG (-4.5)': '2.90',
                         'Handicap rounds Game 1 Team Vitality (+2.5)': '1.68',
                         'Handicap rounds Game 1 Team Vitality (+3.5)': '1.48',
                         'Handicap rounds Game 1 Team Vitality (+4.5)': '1.34',
                         'Handicap rounds Game 1 Team Vitality (-2.5)': '2.30',
                         'Handicap rounds Game 1 Team Vitality (-3.5)': '2.73',
                         'Handicap winner Full Time BIG (+1.5)': '1.23',
                         'Handicap winner Full Time BIG (-1.5)': '3.05',
                         'Handicap winner Full Time Team Vitality (+1.5)': '1.35',
                         'Handicap winner Full Time Team Vitality (-1.5)': '3.85',
                         'Match winner Full Time BIG': '1.75',
                         'Match winner Full Time Team Vitality': '2.00',
                         'Odd / Even Game 1 Even': '1.80',
                         'Odd / Even Game 1 Odd': '1.94',
                         'Over/Under Games Full Time Over (2.5)': '2.00',
                         'Over/Under Games Full Time Under (2.5)': '1.75',
                         'Total rounds Game 1 Over (24.5)': '1.29',
                         'Total rounds Game 1 Over (25.5)': '1.60',
                         'Total rounds Game 1 Over (26.5)': '1.85',
                         'Total rounds Game 1 Over (27.5)': '2.21',
                         'Total rounds Game 1 Over (28.5)': '2.78',
                         'Total rounds Game 1 Under (24.5)': '3.15',
                         'Total rounds Game 1 Under (25.5)': '2.20',
                         'Total rounds Game 1 Under (26.5)': '1.89',
                         'Total rounds Game 1 Under (27.5)': '1.59',
                         'Total rounds Game 1 Under (28.5)': '1.37',
                         'Which team will be the first to win 10 rounds? Game 1 BIG': '1.81',
                         'Which team will be the first to win 10 rounds? Game 1 Team Vitality': '1.94',
                         'Which team will be the first to win 5 rounds? Game 1 BIG': '1.82',
                         'Which team will be the first to win 5 rounds? Game 1 Team Vitality': '1.92',
                         'Winner Game 1 BIG': '1.78',
                         'Winner Game 1 Team Vitality': '1.96'},
 'chiefs esports club - truckers with attitude': {'Correct Score Full Time 0:2': '9.70',
                                                  'Correct Score Full Time 1:2': '7.00',
                                                  'Correct Score Full Time 2:0': '1.66',
                                                  'Correct Score Full Time 2:1': '3.40',
                                                  'Handicap rounds Game 1 Chiefs eSports Club (-4.5)': '1.97',
                                                  'Handicap rounds Game 1 TRUCKERS WITH ATTITUDE (+4.5)': '1.77',
                                                  'Handicap winner Full Time Chiefs eSports Club (-1.5)': '1.66',
                                                  'Handicap winner Full Time TRUCKERS WITH ATTITUDE (+1.5)': '2.14',
                                                  'Match winner Full Time Chiefs eSports Club': '1.18',
                                                  'Match winner Full Time TRUCKERS WITH ATTITUDE': '4.50',
                                                  'Odd / Even Game 1 Even': '1.71',
                                                  'Odd / Even Game 1 Odd': '2.06',
                                                  'Over/Under Games Full Time Over (2.5)': '2.65',
                                                  'Over/Under Games Full Time Under (2.5)': '1.45',
                                                  'Total rounds Game 1 Over (25.5)': '1.74',
                                                  'Total rounds Game 1 Under (25.5)': '2.01',
                                                  'Winner Game 1 Chiefs eSports Club': '1.33',
                                                  'Winner Game 1 TRUCKERS WITH ATTITUDE': '3.10'},
 'd13 - divine vendetta': {'Match winner Full Time D13': '1.57',
                           'Match winner Full Time Divine Vendetta': '2.30'},
 'evil geniuses - team liquid': {'Correct Score Full Time 0:2': '3.55',
                                 'Correct Score Full Time 1:2': '3.50',
                                 'Correct Score Full Time 2:0': '3.55',
                                 'Correct Score Full Time 2:1': '3.50',
                                 'Handicap rounds Game 1 Evil Geniuses (+2.5)': '1.59',
                                 'Handicap rounds Game 1 Evil Geniuses (+3.5)': '1.41',
                                 'Handicap rounds Game 1 Evil Geniuses (-2.5)': '2.24',
                                 'Handicap rounds Game 1 Evil Geniuses (-3.5)': '2.65',
                                 'Handicap rounds Game 1 Evil Geniuses (-4.5)': '3.15',
                                 'Handicap rounds Game 1 Team Liquid (+2.5)': '1.60',
                                 'Handicap rounds Game 1 Team Liquid (+3.5)': '1.42',
                                 'Handicap rounds Game 1 Team Liquid (+4.5)': '1.30',
                                 'Handicap rounds Game 1 Team Liquid (-2.5)': '2.22',
                                 'Handicap rounds Game 1 Team Liquid (-3.5)': '2.63',
                                 'Handicap winner Full Time Evil Geniuses (+1.5)': '1.27',
                                 'Handicap winner Full Time Evil Geniuses (-1.5)': '3.55',
                                 'Handicap winner Full Time Team Liquid (+1.5)': '1.27',
                                 'Handicap winner Full Time Team Liquid (-1.5)': '3.55',
                                 'Match winner Full Time Evil Geniuses': '1.87',
                                 'Match winner Full Time Team Liquid': '1.87',
                                 'Odd / Even Game 1 Even': '1.79',
                                 'Odd / Even Game 1 Odd': '1.96',
                                 'Over/Under Games Full Time Over (2.5)': '1.87',
                                 'Over/Under Games Full Time Under (2.5)': '1.87',
                                 'Total rounds Game 1 Over (24.5)': '1.26',
                                 'Total rounds Game 1 Over (25.5)': '1.54',
                                 'Total rounds Game 1 Over (26.5)': '1.77',
                                 'Total rounds Game 1 Over (27.5)': '2.12',
                                 'Total rounds Game 1 Over (28.5)': '2.68',
                                 'Total rounds Game 1 Under (24.5)': '3.35',
                                 'Total rounds Game 1 Under (25.5)': '2.32',
                                 'Total rounds Game 1 Under (26.5)': '1.98',
                                 'Total rounds Game 1 Under (27.5)': '1.65',
                                 'Total rounds Game 1 Under (28.5)': '1.40',
                                 'Which team will be the first to win 10 rounds? Game 1 Evil Geniuses': '1.87',
                                 'Which team will be the first to win 10 rounds? Game 1 Team Liquid': '1.87',
                                 'Which team will be the first to win 5 rounds? Game 1 Evil Geniuses': '1.87',
                                 'Which team will be the first to win 5 rounds? Game 1 Team Liquid': '1.87',
                                 'Winner Game 1 Evil Geniuses': '1.87',
                                 'Winner Game 1 Team Liquid': '1.87'},
 'fnatic - godsent': {'Correct Score Full Time 0:2': '5.30',
                      'Correct Score Full Time 1:2': '4.40',
                      'Correct Score Full Time 2:0': '2.25',
                      'Correct Score Full Time 2:1': '3.40',
                      'Handicap rounds Game 1 Fnatic (+2.5)': '1.37',
                      'Handicap rounds Game 1 Fnatic (-2.5)': '1.78',
                      'Handicap rounds Game 1 Fnatic (-3.5)': '2.08',
                      'Handicap rounds Game 1 Fnatic (-4.5)': '2.42',
                      'Handicap rounds Game 1 Fnatic (-5.5)': '2.76',
                      'Handicap rounds Game 1 GODSENT (+2.5)': '1.97',
                      'Handicap rounds Game 1 GODSENT (+3.5)': '1.67',
                      'Handicap rounds Game 1 GODSENT (+4.5)': '1.50',
                      'Handicap rounds Game 1 GODSENT (+5.5)': '1.37',
                      'Handicap rounds Game 1 GODSENT (-2.5)': '2.77',
                      'Handicap winner Full Time Fnatic (+1.5)': '1.13',
                      'Handicap winner Full Time Fnatic (-1.5)': '2.25',
                      'Handicap winner Full Time GODSENT (+1.5)': '1.60',
                      'Handicap winner Full Time GODSENT (-1.5)': '5.30',
                      'Match winner Full Time Fnatic': '1.45',
                      'Match winner Full Time GODSENT': '2.63',
                      'Odd / Even Game 1 Even': '1.71',
                      'Odd / Even Game 1 Odd': '2.06',
                      'Over/Under Games Full Time Over (2.5)': '2.16',
                      'Over/Under Games Full Time Under (2.5)': '1.65',
                      'Total rounds Game 1 Over (24.5)': '1.40',
                      'Total rounds Game 1 Over (25.5)': '1.64',
                      'Total rounds Game 1 Over (26.5)': '1.90',
                      'Total rounds Game 1 Over (27.5)': '2.27',
                      'Total rounds Game 1 Over (28.5)': '2.88',
                      'Total rounds Game 1 Under (24.5)': '2.65',
                      'Total rounds Game 1 Under (25.5)': '2.12',
                      'Total rounds Game 1 Under (26.5)': '1.84',
                      'Total rounds Game 1 Under (27.5)': '1.56',
                      'Total rounds Game 1 Under (28.5)': '1.35',
                      'Which team will be the first to win 10 rounds? Game 1 Fnatic': '1.61',
                      'Which team will be the first to win 10 rounds? Game 1 GODSENT': '2.23',
                      'Which team will be the first to win 5 rounds? Game 1 Fnatic': '1.68',
                      'Which team will be the first to win 5 rounds? Game 1 GODSENT': '2.11',
                      'Winner Game 1 Fnatic': '1.55',
                      'Winner Game 1 GODSENT': '2.36'},
 'forze - nordavind': {'Correct Score Full Time 0:2': '5.10',
                       'Correct Score Full Time 1:2': '4.50',
                       'Correct Score Full Time 2:0': '2.35',
                       'Correct Score Full Time 2:1': '3.30',
                       'Handicap rounds Game 1 Nordavind (+2.5)': '1.93',
                       'Handicap rounds Game 1 Nordavind (+3.5)': '1.64',
                       'Handicap rounds Game 1 Nordavind (+4.5)': '1.48',
                       'Handicap rounds Game 1 forZe (-2.5)': '1.81',
                       'Handicap rounds Game 1 forZe (-3.5)': '2.12',
                       'Handicap rounds Game 1 forZe (-4.5)': '2.47',
                       'Handicap winner Full Time Nordavind (+1.5)': '1.56',
                       'Handicap winner Full Time Nordavind (-1.5)': '5.10',
                       'Handicap winner Full Time forZe (+1.5)': '1.14',
                       'Handicap winner Full Time forZe (-1.5)': '2.35',
                       'Match winner Full Time Nordavind': '2.60',
                       'Match winner Full Time forZe': '1.46',
                       'Odd / Even Game 1 Even': '1.71',
                       'Odd / Even Game 1 Odd': '2.06',
                       'Over/Under Games Full Time Over (2.5)': '2.03',
                       'Over/Under Games Full Time Under (2.5)': '1.73',
                       'Total rounds Game 1 Over (25.5)': '1.64',
                       'Total rounds Game 1 Over (26.5)': '1.90',
                       'Total rounds Game 1 Over (27.5)': '2.26',
                       'Total rounds Game 1 Under (25.5)': '2.13',
                       'Total rounds Game 1 Under (26.5)': '1.84',
                       'Total rounds Game 1 Under (27.5)': '1.57',
                       'Winner Game 1 Nordavind': '2.31',
                       'Winner Game 1 forZe': '1.57'},
 'havu - hard legion': {'Correct Score Full Time 0:2': '4.35',
                        'Correct Score Full Time 1:2': '3.80',
                        'Correct Score Full Time 2:0': '2.60',
                        'Correct Score Full Time 2:1': '3.70',
                        'Handicap rounds Game 1 HAVU (+2.5)': '1.48',
                        'Handicap rounds Game 1 HAVU (-2.5)': '1.97',
                        'Handicap rounds Game 1 HAVU (-3.5)': '2.31',
                        'Handicap rounds Game 1 Hard Legion (+2.5)': '1.78',
                        'Handicap rounds Game 1 Hard Legion (+3.5)': '1.55',
                        'Handicap rounds Game 1 Hard Legion (-2.5)': '2.47',
                        'Handicap winner Full Time HAVU (+1.5)': '1.19',
                        'Handicap winner Full Time HAVU (-1.5)': '2.60',
                        'Handicap winner Full Time Hard Legion (+1.5)': '1.46',
                        'Handicap winner Full Time Hard Legion (-1.5)': '4.35',
                        'Match winner Full Time HAVU': '1.62',
                        'Match winner Full Time Hard Legion': '2.21',
                        'Odd / Even Game 1 Even': '1.71',
                        'Odd / Even Game 1 Odd': '2.06',
                        'Over/Under Games Full Time Over (2.5)': '2.06',
                        'Over/Under Games Full Time Under (2.5)': '1.71',
                        'Total rounds Game 1 Over (25.5)': '1.61',
                        'Total rounds Game 1 Over (26.5)': '1.86',
                        'Total rounds Game 1 Over (27.5)': '2.22',
                        'Total rounds Game 1 Under (25.5)': '2.19',
                        'Total rounds Game 1 Under (26.5)': '1.88',
                        'Total rounds Game 1 Under (27.5)': '1.59',
                        'Winner Game 1 HAVU': '1.68',
                        'Winner Game 1 Hard Legion': '2.11'},
 'heroic - og': {'Correct Score Full Time 0:2': '3.90',
                 'Correct Score Full Time 1:2': '3.70',
                 'Correct Score Full Time 2:0': '2.95',
                 'Correct Score Full Time 2:1': '3.60',
                 'Handicap rounds Game 1 Heroic (+2.5)': '1.57',
                 'Handicap rounds Game 1 Heroic (-2.5)': '2.16',
                 'Handicap rounds Game 1 Heroic (-3.5)': '2.55',
                 'Handicap rounds Game 1 OG (+2.5)': '1.65',
                 'Handicap rounds Game 1 OG (+3.5)': '1.45',
                 'Handicap rounds Game 1 OG (-2.5)': '2.26',
                 'Handicap winner Full Time Heroic (+1.5)': '1.23',
                 'Handicap winner Full Time Heroic (-1.5)': '2.95',
                 'Handicap winner Full Time OG (+1.5)': '1.37',
                 'Handicap winner Full Time OG (-1.5)': '3.90',
                 'Match winner Full Time Heroic': '1.77',
                 'Match winner Full Time OG': '1.98',
                 'Odd / Even Game 1 Even': '1.79',
                 'Odd / Even Game 1 Odd': '1.95',
                 'Over/Under Games Full Time Over (2.5)': '2.00',
                 'Over/Under Games Full Time Under (2.5)': '1.75',
                 'Total rounds Game 1 Over (25.5)': '1.57',
                 'Total rounds Game 1 Over (26.5)': '1.81',
                 'Total rounds Game 1 Over (27.5)': '2.16',
                 'Total rounds Game 1 Under (25.5)': '2.25',
                 'Total rounds Game 1 Under (26.5)': '1.93',
                 'Total rounds Game 1 Under (27.5)': '1.62',
                 'Winner Game 1 Heroic': '1.82',
                 'Winner Game 1 OG': '1.92'},
 'nemiga gaming - apeks': {'Correct Score Full Time 0:2': '5.80',
                           'Correct Score Full Time 1:2': '5.00',
                           'Correct Score Full Time 2:0': '2.03',
                           'Correct Score Full Time 2:1': '3.55',
                           'Handicap rounds Game 1 Apeks (+2.5)': '2.02',
                           'Handicap rounds Game 1 Apeks (+3.5)': '1.73',
                           'Handicap rounds Game 1 Apeks (+4.5)': '1.53',
                           'Handicap rounds Game 1 Nemiga Gaming (-2.5)': '1.71',
                           'Handicap rounds Game 1 Nemiga Gaming (-3.5)': '2.03',
                           'Handicap rounds Game 1 Nemiga Gaming (-4.5)': '2.34',
                           'Handicap winner Full Time Apeks (+1.5)': '1.73',
                           'Handicap winner Full Time Apeks (-1.5)': '5.80',
                           'Handicap winner Full Time Nemiga Gaming (+1.5)': '1.11',
                           'Handicap winner Full Time Nemiga Gaming (-1.5)': '2.03',
                           'Match winner Full Time Apeks': '2.93',
                           'Match winner Full Time Nemiga Gaming': '1.37',
                           'Odd / Even Game 1 Even': '1.71',
                           'Odd / Even Game 1 Odd': '2.06',
                           'Over/Under Games Full Time Over (2.5)': '2.17',
                           'Over/Under Games Full Time Under (2.5)': '1.64',
                           'Total rounds Game 1 Over (25.5)': '1.63',
                           'Total rounds Game 1 Over (26.5)': '1.90',
                           'Total rounds Game 1 Over (27.5)': '2.26',
                           'Total rounds Game 1 Under (25.5)': '2.14',
                           'Total rounds Game 1 Under (26.5)': '1.84',
                           'Total rounds Game 1 Under (27.5)': '1.57',
                           'Winner Game 1 Apeks': '2.46',
                           'Winner Game 1 Nemiga Gaming': '1.51'},
 'nordavind - ago esports': {'Handicap rounds Game 1 AGO Esports (+2.5)': '1.84',
                             'Handicap rounds Game 1 AGO Esports (+3.5)': '1.56',
                             'Handicap rounds Game 1 AGO Esports (-2.5)': '2.71',
                             'Handicap rounds Game 1 Nordavind (+2.5)': '1.41',
                             'Handicap rounds Game 1 Nordavind (-2.5)': '1.90',
                             'Handicap rounds Game 1 Nordavind (-3.5)': '2.28',
                             'Match winner Full Time AGO Esports': '2.25',
                             'Match winner Full Time Nordavind': '1.60',
                             'Odd / Even Game 1 Even': '1.70',
                             'Odd / Even Game 1 Odd': '2.07',
                             'Total rounds Game 1 Over (26.5)': '1.64',
                             'Total rounds Game 1 Over (27.5)': '2.00',
                             'Total rounds Game 1 Over (28.5)': '2.55',
                             'Total rounds Game 1 Under (26.5)': '2.12',
                             'Total rounds Game 1 Under (27.5)': '1.75',
                             'Total rounds Game 1 Under (28.5)': '1.45'},
 'syman gaming - hellraisers': {'Handicap rounds Game 1 HellRaisers (+2.5)': '1.64',
                                'Handicap rounds Game 1 HellRaisers (+3.5)': '1.44',
                                'Handicap rounds Game 1 HellRaisers (-2.5)': '2.32',
                                'Handicap rounds Game 1 Syman Gaming (+2.5)': '1.54',
                                'Handicap rounds Game 1 Syman Gaming (-2.5)': '2.17',
                                'Handicap rounds Game 1 Syman Gaming (-3.5)': '2.60',
                                'Match winner Full Time HellRaisers': '1.94',
                                'Match winner Full Time Syman Gaming': '1.80',
                                'Odd / Even Game 1 Even': '1.77',
                                'Odd / Even Game 1 Odd': '1.98',
                                'Total rounds Game 1 Over (25.5)': '1.47',
                                'Total rounds Game 1 Over (26.5)': '1.67',
                                'Total rounds Game 1 Over (27.5)': '2.03',
                                'Total rounds Game 1 Under (25.5)': '2.50',
                                'Total rounds Game 1 Under (26.5)': '2.08',
                                'Total rounds Game 1 Under (27.5)': '1.73'},
 'tikitakan - team brute': {'Correct Score Full Time 0:2': '4.00',
                            'Correct Score Full Time 1:2': '3.70',
                            'Correct Score Full Time 2:0': '2.95',
                            'Correct Score Full Time 2:1': '3.40',
                            'Handicap rounds Game 1 Team Brute (+2.5)': '1.70',
                            'Handicap rounds Game 1 Tikitakan (-2.5)': '2.07',
                            'Handicap winner Full Time Team Brute (+1.5)': '1.37',
                            'Handicap winner Full Time Tikitakan (-1.5)': '2.95',
                            'Match winner Full Time Team Brute': '2.07',
                            'Match winner Full Time Tikitakan': '1.71',
                            'Odd / Even Game 1 Even': '1.71',
                            'Odd / Even Game 1 Odd': '2.06',
                            'Over/Under Games Full Time Over (2.5)': '2.08',
                            'Over/Under Games Full Time Under (2.5)': '1.70',
                            'Total rounds Game 1 Over (26.5)': '1.83',
                            'Total rounds Game 1 Under (26.5)': '1.91',
                            'Winner Game 1 Team Brute': '2.00',
                            'Winner Game 1 Tikitakan': '1.75'}}
=======
bets = {
    'big - team vitality': {
        'Correct Score Full Time 0:2': '3.85',
        'Correct Score Full Time 1:2': '3.60',
        'Correct Score Full Time 2:0': '3.05',
        'Correct Score Full Time 2:1': '3.45',
        'Handicap rounds Game 1 BIG (+2.5)': '1.55',
        'Handicap rounds Game 1 BIG (+3.5)': '1.38',
        'Handicap rounds Game 1 BIG (-2.5)': '2.11',
        'Handicap rounds Game 1 BIG (-3.5)': '2.48',
        'Handicap rounds Game 1 BIG (-4.5)': '2.90',
        'Handicap rounds Game 1 Team Vitality (+2.5)': '1.68',
        'Handicap rounds Game 1 Team Vitality (+3.5)': '1.48',
        'Handicap rounds Game 1 Team Vitality (+4.5)': '1.34',
        'Handicap rounds Game 1 Team Vitality (-2.5)': '2.30',
        'Handicap rounds Game 1 Team Vitality (-3.5)': '2.73',
        'Handicap winner Full Time BIG (+1.5)': '1.23',
        'Handicap winner Full Time BIG (-1.5)': '3.05',
        'Handicap winner Full Time Team Vitality (+1.5)': '1.35',
        'Handicap winner Full Time Team Vitality (-1.5)': '3.85',
        'Match winner Full Time BIG': '1.75',
        'Match winner Full Time Team Vitality': '2.00',
        'Odd / Even Game 1 Even': '1.80',
        'Odd / Even Game 1 Odd': '1.94',
        'Over/Under Games Full Time Over (2.5)': '2.00',
        'Over/Under Games Full Time Under (2.5)': '1.75',
        'Total rounds Game 1 Over (24.5)': '1.29',
        'Total rounds Game 1 Over (25.5)': '1.60',
        'Total rounds Game 1 Over (26.5)': '1.85',
        'Total rounds Game 1 Over (27.5)': '2.21',
        'Total rounds Game 1 Over (28.5)': '2.78',
        'Total rounds Game 1 Under (24.5)': '3.15',
        'Total rounds Game 1 Under (25.5)': '2.20',
        'Total rounds Game 1 Under (26.5)': '1.89',
        'Total rounds Game 1 Under (27.5)': '1.59',
        'Total rounds Game 1 Under (28.5)': '1.37',
        'Which team will be the first to win 10 rounds? Game 1 BIG': '1.81',
        'Which team will be the first to win 10 rounds? Game 1 Team Vitality': '1.94',
        'Which team will be the first to win 5 rounds? Game 1 BIG': '1.82',
        'Which team will be the first to win 5 rounds? Game 1 Team Vitality': '1.92',
        'Winner Game 1 BIG': '1.78',
        'Winner Game 1 Team Vitality': '1.96',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27048215&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'd13 - divine vendetta': {
        'Match winner Full Time D13': '1.59',
        'Match winner Full Time Divine Vendetta': '2.25',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27064238&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'evil geniuses - team liquid': {
        'Correct Score Full Time 0:2': '3.65',
        'Correct Score Full Time 1:2': '3.60',
        'Correct Score Full Time 2:0': '3.40',
        'Correct Score Full Time 2:1': '3.30',
        'Handicap rounds Game 1 Evil Geniuses (+2.5)': '1.58',
        'Handicap rounds Game 1 Evil Geniuses (+3.5)': '1.40',
        'Handicap rounds Game 1 Evil Geniuses (-2.5)': '2.18',
        'Handicap rounds Game 1 Evil Geniuses (-3.5)': '2.57',
        'Handicap rounds Game 1 Evil Geniuses (-4.5)': '3.00',
        'Handicap rounds Game 1 Team Liquid (+2.5)': '1.63',
        'Handicap rounds Game 1 Team Liquid (+3.5)': '1.45',
        'Handicap rounds Game 1 Team Liquid (+4.5)': '1.31',
        'Handicap rounds Game 1 Team Liquid (-2.5)': '2.24',
        'Handicap rounds Game 1 Team Liquid (-3.5)': '2.66',
        'Handicap winner Full Time Evil Geniuses (+1.5)': '1.25',
        'Handicap winner Full Time Evil Geniuses (-1.5)': '3.40',
        'Handicap winner Full Time Team Liquid (+1.5)': '1.28',
        'Handicap winner Full Time Team Liquid (-1.5)': '3.65',
        'Match winner Full Time Evil Geniuses': '1.80',
        'Match winner Full Time Team Liquid': '1.94',
        'Odd / Even Game 1 Even': '1.79',
        'Odd / Even Game 1 Odd': '1.95',
        'Over/Under Games Full Time Over (2.5)': '1.95',
        'Over/Under Games Full Time Under (2.5)': '1.80',
        'Total rounds Game 1 Over (24.5)': '1.36',
        'Total rounds Game 1 Over (25.5)': '1.57',
        'Total rounds Game 1 Over (26.5)': '1.81',
        'Total rounds Game 1 Over (27.5)': '2.16',
        'Total rounds Game 1 Over (28.5)': '2.73',
        'Total rounds Game 1 Under (24.5)': '3.00',
        'Total rounds Game 1 Under (25.5)': '2.25',
        'Total rounds Game 1 Under (26.5)': '1.93',
        'Total rounds Game 1 Under (27.5)': '1.62',
        'Total rounds Game 1 Under (28.5)': '1.38',
        'Which team will be the first to win 10 rounds? Game 1 Evil Geniuses': '1.84',
        'Which team will be the first to win 10 rounds? Game 1 Team Liquid': '1.90',
        'Which team will be the first to win 5 rounds? Game 1 Evil Geniuses': '1.85',
        'Which team will be the first to win 5 rounds? Game 1 Team Liquid': '1.89',
        'Winner Game 1 Evil Geniuses': '1.83',
        'Winner Game 1 Team Liquid': '1.91',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27054967&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'fnatic - godsent': {
        'Correct Score Full Time 0:2': '5.30',
        'Correct Score Full Time 1:2': '4.40',
        'Correct Score Full Time 2:0': '2.25',
        'Correct Score Full Time 2:1': '3.40',
        'Handicap rounds Game 1 Fnatic (+2.5)': '1.37',
        'Handicap rounds Game 1 Fnatic (-2.5)': '1.78',
        'Handicap rounds Game 1 Fnatic (-3.5)': '2.08',
        'Handicap rounds Game 1 Fnatic (-4.5)': '2.42',
        'Handicap rounds Game 1 Fnatic (-5.5)': '2.76',
        'Handicap rounds Game 1 GODSENT (+2.5)': '1.97',
        'Handicap rounds Game 1 GODSENT (+3.5)': '1.67',
        'Handicap rounds Game 1 GODSENT (+4.5)': '1.50',
        'Handicap rounds Game 1 GODSENT (+5.5)': '1.37',
        'Handicap rounds Game 1 GODSENT (-2.5)': '2.77',
        'Handicap winner Full Time Fnatic (+1.5)': '1.13',
        'Handicap winner Full Time Fnatic (-1.5)': '2.25',
        'Handicap winner Full Time GODSENT (+1.5)': '1.60',
        'Handicap winner Full Time GODSENT (-1.5)': '5.30',
        'Match winner Full Time Fnatic': '1.45',
        'Match winner Full Time GODSENT': '2.63',
        'Odd / Even Game 1 Even': '1.71',
        'Odd / Even Game 1 Odd': '2.06',
        'Over/Under Games Full Time Over (2.5)': '2.16',
        'Over/Under Games Full Time Under (2.5)': '1.65',
        'Total rounds Game 1 Over (24.5)': '1.40',
        'Total rounds Game 1 Over (25.5)': '1.64',
        'Total rounds Game 1 Over (26.5)': '1.90',
        'Total rounds Game 1 Over (27.5)': '2.27',
        'Total rounds Game 1 Over (28.5)': '2.88',
        'Total rounds Game 1 Under (24.5)': '2.65',
        'Total rounds Game 1 Under (25.5)': '2.12',
        'Total rounds Game 1 Under (26.5)': '1.84',
        'Total rounds Game 1 Under (27.5)': '1.56',
        'Total rounds Game 1 Under (28.5)': '1.35',
        'Which team will be the first to win 10 rounds? Game 1 Fnatic': '1.61',
        'Which team will be the first to win 10 rounds? Game 1 GODSENT': '2.23',
        'Which team will be the first to win 5 rounds? Game 1 Fnatic': '1.68',
        'Which team will be the first to win 5 rounds? Game 1 GODSENT': '2.11',
        'Winner Game 1 Fnatic': '1.55',
        'Winner Game 1 GODSENT': '2.36',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27063844&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'forze - nordavind': {
        'Correct Score Full Time 0:2': '5.10',
        'Correct Score Full Time 1:2': '4.50',
        'Correct Score Full Time 2:0': '2.35',
        'Correct Score Full Time 2:1': '3.30',
        'Handicap rounds Game 1 Nordavind (+2.5)': '1.93',
        'Handicap rounds Game 1 Nordavind (+3.5)': '1.64',
        'Handicap rounds Game 1 Nordavind (+4.5)': '1.48',
        'Handicap rounds Game 1 forZe (-2.5)': '1.81',
        'Handicap rounds Game 1 forZe (-3.5)': '2.12',
        'Handicap rounds Game 1 forZe (-4.5)': '2.47',
        'Handicap winner Full Time Nordavind (+1.5)': '1.56',
        'Handicap winner Full Time Nordavind (-1.5)': '5.10',
        'Handicap winner Full Time forZe (+1.5)': '1.14',
        'Handicap winner Full Time forZe (-1.5)': '2.35',
        'Match winner Full Time Nordavind': '2.60',
        'Match winner Full Time forZe': '1.46',
        'Odd / Even Game 1 Even': '1.71',
        'Odd / Even Game 1 Odd': '2.06',
        'Over/Under Games Full Time Over (2.5)': '2.03',
        'Over/Under Games Full Time Under (2.5)': '1.73',
        'Total rounds Game 1 Over (25.5)': '1.64',
        'Total rounds Game 1 Over (26.5)': '1.90',
        'Total rounds Game 1 Over (27.5)': '2.26',
        'Total rounds Game 1 Under (25.5)': '2.13',
        'Total rounds Game 1 Under (26.5)': '1.84',
        'Total rounds Game 1 Under (27.5)': '1.57',
        'Winner Game 1 Nordavind': '2.31',
        'Winner Game 1 forZe': '1.57',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27064230&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'havu - hard legion': {
        'Correct Score Full Time 0:2': '4.35',
        'Correct Score Full Time 1:2': '3.80',
        'Correct Score Full Time 2:0': '2.60',
        'Correct Score Full Time 2:1': '3.70',
        'Handicap rounds Game 1 HAVU (+2.5)': '1.48',
        'Handicap rounds Game 1 HAVU (-2.5)': '1.97',
        'Handicap rounds Game 1 HAVU (-3.5)': '2.31',
        'Handicap rounds Game 1 Hard Legion (+2.5)': '1.78',
        'Handicap rounds Game 1 Hard Legion (+3.5)': '1.55',
        'Handicap rounds Game 1 Hard Legion (-2.5)': '2.47',
        'Handicap winner Full Time HAVU (+1.5)': '1.19',
        'Handicap winner Full Time HAVU (-1.5)': '2.60',
        'Handicap winner Full Time Hard Legion (+1.5)': '1.46',
        'Handicap winner Full Time Hard Legion (-1.5)': '4.35',
        'Match winner Full Time HAVU': '1.62',
        'Match winner Full Time Hard Legion': '2.21',
        'Odd / Even Game 1 Even': '1.71',
        'Odd / Even Game 1 Odd': '2.06',
        'Over/Under Games Full Time Over (2.5)': '2.06',
        'Over/Under Games Full Time Under (2.5)': '1.71',
        'Total rounds Game 1 Over (25.5)': '1.61',
        'Total rounds Game 1 Over (26.5)': '1.86',
        'Total rounds Game 1 Over (27.5)': '2.22',
        'Total rounds Game 1 Under (25.5)': '2.19',
        'Total rounds Game 1 Under (26.5)': '1.88',
        'Total rounds Game 1 Under (27.5)': '1.59',
        'Winner Game 1 HAVU': '1.68',
        'Winner Game 1 Hard Legion': '2.11',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27064217&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'heroic - og': {
        'Correct Score Full Time 0:2': '3.90',
        'Correct Score Full Time 1:2': '3.80',
        'Correct Score Full Time 2:0': '3.00',
        'Correct Score Full Time 2:1': '3.40',
        'Handicap rounds Game 1 Heroic (+2.5)': '1.56',
        'Handicap rounds Game 1 Heroic (-2.5)': '2.14',
        'Handicap rounds Game 1 Heroic (-3.5)': '2.52',
        'Handicap rounds Game 1 OG (+2.5)': '1.66',
        'Handicap rounds Game 1 OG (+3.5)': '1.46',
        'Handicap rounds Game 1 OG (-2.5)': '2.28',
        'Handicap winner Full Time Heroic (+1.5)': '1.23',
        'Handicap winner Full Time Heroic (-1.5)': '3.00',
        'Handicap winner Full Time OG (+1.5)': '1.36',
        'Handicap winner Full Time OG (-1.5)': '3.90',
        'Match winner Full Time Heroic': '1.72',
        'Match winner Full Time OG': '2.04',
        'Odd / Even Game 1 Even': '1.79',
        'Odd / Even Game 1 Odd': '1.95',
        'Over/Under Games Full Time Over (2.5)': '2.00',
        'Over/Under Games Full Time Under (2.5)': '1.75',
        'Total rounds Game 1 Over (25.5)': '1.57',
        'Total rounds Game 1 Over (26.5)': '1.81',
        'Total rounds Game 1 Over (27.5)': '2.16',
        'Total rounds Game 1 Under (25.5)': '2.25',
        'Total rounds Game 1 Under (26.5)': '1.93',
        'Total rounds Game 1 Under (27.5)': '1.62',
        'Winner Game 1 Heroic': '1.80',
        'Winner Game 1 OG': '1.94',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27063835&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'nemiga gaming - apeks': {
        'Correct Score Full Time 0:2': '6.10',
        'Correct Score Full Time 1:2': '5.00',
        'Correct Score Full Time 2:0': '2.02',
        'Correct Score Full Time 2:1': '3.40',
        'Handicap rounds Game 1 Apeks (+2.5)': '2.09',
        'Handicap rounds Game 1 Apeks (+3.5)': '1.78',
        'Handicap rounds Game 1 Apeks (+4.5)': '1.56',
        'Handicap rounds Game 1 Nemiga Gaming (-2.5)': '1.67',
        'Handicap rounds Game 1 Nemiga Gaming (-3.5)': '1.97',
        'Handicap rounds Game 1 Nemiga Gaming (-4.5)': '2.27',
        'Handicap winner Full Time Apeks (+1.5)': '1.74',
        'Handicap winner Full Time Apeks (-1.5)': '6.10',
        'Handicap winner Full Time Nemiga Gaming (+1.5)': '1.10',
        'Handicap winner Full Time Nemiga Gaming (-1.5)': '2.02',
        'Match winner Full Time Apeks': '3.00',
        'Match winner Full Time Nemiga Gaming': '1.35',
        'Odd / Even Game 1 Even': '1.71',
        'Odd / Even Game 1 Odd': '2.06',
        'Over/Under Games Full Time Over (2.5)': '2.25',
        'Over/Under Games Full Time Under (2.5)': '1.59',
        'Total rounds Game 1 Over (25.5)': '1.66',
        'Total rounds Game 1 Over (26.5)': '1.93',
        'Total rounds Game 1 Over (27.5)': '2.30',
        'Total rounds Game 1 Under (25.5)': '2.09',
        'Total rounds Game 1 Under (26.5)': '1.81',
        'Total rounds Game 1 Under (27.5)': '1.55',
        'Winner Game 1 Apeks': '2.55',
        'Winner Game 1 Nemiga Gaming': '1.47',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27057063&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'nemiga gaming - cr4zy': {
        'Correct Score Full Time 0:2': '10.50',
        'Correct Score Full Time 1:2': '8.00',
        'Correct Score Full Time 2:0': '1.58',
        'Correct Score Full Time 2:1': '3.40',
        'Handicap rounds Game 1 CR4ZY (+4.5)': '2.01',
        'Handicap rounds Game 1 CR4ZY (+5.5)': '1.79',
        'Handicap rounds Game 1 CR4ZY (+6.5)': '1.59',
        'Handicap rounds Game 1 Nemiga Gaming (-4.5)': '1.72',
        'Handicap rounds Game 1 Nemiga Gaming (-5.5)': '1.96',
        'Handicap rounds Game 1 Nemiga Gaming (-6.5)': '2.21',
        'Handicap winner Full Time CR4ZY (+1.5)': '2.30',
        'Handicap winner Full Time CR4ZY (-1.5)': '10.50',
        'Handicap winner Full Time Nemiga Gaming (+1.5)': '1.02',
        'Handicap winner Full Time Nemiga Gaming (-1.5)': '1.58',
        'Match winner Full Time CR4ZY': '5.00',
        'Match winner Full Time Nemiga Gaming': '1.15',
        'Odd / Even Game 1 Even': '1.82',
        'Odd / Even Game 1 Odd': '1.93',
        'Over/Under Games Full Time Over (2.5)': '2.75',
        'Over/Under Games Full Time Under (2.5)': '1.41',
        'Total rounds Game 1 Over (24.5)': '1.57',
        'Total rounds Game 1 Over (25.5)': '1.83',
        'Total rounds Game 1 Over (26.5)': '2.23',
        'Total rounds Game 1 Under (24.5)': '2.25',
        'Total rounds Game 1 Under (25.5)': '1.91',
        'Total rounds Game 1 Under (26.5)': '1.59',
        'Winner Game 1 CR4ZY': '3.70',
        'Winner Game 1 Nemiga Gaming': '1.25',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27068507&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'nordavind - ago esports': {
        'Handicap rounds Game 1 AGO Esports (+2.5)': '1.84',
        'Handicap rounds Game 1 AGO Esports (+3.5)': '1.56',
        'Handicap rounds Game 1 AGO Esports (-2.5)': '2.71',
        'Handicap rounds Game 1 Nordavind (+2.5)': '1.41',
        'Handicap rounds Game 1 Nordavind (-2.5)': '1.90',
        'Handicap rounds Game 1 Nordavind (-3.5)': '2.28',
        'Match winner Full Time AGO Esports': '2.25',
        'Match winner Full Time Nordavind': '1.60',
        'Odd / Even Game 1 Even': '1.70',
        'Odd / Even Game 1 Odd': '2.07',
        'Total rounds Game 1 Over (26.5)': '1.64',
        'Total rounds Game 1 Over (27.5)': '2.00',
        'Total rounds Game 1 Over (28.5)': '2.55',
        'Total rounds Game 1 Under (26.5)': '2.12',
        'Total rounds Game 1 Under (27.5)': '1.75',
        'Total rounds Game 1 Under (28.5)': '1.45',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27004967&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'syman gaming - hellraisers': {
        'Handicap rounds Game 1 HellRaisers (+2.5)': '1.64',
        'Handicap rounds Game 1 HellRaisers (+3.5)': '1.44',
        'Handicap rounds Game 1 HellRaisers (-2.5)': '2.32',
        'Handicap rounds Game 1 Syman Gaming (+2.5)': '1.54',
        'Handicap rounds Game 1 Syman Gaming (-2.5)': '2.17',
        'Handicap rounds Game 1 Syman Gaming (-3.5)': '2.60',
        'Match winner Full Time HellRaisers': '1.94',
        'Match winner Full Time Syman Gaming': '1.80',
        'Odd / Even Game 1 Even': '1.77',
        'Odd / Even Game 1 Odd': '1.98',
        'Total rounds Game 1 Over (25.5)': '1.47',
        'Total rounds Game 1 Over (26.5)': '1.67',
        'Total rounds Game 1 Over (27.5)': '2.03',
        'Total rounds Game 1 Under (25.5)': '2.50',
        'Total rounds Game 1 Under (26.5)': '2.08',
        'Total rounds Game 1 Under (27.5)': '1.73',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27032220&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        },
    'tikitakan - team brute': {
        'Correct Score Full Time 0:2': '4.00',
        'Correct Score Full Time 1:2': '3.70',
        'Correct Score Full Time 2:0': '2.95',
        'Correct Score Full Time 2:1': '3.40',
        'Handicap rounds Game 1 Team Brute (+2.5)': '1.70',
        'Handicap rounds Game 1 Tikitakan (-2.5)': '2.07',
        'Handicap winner Full Time Team Brute (+1.5)': '1.37',
        'Handicap winner Full Time Tikitakan (-1.5)': '2.95',
        'Match winner Full Time Team Brute': '2.07',
        'Match winner Full Time Tikitakan': '1.71',
        'Odd / Even Game 1 Even': '1.71',
        'Odd / Even Game 1 Odd': '2.06',
        'Over/Under Games Full Time Over (2.5)': '2.08',
        'Over/Under Games Full Time Under (2.5)': '1.70',
        'Total rounds Game 1 Over (26.5)': '1.83',
        'Total rounds Game 1 Under (26.5)': '1.91',
        'Winner Game 1 Team Brute': '2.00',
        'Winner Game 1 Tikitakan': '1.75',
        'url': 'https://www.favorit.com.ua/en/bets/#event=27063931&tours=451782,592754,1547381,1634075,1727483,2452749,2461097'
        }
    }
>>>>>>> e582648b26037ee6c83b53a3fc50541140242e27
