bets = {
    'ahq - asking questions': {
        '    Correct Score          Asking Questions     (0 - 2)  ': '4.70',
        '    Correct Score          Asking Questions     (1 - 2)  ': '4.05',
        '    Correct Score          ahq     (2 - 0)  ': '2.99',
        '    Correct Score          ahq     (2 - 1)  ': '3.22',
        '    To Win Match With Handicap By Maps          Asking Questions     (+1.5)  ': '1.38',
        '    To Win Match With Handicap By Maps          ahq     (-1.5)  ': '2.99',
        '    Total Maps          Over     (2.5)  ': '1.909',
        '    Total Maps          Under     (2.5)  ': '1.86',
        '    Total Maps        Even ': '1.86',
        '    Total Maps        Odd ': '1.909',
        'ahq will win': '1.64',
        'asking questions will win': '2.26',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/ESEA+Open/Main+Event/Best+of+3+maps/ahq+vs+Asking+Questions+-+9752544'
        },
    'blinkal - adaptation': {
        'adaptation will win': '1.41',
        'blinkal will win': '2.91',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/WINNERS+League/Main+Event/One+map/BlinkAL+vs+Adaptation+-+9757967'
        },
    'bravos - sws': {
        '    Correct Score          Bravos     (2 - 0)  ': '2.49',
        '    Correct Score          Bravos     (2 - 1)  ': '3.08',
        '    Correct Score          SWS     (0 - 2)  ': '6.10',
        '    Correct Score          SWS     (1 - 2)  ': '4.70',
        '    To Win Match With Handicap By Maps          Bravos     (-1.5)  ': '2.49',
        '    To Win Match With Handicap By Maps          SWS     (+1.5)  ': '1.51',
        '    Total Maps          Over     (2.5)  ': '1.98',
        '    Total Maps          Under     (2.5)  ': '1.79',
        '    Total Maps        Even ': '1.79',
        '    Total Maps        Odd ': '1.98',
        'bravos will win': '1.44',
        'sws will win': '2.79',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/CLUTCH/Main+Event/Best+of+3+maps/Bravos+vs+SWS+-+9752226'
        },
    'cream real betis - neverest esports': {
        '    Correct Score          Cream Real Betis     (2 - 0)  ': '2.76',
        '    Correct Score          Cream Real Betis     (2 - 1)  ': '3.14',
        '    Correct Score          Neverest eSports     (0 - 2)  ': '5.25',
        '    Correct Score          Neverest eSports     (1 - 2)  ': '4.30',
        '    To Win Match With Handicap By Maps          Cream Real Betis     (-1.5)  ': '2.76',
        '    To Win Match With Handicap By Maps          Neverest eSports     (+1.5)  ': '1.43',
        '    Total Maps          Over     (2.5)  ': '1.94',
        '    Total Maps          Under     (2.5)  ': '1.83',
        '    Total Maps        Even ': '1.83',
        '    Total Maps        Odd ': '1.94',
        'cream real betis will win': '1.54',
        'neverest esports will win': '2.48',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/CLUTCH/Main+Event/Best+of+3+maps/Cream+Real+Betis+vs+Neverest+eSports+-+9752227'
        },
    'fnatic - godsent': {
        '    1st Map Result         Fnatic To Win   ': '1.60',
        '    1st Map Result         GODSENT To Win   ': '2.28',
        '    2nd Map Result         Fnatic To Win   ': '1.60',
        '    2nd Map Result         GODSENT To Win   ': '2.28',
        '    Correct Score          Fnatic     (2 - 0)  ': '2.65',
        '    Correct Score          Fnatic     (2 - 1)  ': '3.10',
        '    Correct Score          GODSENT     (0 - 2)  ': '5.55',
        '    Correct Score          GODSENT     (1 - 2)  ': '4.45',
        '    Most Kills         Equal Number   ': '31.00',
        '    Most Kills         Fnatic   ': '1.40',
        '    Most Kills         Fnatic or Equal Number   ': '1.35',
        '    Most Kills         GODSENT   ': '2.93',
        '    Most Kills         GODSENT or Equal Number   ': '2.69',
        '    Most Kills - 1st map         Equal Number   ': '25.00',
        '    Most Kills - 1st map         Fnatic   ': '1.55',
        '    Most Kills - 1st map         GODSENT   ': '2.49',
        '    Most Kills - 2nd map         Equal Number   ': '25.00',
        '    Most Kills - 2nd map         Fnatic   ': '1.55',
        '    Most Kills - 2nd map         GODSENT   ': '2.49',
        '    Most Kills With Handicap          Fnatic     (-12.5)  ': '1.88',
        '    Most Kills With Handicap          GODSENT     (+12.5)  ': '1.88',
        '    Most Kills With Handicap - 1st map          Fnatic     (-5.5)  ': '1.909',
        '    Most Kills With Handicap - 1st map          GODSENT     (+5.5)  ': '1.85',
        '    Most Kills With Handicap - 2nd map          Fnatic     (-5.5)  ': '1.909',
        '    Most Kills With Handicap - 2nd map          GODSENT     (+5.5)  ': '1.85',
        '    To Win 1st Map With Handicap By Rounds          Fnatic     (-2.5)  ': '1.82',
        '    To Win 1st Map With Handicap By Rounds          GODSENT     (+2.5)  ': '1.94',
        '    To Win 2nd Map With Handicap By Rounds          Fnatic     (-2.5)  ': '1.82',
        '    To Win 2nd Map With Handicap By Rounds          GODSENT     (+2.5)  ': '1.94',
        '    To Win Match With Handicap By Maps          Fnatic     (-1.5)  ': '2.65',
        '    To Win Match With Handicap By Maps          GODSENT     (+1.5)  ': '1.46',
        '    To Win Match With Handicap By Rounds          Fnatic     (-2.5)  ': '1.615',
        '    To Win Match With Handicap By Rounds          Fnatic     (-3.5)  ': '1.68',
        '    To Win Match With Handicap By Rounds          Fnatic     (-4.5)  ': '1.77',
        '    To Win Match With Handicap By Rounds          Fnatic     (-5.5)  ': '1.89',
        '    To Win Match With Handicap By Rounds          Fnatic     (-6.5)  ': '2.04',
        '    To Win Match With Handicap By Rounds          Fnatic     (-7.5)  ': '2.24',
        '    To Win Match With Handicap By Rounds          Fnatic     (-8.5)  ': '2.52',
        '    To Win Match With Handicap By Rounds          GODSENT     (+2.5)  ': '2.27',
        '    To Win Match With Handicap By Rounds          GODSENT     (+3.5)  ': '2.15',
        '    To Win Match With Handicap By Rounds          GODSENT     (+4.5)  ': '2.02',
        '    To Win Match With Handicap By Rounds          GODSENT     (+5.5)  ': '1.89',
        '    To Win Match With Handicap By Rounds          GODSENT     (+6.5)  ': '1.76',
        '    To Win Match With Handicap By Rounds          GODSENT     (+7.5)  ': '1.63',
        '    To Win Match With Handicap By Rounds          GODSENT     (+8.5)  ': '1.51',
        '    Total Kills          Over     (449.5)  ': '1.88',
        '    Total Kills          Under     (449.5)  ': '1.88',
        '    Total Kills        Even ': '1.88',
        '    Total Kills        Odd ': '1.88',
        '    Total Kills (Fnatic)          Over     (231.5)  ': '1.88',
        '    Total Kills (Fnatic)          Under     (231.5)  ': '1.88',
        '    Total Kills (Fnatic)        Even ': '1.88',
        '    Total Kills (Fnatic)        Odd ': '1.88',
        '    Total Kills (Fnatic) - 1st map          Over     (94.5)  ': '1.89',
        '    Total Kills (Fnatic) - 1st map          Under     (94.5)  ': '1.87',
        '    Total Kills (Fnatic) - 1st map        Even ': '1.88',
        '    Total Kills (Fnatic) - 1st map        Odd ': '1.88',
        '    Total Kills (Fnatic) - 2nd map          Over     (94.5)  ': '1.89',
        '    Total Kills (Fnatic) - 2nd map          Under     (94.5)  ': '1.87',
        '    Total Kills (Fnatic) - 2nd map        Even ': '1.88',
        '    Total Kills (Fnatic) - 2nd map        Odd ': '1.88',
        '    Total Kills (GODSENT)          Over     (218.5)  ': '1.88',
        '    Total Kills (GODSENT)          Under     (218.5)  ': '1.88',
        '    Total Kills (GODSENT)        Even ': '1.88',
        '    Total Kills (GODSENT)        Odd ': '1.88',
        '    Total Kills (GODSENT) - 1st map          Over     (89.5)  ': '1.90',
        '    Total Kills (GODSENT) - 1st map          Under     (89.5)  ': '1.86',
        '    Total Kills (GODSENT) - 1st map        Even ': '1.88',
        '    Total Kills (GODSENT) - 1st map        Odd ': '1.88',
        '    Total Kills (GODSENT) - 2nd map          Over     (89.5)  ': '1.90',
        '    Total Kills (GODSENT) - 2nd map          Under     (89.5)  ': '1.86',
        '    Total Kills (GODSENT) - 2nd map        Even ': '1.88',
        '    Total Kills (GODSENT) - 2nd map        Odd ': '1.88',
        '    Total Kills - 1st map          Over     (184.5)  ': '1.89',
        '    Total Kills - 1st map          Under     (184.5)  ': '1.87',
        '    Total Kills - 1st map        Even ': '1.88',
        '    Total Kills - 1st map        Odd ': '1.88',
        '    Total Kills - 2nd map          Over     (184.5)  ': '1.89',
        '    Total Kills - 2nd map          Under     (184.5)  ': '1.87',
        '    Total Kills - 2nd map        Even ': '1.88',
        '    Total Kills - 2nd map        Odd ': '1.88',
        '    Total Maps          Over     (2.5)  ': '1.95',
        '    Total Maps          Under     (2.5)  ': '1.82',
        '    Total Maps        Even ': '1.82',
        '    Total Maps        Odd ': '1.95',
        '    Total Rounds          Over     (62.5)  ': '1.80',
        '    Total Rounds          Over     (63.5)  ': '1.83',
        '    Total Rounds          Over     (64.5)  ': '1.86',
        '    Total Rounds          Over     (65.5)  ': '1.89',
        '    Total Rounds          Over     (66.5)  ': '1.90',
        '    Total Rounds          Over     (67.5)  ': '1.92',
        '    Total Rounds          Over     (68.5)  ': '1.94',
        '    Total Rounds          Over     (69.5)  ': '1.97',
        '    Total Rounds          Under     (62.5)  ': '1.97',
        '    Total Rounds          Under     (63.5)  ': '1.93',
        '    Total Rounds          Under     (64.5)  ': '1.90',
        '    Total Rounds          Under     (65.5)  ': '1.89',
        '    Total Rounds          Under     (66.5)  ': '1.86',
        '    Total Rounds          Under     (67.5)  ': '1.84',
        '    Total Rounds          Under     (68.5)  ': '1.82',
        '    Total Rounds          Under     (69.5)  ': '1.80',
        '    Total Rounds        Even ': '1.90',
        '    Total Rounds        Odd ': '1.90',
        '    Total Rounds - 1st Map          Over     (26.5)  ': '1.78',
        '    Total Rounds - 1st Map          Under     (26.5)  ': '1.99',
        '    Total Rounds - 1st Map        Even ': '1.77',
        '    Total Rounds - 1st Map        Odd ': '2.01',
        '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.78',
        '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.99',
        '    Total Rounds - 2nd Map        Even ': '1.77',
        '    Total Rounds - 2nd Map        Odd ': '2.01',
        'fnatic will win': '1.50',
        'godsent will win': '2.59',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Summit/Main+Event/Best+of+3+maps/Fnatic+vs+GODSENT+-+9755591'
        },
    'forze - nordavind': {
        '    Correct Score          Nordavind     (0 - 2)  ': '5.40',
        '    Correct Score          Nordavind     (1 - 2)  ': '4.40',
        '    Correct Score          forZe     (2 - 0)  ': '2.70',
        '    Correct Score          forZe     (2 - 1)  ': '3.125',
        '    To Win Match With Handicap By Maps          Nordavind     (+1.5)  ': '1.444',
        '    To Win Match With Handicap By Maps          forZe     (-1.5)  ': '2.70',
        '    Total Maps          Over     (2.5)  ': '1.94',
        '    Total Maps          Under     (2.5)  ': '1.83',
        '    Total Maps        Even ': '1.83',
        '    Total Maps        Odd ': '1.94',
        'forze will win': '1.52',
        'nordavind will win': '2.53',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Hellcase+Cup/Main+Event/Best+of+3+maps/forZe+vs+Nordavind+-+9757944'
        },
    'grazur - lethal divide': {
        '    Correct Score          Grazur     (2 - 0)  ': '5.45',
        '    Correct Score          Grazur     (2 - 1)  ': '4.40',
        '    Correct Score          Lethal Divide     (0 - 2)  ': '2.69',
        '    Correct Score          Lethal Divide     (1 - 2)  ': '3.125',
        '    To Win Match With Handicap By Maps          Grazur     (+1.5)  ': '1.45',
        '    To Win Match With Handicap By Maps          Lethal Divide     (-1.5)  ': '2.69',
        '    Total Maps          Over     (2.5)  ': '1.94',
        '    Total Maps          Under     (2.5)  ': '1.83',
        '    Total Maps        Even ': '1.83',
        '    Total Maps        Odd ': '1.94',
        'grazur will win': '2.53',
        'lethal divide will win': '1.52',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/WINNERS+League/Main+Event/Best+of+3+maps/Grazur+vs+Lethal+Divide+-+9752584'
        },
    'hard legion - havu': {
        '    Correct Score          HAVU     (0 - 2)  ': '2.70',
        '    Correct Score          HAVU     (1 - 2)  ': '3.125',
        '    Correct Score          Hard Legion     (2 - 0)  ': '5.40',
        '    Correct Score          Hard Legion     (2 - 1)  ': '4.40',
        '    To Win Match With Handicap By Maps          HAVU     (-1.5)  ': '2.70',
        '    To Win Match With Handicap By Maps          Hard Legion     (+1.5)  ': '1.444',
        '    Total Maps          Over     (2.5)  ': '1.94',
        '    Total Maps          Under     (2.5)  ': '1.83',
        '    Total Maps        Even ': '1.83',
        '    Total Maps        Odd ': '1.94',
        'hard legion will win': '2.53',
        'havu will win': '1.52',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Hellcase+Cup/Main+Event/Best+of+3+maps/Hard+Legion+vs+HAVU+-+9757943'
        },
    'heroic - og': {
        '    1st Map Result         Heroic To Win   ': '1.74',
        '    1st Map Result         OG To Win   ': '2.04',
        '    2nd Map Result         Heroic To Win   ': '1.666',
        '    2nd Map Result         OG To Win   ': '2.16',
        '    Correct Score          Heroic     (2 - 0)  ': '3.02',
        '    Correct Score          Heroic     (2 - 1)  ': '3.15',
        '    Correct Score          OG     (0 - 2)  ': '4.65',
        '    Correct Score          OG     (1 - 2)  ': '4.15',
        '    Most Kills         Equal Number   ': '28.00',
        '    Most Kills         Heroic   ': '1.68',
        '    Most Kills         Heroic or Equal Number   ': '1.59',
        '    Most Kills         OG   ': '2.19',
        '    Most Kills         OG or Equal Number   ': '2.04',
        '    Most Kills - 1st map         Equal Number   ': '23.00',
        '    Most Kills - 1st map         Heroic   ': '1.76',
        '    Most Kills - 1st map         OG   ': '2.10',
        '    Most Kills - 2nd map         Equal Number   ': '23.00',
        '    Most Kills - 2nd map         Heroic   ': '1.76',
        '    Most Kills - 2nd map         OG   ': '2.10',
        '    Most Kills With Handicap          Heroic     (-4.5)  ': '1.88',
        '    Most Kills With Handicap          OG     (+4.5)  ': '1.88',
        '    Most Kills With Handicap - 1st map          Heroic     (-1.5)  ': '1.86',
        '    Most Kills With Handicap - 1st map          OG     (+1.5)  ': '1.90',
        '    Most Kills With Handicap - 2nd map          Heroic     (-1.5)  ': '1.86',
        '    Most Kills With Handicap - 2nd map          OG     (+1.5)  ': '1.90',
        '    To Win 1st Map With Handicap By Rounds          Heroic     (-2.5)  ': '2.02',
        '    To Win 1st Map With Handicap By Rounds          OG     (+2.5)  ': '1.76',
        '    To Win 2nd Map With Handicap By Rounds          Heroic     (-2.5)  ': '1.90',
        '    To Win 2nd Map With Handicap By Rounds          OG     (+2.5)  ': '1.86',
        '    To Win Match With Handicap By Maps          Heroic     (-1.5)  ': '3.02',
        '    To Win Match With Handicap By Maps          OG     (+1.5)  ': '1.37',
        '    To Win Match With Handicap By Rounds          Heroic     (-0.5)  ': '1.64',
        '    To Win Match With Handicap By Rounds          Heroic     (-1.5)  ': '1.70',
        '    To Win Match With Handicap By Rounds          Heroic     (-2.5)  ': '1.77',
        '    To Win Match With Handicap By Rounds          Heroic     (-3.5)  ': '1.85',
        '    To Win Match With Handicap By Rounds          Heroic     (-4.5)  ': '1.95',
        '    To Win Match With Handicap By Rounds          Heroic     (-5.5)  ': '2.11',
        '    To Win Match With Handicap By Rounds          Heroic     (-6.5)  ': '2.30',
        '    To Win Match With Handicap By Rounds          OG     (+0.5)  ': '2.22',
        '    To Win Match With Handicap By Rounds          OG     (+1.5)  ': '2.12',
        '    To Win Match With Handicap By Rounds          OG     (+2.5)  ': '2.02',
        '    To Win Match With Handicap By Rounds          OG     (+3.5)  ': '1.93',
        '    To Win Match With Handicap By Rounds          OG     (+4.5)  ': '1.83',
        '    To Win Match With Handicap By Rounds          OG     (+5.5)  ': '1.71',
        '    To Win Match With Handicap By Rounds          OG     (+6.5)  ': '1.60',
        '    Total Kills          Over     (470.5)  ': '1.88',
        '    Total Kills          Under     (470.5)  ': '1.88',
        '    Total Kills        Even ': '1.88',
        '    Total Kills        Odd ': '1.88',
        '    Total Kills (Heroic)          Over     (234.5)  ': '1.88',
        '    Total Kills (Heroic)          Under     (234.5)  ': '1.88',
        '    Total Kills (Heroic)        Even ': '1.88',
        '    Total Kills (Heroic)        Odd ': '1.88',
        '    Total Kills (Heroic) - 1st map          Over     (93.5)  ': '1.88',
        '    Total Kills (Heroic) - 1st map          Under     (93.5)  ': '1.88',
        '    Total Kills (Heroic) - 1st map        Even ': '1.88',
        '    Total Kills (Heroic) - 1st map        Odd ': '1.88',
        '    Total Kills (Heroic) - 2nd map          Over     (93.5)  ': '1.88',
        '    Total Kills (Heroic) - 2nd map          Under     (93.5)  ': '1.88',
        '    Total Kills (Heroic) - 2nd map        Even ': '1.88',
        '    Total Kills (Heroic) - 2nd map        Odd ': '1.88',
        '    Total Kills (OG)          Over     (230.5)  ': '1.88',
        '    Total Kills (OG)          Under     (230.5)  ': '1.88',
        '    Total Kills (OG)        Even ': '1.88',
        '    Total Kills (OG)        Odd ': '1.88',
        '    Total Kills (OG) - 1st map          Over     (91.5)  ': '1.88',
        '    Total Kills (OG) - 1st map          Under     (91.5)  ': '1.88',
        '    Total Kills (OG) - 1st map        Even ': '1.88',
        '    Total Kills (OG) - 1st map        Odd ': '1.88',
        '    Total Kills (OG) - 2nd map          Over     (91.5)  ': '1.88',
        '    Total Kills (OG) - 2nd map          Under     (91.5)  ': '1.88',
        '    Total Kills (OG) - 2nd map        Even ': '1.88',
        '    Total Kills (OG) - 2nd map        Odd ': '1.88',
        '    Total Kills - 1st map          Over     (185.5)  ': '1.87',
        '    Total Kills - 1st map          Under     (185.5)  ': '1.89',
        '    Total Kills - 1st map        Even ': '1.88',
        '    Total Kills - 1st map        Odd ': '1.88',
        '    Total Kills - 2nd map          Over     (185.5)  ': '1.87',
        '    Total Kills - 2nd map          Under     (185.5)  ': '1.89',
        '    Total Kills - 2nd map        Even ': '1.88',
        '    Total Kills - 2nd map        Odd ': '1.88',
        '    Total Maps          Over     (2.5)  ': '1.909',
        '    Total Maps          Under     (2.5)  ': '1.86',
        '    Total Maps        Even ': '1.86',
        '    Total Maps        Odd ': '1.909',
        '    Total Rounds          Over     (64.5)  ': '1.80',
        '    Total Rounds          Over     (65.5)  ': '1.83',
        '    Total Rounds          Over     (66.5)  ': '1.85',
        '    Total Rounds          Over     (67.5)  ': '1.86',
        '    Total Rounds          Over     (68.5)  ': '1.89',
        '    Total Rounds          Over     (69.5)  ': '1.909',
        '    Total Rounds          Over     (70.5)  ': '1.94',
        '    Total Rounds          Over     (71.5)  ': '1.99',
        '    Total Rounds          Under     (64.5)  ': '1.97',
        '    Total Rounds          Under     (65.5)  ': '1.93',
        '    Total Rounds          Under     (66.5)  ': '1.909',
        '    Total Rounds          Under     (67.5)  ': '1.90',
        '    Total Rounds          Under     (68.5)  ': '1.89',
        '    Total Rounds          Under     (69.5)  ': '1.85',
        '    Total Rounds          Under     (70.5)  ': '1.82',
        '    Total Rounds          Under     (71.5)  ': '1.78',
        '    Total Rounds        Even ': '1.90',
        '    Total Rounds        Odd ': '1.90',
        '    Total Rounds - 1st Map          Over     (27.5)  ': '2.10',
        '    Total Rounds - 1st Map          Under     (27.5)  ': '1.70',
        '    Total Rounds - 1st Map        Even ': '1.75',
        '    Total Rounds - 1st Map        Odd ': '2.03',
        '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.77',
        '    Total Rounds - 2nd Map          Under     (26.5)  ': '2.01',
        '    Total Rounds - 2nd Map        Even ': '1.76',
        '    Total Rounds - 2nd Map        Odd ': '2.02',
        'heroic will win': '1.63',
        'og will win': '2.28',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Summit/Main+Event/Best+of+3+maps/Heroic+vs+OG+-+9755590'
        },
    'lucid dream - invictus gaming': {
        '    Correct Score          Invictus Gaming     (0 - 2)  ': '2.00',
        '    Correct Score          Invictus Gaming     (1 - 2)  ': '3.02',
        '    Correct Score          Lucid Dream     (2 - 0)  ': '9.20',
        '    Correct Score          Lucid Dream     (2 - 1)  ': '6.10',
        '    To Win Match With Handicap By Maps          Invictus Gaming     (-1.5)  ': '2.00',
        '    To Win Match With Handicap By Maps          Lucid Dream     (+1.5)  ': '1.78',
        '    Total Maps          Over     (2.5)  ': '2.18',
        '    Total Maps          Under     (2.5)  ': '1.66',
        '    Total Maps        Even ': '1.66',
        '    Total Maps        Odd ': '2.18',
        'invictus gaming will win': '1.26',
        'lucid dream will win': '3.85',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Perfect+World+Asia+League+Summer/Main+Event/Best+of+3+maps/Lucid+Dream+vs+Invictus+Gaming+-+9734320'
        },
    'nemiga gaming - sprout': {
        '    Correct Score          Nemiga Gaming     (2 - 0)  ': '5.05',
        '    Correct Score          Nemiga Gaming     (2 - 1)  ': '4.20',
        '    Correct Score          Sprout     (0 - 2)  ': '2.84',
        '    Correct Score          Sprout     (1 - 2)  ': '3.16',
        '    To Win Match With Handicap By Maps          Nemiga Gaming     (+1.5)  ': '1.41',
        '    To Win Match With Handicap By Maps          Sprout     (-1.5)  ': '2.84',
        '    Total Maps          Over     (2.5)  ': '1.92',
        '    Total Maps          Under     (2.5)  ': '1.85',
        '    Total Maps        Even ': '1.85',
        '    Total Maps        Odd ': '1.92',
        'nemiga gaming will win': '2.40',
        'sprout will win': '1.57',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Hellcase+Cup/Main+Event/Best+of+3+maps/Nemiga+Gaming+vs+Sprout+-+9757945'
        },
    'new england whalers - chaos': {
        '    Correct Score          CHAOS     (0 - 2)  ': '2.02',
        '    Correct Score          CHAOS     (1 - 2)  ': '3.02',
        '    Correct Score          New England Whalers     (2 - 0)  ': '9.00',
        '    Correct Score          New England Whalers     (2 - 1)  ': '6.00',
        '    To Win Match With Handicap By Maps          CHAOS     (-1.5)  ': '2.02',
        '    To Win Match With Handicap By Maps          New England Whalers     (+1.5)  ': '1.76',
        '    Total Maps          Over     (2.5)  ': '2.17',
        '    Total Maps          Under     (2.5)  ': '1.66',
        '    Total Maps        Even ': '1.66',
        '    Total Maps        Odd ': '2.17',
        'chaos will win': '1.27',
        'new england whalers will win': '3.76',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/WINNERS+League/Main+Event/Best+of+3+maps/New+England+Whalers+vs+CHAOS+-+9758010'
        },
    'team liquid - evil geniuses': {
        '    1st Map Result         Evil Geniuses To Win   ': '1.85',
        '    1st Map Result         Team Liquid To Win   ': '1.909',
        '    2nd Map Result         Evil Geniuses To Win   ': '1.85',
        '    2nd Map Result         Team Liquid To Win   ': '1.909',
        '    Correct Score          Evil Geniuses     (0 - 2)  ': '3.58',
        '    Correct Score          Evil Geniuses     (1 - 2)  ': '3.50',
        '    Correct Score          Team Liquid     (2 - 0)  ': '3.80',
        '    Correct Score          Team Liquid     (2 - 1)  ': '3.62',
        '    Most Kills         Equal Number   ': '29.00',
        '    Most Kills         Evil Geniuses   ': '1.89',
        '    Most Kills         Evil Geniuses or Equal Number   ': '1.78',
        '    Most Kills         Team Liquid   ': '1.909',
        '    Most Kills         Team Liquid or Equal Number   ': '1.80',
        '    Most Kills - 1st map         Equal Number   ': '24.00',
        '    Most Kills - 1st map         Evil Geniuses   ': '1.909',
        '    Most Kills - 1st map         Team Liquid   ': '1.92',
        '    Most Kills - 2nd map         Equal Number   ': '24.00',
        '    Most Kills - 2nd map         Evil Geniuses   ': '1.909',
        '    Most Kills - 2nd map         Team Liquid   ': '1.92',
        '    Most Kills With Handicap          Evil Geniuses     (-0.5)  ': '1.90',
        '    Most Kills With Handicap          Team Liquid     (+0.5)  ': '1.86',
        '    Most Kills With Handicap - 1st map          Evil Geniuses     (-0.5)  ': '1.909',
        '    Most Kills With Handicap - 1st map          Team Liquid     (+0.5)  ': '1.85',
        '    Most Kills With Handicap - 2nd map          Evil Geniuses     (-0.5)  ': '1.909',
        '    Most Kills With Handicap - 2nd map          Team Liquid     (+0.5)  ': '1.85',
        '    To Win 1st Map With Handicap By Rounds          Evil Geniuses     (+2.5)  ': '1.63',
        '    To Win 1st Map With Handicap By Rounds          Team Liquid     (-2.5)  ': '2.22',
        '    To Win 2nd Map With Handicap By Rounds          Evil Geniuses     (+2.5)  ': '1.63',
        '    To Win 2nd Map With Handicap By Rounds          Team Liquid     (-2.5)  ': '2.22',
        '    To Win Match With Handicap By Maps          Evil Geniuses     (-1.5)  ': '3.58',
        '    To Win Match With Handicap By Maps          Team Liquid     (+1.5)  ': '1.28',
        '    To Win Match With Handicap By Rounds          Evil Geniuses     (+0.5)  ': '1.81',
        '    To Win Match With Handicap By Rounds          Evil Geniuses     (+1.5)  ': '1.74',
        '    To Win Match With Handicap By Rounds          Evil Geniuses     (-0.5)  ': '1.88',
        '    To Win Match With Handicap By Rounds          Evil Geniuses     (-1.5)  ': '1.95',
        '    To Win Match With Handicap By Rounds          Evil Geniuses     (-2.5)  ': '2.05',
        '    To Win Match With Handicap By Rounds          Evil Geniuses     (-3.5)  ': '2.14',
        '    To Win Match With Handicap By Rounds          Evil Geniuses     (0)  ': '1.84',
        '    To Win Match With Handicap By Rounds          Team Liquid     (+0.5)  ': '1.90',
        '    To Win Match With Handicap By Rounds          Team Liquid     (+1.5)  ': '1.83',
        '    To Win Match With Handicap By Rounds          Team Liquid     (+2.5)  ': '1.75',
        '    To Win Match With Handicap By Rounds          Team Liquid     (+3.5)  ': '1.69',
        '    To Win Match With Handicap By Rounds          Team Liquid     (-0.5)  ': '1.97',
        '    To Win Match With Handicap By Rounds          Team Liquid     (-1.5)  ': '2.06',
        '    To Win Match With Handicap By Rounds          Team Liquid     (0)  ': '1.94',
        '    Total Kills          Over     (473.5)  ': '1.88',
        '    Total Kills          Under     (473.5)  ': '1.88',
        '    Total Kills        Even ': '1.88',
        '    Total Kills        Odd ': '1.88',
        '    Total Kills (Evil Geniuses)          Over     (233.5)  ': '1.88',
        '    Total Kills (Evil Geniuses)          Under     (233.5)  ': '1.88',
        '    Total Kills (Evil Geniuses)        Even ': '1.88',
        '    Total Kills (Evil Geniuses)        Odd ': '1.88',
        '    Total Kills (Evil Geniuses) - 1st map          Over     (92.5)  ': '1.87',
        '    Total Kills (Evil Geniuses) - 1st map          Under     (92.5)  ': '1.89',
        '    Total Kills (Evil Geniuses) - 1st map        Even ': '1.88',
        '    Total Kills (Evil Geniuses) - 1st map        Odd ': '1.88',
        '    Total Kills (Evil Geniuses) - 2nd map          Over     (92.5)  ': '1.87',
        '    Total Kills (Evil Geniuses) - 2nd map          Under     (92.5)  ': '1.89',
        '    Total Kills (Evil Geniuses) - 2nd map        Even ': '1.88',
        '    Total Kills (Evil Geniuses) - 2nd map        Odd ': '1.88',
        '    Total Kills (Team Liquid)          Over     (233.5)  ': '1.88',
        '    Total Kills (Team Liquid)          Under     (233.5)  ': '1.88',
        '    Total Kills (Team Liquid)        Even ': '1.88',
        '    Total Kills (Team Liquid)        Odd ': '1.88',
        '    Total Kills (Team Liquid) - 1st map          Over     (92.5)  ': '1.87',
        '    Total Kills (Team Liquid) - 1st map          Under     (92.5)  ': '1.89',
        '    Total Kills (Team Liquid) - 1st map        Even ': '1.88',
        '    Total Kills (Team Liquid) - 1st map        Odd ': '1.88',
        '    Total Kills (Team Liquid) - 2nd map          Over     (92.5)  ': '1.87',
        '    Total Kills (Team Liquid) - 2nd map          Under     (92.5)  ': '1.89',
        '    Total Kills (Team Liquid) - 2nd map        Even ': '1.88',
        '    Total Kills (Team Liquid) - 2nd map        Odd ': '1.88',
        '    Total Kills - 1st map          Over     (186.5)  ': '1.90',
        '    Total Kills - 1st map          Under     (186.5)  ': '1.86',
        '    Total Kills - 1st map        Even ': '1.88',
        '    Total Kills - 1st map        Odd ': '1.88',
        '    Total Kills - 2nd map          Over     (186.5)  ': '1.90',
        '    Total Kills - 2nd map          Under     (186.5)  ': '1.86',
        '    Total Kills - 2nd map        Even ': '1.88',
        '    Total Kills - 2nd map        Odd ': '1.88',
        '    Total Maps          Over     (2.5)  ': '1.88',
        '    Total Maps          Under     (2.5)  ': '1.88',
        '    Total Maps        Even ': '1.88',
        '    Total Maps        Odd ': '1.88',
        '    Total Rounds          Over     (65.5)  ': '1.82',
        '    Total Rounds          Over     (66.5)  ': '1.85',
        '    Total Rounds          Over     (67.5)  ': '1.86',
        '    Total Rounds          Over     (68.5)  ': '1.89',
        '    Total Rounds          Over     (69.5)  ': '1.90',
        '    Total Rounds          Over     (70.5)  ': '1.94',
        '    Total Rounds          Over     (71.5)  ': '1.99',
        '    Total Rounds          Under     (65.5)  ': '1.95',
        '    Total Rounds          Under     (66.5)  ': '1.909',
        '    Total Rounds          Under     (67.5)  ': '1.90',
        '    Total Rounds          Under     (68.5)  ': '1.89',
        '    Total Rounds          Under     (69.5)  ': '1.86',
        '    Total Rounds          Under     (70.5)  ': '1.82',
        '    Total Rounds          Under     (71.5)  ': '1.78',
        '    Total Rounds        Even ': '1.90',
        '    Total Rounds        Odd ': '1.90',
        '    Total Rounds - 1st Map          Over     (26.5)  ': '1.75',
        '    Total Rounds - 1st Map          Under     (26.5)  ': '2.03',
        '    Total Rounds - 1st Map        Even ': '1.76',
        '    Total Rounds - 1st Map        Odd ': '2.02',
        '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.75',
        '    Total Rounds - 2nd Map          Under     (26.5)  ': '2.03',
        '    Total Rounds - 2nd Map        Even ': '1.76',
        '    Total Rounds - 2nd Map        Odd ': '2.02',
        'evil geniuses will win': '1.86',
        'team liquid will win': '1.94',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Summit/Main+Event/Best+of+3+maps/Team+Liquid+vs+Evil+Geniuses+-+9751272'
        },
    'tikitakan - brute': {
        '    1st Map Result         Brute To Win   ': '2.12',
        '    1st Map Result         Tikitakan To Win   ': '1.69',
        '    2nd Map Result         Brute To Win   ': '2.12',
        '    2nd Map Result         Tikitakan To Win   ': '1.69',
        '    Correct Score          Brute     (0 - 2)  ': '4.75',
        '    Correct Score          Brute     (1 - 2)  ': '4.05',
        '    Correct Score          Tikitakan     (2 - 0)  ': '2.97',
        '    Correct Score          Tikitakan     (2 - 1)  ': '3.22',
        '    To Win 1st Map With Handicap By Rounds          Brute     (+2.5)  ': '1.833',
        '    To Win 1st Map With Handicap By Rounds          Tikitakan     (-2.5)  ': '1.93',
        '    To Win 2nd Map With Handicap By Rounds          Brute     (+2.5)  ': '1.833',
        '    To Win 2nd Map With Handicap By Rounds          Tikitakan     (-2.5)  ': '1.93',
        '    To Win Match With Handicap By Maps          Brute     (+1.5)  ': '1.38',
        '    To Win Match With Handicap By Maps          Tikitakan     (-1.5)  ': '2.97',
        '    To Win Match With Handicap By Rounds          Brute     (+3.5)  ': '1.93',
        '    To Win Match With Handicap By Rounds          Tikitakan     (-3.5)  ': '1.85',
        '    Total Maps          Over     (2.5)  ': '1.909',
        '    Total Maps          Under     (2.5)  ': '1.86',
        '    Total Maps        Even ': '1.86',
        '    Total Maps        Odd ': '1.909',
        '    Total Rounds          Over     (67.5)  ': '1.89',
        '    Total Rounds          Under     (67.5)  ': '1.89',
        '    Total Rounds        Even ': '1.90',
        '    Total Rounds        Odd ': '1.90',
        '    Total Rounds - 1st Map          Over     (26.5)  ': '1.76',
        '    Total Rounds - 1st Map          Under     (26.5)  ': '2.02',
        '    Total Rounds - 1st Map        Even ': '1.76',
        '    Total Rounds - 1st Map        Odd ': '2.02',
        '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.76',
        '    Total Rounds - 2nd Map          Under     (26.5)  ': '2.02',
        '    Total Rounds - 2nd Map        Even ': '1.76',
        '    Total Rounds - 2nd Map        Odd ': '2.02',
        'brute will win': '2.28',
        'tikitakan will win': '1.63',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/ESEA+Advanced+Season/Main+Event/Best+of+3+maps/Tikitakan+vs+Brute+-+9751264'
        },
    'tyloo - mazaalai': {
        '    Correct Score          Mazaalai     (0 - 2)  ': '13.50',
        '    Correct Score          Mazaalai     (1 - 2)  ': '9.40',
        '    Correct Score          TyLoo     (2 - 0)  ': '1.62',
        '    Correct Score          TyLoo     (2 - 1)  ': '3.26',
        '    To Win Match With Handicap By Maps          Mazaalai     (+1.5)  ': '2.24',
        '    To Win Match With Handicap By Maps          TyLoo     (-1.5)  ': '1.62',
        '    Total Maps          Over     (2.5)  ': '2.58',
        '    Total Maps          Under     (2.5)  ': '1.48',
        '    Total Maps        Even ': '1.48',
        '    Total Maps        Odd ': '2.58',
        'mazaalai will win': '6.00',
        'tyloo will win': '1.129',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Perfect+World+Asia+League+Summer/Main+Event/Best+of+3+maps/TyLoo+vs+Mazaalai+-+9734321'
        },
    'vici gaming - divine vendetta': {
        '    Correct Score          Divine Vendetta     (0 - 2)  ': '13.00',
        '    Correct Score          Divine Vendetta     (1 - 2)  ': '9.20',
        '    Correct Score          Vici Gaming     (2 - 0)  ': '1.64',
        '    Correct Score          Vici Gaming     (2 - 1)  ': '3.24',
        '    To Win Match With Handicap By Maps          Divine Vendetta     (+1.5)  ': '2.22',
        '    To Win Match With Handicap By Maps          Vici Gaming     (-1.5)  ': '1.64',
        '    Total Maps          Over     (2.5)  ': '2.57',
        '    Total Maps          Under     (2.5)  ': '1.49',
        '    Total Maps        Even ': '1.49',
        '    Total Maps        Odd ': '2.57',
        'divine vendetta will win': '5.90',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Perfect+World+Asia+League+Summer/Main+Event/Best+of+3+maps/Vici+Gaming+vs+Divine+Vendetta+-+9734319',
        'vici gaming will win': '1.132'
        },
    'vitality - big': {
        '    1st Map Result         BIG To Win   ': '1.952',
        '    1st Map Result         Vitality To Win   ': '1.81',
        '    2nd Map Result         BIG To Win   ': '1.952',
        '    2nd Map Result         Vitality To Win   ': '1.81',
        '    Correct Score          BIG     (0 - 2)  ': '4.00',
        '    Correct Score          BIG     (1 - 2)  ': '3.72',
        '    Correct Score          Vitality     (2 - 0)  ': '3.40',
        '    Correct Score          Vitality     (2 - 1)  ': '3.44',
        '    Most Kills         BIG   ': '1.74',
        '    Most Kills         BIG or Equal Number   ': '1.65',
        '    Most Kills         Equal Number   ': '29.00',
        '    Most Kills         Vitality   ': '2.09',
        '    Most Kills         Vitality or Equal Number   ': '1.96',
        '    Most Kills - 1st map         BIG   ': '1.81',
        '    Most Kills - 1st map         Equal Number   ': '24.00',
        '    Most Kills - 1st map         Vitality   ': '2.03',
        '    Most Kills - 2nd map         BIG   ': '1.81',
        '    Most Kills - 2nd map         Equal Number   ': '24.00',
        '    Most Kills - 2nd map         Vitality   ': '2.03',
        '    Most Kills With Handicap          BIG     (-3.5)  ': '1.89',
        '    Most Kills With Handicap          Vitality     (+3.5)  ': '1.87',
        '    Most Kills With Handicap - 1st map          BIG     (-1.5)  ': '1.89',
        '    Most Kills With Handicap - 1st map          Vitality     (+1.5)  ': '1.87',
        '    Most Kills With Handicap - 2nd map          BIG     (-1.5)  ': '1.89',
        '    Most Kills With Handicap - 2nd map          Vitality     (+1.5)  ': '1.87',
        '    To Win 1st Map With Handicap By Rounds          BIG     (+2.5)  ': '1.72',
        '    To Win 1st Map With Handicap By Rounds          Vitality     (-2.5)  ': '2.07',
        '    To Win 2nd Map With Handicap By Rounds          BIG     (+2.5)  ': '1.72',
        '    To Win 2nd Map With Handicap By Rounds          Vitality     (-2.5)  ': '2.07',
        '    To Win Match With Handicap By Maps          BIG     (+1.5)  ': '1.30',
        '    To Win Match With Handicap By Maps          Vitality     (-1.5)  ': '3.40',
        '    To Win Match With Handicap By Rounds          BIG     (+0.5)  ': '1.96',
        '    To Win Match With Handicap By Rounds          BIG     (+1.5)  ': '1.89',
        '    To Win Match With Handicap By Rounds          BIG     (+2.5)  ': '1.81',
        '    To Win Match With Handicap By Rounds          BIG     (+3.5)  ': '1.74',
        '    To Win Match With Handicap By Rounds          BIG     (+4.5)  ': '1.66',
        '    To Win Match With Handicap By Rounds          BIG     (-0.5)  ': '2.05',
        '    To Win Match With Handicap By Rounds          BIG     (-1.5)  ': '2.15',
        '    To Win Match With Handicap By Rounds          BIG     (0)  ': '2.01',
        '    To Win Match With Handicap By Rounds          Vitality     (+0.5)  ': '1.75',
        '    To Win Match With Handicap By Rounds          Vitality     (+1.5)  ': '1.68',
        '    To Win Match With Handicap By Rounds          Vitality     (-0.5)  ': '1.82',
        '    To Win Match With Handicap By Rounds          Vitality     (-1.5)  ': '1.89',
        '    To Win Match With Handicap By Rounds          Vitality     (-2.5)  ': '1.97',
        '    To Win Match With Handicap By Rounds          Vitality     (-3.5)  ': '2.06',
        '    To Win Match With Handicap By Rounds          Vitality     (-4.5)  ': '2.19',
        '    To Win Match With Handicap By Rounds          Vitality     (0)  ': '1.78',
        '    Total Kills          Over     (471.5)  ': '1.88',
        '    Total Kills          Under     (471.5)  ': '1.88',
        '    Total Kills        Even ': '1.88',
        '    Total Kills        Odd ': '1.88',
        '    Total Kills (BIG)          Over     (234.5)  ': '1.88',
        '    Total Kills (BIG)          Under     (234.5)  ': '1.88',
        '    Total Kills (BIG)        Even ': '1.88',
        '    Total Kills (BIG)        Odd ': '1.88',
        '    Total Kills (BIG) - 1st map          Over     (93.5)  ': '1.90',
        '    Total Kills (BIG) - 1st map          Under     (93.5)  ': '1.86',
        '    Total Kills (BIG) - 1st map        Even ': '1.88',
        '    Total Kills (BIG) - 1st map        Odd ': '1.88',
        '    Total Kills (BIG) - 2nd map          Over     (93.5)  ': '1.90',
        '    Total Kills (BIG) - 2nd map          Under     (93.5)  ': '1.86',
        '    Total Kills (BIG) - 2nd map        Even ': '1.88',
        '    Total Kills (BIG) - 2nd map        Odd ': '1.88',
        '    Total Kills (Vitality)          Over     (231.5)  ': '1.88',
        '    Total Kills (Vitality)          Under     (231.5)  ': '1.88',
        '    Total Kills (Vitality)        Even ': '1.88',
        '    Total Kills (Vitality)        Odd ': '1.88',
        '    Total Kills (Vitality) - 1st map          Over     (91.5)  ': '1.84',
        '    Total Kills (Vitality) - 1st map          Under     (91.5)  ': '1.92',
        '    Total Kills (Vitality) - 1st map        Even ': '1.88',
        '    Total Kills (Vitality) - 1st map        Odd ': '1.88',
        '    Total Kills (Vitality) - 2nd map          Over     (91.5)  ': '1.84',
        '    Total Kills (Vitality) - 2nd map          Under     (91.5)  ': '1.92',
        '    Total Kills (Vitality) - 2nd map        Even ': '1.88',
        '    Total Kills (Vitality) - 2nd map        Odd ': '1.88',
        '    Total Kills - 1st map          Over     (185.5)  ': '1.86',
        '    Total Kills - 1st map          Under     (185.5)  ': '1.90',
        '    Total Kills - 1st map        Even ': '1.88',
        '    Total Kills - 1st map        Odd ': '1.88',
        '    Total Kills - 2nd map          Over     (185.5)  ': '1.86',
        '    Total Kills - 2nd map          Under     (185.5)  ': '1.90',
        '    Total Kills - 2nd map        Even ': '1.88',
        '    Total Kills - 2nd map        Odd ': '1.88',
        '    Total Maps          Over     (2.5)  ': '1.88',
        '    Total Maps          Under     (2.5)  ': '1.88',
        '    Total Maps        Even ': '1.88',
        '    Total Maps        Odd ': '1.88',
        '    Total Rounds          Over     (64.5)  ': '1.80',
        '    Total Rounds          Over     (65.5)  ': '1.83',
        '    Total Rounds          Over     (66.5)  ': '1.85',
        '    Total Rounds          Over     (67.5)  ': '1.86',
        '    Total Rounds          Over     (68.5)  ': '1.89',
        '    Total Rounds          Over     (69.5)  ': '1.909',
        '    Total Rounds          Over     (70.5)  ': '1.94',
        '    Total Rounds          Over     (71.5)  ': '1.99',
        '    Total Rounds          Under     (64.5)  ': '1.97',
        '    Total Rounds          Under     (65.5)  ': '1.93',
        '    Total Rounds          Under     (66.5)  ': '1.909',
        '    Total Rounds          Under     (67.5)  ': '1.90',
        '    Total Rounds          Under     (68.5)  ': '1.89',
        '    Total Rounds          Under     (69.5)  ': '1.85',
        '    Total Rounds          Under     (70.5)  ': '1.82',
        '    Total Rounds          Under     (71.5)  ': '1.78',
        '    Total Rounds        Even ': '1.90',
        '    Total Rounds        Odd ': '1.90',
        '    Total Rounds - 1st Map          Over     (26.5)  ': '1.75',
        '    Total Rounds - 1st Map          Under     (26.5)  ': '2.03',
        '    Total Rounds - 1st Map        Even ': '1.76',
        '    Total Rounds - 1st Map        Odd ': '2.02',
        '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.75',
        '    Total Rounds - 2nd Map          Under     (26.5)  ': '2.03',
        '    Total Rounds - 2nd Map        Even ': '1.76',
        '    Total Rounds - 2nd Map        Odd ': '2.02',
        'big will win': '2.02',
        'url': 'https://www.marathonbet.com/en/betting/e-Sports/CS%3AGO/Summit/Main+Event/Best+of+3+maps/Vitality+vs+BIG+-+9749903',
        'vitality will win': '1.79'
        }
    }
