bets =  {'ahq - asking questions': {'    Correct Score          Asking Questions     (0 - 2)  ': '4.85',
                            '    Correct Score          Asking Questions     (1 - 2)  ': '4.10',
                            '    Correct Score          ahq     (2 - 0)  ': '2.93',
                            '    Correct Score          ahq     (2 - 1)  ': '3.20',
                            '    To Win Match With Handicap By Maps          Asking Questions     (+1.5)  ': '1.39',
                            '    To Win Match With Handicap By Maps          ahq     (-1.5)  ': '2.93',
                            '    Total Maps          Over     (2.5)  ': '1.92',
                            '    Total Maps          Under     (2.5)  ': '1.85',
                            '    Total Maps        Even ': '1.85',
                            '    Total Maps        Odd ': '1.92',
                            'ahq will win': '1.61',
                            'asking questions will win': '2.32'},
 'apeks - nemiga gaming': {'    Correct Score          Apeks     (2 - 0)  ': '6.30',
                           '    Correct Score          Apeks     (2 - 1)  ': '6.60',
                           '    Correct Score          Nemiga Gaming     (0 - 2)  ': '2.06',
                           '    Correct Score          Nemiga Gaming     (1 - 2)  ': '3.24',
                           '    To Win Match With Handicap By Maps          Apeks     (+1.5)  ': '1.73',
                           '    To Win Match With Handicap By Maps          Nemiga Gaming     (-1.5)  ': '2.06',
                           '    Total Maps          Over     (2.5)  ': '2.36',
                           '    Total Maps          Under     (2.5)  ': '1.57',
                           '    Total Maps        Even ': '1.57',
                           '    Total Maps        Odd ': '2.36',
                           'apeks will win': '3.38',
                           'nemiga gaming will win': '1.32'},
 'avant - paradox': {'    Correct Score          AVANT     (2 - 0)  ': '1.909',
                     '    Correct Score          AVANT     (2 - 1)  ': '3.04',
                     '    Correct Score          Paradox     (0 - 2)  ': '10.25',
                     '    Correct Score          Paradox     (1 - 2)  ': '6.55',
                     '    To Win Match With Handicap By Maps          AVANT     (-1.5)  ': '1.909',
                     '    To Win Match With Handicap By Maps          Paradox     (+1.5)  ': '1.86',
                     '    Total Maps          Over     (2.5)  ': '2.25',
                     '    Total Maps          Under     (2.5)  ': '1.615',
                     '    Total Maps        Even ': '1.615',
                     '    Total Maps        Odd ': '2.25',
                     'avant will win': '1.23',
                     'paradox will win': '4.20'},
 'd13 - divine vendetta': {'    Correct Score          D13     (2 - 0)  ': '3.10',
                           '    Correct Score          D13     (2 - 1)  ': '3.28',
                           '    Correct Score          Divine Vendetta     (0 - 2)  ': '4.50',
                           '    Correct Score          Divine Vendetta     (1 - 2)  ': '3.92',
                           '    To Win Match With Handicap By Maps          D13     (-1.5)  ': '3.10',
                           '    To Win Match With Handicap By Maps          Divine Vendetta     (+1.5)  ': '1.35',
                           '    Total Maps          Over     (2.5)  ': '1.90',
                           '    Total Maps          Under     (2.5)  ': '1.87',
                           '    Total Maps        Even ': '1.87',
                           '    Total Maps        Odd ': '1.90',
                           'd13 will win': '1.68',
                           'divine vendetta will win': '2.19'},
 'grazur - lethal divide': {'    Correct Score          Grazur     (2 - 0)  ': '5.45',
                            '    Correct Score          Grazur     (2 - 1)  ': '4.40',
                            '    Correct Score          Lethal Divide     (0 - 2)  ': '2.69',
                            '    Correct Score          Lethal Divide     (1 - 2)  ': '3.125',
                            '    To Win Match With Handicap By Maps          Grazur     (+1.5)  ': '1.45',
                            '    To Win Match With Handicap By Maps          Lethal Divide     (-1.5)  ': '2.69',
                            '    Total Maps          Over     (2.5)  ': '1.94',
                            '    Total Maps          Under     (2.5)  ': '1.83',
                            '    Total Maps        Even ': '1.83',
                            '    Total Maps        Odd ': '1.94',
                            'grazur will win': '2.53',
                            'lethal divide will win': '1.52'},
 'ground zero - rooster': {'    Correct Score          Ground Zero     (2 - 0)  ': '5.95',
                           '    Correct Score          Ground Zero     (2 - 1)  ': '4.60',
                           '    Correct Score          Rooster     (0 - 2)  ': '2.54',
                           '    Correct Score          Rooster     (1 - 2)  ': '3.08',
                           '    To Win Match With Handicap By Maps          Ground Zero     (+1.5)  ': '1.50',
                           '    To Win Match With Handicap By Maps          Rooster     (-1.5)  ': '2.54',
                           '    Total Maps          Over     (2.5)  ': '1.97',
                           '    Total Maps          Under     (2.5)  ': '1.80',
                           '    Total Maps        Even ': '1.80',
                           '    Total Maps        Odd ': '1.97',
                           'ground zero will win': '2.72',
                           'rooster will win': '1.46'},
 'lucid dream - invictus gaming': {'    Correct Score          Invictus Gaming     (0 - 2)  ': '2.03',
                                   '    Correct Score          Invictus Gaming     (1 - 2)  ': '3.02',
                                   '    Correct Score          Lucid Dream     (2 - 0)  ': '9.00',
                                   '    Correct Score          Lucid Dream     (2 - 1)  ': '5.95',
                                   '    To Win Match With Handicap By Maps          Invictus Gaming     (-1.5)  ': '2.03',
                                   '    To Win Match With Handicap By Maps          Lucid Dream     (+1.5)  ': '1.76',
                                   '    Total Maps          Over     (2.5)  ': '2.16',
                                   '    Total Maps          Under     (2.5)  ': '1.666',
                                   '    Total Maps        Even ': '1.666',
                                   '    Total Maps        Odd ': '2.16',
                                   'invictus gaming will win': '1.27',
                                   'lucid dream will win': '3.76'},
 'mazaalai - invictus gaming': {'    1st Map Result         Invictus Gaming To Win   ': '1.35',
                                '    1st Map Result         Mazaalai To Win   ': '3.10',
                                '    2nd Map Result         Invictus Gaming To Win   ': '1.35',
                                '    2nd Map Result         Mazaalai To Win   ': '3.10',
                                '    Correct Score          Invictus Gaming     (0 - 2)  ': '1.87',
                                '    Correct Score          Invictus Gaming     (1 - 2)  ': '3.04',
                                '    Correct Score          Mazaalai     (2 - 0)  ': '10.75',
                                '    Correct Score          Mazaalai     (2 - 1)  ': '6.75',
                                '    To Win 1st Map With Handicap By Rounds          Invictus Gaming     (-4.5)  ': '1.97',
                                '    To Win 1st Map With Handicap By Rounds          Mazaalai     (+4.5)  ': '1.80',
                                '    To Win 2nd Map With Handicap By Rounds          Invictus Gaming     (-4.5)  ': '1.97',
                                '    To Win 2nd Map With Handicap By Rounds          Mazaalai     (+4.5)  ': '1.80',
                                '    To Win Match With Handicap By Maps          Invictus Gaming     (-1.5)  ': '1.87',
                                '    To Win Match With Handicap By Maps          Mazaalai     (+1.5)  ': '1.90',
                                '    To Win Match With Handicap By Rounds          Invictus Gaming     (-9.5)  ': '1.95',
                                '    To Win Match With Handicap By Rounds          Mazaalai     (+9.5)  ': '1.83',
                                '    Total Maps          Over     (2.5)  ': '2.28',
                                '    Total Maps          Under     (2.5)  ': '1.60',
                                '    Total Maps        Even ': '1.60',
                                '    Total Maps        Odd ': '2.28',
                                '    Total Rounds          Over     (58.5)  ': '1.909',
                                '    Total Rounds          Under     (58.5)  ': '1.87',
                                '    Total Rounds        Even ': '1.90',
                                '    Total Rounds        Odd ': '1.90',
                                '    Total Rounds - 1st Map          Over     (26.5)  ': '1.909',
                                '    Total Rounds - 1st Map          Under     (26.5)  ': '1.85',
                                '    Total Rounds - 1st Map        Even ': '1.78',
                                '    Total Rounds - 1st Map        Odd ': '1.99',
                                '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.909',
                                '    Total Rounds - 2nd Map          Under     (26.5)  ': '1.85',
                                '    Total Rounds - 2nd Map        Even ': '1.78',
                                '    Total Rounds - 2nd Map        Odd ': '1.99',
                                'invictus gaming will win': '1.22',
                                'mazaalai will win': '4.30'},
 'team liquid - evil geniuses': {'    1st Map Result         Evil Geniuses To Win   ': '1.88',
                                 '    1st Map Result         Team Liquid To Win   ': '1.88',
                                 '    2nd Map Result         Evil Geniuses To Win   ': '1.88',
                                 '    2nd Map Result         Team Liquid To Win   ': '1.88',
                                 '    Correct Score          Evil Geniuses     (0 - 2)  ': '3.66',
                                 '    Correct Score          Evil Geniuses     (1 - 2)  ': '3.55',
                                 '    Correct Score          Team Liquid     (2 - 0)  ': '3.70',
                                 '    Correct Score          Team Liquid     (2 - 1)  ': '3.58',
                                 '    Most Kills         Equal Number   ': '29.00',
                                 '    Most Kills         Evil Geniuses   ': '1.89',
                                 '    Most Kills         Evil Geniuses or Equal Number   ': '1.78',
                                 '    Most Kills         Team Liquid   ': '1.909',
                                 '    Most Kills         Team Liquid or Equal Number   ': '1.80',
                                 '    Most Kills - 1st map         Equal Number   ': '24.00',
                                 '    Most Kills - 1st map         Evil Geniuses   ': '1.909',
                                 '    Most Kills - 1st map         Team Liquid   ': '1.92',
                                 '    Most Kills - 2nd map         Equal Number   ': '24.00',
                                 '    Most Kills - 2nd map         Evil Geniuses   ': '1.909',
                                 '    Most Kills - 2nd map         Team Liquid   ': '1.92',
                                 '    Most Kills With Handicap          Evil Geniuses     (-0.5)  ': '1.90',
                                 '    Most Kills With Handicap          Team Liquid     (+0.5)  ': '1.86',
                                 '    Most Kills With Handicap - 1st map          Evil Geniuses     (-0.5)  ': '1.909',
                                 '    Most Kills With Handicap - 1st map          Team Liquid     (+0.5)  ': '1.85',
                                 '    Most Kills With Handicap - 2nd map          Evil Geniuses     (-0.5)  ': '1.909',
                                 '    Most Kills With Handicap - 2nd map          Team Liquid     (+0.5)  ': '1.85',
                                 '    To Win 1st Map With Handicap By Rounds          Evil Geniuses     (+2.5)  ': '1.65',
                                 '    To Win 1st Map With Handicap By Rounds          Team Liquid     (-2.5)  ': '2.18',
                                 '    To Win 2nd Map With Handicap By Rounds          Evil Geniuses     (+2.5)  ': '1.65',
                                 '    To Win 2nd Map With Handicap By Rounds          Team Liquid     (-2.5)  ': '2.18',
                                 '    To Win Match With Handicap By Maps          Evil Geniuses     (-1.5)  ': '3.66',
                                 '    To Win Match With Handicap By Maps          Team Liquid     (+1.5)  ': '1.27',
                                 '    To Win Match With Handicap By Rounds          Evil Geniuses     (+0.5)  ': '1.84',
                                 '    To Win Match With Handicap By Rounds          Evil Geniuses     (+1.5)  ': '1.77',
                                 '    To Win Match With Handicap By Rounds          Evil Geniuses     (-0.5)  ': '1.909',
                                 '    To Win Match With Handicap By Rounds          Evil Geniuses     (-1.5)  ': '2.00',
                                 '    To Win Match With Handicap By Rounds          Evil Geniuses     (-2.5)  ': '2.09',
                                 '    To Win Match With Handicap By Rounds          Evil Geniuses     (-3.5)  ': '2.19',
                                 '    To Win Match With Handicap By Rounds          Evil Geniuses     (0)  ': '1.88',
                                 '    To Win Match With Handicap By Rounds          Team Liquid     (+0.5)  ': '1.87',
                                 '    To Win Match With Handicap By Rounds          Team Liquid     (+1.5)  ': '1.79',
                                 '    To Win Match With Handicap By Rounds          Team Liquid     (+2.5)  ': '1.72',
                                 '    To Win Match With Handicap By Rounds          Team Liquid     (+3.5)  ': '1.66',
                                 '    To Win Match With Handicap By Rounds          Team Liquid     (-0.5)  ': '1.94',
                                 '    To Win Match With Handicap By Rounds          Team Liquid     (-1.5)  ': '2.02',
                                 '    To Win Match With Handicap By Rounds          Team Liquid     (0)  ': '1.90',
                                 '    Total Kills          Over     (473.5)  ': '1.88',
                                 '    Total Kills          Under     (473.5)  ': '1.88',
                                 '    Total Kills        Even ': '1.88',
                                 '    Total Kills        Odd ': '1.88',
                                 '    Total Kills (Evil Geniuses)          Over     (233.5)  ': '1.88',
                                 '    Total Kills (Evil Geniuses)          Under     (233.5)  ': '1.88',
                                 '    Total Kills (Evil Geniuses)        Even ': '1.88',
                                 '    Total Kills (Evil Geniuses)        Odd ': '1.88',
                                 '    Total Kills (Evil Geniuses) - 1st map          Over     (92.5)  ': '1.87',
                                 '    Total Kills (Evil Geniuses) - 1st map          Under     (92.5)  ': '1.89',
                                 '    Total Kills (Evil Geniuses) - 1st map        Even ': '1.88',
                                 '    Total Kills (Evil Geniuses) - 1st map        Odd ': '1.88',
                                 '    Total Kills (Evil Geniuses) - 2nd map          Over     (92.5)  ': '1.87',
                                 '    Total Kills (Evil Geniuses) - 2nd map          Under     (92.5)  ': '1.89',
                                 '    Total Kills (Evil Geniuses) - 2nd map        Even ': '1.88',
                                 '    Total Kills (Evil Geniuses) - 2nd map        Odd ': '1.88',
                                 '    Total Kills (Team Liquid)          Over     (233.5)  ': '1.88',
                                 '    Total Kills (Team Liquid)          Under     (233.5)  ': '1.88',
                                 '    Total Kills (Team Liquid)        Even ': '1.88',
                                 '    Total Kills (Team Liquid)        Odd ': '1.88',
                                 '    Total Kills (Team Liquid) - 1st map          Over     (92.5)  ': '1.87',
                                 '    Total Kills (Team Liquid) - 1st map          Under     (92.5)  ': '1.89',
                                 '    Total Kills (Team Liquid) - 1st map        Even ': '1.88',
                                 '    Total Kills (Team Liquid) - 1st map        Odd ': '1.88',
                                 '    Total Kills (Team Liquid) - 2nd map          Over     (92.5)  ': '1.87',
                                 '    Total Kills (Team Liquid) - 2nd map          Under     (92.5)  ': '1.89',
                                 '    Total Kills (Team Liquid) - 2nd map        Even ': '1.88',
                                 '    Total Kills (Team Liquid) - 2nd map        Odd ': '1.88',
                                 '    Total Kills - 1st map          Over     (186.5)  ': '1.90',
                                 '    Total Kills - 1st map          Under     (186.5)  ': '1.86',
                                 '    Total Kills - 1st map        Even ': '1.88',
                                 '    Total Kills - 1st map        Odd ': '1.88',
                                 '    Total Kills - 2nd map          Over     (186.5)  ': '1.90',
                                 '    Total Kills - 2nd map          Under     (186.5)  ': '1.86',
                                 '    Total Kills - 2nd map        Even ': '1.88',
                                 '    Total Kills - 2nd map        Odd ': '1.88',
                                 '    Total Maps          Over     (2.5)  ': '1.88',
                                 '    Total Maps          Under     (2.5)  ': '1.88',
                                 '    Total Maps        Even ': '1.88',
                                 '    Total Maps        Odd ': '1.88',
                                 '    Total Rounds          Over     (65.5)  ': '1.82',
                                 '    Total Rounds          Over     (66.5)  ': '1.85',
                                 '    Total Rounds          Over     (67.5)  ': '1.86',
                                 '    Total Rounds          Over     (68.5)  ': '1.89',
                                 '    Total Rounds          Over     (69.5)  ': '1.90',
                                 '    Total Rounds          Over     (70.5)  ': '1.94',
                                 '    Total Rounds          Over     (71.5)  ': '1.99',
                                 '    Total Rounds          Under     (65.5)  ': '1.95',
                                 '    Total Rounds          Under     (66.5)  ': '1.909',
                                 '    Total Rounds          Under     (67.5)  ': '1.90',
                                 '    Total Rounds          Under     (68.5)  ': '1.89',
                                 '    Total Rounds          Under     (69.5)  ': '1.86',
                                 '    Total Rounds          Under     (70.5)  ': '1.82',
                                 '    Total Rounds          Under     (71.5)  ': '1.78',
                                 '    Total Rounds        Even ': '1.90',
                                 '    Total Rounds        Odd ': '1.90',
                                 '    Total Rounds - 1st Map          Over     (26.5)  ': '1.75',
                                 '    Total Rounds - 1st Map          Under     (26.5)  ': '2.03',
                                 '    Total Rounds - 1st Map        Even ': '1.76',
                                 '    Total Rounds - 1st Map        Odd ': '2.02',
                                 '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.75',
                                 '    Total Rounds - 2nd Map          Under     (26.5)  ': '2.03',
                                 '    Total Rounds - 2nd Map        Even ': '1.76',
                                 '    Total Rounds - 2nd Map        Odd ': '2.02',
                                 'evil geniuses will win': '1.89',
                                 'team liquid will win': '1.909'},
 'tiger - lucid dream': {'    Correct Score          Lucid Dream     (0 - 2)  ': '6.85',
                         '    Correct Score          Lucid Dream     (1 - 2)  ': '5.05',
                         '    Correct Score          TIGER     (2 - 0)  ': '2.33',
                         '    Correct Score          TIGER     (2 - 1)  ': '3.02',
                         '    To Win Match With Handicap By Maps          Lucid Dream     (+1.5)  ': '1.58',
                         '    To Win Match With Handicap By Maps          TIGER     (-1.5)  ': '2.33',
                         '    Total Maps          Over     (2.5)  ': '2.03',
                         '    Total Maps          Under     (2.5)  ': '1.76',
                         '    Total Maps        Even ': '1.76',
                         '    Total Maps        Odd ': '2.03',
                         'lucid dream will win': '3.04',
                         'tiger will win': '1.38'},
 'truckers with attitude - chiefs': {'    Correct Score          Chiefs     (0 - 2)  ': '1.65',
                                     '    Correct Score          Chiefs     (1 - 2)  ': '3.22',
                                     '    Correct Score          TRUCKERS WITH ATTITUDE     (2 - 0)  ': '12.75',
                                     '    Correct Score          TRUCKERS WITH ATTITUDE     (2 - 1)  ': '9.10',
                                     '    To Win Match With Handicap By Maps          Chiefs     (-1.5)  ': '1.65',
                                     '    To Win Match With Handicap By Maps          TRUCKERS WITH ATTITUDE     (+1.5)  ': '2.20',
                                     '    Total Maps          Over     (2.5)  ': '2.54',
                                     '    Total Maps          Under     (2.5)  ': '1.50',
                                     '    Total Maps        Even ': '1.50',
                                     '    Total Maps        Odd ': '2.54',
                                     'chiefs will win': '1.137',
                                     'truckers with attitude will win': '5.75'},
 'tyloo - mazaalai': {'    Correct Score          Mazaalai     (0 - 2)  ': '13.50',
                      '    Correct Score          Mazaalai     (1 - 2)  ': '9.40',
                      '    Correct Score          TyLoo     (2 - 0)  ': '1.62',
                      '    Correct Score          TyLoo     (2 - 1)  ': '3.26',
                      '    To Win Match With Handicap By Maps          Mazaalai     (+1.5)  ': '2.24',
                      '    To Win Match With Handicap By Maps          TyLoo     (-1.5)  ': '1.62',
                      '    Total Maps          Over     (2.5)  ': '2.58',
                      '    Total Maps          Under     (2.5)  ': '1.48',
                      '    Total Maps        Even ': '1.48',
                      '    Total Maps        Odd ': '2.58',
                      'mazaalai will win': '6.00',
                      'tyloo will win': '1.129'},
 'vici gaming - divine vendetta': {'    Correct Score          Divine Vendetta     (0 - 2)  ': '13.50',
                                   '    Correct Score          Divine Vendetta     (1 - 2)  ': '7.90',
                                   '    Correct Score          Vici Gaming     (2 - 0)  ': '1.72',
                                   '    Correct Score          Vici Gaming     (2 - 1)  ': '3.10',
                                   '    To Win Match With Handicap By Maps          Divine Vendetta     (+1.5)  ': '2.08',
                                   '    To Win Match With Handicap By Maps          Vici Gaming     (-1.5)  ': '1.72',
                                   '    Total Maps          Over     (2.5)  ': '2.44',
                                   '    Total Maps          Under     (2.5)  ': '1.53',
                                   '    Total Maps        Even ': '1.53',
                                   '    Total Maps        Odd ': '2.44',
                                   'divine vendetta will win': '5.20',
                                   'vici gaming will win': '1.161'},
 'vitality - big': {'    1st Map Result         BIG To Win   ': '1.78',
                    '    1st Map Result         Vitality To Win   ': '1.99',
                    '    2nd Map Result         BIG To Win   ': '1.78',
                    '    2nd Map Result         Vitality To Win   ': '1.99',
                    '    Correct Score          BIG     (0 - 2)  ': '3.32',
                    '    Correct Score          BIG     (1 - 2)  ': '3.36',
                    '    Correct Score          Vitality     (2 - 0)  ': '4.15',
                    '    Correct Score          Vitality     (2 - 1)  ': '3.78',
                    '    Most Kills         BIG   ': '1.74',
                    '    Most Kills         BIG or Equal Number   ': '1.65',
                    '    Most Kills         Equal Number   ': '29.00',
                    '    Most Kills         Vitality   ': '2.09',
                    '    Most Kills         Vitality or Equal Number   ': '1.96',
                    '    Most Kills - 1st map         BIG   ': '1.81',
                    '    Most Kills - 1st map         Equal Number   ': '24.00',
                    '    Most Kills - 1st map         Vitality   ': '2.03',
                    '    Most Kills - 2nd map         BIG   ': '1.81',
                    '    Most Kills - 2nd map         Equal Number   ': '24.00',
                    '    Most Kills - 2nd map         Vitality   ': '2.03',
                    '    Most Kills With Handicap          BIG     (-3.5)  ': '1.89',
                    '    Most Kills With Handicap          Vitality     (+3.5)  ': '1.87',
                    '    Most Kills With Handicap - 1st map          BIG     (-1.5)  ': '1.89',
                    '    Most Kills With Handicap - 1st map          Vitality     (+1.5)  ': '1.87',
                    '    Most Kills With Handicap - 2nd map          BIG     (-1.5)  ': '1.89',
                    '    Most Kills With Handicap - 2nd map          Vitality     (+1.5)  ': '1.87',
                    '    To Win 1st Map With Handicap By Rounds          BIG     (-2.5)  ': '2.04',
                    '    To Win 1st Map With Handicap By Rounds          Vitality     (+2.5)  ': '1.74',
                    '    To Win 2nd Map With Handicap By Rounds          BIG     (-2.5)  ': '2.04',
                    '    To Win 2nd Map With Handicap By Rounds          Vitality     (+2.5)  ': '1.74',
                    '    To Win Match With Handicap By Maps          BIG     (-1.5)  ': '3.32',
                    '    To Win Match With Handicap By Maps          Vitality     (+1.5)  ': '1.32',
                    '    To Win Match With Handicap By Rounds          BIG     (+0.5)  ': '1.71',
                    '    To Win Match With Handicap By Rounds          BIG     (-0.5)  ': '1.77',
                    '    To Win Match With Handicap By Rounds          BIG     (-1.5)  ': '1.85',
                    '    To Win Match With Handicap By Rounds          BIG     (-2.5)  ': '1.92',
                    '    To Win Match With Handicap By Rounds          BIG     (-3.5)  ': '2.01',
                    '    To Win Match With Handicap By Rounds          BIG     (-4.5)  ': '2.14',
                    '    To Win Match With Handicap By Rounds          BIG     (-5.5)  ': '2.30',
                    '    To Win Match With Handicap By Rounds          BIG     (0)  ': '1.74',
                    '    To Win Match With Handicap By Rounds          Vitality     (+0.5)  ': '2.02',
                    '    To Win Match With Handicap By Rounds          Vitality     (+1.5)  ': '1.93',
                    '    To Win Match With Handicap By Rounds          Vitality     (+2.5)  ': '1.86',
                    '    To Win Match With Handicap By Rounds          Vitality     (+3.5)  ': '1.78',
                    '    To Win Match With Handicap By Rounds          Vitality     (+4.5)  ': '1.69',
                    '    To Win Match With Handicap By Rounds          Vitality     (+5.5)  ': '1.60',
                    '    To Win Match With Handicap By Rounds          Vitality     (-0.5)  ': '2.11',
                    '    To Win Match With Handicap By Rounds          Vitality     (0)  ': '2.06',
                    '    Total Kills          Over     (471.5)  ': '1.88',
                    '    Total Kills          Under     (471.5)  ': '1.88',
                    '    Total Kills        Even ': '1.88',
                    '    Total Kills        Odd ': '1.88',
                    '    Total Kills (BIG)          Over     (234.5)  ': '1.88',
                    '    Total Kills (BIG)          Under     (234.5)  ': '1.88',
                    '    Total Kills (BIG)        Even ': '1.88',
                    '    Total Kills (BIG)        Odd ': '1.88',
                    '    Total Kills (BIG) - 1st map          Over     (93.5)  ': '1.90',
                    '    Total Kills (BIG) - 1st map          Under     (93.5)  ': '1.86',
                    '    Total Kills (BIG) - 1st map        Even ': '1.88',
                    '    Total Kills (BIG) - 1st map        Odd ': '1.88',
                    '    Total Kills (BIG) - 2nd map          Over     (93.5)  ': '1.90',
                    '    Total Kills (BIG) - 2nd map          Under     (93.5)  ': '1.86',
                    '    Total Kills (BIG) - 2nd map        Even ': '1.88',
                    '    Total Kills (BIG) - 2nd map        Odd ': '1.88',
                    '    Total Kills (Vitality)          Over     (231.5)  ': '1.88',
                    '    Total Kills (Vitality)          Under     (231.5)  ': '1.88',
                    '    Total Kills (Vitality)        Even ': '1.88',
                    '    Total Kills (Vitality)        Odd ': '1.88',
                    '    Total Kills (Vitality) - 1st map          Over     (91.5)  ': '1.84',
                    '    Total Kills (Vitality) - 1st map          Under     (91.5)  ': '1.92',
                    '    Total Kills (Vitality) - 1st map        Even ': '1.88',
                    '    Total Kills (Vitality) - 1st map        Odd ': '1.88',
                    '    Total Kills (Vitality) - 2nd map          Over     (91.5)  ': '1.84',
                    '    Total Kills (Vitality) - 2nd map          Under     (91.5)  ': '1.92',
                    '    Total Kills (Vitality) - 2nd map        Even ': '1.88',
                    '    Total Kills (Vitality) - 2nd map        Odd ': '1.88',
                    '    Total Kills - 1st map          Over     (185.5)  ': '1.86',
                    '    Total Kills - 1st map          Under     (185.5)  ': '1.90',
                    '    Total Kills - 1st map        Even ': '1.88',
                    '    Total Kills - 1st map        Odd ': '1.88',
                    '    Total Kills - 2nd map          Over     (185.5)  ': '1.86',
                    '    Total Kills - 2nd map          Under     (185.5)  ': '1.90',
                    '    Total Kills - 2nd map        Even ': '1.88',
                    '    Total Kills - 2nd map        Odd ': '1.88',
                    '    Total Maps          Over     (2.5)  ': '1.88',
                    '    Total Maps          Under     (2.5)  ': '1.88',
                    '    Total Maps        Even ': '1.88',
                    '    Total Maps        Odd ': '1.88',
                    '    Total Rounds          Over     (64.5)  ': '1.80',
                    '    Total Rounds          Over     (65.5)  ': '1.83',
                    '    Total Rounds          Over     (66.5)  ': '1.85',
                    '    Total Rounds          Over     (67.5)  ': '1.86',
                    '    Total Rounds          Over     (68.5)  ': '1.89',
                    '    Total Rounds          Over     (69.5)  ': '1.909',
                    '    Total Rounds          Over     (70.5)  ': '1.94',
                    '    Total Rounds          Over     (71.5)  ': '1.99',
                    '    Total Rounds          Under     (64.5)  ': '1.97',
                    '    Total Rounds          Under     (65.5)  ': '1.93',
                    '    Total Rounds          Under     (66.5)  ': '1.909',
                    '    Total Rounds          Under     (67.5)  ': '1.90',
                    '    Total Rounds          Under     (68.5)  ': '1.89',
                    '    Total Rounds          Under     (69.5)  ': '1.85',
                    '    Total Rounds          Under     (70.5)  ': '1.82',
                    '    Total Rounds          Under     (71.5)  ': '1.78',
                    '    Total Rounds        Even ': '1.90',
                    '    Total Rounds        Odd ': '1.90',
                    '    Total Rounds - 1st Map          Over     (26.5)  ': '1.75',
                    '    Total Rounds - 1st Map          Under     (26.5)  ': '2.03',
                    '    Total Rounds - 1st Map        Even ': '1.76',
                    '    Total Rounds - 1st Map        Odd ': '2.02',
                    '    Total Rounds - 2nd Map          Over     (26.5)  ': '1.75',
                    '    Total Rounds - 2nd Map          Under     (26.5)  ': '2.03',
                    '    Total Rounds - 2nd Map        Even ': '1.76',
                    '    Total Rounds - 2nd Map        Odd ': '2.02',
                    'big will win': '1.75',
                    'vitality will win': '2.08'},
 'w2c - aim4r': {'    Correct Score          Aim4R     (0 - 2)  ': '5.30',
                 '    Correct Score          Aim4R     (1 - 2)  ': '4.333',
                 '    Correct Score          W2c     (2 - 0)  ': '2.73',
                 '    Correct Score          W2c     (2 - 1)  ': '3.14',
                 '    To Win Match With Handicap By Maps          Aim4R     (+1.5)  ': '1.44',
                 '    To Win Match With Handicap By Maps          W2c     (-1.5)  ': '2.73',
                 '    Total Maps          Over     (2.5)  ': '1.94',
                 '    Total Maps          Under     (2.5)  ': '1.83',
                 '    Total Maps        Even ': '1.83',
                 '    Total Maps        Odd ': '1.94',
                 'aim4r will win': '2.50',
                 'w2c will win': '1.53'}}
