bets = {
    'blinkal - adaptation': {
        '1x2. 1 map. Adaptation': '1.4',
        '1x2. 1 map. BlinkAL': '2.835',
        '1x2. Adaptation': '1.336',
        '1x2. BlinkAL': '3.184',
        'url': 'https://1x-bet.com/en/line/Esports/2097636-CSGO-Winners-League-Main-Division/78680468-BlinkAL-Adaptation/'
        },
    'bravos - sws gaming': {
        '1x2. 1 map. Bravos': '1.525',
        '1x2. 1 map. SWS Gaming': '2.43',
        '1x2. 2 map. Bravos': '1.53',
        '1x2. 2 map. SWS Gaming': '2.42',
        '1x2. Bravos': '1.42',
        '1x2. SWS Gaming': '2.78',
        'url': 'https://1x-bet.com/en/line/Esports/2064339-CSGO-CLUTCH/78634209-Bravos-SWS-Gaming/'
        },
    'cream real betis - neverest esports': {
        '1x2. 1 map. Cream Real Betis': '1.59',
        '1x2. 1 map. Neverest eSports': '2.28',
        '1x2. 2 map. Cream Real Betis': '1.59',
        '1x2. 2 map. Neverest eSports': '2.28',
        '1x2. Cream Real Betis': '1.51',
        '1x2. Neverest eSports': '2.504',
        'url': 'https://1x-bet.com/en/line/Esports/2064339-CSGO-CLUTCH/78634228-Cream-Real-Betis-Neverest-eSports/'
        },
    'divizon - planetkey dynamics': {
        '1x2. 1 map. DIVIZON': '1.62',
        '1x2. 1 map. Planetkey Dynamics': '2.23',
        '1x2. 2 map. DIVIZON': '1.63',
        '1x2. 2 map. Planetkey Dynamics': '2.21',
        '1x2. DIVIZON': '2.38',
        '1x2. Draw': '2.35',
        '1x2. Planetkey Dynamics': '4',
        'url': 'https://1x-bet.com/en/line/Esports/1390215-CSGO-99Damage/78691674-DIVIZON-Planetkey-Dynamics/'
        },
    'ex-smash - s-gaming': {
        '1x2. 1 map. S-Gaming': '2.56',
        '1x2. 1 map. ex-SMASH': '1.48',
        '1x2. 2 map. S-Gaming': '2.56',
        '1x2. 2 map. ex-SMASH': '1.48',
        '1x2. S-Gaming': '2.915',
        '1x2. ex-SMASH': '1.39',
        'url': 'https://1x-bet.com/en/line/Esports/2107656-CSGO-Nine-to-Five-Dawn/78698983-ex-SMASH-S-Gaming/'
        },
    'exploit esports - for the win': {
        '1x2. 1 map. Exploit Esports': '2.352',
        '1x2. 1 map. For The Win': '1.56',
        '1x2. Exploit Esports': '2.36',
        '1x2. For The Win': '1.57',
        'url': 'https://1x-bet.com/en/line/Esports/2092898-CSGO-One-Tap-League-Season-1/78697169-Exploit-Esports-For-The-Win/'
        },
    'fnatic - godsent': {
        '. ': '',
        '1x2. 1 map. Fnatic': '1.61',
        '1x2. 1 map. GODSENT': '2.37',
        '1x2. Fnatic': '1.504',
        '1x2. GODSENT': '2.625',
        'First Frag In Round - Team. 1 map. First Frag In 1 Round - Fnatic': '1.85',
        'First Frag In Round - Team. 1 map. First Frag In 1 Round - GODSENT': '1.9',
        'First Frag In Round - Team. 1 map. First Frag In 16 Round - Fnatic': '1.85',
        'First Frag In Round - Team. 1 map. First Frag In 16 Round - GODSENT': '1.9',
        'Handicap. 1 map. ': '',
        'Handicap. 1 map. Handiсap Fnatic (+2.5)': '1.43',
        'Handicap. 1 map. Handiсap Fnatic (+3.5)': '1.33',
        'Handicap. 1 map. Handiсap Fnatic (+4.5)': '1.24',
        'Handicap. 1 map. Handiсap Fnatic (-2.5)': '1.83',
        'Handicap. 1 map. Handiсap Fnatic (-3.5)': '2.12',
        'Handicap. 1 map. Handiсap Fnatic (-4.5)': '2.54',
        'Handicap. 1 map. Handiсap Fnatic (-5.5)': '3',
        'Handicap. 1 map. Handiсap Fnatic (-6.5)': '3.56',
        'Handicap. 1 map. Handiсap Fnatic (-7.5)': '4.3',
        'Handicap. 1 map. Handiсap GODSENT (+2.5)': '1.99',
        'Handicap. 1 map. Handiсap GODSENT (+3.5)': '1.74',
        'Handicap. 1 map. Handiсap GODSENT (+4.5)': '1.53',
        'Handicap. 1 map. Handiсap GODSENT (+5.5)': '1.4',
        'Handicap. 1 map. Handiсap GODSENT (+6.5)': '1.3',
        'Handicap. 1 map. Handiсap GODSENT (+7.5)': '1.23',
        'Handicap. 1 map. Handiсap GODSENT (-2.5)': '2.85',
        'Handicap. 1 map. Handiсap GODSENT (-3.5)': '3.4',
        'Handicap. 1 map. Handiсap GODSENT (-4.5)': '4.22',
        'Team 1 To Win At Least One Map. Team Fnatic To Win At Least One Map - Yes': '1.1',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Fnatic Exactly 0': '4.9',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Fnatic Exactly 1': '4.4',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Fnatic Exactly 2': '1.45',
        'Team 2 To Win At Least One Map. Team GODSENT To Win At Least One Map - No': '2.488',
        'Team 2 To Win At Least One Map. Team GODSENT To Win At Least One Map - Yes': '1.47',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team GODSENT Exactly 0': '1.95',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team GODSENT Exactly 1': '2.85',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team GODSENT Exactly 2': '2.55',
        'Total Maps Even/Odd. Total Maps - Even': '1.75',
        'Total Maps Even/Odd. Total Maps - Odd': '2.01',
        'Total Maps Handicap. Fnatic Handicap -1.5 Maps': '2.7',
        'Total Maps Handicap. Fnatic Handicap 1.5 Maps': '1.17',
        'Total Maps Handicap. GODSENT Handicap -1.5 Maps': '5.2',
        'Total Maps Handicap. GODSENT Handicap 1.5 Maps': '1.31',
        'Total Maps. Total Maps Over 2.5': '1.9',
        'Total Maps. Total Maps Under 2.5': '1.81',
        'Total. 1 map. ': '',
        'Total. 1 map. Total Over 22.5': '1.21',
        'Total. 1 map. Total Over 23.5': '1.3',
        'Total. 1 map. Total Over 24.5': '1.425',
        'Total. 1 map. Total Over 25.5': '1.62',
        'Total. 1 map. Total Over 26.5': '1.89',
        'Total. 1 map. Total Over 27.5': '2.35',
        'Total. 1 map. Total Under 22.5': '4.6',
        'Total. 1 map. Total Under 23.5': '3.58',
        'Total. 1 map. Total Under 24.5': '2.88',
        'Total. 1 map. Total Under 25.5': '2.32',
        'Total. 1 map. Total Under 26.5': '1.93',
        'Total. 1 map. Total Under 27.5': '1.61',
        'url': 'https://1x-bet.com/en/line/Esports/2105037-CSGO-cs-summit-6-Europe/78670279-Fnatic-GODSENT/'
        },
    'gamers 1337 - blinkal': {
        '1x2. 1 map. BlinkAL': '1.5',
        '1x2. 1 map. GamerS 1337': '2.5',
        '1x2. 2 map. BlinkAL': '1.5',
        '1x2. 2 map. GamerS 1337': '2.5',
        '1x2. BlinkAL': '1.39',
        '1x2. GamerS 1337': '2.92',
        'url': 'https://1x-bet.com/en/line/Esports/1826104-CSGO-A1-Adria-League/78692836-GamerS-1337-BlinkAL/'
        },
    'grazur esports - lethal divide': {
        '1x2. 1 map. Grazur Esports': '2.28',
        '1x2. 1 map. Lethal Divide': '1.59',
        '1x2. 2 map. Grazur Esports': '2.304',
        '1x2. 2 map. Lethal Divide': '1.58',
        '1x2. Grazur Esports': '2.71',
        '1x2. Lethal Divide': '1.445',
        'url': 'https://1x-bet.com/en/line/Esports/2097636-CSGO-Winners-League-Main-Division/78634241-Grazur-Esports-Lethal-Divide/'
        },
    'ground zero gaming - rooster': {
        '1x2. 1 map. Ground Zero Gaming': '2.352',
        '1x2. 1 map. Rooster': '1.56',
        '1x2. 2 map. Ground Zero Gaming': '2.37',
        '1x2. 2 map. Rooster': '1.55',
        '1x2. Ground Zero Gaming': '2.62',
        '1x2. Rooster': '1.47',
        'url': 'https://1x-bet.com/en/line/Esports/2091919-CSGO-ESEA-MDL-Season-34-Australia/78704358-Ground-Zero-Gaming-Rooster/'
        },
    'havu gaming - hard legion esports': {
        '. ': '',
        '1x2. 1 map. HAVU Gaming': '1.63',
        '1x2. 1 map. Hard Legion Esports': '2.215',
        '1x2. HAVU Gaming': '1.416',
        '1x2. Hard Legion Esports': '2.816',
        'Bomb Planted. 1 map. Bomb Planted In Round 1 - No': '2.25',
        'Bomb Planted. 1 map. Bomb Planted In Round 1 - Yes': '1.6',
        'Bomb Planted. 1 map. Bomb Planted In Round 16 - No': '2.25',
        'Bomb Planted. 1 map. Bomb Planted In Round 16 - Yes': '1.6',
        'Handicap. 1 map. Handiсap HAVU Gaming (+2.5)': '1.448',
        'Handicap. 1 map. Handiсap HAVU Gaming (+3.5)': '1.34',
        'Handicap. 1 map. Handiсap HAVU Gaming (+4.5)': '1.26',
        'Handicap. 1 map. Handiсap HAVU Gaming (+5.5)': '1.2',
        'Handicap. 1 map. Handiсap HAVU Gaming (+6.5)': '1.15',
        'Handicap. 1 map. Handiсap HAVU Gaming (-2.5)': '1.97',
        'Handicap. 1 map. Handiсap HAVU Gaming (-3.5)': '2.21',
        'Handicap. 1 map. Handiсap HAVU Gaming (-4.5)': '2.552',
        'Handicap. 1 map. Handiсap HAVU Gaming (-5.5)': '3.2',
        'Handicap. 1 map. Handiсap HAVU Gaming (-6.5)': '3.84',
        'Handicap. 1 map. Handiсap HAVU Gaming (-7.5)': '4.68',
        'Handicap. 1 map. Handiсap Hard Legion Esports (+2.5)': '1.784',
        'Handicap. 1 map. Handiсap Hard Legion Esports (+3.5)': '1.62',
        'Handicap. 1 map. Handiсap Hard Legion Esports (+4.5)': '1.48',
        'Handicap. 1 map. Handiсap Hard Legion Esports (+5.5)': '1.36',
        'Handicap. 1 map. Handiсap Hard Legion Esports (+6.5)': '1.27',
        'Handicap. 1 map. Handiсap Hard Legion Esports (+7.5)': '1.2',
        'Handicap. 1 map. Handiсap Hard Legion Esports (-2.5)': '2.79',
        'Handicap. 1 map. Handiсap Hard Legion Esports (-3.5)': '3.28',
        'Handicap. 1 map. Handiсap Hard Legion Esports (-4.5)': '3.94',
        'Handicap. 1 map. Handiсap Hard Legion Esports (-5.5)': '4.74',
        'Handicap. 1 map. Handiсap Hard Legion Esports (-6.5)': '5.65',
        'Method Of Win In Round. 1 map. ': '',
        'Method Of Win In Round. 1 map. Bomb Defused In Round 1': '3.5',
        'Method Of Win In Round. 1 map. Bomb Exploded In 1 Round': '15',
        'Round Total. 1 map. Total Frags In 1 Round Over 7.5': '2.25',
        'Round Total. 1 map. Total Frags In 1 Round Under 7.5': '1.6',
        'Round Total. 1 map. Total Frags In 16 Round Over 7.5': '2.25',
        'Round Total. 1 map. Total Frags In 16 Round Under 7.5': '1.6',
        'Total Maps Even/Odd. Total Maps - Even': '1.66',
        'Total Maps Even/Odd. Total Maps - Odd': '2.14',
        'Total Maps Handicap. HAVU Gaming Handicap -1.5 Maps': '2.45',
        'Total Maps Handicap. HAVU Gaming Handicap 1.5 Maps': '1.2',
        'Total Maps Handicap. Hard Legion Esports Handicap -1.5 Maps': '4.22',
        'Total Maps Handicap. Hard Legion Esports Handicap 1.5 Maps': '1.5',
        'Total Maps. Total Maps Over 2.5': '2.14',
        'Total Maps. Total Maps Under 2.5': '1.66',
        'Total. 1 map. Total Over 22.5': '1.19',
        'Total. 1 map. Total Over 23.5': '1.29',
        'Total. 1 map. Total Over 24.5': '1.42',
        'Total. 1 map. Total Over 25.5': '1.54',
        'Total. 1 map. Total Over 26.5': '1.81',
        'Total. 1 map. Total Over 27.5': '2.21',
        'Total. 1 map. Total Over 28.5': '3',
        'Total. 1 map. Total Over 29.5': '4.3',
        'Total. 1 map. Total Over 30.5': '9.3',
        'Total. 1 map. Total Under 22.5': '4.78',
        'Total. 1 map. Total Under 23.5': '3.68',
        'Total. 1 map. Total Under 24.5': '2.93',
        'Total. 1 map. Total Under 25.5': '2.38',
        'Total. 1 map. Total Under 26.5': '1.93',
        'Total. 1 map. Total Under 27.5': '1.62',
        'Total. 1 map. Total Under 28.5': '1.4',
        'Total. 1 map. Total Under 29.5': '1.23',
        'Total. 1 map. Total Under 30.5': '1.07',
        'Will There Be Overtime? - Yes/No. 1 map. Will There Be Overtime? - No': '1.07',
        'Will There Be Overtime? - Yes/No. 1 map. Will There Be Overtime? - Yes': '9',
        'Win In Round. 1 map. ': '',
        'url': 'https://1x-bet.com/en/line/Esports/2093139-CSGO-Hellcase-Cup-8/78667156-HAVU-Gaming-Hard-Legion-Esports/'
        },
    'heroic - og': {
        '. ': '',
        '1x2. 1 map. Heroic': '1.985',
        '1x2. 1 map. OG': '1.84',
        '1x2. Heroic': '1.616',
        '1x2. OG': '2.35',
        'First Frag In Round - Team. 1 map. First Frag In 1 Round - Heroic': '1.87',
        'First Frag In Round - Team. 1 map. First Frag In 1 Round - OG': '1.87',
        'First Frag In Round - Team. 1 map. First Frag In 16 Round - Heroic': '1.87',
        'First Frag In Round - Team. 1 map. First Frag In 16 Round - OG': '1.87',
        'Handicap. 1 map. ': '',
        'Handicap. 1 map. Handiсap Heroic (+2.5)': '1.61',
        'Handicap. 1 map. Handiсap Heroic (+3.5)': '1.45',
        'Handicap. 1 map. Handiсap Heroic (+4.5)': '1.34',
        'Handicap. 1 map. Handiсap Heroic (-2.5)': '2.18',
        'Handicap. 1 map. Handiсap Heroic (-3.5)': '2.59',
        'Handicap. 1 map. Handiсap Heroic (-4.5)': '3.185',
        'Handicap. 1 map. Handiсap Heroic (-5.5)': '3.78',
        'Handicap. 1 map. Handiсap Heroic (-6.5)': '4.54',
        'Handicap. 1 map. Handiсap Heroic (-7.5)': '5.45',
        'Handicap. 1 map. Handiсap OG (+2.5)': '1.7',
        'Handicap. 1 map. Handiсap OG (+3.5)': '1.52',
        'Handicap. 1 map. Handiсap OG (+4.5)': '1.36',
        'Handicap. 1 map. Handiсap OG (+5.5)': '1.28',
        'Handicap. 1 map. Handiсap OG (+6.5)': '1.21',
        'Handicap. 1 map. Handiсap OG (+7.5)': '1.16',
        'Handicap. 1 map. Handiсap OG (-2.5)': '2.336',
        'Handicap. 1 map. Handiсap OG (-3.5)': '2.76',
        'Handicap. 1 map. Handiсap OG (-4.5)': '3.34',
        'Team 1 To Win At Least One Map. Team Heroic To Win At Least One Map - No': '3.58',
        'Team 1 To Win At Least One Map. Team Heroic To Win At Least One Map - Yes': '1.216',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Heroic Exactly 0': '3.4',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Heroic Exactly 1': '3.5',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Heroic Exactly 2': '1.696',
        'Team 2 To Win At Least One Map. Team OG To Win At Least One Map - No': '2.73',
        'Team 2 To Win At Least One Map. Team OG To Win At Least One Map - Yes': '1.384',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team OG Exactly 0': '2.55',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team OG Exactly 1': '3.096',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team OG Exactly 2': '2.05',
        'Total Maps Even/Odd. Total Maps - Even': '1.8',
        'Total Maps Even/Odd. Total Maps - Odd': '1.94',
        'Total Maps Handicap. Heroic Handicap -1.5 Maps': '2.904',
        'Total Maps Handicap. Heroic Handicap 1.5 Maps': '1.225',
        'Total Maps Handicap. OG Handicap -1.5 Maps': '4.18',
        'Total Maps Handicap. OG Handicap 1.5 Maps': '1.4',
        'Total Maps. Total Maps Over 2.5': '1.94',
        'Total Maps. Total Maps Under 2.5': '1.75',
        'Total. 1 map. ': '',
        'Total. 1 map. Total Over 22.5': '1.19',
        'Total. 1 map. Total Over 23.5': '1.29',
        'Total. 1 map. Total Over 24.5': '1.416',
        'Total. 1 map. Total Over 25.5': '1.59',
        'Total. 1 map. Total Over 26.5': '1.85',
        'Total. 1 map. Total Over 27.5': '2.26',
        'Total. 1 map. Total Under 22.5': '4.8',
        'Total. 1 map. Total Under 23.5': '3.68',
        'Total. 1 map. Total Under 24.5': '2.94',
        'Total. 1 map. Total Under 25.5': '2.39',
        'Total. 1 map. Total Under 26.5': '1.97',
        'Total. 1 map. Total Under 27.5': '1.65',
        'url': 'https://1x-bet.com/en/line/Esports/2105037-CSGO-cs-summit-6-Europe/78670150-Heroic-OG/'
        },
    'honoris - wizards club': {
        '1x2. 1 map. HONORIS': '1.41',
        '1x2. 1 map. Wizards Club': '2.79',
        '1x2. 2 map. HONORIS': '1.41',
        '1x2. 2 map. Wizards Club': '2.79',
        '1x2. HONORIS': '1.32',
        '1x2. Wizards Club': '3.28',
        'url': 'https://1x-bet.com/en/line/Esports/2107656-CSGO-Nine-to-Five-Dawn/78700155-HONORIS-Wizards-Club/'
        },
    'illuminar - wisla krakow': {
        '1x2. 1 map. Illuminar': '1.7',
        '1x2. 1 map. Wisla Krakow': '2.09',
        '1x2. 2 map. Illuminar': '1.7',
        '1x2. 2 map. Wisla Krakow': '2.09',
        '1x2. Illuminar': '1.648',
        '1x2. Wisla Krakow': '2.2',
        'url': 'https://1x-bet.com/en/line/Esports/2107656-CSGO-Nine-to-Five-Dawn/78699312-Illuminar-Wisla-Krakow/'
        },
    'kova esports - veto': {
        '1x2. 1 map. KOVA Esports': '1.41',
        '1x2. 1 map. VETO': '2.79',
        '1x2. 2 map. KOVA Esports': '1.41',
        '1x2. 2 map. VETO': '2.79',
        '1x2. KOVA Esports': '1.22',
        '1x2. VETO': '3.32',
        'url': 'https://1x-bet.com/en/line/Esports/2089224-CSGO-Finnish-Esports-League-Season-8/78617464-KOVA-Esports-VETO/'
        },
    'ldlc - cr4zy': {
        '1x2. 1 map. CR4ZY': '1.75',
        '1x2. 1 map. LDLC': '2.015',
        '1x2. 2 map. CR4ZY': '1.75',
        '1x2. 2 map. LDLC': '2.015',
        '1x2. CR4ZY': '1.73',
        '1x2. LDLC': '2.06',
        'url': 'https://1x-bet.com/en/line/Esports/2107656-CSGO-Nine-to-Five-Dawn/78699308-LDLC-CR4ZY/'
        },
    'lucid dream - invictus gaming': {
        '1x2. 1 map. Invictus Gaming': '1.33',
        '1x2. 1 map. Lucid Dream': '3.17',
        '1x2. 2 map. Invictus Gaming': '1.33',
        '1x2. 2 map. Lucid Dream': '3.17',
        '1x2. Invictus Gaming': '1.24',
        '1x2. Lucid Dream': '3.92',
        'Handicap. 1 map. Handiсap Invictus Gaming (-3.5)': '1.71',
        'Handicap. 1 map. Handiсap Invictus Gaming (-4.5)': '1.92',
        'Handicap. 1 map. Handiсap Invictus Gaming (-5.5)': '2.19',
        'Handicap. 1 map. Handiсap Lucid Dream (+3.5)': '2.06',
        'Handicap. 1 map. Handiсap Lucid Dream (+4.5)': '1.82',
        'Handicap. 1 map. Handiсap Lucid Dream (+5.5)': '1.63',
        'Handicap. 2 map. Handiсap Invictus Gaming (-3.5)': '1.69',
        'Handicap. 2 map. Handiсap Invictus Gaming (-4.5)': '1.9',
        'Handicap. 2 map. Handiсap Invictus Gaming (-5.5)': '2.17',
        'Handicap. 2 map. Handiсap Lucid Dream (+3.5)': '2.09',
        'Handicap. 2 map. Handiсap Lucid Dream (+4.5)': '1.84',
        'Handicap. 2 map. Handiсap Lucid Dream (+5.5)': '1.64',
        'Total Maps Even/Odd. Total Maps - Even': '1.48',
        'Total Maps Even/Odd. Total Maps - Odd': '2.54',
        'Total Maps Handicap. Invictus Gaming Handicap -1.5 Maps': '1.73',
        'Total Maps Handicap. Invictus Gaming Handicap 1.5 Maps': '1.07',
        'Total Maps Handicap. Lucid Dream Handicap -1.5 Maps': '7.3',
        'Total Maps Handicap. Lucid Dream Handicap 1.5 Maps': '2.03',
        'Total Maps. Total Maps Over 2.5': '2.54',
        'Total Maps. Total Maps Under 2.5': '1.48',
        'Total. 1 map. Total Over 25.5': '1.66',
        'Total. 1 map. Total Over 26.5': '1.96',
        'Total. 1 map. Total Under 25.5': '2.14',
        'Total. 1 map. Total Under 26.5': '1.79',
        'Total. 2 map. Total Over 25.5': '1.67',
        'Total. 2 map. Total Over 26.5': '1.98',
        'Total. 2 map. Total Under 25.5': '2.12',
        'Total. 2 map. Total Under 26.5': '1.77',
        'Win In Round. 1 map. Invictus Gaming Will Win In Round 1': '1.78',
        'Win In Round. 1 map. Invictus Gaming Will Win In Round 16': '1.78',
        'Win In Round. 1 map. Lucid Dream Will Win In Round 1': '1.97',
        'Win In Round. 1 map. Lucid Dream Will Win In Round 16': '1.97',
        'Win In Round. 2 map. Invictus Gaming Will Win In Round 1': '1.77',
        'Win In Round. 2 map. Invictus Gaming Will Win In Round 16': '1.77',
        'Win In Round. 2 map. Lucid Dream Will Win In Round 1': '1.98',
        'Win In Round. 2 map. Lucid Dream Will Win In Round 16': '1.98',
        'url': 'https://1x-bet.com/en/line/Esports/2106875-CSGO-Perfect-World-Asia-League-Summer-2020/78631196-Lucid-Dream-Invictus-Gaming/'
        },
    'nemiga gaming - cr4zy': {
        '1x2. 1 map. CR4ZY': '4.16',
        '1x2. 1 map. Nemiga Gaming': '1.21',
        '1x2. 2 map. CR4ZY': '4.16',
        '1x2. 2 map. Nemiga Gaming': '1.21',
        '1x2. CR4ZY': '6.2',
        '1x2. Nemiga Gaming': '1.11',
        'Handicap. 1 map. Handiсap CR4ZY (+4.5)': '2.17',
        'Handicap. 1 map. Handiсap CR4ZY (+5.5)': '1.88',
        'Handicap. 1 map. Handiсap CR4ZY (+6.5)': '1.65',
        'Handicap. 1 map. Handiсap Nemiga Gaming (-4.5)': '1.64',
        'Handicap. 1 map. Handiсap Nemiga Gaming (-5.5)': '1.86',
        'Handicap. 1 map. Handiсap Nemiga Gaming (-6.5)': '2.16',
        'Handicap. 2 map. Handiсap CR4ZY (+4.5)': '2.19',
        'Handicap. 2 map. Handiсap CR4ZY (+5.5)': '1.9',
        'Handicap. 2 map. Handiсap CR4ZY (+6.5)': '1.66',
        'Handicap. 2 map. Handiсap Nemiga Gaming (-4.5)': '1.63',
        'Handicap. 2 map. Handiсap Nemiga Gaming (-5.5)': '1.84',
        'Handicap. 2 map. Handiсap Nemiga Gaming (-6.5)': '2.14',
        'Total Maps Even/Odd. Total Maps - Even': '1.35',
        'Total Maps Even/Odd. Total Maps - Odd': '3.04',
        'Total Maps Handicap. CR4ZY Handicap -1.5 Maps': '10',
        'Total Maps Handicap. CR4ZY Handicap 1.5 Maps': '2.63',
        'Total Maps Handicap. Nemiga Gaming Handicap -1.5 Maps': '1.43',
        'Total Maps Handicap. Nemiga Gaming Handicap 1.5 Maps': '1.03',
        'Total Maps. Total Maps Over 2.5': '3.04',
        'Total Maps. Total Maps Under 2.5': '1.35',
        'Total. 1 map. Total Over 24.5': '1.55',
        'Total. 1 map. Total Over 25.5': '1.8',
        'Total. 1 map. Total Over 26.5': '2.16',
        'Total. 1 map. Total Under 24.5': '2.35',
        'Total. 1 map. Total Under 25.5': '1.94',
        'Total. 1 map. Total Under 26.5': '1.65',
        'Total. 2 map. Total Over 24.5': '1.56',
        'Total. 2 map. Total Over 25.5': '1.82',
        'Total. 2 map. Total Over 26.5': '2.17',
        'Total. 2 map. Total Under 24.5': '2.33',
        'Total. 2 map. Total Under 25.5': '1.92',
        'Total. 2 map. Total Under 26.5': '1.64',
        'Win In Round. 1 map. CR4ZY Will Win In Round 1': '2.02',
        'Win In Round. 1 map. CR4ZY Will Win In Round 16': '2.02',
        'Win In Round. 1 map. Nemiga Gaming Will Win In Round 1': '1.74',
        'Win In Round. 1 map. Nemiga Gaming Will Win In Round 16': '1.74',
        'Win In Round. 2 map. CR4ZY Will Win In Round 1': '2.02',
        'Win In Round. 2 map. CR4ZY Will Win In Round 16': '2.02',
        'Win In Round. 2 map. Nemiga Gaming Will Win In Round 1': '1.74',
        'Win In Round. 2 map. Nemiga Gaming Will Win In Round 16': '1.74',
        'url': 'https://1x-bet.com/en/line/Esports/1842596-CSGO-Winners-League/78632188-Nemiga-Gaming-CR4ZY/'
        },
    'new england whalers - chaos': {
        '1x2. 1 map. CHAOS': '1.36',
        '1x2. 1 map. New England Whalers': '3.01',
        '1x2. 2 map. CHAOS': '1.36',
        '1x2. 2 map. New England Whalers': '3.01',
        '1x2. CHAOS': '1.27',
        '1x2. New England Whalers': '3.64',
        'Handicap. 1 map. Handiсap CHAOS (-2.5)': '1.6',
        'Handicap. 1 map. Handiсap CHAOS (-3.5)': '1.76',
        'Handicap. 1 map. Handiсap CHAOS (-4.5)': '1.98',
        'Handicap. 1 map. Handiсap CHAOS (-5.5)': '2.29',
        'Handicap. 1 map. Handiсap New England Whalers (+2.5)': '2.25',
        'Handicap. 1 map. Handiсap New England Whalers (+3.5)': '1.99',
        'Handicap. 1 map. Handiсap New England Whalers (+4.5)': '1.77',
        'Handicap. 1 map. Handiсap New England Whalers (+5.5)': '1.58',
        'Handicap. 2 map. Handiсap CHAOS (-2.5)': '1.59',
        'Handicap. 2 map. Handiсap CHAOS (-3.5)': '1.75',
        'Handicap. 2 map. Handiсap CHAOS (-4.5)': '1.97',
        'Handicap. 2 map. Handiсap CHAOS (-5.5)': '2.25',
        'Handicap. 2 map. Handiсap New England Whalers (+2.5)': '2.27',
        'Handicap. 2 map. Handiсap New England Whalers (+3.5)': '2.01',
        'Handicap. 2 map. Handiсap New England Whalers (+4.5)': '1.78',
        'Handicap. 2 map. Handiсap New England Whalers (+5.5)': '1.6',
        'Total Maps Even/Odd. Total Maps - Even': '1.51',
        'Total Maps Even/Odd. Total Maps - Odd': '2.45',
        'Total Maps Handicap. CHAOS Handicap -1.5 Maps': '1.805',
        'Total Maps Handicap. CHAOS Handicap 1.5 Maps': '1.08',
        'Total Maps Handicap. New England Whalers Handicap -1.5 Maps': '6.9',
        'Total Maps Handicap. New England Whalers Handicap 1.5 Maps': '1.93',
        'Total Maps. Total Maps Over 2.5': '2.45',
        'Total Maps. Total Maps Under 2.5': '1.51',
        'Total. 1 map. Total Over 25.5': '1.63',
        'Total. 1 map. Total Over 26.5': '1.93',
        'Total. 1 map. Total Over 27.5': '2.38',
        'Total. 1 map. Total Under 25.5': '2.19',
        'Total. 1 map. Total Under 26.5': '1.81',
        'Total. 1 map. Total Under 27.5': '1.54',
        'Total. 2 map. Total Over 25.5': '1.64',
        'Total. 2 map. Total Over 26.5': '1.94',
        'Total. 2 map. Total Over 27.5': '2.4',
        'Total. 2 map. Total Under 25.5': '2.17',
        'Total. 2 map. Total Under 26.5': '1.8',
        'Total. 2 map. Total Under 27.5': '1.53',
        'Win In Round. 1 map. CHAOS Will Win In Round 1': '1.79',
        'Win In Round. 1 map. CHAOS Will Win In Round 16': '1.78',
        'Win In Round. 1 map. New England Whalers Will Win In Round 1': '1.96',
        'Win In Round. 1 map. New England Whalers Will Win In Round 16': '1.97',
        'Win In Round. 2 map. CHAOS Will Win In Round 1': '1.78',
        'Win In Round. 2 map. CHAOS Will Win In Round 16': '1.78',
        'Win In Round. 2 map. New England Whalers Will Win In Round 1': '1.97',
        'Win In Round. 2 map. New England Whalers Will Win In Round 16': '1.97',
        'url': 'https://1x-bet.com/en/line/Esports/1842596-CSGO-Winners-League/78693140-New-England-Whalers-CHAOS/'
        },
    'nordavind - forze': {
        '. ': '',
        '1x2. 1 map. Nordavind': '2.26',
        '1x2. 1 map. forZe': '1.6',
        '1x2. Nordavind': '2.504',
        '1x2. forZe': '1.51',
        'Bomb Planted. 1 map. Bomb Planted In Round 1 - No': '2.25',
        'Bomb Planted. 1 map. Bomb Planted In Round 1 - Yes': '1.6',
        'Bomb Planted. 1 map. Bomb Planted In Round 16 - No': '2.25',
        'Bomb Planted. 1 map. Bomb Planted In Round 16 - Yes': '1.6',
        'Handicap. 1 map. Handiсap Nordavind (+2.5)': '1.83',
        'Handicap. 1 map. Handiсap Nordavind (+3.5)': '1.65',
        'Handicap. 1 map. Handiсap Nordavind (+4.5)': '1.51',
        'Handicap. 1 map. Handiсap Nordavind (+5.5)': '1.38',
        'Handicap. 1 map. Handiсap Nordavind (+6.5)': '1.29',
        'Handicap. 1 map. Handiсap Nordavind (+7.5)': '1.22',
        'Handicap. 1 map. Handiсap Nordavind (-2.5)': '2.77',
        'Handicap. 1 map. Handiсap Nordavind (-3.5)': '3.3',
        'Handicap. 1 map. Handiсap Nordavind (-4.5)': '4.12',
        'Handicap. 1 map. Handiсap Nordavind (-5.5)': '4.98',
        'Handicap. 1 map. Handiсap Nordavind (-6.5)': '6',
        'Handicap. 1 map. Handiсap forZe (+2.5)': '1.46',
        'Handicap. 1 map. Handiсap forZe (+3.5)': '1.34',
        'Handicap. 1 map. Handiсap forZe (+4.5)': '1.24',
        'Handicap. 1 map. Handiсap forZe (+5.5)': '1.18',
        'Handicap. 1 map. Handiсap forZe (+6.5)': '1.14',
        'Handicap. 1 map. Handiсap forZe (-2.5)': '1.91',
        'Handicap. 1 map. Handiсap forZe (-3.5)': '2.16',
        'Handicap. 1 map. Handiсap forZe (-4.5)': '2.45',
        'Handicap. 1 map. Handiсap forZe (-5.5)': '3.11',
        'Handicap. 1 map. Handiсap forZe (-6.5)': '3.68',
        'Handicap. 1 map. Handiсap forZe (-7.5)': '4.44',
        'Method Of Win In Round. 1 map. ': '',
        'Method Of Win In Round. 1 map. Bomb Defused In Round 1': '3.5',
        'Method Of Win In Round. 1 map. Bomb Exploded In 1 Round': '15',
        'Round Total. 1 map. Total Frags In 1 Round Over 7.5': '2.25',
        'Round Total. 1 map. Total Frags In 1 Round Under 7.5': '1.6',
        'Round Total. 1 map. Total Frags In 16 Round Over 7.5': '2.25',
        'Round Total. 1 map. Total Frags In 16 Round Under 7.5': '1.6',
        'Total Maps Even/Odd. Total Maps - Even': '1.65',
        'Total Maps Even/Odd. Total Maps - Odd': '2.16',
        'Total Maps Handicap. Nordavind Handicap -1.5 Maps': '4.48',
        'Total Maps Handicap. Nordavind Handicap 1.5 Maps': '1.51',
        'Total Maps Handicap. forZe Handicap -1.5 Maps': '2.38',
        'Total Maps Handicap. forZe Handicap 1.5 Maps': '1.18',
        'Total Maps. Total Maps Over 2.5': '2.155',
        'Total Maps. Total Maps Under 2.5': '1.65',
        'Total. 1 map. Total Over 22.5': '1.2',
        'Total. 1 map. Total Over 23.5': '1.3',
        'Total. 1 map. Total Over 24.5': '1.42',
        'Total. 1 map. Total Over 25.5': '1.55',
        'Total. 1 map. Total Over 26.5': '1.82',
        'Total. 1 map. Total Over 27.5': '2.23',
        'Total. 1 map. Total Over 28.5': '3.07',
        'Total. 1 map. Total Over 29.5': '4.44',
        'Total. 1 map. Total Over 30.5': '9.1',
        'Total. 1 map. Total Under 22.5': '4.66',
        'Total. 1 map. Total Under 23.5': '3.62',
        'Total. 1 map. Total Under 24.5': '2.91',
        'Total. 1 map. Total Under 25.5': '2.35',
        'Total. 1 map. Total Under 26.5': '1.92',
        'Total. 1 map. Total Under 27.5': '1.61',
        'Total. 1 map. Total Under 28.5': '1.39',
        'Total. 1 map. Total Under 29.5': '1.22',
        'Total. 1 map. Total Under 30.5': '1.08',
        'Will There Be Overtime? - Yes/No. 1 map. Will There Be Overtime? - No': '1.07',
        'Will There Be Overtime? - Yes/No. 1 map. Will There Be Overtime? - Yes': '9',
        'Win In Round. 1 map. ': '',
        'url': 'https://1x-bet.com/en/line/Esports/2093139-CSGO-Hellcase-Cup-8/78654581-Nordavind-forZe/'
        },
    'northern forces - tnt': {
        '1x2. 1 map. Northern Forces': '1.68',
        '1x2. 1 map. tNt': '2.125',
        '1x2. 2 map. Northern Forces': '1.68',
        '1x2. 2 map. tNt': '2.125',
        '1x2. Northern Forces': '1.56',
        '1x2. tNt': '2.38',
        'url': 'https://1x-bet.com/en/line/Esports/2097636-CSGO-Winners-League-Main-Division/78634230-Northern-Forces-tNt/'
        },
    'qske - lvlup': {
        '1x2. 1 map. LVLUP': '1.55',
        '1x2. 1 map. QSKE': '2.37',
        '1x2. 2 map. LVLUP': '1.54',
        '1x2. 2 map. QSKE': '2.4',
        '1x2. LVLUP': '1.36',
        '1x2. QSKE': '2.725',
        'url': 'https://1x-bet.com/en/line/Esports/1826104-CSGO-A1-Adria-League/78692830-QSKE-LVLUP/'
        },
    'saw - agf': {
        '1x2. 1 map. AGF': '2.325',
        '1x2. 1 map. sAw': '1.57',
        '1x2. 2 map. AGF': '2.325',
        '1x2. 2 map. sAw': '1.57',
        '1x2. AGF': '2.568',
        '1x2. sAw': '1.488',
        'url': 'https://1x-bet.com/en/line/Esports/2107656-CSGO-Nine-to-Five-Dawn/78695966-sAw-AGF/'
        },
    'team liquid - evil geniuses': {
        '. ': '',
        '1x2. 1 map. Evil Geniuses': '1.775',
        '1x2. 1 map. Team Liquid': '2',
        '1x2. Evil Geniuses': '1.7',
        '1x2. Team Liquid': '2.12',
        'First Frag In Round - Team. 1 map. First Frag In 1 Round - Evil Geniuses': '1.87',
        'First Frag In Round - Team. 1 map. First Frag In 1 Round - Team Liquid': '1.87',
        'First Frag In Round - Team. 1 map. First Frag In 16 Round - Evil Geniuses': '1.87',
        'First Frag In Round - Team. 1 map. First Frag In 16 Round - Team Liquid': '1.87',
        'Handicap. 1 map. ': '',
        'Handicap. 1 map. Handiсap Evil Geniuses (+2.5)': '1.47',
        'Handicap. 1 map. Handiсap Evil Geniuses (+3.5)': '1.36',
        'Handicap. 1 map. Handiсap Evil Geniuses (+4.5)': '1.27',
        'Handicap. 1 map. Handiсap Evil Geniuses (+5.5)': '1.2',
        'Handicap. 1 map. Handiсap Evil Geniuses (+6.5)': '1.21',
        'Handicap. 1 map. Handiсap Evil Geniuses (-2.5)': '2.19',
        'Handicap. 1 map. Handiсap Evil Geniuses (-3.5)': '2.51',
        'Handicap. 1 map. Handiсap Evil Geniuses (-4.5)': '2.94',
        'Handicap. 1 map. Handiсap Evil Geniuses (-5.5)': '3.54',
        'Handicap. 1 map. Handiсap Team Liquid (+2.5)': '1.63',
        'Handicap. 1 map. Handiсap Team Liquid (+3.5)': '1.49',
        'Handicap. 1 map. Handiсap Team Liquid (+4.5)': '1.37',
        'Handicap. 1 map. Handiсap Team Liquid (+5.5)': '1.27',
        'Handicap. 1 map. Handiсap Team Liquid (-2.5)': '2.57',
        'Handicap. 1 map. Handiсap Team Liquid (-3.5)': '2.99',
        'Handicap. 1 map. Handiсap Team Liquid (-4.5)': '3.54',
        'Handicap. 1 map. Handiсap Team Liquid (-5.5)': '4.22',
        'Handicap. 1 map. Handiсap Team Liquid (-6.5)': '4.54',
        'Team 1 To Win At Least One Map. Team Team Liquid To Win At Least One Map - Yes': '1.28',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Team Liquid Exactly 0': '2.7',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Team Liquid Exactly 1': '3.2',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Team Liquid Exactly 2': '1.9',
        'Team 2 To Win At Least One Map. Team Evil Geniuses To Win At Least One Map - Yes': '1.2',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team Evil Geniuses Exactly 0': '3.2',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team Evil Geniuses Exactly 1': '3.4',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team Evil Geniuses Exactly 2': '1.8',
        'Total Maps Even/Odd. Total Maps - Even': '1.8',
        'Total Maps Even/Odd. Total Maps - Odd': '1.94',
        'Total Maps Handicap. Evil Geniuses Handicap -1.5 Maps': '3.04',
        'Total Maps Handicap. Evil Geniuses Handicap 1.5 Maps': '1.24',
        'Total Maps Handicap. Team Liquid Handicap -1.5 Maps': '3.78',
        'Total Maps Handicap. Team Liquid Handicap 1.5 Maps': '1.34',
        'Total Maps. Total Maps Over 2.5': '1.92',
        'Total Maps. Total Maps Under 2.5': '1.8',
        'Total. 1 map. ': '',
        'Total. 1 map. Total Over 22.5': '1.19',
        'Total. 1 map. Total Over 23.5': '1.29',
        'Total. 1 map. Total Over 24.5': '1.3',
        'Total. 1 map. Total Over 25.5': '1.46',
        'Total. 1 map. Total Over 26.5': '1.7',
        'Total. 1 map. Total Over 27.5': '2.08',
        'Total. 1 map. Total Under 22.5': '4.8',
        'Total. 1 map. Total Under 23.5': '3.68',
        'Total. 1 map. Total Under 24.5': '3.32',
        'Total. 1 map. Total Under 25.5': '2.605',
        'Total. 1 map. Total Under 26.5': '2.075',
        'Total. 1 map. Total Under 27.5': '1.7',
        'url': 'https://1x-bet.com/en/line/Esports/2105034-CSGO-cs-summit-6-North-America/78618439-Team-Liquid-Evil-Geniuses/'
        },
    'team vitality - big': {
        '. ': '',
        '1x2. 1 map. BIG': '1.87',
        '1x2. 1 map. Team Vitality': '1.968',
        '1x2. BIG': '1.965',
        '1x2. Team Vitality': '1.86',
        'First Frag In Round - Team. 1 map. First Frag In 1 Round - BIG': '1.87',
        'First Frag In Round - Team. 1 map. First Frag In 1 Round - Team Vitality': '1.87',
        'First Frag In Round - Team. 1 map. First Frag In 16 Round - BIG': '1.87',
        'First Frag In Round - Team. 1 map. First Frag In 16 Round - Team Vitality': '1.87',
        'Handicap. 1 map. ': '',
        'Handicap. 1 map. Handiсap BIG (+2.5)': '1.61',
        'Handicap. 1 map. Handiсap BIG (+3.5)': '1.445',
        'Handicap. 1 map. Handiсap BIG (+4.5)': '1.31',
        'Handicap. 1 map. Handiсap BIG (+5.5)': '1.24',
        'Handicap. 1 map. Handiсap BIG (+6.5)': '1.18',
        'Handicap. 1 map. Handiсap BIG (-2.5)': '2.17',
        'Handicap. 1 map. Handiсap BIG (-3.5)': '2.536',
        'Handicap. 1 map. Handiсap BIG (-4.5)': '3.1',
        'Handicap. 1 map. Handiсap BIG (-5.5)': '3.68',
        'Handicap. 1 map. Handiсap Team Vitality (+2.5)': '1.69',
        'Handicap. 1 map. Handiсap Team Vitality (+3.5)': '1.525',
        'Handicap. 1 map. Handiсap Team Vitality (+4.5)': '1.38',
        'Handicap. 1 map. Handiсap Team Vitality (+5.5)': '1.29',
        'Handicap. 1 map. Handiсap Team Vitality (-2.5)': '2.36',
        'Handicap. 1 map. Handiсap Team Vitality (-3.5)': '2.825',
        'Handicap. 1 map. Handiсap Team Vitality (-4.5)': '3.5',
        'Handicap. 1 map. Handiсap Team Vitality (-5.5)': '4.2',
        'Handicap. 1 map. Handiсap Team Vitality (-6.5)': '5',
        'Team 1 To Win At Least One Map. Team Team Vitality To Win At Least One Map - No': '3',
        'Team 1 To Win At Least One Map. Team Team Vitality To Win At Least One Map - Yes': '1.315',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Team Vitality Exactly 0': '2.7',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Team Vitality Exactly 1': '3.2',
        'Team 1, Exact Number Of Maps Won. Total Maps Won By Team Team Vitality Exactly 2': '1.95',
        'Team 2 To Win At Least One Map. Team BIG To Win At Least One Map - No': '3.54',
        'Team 2 To Win At Least One Map. Team BIG To Win At Least One Map - Yes': '1.225',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team BIG Exactly 0': '3.2',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team BIG Exactly 1': '3.4',
        'Team 2, Exact Number Of Maps Won. Total Maps Won By Team BIG Exactly 2': '1.75',
        'Total Maps Even/Odd. Total Maps - Even': '1.97',
        'Total Maps Even/Odd. Total Maps - Odd': '1.78',
        'Total Maps Handicap. BIG Handicap -1.5 Maps': '3.32',
        'Total Maps Handicap. BIG Handicap 1.5 Maps': '1.275',
        'Total Maps Handicap. Team Vitality Handicap -1.5 Maps': '3.78',
        'Total Maps Handicap. Team Vitality Handicap 1.5 Maps': '1.304',
        'Total Maps. Total Maps Over 2.5': '1.83',
        'Total Maps. Total Maps Under 2.5': '1.8',
        'Total. 1 map. ': '',
        'Total. 1 map. Total Over 22.5': '1.19',
        'Total. 1 map. Total Over 23.5': '1.28',
        'Total. 1 map. Total Over 24.5': '1.39',
        'Total. 1 map. Total Over 25.5': '1.57',
        'Total. 1 map. Total Over 26.5': '1.81',
        'Total. 1 map. Total Over 27.5': '2.24',
        'Total. 1 map. Total Under 22.5': '4.86',
        'Total. 1 map. Total Under 23.5': '3.76',
        'Total. 1 map. Total Under 24.5': '3.005',
        'Total. 1 map. Total Under 25.5': '2.44',
        'Total. 1 map. Total Under 26.5': '2.02',
        'Total. 1 map. Total Under 27.5': '1.66',
        'url': 'https://1x-bet.com/en/line/Esports/2105037-CSGO-cs-summit-6-Europe/78602854-Team-Vitality-BIG/'
        },
    'third impact - valkyrie': {
        '1x2. 1 map. Third Impact': '1.55',
        '1x2. 1 map. Valkyrie': '2.37',
        '1x2. 2 map. Third Impact': '1.55',
        '1x2. 2 map. Valkyrie': '2.37',
        '1x2. Third Impact': '1.22',
        '1x2. Valkyrie': '2.805',
        'url': 'https://1x-bet.com/en/line/Esports/2097636-CSGO-Winners-League-Main-Division/78634244-Third-Impact-Valkyrie/'
        },
    'tikitakan - brute': {
        '. ': '',
        '1x2. 1 map. Brute': '2.125',
        '1x2. 1 map. Tikitakan': '1.68',
        '1x2. Brute': '2.26',
        '1x2. Tikitakan': '1.616',
        'Ace. 1 map. ': '',
        'Handicap. 1 map. Handiсap Brute (+2.5)': '1.74',
        'Handicap. 1 map. Handiсap Brute (+3.5)': '1.58',
        'Handicap. 1 map. Handiсap Brute (+4.5)': '1.45',
        'Handicap. 1 map. Handiсap Brute (+5.5)': '1.31',
        'Handicap. 1 map. Handiсap Brute (+6.5)': '1.23',
        'Handicap. 1 map. Handiсap Brute (+7.5)': '1.17',
        'Handicap. 1 map. Handiсap Brute (-2.5)': '2.7',
        'Handicap. 1 map. Handiсap Brute (-3.5)': '3',
        'Handicap. 1 map. Handiсap Brute (-4.5)': '3.58',
        'Handicap. 1 map. Handiсap Brute (-5.5)': '4.2',
        'Handicap. 1 map. Handiсap Brute (-6.5)': '4.94',
        'Handicap. 1 map. Handiсap Tikitakan (+2.5)': '1.43',
        'Handicap. 1 map. Handiсap Tikitakan (+3.5)': '1.36',
        'Handicap. 1 map. Handiсap Tikitakan (+4.5)': '1.26',
        'Handicap. 1 map. Handiсap Tikitakan (+5.5)': '1.21',
        'Handicap. 1 map. Handiсap Tikitakan (+6.5)': '1.16',
        'Handicap. 1 map. Handiсap Tikitakan (-2.5)': '2.02',
        'Handicap. 1 map. Handiсap Tikitakan (-3.5)': '2.29',
        'Handicap. 1 map. Handiсap Tikitakan (-4.5)': '2.63',
        'Handicap. 1 map. Handiсap Tikitakan (-5.5)': '3.28',
        'Handicap. 1 map. Handiсap Tikitakan (-6.5)': '3.9',
        'Handicap. 1 map. Handiсap Tikitakan (-7.5)': '4.74',
        'Total 2. 1 map. Individual Total 2 Over 14.5': '1.9',
        'Total 2. 1 map. Individual Total 2 Under 14.5': '1.77',
        'Total Maps Even/Odd. Total Maps - Even': '1.67',
        'Total Maps Even/Odd. Total Maps - Odd': '2.12',
        'Total Maps Handicap. Brute Handicap -1.5 Maps': '3.98',
        'Total Maps Handicap. Brute Handicap 1.5 Maps': '1.46',
        'Total Maps Handicap. Tikitakan Handicap -1.5 Maps': '2.6',
        'Total Maps Handicap. Tikitakan Handicap 1.5 Maps': '1.22',
        'Total Maps. Total Maps Over 2.5': '2.12',
        'Total Maps. Total Maps Under 2.5': '1.67',
        'Total. 1 map. Total Over 22.5': '1.18',
        'Total. 1 map. Total Over 23.5': '1.27',
        'Total. 1 map. Total Over 24.5': '1.4',
        'Total. 1 map. Total Over 25.5': '1.54',
        'Total. 1 map. Total Over 26.5': '1.8',
        'Total. 1 map. Total Over 27.5': '2.21',
        'Total. 1 map. Total Over 28.5': '2.93',
        'Total. 1 map. Total Over 29.5': '4.16',
        'Total. 1 map. Total Over 30.5': '8.5',
        'Total. 1 map. Total Under 22.5': '4.56',
        'Total. 1 map. Total Under 23.5': '3.54',
        'Total. 1 map. Total Under 24.5': '2.81',
        'Total. 1 map. Total Under 25.5': '2.38',
        'Total. 1 map. Total Under 26.5': '1.94',
        'Total. 1 map. Total Under 27.5': '1.62',
        'Total. 1 map. Total Under 28.5': '1.37',
        'Total. 1 map. Total Under 29.5': '1.21',
        'Total. 1 map. Total Under 30.5': '1.07',
        'Who Will Win X Rounds?. 1 map. First To Win 5 Rounds - Brute': '1.99',
        'Who Will Win X Rounds?. 1 map. First To Win 5 Rounds - Tikitakan': '1.76',
        'Will There Be Overtime? - Yes/No. 1 map. Will There Be Overtime? - No': '1.06',
        'Will There Be Overtime? - Yes/No. 1 map. Will There Be Overtime? - Yes': '8.2',
        'Win By. 1 map. ': '',
        'Win In Round. 1 map. Brute Will Win In Round 1': '1.9',
        'Win In Round. 1 map. Brute Will Win In Round 16': '1.9',
        'Win In Round. 1 map. Tikitakan Will Win In Round 1': '1.84',
        'Win In Round. 1 map. Tikitakan Will Win In Round 16': '1.84',
        'url': 'https://1x-bet.com/en/line/Esports/2091676-CSGO-ESEA-Advanced-Season-34-Europe/78668319-Tikitakan-Brute/'
        },
    'twa - chiefs esports club': {
        '1x2. 1 map. Chiefs Esports Club': '1.25',
        '1x2. 1 map. TWA': '3.74',
        '1x2. 2 map. Chiefs Esports Club': '1.25',
        '1x2. 2 map. TWA': '3.74',
        '1x2. Chiefs Esports Club': '1.15',
        '1x2. TWA': '5.2',
        'url': 'https://1x-bet.com/en/line/Esports/2091919-CSGO-ESEA-MDL-Season-34-Australia/78704627-TWA-Chiefs-Esports-Club/'
        },
    'tyloo - mazaalai': {
        '1x2. 1 map. Mazaalai': '4.16',
        '1x2. 1 map. Tyloo': '1.21',
        '1x2. 2 map. Mazaalai': '4.16',
        '1x2. 2 map. Tyloo': '1.21',
        '1x2. Mazaalai': '6.2',
        '1x2. Tyloo': '1.11',
        'Handicap. 1 map. Handiсap Mazaalai (+4.5)': '2.17',
        'Handicap. 1 map. Handiсap Mazaalai (+5.5)': '1.88',
        'Handicap. 1 map. Handiсap Mazaalai (+6.5)': '1.65',
        'Handicap. 1 map. Handiсap Tyloo (-4.5)': '1.64',
        'Handicap. 1 map. Handiсap Tyloo (-5.5)': '1.86',
        'Handicap. 1 map. Handiсap Tyloo (-6.5)': '2.16',
        'Handicap. 2 map. Handiсap Mazaalai (+4.5)': '2.19',
        'Handicap. 2 map. Handiсap Mazaalai (+5.5)': '1.9',
        'Handicap. 2 map. Handiсap Mazaalai (+6.5)': '1.66',
        'Handicap. 2 map. Handiсap Tyloo (-4.5)': '1.63',
        'Handicap. 2 map. Handiсap Tyloo (-5.5)': '1.84',
        'Handicap. 2 map. Handiсap Tyloo (-6.5)': '2.14',
        'Total Maps Even/Odd. Total Maps - Even': '1.35',
        'Total Maps Even/Odd. Total Maps - Odd': '3.04',
        'Total Maps Handicap. Mazaalai Handicap -1.5 Maps': '10',
        'Total Maps Handicap. Mazaalai Handicap 1.5 Maps': '2.63',
        'Total Maps Handicap. Tyloo Handicap -1.5 Maps': '1.45',
        'Total Maps Handicap. Tyloo Handicap 1.5 Maps': '1.03',
        'Total Maps. Total Maps Over 2.5': '3.04',
        'Total Maps. Total Maps Under 2.5': '1.35',
        'Total. 1 map. Total Over 25.5': '1.8',
        'Total. 1 map. Total Over 26.5': '2.16',
        'Total. 1 map. Total Under 25.5': '1.94',
        'Total. 1 map. Total Under 26.5': '1.65',
        'Total. 2 map. Total Over 25.5': '1.82',
        'Total. 2 map. Total Over 26.5': '2.17',
        'Total. 2 map. Total Under 25.5': '1.92',
        'Total. 2 map. Total Under 26.5': '1.64',
        'Win In Round. 1 map. Mazaalai Will Win In Round 1': '2.02',
        'Win In Round. 1 map. Mazaalai Will Win In Round 16': '2.02',
        'Win In Round. 1 map. Tyloo Will Win In Round 1': '1.74',
        'Win In Round. 1 map. Tyloo Will Win In Round 16': '1.74',
        'Win In Round. 2 map. Mazaalai Will Win In Round 1': '2.02',
        'Win In Round. 2 map. Mazaalai Will Win In Round 16': '2.02',
        'Win In Round. 2 map. Tyloo Will Win In Round 1': '1.74',
        'Win In Round. 2 map. Tyloo Will Win In Round 16': '1.74',
        'url': 'https://1x-bet.com/en/line/Esports/2106875-CSGO-Perfect-World-Asia-League-Summer-2020/78632126-Tyloo-Mazaalai/'
        },
    'vici gaming - divine vendetta': {
        '1x2. 1 map. Divine Vendetta': '4.04',
        '1x2. 1 map. Vici Gaming': '1.22',
        '1x2. 2 map. Divine Vendetta': '4.04',
        '1x2. 2 map. Vici Gaming': '1.22',
        '1x2. Divine Vendetta': '5.9',
        '1x2. Vici Gaming': '1.12',
        'Handicap. 1 map. Handiсap Divine Vendetta (+4.5)': '2.14',
        'Handicap. 1 map. Handiсap Divine Vendetta (+5.5)': '1.86',
        'Handicap. 1 map. Handiсap Divine Vendetta (+6.5)': '1.63',
        'Handicap. 1 map. Handiсap Vici Gaming (-4.5)': '1.66',
        'Handicap. 1 map. Handiсap Vici Gaming (-5.5)': '1.88',
        'Handicap. 1 map. Handiсap Vici Gaming (-6.5)': '2.19',
        'Handicap. 2 map. Handiсap Divine Vendetta (+4.5)': '2.16',
        'Handicap. 2 map. Handiсap Divine Vendetta (+5.5)': '1.87',
        'Handicap. 2 map. Handiсap Divine Vendetta (+6.5)': '1.64',
        'Handicap. 2 map. Handiсap Vici Gaming (-4.5)': '1.65',
        'Handicap. 2 map. Handiсap Vici Gaming (-5.5)': '1.87',
        'Handicap. 2 map. Handiсap Vici Gaming (-6.5)': '2.17',
        'Total Maps Even/Odd. Total Maps - Even': '1.36',
        'Total Maps Even/Odd. Total Maps - Odd': '2.99',
        'Total Maps Handicap. Divine Vendetta Handicap -1.5 Maps': '10',
        'Total Maps Handicap. Divine Vendetta Handicap 1.5 Maps': '2.57',
        'Total Maps Handicap. Vici Gaming Handicap -1.5 Maps': '1.47',
        'Total Maps Handicap. Vici Gaming Handicap 1.5 Maps': '1.03',
        'Total Maps. Total Maps Over 2.5': '2.99',
        'Total Maps. Total Maps Under 2.5': '1.36',
        'Total. 1 map. Total Over 25.5': '1.79',
        'Total. 1 map. Total Over 26.5': '2.14',
        'Total. 1 map. Total Under 25.5': '1.96',
        'Total. 1 map. Total Under 26.5': '1.66',
        'Total. 2 map. Total Over 25.5': '1.8',
        'Total. 2 map. Total Over 26.5': '2.16',
        'Total. 2 map. Total Under 25.5': '1.94',
        'Total. 2 map. Total Under 26.5': '1.65',
        'Win In Round. 1 map. Divine Vendetta Will Win In Round 1': '2.02',
        'Win In Round. 1 map. Divine Vendetta Will Win In Round 16': '2.02',
        'Win In Round. 1 map. Vici Gaming Will Win In Round 1': '1.74',
        'Win In Round. 1 map. Vici Gaming Will Win In Round 16': '1.74',
        'Win In Round. 2 map. Divine Vendetta Will Win In Round 1': '2.01',
        'Win In Round. 2 map. Divine Vendetta Will Win In Round 16': '2.02',
        'Win In Round. 2 map. Vici Gaming Will Win In Round 1': '1.75',
        'Win In Round. 2 map. Vici Gaming Will Win In Round 16': '1.74',
        'url': 'https://1x-bet.com/en/line/Esports/2106875-CSGO-Perfect-World-Asia-League-Summer-2020/78632132-Vici-Gaming-Divine-Vendetta/'
        }
    }
