bets = {
    '100 thieves - gen.g': {
        '1-st map: 100 thieves Handicap value. +2.5. Handicap coefficient': '1.47',
        '1-st map: 100 thieves Handicap value. –2.5. Handicap coefficient': '1.87',
        '1-st map: 100 thieves Handicap value. –3.5. Handicap coefficient': '2.15',
        '1-st map: Total. 25.5. Over': '1.52',
        '1-st map: Total. 25.5. Under': '2.42',
        '1-st map: Total. 26.5. Over': '1.80',
        '1-st map: Total. 26.5. Under': '1.95',
        '1-st map: Total. 27.5. Over': '2.20',
        '1-st map: Total. 27.5. Under': '1.62',
        '1-st map: Win of the 1st team': '1.65',
        '1-st map: Win of the 2nd team': '2.15',
        '1-st map: gen.g Handicap value. +2.5. Handicap coefficient': '1.87',
        '1-st map: gen.g Handicap value. +3.5. Handicap coefficient': '1.65',
        '1-st map: gen.g Handicap value. –2.5. Handicap coefficient': '2.55',
        '100 thieves Handicap value. –1.5. Handicap coefficient': '2.70',
        'Total. 2.5. Over': '2.00',
        'Total. 2.5. Under': '1.76',
        'Win of the 1st team': '1.55',
        'Win of the 2nd team': '2.35',
        'gen.g Handicap value. +1.5. Handicap coefficient': '1.43'
        },
    'ago nest - dreameaters': {
        'Win of the 1st team': '1.75',
        'Win of the 2nd team': '2.01'
        },
    'ahq - asking questions': {
        'Win of the 1st team': '1.55',
        'Win of the 2nd team': '2.36'
        },
    'alcoholics anonymous - new england whalers': {
        'Win of the 1st team': '2.80',
        'Win of the 2nd team': '1.40'
        },
    'alternate attax - fate': {
        '1-st map: Total. 25.5. Over': '1.58',
        '1-st map: Total. 25.5. Under': '2.30',
        '1-st map: Total. 26.5. Over': '1.80',
        '1-st map: Total. 26.5. Under': '1.95',
        '1-st map: Total. 27.5. Over': '2.31',
        '1-st map: Total. 27.5. Under': '1.57',
        '1-st map: alternate attax Handicap value. –2.5. Handicap coefficient': '1.70',
        '1-st map: alternate attax Handicap value. –3.5. Handicap coefficient': '1.92',
        '1-st map: alternate attax Handicap value. –4.5. Handicap coefficient': '2.25',
        '1-st map: fate Handicap value. +2.5. Handicap coefficient': '2.08',
        '1-st map: fate Handicap value. +3.5. Handicap coefficient': '1.82',
        '1-st map: fate Handicap value. +4.5. Handicap coefficient': '1.60',
        'Win of the 1st team': '1.50',
        'Win of the 2nd team': '2.48'
        },
    'apeks - ambush': {
        '1-st map: Total. 26.5. Over': '1.85',
        '1-st map: Total. 26.5. Under': '1.90',
        '1-st map: Win of the 1st team': '1.55',
        '1-st map: Win of the 2nd team': '2.35',
        '1-st map: ambush Handicap value. +2.5. Handicap coefficient': '2.01',
        '1-st map: apeks Handicap value. –2.5. Handicap coefficient': '1.75',
        'Total. 2.5. Over': '2.01',
        'Total. 2.5. Under': '1.75',
        'Win of the 1st team': '1.45',
        'Win of the 2nd team': '2.62',
        'ambush Handicap value. +1.5. Handicap coefficient': '1.52',
        'apeks Handicap value. –1.5. Handicap coefficient': '2.42'
        },
    'apeks - nemiga': {
        '1-st map: Total. 25.5. Over': '1.75',
        '1-st map: Total. 25.5. Under': '2.01',
        '1-st map: Total. 26.5. Over': '2.00',
        '1-st map: Total. 26.5. Under': '1.76',
        '1-st map: Total. 27.5. Over': '2.55',
        '1-st map: Total. 27.5. Under': '1.47',
        '1-st map: Win of the 1st team': '3.30',
        '1-st map: Win of the 2nd team': '1.30',
        '1-st map: apeks Handicap value. +3.5. Handicap coefficient': '2.11',
        '1-st map: apeks Handicap value. +4.5. Handicap coefficient': '1.85',
        '1-st map: apeks Handicap value. +5.5. Handicap coefficient': '1.62',
        '1-st map: nemiga Handicap value. –3.5. Handicap coefficient': '1.68',
        '1-st map: nemiga Handicap value. –4.5. Handicap coefficient': '1.90',
        '1-st map: nemiga Handicap value. –5.5. Handicap coefficient': '2.20',
        'Total. 2.5. Over': '2.42',
        'Total. 2.5. Under': '1.52',
        'Win of the 1st team': '4.20',
        'Win of the 2nd team': '1.20',
        'apeks Handicap value. +1.5. Handicap coefficient': '2.08',
        'nemiga Handicap value. –1.5. Handicap coefficient': '1.70'
        },
    'atk - good gaming': {
        'Win of the 1st team': '1.25',
        'Win of the 2nd team': '3.71'
        },
    'avant - paradox': {
        '1-st map: Total. 25.5. Over': '1.70',
        '1-st map: Total. 25.5. Under': '2.08',
        '1-st map: Total. 26.5. Over': '1.95',
        '1-st map: Total. 26.5. Under': '1.80',
        '1-st map: Total. 27.5. Over': '2.48',
        '1-st map: Total. 27.5. Under': '1.50',
        '1-st map: Win of the 1st team': '1.35',
        '1-st map: Win of the 2nd team': '3.05',
        '1-st map: avant Handicap value. –3.5. Handicap coefficient': '1.72',
        '1-st map: avant Handicap value. –4.5. Handicap coefficient': '1.97',
        '1-st map: avant Handicap value. –5.5. Handicap coefficient': '2.25',
        '1-st map: paradox Handicap value. +3.5. Handicap coefficient': '2.05',
        '1-st map: paradox Handicap value. +4.5. Handicap coefficient': '1.77',
        '1-st map: paradox Handicap value. +5.5. Handicap coefficient': '1.60',
        'Total. 2.5. Over': '2.35',
        'Total. 2.5. Under': '1.55',
        'Win of the 1st team': '1.25',
        'Win of the 2nd team': '3.75',
        'avant Handicap value. –1.5. Handicap coefficient': '1.82',
        'paradox Handicap value. +1.5. Handicap coefficient': '1.92'
        },
    'avesta - cplay': {'Away win': '2.50', 'Draw': '2.14', 'Home win': '4.00'},
    'big academy - baecon gg': {
        'Win of the 1st team': '1.65',
        'Win of the 2nd team': '2.16'
        },
    'big academy - gameagents': {
        'Win of the 1st team': '1.55',
        'Win of the 2nd team': '2.36'
        },
    'big chillin - third impact': {
        'Win of the 1st team': '1.50',
        'Win of the 2nd team': '2.48'
        },
    'bmth - royalty': {
        '1-st map: Away win': '1.55',
        '1-st map: Home win': '2.35',
        '1-st map: Total. 25.5. Over': '1.57',
        '1-st map: Total. 25.5. Under': '2.31',
        '1-st map: Total. 26.5. Over': '1.87',
        '1-st map: Total. 26.5. Under': '1.87',
        '1-st map: Total. 27.5. Over': '2.35',
        '1-st map: Total. 27.5. Under': '1.55',
        '1-st map: bmth Handicap value. +2.5. Handicap coefficient': '2.01',
        '1-st map: bmth Handicap value. +3.5. Handicap coefficient': '1.76',
        '1-st map: bmth Handicap value. +4.5. Handicap coefficient': '1.55',
        '1-st map: royalty Handicap value. –2.5. Handicap coefficient': '1.75',
        '1-st map: royalty Handicap value. –3.5. Handicap coefficient': '2.00',
        '1-st map: royalty Handicap value. –4.5. Handicap coefficient': '2.35',
        'Away win': '2.35',
        'Draw': '2.00',
        'Home win': '5.21',
        'bmth Handicap value. +0.5. Handicap coefficient': '1.55',
        'royalty Handicap value. –0.5. Handicap coefficient': '2.35'
        },
    'bravos - sws': {'Win of the 1st team': '1.35', 'Win of the 2nd team': '3.04'},
    'cr4zy - nemiga': {
        '1-st map: Total. 25.5. Over': '1.80',
        '1-st map: Total. 25.5. Under': '1.95',
        '1-st map: Total. 26.5. Over': '2.08',
        '1-st map: Total. 26.5. Under': '1.70',
        '1-st map: Total. 27.5. Over': '2.65',
        '1-st map: Total. 27.5. Under': '1.44',
        '1-st map: Win of the 1st team': '3.75',
        '1-st map: Win of the 2nd team': '1.25',
        '1-st map: cr4zy Handicap value. +3.5. Handicap coefficient': '2.35',
        '1-st map: cr4zy Handicap value. +4.5. Handicap coefficient': '2.01',
        '1-st map: cr4zy Handicap value. +5.5. Handicap coefficient': '1.76',
        '1-st map: nemiga Handicap value. –3.5. Handicap coefficient': '1.55',
        '1-st map: nemiga Handicap value. –4.5. Handicap coefficient': '1.75',
        '1-st map: nemiga Handicap value. –5.5. Handicap coefficient': '2.00',
        'Total. 2.5. Over': '2.55',
        'Total. 2.5. Under': '1.47',
        'Win of the 1st team': '5.00',
        'Win of the 2nd team': '1.15',
        'cr4zy Handicap value. +1.5. Handicap coefficient': '2.35',
        'nemiga Handicap value. –1.5. Handicap coefficient': '1.55'
        },
    'cream real betis latam - neverest': {
        'Win of the 1st team': '1.50',
        'Win of the 2nd team': '2.48'
        },
    'd13 - divine vendetta': {
        '1-st map: Total. 26.5. Over': '1.82',
        '1-st map: Total. 26.5. Under': '1.92',
        '1-st map: Win of the 1st team': '1.60',
        '1-st map: Win of the 2nd team': '2.25',
        '1-st map: d13 Handicap value. –2.5. Handicap coefficient': '1.80',
        '1-st map: divine vendetta Handicap value. +2.5. Handicap coefficient': '1.95',
        'Total. 2.5. Over': '2.01',
        'Total. 2.5. Under': '1.75',
        'Win of the 1st team': '1.50',
        'Win of the 2nd team': '2.48',
        'd13 Handicap value. –1.5. Handicap coefficient': '2.62',
        'divine vendetta Handicap value. +1.5. Handicap coefficient': '1.45'
        },
    'die katte - white rabbit': {
        'Win of the 1st team': '1.35',
        'Win of the 2nd team': '3.04'
        },
    'divizon - planetkey dynamics': {
        'Away win': '4.00',
        'Draw': '1.87',
        'Home win': '3.00'
        },
    'espada - pact': {
        '1-st map: Total. 25.5. Over': '1.50',
        '1-st map: Total. 25.5. Under': '2.48',
        '1-st map: Total. 26.5. Over': '1.77',
        '1-st map: Total. 26.5. Under': '1.97',
        '1-st map: Total. 27.5. Over': '2.15',
        '1-st map: Total. 27.5. Under': '1.65',
        '1-st map: Win of the 1st team': '1.70',
        '1-st map: Win of the 2nd team': '2.08',
        '1-st map: espada Handicap value. +2.5. Handicap coefficient': '1.50',
        '1-st map: espada Handicap value. –2.5. Handicap coefficient': '1.90',
        '1-st map: espada Handicap value. –3.5. Handicap coefficient': '2.20',
        '1-st map: pact Handicap value. +2.5. Handicap coefficient': '1.85',
        '1-st map: pact Handicap value. +3.5. Handicap coefficient': '1.62',
        '1-st map: pact Handicap value. –2.5. Handicap coefficient': '2.48',
        'Total. 2.5. Over': '2.08',
        'Total. 2.5. Under': '1.70',
        'Win of the 1st team': '1.60',
        'Win of the 2nd team': '2.25',
        'espada Handicap value. –1.5. Handicap coefficient': '2.74',
        'pact Handicap value. +1.5. Handicap coefficient': '1.42'
        },
    'furia - cloud9': {
        '1-st map: Total. 25.5. Over': '1.62',
        '1-st map: Total. 25.5. Under': '2.20',
        '1-st map: Total. 26.5. Over': '1.90',
        '1-st map: Total. 26.5. Under': '1.85',
        '1-st map: Total. 27.5. Over': '2.42',
        '1-st map: Total. 27.5. Under': '1.52',
        '1-st map: Win of the 1st team': '1.45',
        '1-st map: Win of the 2nd team': '2.62',
        '1-st map: cloud9 Handicap value. +2.5. Handicap coefficient': '2.15',
        '1-st map: cloud9 Handicap value. +3.5. Handicap coefficient': '1.87',
        '1-st map: cloud9 Handicap value. +4.5. Handicap coefficient': '1.62',
        '1-st map: furia Handicap value. –2.5. Handicap coefficient': '1.65',
        '1-st map: furia Handicap value. –3.5. Handicap coefficient': '1.87',
        '1-st map: furia Handicap value. –4.5. Handicap coefficient': '2.20',
        'Total. 2.5. Over': '2.20',
        'Total. 2.5. Under': '1.62',
        'Win of the 1st team': '1.35',
        'Win of the 2nd team': '3.05',
        'cloud9 Handicap value. +1.5. Handicap coefficient': '1.68',
        'furia Handicap value. –1.5. Handicap coefficient': '2.11'
        },
    'gameagents - baecon gg': {
        'Win of the 1st team': '1.60',
        'Win of the 2nd team': '2.25'
        },
    'godsent - og': {
        '1-st map: Total. 25.5. Over': '1.47',
        '1-st map: Total. 25.5. Under': '2.55',
        '1-st map: Total. 26.5. Over': '1.75',
        '1-st map: Total. 26.5. Under': '2.01',
        '1-st map: Total. 27.5. Over': '2.15',
        '1-st map: Total. 27.5. Under': '1.65',
        '1-st map: Win of the 1st team': '1.82',
        '1-st map: Win of the 2nd team': '1.92',
        '1-st map: godsent Handicap value. +2.5. Handicap coefficient': '1.60',
        '1-st map: godsent Handicap value. –2.5. Handicap coefficient': '2.05',
        '1-st map: godsent Handicap value. –3.5. Handicap coefficient': '2.35',
        '1-st map: og Handicap value. +2.5. Handicap coefficient': '1.72',
        '1-st map: og Handicap value. +3.5. Handicap coefficient': '1.55',
        '1-st map: og Handicap value. –2.5. Handicap coefficient': '2.25',
        'Total. 2.5. Over': '1.87',
        'Total. 2.5. Under': '1.87',
        'Win of the 1st team': '1.75',
        'Win of the 2nd team': '2.01',
        'godsent Handicap value. –1.5. Handicap coefficient': '3.30',
        'og Handicap value. +1.5. Handicap coefficient': '1.30'
        },
    'grazur - lethal divide': {
        'Win of the 1st team': '2.48',
        'Win of the 2nd team': '1.50'
        },
    'ground zero - rooster': {
        '1-st map: Total. 25.5. Over': '1.55',
        '1-st map: Total. 25.5. Under': '2.35',
        '1-st map: Total. 26.5. Over': '1.82',
        '1-st map: Total. 26.5. Under': '1.92',
        '1-st map: Total. 27.5. Over': '2.20',
        '1-st map: Total. 27.5. Under': '1.62',
        '1-st map: Win of the 1st team': '2.25',
        '1-st map: Win of the 2nd team': '1.60',
        '1-st map: ground zero Handicap value. +2.5. Handicap coefficient': '1.95',
        '1-st map: ground zero Handicap value. +3.5. Handicap coefficient': '1.68',
        '1-st map: ground zero Handicap value. +4.5. Handicap coefficient': '1.50',
        '1-st map: rooster Handicap value. –2.5. Handicap coefficient': '1.80',
        '1-st map: rooster Handicap value. –3.5. Handicap coefficient': '2.11',
        '1-st map: rooster Handicap value. –4.5. Handicap coefficient': '2.48',
        'Total. 2.5. Over': '2.01',
        'Total. 2.5. Under': '1.75',
        'Win of the 1st team': '2.48',
        'Win of the 2nd team': '1.50',
        'ground zero Handicap value. +1.5. Handicap coefficient': '1.45',
        'rooster Handicap value. –1.5. Handicap coefficient': '2.62'
        },
    'hard legion - sprout': {
        '1-st map: Total. 25.5. Over': '1.52',
        '1-st map: Total. 25.5. Under': '2.42',
        '1-st map: Total. 26.5. Over': '1.80',
        '1-st map: Total. 26.5. Under': '1.95',
        '1-st map: Total. 27.5. Over': '2.20',
        '1-st map: Total. 27.5. Under': '1.62',
        '1-st map: Win of the 1st team': '2.15',
        '1-st map: Win of the 2nd team': '1.65',
        '1-st map: hard legion Handicap value. +2.5. Handicap coefficient': '1.87',
        '1-st map: hard legion Handicap value. +3.5. Handicap coefficient': '1.65',
        '1-st map: hard legion Handicap value. –2.5. Handicap coefficient': '2.55',
        '1-st map: sprout Handicap value. +2.5. Handicap coefficient': '1.47',
        '1-st map: sprout Handicap value. –2.5. Handicap coefficient': '1.87',
        '1-st map: sprout Handicap value. –3.5. Handicap coefficient': '2.15',
        'Total. 2.5. Over': '2.00',
        'Total. 2.5. Under': '1.76',
        'Win of the 1st team': '2.35',
        'Win of the 2nd team': '1.55',
        'hard legion Handicap value. +1.5. Handicap coefficient': '1.43',
        'sprout Handicap value. –1.5. Handicap coefficient': '2.70'
        },
    'hyper - rbg': {'Win of the 1st team': '2.15', 'Win of the 2nd team': '1.65'},
    'imperium - eternal': {
        'Win of the 1st team': '1.95',
        'Win of the 2nd team': '1.80'
        },
    'kolossus - seven-gg': {
        'Away win': '2.30',
        'Draw': '2.31',
        'Home win': '4.00'
        },
    'kova - veto': {'Win of the 1st team': '1.30', 'Win of the 2nd team': '3.33'},
    'levelup - the dice': {
        '1-st map: Total. 26.5. Over': '1.77',
        '1-st map: Total. 26.5. Under': '1.97',
        '1-st map: Win of the 1st team': '1.70',
        '1-st map: Win of the 2nd team': '2.08',
        '1-st map: levelup Handicap value. –2.5. Handicap coefficient': '1.90',
        '1-st map: the dice Handicap value. +2.5. Handicap coefficient': '1.85',
        'Total. 2.5. Over': '2.00',
        'Total. 2.5. Under': '1.76',
        'Win of the 1st team': '1.60',
        'Win of the 2nd team': '2.25',
        'levelup Handicap value. –1.5. Handicap coefficient': '2.90',
        'the dice Handicap value. +1.5. Handicap coefficient': '1.38'
        },
    'lilmix - cr4zy': {
        '1-st map: Total. 25.5. Over': '1.58',
        '1-st map: Total. 25.5. Under': '2.30',
        '1-st map: Total. 26.5. Over': '1.87',
        '1-st map: Total. 26.5. Under': '1.87',
        '1-st map: Total. 27.5. Over': '2.31',
        '1-st map: Total. 27.5. Under': '1.57',
        '1-st map: Win of the 1st team': '2.48',
        '1-st map: Win of the 2nd team': '1.50',
        '1-st map: cr4zy Handicap value. –2.5. Handicap coefficient': '1.70',
        '1-st map: cr4zy Handicap value. –3.5. Handicap coefficient': '1.92',
        '1-st map: cr4zy Handicap value. –4.5. Handicap coefficient': '2.25',
        '1-st map: lilmix Handicap value. +2.5. Handicap coefficient': '2.08',
        '1-st map: lilmix Handicap value. +3.5. Handicap coefficient': '1.82',
        '1-st map: lilmix Handicap value. +4.5. Handicap coefficient': '1.60',
        'Total. 2.5. Over': '2.08',
        'Total. 2.5. Under': '1.70',
        'Win of the 1st team': '2.80',
        'Win of the 2nd team': '1.40',
        'cr4zy Handicap value. –1.5. Handicap coefficient': '2.25',
        'lilmix Handicap value. +1.5. Handicap coefficient': '1.60'
        },
    'liquid - evil geniuses': {
        '1-st map: Total. 25.5. Over': '1.45',
        '1-st map: Total. 25.5. Under': '2.62',
        '1-st map: Total. 26.5. Over': '1.72',
        '1-st map: Total. 26.5. Under': '2.05',
        '1-st map: Total. 27.5. Over': '2.11',
        '1-st map: Total. 27.5. Under': '1.68',
        '1-st map: Win of the 1st team': '1.87',
        '1-st map: Win of the 2nd team': '1.87',
        '1-st map: evil geniuses Handicap value. +2.5. Handicap coefficient': '1.68',
        '1-st map: evil geniuses Handicap value. +3.5. Handicap coefficient': '1.50',
        '1-st map: evil geniuses Handicap value. –2.5. Handicap coefficient': '2.11',
        '1-st map: liquid Handicap value. +2.5. Handicap coefficient': '1.68',
        '1-st map: liquid Handicap value. –2.5. Handicap coefficient': '2.11',
        '1-st map: liquid Handicap value. –3.5. Handicap coefficient': '2.48',
        'Total. 2.5. Over': '2.01',
        'Total. 2.5. Under': '1.75',
        'Win of the 1st team': '1.87',
        'Win of the 2nd team': '1.87',
        'evil geniuses Handicap value. +1.5. Handicap coefficient': '1.27',
        'liquid Handicap value. –1.5. Handicap coefficient': '3.55'
        },
    'lucid dream - invictus gaming': {
        '1-st map: Total. 26.5. Over': '1.92',
        '1-st map: Total. 26.5. Under': '1.82',
        '1-st map: Win of the 1st team': '2.80',
        '1-st map: Win of the 2nd team': '1.40',
        '1-st map: invictus gaming Handicap value. –3.5. Handicap coefficient': '1.80',
        '1-st map: lucid dream Handicap value. +3.5. Handicap coefficient': '1.95',
        'Total. 2.5. Over': '2.25',
        'Total. 2.5. Under': '1.60',
        'Win of the 1st team': '3.30',
        'Win of the 2nd team': '1.30',
        'invictus gaming Handicap value. –1.5. Handicap coefficient': '1.97',
        'lucid dream Handicap value. +1.5. Handicap coefficient': '1.77'
        },
    'mazaalai - invictus gaming': {
        '1-st map: Total. 26.5. Over': '2.00',
        '1-st map: Total. 26.5. Under': '1.76',
        '1-st map: Win of the 1st team': '3.30',
        '1-st map: Win of the 2nd team': '1.30',
        '1-st map: invictus gaming Handicap value. –4.5. Handicap coefficient': '1.90',
        '1-st map: mazaalai Handicap value. +4.5. Handicap coefficient': '1.85',
        'Total. 2.5. Over': '2.42',
        'Total. 2.5. Under': '1.52',
        'Win of the 1st team': '4.20',
        'Win of the 2nd team': '1.20',
        'invictus gaming Handicap value. –1.5. Handicap coefficient': '1.70',
        'mazaalai Handicap value. +1.5. Handicap coefficient': '2.08'
        },
    'nemiga - apeks': {
        '1-st map: Total. 25.5. Over': '1.75',
        '1-st map: Total. 25.5. Under': '2.01',
        '1-st map: Total. 26.5. Over': '2.00',
        '1-st map: Total. 26.5. Under': '1.76',
        '1-st map: Total. 27.5. Over': '2.55',
        '1-st map: Total. 27.5. Under': '1.47',
        '1-st map: apeks Handicap value. +3.5. Handicap coefficient': '2.20',
        '1-st map: apeks Handicap value. +4.5. Handicap coefficient': '1.90',
        '1-st map: apeks Handicap value. +5.5. Handicap coefficient': '1.68',
        '1-st map: nemiga Handicap value. –3.5. Handicap coefficient': '1.62',
        '1-st map: nemiga Handicap value. –4.5. Handicap coefficient': '1.85',
        '1-st map: nemiga Handicap value. –5.5. Handicap coefficient': '2.11',
        'Win of the 1st team': '1.30',
        'Win of the 2nd team': '3.30'
        },
    'new england whalers - recon 5': {
        '1-st map: Total. 25.5. Over': '1.52',
        '1-st map: Total. 25.5. Under': '2.42',
        '1-st map: Total. 26.5. Over': '1.80',
        '1-st map: Total. 26.5. Under': '1.95',
        '1-st map: Total. 27.5. Over': '2.20',
        '1-st map: Total. 27.5. Under': '1.62',
        '1-st map: Win of the 1st team': '1.65',
        '1-st map: Win of the 2nd team': '2.15',
        '1-st map: new england whalers Handicap value. +2.5. Handicap coefficient': '1.47',
        '1-st map: new england whalers Handicap value. –2.5. Handicap coefficient': '1.87',
        '1-st map: new england whalers Handicap value. –3.5. Handicap coefficient': '2.15',
        '1-st map: recon 5 Handicap value. +2.5. Handicap coefficient': '1.87',
        '1-st map: recon 5 Handicap value. +3.5. Handicap coefficient': '1.65',
        '1-st map: recon 5 Handicap value. –2.5. Handicap coefficient': '2.55',
        'Total. 2.5. Over': '2.00',
        'Total. 2.5. Under': '1.76',
        'Win of the 1st team': '1.55',
        'Win of the 2nd team': '2.35',
        'new england whalers Handicap value. –1.5. Handicap coefficient': '2.70',
        'recon 5 Handicap value. +1.5. Handicap coefficient': '1.43'
        },
    'nexus - saw': {
        '1-st map: Total. 26.5. Over': '1.90',
        '1-st map: Total. 26.5. Under': '1.85',
        '1-st map: Win of the 1st team': '2.62',
        '1-st map: Win of the 2nd team': '1.45',
        '1-st map: nexus Handicap value. +3.5. Handicap coefficient': '1.87',
        '1-st map: saw Handicap value. –3.5. Handicap coefficient': '1.87',
        'Total. 2.5. Over': '2.20',
        'Total. 2.5. Under': '1.62',
        'Win of the 1st team': '3.05',
        'Win of the 2nd team': '1.35',
        'nexus Handicap value. +1.5. Handicap coefficient': '1.65',
        'saw Handicap value. –1.5. Handicap coefficient': '2.16'
        },
    'nordavind - ago': {
        '1-st map: Total. 25.5. Over': '1.50',
        '1-st map: Total. 25.5. Under': '2.48',
        '1-st map: Total. 26.5. Over': '1.72',
        '1-st map: Total. 26.5. Under': '2.05',
        '1-st map: Total. 27.5. Over': '2.15',
        '1-st map: Total. 27.5. Under': '1.65',
        '1-st map: ago Handicap value. +2.5. Handicap coefficient': '1.85',
        '1-st map: ago Handicap value. +3.5. Handicap coefficient': '1.62',
        '1-st map: ago Handicap value. –2.5. Handicap coefficient': '2.48',
        '1-st map: nordavind Handicap value. +2.5. Handicap coefficient': '1.50',
        '1-st map: nordavind Handicap value. –2.5. Handicap coefficient': '1.90',
        '1-st map: nordavind Handicap value. –3.5. Handicap coefficient': '2.20',
        'Win of the 1st team': '1.70',
        'Win of the 2nd team': '2.08'
        },
    'north - ninjas in pyjamas': {
        '1-st map: Total. 25.5. Over': '1.65',
        '1-st map: Total. 25.5. Under': '2.15',
        '1-st map: Total. 26.5. Over': '1.92',
        '1-st map: Total. 26.5. Under': '1.82',
        '1-st map: Total. 27.5. Over': '2.48',
        '1-st map: Total. 27.5. Under': '1.50',
        '1-st map: Win of the 1st team': '2.80',
        '1-st map: Win of the 2nd team': '1.40',
        '1-st map: ninjas in pyjamas Handicap value. –2.5. Handicap coefficient': '1.60',
        '1-st map: ninjas in pyjamas Handicap value. –3.5. Handicap coefficient': '1.80',
        '1-st map: ninjas in pyjamas Handicap value. –4.5. Handicap coefficient': '2.08',
        '1-st map: north Handicap value. +2.5. Handicap coefficient': '2.25',
        '1-st map: north Handicap value. +3.5. Handicap coefficient': '1.95',
        '1-st map: north Handicap value. +4.5. Handicap coefficient': '1.70',
        'Total. 2.5. Over': '2.25',
        'Total. 2.5. Under': '1.60',
        'Win of the 1st team': '3.30',
        'Win of the 2nd team': '1.30',
        'ninjas in pyjamas Handicap value. –1.5. Handicap coefficient': '1.97',
        'north Handicap value. +1.5. Handicap coefficient': '1.77'
        },
    'oceanus - ex-polar ace': {
        'Win of the 1st team': '1.30',
        'Win of the 2nd team': '3.33'
        },
    'royalty - spassion': {
        '1-st map: Away win': '2.25',
        '1-st map: Home win': '1.60',
        '1-st map: Total. 25.5. Over': '1.57',
        '1-st map: Total. 25.5. Under': '2.31',
        '1-st map: Total. 26.5. Over': '1.87',
        '1-st map: Total. 26.5. Under': '1.87',
        '1-st map: Total. 27.5. Over': '2.37',
        '1-st map: Total. 27.5. Under': '1.54',
        '1-st map: royalty Handicap value. –2.5. Handicap coefficient': '1.80',
        '1-st map: royalty Handicap value. –3.5. Handicap coefficient': '2.11',
        '1-st map: royalty Handicap value. –4.5. Handicap coefficient': '2.48',
        '1-st map: spassion Handicap value. +2.5. Handicap coefficient': '1.95',
        '1-st map: spassion Handicap value. +3.5. Handicap coefficient': '1.68',
        '1-st map: spassion Handicap value. +4.5. Handicap coefficient': '1.50',
        'Away win': '4.89',
        'Draw': '1.95',
        'Home win': '2.50',
        'royalty Handicap value. –0.5. Handicap coefficient': '2.50',
        'spassion Handicap value. +0.5. Handicap coefficient': '1.49'
        },
    'royalty - unknown gods': {
        '1-st map: Away win': '2.25',
        '1-st map: Home win': '1.60',
        '1-st map: Total. 25.5. Over': '1.57',
        '1-st map: Total. 25.5. Under': '2.31',
        '1-st map: Total. 26.5. Over': '1.87',
        '1-st map: Total. 26.5. Under': '1.87',
        '1-st map: Total. 27.5. Over': '2.35',
        '1-st map: Total. 27.5. Under': '1.55',
        '1-st map: royalty Handicap value. –2.5. Handicap coefficient': '1.80',
        '1-st map: royalty Handicap value. –3.5. Handicap coefficient': '2.11',
        '1-st map: royalty Handicap value. –4.5. Handicap coefficient': '2.48',
        '1-st map: unknown gods Handicap value. +2.5. Handicap coefficient': '1.95',
        '1-st map: unknown gods Handicap value. +3.5. Handicap coefficient': '1.68',
        '1-st map: unknown gods Handicap value. +4.5. Handicap coefficient': '1.50',
        'Away win': '4.89',
        'Draw': '1.95',
        'Home win': '2.50',
        'royalty Handicap value. –0.5. Handicap coefficient': '2.50',
        'unknown gods Handicap value. +0.5. Handicap coefficient': '1.49'
        },
    'sangal - tricked': {
        '1-st map: Total. 26.5. Over': '1.87',
        '1-st map: Total. 26.5. Under': '1.87',
        '1-st map: Win of the 1st team': '2.43',
        '1-st map: Win of the 2nd team': '1.52',
        '1-st map: sangal Handicap value. +3.5. Handicap coefficient': '1.82',
        '1-st map: tricked Handicap value. –3.5. Handicap coefficient': '1.92',
        'Total. 2.5. Over': '2.08',
        'Total. 2.5. Under': '1.70',
        'Win of the 1st team': '2.74',
        'Win of the 2nd team': '1.42',
        'sangal Handicap value. +1.5. Handicap coefficient': '1.57',
        'tricked Handicap value. –1.5. Handicap coefficient': '2.31'
        },
    'secret - ldlc': {
        '1-st map: Total. 26.5. Over': '1.80',
        '1-st map: Total. 26.5. Under': '1.95',
        '1-st map: Win of the 1st team': '1.65',
        '1-st map: Win of the 2nd team': '2.15',
        '1-st map: ldlc Handicap value. +2.5. Handicap coefficient': '1.87',
        '1-st map: secret Handicap value. –2.5. Handicap coefficient': '1.87',
        'Total. 2.5. Over': '2.00',
        'Total. 2.5. Under': '1.76',
        'Win of the 1st team': '1.55',
        'Win of the 2nd team': '2.35',
        'ldlc Handicap value. +1.5. Handicap coefficient': '1.43',
        'secret Handicap value. –1.5. Handicap coefficient': '2.70'
        },
    'sinister5 - energy': {
        'Win of the 1st team': '1.80',
        'Win of the 2nd team': '1.95'
        },
    'sj - hreds': {'Win of the 1st team': '1.35', 'Win of the 2nd team': '3.04'},
    'spassion - bmth': {
        '1-st map: Away win': '1.95',
        '1-st map: Home win': '1.80',
        '1-st map: Total. 25.5. Over': '1.57',
        '1-st map: Total. 25.5. Under': '2.31',
        '1-st map: Total. 26.5. Over': '1.87',
        '1-st map: Total. 26.5. Under': '1.87',
        '1-st map: Total. 27.5. Over': '2.35',
        '1-st map: Total. 27.5. Under': '1.55',
        '1-st map: bmth Handicap value. +2.5. Handicap coefficient': '1.73',
        '1-st map: bmth Handicap value. +3.5. Handicap coefficient': '1.55',
        '1-st map: bmth Handicap value. –2.5. Handicap coefficient': '2.30',
        '1-st map: spassion Handicap value. +2.5. Handicap coefficient': '1.58',
        '1-st map: spassion Handicap value. –2.5. Handicap coefficient': '2.03',
        '1-st map: spassion Handicap value. –3.5. Handicap coefficient': '2.35',
        'Away win': '3.53',
        'Draw': '1.90',
        'Home win': '3.25',
        'bmth Handicap value. +0.5. Handicap coefficient': '1.31',
        'spassion Handicap value. –0.5. Handicap coefficient': '3.25'
        },
    'spassion - unknown gods': {
        '1-st map: Away win': '1.87',
        '1-st map: Home win': '1.87',
        '1-st map: Total. 25.5. Over': '1.57',
        '1-st map: Total. 25.5. Under': '2.31',
        '1-st map: Total. 26.5. Over': '1.87',
        '1-st map: Total. 26.5. Under': '1.87',
        '1-st map: Total. 27.5. Over': '2.35',
        '1-st map: Total. 27.5. Under': '1.55',
        '1-st map: spassion Handicap value. +2.5. Handicap coefficient': '1.68',
        '1-st map: spassion Handicap value. –2.5. Handicap coefficient': '2.11',
        '1-st map: spassion Handicap value. –3.5. Handicap coefficient': '2.48',
        '1-st map: unknown gods Handicap value. +2.5. Handicap coefficient': '1.68',
        '1-st map: unknown gods Handicap value. +3.5. Handicap coefficient': '1.50',
        '1-st map: unknown gods Handicap value. –2.5. Handicap coefficient': '2.11',
        'Away win': '3.43',
        'Draw': '1.87',
        'Home win': '3.44',
        'spassion Handicap value. +0.5. Handicap coefficient': '1.28',
        'unknown gods Handicap value. –0.5. Handicap coefficient': '3.44'
        },
    'supernova - lethal divide': {
        'Win of the 1st team': '2.08',
        'Win of the 2nd team': '1.70'
        },
    'syman - hellraisers': {
        '1-st map: Total. 25.5. Over': '1.45',
        '1-st map: Total. 25.5. Under': '2.62',
        '1-st map: Total. 26.5. Over': '1.72',
        '1-st map: Total. 26.5. Under': '2.05',
        '1-st map: Total. 27.5. Over': '2.11',
        '1-st map: Total. 27.5. Under': '1.68',
        '1-st map: hellraisers Handicap value. +2.5. Handicap coefficient': '1.68',
        '1-st map: hellraisers Handicap value. +3.5. Handicap coefficient': '1.50',
        '1-st map: hellraisers Handicap value. –2.5. Handicap coefficient': '2.11',
        '1-st map: syman Handicap value. +2.5. Handicap coefficient': '1.68',
        '1-st map: syman Handicap value. –2.5. Handicap coefficient': '2.11',
        '1-st map: syman Handicap value. –3.5. Handicap coefficient': '2.48',
        'Win of the 1st team': '1.87',
        'Win of the 2nd team': '1.87'
        },
    'third impact - valkyrie': {
        'Win of the 1st team': '1.30',
        'Win of the 2nd team': '3.33'
        },
    'tiger - lucid dream': {
        '1-st map: Total. 26.5. Over': '1.90',
        '1-st map: Total. 26.5. Under': '1.85',
        '1-st map: Win of the 1st team': '1.45',
        '1-st map: Win of the 2nd team': '2.62',
        '1-st map: lucid dream Handicap value. +3.5. Handicap coefficient': '1.87',
        '1-st map: tiger Handicap value. –3.5. Handicap coefficient': '1.87',
        'Total. 2.5. Over': '2.20',
        'Total. 2.5. Under': '1.62',
        'Win of the 1st team': '1.35',
        'Win of the 2nd team': '3.05',
        'lucid dream Handicap value. +1.5. Handicap coefficient': '1.68',
        'tiger Handicap value. –1.5. Handicap coefficient': '2.11'
        },
    'tikitakan - brute': {
        '1-st map: Total. 26.5. Over': '1.77',
        '1-st map: Total. 26.5. Under': '1.97',
        '1-st map: Win of the 1st team': '1.77',
        '1-st map: Win of the 2nd team': '1.97',
        '1-st map: brute Handicap value. +2.5. Handicap coefficient': '1.75',
        '1-st map: tikitakan Handicap value. –2.5. Handicap coefficient': '2.01',
        'Total. 2.5. Over': '1.92',
        'Total. 2.5. Under': '1.82',
        'Win of the 1st team': '1.70',
        'Win of the 2nd team': '2.08',
        'brute Handicap value. +1.5. Handicap coefficient': '1.33',
        'tikitakan Handicap value. –1.5. Handicap coefficient': '3.15'
        },
    'twa - chiefs': {
        '1-st map: Total. 25.5. Over': '1.80',
        '1-st map: Total. 25.5. Under': '1.95',
        '1-st map: Total. 26.5. Over': '2.08',
        '1-st map: Total. 26.5. Under': '1.70',
        '1-st map: Total. 27.5. Over': '2.65',
        '1-st map: Total. 27.5. Under': '1.44',
        '1-st map: Win of the 1st team': '3.75',
        '1-st map: Win of the 2nd team': '1.25',
        '1-st map: chiefs Handicap value. –3.5. Handicap coefficient': '1.55',
        '1-st map: chiefs Handicap value. –4.5. Handicap coefficient': '1.75',
        '1-st map: chiefs Handicap value. –5.5. Handicap coefficient': '2.00',
        '1-st map: twa Handicap value. +3.5. Handicap coefficient': '2.35',
        '1-st map: twa Handicap value. +4.5. Handicap coefficient': '2.01',
        '1-st map: twa Handicap value. +5.5. Handicap coefficient': '1.76',
        'Total. 2.5. Over': '2.55',
        'Total. 2.5. Under': '1.47',
        'Win of the 1st team': '5.00',
        'Win of the 2nd team': '1.15',
        'chiefs Handicap value. –1.5. Handicap coefficient': '1.55',
        'twa Handicap value. +1.5. Handicap coefficient': '2.35'
        },
    'tyloo - mazaalai': {
        '1-st map: Total. 25.5. Over': '1.90',
        '1-st map: Total. 25.5. Under': '1.85',
        '1-st map: Win of the 1st team': '1.20',
        '1-st map: Win of the 2nd team': '4.20',
        '1-st map: mazaalai Handicap value. +5.5. Handicap coefficient': '1.95',
        '1-st map: tyloo Handicap value. –5.5. Handicap coefficient': '1.80',
        'Total. 2.5. Over': '2.95',
        'Total. 2.5. Under': '1.37',
        'Win of the 1st team': '1.10',
        'Win of the 2nd team': '6.25',
        'mazaalai Handicap value. +1.5. Handicap coefficient': '2.62',
        'tyloo Handicap value. –1.5. Handicap coefficient': '1.44'
        },
    'unknown gods - bmth': {
        '1-st map: Away win': '1.95',
        '1-st map: Home win': '1.80',
        '1-st map: Total. 25.5. Over': '1.57',
        '1-st map: Total. 25.5. Under': '2.31',
        '1-st map: Total. 26.5. Over': '1.87',
        '1-st map: Total. 26.5. Under': '1.87',
        '1-st map: Total. 27.5. Over': '2.37',
        '1-st map: Total. 27.5. Under': '1.54',
        '1-st map: bmth Handicap value. +2.5. Handicap coefficient': '1.73',
        '1-st map: bmth Handicap value. +3.5. Handicap coefficient': '1.55',
        '1-st map: bmth Handicap value. –2.5. Handicap coefficient': '2.30',
        '1-st map: unknown gods Handicap value. +2.5. Handicap coefficient': '1.58',
        '1-st map: unknown gods Handicap value. –2.5. Handicap coefficient': '2.03',
        '1-st map: unknown gods Handicap value. –3.5. Handicap coefficient': '2.35',
        'Away win': '3.53',
        'Draw': '1.90',
        'Home win': '3.25',
        'bmth Handicap value. +0.5. Handicap coefficient': '1.31',
        'unknown gods Handicap value. –0.5. Handicap coefficient': '3.25'
        },
    'vici gaming - divine vendetta': {
        '1-st map: Total. 25.5. Over': '1.80',
        '1-st map: Total. 25.5. Under': '1.95',
        '1-st map: Win of the 1st team': '1.25',
        '1-st map: Win of the 2nd team': '3.75',
        '1-st map: divine vendetta Handicap value. +4.5. Handicap coefficient': '2.01',
        '1-st map: vici gaming Handicap value. –4.5. Handicap coefficient': '1.75',
        'Total. 2.5. Over': '2.55',
        'Total. 2.5. Under': '1.47',
        'Win of the 1st team': '1.15',
        'Win of the 2nd team': '5.00',
        'divine vendetta Handicap value. +1.5. Handicap coefficient': '2.35',
        'vici gaming Handicap value. –1.5. Handicap coefficient': '1.55'
        },
    'vitality - big': {
        '1-st map: Total. 25.5. Over': '1.47',
        '1-st map: Total. 25.5. Under': '2.55',
        '1-st map: Total. 26.5. Over': '1.77',
        '1-st map: Total. 26.5. Under': '1.97',
        '1-st map: Total. 27.5. Over': '2.15',
        '1-st map: Total. 27.5. Under': '1.65',
        '1-st map: Win of the 1st team': '2.01',
        '1-st map: Win of the 2nd team': '1.75',
        '1-st map: big Handicap value. +2.5. Handicap coefficient': '1.55',
        '1-st map: big Handicap value. –2.5. Handicap coefficient': '2.00',
        '1-st map: big Handicap value. –3.5. Handicap coefficient': '2.30',
        '1-st map: vitality Handicap value. +2.5. Handicap coefficient': '1.76',
        '1-st map: vitality Handicap value. +3.5. Handicap coefficient': '1.58',
        '1-st map: vitality Handicap value. –2.5. Handicap coefficient': '2.35',
        'Total. 2.5. Over': '1.95',
        'Total. 2.5. Under': '1.80',
        'Win of the 1st team': '2.15',
        'Win of the 2nd team': '1.65',
        'big Handicap value. –1.5. Handicap coefficient': '3.05',
        'vitality Handicap value. +1.5. Handicap coefficient': '1.35'
        },
    'w2c - aim4r': {'Win of the 1st team': '1.50', 'Win of the 2nd team': '2.48'},
    'wesq - purple haze': {
        '1-st map: Away win': '1.20',
        '1-st map: Home win': '4.20',
        '1-st map: Total. 25.5. Over': '1.90',
        '1-st map: Total. 25.5. Under': '1.85',
        '1-st map: Total. 26.5. Over': '2.25',
        '1-st map: Total. 26.5. Under': '1.60',
        '1-st map: Total. 27.5. Over': '2.75',
        '1-st map: Total. 27.5. Under': '1.42',
        '1-st map: purple haze Handicap value. –5.5. Handicap coefficient': '1.80',
        '1-st map: purple haze Handicap value. –6.5. Handicap coefficient': '2.05',
        '1-st map: purple haze Handicap value. –7.5. Handicap coefficient': '2.35',
        '1-st map: wesq Handicap value. +5.5. Handicap coefficient': '1.95',
        '1-st map: wesq Handicap value. +6.5. Handicap coefficient': '1.72',
        '1-st map: wesq Handicap value. +7.5. Handicap coefficient': '1.55',
        'Away win': '1.45',
        'Draw': '2.75',
        'Home win': '15.6',
        'purple haze Handicap value. –0.5. Handicap coefficient': '1.45',
        'wesq Handicap value. +0.5. Handicap coefficient': '2.63'
        },
    'wesq - rembaza': {
        '1-st map: Away win': '1.25',
        '1-st map: Home win': '3.75',
        '1-st map: Total. 25.5. Over': '1.80',
        '1-st map: Total. 25.5. Under': '1.95',
        '1-st map: Total. 26.5. Over': '2.08',
        '1-st map: Total. 26.5. Under': '1.70',
        '1-st map: Total. 27.5. Over': '2.65',
        '1-st map: Total. 27.5. Under': '1.44',
        '1-st map: rembaza Handicap value. –3.5. Handicap coefficient': '1.55',
        '1-st map: rembaza Handicap value. –4.5. Handicap coefficient': '1.75',
        '1-st map: rembaza Handicap value. –5.5. Handicap coefficient': '2.00',
        '1-st map: wesq Handicap value. +3.5. Handicap coefficient': '2.35',
        '1-st map: wesq Handicap value. +4.5. Handicap coefficient': '2.01',
        '1-st map: wesq Handicap value. +5.5. Handicap coefficient': '1.76',
        'Away win': '1.50',
        'Draw': '2.65',
        'Home win': '13.6',
        'rembaza Handicap value. –0.5. Handicap coefficient': '1.50',
        'wesq Handicap value. +0.5. Handicap coefficient': '2.48'
        },
    'winstrike - tenerife titans': {
        '1-st map: Total. 25.5. Over': '1.80',
        '1-st map: Total. 25.5. Under': '1.95',
        '1-st map: Win of the 1st team': '1.25',
        '1-st map: Win of the 2nd team': '3.75',
        '1-st map: tenerife titans Handicap value. +4.5. Handicap coefficient': '2.01',
        '1-st map: winstrike Handicap value. –4.5. Handicap coefficient': '1.75',
        'Total. 2.5. Over': '2.80',
        'Total. 2.5. Under': '1.40',
        'Win of the 1st team': '1.15',
        'Win of the 2nd team': '5.00',
        'tenerife titans Handicap value. +1.5. Handicap coefficient': '2.35',
        'winstrike Handicap value. –1.5. Handicap coefficient': '1.55'
        },
    'yung trappers - purple haze': {
        '1-st map: Away win': '1.20',
        '1-st map: Home win': '4.20',
        '1-st map: Total. 25.5. Over': '1.90',
        '1-st map: Total. 25.5. Under': '1.85',
        '1-st map: Total. 26.5. Over': '2.25',
        '1-st map: Total. 26.5. Under': '1.60',
        '1-st map: Total. 27.5. Over': '2.75',
        '1-st map: Total. 27.5. Under': '1.42',
        '1-st map: purple haze Handicap value. –5.5. Handicap coefficient': '1.80',
        '1-st map: purple haze Handicap value. –6.5. Handicap coefficient': '2.05',
        '1-st map: purple haze Handicap value. –7.5. Handicap coefficient': '2.35',
        '1-st map: yung trappers Handicap value. +5.5. Handicap coefficient': '1.95',
        '1-st map: yung trappers Handicap value. +6.5. Handicap coefficient': '1.72',
        '1-st map: yung trappers Handicap value. +7.5. Handicap coefficient': '1.55',
        'Away win': '1.45',
        'Draw': '2.75',
        'Home win': '15.6',
        'purple haze Handicap value. –0.5. Handicap coefficient': '1.45',
        'yung trappers Handicap value. +0.5. Handicap coefficient': '2.63'
        },
    'yung trappers - rembaza': {
        '1-st map: Away win': '1.25',
        '1-st map: Home win': '3.75',
        '1-st map: Total. 25.5. Over': '1.80',
        '1-st map: Total. 25.5. Under': '1.95',
        '1-st map: Total. 26.5. Over': '2.08',
        '1-st map: Total. 26.5. Under': '1.70',
        '1-st map: Total. 27.5. Over': '2.65',
        '1-st map: Total. 27.5. Under': '1.44',
        '1-st map: rembaza Handicap value. –3.5. Handicap coefficient': '1.55',
        '1-st map: rembaza Handicap value. –4.5. Handicap coefficient': '1.75',
        '1-st map: rembaza Handicap value. –5.5. Handicap coefficient': '2.00',
        '1-st map: yung trappers Handicap value. +3.5. Handicap coefficient': '2.35',
        '1-st map: yung trappers Handicap value. +4.5. Handicap coefficient': '2.01',
        '1-st map: yung trappers Handicap value. +5.5. Handicap coefficient': '1.76',
        'Away win': '1.50',
        'Draw': '2.65',
        'Home win': '13.6',
        'rembaza Handicap value. –0.5. Handicap coefficient': '1.50',
        'yung trappers Handicap value. +0.5. Handicap coefficient': '2.48'
        }
    }
