sport = {'csgo': {'ambush - tricked(favorit - https://www.favorit.com.ua/en/bets/#event=27118877&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'1-st map: ambush handicap +2.5': '1.62',
                                                                                                                                                           '1-st map: ambush will win': '1.89',
                                                                                                                                                           '1-st map: overtime no': '1.08',
                                                                                                                                                           '1-st map: overtime yes': '6.80',
                                                                                                                                                           '1-st map: total rounds even': '1.79',
                                                                                                                                                           '1-st map: total rounds odd': '1.96',
                                                                                                                                                           '1-st map: total rounds over 26.5': '1.77',
                                                                                                                                                           '1-st map: total rounds under 26.5': '1.98',
                                                                                                                                                           '1-st map: tricked handicap -2.5': '2.21',
                                                                                                                                                           '1-st map: tricked will win': '1.85',
                                                                                                                                                           '2-nd map: ambush handicap +2.5': '1.62',
                                                                                                                                                           '2-nd map: ambush will win': '1.89',
                                                                                                                                                           '2-nd map: overtime no': '1.08',
                                                                                                                                                           '2-nd map: overtime yes': '6.80',
                                                                                                                                                           '2-nd map: total rounds even': '1.79',
                                                                                                                                                           '2-nd map: total rounds odd': '1.96',
                                                                                                                                                           '2-nd map: total rounds over 26.5': '1.77',
                                                                                                                                                           '2-nd map: total rounds under 26.5': '1.98',
                                                                                                                                                           '2-nd map: tricked handicap -2.5': '2.21',
                                                                                                                                                           '2-nd map: tricked will win': '1.85',
                                                                                                                                                           'ambush handicap +1.5 maps': '1.30',
                                                                                                                                                           'ambush will win': '1.90',
                                                                                                                                                           'correct score 0-2': '3.30',
                                                                                                                                                           'correct score 1-2': '3.40',
                                                                                                                                                           'correct score 2-0': '3.60',
                                                                                                                                                           'correct score 2-1': '3.50',
                                                                                                                                                           'total maps over 2.5': '2.08',
                                                                                                                                                           'total maps under 2.5': '1.70',
                                                                                                                                                           'tricked handicap -1.5 maps': '3.30',
                                                                                                                                                           'tricked will win': '1.84'},
          'avez - cr4zy(favorit - https://www.favorit.com.ua/en/bets/#event=27150815&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'1-st map: avez handicap -2.5': '1.80',
                                                                                                                                                       '1-st map: avez will win': '1.56',
                                                                                                                                                       '1-st map: cr4zy handicap +2.5': '1.95',
                                                                                                                                                       '1-st map: cr4zy will win': '2.33',
                                                                                                                                                       '1-st map: overtime no': '1.07',
                                                                                                                                                       '1-st map: overtime yes': '7.20',
                                                                                                                                                       '1-st map: total rounds even': '1.71',
                                                                                                                                                       '1-st map: total rounds odd': '2.06',
                                                                                                                                                       '1-st map: total rounds over 26.5': '1.90',
                                                                                                                                                       '1-st map: total rounds under 26.5': '1.84',
                                                                                                                                                       '2-nd map: avez handicap -2.5': '1.80',
                                                                                                                                                       '2-nd map: avez will win': '1.56',
                                                                                                                                                       '2-nd map: cr4zy handicap +2.5': '1.95',
                                                                                                                                                       '2-nd map: cr4zy will win': '2.33',
                                                                                                                                                       '2-nd map: overtime no': '1.07',
                                                                                                                                                       '2-nd map: overtime yes': '7.20',
                                                                                                                                                       '2-nd map: total rounds even': '1.71',
                                                                                                                                                       '2-nd map: total rounds odd': '2.06',
                                                                                                                                                       '2-nd map: total rounds over 26.5': '1.90',
                                                                                                                                                       '2-nd map: total rounds under 26.5': '1.84',
                                                                                                                                                       'avez handicap -1.5 maps': '2.53',
                                                                                                                                                       'avez will win': '1.53',
                                                                                                                                                       'correct score 0-2': '5.20',
                                                                                                                                                       'correct score 1-2': '3.80',
                                                                                                                                                       'correct score 2-0': '2.53',
                                                                                                                                                       'correct score 2-1': '3.30',
                                                                                                                                                       'cr4zy handicap +1.5 maps': '1.48',
                                                                                                                                                       'cr4zy will win': '2.40',
                                                                                                                                                       'total maps over 2.5': '2.03',
                                                                                                                                                       'total maps under 2.5': '1.73'},
          'bantz - mako(favorit - https://www.favorit.com.ua/en/bets/#event=27159240&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'bantz will win': '1.53',
                                                                                                                                                       'mako will win': '2.40'},
          'bren - invictus gaming(favorit - https://www.favorit.com.ua/en/bets/#event=27150824&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'bren will win': '2.65',
                                                                                                                                                                 'invictus gaming will win': '1.44'},
          'chaos - yeah gaming(favorit - https://www.favorit.com.ua/en/bets/#event=27156869&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'1-st map: chaos handicap -5.5': '1.96',
                                                                                                                                                              '1-st map: chaos will win': '1.23',
                                                                                                                                                              '1-st map: overtime no': '1.05',
                                                                                                                                                              '1-st map: overtime yes': '8.40',
                                                                                                                                                              '1-st map: total rounds even': '1.81',
                                                                                                                                                              '1-st map: total rounds odd': '1.94',
                                                                                                                                                              '1-st map: total rounds over 25.5': '1.78',
                                                                                                                                                              '1-st map: total rounds under 25.5': '1.97',
                                                                                                                                                              '1-st map: yeah gaming handicap +5.5': '1.79',
                                                                                                                                                              '1-st map: yeah gaming will win': '3.90',
                                                                                                                                                              '2-nd map: chaos handicap -5.5': '1.96',
                                                                                                                                                              '2-nd map: chaos will win': '1.23',
                                                                                                                                                              '2-nd map: overtime no': '1.05',
                                                                                                                                                              '2-nd map: overtime yes': '8.40',
                                                                                                                                                              '2-nd map: total rounds even': '1.81',
                                                                                                                                                              '2-nd map: total rounds odd': '1.94',
                                                                                                                                                              '2-nd map: total rounds over 25.5': '1.78',
                                                                                                                                                              '2-nd map: total rounds under 25.5': '1.97',
                                                                                                                                                              '2-nd map: yeah gaming handicap +5.5': '1.79',
                                                                                                                                                              '2-nd map: yeah gaming will win': '3.90',
                                                                                                                                                              'chaos handicap -1.5 maps': '1.50',
                                                                                                                                                              'chaos will win': '1.13',
                                                                                                                                                              'correct score 0-2': '11.50',
                                                                                                                                                              'correct score 1-2': '8.00',
                                                                                                                                                              'correct score 2-0': '1.50',
                                                                                                                                                              'correct score 2-1': '3.60',
                                                                                                                                                              'total maps over 2.5': '2.95',
                                                                                                                                                              'total maps under 2.5': '1.37',
                                                                                                                                                              'yeah gaming handicap +1.5 maps': '2.50',
                                                                                                                                                              'yeah gaming will win': '5.40'},
          'esport rhein-neckar - for the win(favorit - https://www.favorit.com.ua/en/bets/#event=27145904&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'esport rhein-neckar will win': '2.23',
                                                                                                                                                                            'for the win will win': '1.61'},
          'esport rhein-neckar - nexus(favorit - https://www.favorit.com.ua/en/bets/#event=27145903&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'esport rhein-neckar will win': '4.25',
                                                                                                                                                                      'nexus will win': '1.20'},
          'fate - wizards(favorit - https://www.favorit.com.ua/en/bets/#event=27150798&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'1-st map: fate handicap -3.5': '2.02',
                                                                                                                                                         '1-st map: fate will win': '1.51',
                                                                                                                                                         '1-st map: overtime no': '1.07',
                                                                                                                                                         '1-st map: overtime yes': '7.20',
                                                                                                                                                         '1-st map: total rounds even': '1.71',
                                                                                                                                                         '1-st map: total rounds odd': '2.06',
                                                                                                                                                         '1-st map: total rounds over 26.5': '1.92',
                                                                                                                                                         '1-st map: total rounds under 26.5': '1.82',
                                                                                                                                                         '1-st map: wizards handicap +3.5': '1.74',
                                                                                                                                                         '1-st map: wizards will win': '2.46',
                                                                                                                                                         '2-nd map: fate handicap -3.5': '2.02',
                                                                                                                                                         '2-nd map: fate will win': '1.51',
                                                                                                                                                         '2-nd map: overtime no': '1.07',
                                                                                                                                                         '2-nd map: overtime yes': '7.20',
                                                                                                                                                         '2-nd map: total rounds even': '1.71',
                                                                                                                                                         '2-nd map: total rounds odd': '2.06',
                                                                                                                                                         '2-nd map: total rounds over 26.5': '1.92',
                                                                                                                                                         '2-nd map: total rounds under 26.5': '1.82',
                                                                                                                                                         '2-nd map: wizards handicap +3.5': '1.74',
                                                                                                                                                         '2-nd map: wizards will win': '2.46',
                                                                                                                                                         'correct score 0-2': '5.80',
                                                                                                                                                         'correct score 1-2': '4.50',
                                                                                                                                                         'correct score 2-0': '2.36',
                                                                                                                                                         'correct score 2-1': '3.10',
                                                                                                                                                         'fate handicap -1.5 maps': '2.36',
                                                                                                                                                         'fate will win': '1.42',
                                                                                                                                                         'total maps over 2.5': '2.08',
                                                                                                                                                         'total maps under 2.5': '1.70',
                                                                                                                                                         'wizards handicap +1.5 maps': '1.55',
                                                                                                                                                         'wizards will win': '2.75'},
          'for the win - nexus(favorit - https://www.favorit.com.ua/en/bets/#event=27158204&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'for the win will win': '3.90',
                                                                                                                                                              'nexus will win': '1.23'},
          'one - triumph(favorit - https://www.favorit.com.ua/en/bets/#event=27156920&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'1-st map: one handicap +3.5': '1.94',
                                                                                                                                                        '1-st map: one will win': '2.87',
                                                                                                                                                        '1-st map: overtime no': '1.07',
                                                                                                                                                        '1-st map: overtime yes': '7.60',
                                                                                                                                                        '1-st map: total rounds even': '1.71',
                                                                                                                                                        '1-st map: total rounds odd': '2.06',
                                                                                                                                                        '1-st map: total rounds over 26.5': '1.98',
                                                                                                                                                        '1-st map: total rounds under 26.5': '1.77',
                                                                                                                                                        '1-st map: triumph handicap -3.5': '1.81',
                                                                                                                                                        '1-st map: triumph will win': '1.39',
                                                                                                                                                        '2-nd map: one handicap +3.5': '1.94',
                                                                                                                                                        '2-nd map: one will win': '2.87',
                                                                                                                                                        '2-nd map: overtime no': '1.07',
                                                                                                                                                        '2-nd map: overtime yes': '7.60',
                                                                                                                                                        '2-nd map: total rounds even': '1.71',
                                                                                                                                                        '2-nd map: total rounds odd': '2.06',
                                                                                                                                                        '2-nd map: total rounds over 26.5': '1.98',
                                                                                                                                                        '2-nd map: total rounds under 26.5': '1.77',
                                                                                                                                                        '2-nd map: triumph handicap -3.5': '1.81',
                                                                                                                                                        '2-nd map: triumph will win': '1.39',
                                                                                                                                                        'correct score 0-2': '1.97',
                                                                                                                                                        'correct score 1-2': '3.30',
                                                                                                                                                        'correct score 2-0': '7.40',
                                                                                                                                                        'correct score 2-1': '5.00',
                                                                                                                                                        'one handicap +1.5 maps': '1.78',
                                                                                                                                                        'one will win': '3.25',
                                                                                                                                                        'total maps over 2.5': '2.40',
                                                                                                                                                        'total maps under 2.5': '1.54',
                                                                                                                                                        'triumph handicap -1.5 maps': '1.97',
                                                                                                                                                        'triumph will win': '1.31'},
          'reckoning - wolf(favorit - https://www.favorit.com.ua/en/bets/#event=27141060&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'reckoning will win': '1.25',
                                                                                                                                                           'wolf will win': '3.70'},
          'saw - secret(favorit - https://www.favorit.com.ua/en/bets/#event=27124572&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'1-st map: overtime no': '1.07',
                                                                                                                                                       '1-st map: overtime yes': '7.20',
                                                                                                                                                       '1-st map: saw handicap -3.5': '2.02',
                                                                                                                                                       '1-st map: saw will win': '1.51',
                                                                                                                                                       '1-st map: secret handicap +3.5': '1.74',
                                                                                                                                                       '1-st map: secret will win': '2.46',
                                                                                                                                                       '1-st map: total rounds even': '1.71',
                                                                                                                                                       '1-st map: total rounds odd': '2.06',
                                                                                                                                                       '1-st map: total rounds over 26.5': '1.92',
                                                                                                                                                       '1-st map: total rounds under 26.5': '1.82',
                                                                                                                                                       '2-nd map: overtime no': '1.07',
                                                                                                                                                       '2-nd map: overtime yes': '7.20',
                                                                                                                                                       '2-nd map: saw handicap -3.5': '2.02',
                                                                                                                                                       '2-nd map: saw will win': '1.51',
                                                                                                                                                       '2-nd map: secret handicap +3.5': '1.74',
                                                                                                                                                       '2-nd map: secret will win': '2.46',
                                                                                                                                                       '2-nd map: total rounds even': '1.71',
                                                                                                                                                       '2-nd map: total rounds odd': '2.06',
                                                                                                                                                       '2-nd map: total rounds over 26.5': '1.92',
                                                                                                                                                       '2-nd map: total rounds under 26.5': '1.82',
                                                                                                                                                       'correct score 0-2': '5.80',
                                                                                                                                                       'correct score 1-2': '4.40',
                                                                                                                                                       'correct score 2-0': '2.36',
                                                                                                                                                       'correct score 2-1': '3.20',
                                                                                                                                                       'saw handicap -1.5 maps': '2.36',
                                                                                                                                                       'saw will win': '1.42',
                                                                                                                                                       'secret handicap +1.5 maps': '1.55',
                                                                                                                                                       'secret will win': '2.72',
                                                                                                                                                       'total maps over 2.5': '2.16',
                                                                                                                                                       'total maps under 2.5': '1.65'},
          'skyfire - truckers with attitude(favorit - https://www.favorit.com.ua/en/bets/#event=27159244&tours=1284478,1636941,1727483,2408290,2452749,2458146,2472408)': {'skyfire will win': '2.55',
                                                                                                                                                                           'truckers with attitude will win': '1.47'}}}
