sport = {'csgo': {'bluejays international - dragon shark': {'1-st map: bluejays international will win': ['1.52(ggbet - https://gg.bet/en/betting/match/bluejays-international-vs-dragon-shark-18-07)'],
                                                    '1-st map: dragon shark will win': ['2.43(ggbet - https://gg.bet/en/betting/match/bluejays-international-vs-dragon-shark-18-07)'],
                                                    'bluejays international will win': ['1.53(ggbet - https://gg.bet/en/betting/match/bluejays-international-vs-dragon-shark-18-07)'],
                                                    'dragon shark will win': ['2.43(ggbet - https://gg.bet/en/betting/match/bluejays-international-vs-dragon-shark-18-07)']},
          'bmth - qup': {'bmth will win': ['1.48(ggbet - https://gg.bet/en/betting/match/bmth-vs-qup-18-07)'], 'qup will win': ['2.57(ggbet - https://gg.bet/en/betting/match/bmth-vs-qup-18-07)']},
          'excellency - fate': {'1-st map: excellency handicap +1.5 rounds': ['2.11(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency handicap +2.5 rounds': ['1.88(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency handicap +3.5 rounds': ['1.69(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency handicap +4.5 rounds': ['1.54(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency handicap +5.5 rounds': ['1.41(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency handicap +6.5 rounds': ['1.3(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency handicap +7.5 rounds': ['1.21(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency handicap -1.5 rounds': ['2.66(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency handicap -2.5 rounds': ['3.04(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency handicap -3.5 rounds': ['3.54(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency handicap -4.5 rounds': ['4.11(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency will win': ['2.38(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: excellency will win in round 1': ['1.92(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap +1.5 rounds': ['1.44(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap +2.5 rounds': ['1.35(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap +3.5 rounds': ['1.27(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap +4.5 rounds': ['1.21(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap -1.5 rounds': ['1.68(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap -2.5 rounds': ['1.86(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap -3.5 rounds': ['2.09(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap -4.5 rounds': ['2.38(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap -5.5 rounds': ['2.77(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap -6.5 rounds': ['3.32(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate handicap -7.5 rounds': ['4.11(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate will win': ['1.54(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: fate will win in round 1': ['1.82(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds over 23.5': ['1.23(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds over 24.5': ['1.37(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds over 25.5': ['1.55(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds over 26.5': ['1.82(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds over 27.5': ['2.23(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds over 28.5': ['2.9(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds over 29.5': ['4.11(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds under 23.5': ['3.89(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds under 24.5': ['2.94(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds under 25.5': ['2.35(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds under 26.5': ['1.92(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds under 27.5': ['1.61(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds under 28.5': ['1.38(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                '1-st map: total rounds under 29.5': ['1.21(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                'excellency will win': ['2.38(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)'],
                                'fate will win': ['1.55(ggbet - https://gg.bet/en/betting/match/excellency-vs-fate-17-07)']},
          'for the win esports - nexus': {'1-st map: for the win esports will win': ['2.63(ggbet - https://gg.bet/en/betting/match/for-the-win-esports-vs-nexus-17-07)'],
                                          '1-st map: nexus will win': ['1.45(ggbet - https://gg.bet/en/betting/match/for-the-win-esports-vs-nexus-17-07)'],
                                          '2-nd map: for the win esports will win': ['2.66(ggbet - https://gg.bet/en/betting/match/for-the-win-esports-vs-nexus-17-07)'],
                                          '2-nd map: nexus will win': ['1.44(ggbet - https://gg.bet/en/betting/match/for-the-win-esports-vs-nexus-17-07)'],
                                          'for the win esports will win': ['3.03(ggbet - https://gg.bet/en/betting/match/for-the-win-esports-vs-nexus-17-07)'],
                                          'nexus will win': ['1.36(ggbet - https://gg.bet/en/betting/match/for-the-win-esports-vs-nexus-17-07)']},
          'gucci squad - next': {'gucci squad will win': ['1.15(ggbet - https://gg.bet/en/betting/match/gucci-squad-vs-next-18-07)'], 'next will win': ['5.12(ggbet - https://gg.bet/en/betting/match/gucci-squad-vs-next-18-07)']},
          'invictus gaming - vici': {'1-st map: invictus gaming handicap +1.5 rounds': ['2.11(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming handicap +2.5 rounds': ['1.88(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming handicap +3.5 rounds': ['1.69(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming handicap +4.5 rounds': ['1.54(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming handicap +5.5 rounds': ['1.41(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming handicap +6.5 rounds': ['1.3(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming handicap +7.5 rounds': ['1.21(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming handicap -1.5 rounds': ['2.66(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming handicap -2.5 rounds': ['3.04(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming handicap -3.5 rounds': ['3.54(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming handicap -4.5 rounds': ['4.11(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming will win': ['2.38(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: invictus gaming will win in round 1': ['1.92(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds over 23.5': ['1.24(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds over 24.5': ['1.37(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds over 25.5': ['1.56(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds over 26.5': ['1.83(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds over 27.5': ['2.25(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds over 28.5': ['2.9(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds over 29.5': ['4.11(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds under 23.5': ['3.79(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds under 24.5': ['2.94(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds under 25.5': ['2.33(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds under 26.5': ['1.91(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds under 27.5': ['1.6(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds under 28.5': ['1.38(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: total rounds under 29.5': ['1.21(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap +1.5 rounds': ['1.44(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap +2.5 rounds': ['1.35(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap +3.5 rounds': ['1.27(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap +4.5 rounds': ['1.21(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap -1.5 rounds': ['1.68(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap -2.5 rounds': ['1.86(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap -3.5 rounds': ['2.09(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap -4.5 rounds': ['2.38(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap -5.5 rounds': ['2.77(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap -6.5 rounds': ['3.32(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici handicap -7.5 rounds': ['4.11(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici will win': ['1.54(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '1-st map: vici will win in round 1': ['1.82(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap +1.5 rounds': ['2.11(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap +2.5 rounds': ['1.89(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap +3.5 rounds': ['1.71(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap +4.5 rounds': ['1.55(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap +5.5 rounds': ['1.42(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap +6.5 rounds': ['1.31(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap +7.5 rounds': ['1.22(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap -1.5 rounds': ['2.66(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap -2.5 rounds': ['3.04(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap -3.5 rounds': ['3.54(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming handicap -4.5 rounds': ['4.11(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming will win': ['2.4(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: invictus gaming will win in round 1': ['1.92(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds over 23.5': ['1.24(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds over 24.5': ['1.38(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds over 25.5': ['1.56(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds over 26.5': ['1.84(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds over 27.5': ['2.25(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds over 28.5': ['2.94(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds over 29.5': ['4.23(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds under 23.5': ['3.79(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds under 24.5': ['2.9(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds under 25.5': ['2.33(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds under 26.5': ['1.9(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds under 27.5': ['1.6(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds under 28.5': ['1.37(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: total rounds under 29.5': ['1.2(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap +1.5 rounds': ['1.44(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap +2.5 rounds': ['1.35(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap +3.5 rounds': ['1.27(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap +4.5 rounds': ['1.21(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap -1.5 rounds': ['1.68(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap -2.5 rounds': ['1.85(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap -3.5 rounds': ['2.06(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap -4.5 rounds': ['2.35(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap -5.5 rounds': ['2.73(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap -6.5 rounds': ['3.26(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici handicap -7.5 rounds': ['3.99(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici will win': ['1.53(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     '2-nd map: vici will win in round 1': ['1.82(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'correct score 0-2': ['2.27(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'correct score 1-2': ['3.52(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'correct score 2-0': ['4.74(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'correct score 2-1': ['4.83(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'invictus gaming handicap +1.5 maps': ['1.59(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'invictus gaming handicap -1.5 maps': ['4.81(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'invictus gaming will win': ['2.63(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'total maps even': ['1.63(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'total maps odd': ['2.19(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'total maps over 2.5': ['2.19(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'total maps under 2.5': ['1.63(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'vici handicap +1.5 maps': ['1.16(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'vici handicap -1.5 maps': ['2.27(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)'],
                                     'vici will win': ['1.46(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-vici-18-07)']},
          'izako boars - s-gaming': {'1-st map: izako boars will win': ['1.57(ggbet - https://gg.bet/en/betting/match/izako-boars-vs-s-gaming-18-07)'],
                                     '1-st map: s-gaming will win': ['2.31(ggbet - https://gg.bet/en/betting/match/izako-boars-vs-s-gaming-18-07)'],
                                     'izako boars will win': ['1.58(ggbet - https://gg.bet/en/betting/match/izako-boars-vs-s-gaming-18-07)'],
                                     's-gaming will win': ['2.31(ggbet - https://gg.bet/en/betting/match/izako-boars-vs-s-gaming-18-07)']},
          'lyngby vikings - unicorns of love': {'1-st map: lyngby vikings will win': ['1.57(ggbet - https://gg.bet/en/betting/match/lyngby-vikings-vs-unicorns-of-love-17-07)'],
                                                '1-st map: unicorns of love will win': ['2.31(ggbet - https://gg.bet/en/betting/match/lyngby-vikings-vs-unicorns-of-love-17-07)'],
                                                'lyngby vikings will win': ['1.58(ggbet - https://gg.bet/en/betting/match/lyngby-vikings-vs-unicorns-of-love-17-07)'],
                                                'unicorns of love will win': ['2.31(ggbet - https://gg.bet/en/betting/match/lyngby-vikings-vs-unicorns-of-love-17-07)']},
          'majesty - hauntedfamilly': {'hauntedfamilly will win': ['2.51(ggbet - https://gg.bet/en/betting/match/majesty-vs-hauntedfamilly-18-07)'], 'majesty will win': ['1.5(ggbet - https://gg.bet/en/betting/match/majesty-vs-hauntedfamilly-18-07)']},
          'nightraid - libertatem': {'1-st map: libertatem handicap -1.5 rounds': ['1.64(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '1-st map: libertatem handicap -2.5 rounds': ['1.81(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '1-st map: libertatem handicap -3.5 rounds': ['2.02(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '1-st map: libertatem will win': ['1.5(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '1-st map: nightraid handicap +1.5 rounds': ['2.17(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '1-st map: nightraid handicap +2.5 rounds': ['1.93(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '1-st map: nightraid handicap +3.5 rounds': ['1.74(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '1-st map: nightraid will win': ['2.48(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '1-st map: total rounds over 26.5': ['1.84(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '1-st map: total rounds under 26.5': ['1.9(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '2-nd map: libertatem handicap -1.5 rounds': ['1.63(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '2-nd map: libertatem handicap -2.5 rounds': ['1.79(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '2-nd map: libertatem handicap -3.5 rounds': ['2.01(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '2-nd map: libertatem will win': ['1.49(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '2-nd map: nightraid handicap +1.5 rounds': ['2.19(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '2-nd map: nightraid handicap +2.5 rounds': ['1.96(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '2-nd map: nightraid handicap +3.5 rounds': ['1.75(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '2-nd map: nightraid will win': ['2.51(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '2-nd map: total rounds over 26.5': ['1.85(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     '2-nd map: total rounds under 26.5': ['1.89(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     'draw will win': ['2.1(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     'libertatem handicap +0.5 maps': ['1.15(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     'libertatem handicap -0.5 maps': ['2.17(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     'libertatem will win': ['2.27(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     'nightraid handicap +0.5 maps': ['1.64(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     'nightraid handicap -0.5 maps': ['4.99(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)'],
                                     'nightraid will win': ['5.63(ggbet - https://gg.bet/en/betting/match/nightraid-vs-libertatem-17-07)']},
          'penta - big academy': {'1-st map: big academy will win': ['1.45(ggbet - https://gg.bet/en/betting/match/penta-vs-big-academy-17-07)'],
                                  '1-st map: penta will win': ['2.63(ggbet - https://gg.bet/en/betting/match/penta-vs-big-academy-17-07)'],
                                  '2-nd map: big academy will win': ['1.44(ggbet - https://gg.bet/en/betting/match/penta-vs-big-academy-17-07)'],
                                  '2-nd map: penta will win': ['2.66(ggbet - https://gg.bet/en/betting/match/penta-vs-big-academy-17-07)'],
                                  'big academy will win': ['2.06(ggbet - https://gg.bet/en/betting/match/penta-vs-big-academy-17-07)'],
                                  'draw will win': ['2.32(ggbet - https://gg.bet/en/betting/match/penta-vs-big-academy-17-07)'],
                                  'penta will win': ['5.61(ggbet - https://gg.bet/en/betting/match/penta-vs-big-academy-17-07)']},
          'rembaza - libertatem': {'1-st map: libertatem handicap +1.5 rounds': ['1.7(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '1-st map: libertatem handicap -1.5 rounds': ['2.06(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '1-st map: libertatem will win': ['1.86(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '1-st map: rembaza handicap +1.5 rounds': ['1.71(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '1-st map: rembaza handicap -1.5 rounds': ['2.08(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '1-st map: rembaza will win': ['1.88(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '1-st map: total rounds over 26.5': ['1.79(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '1-st map: total rounds over 27.5': ['2.19(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '1-st map: total rounds under 26.5': ['1.96(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '1-st map: total rounds under 27.5': ['1.63(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '2-nd map: libertatem handicap +1.5 rounds': ['1.7(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '2-nd map: libertatem handicap -1.5 rounds': ['2.06(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '2-nd map: libertatem will win': ['1.86(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '2-nd map: rembaza handicap +1.5 rounds': ['1.71(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '2-nd map: rembaza handicap -1.5 rounds': ['2.08(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '2-nd map: rembaza will win': ['1.88(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '2-nd map: total rounds over 26.5': ['1.8(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '2-nd map: total rounds over 27.5': ['2.19(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '2-nd map: total rounds under 26.5': ['1.94(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   '2-nd map: total rounds under 27.5': ['1.63(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   'draw will win': ['1.97(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   'libertatem handicap +0.5 maps': ['1.32(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   'libertatem handicap -0.5 maps': ['3.2(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   'libertatem will win': ['3.4(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   'rembaza handicap +0.5 maps': ['1.32(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   'rembaza handicap -0.5 maps': ['3.2(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)'],
                                   'rembaza will win': ['3.41(ggbet - https://gg.bet/en/betting/match/rembaza-vs-libertatem-17-07)']},
          'rembaza - nightraid': {'1-st map: nightraid handicap +1.5 rounds': ['2.17(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '1-st map: nightraid handicap +2.5 rounds': ['1.93(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '1-st map: nightraid handicap +3.5 rounds': ['1.73(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '1-st map: nightraid will win': ['2.45(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '1-st map: rembaza handicap -1.5 rounds': ['1.64(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '1-st map: rembaza handicap -2.5 rounds': ['1.81(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '1-st map: rembaza handicap -3.5 rounds': ['2.03(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '1-st map: rembaza will win': ['1.51(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '1-st map: total rounds over 26.5': ['1.84(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '1-st map: total rounds under 26.5': ['1.9(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '2-nd map: nightraid handicap +1.5 rounds': ['2.17(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '2-nd map: nightraid handicap +2.5 rounds': ['1.93(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '2-nd map: nightraid handicap +3.5 rounds': ['1.74(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '2-nd map: nightraid will win': ['2.45(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '2-nd map: rembaza handicap -1.5 rounds': ['1.64(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '2-nd map: rembaza handicap -2.5 rounds': ['1.81(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '2-nd map: rembaza handicap -3.5 rounds': ['2.02(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '2-nd map: rembaza will win': ['1.51(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '2-nd map: total rounds over 26.5': ['1.85(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  '2-nd map: total rounds under 26.5': ['1.89(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  'draw will win': ['2.09(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  'nightraid handicap +0.5 maps': ['1.63(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  'nightraid handicap -0.5 maps': ['4.99(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  'nightraid will win': ['5.6(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  'rembaza handicap +0.5 maps': ['1.15(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  'rembaza handicap -0.5 maps': ['2.19(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)'],
                                  'rembaza will win': ['2.28(ggbet - https://gg.bet/en/betting/match/rembaza-vs-nightraid-17-07)']},
          'royalty - gameinside': {'gameinside will win': ['2.34(ggbet - https://gg.bet/en/betting/match/royalty-vs-gameinside-18-07)'], 'royalty will win': ['1.57(ggbet - https://gg.bet/en/betting/match/royalty-vs-gameinside-18-07)']},
          'team sampi - ex-adaptation': {'1-st map: ex-adaptation will win': ['2.03(ggbet - https://gg.bet/en/betting/match/team-sampi-vs-ex-adaptation-21-07)'],
                                         '1-st map: team sampi will win': ['1.73(ggbet - https://gg.bet/en/betting/match/team-sampi-vs-ex-adaptation-21-07)'],
                                         '2-nd map: ex-adaptation will win': ['2.03(ggbet - https://gg.bet/en/betting/match/team-sampi-vs-ex-adaptation-21-07)'],
                                         '2-nd map: team sampi will win': ['1.73(ggbet - https://gg.bet/en/betting/match/team-sampi-vs-ex-adaptation-21-07)'],
                                         'ex-adaptation will win': ['2.1(ggbet - https://gg.bet/en/betting/match/team-sampi-vs-ex-adaptation-21-07)'],
                                         'team sampi will win': ['1.7(ggbet - https://gg.bet/en/betting/match/team-sampi-vs-ex-adaptation-21-07)']},
          'tiger - beyond': {'1-st map: beyond handicap +1.5 rounds': ['2.17(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: beyond handicap +2.5 rounds': ['1.93(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: beyond handicap +3.5 rounds': ['1.73(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: beyond handicap +4.5 rounds': ['1.57(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: beyond will win': ['2.45(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: beyond will win in round 1': ['1.92(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: tiger handicap -1.5 rounds': ['1.64(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: tiger handicap -2.5 rounds': ['1.81(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: tiger handicap -3.5 rounds': ['2.03(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: tiger handicap -4.5 rounds': ['2.31(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: tiger will win': ['1.51(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: tiger will win in round 1': ['1.82(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: total rounds over 25.5': ['1.56(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: total rounds over 26.5': ['1.84(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: total rounds over 27.5': ['2.25(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: total rounds under 25.5': ['2.33(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: total rounds under 26.5': ['1.9(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '1-st map: total rounds under 27.5': ['1.6(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: beyond handicap +1.5 rounds': ['2.17(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: beyond handicap +2.5 rounds': ['1.93(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: beyond handicap +3.5 rounds': ['1.74(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: beyond handicap +4.5 rounds': ['1.57(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: beyond will win': ['2.45(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: beyond will win in round 1': ['1.92(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: tiger handicap -1.5 rounds': ['1.64(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: tiger handicap -2.5 rounds': ['1.81(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: tiger handicap -3.5 rounds': ['2.02(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: tiger handicap -4.5 rounds': ['2.31(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: tiger will win': ['1.51(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: tiger will win in round 1': ['1.82(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: total rounds over 25.5': ['1.57(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: total rounds over 26.5': ['1.85(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: total rounds over 27.5': ['2.27(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: total rounds under 25.5': ['2.31(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: total rounds under 26.5': ['1.89(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             '2-nd map: total rounds under 27.5': ['1.59(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'beyond handicap +1.5 maps': ['1.63(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'beyond handicap -1.5 maps': ['4.99(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'beyond will win': ['2.77(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'correct score 0-2': ['5.01(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'correct score 1-2': ['5.01(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'correct score 2-0': ['2.18(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'correct score 2-1': ['3.51(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'tiger handicap +1.5 maps': ['1.15(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'tiger handicap -1.5 maps': ['2.19(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'tiger will win': ['1.42(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'total maps even': ['1.62(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'total maps odd': ['2.21(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'total maps over 2.5': ['2.21(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)'],
                             'total maps under 2.5': ['1.62(ggbet - https://gg.bet/en/betting/match/tiger-vs-beyond-17-07)']},
          'tka e-sports - planetkey dynamics': {'1-st map: planetkey dynamics will win': ['3.2(ggbet - https://gg.bet/en/betting/match/tka-e-sports-vs-planetkey-dynamics-17-07)'],
                                                '1-st map: tka e-sports will win': ['1.32(ggbet - https://gg.bet/en/betting/match/tka-e-sports-vs-planetkey-dynamics-17-07)'],
                                                '2-nd map: planetkey dynamics will win': ['3.2(ggbet - https://gg.bet/en/betting/match/tka-e-sports-vs-planetkey-dynamics-17-07)'],
                                                '2-nd map: tka e-sports will win': ['1.32(ggbet - https://gg.bet/en/betting/match/tka-e-sports-vs-planetkey-dynamics-17-07)'],
                                                'draw will win': ['2.58(ggbet - https://gg.bet/en/betting/match/tka-e-sports-vs-planetkey-dynamics-17-07)'],
                                                'planetkey dynamics will win': ['7.55(ggbet - https://gg.bet/en/betting/match/tka-e-sports-vs-planetkey-dynamics-17-07)'],
                                                'tka e-sports will win': ['1.73(ggbet - https://gg.bet/en/betting/match/tka-e-sports-vs-planetkey-dynamics-17-07)']},
          'veterani - libertatem': {'1-st map: libertatem handicap +1.5 rounds': ['1.7(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '1-st map: libertatem handicap -1.5 rounds': ['2.06(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '1-st map: libertatem will win': ['1.86(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '1-st map: total rounds over 26.5': ['1.79(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '1-st map: total rounds over 27.5': ['2.19(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '1-st map: total rounds under 26.5': ['1.96(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '1-st map: total rounds under 27.5': ['1.63(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '1-st map: veterani handicap +1.5 rounds': ['1.71(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '1-st map: veterani handicap -1.5 rounds': ['2.08(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '1-st map: veterani will win': ['1.88(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '2-nd map: libertatem handicap +1.5 rounds': ['1.7(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '2-nd map: libertatem handicap -1.5 rounds': ['2.06(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '2-nd map: libertatem will win': ['1.86(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '2-nd map: total rounds over 26.5': ['1.8(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '2-nd map: total rounds over 27.5': ['2.19(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '2-nd map: total rounds under 26.5': ['1.94(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '2-nd map: total rounds under 27.5': ['1.63(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '2-nd map: veterani handicap +1.5 rounds': ['1.71(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '2-nd map: veterani handicap -1.5 rounds': ['2.08(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    '2-nd map: veterani will win': ['1.88(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    'draw will win': ['1.97(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    'libertatem handicap +0.5 maps': ['1.32(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    'libertatem handicap -0.5 maps': ['3.2(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    'libertatem will win': ['3.4(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    'veterani handicap +0.5 maps': ['1.32(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    'veterani handicap -0.5 maps': ['3.2(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)'],
                                    'veterani will win': ['3.41(ggbet - https://gg.bet/en/betting/match/veterani-vs-libertatem-17-07)']},
          'veterani - nightraid': {'1-st map: nightraid handicap +1.5 rounds': ['2.17(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '1-st map: nightraid handicap +2.5 rounds': ['1.93(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '1-st map: nightraid handicap +3.5 rounds': ['1.73(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '1-st map: nightraid will win': ['2.45(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '1-st map: total rounds over 26.5': ['1.84(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '1-st map: total rounds under 26.5': ['1.9(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '1-st map: veterani handicap -1.5 rounds': ['1.64(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '1-st map: veterani handicap -2.5 rounds': ['1.81(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '1-st map: veterani handicap -3.5 rounds': ['2.03(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '1-st map: veterani will win': ['1.51(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '2-nd map: nightraid handicap +1.5 rounds': ['2.17(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '2-nd map: nightraid handicap +2.5 rounds': ['1.93(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '2-nd map: nightraid handicap +3.5 rounds': ['1.74(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '2-nd map: nightraid will win': ['2.45(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '2-nd map: total rounds over 26.5': ['1.85(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '2-nd map: total rounds under 26.5': ['1.89(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '2-nd map: veterani handicap -1.5 rounds': ['1.64(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '2-nd map: veterani handicap -2.5 rounds': ['1.81(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '2-nd map: veterani handicap -3.5 rounds': ['2.02(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   '2-nd map: veterani will win': ['1.51(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   'draw will win': ['2.09(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   'nightraid handicap +0.5 maps': ['1.63(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   'nightraid handicap -0.5 maps': ['4.99(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   'nightraid will win': ['5.6(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   'veterani handicap +0.5 maps': ['1.15(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   'veterani handicap -0.5 maps': ['2.19(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)'],
                                   'veterani will win': ['2.28(ggbet - https://gg.bet/en/betting/match/veterani-vs-nightraid-17-07)']},
          'veterani - rembaza': {'1-st map: rembaza handicap +1.5 rounds': ['1.7(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '1-st map: rembaza handicap -1.5 rounds': ['2.06(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '1-st map: rembaza will win': ['1.86(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '1-st map: total rounds over 26.5': ['1.79(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '1-st map: total rounds over 27.5': ['2.19(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '1-st map: total rounds under 26.5': ['1.96(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '1-st map: total rounds under 27.5': ['1.63(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '1-st map: veterani handicap +1.5 rounds': ['1.71(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '1-st map: veterani handicap -1.5 rounds': ['2.08(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '1-st map: veterani will win': ['1.88(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '2-nd map: rembaza handicap +1.5 rounds': ['1.7(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '2-nd map: rembaza handicap -1.5 rounds': ['2.06(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '2-nd map: rembaza will win': ['1.86(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '2-nd map: total rounds over 26.5': ['1.8(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '2-nd map: total rounds over 27.5': ['2.19(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '2-nd map: total rounds under 26.5': ['1.94(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '2-nd map: total rounds under 27.5': ['1.63(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '2-nd map: veterani handicap +1.5 rounds': ['1.71(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '2-nd map: veterani handicap -1.5 rounds': ['2.08(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 '2-nd map: veterani will win': ['1.88(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 'draw will win': ['1.97(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 'rembaza handicap +0.5 maps': ['1.32(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 'rembaza handicap -0.5 maps': ['3.2(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 'rembaza will win': ['3.4(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 'veterani handicap +0.5 maps': ['1.32(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 'veterani handicap -0.5 maps': ['3.2(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)'],
                                 'veterani will win': ['3.41(ggbet - https://gg.bet/en/betting/match/veterani-vs-rembaza-17-07)']}}}
