sport = {'csgo': {'(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike)': {},
          'aion - wygers(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)': {'aion will win': '1.85',
                                                                                                                   'wygers will win': '1.90'},
          'alternate attax - sg.pro(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)': {'1-st map: handicap alternate attax -3.5': '1.55',
                                                                                                                              '1-st map: handicap sg.pro +3.5': '2.35',
                                                                                                                              '1-st map: total over 27.5': '2.65',
                                                                                                                              '1-st map: total under 27.5': '1.44'},
          'ambush - tricked(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)': {'1-st map: ambush will win': '1.90',
                                                                                                                          '1-st map: handicap ambush +2.5': '1.70',
                                                                                                                          '1-st map: handicap tricked -2.5': '2.08',
                                                                                                                          '1-st map: total over 26.5': '1.72',
                                                                                                                          '1-st map: total under 26.5': '2.05',
                                                                                                                          '1-st map: tricked will win': '1.85'},
          'apeks - winstrike(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)': {'1-st map: apeks will win': '2.01',
                                                                                                                           '1-st map: handicap apeks +2.5': '1.76',
                                                                                                                           '1-st map: handicap winstrike -2.5': '2.00',
                                                                                                                           '1-st map: total over 26.5': '1.77',
                                                                                                                           '1-st map: total under 26.5': '1.97',
                                                                                                                           '1-st map: winstrike will win': '1.75'},
          'atrapa2 - lbs(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)': {'atrapa2 will win': '4.20',
                                                                                                                   'lbs will win': '1.20'},
          'avez - nexus(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)': {'1-st map: handicap avez -4.5': '2.35',
                                                                                                                  '1-st map: handicap nexus +4.5': '1.55',
                                                                                                                  '1-st map: total over 25.5': '1.57',
                                                                                                                  '1-st map: total under 25.5': '2.31'},
          'big academy - down2earth(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-main-division)': {'big academy will win': '1.60',
                                                                                                                                       'down2earth will win': '2.25'},
          'bren - lucid dream(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)': {'1-st map: bren will win': '1.90',
                                                                                                                                     '1-st map: handicap bren +2.5': '1.70',
                                                                                                                                     '1-st map: handicap lucid dream -2.5': '2.08',
                                                                                                                                     '1-st map: lucid dream will win': '1.85',
                                                                                                                                     '1-st map: total over 26.5': '1.72',
                                                                                                                                     '1-st map: total under 26.5': '2.05'},
          'chaos - triumph(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-winners-league-na)': {'1-st map: handicap chaos +4.5': '1.50',
                                                                                                                          '1-st map: handicap triumph -4.5': '2.48',
                                                                                                                          '1-st map: total over 25.5': '1.55',
                                                                                                                          '1-st map: total under 25.5': '2.35'},
          'coliseo dragons - hawks(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)': {'coliseo dragons will win': '4.20',
                                                                                                                             'hawks will win': '1.20'},
          'cool - exploit(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-betano-masters-eu)': {'cool will win': '3.54',
                                                                                                                         'exploit will win': '1.27'},
          'cool - unicorns of love(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-betano-masters-eu)': {'cool will win': '5.00',
                                                                                                                                  'unicorns of love will win': '1.15'},
          'coscu army - nocturns(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)': {'coscu army will win': '1.55',
                                                                                                                           'nocturns will win': '2.35'},
          'cr4zy - ldlc(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)': {'1-st map: handicap cr4zy +2.5': '1.60',
                                                                                                                  '1-st map: handicap ldlc -2.5': '2.25',
                                                                                                                  '1-st map: total over 25.5': '1.47',
                                                                                                                  '1-st map: total under 25.5': '2.55'},
          'd13 - tiger(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)': {'1-st map: d13 will win': '2.80',
                                                                                                                              '1-st map: handicap d13 +3.5': '1.95',
                                                                                                                              '1-st map: handicap tiger -3.5': '1.80',
                                                                                                                              '1-st map: tiger will win': '1.40',
                                                                                                                              '1-st map: total over 26.5': '1.92',
                                                                                                                              '1-st map: total under 26.5': '1.82'},
          'divine vendetta - tyloo(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-perfect-world-asia-league)': {'1-st map: divine vendetta will win': '3.75',
                                                                                                                                          '1-st map: handicap divine vendetta +4.5': '2.01',
                                                                                                                                          '1-st map: handicap tyloo -4.5': '1.75',
                                                                                                                                          '1-st map: total over 25.5': '1.80',
                                                                                                                                          '1-st map: total under 25.5': '1.95',
                                                                                                                                          '1-st map: tyloo will win': '1.25'},
          'eternal - imperium(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-winners-league-na-main-division)': {'eternal will win': '1.80',
                                                                                                                                           'imperium will win': '1.95'},
          'ex-polar ace - mythic(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-invite-league)': {'1-st map: ex-polar ace will win': '3.30',
                                                                                                                                   '1-st map: handicap ex-polar ace +4.5': '1.90',
                                                                                                                                   '1-st map: handicap mythic -4.5': '1.85',
                                                                                                                                   '1-st map: mythic will win': '1.30',
                                                                                                                                   '1-st map: total over 26.5': '2.00',
                                                                                                                                   '1-st map: total under 26.5': '1.76'},
          'exploit - unicorns of love(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-betano-masters-eu)': {'exploit will win': '4.00',
                                                                                                                                     'unicorns of love will win': '1.22'},
          'furious - malvinas(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-lvp-unity-ar)': {'furious will win': '3.75',
                                                                                                                        'malvinas will win': '1.25'},
          'global - knockturnal(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esl-india-premiership)': {'global will win': '1.12',
                                                                                                                                   'knockturnal will win': '5.66'},
          'honoris - wizards(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)': {'1-st map: handicap honoris -4.5': '2.48',
                                                                                                                       '1-st map: handicap wizards +4.5': '1.50',
                                                                                                                       '1-st map: total over 25.5': '1.55',
                                                                                                                       '1-st map: total under 25.5': '2.35'},
          'illuminar - wisla krakow(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)': {'1-st map: handicap illuminar -4.5': '2.35',
                                                                                                                              '1-st map: handicap wisla krakow +4.5': '1.55',
                                                                                                                              '1-st map: total over 25.5': '1.57',
                                                                                                                              '1-st map: total under 25.5': '2.31'},
          'ldlc - lilmix(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)': {'1-st map: handicap ldlc -3.5': '1.92',
                                                                                                                       '1-st map: handicap lilmix +3.5': '1.82',
                                                                                                                       '1-st map: ldlc will win': '1.50',
                                                                                                                       '1-st map: lilmix will win': '2.48',
                                                                                                                       '1-st map: total over 26.5': '1.87',
                                                                                                                       '1-st map: total under 26.5': '1.87'},
          'levadia - zawisza bydgoszcz(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-winners-league-eu-main-division)': {'levadia will win': '2.00',
                                                                                                                                                    'zawisza bydgoszcz will win': '1.76'},
          'levelup - syman(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)': {'1-st map: handicap levelup +5.5': '1.60',
                                                                                                                     '1-st map: handicap syman -5.5': '2.25',
                                                                                                                     '1-st map: total over 25.5': '1.70',
                                                                                                                     '1-st map: total under 25.5': '2.08'},
          'mustang crew - nosurrendergg(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-main-division)': {'mustang crew will win': '1.40',
                                                                                                                                           'nosurrendergg will win': '2.82'},
          'new england whalers - oceanus(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-invite-league)': {'1-st map: handicap new england whalers -3.5': '1.80',
                                                                                                                                           '1-st map: handicap oceanus +3.5': '1.95',
                                                                                                                                           '1-st map: new england whalers will win': '1.40',
                                                                                                                                           '1-st map: oceanus will win': '2.80',
                                                                                                                                           '1-st map: total over 26.5': '1.92',
                                                                                                                                           '1-st map: total under 26.5': '1.82'},
          'nexus - the dice(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)': {'1-st map: handicap nexus -3.5': '1.87',
                                                                                                                          '1-st map: handicap the dice +3.5': '1.87',
                                                                                                                          '1-st map: nexus will win': '1.45',
                                                                                                                          '1-st map: the dice will win': '2.62',
                                                                                                                          '1-st map: total over 26.5': '1.90',
                                                                                                                          '1-st map: total under 26.5': '1.85'},
          'nightraid - purple haze(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)': {'1-st map: handicap nightraid +3.5': '2.35',
                                                                                                                               '1-st map: handicap purple haze -3.5': '1.55',
                                                                                                                               '1-st map: total over 27.5': '2.37',
                                                                                                                               '1-st map: total under 27.5': '1.54'},
          'nightraid - veterani(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)': {'1-st map: handicap nightraid +5.5': '1.60',
                                                                                                                            '1-st map: handicap veterani -5.5': '2.25',
                                                                                                                            '1-st map: total over 25.5': '1.57',
                                                                                                                            '1-st map: total under 25.5': '2.31'},
          'nightraid - yung trappers(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)': {'1-st map: handicap nightraid +2.5': '1.47',
                                                                                                                                 '1-st map: handicap yung trappers -2.5': '2.55',
                                                                                                                                 '1-st map: total over 25.5': '1.47',
                                                                                                                                 '1-st map: total under 25.5': '2.57'},
          'penta - sinners(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-main-division)': {'penta will win': '3.04',
                                                                                                                              'sinners will win': '1.35'},
          'planetkey dynamics - rhein-neckar(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-99liga)': {'draw will win': '2.10',
                                                                                                                                 'planetkey dynamics will win': '4.20',
                                                                                                                                 'rhein-neckar will win': '2.48'},
          'purple haze - veterani(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)': {'1-st map: handicap purple haze -4.5': '2.25',
                                                                                                                              '1-st map: handicap veterani +4.5': '1.60',
                                                                                                                              '1-st map: total over 25.5': '1.47',
                                                                                                                              '1-st map: total under 25.5': '2.57'},
          'purple haze - yung trappers(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)': {'1-st map: handicap purple haze -3.5': '1.55',
                                                                                                                                   '1-st map: handicap yung trappers +3.5': '2.35',
                                                                                                                                   '1-st map: total over 27.5': '2.37',
                                                                                                                                   '1-st map: total under 27.5': '1.54'},
          'reckoning - wolf(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esl-india-premiership)': {'reckoning will win': '1.18',
                                                                                                                               'wolf will win': '4.50'},
          'sangal - tikitakan(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)': {'1-st map: handicap sangal -3.5': '1.92',
                                                                                                                            '1-st map: handicap tikitakan +3.5': '1.82',
                                                                                                                            '1-st map: sangal will win': '1.50',
                                                                                                                            '1-st map: tikitakan will win': '2.48',
                                                                                                                            '1-st map: total over 26.5': '1.87',
                                                                                                                            '1-st map: total under 26.5': '1.87'},
          'saw - secret(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-advanced)': {'1-st map: handicap saw -3.5': '1.92',
                                                                                                                      '1-st map: handicap secret +3.5': '1.82',
                                                                                                                      '1-st map: saw will win': '1.50',
                                                                                                                      '1-st map: secret will win': '2.48',
                                                                                                                      '1-st map: total over 26.5': '1.87',
                                                                                                                      '1-st map: total under 26.5': '1.87'},
          'veterani - yung trappers(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esports-battle)': {'1-st map: handicap veterani -5.5': '2.11',
                                                                                                                                '1-st map: handicap yung trappers +5.5': '1.68',
                                                                                                                                '1-st map: total over 25.5': '1.57',
                                                                                                                                '1-st map: total under 25.5': '2.31'}}}
