sport = {'csgo': {'2020-01-01 08:00:00: any other': [{'winneryes': ['20.0(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-01-01 08:00:00: device': [{'winneryes': ['17.5(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-01-01 08:00:00: electronic': [{'winneryes': ['20.0(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-01-01 08:00:00: elige': [{'winneryes': ['25.0(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-01-01 08:00:00: magisk': [{'winneryes': ['25.0(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-01-01 08:00:00: niko': [{'winneryes': ['8.00(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-01-01 08:00:00: ropz': [{'winneryes': ['35.0(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-01-01 08:00:00: s1mple': [{'winneryes': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-01-01 08:00:00: woxic': [{'winneryes': ['40.0(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-01-01 08:00:00: xantares': [{'winneryes': ['45.0(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-01-01 08:00:00: zywoo': [{'winneryes': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-counter-strike-hltv-top-20-players-of-2020)']}],
          '2020-08-02 11:00:00: nordavind - gamerlegion': [{'1-st map: gamerlegion handicap +2.5 rounds': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: gamerlegion handicap +3.5 rounds': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: gamerlegion handicap +4.5 rounds': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: gamerlegion will win': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: nordavind handicap -2.5 rounds': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: nordavind handicap -3.5 rounds': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: nordavind handicap -4.5 rounds': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: nordavind will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: total rounds over 25.5': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: total rounds over 26.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: total rounds over 27.5': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: total rounds under 25.5': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: total rounds under 26.5': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '1-st map: total rounds under 27.5': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: gamerlegion handicap +2.5 rounds': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: gamerlegion handicap +3.5 rounds': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: gamerlegion handicap +4.5 rounds': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: gamerlegion will win': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: nordavind handicap -2.5 rounds': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: nordavind handicap -3.5 rounds': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: nordavind handicap -4.5 rounds': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: nordavind will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: total rounds over 25.5': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: total rounds over 26.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: total rounds over 27.5': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: total rounds under 25.5': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: total rounds under 26.5': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            '2-nd map: total rounds under 27.5': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            'gamerlegion handicap +1.5 maps': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            'gamerlegion will win': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            'nordavind handicap -1.5 maps': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            'nordavind will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            'total maps over 2.5': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                            'total maps under 2.5': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)']}],
          '2020-08-02 14:00:00: honoris - tikitakan': [{'1-st map: honoris handicap +2.5 rounds': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: honoris handicap +3.5 rounds': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: honoris handicap -2.5 rounds': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: honoris will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: tikitakan handicap +2.5 rounds': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: tikitakan handicap -2.5 rounds': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: tikitakan handicap -3.5 rounds': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: tikitakan will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: total rounds over 25.5': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: total rounds over 26.5': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: total rounds over 27.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: total rounds under 25.5': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: total rounds under 26.5': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '1-st map: total rounds under 27.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: honoris handicap +2.5 rounds': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: honoris handicap +3.5 rounds': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: honoris handicap -2.5 rounds': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: honoris will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: tikitakan handicap +2.5 rounds': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: tikitakan handicap -2.5 rounds': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: tikitakan handicap -3.5 rounds': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: tikitakan will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: total rounds over 25.5': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: total rounds over 26.5': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: total rounds over 27.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: total rounds under 25.5': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: total rounds under 26.5': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        '2-nd map: total rounds under 27.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        'honoris handicap +1.5 maps': ['1.38(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        'honoris will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        'tikitakan handicap -1.5 maps': ['2.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        'tikitakan will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        'total maps over 2.5': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                        'total maps under 2.5': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)']}],
          '2020-08-02 14:00:00: ignis - crnb': [{'crnb will win': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-utage-japan-league)'], 'ignis will win': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-utage-japan-league)']}],
          '2020-08-02 14:00:00: lilmix - 9ine': [{'9ine will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-tob-cup)'], 'lilmix will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-tob-cup)']}],
          '2020-08-02 17:00:00: exploit - ftw': [{'exploit will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-omen-wgr-challenge)'], 'ftw will win': ['2.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-omen-wgr-challenge)']}],
          '2020-08-02 17:00:00: natus vincere junior - alternate attax': [{'1-st map: alternate attax handicap -2.5 rounds': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: alternate attax handicap -3.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: alternate attax handicap -4.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: alternate attax will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: natus vincere junior handicap +2.5 rounds': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: natus vincere junior handicap +3.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: natus vincere junior handicap +4.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: natus vincere junior will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: total rounds over 25.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: total rounds over 26.5': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: total rounds over 27.5': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: total rounds under 25.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: total rounds under 26.5': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '1-st map: total rounds under 27.5': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: alternate attax handicap -2.5 rounds': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: alternate attax handicap -3.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: alternate attax handicap -4.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: alternate attax will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: natus vincere junior handicap +2.5 rounds': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: natus vincere junior handicap +3.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: natus vincere junior handicap +4.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: natus vincere junior will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: total rounds over 25.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: total rounds over 26.5': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: total rounds over 27.5': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: total rounds under 25.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: total rounds under 26.5': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           '2-nd map: total rounds under 27.5': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           'alternate attax handicap -1.5 maps': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           'alternate attax will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           'natus vincere junior handicap +1.5 maps': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           'natus vincere junior will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           'total maps over 2.5': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                           'total maps under 2.5': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)']}],
          '2020-08-02 20:00:00: gambit youngsters - bluejays': [{'1-st map: bluejays handicap +5.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: bluejays handicap +6.5 rounds': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: bluejays handicap +7.5 rounds': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: bluejays will win': ['4.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: gambit youngsters handicap -5.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: gambit youngsters handicap -6.5 rounds': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: gambit youngsters handicap -7.5 rounds': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: gambit youngsters will win': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: total rounds over 25.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: total rounds over 26.5': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: total rounds over 27.5': ['2.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: total rounds under 25.5': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: total rounds under 26.5': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '1-st map: total rounds under 27.5': ['1.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: bluejays handicap +5.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: bluejays handicap +6.5 rounds': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: bluejays handicap +7.5 rounds': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: bluejays will win': ['4.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: gambit youngsters handicap -5.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: gambit youngsters handicap -6.5 rounds': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: gambit youngsters handicap -7.5 rounds': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: gambit youngsters will win': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: total rounds over 25.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: total rounds over 26.5': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: total rounds over 27.5': ['2.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: total rounds under 25.5': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: total rounds under 26.5': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 '2-nd map: total rounds under 27.5': ['1.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 'bluejays handicap +1.5 maps': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 'bluejays will win': ['6.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 'gambit youngsters handicap -1.5 maps': ['1.44(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 'gambit youngsters will win': ['1.10(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 'total maps over 2.5': ['2.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                                                 'total maps under 2.5': ['1.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)']}],
          '2020-08-02 21:00:00: plan-b - cowana ': [{'cowana  will win': ['2.43(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-99liga)'], 'plan-b will win': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-99liga)']}],
          '2020-08-02 22:00:00: chaos - rbg': [{'1-st map: chaos handicap -5.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                '1-st map: chaos will win': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                '1-st map: rbg handicap +5.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                '1-st map: rbg will win': ['4.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                '1-st map: total rounds over 25.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                '1-st map: total rounds under 25.5': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                'chaos handicap -1.5 maps': ['1.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                'chaos will win': ['1.10(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                'rbg handicap +1.5 maps': ['2.74(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                'rbg will win': ['6.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                'total maps over 2.5': ['2.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                'total maps under 2.5': ['1.37(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)']}],
          '2020-08-02 22:00:00: levitate - yeah': [{'1-st map: levitate handicap +3.5 rounds': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    '1-st map: levitate will win': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    '1-st map: total rounds over 26.5': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    '1-st map: total rounds under 26.5': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    '1-st map: yeah handicap -3.5 rounds': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    '1-st map: yeah will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    'levitate handicap +1.5 maps': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    'levitate will win': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    'total maps over 2.5': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    'total maps under 2.5': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    'yeah handicap -1.5 maps': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                    'yeah will win': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)']}],
          '2020-08-02 22:00:00: new england whalers - teamone': [{'1-st map: new england whalers handicap +2.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  '1-st map: new england whalers will win': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  '1-st map: teamone handicap -2.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  '1-st map: teamone will win': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  '1-st map: total rounds over 26.5': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  '1-st map: total rounds under 26.5': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  'new england whalers handicap +1.5 maps': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  'new england whalers will win': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  'teamone handicap -1.5 maps': ['3.45(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  'teamone will win': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  'total maps over 2.5': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)'],
                                                                  'total maps under 2.5': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-mythic-summer-cup)']}],
          '2020-08-02 22:00:00: sinister5 - online kingdom': [{'online kingdom will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-umzansi-league)'],
                                                               'sinister5 will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-umzansi-league)']}],
          '2020-08-03 00:00:00: pain - boom': [{'1-st map: boom handicap -2.5 rounds': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: boom handicap -3.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: boom handicap -4.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: boom will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: pain handicap +2.5 rounds': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: pain handicap +3.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: pain handicap +4.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: pain will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: total rounds over 25.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: total rounds over 26.5': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: total rounds over 27.5': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: total rounds under 25.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: total rounds under 26.5': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '1-st map: total rounds under 27.5': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: boom handicap -2.5 rounds': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: boom handicap -3.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: boom handicap -4.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: boom will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: pain handicap +2.5 rounds': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: pain handicap +3.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: pain handicap +4.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: pain will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: total rounds over 25.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: total rounds over 26.5': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: total rounds over 27.5': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: total rounds under 25.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: total rounds under 26.5': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                '2-nd map: total rounds under 27.5': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                'boom handicap -1.5 maps': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                'boom will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                'pain handicap +1.5 maps': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                'pain will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                'total maps over 2.5': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)'],
                                                'total maps under 2.5': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-gamers-club)']}],
          '2020-08-03 10:00:00: avez - izako boars': [{'1-st map: avez handicap -2.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: avez handicap -3.5 rounds': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: avez handicap -4.5 rounds': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: avez will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: izako boars handicap +2.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: izako boars handicap +3.5 rounds': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: izako boars handicap +4.5 rounds': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: izako boars will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: total rounds over 25.5': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: total rounds over 26.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: total rounds over 27.5': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: total rounds under 25.5': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: total rounds under 26.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '1-st map: total rounds under 27.5': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: avez handicap -2.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: avez handicap -3.5 rounds': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: avez handicap -4.5 rounds': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: avez will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: izako boars handicap +2.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: izako boars handicap +3.5 rounds': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: izako boars handicap +4.5 rounds': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: izako boars will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: total rounds over 25.5': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: total rounds over 26.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: total rounds over 27.5': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: total rounds under 25.5': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: total rounds under 26.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       '2-nd map: total rounds under 27.5': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       'avez handicap -1.5 maps': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       'avez will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       'izako boars handicap +1.5 maps': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       'izako boars will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       'total maps over 2.5': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                       'total maps under 2.5': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)']}],
          '2020-08-03 10:00:00: syman - tikitakan': [{'1-st map: syman handicap +2.5 rounds': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: syman handicap -2.5 rounds': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: syman handicap -3.5 rounds': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: syman will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: tikitakan handicap +2.5 rounds': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: tikitakan handicap +3.5 rounds': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: tikitakan handicap -2.5 rounds': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: tikitakan will win': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: total rounds over 25.5': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: total rounds over 26.5': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: total rounds over 27.5': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: total rounds under 25.5': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: total rounds under 26.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '1-st map: total rounds under 27.5': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: syman handicap +2.5 rounds': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: syman handicap -2.5 rounds': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: syman handicap -3.5 rounds': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: syman will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: tikitakan handicap +2.5 rounds': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: tikitakan handicap +3.5 rounds': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: tikitakan handicap -2.5 rounds': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: tikitakan will win': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: total rounds over 25.5': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: total rounds over 26.5': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: total rounds over 27.5': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: total rounds under 25.5': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: total rounds under 26.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      '2-nd map: total rounds under 27.5': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      'syman handicap -1.5 maps': ['2.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      'syman will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      'tikitakan handicap +1.5 maps': ['1.43(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      'tikitakan will win': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      'total maps over 2.5': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                      'total maps under 2.5': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)']}],
          '2020-08-03 13:00:00: gambit youngsters - alternate attax': [{'1-st map: alternate attax handicap +2.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: alternate attax handicap +3.5 rounds': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: alternate attax handicap +4.5 rounds': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: alternate attax will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: gambit youngsters handicap -2.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: gambit youngsters handicap -3.5 rounds': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: gambit youngsters handicap -4.5 rounds': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: gambit youngsters will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: total rounds over 25.5': ['1.58(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: total rounds over 26.5': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: total rounds over 27.5': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: total rounds under 25.5': ['2.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: total rounds under 26.5': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '1-st map: total rounds under 27.5': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: alternate attax handicap +2.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: alternate attax handicap +3.5 rounds': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: alternate attax handicap +4.5 rounds': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: alternate attax will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: gambit youngsters handicap -2.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: gambit youngsters handicap -3.5 rounds': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: gambit youngsters handicap -4.5 rounds': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: gambit youngsters will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: total rounds over 25.5': ['1.58(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: total rounds over 26.5': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: total rounds over 27.5': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: total rounds under 25.5': ['2.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: total rounds under 26.5': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        '2-nd map: total rounds under 27.5': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        'alternate attax handicap +1.5 maps': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        'alternate attax will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        'gambit youngsters handicap -1.5 maps': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        'gambit youngsters will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        'total maps over 2.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                                        'total maps under 2.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)']}],
          '2020-08-03 13:00:00: ldlc - sg.pro': [{'1-st map: ldlc handicap -2.5 rounds': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: ldlc handicap -3.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: ldlc handicap -4.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: ldlc will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: sg.pro handicap +2.5 rounds': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: sg.pro handicap +3.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: sg.pro handicap +4.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: sg.pro will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: total rounds over 25.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: total rounds over 26.5': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: total rounds over 27.5': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: total rounds under 25.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: total rounds under 26.5': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '1-st map: total rounds under 27.5': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: ldlc handicap -2.5 rounds': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: ldlc handicap -3.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: ldlc handicap -4.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: ldlc will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: sg.pro handicap +2.5 rounds': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: sg.pro handicap +3.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: sg.pro handicap +4.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: sg.pro will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: total rounds over 25.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: total rounds over 26.5': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: total rounds over 27.5': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: total rounds under 25.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: total rounds under 26.5': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  '2-nd map: total rounds under 27.5': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  'ldlc handicap -1.5 maps': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  'ldlc will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  'sg.pro handicap +1.5 maps': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  'sg.pro will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  'total maps over 2.5': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)'],
                                                  'total maps under 2.5': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-nine-to-five)']}],
          '2020-08-03 15:30:00: reckoning - underdogs': [{'reckoning will win': ['1.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-rise-of-legion-in)'],
                                                          'underdogs will win': ['3.71(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-rise-of-legion-in)']}],
          '2020-08-03 17:00:00: skilled enough - for the win': [{'for the win will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esn-league)'],
                                                                 'skilled enough will win': ['3.33(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esn-league)']}],
          '2020-08-03 20:00:00: granit - revenge': [{'granit will win': ['1.36(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esn-league)'], 'revenge will win': ['3.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esn-league)']}],
          '2020-08-03 21:30:00: dr. pepper - lowlandlions': [{'dr. pepper will win': ['2.63(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esn-league)'],
                                                              'lowlandlions will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esn-league)']}],
          '2020-08-03 21:30:00: granit - excellency': [{'excellency will win': ['2.63(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-main-division)'],
                                                        'granit will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-esea-eu-main-division)']}],
          '2020-08-08 11:00:00: big': [{'winneryes': ['3.75(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-eu)']}],
          '2020-08-08 11:00:00: complexity': [{'winneryes': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-eu)']}],
          '2020-08-08 11:00:00: endpoint': [{'winneryes': ['26.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-eu)']}],
          '2020-08-08 11:00:00: forze': [{'winneryes': ['9.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-eu)']}],
          '2020-08-08 11:00:00: heroic': [{'winneryes': ['7.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-eu)']}],
          '2020-08-08 11:00:00: mad lions': [{'winneryes': ['7.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-eu)']}],
          '2020-08-08 11:00:00: og': [{'winneryes': ['6.50(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-eu)']}],
          '2020-08-08 11:00:00: spirit': [{'winneryes': ['9.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-eu)']}],
          '2020-08-08 14:00:00: dignitas - giants': [{'1-st map: dignitas handicap -3.5 rounds': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: dignitas handicap -4.5 rounds': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: dignitas handicap -5.5 rounds': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: giants handicap +3.5 rounds': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: giants handicap +4.5 rounds': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: giants handicap +5.5 rounds': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds over 25.5': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds over 26.5': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds over 27.5': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds under 25.5': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds under 26.5': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds under 27.5': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      'dignitas will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      'giants will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)']}],
          '2020-08-08 15:30:00: secret - syman': [{'1-st map: secret handicap +2.5 rounds': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: secret handicap +3.5 rounds': ['1.58(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: secret handicap -2.5 rounds': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: syman handicap +2.5 rounds': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: syman handicap -2.5 rounds': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: syman handicap -3.5 rounds': ['2.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: total rounds over 25.5': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: total rounds over 26.5': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: total rounds over 27.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: total rounds under 25.5': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: total rounds under 26.5': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   '1-st map: total rounds under 27.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   'secret will win': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                   'syman will win': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)']}],
          '2020-08-08 17:00:00: forze - nordavind': [{'1-st map: forze handicap -2.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: forze handicap -3.5 rounds': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: forze handicap -4.5 rounds': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: nordavind handicap +2.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: nordavind handicap +3.5 rounds': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: nordavind handicap +4.5 rounds': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds over 25.5': ['1.58(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds over 26.5': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds over 27.5': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds under 25.5': ['2.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds under 26.5': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      '1-st map: total rounds under 27.5': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      'forze will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                      'nordavind will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)']}],
          '2020-08-08 18:00:00: 100 thieves': [{'winneryes': ['7.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-na)']}],
          '2020-08-08 18:00:00: cloud9': [{'winneryes': ['11.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-na)']}],
          '2020-08-08 18:00:00: evil geniuses': [{'winneryes': ['4.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-na)']}],
          '2020-08-08 18:00:00: furia': [{'winneryes': ['4.50(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-na)']}],
          '2020-08-08 18:00:00: gen.g': [{'winneryes': ['7.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-na)']}],
          '2020-08-08 18:00:00: liquid': [{'winneryes': ['4.50(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-na)']}],
          '2020-08-08 18:00:00: triumph': [{'winneryes': ['17.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-na)']}],
          '2020-08-08 18:00:00: ze pug godz': [{'winneryes': ['26.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-dreamhack-open-na)']}],
          '2020-08-08 18:30:00: endpoint - movistar riders': [{'1-st map: endpoint handicap +2.5 rounds': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: endpoint handicap -2.5 rounds': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: endpoint handicap -3.5 rounds': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: movistar riders handicap +2.5 rounds': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: movistar riders handicap +3.5 rounds': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: movistar riders handicap -2.5 rounds': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: total rounds over 25.5': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: total rounds over 26.5': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: total rounds over 27.5': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: total rounds under 25.5': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: total rounds under 26.5': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               '1-st map: total rounds under 27.5': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               'endpoint will win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                               'movistar riders will win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)']}],
          '2020-08-08 21:00:00: teamone - cloud9': [{'1-st map: cloud9 handicap -4.5 rounds': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                     '1-st map: teamone handicap +4.5 rounds': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                     '1-st map: total rounds over 26.5': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                     '1-st map: total rounds under 26.5': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                     'cloud9 will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                     'teamone will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)']}],
          '2020-08-08 22:30:00: ze pug godz - yeah': [{'1-st map: total rounds over 26.5': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                       '1-st map: total rounds under 26.5': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                       '1-st map: yeah handicap +3.5 rounds': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                       '1-st map: ze pug godz handicap -3.5 rounds': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                       'yeah will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                       'ze pug godz will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)']}],
          '2020-08-09 00:00:00: levitate - chaos': [{'1-st map: chaos handicap -5.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                     '1-st map: levitate handicap +5.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                     '1-st map: total rounds over 25.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                     '1-st map: total rounds under 25.5': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                     'chaos will win': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)'],
                                                     'levitate will win': ['4.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-na-qualifier)']}],
          '2020-08-09 15:30:00: ago - illuminar': [{'1-st map: ago handicap +2.5 rounds': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: ago handicap -2.5 rounds': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: ago handicap -3.5 rounds': ['2.30(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: illuminar handicap +2.5 rounds': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: illuminar handicap +3.5 rounds': ['1.58(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: illuminar handicap -2.5 rounds': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: total rounds over 25.5': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: total rounds over 26.5': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: total rounds over 27.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: total rounds under 25.5': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: total rounds under 26.5': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    '1-st map: total rounds under 27.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    'ago will win': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                    'illuminar will win': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)']}],
          '2020-08-09 18:30:00: nemiga - c0ntact': [{'1-st map: c0ntact handicap +2.5 rounds': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: c0ntact handicap +3.5 rounds': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: c0ntact handicap -2.5 rounds': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: nemiga handicap +2.5 rounds': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: nemiga handicap -2.5 rounds': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: nemiga handicap -3.5 rounds': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: total rounds over 25.5': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: total rounds over 26.5': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: total rounds over 27.5': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: total rounds under 25.5': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: total rounds under 26.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     '1-st map: total rounds under 27.5': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     'c0ntact will win': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)'],
                                                     'nemiga will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-funspark-ulti-eu-qualifier)']}],
          '2020-08-18 18:00:00: 100 thieves': [{'winneryes': ['7.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-na)']}],
          '2020-08-18 18:00:00: cloud9': [{'winneryes': ['11.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-na)']}],
          '2020-08-18 18:00:00: evil geniuses': [{'winneryes': ['4.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-na)']}],
          '2020-08-18 18:00:00: furia': [{'winneryes': ['5.50(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-na)']}],
          '2020-08-18 18:00:00: gen.g': [{'winneryes': ['7.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-na)']}],
          '2020-08-18 18:00:00: liquid': [{'winneryes': ['5.50(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-na)']}],
          '2020-08-18 18:00:00: mibr': [{'winneryes': ['9.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-na)']}],
          '2020-08-18 18:00:00: triumph': [{'winneryes': ['17.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-na)']}],
          '2020-08-23 11:00:00: astralis': [{'winneryes': ['9.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: big': [{'winneryes': ['6.50(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: complexity': [{'winneryes': ['26.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: faze': [{'winneryes': ['11.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: fnatic': [{'winneryes': ['7.00(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: g2': [{'winneryes': ['6.50(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: godsent': [{'winneryes': ['51.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: heretics': [{'winneryes': ['101.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: heroic': [{'winneryes': ['34.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: mad lions': [{'winneryes': ['34.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: mousesports': [{'winneryes': ['17.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: natus vincere': [{'winneryes': ['5.50(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: nip': [{'winneryes': ['13.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: og': [{'winneryes': ['26.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: sprout': [{'winneryes': ['151.0(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}],
          '2020-08-23 11:00:00: vitality': [{'winneryes': ['5.50(parimatch - https://www.parimatch.com/en/sport/kibersport/itogi-counter-strike-esl-one-cologne-eu)']}]}}
