sport = {'csgo': {'01/0811:00: hard legion - gamerlegion': [{}],
          '01/0811:00: syman - illuminar': [{'1-st map: illuminar handicap +2.5 rounds': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: illuminar handicap +3.5 rounds': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: illuminar handicap +4.5 rounds': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: syman handicap -2.5 rounds': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: syman handicap -3.5 rounds': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: syman handicap -4.5 rounds': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: total rounds over 25.5': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: total rounds over 26.5': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: total rounds over 27.5': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: total rounds under 25.5': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: total rounds under 26.5': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             '1-st map: total rounds under 27.5': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             'illuminar will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)'],
                                             'syman will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/counter-strike-eden-arena-malta-vibes)']}],
          '01/0816:00: natus vincere 2020 - natus vincere 2010': [{}],
          '01/0817:00: natus vincere 2020 - natus vincere 2010': [{}],
          '01/0818:00: alternate attax - budapest five': [{}],
          '01/0818:00: natus vincere 2020 - natus vincere 2010': [{}],
          '01/0819:00: natus vincere 2020 - natus vincere 2010': [{}],
          '01/0820:00: natus vincere 2020 - natus vincere 2010': [{}],
          '01/0821:00: natus vincere 2020 - natus vincere 2010': [{}],
          '29/0722:40: tikitakan - gambit youngsters': [{}],
          '30/0708:30: bmth - gameinside': [{}],
          '30/0708:30: unknown gods - royalty': [{}],
          '30/0710:30: bmth - royalty': [{}],
          '30/0710:30: gameinside - unknown gods': [{}],
          '30/0712:30: bmth - unknown gods': [{}],
          '30/0712:30: gameinside - royalty': [{}],
          '30/0715:30: night raid - purple haze': [{}],
          '30/0715:30: veterani - libertatem': [{}],
          '30/0716:00: global - lvl0': [{}],
          '30/0717:30: night raid - veterani': [{}],
          '30/0717:30: purple haze - libertatem': [{}],
          '30/0719:00: cr4zy - sg.pro': [{}],
          '30/0719:00: nordavind - honoris': [{}],
          '30/0719:00: sinners - excellency': [{}],
          '30/0719:30: night raid - libertatem': [{}],
          '30/0719:30: veterani - purple haze': [{}],
          '30/0721:30: project 5 - granit': [{}],
          '31/0716:00: animehs  - phoenix': [{}],
          '31/0716:00: ex-adaptation - nexus': [{}],
          '31/0719:00: avez - apeks': [{}],
          '31/0719:00: gambit youngsters - natus vincere junior': [{}]}}
