sport = {'lol': {'7more7 pompa - piratesports': {'1-st map: 7more7 pompa will win': ['1.24(ggbet - https://gg.bet/en/betting/match/7more7-pompa-team-vs-piratesports-14-07)'],
                                         '1-st map: piratesports will win': ['3.79(ggbet - https://gg.bet/en/betting/match/7more7-pompa-team-vs-piratesports-14-07)'],
                                         '7more7 pompa will win': ['1.24(ggbet - https://gg.bet/en/betting/match/7more7-pompa-team-vs-piratesports-14-07)'],
                                         'piratesports will win': ['3.87(ggbet - https://gg.bet/en/betting/match/7more7-pompa-team-vs-piratesports-14-07)']},
         'bilibili - dominus': {'1-st map: bilibili first blood': ['1.83(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '1-st map: bilibili will win': ['1.63(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '1-st map: dominus first blood': ['1.91(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '1-st map: dominus will win': ['2.19(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '2-nd map: bilibili first blood': ['1.83(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '2-nd map: bilibili will win': ['1.63(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '2-nd map: dominus first blood': ['1.91(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '2-nd map: dominus will win': ['2.19(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'bilibili handicap +1.5 maps': ['1.19(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'bilibili handicap -1.5 maps': ['2.6(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'bilibili will win': ['1.55(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'correct score 0-2': ['4.36(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'correct score 1-2': ['4.3(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'correct score 2-0': ['2.59(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'correct score 2-1': ['3.34(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'dominus handicap +1.5 maps': ['1.46(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'dominus handicap -1.5 maps': ['4.35(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'dominus will win': ['2.38(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'total maps even': ['1.73(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'total maps odd': ['2.03(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'total maps over 2.5': ['2.03(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)'],
                                'total maps under 2.5': ['1.73(ggbet - https://gg.bet/en/betting/match/bilibili-gaming-vs-dominus-esports-18-07)']},
         'bilibili - we': {'1-st map: bilibili first blood': ['1.96(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '1-st map: bilibili will win': ['2.66(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '1-st map: we first blood': ['1.79(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '1-st map: we will win': ['1.44(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '2-nd map: bilibili first blood': ['1.96(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '2-nd map: bilibili will win': ['2.66(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '2-nd map: we first blood': ['1.79(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           '2-nd map: we will win': ['1.44(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'bilibili handicap +1.5 maps': ['1.71(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'bilibili handicap -1.5 maps': ['5.91(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'bilibili will win': ['3.19(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'correct score 0-2': ['2.06(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'correct score 1-2': ['3.22(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'correct score 2-0': ['5.95(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'correct score 2-1': ['5.37(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'total maps even': ['1.63(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'total maps odd': ['2.19(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'total maps over 2.5': ['2.19(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'total maps under 2.5': ['1.63(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'we handicap +1.5 maps': ['1.11(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'we handicap -1.5 maps': ['2.06(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)'],
                           'we will win': ['1.33(ggbet - https://gg.bet/en/betting/match/team-we-vs-bilibili-gaming-22-07)']},
         'edward - lgd': {'1-st map: edward first blood': ['1.89(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '1-st map: edward will win': ['2.02(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '1-st map: lgd first blood': ['1.85(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '1-st map: lgd will win': ['1.74(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '2-nd map: edward first blood': ['1.89(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '2-nd map: edward will win': ['2.02(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '2-nd map: lgd first blood': ['1.85(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '2-nd map: lgd will win': ['1.74(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'correct score 0-2': ['2.92(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'correct score 1-2': ['3.48(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'correct score 2-0': ['3.8(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'correct score 2-1': ['3.95(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'edward handicap +1.5 maps': ['1.37(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'edward handicap -1.5 maps': ['3.79(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'edward will win': ['2.1(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'lgd handicap +1.5 maps': ['1.24(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'lgd handicap -1.5 maps': ['2.94(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'lgd will win': ['1.7(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'total maps even': ['1.76(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'total maps odd': ['1.99(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'total maps over 2.5': ['1.99(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)'],
                          'total maps under 2.5': ['1.76(ggbet - https://gg.bet/en/betting/match/edward-gaming-vs-lgd-gaming-17-07)']},
         'edward - vici': {'1-st map: edward first blood': ['1.88(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '1-st map: edward will win': ['1.94(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '1-st map: vici first blood': ['1.86(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '1-st map: vici will win': ['1.8(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '2-nd map: edward first blood': ['1.88(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '2-nd map: edward will win': ['1.94(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '2-nd map: vici first blood': ['1.86(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           '2-nd map: vici will win': ['1.8(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'correct score 0-2': ['3.1(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'correct score 1-2': ['3.57(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'correct score 2-0': ['3.55(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'correct score 2-1': ['3.81(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'edward handicap +1.5 maps': ['1.34(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'edward handicap -1.5 maps': ['3.54(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'edward will win': ['1.99(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'total maps even': ['1.77(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'total maps odd': ['1.98(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'total maps over 2.5': ['1.98(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'total maps under 2.5': ['1.77(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'vici handicap +1.5 maps': ['1.27(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'vici handicap -1.5 maps': ['3.09(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)'],
                           'vici will win': ['1.78(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-edward-gaming-21-07)']},
         'estar - oh my god': {'1-st map: estar first blood': ['1.88(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '1-st map: estar will win': ['1.96(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '1-st map: oh my god first blood': ['1.86(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '1-st map: oh my god will win': ['1.79(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '2-nd map: estar first blood': ['1.88(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '2-nd map: estar will win': ['1.94(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '2-nd map: oh my god first blood': ['1.86(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '2-nd map: oh my god will win': ['1.8(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'correct score 0-2': ['3.09(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'correct score 1-2': ['3.56(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'correct score 2-0': ['3.57(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'correct score 2-1': ['3.82(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'estar handicap +1.5 maps': ['1.34(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'estar handicap -1.5 maps': ['3.54(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'estar will win': ['2(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'oh my god handicap +1.5 maps': ['1.27(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'oh my god handicap -1.5 maps': ['3.09(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'oh my god will win': ['1.77(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'total maps even': ['1.77(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'total maps odd': ['1.98(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'total maps over 2.5': ['1.98(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)'],
                               'total maps under 2.5': ['1.77(ggbet - https://gg.bet/en/betting/match/estar-vs-oh-my-god-15-07)']},
         'estar - rogue warriors': {'1-st map: estar first blood': ['1.81(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '1-st map: estar will win': ['1.51(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '1-st map: rogue warriors first blood': ['1.93(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '1-st map: rogue warriors will win': ['2.45(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '2-nd map: estar first blood': ['1.81(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '2-nd map: estar will win': ['1.51(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '2-nd map: rogue warriors first blood': ['1.93(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '2-nd map: rogue warriors will win': ['2.45(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'correct score 0-2': ['5.23(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'correct score 1-2': ['4.87(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'correct score 2-0': ['2.26(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'correct score 2-1': ['3.24(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'estar handicap +1.5 maps': ['1.14(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'estar handicap -1.5 maps': ['2.27(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'estar will win': ['1.41(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'rogue warriors handicap +1.5 maps': ['1.59(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'rogue warriors handicap -1.5 maps': ['5.19(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'rogue warriors will win': ['2.81(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'total maps even': ['1.68(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'total maps odd': ['2.11(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'total maps over 2.5': ['2.11(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)'],
                                    'total maps under 2.5': ['1.68(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-estar-22-07)']},
         'funplus phoenix - jd': {'1-st map: funplus phoenix first blood': ['1.91(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '1-st map: funplus phoenix will win': ['2.19(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '1-st map: jd first blood': ['1.83(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '1-st map: jd will win': ['1.63(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '2-nd map: funplus phoenix first blood': ['1.91(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '2-nd map: funplus phoenix will win': ['2.19(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '2-nd map: jd first blood': ['1.83(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '2-nd map: jd will win': ['1.63(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'correct score 0-2': ['2.59(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'correct score 1-2': ['3.34(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'correct score 2-0': ['4.36(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'correct score 2-1': ['4.3(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'funplus phoenix handicap +1.5 maps': ['1.46(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'funplus phoenix handicap -1.5 maps': ['4.35(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'funplus phoenix will win': ['2.38(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'jd handicap +1.5 maps': ['1.19(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'jd handicap -1.5 maps': ['2.6(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'jd will win': ['1.55(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'total maps even': ['1.73(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'total maps odd': ['2.03(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'total maps over 2.5': ['2.03(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)'],
                                  'total maps under 2.5': ['1.73(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-funplus-phoenix-19-07)']},
         'funplus phoenix - oh my god': {'1-st map: funplus phoenix first blood': ['1.78(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '1-st map: funplus phoenix will win': ['1.38(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '1-st map: oh my god first blood': ['1.97(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '1-st map: oh my god will win': ['2.9(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '2-nd map: funplus phoenix first blood': ['1.78(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '2-nd map: funplus phoenix will win': ['1.38(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '2-nd map: oh my god first blood': ['1.97(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '2-nd map: oh my god will win': ['2.9(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'correct score 0-2': ['6.75(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'correct score 1-2': ['5.95(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'correct score 2-0': ['1.9(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'correct score 2-1': ['3.24(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'funplus phoenix handicap +1.5 maps': ['1.08(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'funplus phoenix handicap -1.5 maps': ['1.9(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'funplus phoenix will win': ['1.26(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'oh my god handicap +1.5 maps': ['1.84(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'oh my god handicap -1.5 maps': ['6.94(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'oh my god will win': ['3.69(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'total maps even': ['1.58(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'total maps odd': ['2.29(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'total maps over 2.5': ['2.29(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)'],
                                         'total maps under 2.5': ['1.58(ggbet - https://gg.bet/en/betting/match/oh-my-god-vs-funplus-phoenix-21-07)']},
         'funplus phoenix - rogue warriors': {'1-st map: funplus phoenix first blood': ['1.72(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '1-st map: funplus phoenix will win': ['1.16(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '1-st map: rogue warriors first blood': ['2.05(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '1-st map: rogue warriors will win': ['4.81(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '2-nd map: funplus phoenix first blood': ['1.72(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '2-nd map: funplus phoenix will win': ['1.16(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '2-nd map: rogue warriors first blood': ['2.05(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '2-nd map: rogue warriors will win': ['4.81(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'correct score 0-2': ['11.62(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'correct score 1-2': ['10.36(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'correct score 2-0': ['1.37(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'correct score 2-1': ['3.96(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'funplus phoenix handicap +1.5 maps': ['1.02(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'funplus phoenix handicap -1.5 maps': ['1.37(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'funplus phoenix will win': ['1.07(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'rogue warriors handicap +1.5 maps': ['2.94(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'rogue warriors handicap -1.5 maps': ['11.62(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'rogue warriors will win': ['7.67(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'total maps even': ['1.3(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'total maps odd': ['3.32(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'total maps over 2.5': ['3.32(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)'],
                                              'total maps under 2.5': ['1.3(ggbet - https://gg.bet/en/betting/match/rogue-warriors-vs-funplus-phoenix-17-07-1)']},
         'illuminar - k1ck neosurf': {'1-st map: illuminar will win': ['2.35(ggbet - https://gg.bet/en/betting/match/illuminar-gaming-vs-k1ck-neosurf-14-07)'],
                                      '1-st map: k1ck neosurf will win': ['1.55(ggbet - https://gg.bet/en/betting/match/illuminar-gaming-vs-k1ck-neosurf-14-07)'],
                                      'illuminar will win': ['2.36(ggbet - https://gg.bet/en/betting/match/illuminar-gaming-vs-k1ck-neosurf-14-07)'],
                                      'k1ck neosurf will win': ['1.56(ggbet - https://gg.bet/en/betting/match/illuminar-gaming-vs-k1ck-neosurf-14-07)']},
         'invictus - lng': {'1-st map: invictus first blood': ['1.76(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '1-st map: invictus will win': ['1.3(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '1-st map: lng first blood': ['1.99(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '1-st map: lng will win': ['3.32(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '2-nd map: invictus first blood': ['1.76(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '2-nd map: invictus will win': ['1.31(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '2-nd map: lng first blood': ['1.99(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '2-nd map: lng will win': ['3.26(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'correct score 0-2': ['8.03(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'correct score 1-2': ['6.95(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'correct score 2-0': ['1.71(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'correct score 2-1': ['3.32(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'invictus handicap +1.5 maps': ['1.06(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'invictus handicap -1.5 maps': ['1.71(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'invictus will win': ['1.19(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'lng handicap +1.5 maps': ['2.06(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'lng handicap -1.5 maps': ['7.9(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'lng will win': ['4.45(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'total maps even': ['1.5(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'total maps odd': ['2.48(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'total maps over 2.5': ['2.48(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)'],
                            'total maps under 2.5': ['1.5(ggbet - https://gg.bet/en/betting/match/lng-esports-vs-invictus-gaming-16-07)']},
         'invictus - royal never give up': {'1-st map: invictus first blood': ['1.83(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '1-st map: invictus will win': ['1.63(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '1-st map: royal never give up first blood': ['1.91(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '1-st map: royal never give up will win': ['2.19(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '2-nd map: invictus first blood': ['1.83(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '2-nd map: invictus will win': ['1.63(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '2-nd map: royal never give up first blood': ['1.91(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '2-nd map: royal never give up will win': ['2.19(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'correct score 0-2': ['4.36(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'correct score 1-2': ['4.3(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'correct score 2-0': ['2.59(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'correct score 2-1': ['3.34(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'invictus handicap +1.5 maps': ['1.19(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'invictus handicap -1.5 maps': ['2.6(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'invictus will win': ['1.55(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'royal never give up handicap +1.5 maps': ['1.46(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'royal never give up handicap -1.5 maps': ['4.35(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'royal never give up will win': ['2.38(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'total maps even': ['1.73(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'total maps odd': ['2.03(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'total maps over 2.5': ['2.03(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)'],
                                            'total maps under 2.5': ['1.73(ggbet - https://gg.bet/en/betting/match/invictus-gaming-vs-royal-never-give-up-18-07)']},
         'invictus - victory five': {'1-st map: invictus first blood': ['1.9(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '1-st map: invictus will win': ['2.11(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '1-st map: victory five first blood': ['1.84(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '1-st map: victory five will win': ['1.68(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '2-nd map: invictus first blood': ['1.9(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '2-nd map: invictus will win': ['2.11(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '2-nd map: victory five first blood': ['1.84(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     '2-nd map: victory five will win': ['1.68(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'correct score 0-2': ['2.74(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'correct score 1-2': ['3.4(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'correct score 2-0': ['4.08(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'correct score 2-1': ['4.12(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'invictus handicap +1.5 maps': ['1.42(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'invictus handicap -1.5 maps': ['4.11(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'invictus will win': ['2.23(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'total maps even': ['1.75(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'total maps odd': ['2.01(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'total maps over 2.5': ['2.01(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'total maps under 2.5': ['1.75(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'victory five handicap +1.5 maps': ['1.21(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'victory five handicap -1.5 maps': ['2.73(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)'],
                                     'victory five will win': ['1.62(ggbet - https://gg.bet/en/betting/match/victory-five-vs-invictus-gaming-20-07)']},
         'jd - vici': {'1-st map: jd first blood': ['1.8(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '1-st map: jd will win': ['1.47(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '1-st map: vici first blood': ['1.94(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '1-st map: vici will win': ['2.57(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '2-nd map: jd first blood': ['1.8(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '2-nd map: jd will win': ['1.47(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '2-nd map: vici first blood': ['1.94(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       '2-nd map: vici will win': ['2.57(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'correct score 0-2': ['5.62(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'correct score 1-2': ['5.14(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'correct score 2-0': ['2.15(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'correct score 2-1': ['3.22(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'jd handicap +1.5 maps': ['1.12(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'jd handicap -1.5 maps': ['2.14(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'jd will win': ['1.36(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'total maps even': ['1.65(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'total maps odd': ['2.16(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'total maps over 2.5': ['2.16(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'total maps under 2.5': ['1.65(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'vici handicap +1.5 maps': ['1.66(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'vici handicap -1.5 maps': ['5.65(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)'],
                       'vici will win': ['3.03(ggbet - https://gg.bet/en/betting/match/jd-gaming-vs-vici-gaming-15-07)']},
         'lgd - rogue warriors': {'1-st map: duration over 33.5': ['2.01(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: duration under 33.5': ['1.75(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: lgd first blood': ['1.76(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: lgd will first destroy turret': ['1.54(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: lgd will first kill baron': ['1.44(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: lgd will first make 10 kills': ['1.34(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: lgd will first make 5 kills': ['1.51(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: lgd will win': ['1.31(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: rogue warriors first blood': ['1.99(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: rogue warriors will first destroy turret': ['2.38(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: rogue warriors will first kill baron': ['2.66(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: rogue warriors will first make 10 kills': ['3.09(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: rogue warriors will first make 5 kills': ['2.45(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: rogue warriors will win': ['3.26(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: total kills over 26.5': ['1.8(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '1-st map: total kills under 26.5': ['1.94(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: duration over 33.5': ['2.01(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: duration under 33.5': ['1.75(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: lgd first blood': ['1.76(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: lgd will first destroy turret': ['1.54(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: lgd will first kill baron': ['1.44(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: lgd will first make 10 kills': ['1.34(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: lgd will first make 5 kills': ['1.51(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: lgd will win': ['1.31(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: rogue warriors first blood': ['1.99(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: rogue warriors will first destroy turret': ['2.38(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: rogue warriors will first kill baron': ['2.66(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: rogue warriors will first make 10 kills': ['3.09(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: rogue warriors will first make 5 kills': ['2.45(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: rogue warriors will win': ['3.26(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: total kills over 26.5': ['1.8(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  '2-nd map: total kills under 26.5': ['1.94(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'correct score 0-2': ['7.91(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'correct score 1-2': ['6.86(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'correct score 2-0': ['1.73(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'correct score 2-1': ['3.31(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'lgd handicap +1.5 maps': ['1.06(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'lgd handicap -1.5 maps': ['1.73(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'lgd will win': ['1.19(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'rogue warriors handicap +1.5 maps': ['2.03(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'rogue warriors handicap -1.5 maps': ['7.9(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'rogue warriors will win': ['4.45(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'total maps even': ['1.51(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'total maps odd': ['2.45(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'total maps over 2.5': ['2.45(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)'],
                                  'total maps under 2.5': ['1.51(ggbet - https://gg.bet/en/betting/match/lgd-gaming-vs-rogue-warriors-14-07)']},
         'lgd - we': {'1-st map: lgd first blood': ['1.91(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '1-st map: lgd will win': ['2.17(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '1-st map: we first blood': ['1.83(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '1-st map: we will win': ['1.64(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '2-nd map: lgd first blood': ['1.91(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '2-nd map: lgd will win': ['2.17(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '2-nd map: we first blood': ['1.83(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      '2-nd map: we will win': ['1.64(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'correct score 0-2': ['2.62(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'correct score 1-2': ['3.35(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'correct score 2-0': ['4.3(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'correct score 2-1': ['4.26(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'lgd handicap +1.5 maps': ['1.45(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'lgd handicap -1.5 maps': ['4.35(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'lgd will win': ['2.36(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'total maps even': ['1.74(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'total maps odd': ['2.02(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'total maps over 2.5': ['2.02(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'total maps under 2.5': ['1.74(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'we handicap +1.5 maps': ['1.19(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'we handicap -1.5 maps': ['2.63(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)'],
                      'we will win': ['1.56(ggbet - https://gg.bet/en/betting/match/team-we-vs-lgd-gaming-20-07)']},
         'lng - we': {'1-st map: duration over 33.5': ['2.02(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: duration under 33.5': ['1.74(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: lng first blood': ['2.09(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: lng will first destroy turret': ['2.27(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: lng will first kill baron': ['2.7(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: lng will first make 10 kills': ['2.6(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: lng will first make 5 kills': ['2.27(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: lng will win': ['3.32(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: total kills over 23.5': ['1.96(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: total kills under 23.5': ['1.79(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: we first blood': ['1.69(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: we will first destroy turret': ['1.59(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: we will first kill baron': ['1.43(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: we will first make 10 kills': ['1.46(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: we will first make 5 kills': ['1.59(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '1-st map: we will win': ['1.3(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: duration over 33.5': ['2.02(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: duration under 33.5': ['1.74(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: lng first blood': ['2.09(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: lng will first destroy turret': ['2.27(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: lng will first kill baron': ['2.7(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: lng will first make 10 kills': ['2.6(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: lng will first make 5 kills': ['2.27(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: lng will win': ['3.32(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: total kills over 23.5': ['1.96(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: total kills under 23.5': ['1.79(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: we first blood': ['1.69(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: we will first destroy turret': ['1.59(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: we will first kill baron': ['1.43(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: we will first make 10 kills': ['1.46(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: we will first make 5 kills': ['1.59(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      '2-nd map: we will win': ['1.3(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'correct score 0-2': ['1.7(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'correct score 1-2': ['3.33(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'correct score 2-0': ['8.11(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'correct score 2-1': ['7.02(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'lng handicap +1.5 maps': ['2.08(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'lng handicap -1.5 maps': ['7.9(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'lng will win': ['4.6(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'total maps even': ['1.5(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'total maps odd': ['2.48(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'total maps over 2.5': ['2.48(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'total maps under 2.5': ['1.5(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'we handicap +1.5 maps': ['1.06(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'we handicap -1.5 maps': ['1.7(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)'],
                      'we will win': ['1.18(ggbet - https://gg.bet/en/betting/match/team-we-vs-lng-esports-14-07)']},
         'royal never give up - suning': {'1-st map: royal never give up first blood': ['1.89(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '1-st map: royal never give up will win': ['2.05(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '1-st map: suning first blood': ['1.85(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '1-st map: suning will win': ['1.72(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '2-nd map: royal never give up first blood': ['1.89(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '2-nd map: royal never give up will win': ['2.05(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '2-nd map: suning first blood': ['1.85(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '2-nd map: suning will win': ['1.72(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'correct score 0-2': ['2.85(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'correct score 1-2': ['3.45(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'correct score 2-0': ['3.9(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'correct score 2-1': ['4.01(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'royal never give up handicap +1.5 maps': ['1.39(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'royal never give up handicap -1.5 maps': ['3.89(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'royal never give up will win': ['2.15(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'suning handicap +1.5 maps': ['1.23(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'suning handicap -1.5 maps': ['2.85(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'suning will win': ['1.67(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'total maps even': ['1.76(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'total maps odd': ['1.99(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'total maps over 2.5': ['1.99(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)'],
                                          'total maps under 2.5': ['1.76(ggbet - https://gg.bet/en/betting/match/royal-never-give-up-vs-suning-gaming-16-07)']},
         'top - vici': {'1-st map: top first blood': ['1.74(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '1-st map: top will win': ['1.21(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '1-st map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '1-st map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '1-st map: vici first blood': ['2.02(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '1-st map: vici will win': ['4.11(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '2-nd map: top first blood': ['1.74(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '2-nd map: top will win': ['1.22(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '2-nd map: total kills even': ['1.87(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '2-nd map: total kills odd': ['1.87(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '2-nd map: vici first blood': ['2.02(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        '2-nd map: vici will win': ['3.99(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'correct score 0-2': ['10.1(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'correct score 1-2': ['8.78(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'correct score 2-0': ['1.5(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'correct score 2-1': ['3.6(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'top handicap +1.5 maps': ['1.03(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'top handicap -1.5 maps': ['1.5(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'top will win': ['1.11(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'total maps even': ['1.39(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'total maps odd': ['2.85(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'total maps over 2.5': ['2.85(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'total maps under 2.5': ['1.39(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'vici handicap +1.5 maps': ['2.48(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'vici handicap -1.5 maps': ['10.09(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)'],
                        'vici will win': ['6.09(ggbet - https://gg.bet/en/betting/match/vici-gaming-vs-top-esports-19-07)']}}}
