sport = {'lol': {'100 thieves - liquid': {'100 thieves will win': ['3.04(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)'], 'liquid will win': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)']},
         '100 thieves - tsm': {'100 thieves will win': ['2.63(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)'], 'tsm will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)']},
         '100 thieves academy - liquid academy': {'100 thieves academy will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)'], 'liquid academy will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)']},
         '100 thieves academy - tsm academy': {'100 thieves academy will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)'], 'tsm academy will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)']},
         '1907 fenerbahce academy - besiktas academy': {'1907 fenerbahce academy will win': ['1.18(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)'],
                                                        'besiktas academy will win': ['4.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)']},
         '5 ronin - fenerbahce': {'5 ronin will win': ['3.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)'], 'fenerbahce will win': ['1.33(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)']},
         '5 ronin - papara supermassive': {'5 ronin will win': ['5.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)'], 'papara supermassive will win': ['1.12(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)']},
         '5 ronin academy - fenerbahce academy': {'5 ronin academy will win': ['3.54(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)'], 'fenerbahce academy will win': ['1.27(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)']},
         '5 ronin academy - supermassive academy': {'5 ronin academy will win': ['3.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)'], 'supermassive academy will win': ['1.32(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)']},
         '7am - aethra': {'7am will win': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-belgian-league)'], 'aethra will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-belgian-league)']},
         '7more 7pompa - ago rogue': {'7more 7pompa will win': ['2.94(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)'], 'ago rogue will win': ['1.37(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)']},
         '7more 7pompa - gentlemens': {'7more 7pompa will win': ['1.27(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)'], 'gentlemens will win': ['3.54(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)']},
         'ad hoc - fc schalke 04 evolution': {'ad hoc will win': ['2.57(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)'], 'fc schalke 04 evolution will win': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)']},
         'ad hoc - myinsanity': {'ad hoc will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)'], 'myinsanity will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)']},
         'afreeca freecs - damwon': {'1-st map: afreeca freecs handicap +6.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                     '1-st map: damwon handicap -6.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                     '2-nd map: afreeca freecs handicap +6.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                     '2-nd map: damwon handicap -6.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                     'afreeca freecs handicap +1.5 maps': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                     'afreeca freecs will win': ['3.47(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                     'damwon handicap -1.5 maps': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                     'damwon will win': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                     'total maps over 2.5': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                     'total maps under 2.5': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)']},
         'ago rogue - k1ck neosurf': {'ago rogue will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)'], 'k1ck neosurf will win': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)']},
         'ahq - j': {'ahq will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'j will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'ahq - nova': {'ahq will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'nova will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'all knights - pixel': {'all knights will win': ['1.10(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)'], 'pixel will win': ['6.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)']},
         'all knights - rainbow7': {'all knights will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)'], 'rainbow7 will win': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)']},
         'alpha - berjaya dragons': {'alpha will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'berjaya dragons will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'alpha - liyab': {'alpha will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'liyab will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'alpha - psg talon': {'alpha will win': ['4.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'psg talon will win': ['1.18(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'asus rog elite - cr4zy': {'asus rog elite will win': ['3.75(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ebl)'], 'cr4zy will win': ['1.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ebl)']},
         'aurora academy - galatasaray academy': {'aurora academy will win': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)'], 'galatasaray academy will win': ['1.89(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)']},
         'aurora academy - royal youth academy': {'aurora academy will win': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)'], 'royal youth academy will win': ['1.89(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)']},
         'avant - legacy': {'avant will win': ['4.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)'], 'legacy will win': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)']},
         'avant - pentanet.gg': {'avant will win': ['2.16(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)'], 'pentanet.gg will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)']},
         'awesome spear - hyfresh blade': {'awesome spear will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ck)'], 'hyfresh blade will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ck)']},
         'azules - infinity': {'azules will win': ['2.74(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)'], 'infinity will win': ['1.42(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)']},
         'azules - xten': {'azules will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)'], 'xten will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)']},
         'barrage academy - demise': {'barrage academy will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)'], 'demise will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)']},
         'barrage academy - london': {'barrage academy will win': ['2.75(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)'], 'london will win': ['1.42(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)']},
         'bcn squad - movistar riders': {'bcn squad will win': ['3.71(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)'], 'movistar riders will win': ['1.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)']},
         'bcn squad - vodafone giants': {'bcn squad will win': ['4.23(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)'], 'vodafone giants will win': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)']},
         'berjaya dragons - resurgence': {'berjaya dragons will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'resurgence will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'besiktas - fenerbahce': {'besiktas will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)'], 'fenerbahce will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)']},
         'besiktas - galatasaray': {'besiktas will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)'], 'galatasaray will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)']},
         'besiktas academy - galatasaray academy': {'besiktas academy will win': ['3.90(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)'], 'galatasaray academy will win': ['1.23(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)']},
         'big - gamerlegion': {'big will win': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)'], 'gamerlegion will win': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)']},
         'big - op innogy': {'big will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)'], 'op innogy will win': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)']},
         'bilibili - dominus': {'1-st map: bilibili handicap -4.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                '1-st map: dominus handicap +4.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                '2-nd map: bilibili handicap -4.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                '2-nd map: dominus handicap +4.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                'bilibili handicap -1.5 maps': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                'bilibili will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                'dominus handicap +1.5 maps': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                'dominus will win': ['2.63(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                'total maps over 2.5': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                'total maps under 2.5': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'bilibili - we': {'bilibili will win': ['3.47(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'], 'we will win': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'brussels guardians - kv mechelen': {'brussels guardians will win': ['2.90(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-belgian-league)'], 'kv mechelen will win': ['1.38(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-belgian-league)']},
         'bulldog - london': {'bulldog will win': ['4.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)'], 'london will win': ['1.18(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)']},
         'bulldog - munster rugby academy': {'bulldog will win': ['5.66(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)'], 'munster rugby academy will win': ['1.12(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)']},
         'cerberus - gam': {'cerberus will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)'], 'gam will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)']},
         'chiefs - dire wolves': {'chiefs will win': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)'], 'dire wolves will win': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)']},
         'chiefs - legacy': {'chiefs will win': ['2.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)'], 'legacy will win': ['1.44(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)']},
         'clg - dignitas': {'clg will win': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)'], 'dignitas will win': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)']},
         'clg - immortals': {'clg will win': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)'], 'immortals will win': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)']},
         'clg academy - dignitas academy': {'clg academy will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)'], 'dignitas academy will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)']},
         'clg academy - immortals academy': {'clg academy will win': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)'], 'immortals academy will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)']},
         'cloud9 - evil geniuses': {'cloud9 will win': ['1.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)'], 'evil geniuses will win': ['3.71(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)']},
         'cloud9 - flyquest': {'cloud9 will win': ['1.18(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)'], 'flyquest will win': ['4.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)']},
         'cloud9 academy - evil geniuses academy': {'cloud9 academy will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)'], 'evil geniuses academy will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)']},
         'cloud9 academy - flyquest academy': {'cloud9 academy will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)'], 'flyquest academy will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)']},
         'cream real betis - emonkeyz': {'cream real betis will win': ['1.67(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)'], 'emonkeyz will win': ['2.12(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)']},
         'cream real betis - ucam': {'cream real betis will win': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)'], 'ucam will win': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)']},
         'crvena zvezda - zero tenacity': {'crvena zvezda will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ebl)'], 'zero tenacity will win': ['2.82(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ebl)']},
         'dark passage - istanbul wild cats': {'dark passage will win': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)'], 'istanbul wild cats will win': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)']},
         'dark passage - royal youth': {'dark passage will win': ['1.22(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)'], 'royal youth will win': ['4.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)']},
         'dark passage academy - nbul wild cats academy': {'dark passage academy will win': ['2.99(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)'],
                                                           'nbul wild cats academy will win': ['1.36(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)']},
         'demise - mnm academy': {'demise will win': ['2.40(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)'], 'mnm academy will win': ['1.53(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)']},
         'dignitas - golden guardians': {'dignitas will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)'], 'golden guardians will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)']},
         'dignitas academy - golden guardians academy': {'dignitas academy will win': ['1.78(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)'],
                                                         'golden guardians academy will win': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)']},
         'dire wolves - order': {'dire wolves will win': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)'], 'order will win': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)']},
         'drx - dynamics': {'1-st map: drx handicap -7.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                            '1-st map: dynamics handicap +7.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                            '2-nd map: drx handicap -7.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                            '2-nd map: dynamics handicap +7.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                            'drx handicap -1.5 maps': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                            'drx will win': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                            'dynamics handicap +1.5 maps': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                            'dynamics will win': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                            'total maps over 2.5': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                            'total maps under 2.5': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)']},
         'drx - hanwha life': {'1-st map: drx handicap -8.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                               '1-st map: hanwha life handicap +8.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                               '2-nd map: drx handicap -8.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                               '2-nd map: hanwha life handicap +8.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                               'drx handicap -1.5 maps': ['1.32(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                               'drx will win': ['1.03(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                               'hanwha life handicap +1.5 maps': ['3.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                               'hanwha life will win': ['10.0(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                               'total maps over 2.5': ['3.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                               'total maps under 2.5': ['1.26(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)']},
         'dynasty - mcon': {'dynasty will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-dutch-league)'], 'mcon will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-dutch-league)']},
         'echo zulu - thrll': {'echo zulu will win': ['3.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-dutch-league)'], 'thrll will win': ['1.27(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-dutch-league)']},
         'edward - lgd': {'1-st map: edward handicap +4.5 kills': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                          '1-st map: lgd handicap -4.5 kills': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                          '2-nd map: edward handicap +4.5 kills': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                          '2-nd map: lgd handicap -4.5 kills': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                          'edward handicap +1.5 maps': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                          'edward will win': ['2.16(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                          'lgd handicap -1.5 maps': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                          'lgd will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                          'total maps over 2.5': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                          'total maps under 2.5': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'edward - vici': {'edward will win': ['1.98(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'], 'vici will win': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'element mystic - esc shane': {'element mystic will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ck)'], 'esc shane will win': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ck)']},
         'element mystic - griffin': {'element mystic will win': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ck)'], 'griffin will win': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ck)']},
         'emonkeyz - queso': {'emonkeyz will win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)'], 'queso will win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)']},
         'enclave - envision': {'enclave will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)'], 'envision will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)']},
         'enclave - munster rugby academy': {'enclave will win': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)'], 'munster rugby academy will win': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)']},
         'estar - rogue warriors': {'estar will win': ['1.38(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'], 'rogue warriors will win': ['2.90(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'euronics - op innogy': {'euronics will win': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)'], 'op innogy will win': ['2.43(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)']},
         'euronics - sk prime': {'euronics will win': ['1.27(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)'], 'sk prime will win': ['3.54(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)']},
         'evil geniuses - liquid': {'evil geniuses will win': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)'], 'liquid will win': ['1.63(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)']},
         'evil geniuses academy - liquid academy': {'evil geniuses academy will win': ['1.36(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)'], 'liquid academy will win': ['3.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)']},
         'evos - saigon buffalo': {'evos will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)'], 'saigon buffalo will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)']},
         'excel - mad lions': {'1-st map: excel handicap +6.5 kills': ['1.89(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                               '1-st map: mad lions handicap -6.5 kills': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                               'excel will win': ['3.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                               'mad lions will win': ['1.33(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)']},
         'excel - rogue': {'1-st map: excel handicap +6.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                           '1-st map: rogue handicap -6.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                           'excel will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                           'rogue will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)']},
         'falkol - red canids': {'falkol will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)'], 'red canids will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)']},
         'falkol -one': {'falkol will win': ['2.36(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)'], 'teamone will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)']},
         'fc schalke 04 evolution - sk prime': {'fc schalke 04 evolution will win': ['1.22(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)'], 'sk prime will win': ['4.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)']},
         'flamengo - kabum!': {'1-st map: flamengo handicap -4.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                               '1-st map: kabum! handicap +4.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                               'flamengo will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                               'kabum! will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)']},
         'flamengo - santos': {'1-st map: flamengo handicap -4.5 kills': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                               '1-st map: santos handicap +4.5 kills': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                               'flamengo will win': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                               'santos will win': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)']},
         'flash - percent': {'flash will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)'], 'percent will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)']},
         'flash - secret': {'flash will win': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)'], 'secret will win': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)']},
         'flyquest - tsm': {'flyquest will win': ['2.16(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)'], 'tsm will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)']},
         'flyquest academy - tsm academy': {'flyquest academy will win': ['3.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)'], 'tsm academy will win': ['1.36(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)']},
         'fnatic - misfits': {'1-st map: fnatic handicap -4.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                              '1-st map: misfits handicap +4.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                              'fnatic will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                              'misfits will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)']},
         'fnatic - vitality': {'1-st map: fnatic handicap -6.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                               '1-st map: vitality handicap +6.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                               'fnatic will win': ['1.37(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                               'vitality will win': ['2.94(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)']},
         'funplus phoenix - jd': {'1-st map: funplus phoenix handicap +4.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                  '1-st map: jd handicap -4.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                  '2-nd map: funplus phoenix handicap +4.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                  '2-nd map: jd handicap -4.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                  'funplus phoenix handicap +1.5 maps': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                  'funplus phoenix will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                  'jd handicap -1.5 maps': ['2.63(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                  'jd will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                  'total maps over 2.5': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                  'total maps under 2.5': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'funplus phoenix - oh my god': {'funplus phoenix will win': ['1.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'], 'oh my god will win': ['3.71(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'funplus phoenix - rogue warriors': {'1-st map: funplus phoenix handicap -8.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                              '1-st map: rogue warriors handicap +8.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                              '2-nd map: funplus phoenix handicap -8.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                              '2-nd map: rogue warriors handicap +8.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                              'funplus phoenix handicap -1.5 maps': ['1.44(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                              'funplus phoenix will win': ['1.10(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                              'rogue warriors handicap +1.5 maps': ['2.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                              'rogue warriors will win': ['6.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                              'total maps over 2.5': ['2.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                              'total maps under 2.5': ['1.37(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'furia - pain': {'1-st map: furia handicap +7.5 kills': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                          '1-st map: pain handicap -7.5 kills': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                          'furia will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                          'pain will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)']},
         'furia - vivo keyd': {'1-st map: furia handicap -4.5 kills': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                               '1-st map: vivo keyd handicap +4.5 kills': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                               'furia will win': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                               'vivo keyd will win': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)']},
         'furious - infinity': {'furious will win': ['2.82(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)'], 'infinity will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)']},
         'furious - isurus': {'furious will win': ['3.21(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)'], 'isurus will win': ['1.32(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)']},
         'g2 - mad lions': {'1-st map: g2 handicap -5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                            '1-st map: mad lions handicap +5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                            'g2 will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                            'mad lions will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)']},
         'g2 - origen': {'1-st map: g2 handicap -5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                         '1-st map: origen handicap +5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                         'g2 will win': ['1.42(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                         'origen will win': ['2.75(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)']},
         'g2 arctic - movistar riders': {'g2 arctic will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)'], 'movistar riders will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)']},
         'g2 arctic - queso': {'g2 arctic will win': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)'], 'queso will win': ['2.57(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)']},
         'galakticos - istanbul wild cats': {'galakticos will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)'], 'istanbul wild cats will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)']},
         'galakticos - papara supermassive': {'galakticos will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)'], 'papara supermassive will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)']},
         'galakticos academy - nbul wild cats academy': {'galakticos academy will win': ['4.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)'],
                                                         'nbul wild cats academy will win': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)']},
         'galakticos academy - supermassive academy': {'galakticos academy will win': ['2.43(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)'],
                                                       'supermassive academy will win': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl-academy)']},
         'galatasaray - aurora': {'aurora will win': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)'], 'galatasaray will win': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)']},
         'gamerlegion - mousesports': {'gamerlegion will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)'], 'mousesports will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)']},
         'gen.g - t1': {'1-st map: gen.g handicap +4.5 kills': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                        '1-st map: t1 handicap -4.5 kills': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                        '2-nd map: gen.g handicap +4.5 kills': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                        '2-nd map: t1 handicap -4.5 kills': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                        'gen.g handicap +1.5 maps': ['1.31(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                        'gen.g will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                        't1 handicap -1.5 maps': ['3.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                        't1 will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                        'total maps over 2.5': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                        'total maps under 2.5': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)']},
         'gentlemens - pride': {'gentlemens will win': ['1.58(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)'], 'pride will win': ['2.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)']},
         'golden guardians - immortals': {'golden guardians will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)'], 'immortals will win': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lcs)']},
         'golden guardians academy - immortals academy': {'golden guardians academy will win': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)'],
                                                          'immortals academy will win': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-na-academy)']},
         'gravitas - mammoth': {'gravitas will win': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)'], 'mammoth will win': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)']},
         'gravitas - pentanet.gg': {'gravitas will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)'], 'pentanet.gg will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)']},
         'hanwha life - seolhaeone prince': {'1-st map: hanwha life handicap -4.5 kills': ['2.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                             '1-st map: seolhaeone prince handicap +4.5 kills': ['1.58(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                             '2-nd map: hanwha life handicap -4.5 kills': ['2.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                             '2-nd map: seolhaeone prince handicap +4.5 kills': ['1.58(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                             'hanwha life handicap -1.5 maps': ['3.45(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                             'hanwha life will win': ['1.85(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                             'seolhaeone prince handicap +1.5 maps': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                             'seolhaeone prince will win': ['1.89(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                             'total maps over 2.5': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                             'total maps under 2.5': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)']},
         'havan liberty - red canids': {'havan liberty will win': ['3.33(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)'], 'red canids will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)']},
         'havan liberty - redemption poa': {'havan liberty will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)'], 'redemption poa will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)']},
         'hong kong attitude - j': {'hong kong attitude will win': ['2.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'j will win': ['1.37(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'hong kong attitude - resurgence': {'hong kong attitude will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'resurgence will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'howling - nexus': {'howling will win': ['1.63(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ebl)'], 'nexus will win': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ebl)']},
         'illuminar - komputronik h34t': {'illuminar will win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)'], 'komputronik h34t will win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)']},
         'illuminar - piratesports': {'illuminar will win': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)'], 'piratesports will win': ['3.47(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)']},
         'intz - kabum!': {'1-st map: intz handicap -3.5 kills': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                           '1-st map: kabum! handicap +3.5 kills': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                           'intz will win': ['1.78(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                           'kabum! will win': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)']},
         'intz - vivo keyd': {'1-st map: intz handicap -5.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                              '1-st map: vivo keyd handicap +5.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                              'intz will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                              'vivo keyd will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)']},
         'invictus - royal never give up': {'1-st map: invictus handicap -4.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                            '1-st map: royal never give up handicap +4.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                            '2-nd map: invictus handicap -4.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                            '2-nd map: royal never give up handicap +4.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                            'invictus handicap -1.5 maps': ['2.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                            'invictus will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                            'royal never give up handicap +1.5 maps': ['1.43(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                            'royal never give up will win': ['2.36(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                            'total maps over 2.5': ['1.99(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                                            'total maps under 2.5': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'invictus - victory five': {'invictus will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'], 'victory five will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'isurus - pixel': {'isurus will win': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)'], 'pixel will win': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)']},
         'jin air green wings - runaway': {'jin air green wings will win': ['1.22(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ck)'], 'runaway will win': ['4.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ck)']},
         'k1ck neosurf - komputronik h34t': {'k1ck neosurf will win': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)'], 'komputronik h34t will win': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)']},
         'kt rolster - sandbox': {'1-st map: kt rolster handicap -4.5 kills': ['2.21(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                  '1-st map: sandbox handicap +4.5 kills': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                  '2-nd map: kt rolster handicap -4.5 kills': ['2.21(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                  '2-nd map: sandbox handicap +4.5 kills': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                  'kt rolster handicap -1.5 maps': ['3.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                  'kt rolster will win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                  'sandbox handicap +1.5 maps': ['1.27(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                  'sandbox will win': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                  'total maps over 2.5': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)'],
                                  'total maps under 2.5': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lck)']},
         'lgd - we': {'lgd will win': ['2.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'], 'we will win': ['1.50(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']},
         'liyab - nova': {'liyab will win': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'nova will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'liyab - psg talon': {'liyab will win': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'psg talon will win': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'lowlandlions - psv': {'lowlandlions will win': ['3.21(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-dutch-league)'], 'psv will win': ['1.32(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-dutch-league)']},
         'machi - psg talon': {'machi will win': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'psg talon will win': ['1.63(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'machi - resurgence': {'machi will win': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)'], 'resurgence will win': ['4.20(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-pcs)']},
         'mad lions madrid - s2v': {'mad lions madrid will win': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)'], 's2v will win': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)']},
         'mad lions madrid - ucam': {'mad lions madrid will win': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)'], 'ucam will win': ['2.21(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)']},
         'mammoth - order': {'mammoth will win': ['3.45(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)'], 'order will win': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-opl)']},
         'misfits - origen': {'1-st map: misfits handicap +3.5 kills': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                              '1-st map: origen handicap -3.5 kills': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                              'misfits will win': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                              'origen will win': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)']},
         'mnm academy - nvision': {'mnm academy will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)'], 'nvision will win': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-uklc)']},
         'mousesports - unicorns of love sexy edition': {'mousesports will win': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)'],
                                                         'unicorns of love sexy edition will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)']},
         'myinsanity - unicorns of love sexy edition': {'myinsanity will win': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)'],
                                                        'unicorns of love sexy edition will win': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-prime-league)']},
         'overpower - percent': {'overpower will win': ['2.90(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)'], 'percent will win': ['1.38(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)']},
         'overpower - saigon buffalo': {'overpower will win': ['2.43(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)'], 'saigon buffalo will win': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-vcs)']},
         'pain - prodigy': {'1-st map: pain handicap -7.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                            '1-st map: prodigy handicap +7.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                            'pain will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                            'prodigy will win': ['3.33(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)']},
         'piratesports - pride': {'piratesports will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)'], 'pride will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ultraliga)']},
         'prodigy - santos': {'1-st map: prodigy handicap +5.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                              '1-st map: santos handicap -5.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                              'prodigy will win': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)'],
                              'santos will win': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-cblol)']},
         'rainbow7 - xten': {'rainbow7 will win': ['1.23(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)'], 'xten will win': ['3.90(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lla)']},
         'redemption poa - rensga': {'redemption poa will win': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)'], 'rensga will win': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)']},
         'rensga -one': {'rensga will win': ['2.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)'], 'teamone will win': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-brcc)']},
         'rogue - schalke 04': {'1-st map: rogue handicap -7.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                                '1-st map: schalke 04 handicap +7.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                                'rogue will win': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                                'schalke 04 will win': ['3.47(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)']},
         'royal youth - aurora': {'aurora will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)'], 'royal youth will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-tcl)']},
         'rsc anderlecht - sector one': {'rsc anderlecht will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-belgian-league)'], 'sector one will win': ['2.63(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-belgian-league)']},
         's2v - vodafone giants': {'s2v will win': ['3.71(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)'], 'vodafone giants will win': ['1.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lvp)']},
         'schalke 04 - sk': {'1-st map: schalke 04 handicap +4.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                             '1-st map: sk handicap -4.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                             'schalke 04 will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                             'sk will win': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)']},
         'sk - vitality': {'1-st map: sk handicap -3.5 kills': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                           '1-st map: vitality handicap +3.5 kills': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                           'sk will win': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)'],
                           'vitality will win': ['1.98(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lec)']},
         'split raiders - suppup': {'split raiders will win': ['2.43(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ebl)'], 'suppup will win': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-ebl)']},
         'top - vici': {'1-st map: top handicap -6.5 kills': ['1.84(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                        '1-st map: vici handicap +6.5 kills': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                        '2-nd map: top handicap -6.5 kills': ['1.84(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                        '2-nd map: vici handicap +6.5 kills': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                        'top handicap -1.5 maps': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                        'top will win': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                        'total maps over 2.5': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                        'total maps under 2.5': ['1.48(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                        'vici handicap +1.5 maps': ['2.36(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)'],
                        'vici will win': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/liga-legend-lpl)']}}}
