bets = {
    '100 thieves - gen.g': {
        '1-st map: 100 thieves will win': {'1.60': 'favorit'},
        '1-st map: gen.g will win': {'2.25': 'favorit'},
        '1-st map: handicap 100 thieves +2.5': {'1.41': 'favorit'},
        '1-st map: handicap 100 thieves -2.5': {'1.86': 'favorit'},
        '1-st map: handicap 100 thieves -3.5': {'2.18': 'favorit'},
        '1-st map: handicap 100 thieves -4.5': {'2.54': 'favorit'},
        '1-st map: handicap 100 thieves -5.5': {'2.89': 'favorit'},
        '1-st map: handicap gen.g +2.5': {'1.88': 'favorit'},
        '1-st map: handicap gen.g +3.5': {'1.61': 'favorit'},
        '1-st map: handicap gen.g +4.5': {'1.46': 'favorit'},
        '1-st map: handicap gen.g +5.5': {'1.34': 'favorit'},
        '1-st map: handicap gen.g -2.5': {'2.61': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: total over 24.5': {'1.39': 'favorit'},
        '1-st map: total over 25.5': {'1.63': 'favorit'},
        '1-st map: total over 26.5': {'1.89': 'favorit'},
        '1-st map: total over 27.5': {'2.25': 'favorit'},
        '1-st map: total over 28.5': {'2.85': 'favorit'},
        '1-st map: total under 24.5': {'2.68': 'favorit'},
        '1-st map: total under 25.5': {'2.14': 'favorit'},
        '1-st map: total under 26.5': {'1.85': 'favorit'},
        '1-st map: total under 27.5': {'1.57': 'favorit'},
        '1-st map: total under 28.5': {'1.35': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? 100 thieves': {'1.66': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? gen.g': {'2.14': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? 100 thieves': {'1.72': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? gen.g': {'2.05': 'favorit'},
        '100 thieves handicap +1.5 maps': {'1.15': 'favorit'},
        '100 thieves handicap -1.5 maps': {'2.50': 'favorit'},
        '100 thieves will win': {'1.51': 'favorit'},
        'correct score 0-2': {'4.90': 'favorit'},
        'correct score 1-2': {'4.20': 'favorit'},
        'correct score 2-0': {'2.50': 'favorit'},
        'correct score 2-1': {'3.10': 'favorit'},
        'gen.g handicap +1.5 maps': {'1.50': 'favorit'},
        'gen.g handicap -1.5 maps': {'4.90': 'favorit'},
        'gen.g will win': {'2.45': 'favorit'},
        'total over 2.5': {'2.08': 'favorit'},
        'total under 2.5': {'1.70': 'favorit'}
    },
    'ago - nordavind': {
        '1-st map: handicap ago +2.5': {'1.77': 'favorit'},
        '1-st map: handicap ago +3.5': {'1.54': 'favorit'},
        '1-st map: handicap ago -2.5': {'2.48': 'favorit'},
        '1-st map: handicap nordavind +2.5': {'1.48': 'favorit'},
        '1-st map: handicap nordavind -2.5': {'1.98': 'favorit'},
        '1-st map: handicap nordavind -3.5': {'2.33': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: total over 25.5': {'1.58': 'favorit'},
        '1-st map: total over 26.5': {'1.80': 'favorit'},
        '1-st map: total over 27.5': {'2.17': 'favorit'},
        '1-st map: total under 25.5': {'2.24': 'favorit'},
        '1-st map: total under 26.5': {'1.95': 'favorit'},
        '1-st map: total under 27.5': {'1.61': 'favorit'},
        'ago will win': {'2.11': 'favorit'},
        'nordavind will win': {'1.68': 'favorit'}
    },
    'alternate attax - fate': {
        '1-st map: handicap alternate attax -2.5': {'1.67': 'favorit'},
        '1-st map: handicap alternate attax -3.5': {'1.99': 'favorit'},
        '1-st map: handicap alternate attax -4.5': {'2.31': 'favorit'},
        '1-st map: handicap fate +2.5': {'2.07': 'favorit'},
        '1-st map: handicap fate +3.5': {'1.76': 'favorit'},
        '1-st map: handicap fate +4.5': {'1.55': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: total over 25.5': {'1.61': 'favorit'},
        '1-st map: total over 26.5': {'1.87': 'favorit'},
        '1-st map: total over 27.5': {'2.23': 'favorit'},
        '1-st map: total under 25.5': {'2.18': 'favorit'},
        '1-st map: total under 26.5': {'1.87': 'favorit'},
        '1-st map: total under 27.5': {'1.58': 'favorit'},
        'alternate attax will win': {'1.47': 'favorit'},
        'fate will win': {'2.55': 'favorit'}
    },
    'ambush - apeks': {
        '1-st map: ambush will win': {'2.55': 'favorit'},
        '1-st map: apeks will win': {'1.47': 'favorit'},
        '1-st map: handicap ambush +2.5': {'1.91': 'favorit'},
        '1-st map: handicap ambush +3.5': {'1.78': 'favorit'},
        '1-st map: handicap apeks -2.5': {'1.83': 'favorit'},
        '1-st map: handicap apeks -3.5': {'1.97': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: total over 26.5': {'1.93': 'favorit'},
        '1-st map: total under 26.5': {'1.81': 'favorit'},
        'ambush handicap +1.5 maps': {'1.52': 'favorit'},
        'ambush will win': {'2.65': 'favorit'},
        'apeks handicap -1.5 maps': {'2.43': 'favorit'},
        'apeks will win': {'1.44': 'favorit'},
        'correct score 0-2': {'2.43': 'favorit'},
        'correct score 1-2': {'3.10': 'favorit'},
        'correct score 2-0': {'5.50': 'favorit'},
        'correct score 2-1': {'4.40': 'favorit'},
        'total over 2.5': {'1.97': 'favorit'},
        'total under 2.5': {'1.78': 'favorit'}
    },
    'apeks - nemiga gaming': {
        '1-st map: handicap apeks +3.5': {'2.11': 'favorit'},
        '1-st map: handicap apeks +4.5': {'1.83': 'favorit'},
        '1-st map: handicap apeks +5.5': {'1.62': 'favorit'},
        '1-st map: handicap nemiga gaming -3.5': {'1.65': 'favorit'},
        '1-st map: handicap nemiga gaming -4.5': {'1.92': 'favorit'},
        '1-st map: handicap nemiga gaming -5.5': {'2.17': 'favorit'},
        '1-st map: odd / even even': {'1.72': 'favorit'},
        '1-st map: odd / even odd': {'2.05': 'favorit'},
        '1-st map: total over 24.5': {'1.51': 'favorit'},
        '1-st map: total over 25.5': {'1.78': 'favorit'},
        '1-st map: total over 26.5': {'2.05': 'favorit'},
        '1-st map: total under 24.5': {'2.39': 'favorit'},
        '1-st map: total under 25.5': {'1.97': 'favorit'},
        '1-st map: total under 26.5': {'1.69': 'favorit'},
        'apeks will win': {'3.25': 'favorit'},
        'nemiga gaming will win': {'1.31': 'favorit'}
    },
    'avant - paradox gaming': {
        '1-st map: avant will win': {'1.40': 'favorit'},
        '1-st map: handicap avant -3.5': {'1.85': 'favorit'},
        '1-st map: handicap paradox gaming +3.5': {'1.89': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: paradox gaming will win': {'2.80': 'favorit'},
        '1-st map: total over 26.5': {'1.93': 'favorit'},
        '1-st map: total under 26.5': {'1.81': 'favorit'},
        'avant handicap -1.5 maps': {'2.06': 'favorit'},
        'avant will win': {'1.27': 'favorit'},
        'correct score 0-2': {'7.10': 'favorit'},
        'correct score 1-2': {'6.00': 'favorit'},
        'correct score 2-0': {'2.06': 'favorit'},
        'correct score 2-1': {'2.95': 'favorit'},
        'paradox gaming handicap +1.5 maps': {'1.71': 'favorit'},
        'paradox gaming will win': {'3.50': 'favorit'},
        'total over 2.5': {'2.35': 'favorit'},
        'total under 2.5': {'1.55': 'favorit'}
    },
    'big - vitality': {
        '1-st map: big will win': {'1.78': 'favorit'},
        '1-st map: handicap big +2.5': {'1.55': 'favorit'},
        '1-st map: handicap big +3.5': {'1.38': 'favorit'},
        '1-st map: handicap big -2.5': {'2.11': 'favorit'},
        '1-st map: handicap big -3.5': {'2.48': 'favorit'},
        '1-st map: handicap big -4.5': {'2.90': 'favorit'},
        '1-st map: handicap vitality +2.5': {'1.68': 'favorit'},
        '1-st map: handicap vitality +3.5': {'1.48': 'favorit'},
        '1-st map: handicap vitality +4.5': {'1.34': 'favorit'},
        '1-st map: handicap vitality -2.5': {'2.30': 'favorit'},
        '1-st map: handicap vitality -3.5': {'2.73': 'favorit'},
        '1-st map: odd / even even': {'1.80': 'favorit'},
        '1-st map: odd / even odd': {'1.94': 'favorit'},
        '1-st map: total over 24.5': {'1.29': 'favorit'},
        '1-st map: total over 25.5': {'1.60': 'favorit'},
        '1-st map: total over 26.5': {'1.85': 'favorit'},
        '1-st map: total over 27.5': {'2.21': 'favorit'},
        '1-st map: total over 28.5': {'2.78': 'favorit'},
        '1-st map: total under 24.5': {'3.15': 'favorit'},
        '1-st map: total under 25.5': {'2.20': 'favorit'},
        '1-st map: total under 26.5': {'1.89': 'favorit'},
        '1-st map: total under 27.5': {'1.59': 'favorit'},
        '1-st map: total under 28.5': {'1.37': 'favorit'},
        '1-st map: vitality will win': {'1.96': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? big': {'1.81': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? vitality': {'1.94': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? big': {'1.82': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? vitality': {'1.92': 'favorit'},
        'big handicap +1.5 maps': {'1.23': 'favorit'},
        'big handicap -1.5 maps': {'3.05': 'favorit'},
        'big will win': {'1.75': 'favorit'},
        'correct score 0-2': {'3.85': 'favorit'},
        'correct score 1-2': {'3.60': 'favorit'},
        'correct score 2-0': {'3.05': 'favorit'},
        'correct score 2-1': {'3.45': 'favorit'},
        'total over 2.5': {'2.00': 'favorit'},
        'total under 2.5': {'1.75': 'favorit'},
        'vitality handicap +1.5 maps': {'1.35': 'favorit'},
        'vitality handicap -1.5 maps': {'3.85': 'favorit'},
        'vitality will win': {'2.00': 'favorit'}
    },
    'brute - tikitakan': {
        '1-st map: brute will win': {'1.92': 'favorit'},
        '1-st map: handicap brute +2.5': {'1.65': 'favorit'},
        '1-st map: handicap tikitakan -2.5': {'2.16': 'favorit'},
        '1-st map: odd / even even': {'1.80': 'favorit'},
        '1-st map: odd / even odd': {'1.95': 'favorit'},
        '1-st map: tikitakan will win': {'1.82': 'favorit'},
        '1-st map: total over 26.5': {'1.83': 'favorit'},
        '1-st map: total under 26.5': {'1.91': 'favorit'},
        'brute handicap +1.5 maps': {'1.33': 'favorit'},
        'brute will win': {'1.94': 'favorit'},
        'correct score 0-2': {'3.15': 'favorit'},
        'correct score 1-2': {'3.60': 'favorit'},
        'correct score 2-0': {'3.75': 'favorit'},
        'correct score 2-1': {'3.50': 'favorit'},
        'tikitakan handicap -1.5 maps': {'3.15': 'favorit'},
        'tikitakan will win': {'1.80': 'favorit'},
        'total over 2.5': {'2.11': 'favorit'},
        'total under 2.5': {'1.68': 'favorit'}
    },
    'chiefs - truckers with attitude': {
        '1-st map: chiefs will win': {'1.33': 'favorit'},
        '1-st map: handicap chiefs -4.5': {'1.97': 'favorit'},
        '1-st map: handicap truckers with attitude +4.5': {'1.77': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: total over 25.5': {'1.74': 'favorit'},
        '1-st map: total under 25.5': {'2.01': 'favorit'},
        '1-st map: truckers with attitude will win': {'3.10': 'favorit'},
        'chiefs handicap -1.5 maps': {'1.66': 'favorit'},
        'chiefs will win': {'1.18': 'favorit'},
        'correct score 0-2': {'9.70': 'favorit'},
        'correct score 1-2': {'7.00': 'favorit'},
        'correct score 2-0': {'1.66': 'favorit'},
        'correct score 2-1': {'3.40': 'favorit'},
        'total over 2.5': {'2.65': 'favorit'},
        'total under 2.5': {'1.45': 'favorit'},
        'truckers with attitude handicap +1.5 maps': {'2.14': 'favorit'},
        'truckers with attitude will win': {'4.50': 'favorit'}
    },
    'cloud9 - furia': {
        '1-st map: cloud9 will win': {'2.55': 'favorit'},
        '1-st map: furia will win': {'1.47': 'favorit'},
        '1-st map: handicap cloud9 +2.5': {'2.07': 'favorit'},
        '1-st map: handicap cloud9 +3.5': {'1.76': 'favorit'},
        '1-st map: handicap cloud9 +4.5': {'1.55': 'favorit'},
        '1-st map: handicap cloud9 +5.5': {'1.41': 'favorit'},
        '1-st map: handicap cloud9 -2.5': {'3.00': 'favorit'},
        '1-st map: handicap furia +2.5': {'1.32': 'favorit'},
        '1-st map: handicap furia -2.5': {'1.67': 'favorit'},
        '1-st map: handicap furia -3.5': {'1.99': 'favorit'},
        '1-st map: handicap furia -4.5': {'2.31': 'favorit'},
        '1-st map: handicap furia -5.5': {'2.64': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: total over 24.5': {'1.39': 'favorit'},
        '1-st map: total over 25.5': {'1.61': 'favorit'},
        '1-st map: total over 26.5': {'1.87': 'favorit'},
        '1-st map: total over 27.5': {'2.23': 'favorit'},
        '1-st map: total over 28.5': {'2.85': 'favorit'},
        '1-st map: total under 24.5': {'2.71': 'favorit'},
        '1-st map: total under 25.5': {'2.18': 'favorit'},
        '1-st map: total under 26.5': {'1.87': 'favorit'},
        '1-st map: total under 27.5': {'1.58': 'favorit'},
        '1-st map: total under 28.5': {'1.35': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? cloud9': {'2.34': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? furia': {'1.55': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? cloud9': {'2.19': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? furia': {'1.63': 'favorit'},
        'cloud9 handicap +1.5 maps': {'1.74': 'favorit'},
        'cloud9 handicap -1.5 maps': {'6.10': 'favorit'},
        'cloud9 will win': {'3.10': 'favorit'},
        'correct score 0-2': {'2.02': 'favorit'},
        'correct score 1-2': {'3.40': 'favorit'},
        'correct score 2-0': {'6.10': 'favorit'},
        'correct score 2-1': {'5.25': 'favorit'},
        'furia handicap +1.5 maps': {'1.10': 'favorit'},
        'furia handicap -1.5 maps': {'2.02': 'favorit'},
        'furia will win': {'1.34': 'favorit'},
        'total over 2.5': {'2.25': 'favorit'},
        'total under 2.5': {'1.60': 'favorit'}
    },
    'cr4zy - lilmix': {
        '1-st map: cr4zy will win': {'1.56': 'favorit'},
        '1-st map: handicap cr4zy -2.5': {'1.80': 'favorit'},
        '1-st map: handicap lilmix +2.5': {'1.95': 'favorit'},
        '1-st map: lilmix will win': {'2.33': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: total over 26.5': {'1.90': 'favorit'},
        '1-st map: total under 26.5': {'1.84': 'favorit'},
        'correct score 0-2': {'5.20': 'favorit'},
        'correct score 1-2': {'4.60': 'favorit'},
        'correct score 2-0': {'2.45': 'favorit'},
        'correct score 2-1': {'3.00': 'favorit'},
        'cr4zy handicap -1.5 maps': {'2.45': 'favorit'},
        'cr4zy will win': {'1.44': 'favorit'},
        'lilmix handicap +1.5 maps': {'1.52': 'favorit'},
        'lilmix will win': {'2.66': 'favorit'},
        'total over 2.5': {'1.95': 'favorit'},
        'total under 2.5': {'1.79': 'favorit'}
    },
    'espada - pact': {
        '1-st map: espada will win': {'1.67': 'favorit'},
        '1-st map: handicap espada +2.5': {'1.47': 'favorit'},
        '1-st map: handicap espada -2.5': {'1.95': 'favorit'},
        '1-st map: handicap espada -3.5': {'2.29': 'favorit'},
        '1-st map: handicap pact +2.5': {'1.79': 'favorit'},
        '1-st map: handicap pact +3.5': {'1.55': 'favorit'},
        '1-st map: handicap pact -2.5': {'2.51': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: pact will win': {'2.13': 'favorit'},
        '1-st map: total over 25.5': {'1.59': 'favorit'},
        '1-st map: total over 26.5': {'1.84': 'favorit'},
        '1-st map: total over 27.5': {'2.20': 'favorit'},
        '1-st map: total under 25.5': {'2.22': 'favorit'},
        '1-st map: total under 26.5': {'1.90': 'favorit'},
        '1-st map: total under 27.5': {'1.60': 'favorit'},
        'correct score 0-2': {'4.45': 'favorit'},
        'correct score 1-2': {'3.80': 'favorit'},
        'correct score 2-0': {'2.70': 'favorit'},
        'correct score 2-1': {'3.20': 'favorit'},
        'espada handicap +1.5 maps': {'1.18': 'favorit'},
        'espada handicap -1.5 maps': {'2.70': 'favorit'},
        'espada will win': {'1.60': 'favorit'},
        'pact handicap +1.5 maps': {'1.43': 'favorit'},
        'pact handicap -1.5 maps': {'4.45': 'favorit'},
        'pact will win': {'2.24': 'favorit'},
        'total over 2.5': {'2.19': 'favorit'},
        'total under 2.5': {'1.63': 'favorit'}
    },
    'evil geniuses - liquid': {
        '1-st map: evil geniuses will win': {'1.87': 'favorit'},
        '1-st map: handicap evil geniuses +2.5': {'1.59': 'favorit'},
        '1-st map: handicap evil geniuses +3.5': {'1.41': 'favorit'},
        '1-st map: handicap evil geniuses -2.5': {'2.24': 'favorit'},
        '1-st map: handicap evil geniuses -3.5': {'2.65': 'favorit'},
        '1-st map: handicap evil geniuses -4.5': {'3.15': 'favorit'},
        '1-st map: handicap liquid +2.5': {'1.60': 'favorit'},
        '1-st map: handicap liquid +3.5': {'1.42': 'favorit'},
        '1-st map: handicap liquid +4.5': {'1.30': 'favorit'},
        '1-st map: handicap liquid -2.5': {'2.22': 'favorit'},
        '1-st map: handicap liquid -3.5': {'2.63': 'favorit'},
        '1-st map: liquid will win': {'1.87': 'favorit'},
        '1-st map: odd / even even': {'1.79': 'favorit'},
        '1-st map: odd / even odd': {'1.96': 'favorit'},
        '1-st map: total over 24.5': {'1.26': 'favorit'},
        '1-st map: total over 25.5': {'1.54': 'favorit'},
        '1-st map: total over 26.5': {'1.77': 'favorit'},
        '1-st map: total over 27.5': {'2.12': 'favorit'},
        '1-st map: total over 28.5': {'2.68': 'favorit'},
        '1-st map: total under 24.5': {'3.35': 'favorit'},
        '1-st map: total under 25.5': {'2.32': 'favorit'},
        '1-st map: total under 26.5': {'1.98': 'favorit'},
        '1-st map: total under 27.5': {'1.65': 'favorit'},
        '1-st map: total under 28.5': {'1.40': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? evil geniuses': {'1.87': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? liquid': {'1.87': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? evil geniuses': {'1.87': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? liquid': {'1.87': 'favorit'},
        'correct score 0-2': {'3.55': 'favorit'},
        'correct score 1-2': {'3.50': 'favorit'},
        'correct score 2-0': {'3.55': 'favorit'},
        'correct score 2-1': {'3.50': 'favorit'},
        'evil geniuses handicap +1.5 maps': {'1.27': 'favorit'},
        'evil geniuses handicap -1.5 maps': {'3.55': 'favorit'},
        'evil geniuses will win': {'1.87': 'favorit'},
        'liquid handicap +1.5 maps': {'1.27': 'favorit'},
        'liquid handicap -1.5 maps': {'3.55': 'favorit'},
        'liquid will win': {'1.87': 'favorit'},
        'total over 2.5': {'1.87': 'favorit'},
        'total under 2.5': {'1.87': 'favorit'}
    },
    'fnatic - heroic': {
        '1-st map: fnatic will win': {'1.83': 'favorit'},
        '1-st map: handicap fnatic +2.5': {'1.58': 'favorit'},
        '1-st map: handicap fnatic +3.5': {'1.41': 'favorit'},
        '1-st map: handicap fnatic -2.5': {'2.17': 'favorit'},
        '1-st map: handicap fnatic -3.5': {'2.55': 'favorit'},
        '1-st map: handicap fnatic -4.5': {'2.99': 'favorit'},
        '1-st map: handicap heroic +2.5': {'1.64': 'favorit'},
        '1-st map: handicap heroic +3.5': {'1.45': 'favorit'},
        '1-st map: handicap heroic +4.5': {'1.32': 'favorit'},
        '1-st map: handicap heroic -2.5': {'2.23': 'favorit'},
        '1-st map: handicap heroic -3.5': {'2.64': 'favorit'},
        '1-st map: heroic will win': {'1.91': 'favorit'},
        '1-st map: odd / even even': {'1.80': 'favorit'},
        '1-st map: odd / even odd': {'1.94': 'favorit'},
        '1-st map: total over 24.5': {'1.29': 'favorit'},
        '1-st map: total over 25.5': {'1.60': 'favorit'},
        '1-st map: total over 26.5': {'1.85': 'favorit'},
        '1-st map: total over 27.5': {'2.21': 'favorit'},
        '1-st map: total over 28.5': {'2.79': 'favorit'},
        '1-st map: total under 24.5': {'3.15': 'favorit'},
        '1-st map: total under 25.5': {'2.20': 'favorit'},
        '1-st map: total under 26.5': {'1.89': 'favorit'},
        '1-st map: total under 27.5': {'1.60': 'favorit'},
        '1-st map: total under 28.5': {'1.37': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? fnatic': {'1.84': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? heroic': {'1.90': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? fnatic': {'1.85': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? heroic': {'1.89': 'favorit'},
        'correct score 0-2': {'3.65': 'favorit'},
        'correct score 1-2': {'3.60': 'favorit'},
        'correct score 2-0': {'3.40': 'favorit'},
        'correct score 2-1': {'3.30': 'favorit'},
        'fnatic handicap +1.5 maps': {'1.25': 'favorit'},
        'fnatic handicap -1.5 maps': {'3.40': 'favorit'},
        'fnatic will win': {'1.77': 'favorit'},
        'heroic handicap +1.5 maps': {'1.28': 'favorit'},
        'heroic handicap -1.5 maps': {'3.65': 'favorit'},
        'heroic will win': {'1.98': 'favorit'},
        'total over 2.5': {'1.80': 'favorit'},
        'total under 2.5': {'1.95': 'favorit'}
    },
    'godsent - og': {
        '1-st map: godsent will win': {'1.82': 'favorit'},
        '1-st map: handicap godsent +2.5': {'1.57': 'favorit'},
        '1-st map: handicap godsent +3.5': {'1.40': 'favorit'},
        '1-st map: handicap godsent -2.5': {'2.15': 'favorit'},
        '1-st map: handicap godsent -3.5': {'2.53': 'favorit'},
        '1-st map: handicap godsent -4.5': {'2.96': 'favorit'},
        '1-st map: handicap og +2.5': {'1.65': 'favorit'},
        '1-st map: handicap og +3.5': {'1.46': 'favorit'},
        '1-st map: handicap og +4.5': {'1.33': 'favorit'},
        '1-st map: handicap og -2.5': {'2.25': 'favorit'},
        '1-st map: handicap og -3.5': {'2.67': 'favorit'},
        '1-st map: odd / even even': {'1.80': 'favorit'},
        '1-st map: odd / even odd': {'1.94': 'favorit'},
        '1-st map: og will win': {'1.92': 'favorit'},
        '1-st map: total over 24.5': {'1.29': 'favorit'},
        '1-st map: total over 25.5': {'1.60': 'favorit'},
        '1-st map: total over 26.5': {'1.85': 'favorit'},
        '1-st map: total over 27.5': {'2.21': 'favorit'},
        '1-st map: total over 28.5': {'2.79': 'favorit'},
        '1-st map: total under 24.5': {'3.15': 'favorit'},
        '1-st map: total under 25.5': {'2.20': 'favorit'},
        '1-st map: total under 26.5': {'1.89': 'favorit'},
        '1-st map: total under 27.5': {'1.59': 'favorit'},
        '1-st map: total under 28.5': {'1.37': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? godsent': {'1.83': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? og': {'1.91': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? godsent': {'1.84': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? og': {'1.90': 'favorit'},
        'correct score 0-2': {'3.85': 'favorit'},
        'correct score 1-2': {'3.65': 'favorit'},
        'correct score 2-0': {'3.05': 'favorit'},
        'correct score 2-1': {'3.50': 'favorit'},
        'godsent handicap +1.5 maps': {'1.23': 'favorit'},
        'godsent handicap -1.5 maps': {'3.05': 'favorit'},
        'godsent will win': {'1.78': 'favorit'},
        'og handicap +1.5 maps': {'1.35': 'favorit'},
        'og handicap -1.5 maps': {'3.85': 'favorit'},
        'og will win': {'1.96': 'favorit'},
        'total over 2.5': {'1.90': 'favorit'},
        'total under 2.5': {'1.84': 'favorit'}
    },
    'hard legion - sprout': {
        '1-st map: handicap hard legion +2.5': {'1.95': 'favorit'},
        '1-st map: handicap hard legion +3.5': {'1.66': 'favorit'},
        '1-st map: handicap hard legion +4.5': {'1.49': 'favorit'},
        '1-st map: handicap sprout -2.5': {'1.80': 'favorit'},
        '1-st map: handicap sprout -3.5': {'2.10': 'favorit'},
        '1-st map: handicap sprout -4.5': {'2.45': 'favorit'},
        '1-st map: hard legion will win': {'2.33': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: sprout will win': {'1.56': 'favorit'},
        '1-st map: total over 25.5': {'1.64': 'favorit'},
        '1-st map: total over 26.5': {'1.90': 'favorit'},
        '1-st map: total over 27.5': {'2.26': 'favorit'},
        '1-st map: total under 25.5': {'2.13': 'favorit'},
        '1-st map: total under 26.5': {'1.84': 'favorit'},
        '1-st map: total under 27.5': {'1.57': 'favorit'},
        'correct score 0-2': {'2.53': 'favorit'},
        'correct score 1-2': {'3.10': 'favorit'},
        'correct score 2-0': {'5.20': 'favorit'},
        'correct score 2-1': {'4.30': 'favorit'},
        'hard legion handicap +1.5 maps': {'1.48': 'favorit'},
        'hard legion handicap -1.5 maps': {'5.20': 'favorit'},
        'hard legion will win': {'2.57': 'favorit'},
        'sprout handicap +1.5 maps': {'1.14': 'favorit'},
        'sprout handicap -1.5 maps': {'2.53': 'favorit'},
        'sprout will win': {'1.47': 'favorit'},
        'total over 2.5': {'2.08': 'favorit'},
        'total under 2.5': {'1.70': 'favorit'}
    },
    'ldlc - secret': {
        '1-st map: handicap ldlc +2.5': {'1.95': 'favorit'},
        '1-st map: handicap secret -2.5': {'1.80': 'favorit'},
        '1-st map: ldlc will win': {'2.33': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: secret will win': {'1.56': 'favorit'},
        '1-st map: total over 26.5': {'1.90': 'favorit'},
        '1-st map: total under 26.5': {'1.84': 'favorit'},
        'correct score 0-2': {'2.63': 'favorit'},
        'correct score 1-2': {'3.30': 'favorit'},
        'correct score 2-0': {'5.00': 'favorit'},
        'correct score 2-1': {'3.80': 'favorit'},
        'ldlc handicap +1.5 maps': {'1.45': 'favorit'},
        'ldlc will win': {'2.39': 'favorit'},
        'secret handicap -1.5 maps': {'2.63': 'favorit'},
        'secret will win': {'1.53': 'favorit'},
        'total over 2.5': {'1.93': 'favorit'},
        'total under 2.5': {'1.81': 'favorit'}
    },
    'level up - thedice': {
        '1-st map: handicap level up -2.5': {'1.97': 'favorit'},
        '1-st map: handicap thedice +2.5': {'1.78': 'favorit'},
        '1-st map: level up will win': {'1.68': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: thedice will win': {'2.11': 'favorit'},
        '1-st map: total over 26.5': {'1.88': 'favorit'},
        '1-st map: total under 26.5': {'1.86': 'favorit'},
        'correct score 0-2': {'4.35': 'favorit'},
        'correct score 1-2': {'3.80': 'favorit'},
        'correct score 2-0': {'2.75': 'favorit'},
        'correct score 2-1': {'3.20': 'favorit'},
        'level up handicap -1.5 maps': {'2.75': 'favorit'},
        'level up will win': {'1.61': 'favorit'},
        'thedice handicap +1.5 maps': {'1.42': 'favorit'},
        'thedice will win': {'2.22': 'favorit'},
        'total over 2.5': {'2.08': 'favorit'},
        'total under 2.5': {'1.70': 'favorit'}
    },
    'new england whalers - recon 5': {
        '1-st map: handicap new england whalers -2.5': {'2.08': 'favorit'},
        '1-st map: handicap recon 5 +2.5': {'1.70': 'favorit'},
        '1-st map: new england whalers will win': {'1.75': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: recon 5 will win': {'2.00': 'favorit'},
        '1-st map: total over 26.5': {'1.79': 'favorit'},
        '1-st map: total under 26.5': {'1.95': 'favorit'},
        'correct score 0-2': {'4.55': 'favorit'},
        'correct score 1-2': {'4.30': 'favorit'},
        'correct score 2-0': {'2.65': 'favorit'},
        'correct score 2-1': {'3.20': 'favorit'},
        'new england whalers handicap -1.5 maps': {'2.65': 'favorit'},
        'new england whalers will win': {'1.54': 'favorit'},
        'recon 5 handicap +1.5 maps': {'1.45': 'favorit'},
        'recon 5 will win': {'2.37': 'favorit'},
        'total over 2.5': {'2.12': 'favorit'},
        'total under 2.5': {'1.67': 'favorit'}
    },
    'nexus - saw': {
        '1-st map: handicap nexus +3.5': {'1.79': 'favorit'},
        '1-st map: handicap saw -3.5': {'1.95': 'favorit'},
        '1-st map: nexus will win': {'2.64': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: saw will win': {'1.45': 'favorit'},
        '1-st map: total over 26.5': {'1.85': 'favorit'},
        '1-st map: total under 26.5': {'1.89': 'favorit'},
        'correct score 0-2': {'2.15': 'favorit'},
        'correct score 1-2': {'3.10': 'favorit'},
        'correct score 2-0': {'6.40': 'favorit'},
        'correct score 2-1': {'5.00': 'favorit'},
        'nexus handicap +1.5 maps': {'1.65': 'favorit'},
        'nexus will win': {'3.05': 'favorit'},
        'saw handicap -1.5 maps': {'2.15': 'favorit'},
        'saw will win': {'1.34': 'favorit'},
        'total over 2.5': {'2.23': 'favorit'},
        'total under 2.5': {'1.61': 'favorit'}
    },
    'ninjas in pyjamas - north': {
        '1-st map: handicap ninjas in pyjamas -2.5': {'1.49': 'favorit'},
        '1-st map: handicap ninjas in pyjamas -3.5': {'1.74': 'favorit'},
        '1-st map: handicap ninjas in pyjamas -4.5': {'2.02': 'favorit'},
        '1-st map: handicap ninjas in pyjamas -5.5': {'2.32': 'favorit'},
        '1-st map: handicap ninjas in pyjamas -6.5': {'2.67': 'favorit'},
        '1-st map: handicap north +2.5': {'2.40': 'favorit'},
        '1-st map: handicap north +3.5': {'2.01': 'favorit'},
        '1-st map: handicap north +4.5': {'1.71': 'favorit'},
        '1-st map: handicap north +5.5': {'1.54': 'favorit'},
        '1-st map: handicap north +6.5': {'1.40': 'favorit'},
        '1-st map: ninjas in pyjamas will win': {'1.34': 'favorit'},
        '1-st map: north will win': {'3.05': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: total over 24.5': {'1.42': 'favorit'},
        '1-st map: total over 25.5': {'1.65': 'favorit'},
        '1-st map: total over 26.5': {'1.94': 'favorit'},
        '1-st map: total over 27.5': {'2.33': 'favorit'},
        '1-st map: total over 28.5': {'2.98': 'favorit'},
        '1-st map: total under 24.5': {'2.59': 'favorit'},
        '1-st map: total under 25.5': {'2.11': 'favorit'},
        '1-st map: total under 26.5': {'1.80': 'favorit'},
        '1-st map: total under 27.5': {'1.54': 'favorit'},
        '1-st map: total under 28.5': {'1.33': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? ninjas in pyjamas': {'1.43': 'favorit'},
        '1-st map: which will be the first to win 10 rounds? north': {'2.68': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? ninjas in pyjamas': {'1.54': 'favorit'},
        '1-st map: which will be the first to win 5 rounds? north': {'2.38': 'favorit'},
        'correct score 0-2': {'7.60': 'favorit'},
        'correct score 1-2': {'6.75': 'favorit'},
        'correct score 2-0': {'1.87': 'favorit'},
        'correct score 2-1': {'2.90': 'favorit'},
        'ninjas in pyjamas handicap +1.5 maps': {'1.06': 'favorit'},
        'ninjas in pyjamas handicap -1.5 maps': {'1.87': 'favorit'},
        'ninjas in pyjamas will win': {'1.22': 'favorit'},
        'north handicap +1.5 maps': {'1.87': 'favorit'},
        'north handicap -1.5 maps': {'7.60': 'favorit'},
        'north will win': {'4.00': 'favorit'},
        'total over 2.5': {'2.40': 'favorit'},
        'total under 2.5': {'1.53': 'favorit'}
    },
    'sangal - tricked': {
        '1-st map: handicap sangal +3.5': {'1.78': 'favorit'},
        '1-st map: handicap tricked -3.5': {'1.97': 'favorit'},
        '1-st map: odd / even even': {'1.71': 'favorit'},
        '1-st map: odd / even odd': {'2.06': 'favorit'},
        '1-st map: sangal will win': {'2.55': 'favorit'},
        '1-st map: total over 26.5': {'1.93': 'favorit'},
        '1-st map: total under 26.5': {'1.81': 'favorit'},
        '1-st map: tricked will win': {'1.47': 'favorit'},
        'correct score 0-2': {'2.20': 'favorit'},
        'correct score 1-2': {'3.10': 'favorit'},
        'correct score 2-0': {'6.10': 'favorit'},
        'correct score 2-1': {'4.70': 'favorit'},
        'sangal handicap +1.5 maps': {'1.62': 'favorit'},
        'sangal will win': {'2.89': 'favorit'},
        'total over 2.5': {'2.16': 'favorit'},
        'total under 2.5': {'1.65': 'favorit'},
        'tricked handicap -1.5 maps': {'2.20': 'favorit'},
        'tricked will win': {'1.38': 'favorit'}
    },
    'tenerife titans - winstrike': {
        '1-st map: handicap tenerife titans +5.5': {'1.77': 'favorit'},
        '1-st map: handicap winstrike -5.5': {'1.98': 'favorit'},
        '1-st map: odd / even even': {'1.80': 'favorit'},
        '1-st map: odd / even odd': {'1.94': 'favorit'},
        '1-st map: tenerife titans will win': {'3.85': 'favorit'},
        '1-st map: total over 25.5': {'1.77': 'favorit'},
        '1-st map: total under 25.5': {'1.98': 'favorit'},
        '1-st map: winstrike will win': {'1.23': 'favorit'},
        'correct score 0-2': {'1.50': 'favorit'},
        'correct score 1-2': {'3.50': 'favorit'},
        'correct score 2-0': {'11.50': 'favorit'},
        'correct score 2-1': {'8.00': 'favorit'},
        'tenerife titans handicap +1.5 maps': {'2.50': 'favorit'},
        'tenerife titans will win': {'5.20': 'favorit'},
        'total over 2.5': {'3.10': 'favorit'},
        'total under 2.5': {'1.34': 'favorit'},
        'winstrike handicap -1.5 maps': {'1.50': 'favorit'},
        'winstrike will win': {'1.14': 'favorit'}
    }
}
