bets = {
    '100 thieves - gen.g': {
        '1-st map: 100 thieves will win': {'1.63': 'marathon'},
        '1-st map: gen.g will win': {'2.22': 'marathon'},
        '1-st map: handicap 100 thieves -2.5': {'1.86': 'marathon'},
        '1-st map: handicap gen.g +2.5': {'1.90': 'marathon'},
        '1-st map: most kills 100 thieves': {'1.59': 'marathon'},
        '1-st map: most kills equal number': {'24.00': 'marathon'},
        '1-st map: most kills gen.g': {'2.40': 'marathon'},
        '1-st map: most kills with handicap 100 thieves -4.5': {'1.88': 'marathon'},
        '1-st map: most kills with handicap gen.g +4.5': {'1.88': 'marathon'},
        '1-st map: total even': {'1.77': 'marathon'},
        '1-st map: total kills 100 thieves even': {'1.88': 'marathon'},
        '1-st map: total kills 100 thieves odd': {'1.88': 'marathon'},
        '1-st map: total kills 100 thieves over 94.5': {'1.90': 'marathon'},
        '1-st map: total kills 100 thieves under 94.5': {'1.86': 'marathon'},
        '1-st map: total kills even': {'1.88': 'marathon'},
        '1-st map: total kills gen.g even': {'1.88': 'marathon'},
        '1-st map: total kills gen.g odd': {'1.88': 'marathon'},
        '1-st map: total kills gen.g over 89.5': {'1.86': 'marathon'},
        '1-st map: total kills gen.g under 89.5': {'1.90': 'marathon'},
        '1-st map: total kills odd': {'1.88': 'marathon'},
        '1-st map: total kills over 184.5': {'1.87': 'marathon'},
        '1-st map: total kills under 184.5': {'1.89': 'marathon'},
        '1-st map: total odd': {'2.01': 'marathon'},
        '1-st map: total over 26.5': {'1.77': 'marathon'},
        '1-st map: total under 26.5': {'2.01': 'marathon'},
        '100 thieves handicap -1.5 maps': {'2.76': 'marathon'},
        '100 thieves will win': {'1.54': 'marathon'},
        '2-nd map: 100 thieves will win': {'1.63': 'marathon'},
        '2-nd map: gen.g will win': {'2.22': 'marathon'},
        '2-nd map: handicap 100 thieves -2.5': {'1.86': 'marathon'},
        '2-nd map: handicap gen.g +2.5': {'1.90': 'marathon'},
        '2-nd map: most kills 100 thieves': {'1.59': 'marathon'},
        '2-nd map: most kills equal number': {'24.00': 'marathon'},
        '2-nd map: most kills gen.g': {'2.40': 'marathon'},
        '2-nd map: most kills with handicap 100 thieves -4.5': {'1.88': 'marathon'},
        '2-nd map: most kills with handicap gen.g +4.5': {'1.88': 'marathon'},
        '2-nd map: total even': {'1.77': 'marathon'},
        '2-nd map: total kills 100 thieves even': {'1.88': 'marathon'},
        '2-nd map: total kills 100 thieves odd': {'1.88': 'marathon'},
        '2-nd map: total kills 100 thieves over 94.5': {'1.90': 'marathon'},
        '2-nd map: total kills 100 thieves under 94.5': {'1.86': 'marathon'},
        '2-nd map: total kills even': {'1.88': 'marathon'},
        '2-nd map: total kills gen.g even': {'1.88': 'marathon'},
        '2-nd map: total kills gen.g odd': {'1.88': 'marathon'},
        '2-nd map: total kills gen.g over 89.5': {'1.86': 'marathon'},
        '2-nd map: total kills gen.g under 89.5': {'1.90': 'marathon'},
        '2-nd map: total kills odd': {'1.88': 'marathon'},
        '2-nd map: total kills over 184.5': {'1.87': 'marathon'},
        '2-nd map: total kills under 184.5': {'1.89': 'marathon'},
        '2-nd map: total odd': {'2.01': 'marathon'},
        '2-nd map: total over 26.5': {'1.77': 'marathon'},
        '2-nd map: total under 26.5': {'2.01': 'marathon'},
        'correct score 0-2': {'5.25': 'marathon'},
        'correct score 1-2': {'4.30': 'marathon'},
        'correct score 2-0': {'2.76': 'marathon'},
        'correct score 2-1': {'3.14': 'marathon'},
        'gen.g handicap +1.5 maps': {'1.43': 'marathon'},
        'gen.g will win': {'2.48': 'marathon'},
        'handicap 100 thieves -1.5': {'1.60': 'marathon'},
        'handicap 100 thieves -2.5': {'1.666': 'marathon'},
        'handicap 100 thieves -3.5': {'1.74': 'marathon'},
        'handicap 100 thieves -4.5': {'1.83': 'marathon'},
        'handicap 100 thieves -5.5': {'1.95': 'marathon'},
        'handicap 100 thieves -6.5': {'2.12': 'marathon'},
        'handicap 100 thieves -7.5': {'2.34': 'marathon'},
        'handicap gen.g +1.5': {'2.30': 'marathon'},
        'handicap gen.g +2.5': {'2.18': 'marathon'},
        'handicap gen.g +3.5': {'2.06': 'marathon'},
        'handicap gen.g +4.5': {'1.95': 'marathon'},
        'handicap gen.g +5.5': {'1.83': 'marathon'},
        'handicap gen.g +6.5': {'1.70': 'marathon'},
        'handicap gen.g +7.5': {'1.58': 'marathon'},
        'most kills 100 thieves': {'1.45': 'marathon'},
        'most kills 100 thieves or equal number': {'1.39': 'marathon'},
        'most kills equal number': {'30.00': 'marathon'},
        'most kills gen.g': {'2.74': 'marathon'},
        'most kills gen.g or equal number': {'2.52': 'marathon'},
        'most kills with handicap 100 thieves -10.5': {'1.87': 'marathon'},
        'most kills with handicap gen.g +10.5': {'1.89': 'marathon'},
        'total even': {'1.90': 'marathon'},
        'total kills 100 thieves even': {'1.88': 'marathon'},
        'total kills 100 thieves odd': {'1.88': 'marathon'},
        'total kills 100 thieves over 232.5': {'1.88': 'marathon'},
        'total kills 100 thieves under 232.5': {'1.88': 'marathon'},
        'total kills even': {'1.88': 'marathon'},
        'total kills gen.g even': {'1.88': 'marathon'},
        'total kills gen.g odd': {'1.88': 'marathon'},
        'total kills gen.g over 221.5': {'1.88': 'marathon'},
        'total kills gen.g under 221.5': {'1.88': 'marathon'},
        'total kills odd': {'1.88': 'marathon'},
        'total kills over 454.5': {'1.88': 'marathon'},
        'total kills under 454.5': {'1.88': 'marathon'},
        'total odd': {'1.90': 'marathon'},
        'total over 2.5': {'1.94': 'marathon'},
        'total over 63.5': {'1.81': 'marathon'},
        'total over 64.5': {'1.84': 'marathon'},
        'total over 65.5': {'1.87': 'marathon'},
        'total over 66.5': {'1.90': 'marathon'},
        'total over 67.5': {'1.909': 'marathon'},
        'total over 68.5': {'1.93': 'marathon'},
        'total over 69.5': {'1.952': 'marathon'},
        'total under 2.5': {'1.83': 'marathon'},
        'total under 63.5': {'1.952': 'marathon'},
        'total under 64.5': {'1.92': 'marathon'},
        'total under 65.5': {'1.89': 'marathon'},
        'total under 66.5': {'1.88': 'marathon'},
        'total under 67.5': {'1.85': 'marathon'},
        'total under 68.5': {'1.833': 'marathon'},
        'total under 69.5': {'1.81': 'marathon'}
    },
    'ahq - asking questions': {
        'ahq handicap -1.5 maps': {'2.57': 'marathon'},
        'ahq will win': {'1.47': 'marathon'},
        'asking questions handicap +1.5 maps': {'1.49': 'marathon'},
        'asking questions will win': {'2.68': 'marathon'},
        'correct score 0-2': {'5.85': 'marathon'},
        'correct score 1-2': {'4.55': 'marathon'},
        'correct score 2-0': {'2.57': 'marathon'},
        'correct score 2-1': {'3.08': 'marathon'},
        'total even': {'1.80': 'marathon'},
        'total odd': {'1.97': 'marathon'},
        'total over 2.5': {'1.97': 'marathon'},
        'total under 2.5': {'1.80': 'marathon'}
    },
    'aim4r - w2c': {
        'aim4r handicap +1.5 maps': {'1.44': 'marathon'},
        'aim4r will win': {'2.50': 'marathon'},
        'correct score 0-2': {'2.73': 'marathon'},
        'correct score 1-2': {'3.14': 'marathon'},
        'correct score 2-0': {'5.30': 'marathon'},
        'correct score 2-1': {'4.333': 'marathon'},
        'total even': {'1.83': 'marathon'},
        'total odd': {'1.94': 'marathon'},
        'total over 2.5': {'1.94': 'marathon'},
        'total under 2.5': {'1.83': 'marathon'},
        'w2c handicap -1.5 maps': {'2.73': 'marathon'},
        'w2c will win': {'1.53': 'marathon'}
    },
    'alternate attax - fate': {
        'alternate attax will win': {'1.53': 'marathon'},
        'fate will win': {'2.50': 'marathon'}
    },
    'ambush - apeks': {
        'ambush handicap +1.5 maps': {'1.46': 'marathon'},
        'ambush will win': {'2.56': 'marathon'},
        'apeks handicap -1.5 maps': {'2.67': 'marathon'},
        'apeks will win': {'1.51': 'marathon'},
        'correct score 0-2': {'2.67': 'marathon'},
        'correct score 1-2': {'3.125': 'marathon'},
        'correct score 2-0': {'5.50': 'marathon'},
        'correct score 2-1': {'4.40': 'marathon'},
        'total even': {'1.82': 'marathon'},
        'total odd': {'1.95': 'marathon'},
        'total over 2.5': {'1.95': 'marathon'},
        'total under 2.5': {'1.82': 'marathon'}
    },
    'apeks - nemiga gaming': {
        'apeks will win': {'3.45': 'marathon'},
        'nemiga gaming will win': {'1.31': 'marathon'}
    },
    'atk - good gaming': {
        'atk will win': {'1.25': 'marathon'},
        'good gaming will win': {'3.96': 'marathon'}
    },
    'avant - paradox': {
        'avant handicap -1.5 maps': {'1.96': 'marathon'},
        'avant will win': {'1.25': 'marathon'},
        'correct score 0-2': {'9.60': 'marathon'},
        'correct score 1-2': {'6.30': 'marathon'},
        'correct score 2-0': {'1.96': 'marathon'},
        'correct score 2-1': {'3.02': 'marathon'},
        'paradox handicap +1.5 maps': {'1.81': 'marathon'},
        'paradox will win': {'3.95': 'marathon'},
        'total even': {'1.64': 'marathon'},
        'total odd': {'2.21': 'marathon'},
        'total over 2.5': {'2.21': 'marathon'},
        'total under 2.5': {'1.64': 'marathon'}
    },
    'baecon gaming group - big academy': {
        'baecon gaming group will win': {'2.53': 'marathon'},
        'big academy will win': {'1.52': 'marathon'}
    },
    'baecon gaming group - gameagents': {
        'baecon gaming group will win': {'2.28': 'marathon'},
        'gameagents will win': {'1.63': 'marathon'}
    },
    'big - vitality': {
        '1-st map: big will win': {'1.77': 'marathon'},
        '1-st map: handicap big -2.5': {'2.03': 'marathon'},
        '1-st map: handicap vitality +2.5': {'1.75': 'marathon'},
        '1-st map: most kills big': {'1.81': 'marathon'},
        '1-st map: most kills equal number': {'24.00': 'marathon'},
        '1-st map: most kills vitality': {'2.03': 'marathon'},
        '1-st map: most kills with handicap big -1.5': {'1.89': 'marathon'},
        '1-st map: most kills with handicap vitality +1.5': {'1.87': 'marathon'},
        '1-st map: total even': {'1.76': 'marathon'},
        '1-st map: total kills big even': {'1.88': 'marathon'},
        '1-st map: total kills big odd': {'1.88': 'marathon'},
        '1-st map: total kills big over 93.5': {'1.90': 'marathon'},
        '1-st map: total kills big under 93.5': {'1.86': 'marathon'},
        '1-st map: total kills even': {'1.88': 'marathon'},
        '1-st map: total kills odd': {'1.88': 'marathon'},
        '1-st map: total kills over 185.5': {'1.86': 'marathon'},
        '1-st map: total kills under 185.5': {'1.90': 'marathon'},
        '1-st map: total kills vitality even': {'1.88': 'marathon'},
        '1-st map: total kills vitality odd': {'1.88': 'marathon'},
        '1-st map: total kills vitality over 91.5': {'1.84': 'marathon'},
        '1-st map: total kills vitality under 91.5': {'1.92': 'marathon'},
        '1-st map: total odd': {'2.02': 'marathon'},
        '1-st map: total over 26.5': {'1.75': 'marathon'},
        '1-st map: total under 26.5': {'2.03': 'marathon'},
        '1-st map: vitality will win': {'2.01': 'marathon'},
        '2-nd map: big will win': {'1.77': 'marathon'},
        '2-nd map: handicap big -2.5': {'2.03': 'marathon'},
        '2-nd map: handicap vitality +2.5': {'1.75': 'marathon'},
        '2-nd map: most kills big': {'1.81': 'marathon'},
        '2-nd map: most kills equal number': {'24.00': 'marathon'},
        '2-nd map: most kills vitality': {'2.03': 'marathon'},
        '2-nd map: most kills with handicap big -1.5': {'1.89': 'marathon'},
        '2-nd map: most kills with handicap vitality +1.5': {'1.87': 'marathon'},
        '2-nd map: total even': {'1.76': 'marathon'},
        '2-nd map: total kills big even': {'1.88': 'marathon'},
        '2-nd map: total kills big odd': {'1.88': 'marathon'},
        '2-nd map: total kills big over 93.5': {'1.90': 'marathon'},
        '2-nd map: total kills big under 93.5': {'1.86': 'marathon'},
        '2-nd map: total kills even': {'1.88': 'marathon'},
        '2-nd map: total kills odd': {'1.88': 'marathon'},
        '2-nd map: total kills over 185.5': {'1.86': 'marathon'},
        '2-nd map: total kills under 185.5': {'1.90': 'marathon'},
        '2-nd map: total kills vitality even': {'1.88': 'marathon'},
        '2-nd map: total kills vitality odd': {'1.88': 'marathon'},
        '2-nd map: total kills vitality over 91.5': {'1.84': 'marathon'},
        '2-nd map: total kills vitality under 91.5': {'1.92': 'marathon'},
        '2-nd map: total odd': {'2.02': 'marathon'},
        '2-nd map: total over 26.5': {'1.75': 'marathon'},
        '2-nd map: total under 26.5': {'2.03': 'marathon'},
        '2-nd map: vitality will win': {'2.01': 'marathon'},
        'big handicap -1.5 maps': {'3.28': 'marathon'},
        'big will win': {'1.74': 'marathon'},
        'correct score 0-2': {'4.20': 'marathon'},
        'correct score 1-2': {'3.80': 'marathon'},
        'correct score 2-0': {'3.28': 'marathon'},
        'correct score 2-1': {'3.35': 'marathon'},
        'handicap big -0.5': {'1.76': 'marathon'},
        'handicap big -1.5': {'1.83': 'marathon'},
        'handicap big -2.5': {'1.90': 'marathon'},
        'handicap big -3.5': {'1.99': 'marathon'},
        'handicap big -4.5': {'2.11': 'marathon'},
        'handicap big -5.5': {'2.28': 'marathon'},
        'handicap big 0': {'1.72': 'marathon'},
        'handicap vitality +0.5': {'2.04': 'marathon'},
        'handicap vitality +1.5': {'1.95': 'marathon'},
        'handicap vitality +2.5': {'1.88': 'marathon'},
        'handicap vitality +3.5': {'1.80': 'marathon'},
        'handicap vitality +4.5': {'1.71': 'marathon'},
        'handicap vitality +5.5': {'1.61': 'marathon'},
        'handicap vitality 0': {'2.09': 'marathon'},
        'most kills big': {'1.74': 'marathon'},
        'most kills big or equal number': {'1.65': 'marathon'},
        'most kills equal number': {'29.00': 'marathon'},
        'most kills vitality': {'2.09': 'marathon'},
        'most kills vitality or equal number': {'1.96': 'marathon'},
        'most kills with handicap big -3.5': {'1.89': 'marathon'},
        'most kills with handicap vitality +3.5': {'1.87': 'marathon'},
        'total even': {'1.90': 'marathon'},
        'total kills big even': {'1.88': 'marathon'},
        'total kills big odd': {'1.88': 'marathon'},
        'total kills big over 234.5': {'1.88': 'marathon'},
        'total kills big under 234.5': {'1.88': 'marathon'},
        'total kills even': {'1.88': 'marathon'},
        'total kills odd': {'1.88': 'marathon'},
        'total kills over 471.5': {'1.88': 'marathon'},
        'total kills under 471.5': {'1.88': 'marathon'},
        'total kills vitality even': {'1.88': 'marathon'},
        'total kills vitality odd': {'1.88': 'marathon'},
        'total kills vitality over 231.5': {'1.88': 'marathon'},
        'total kills vitality under 231.5': {'1.88': 'marathon'},
        'total odd': {'1.90': 'marathon'},
        'total over 2.5': {'1.88': 'marathon'},
        'total over 65.5': {'1.83': 'marathon'},
        'total over 66.5': {'1.85': 'marathon'},
        'total over 67.5': {'1.86': 'marathon'},
        'total over 68.5': {'1.89': 'marathon'},
        'total over 69.5': {'1.909': 'marathon'},
        'total over 70.5': {'1.94': 'marathon'},
        'total over 71.5': {'1.99': 'marathon'},
        'total under 2.5': {'1.88': 'marathon'},
        'total under 65.5': {'1.93': 'marathon'},
        'total under 66.5': {'1.909': 'marathon'},
        'total under 67.5': {'1.90': 'marathon'},
        'total under 68.5': {'1.89': 'marathon'},
        'total under 69.5': {'1.85': 'marathon'},
        'total under 70.5': {'1.82': 'marathon'},
        'total under 71.5': {'1.78': 'marathon'},
        'vitality handicap +1.5 maps': {'1.32': 'marathon'},
        'vitality will win': {'2.09': 'marathon'}
    },
    'big academy - gameagents': {
        'big academy will win': {'1.56': 'marathon'},
        'gameagents will win': {'2.43': 'marathon'}
    },
    'brute - tikitakan': {
        '1-st map: brute will win': {'1.98': 'marathon'},
        '1-st map: handicap brute +2.5': {'1.727': 'marathon'},
        '1-st map: handicap tikitakan -2.5': {'2.06': 'marathon'},
        '1-st map: tikitakan will win': {'1.79': 'marathon'},
        '1-st map: total even': {'1.76': 'marathon'},
        '1-st map: total odd': {'2.02': 'marathon'},
        '1-st map: total over 26.5': {'1.75': 'marathon'},
        '1-st map: total under 26.5': {'2.03': 'marathon'},
        '2-nd map: brute will win': {'1.98': 'marathon'},
        '2-nd map: handicap brute +2.5': {'1.727': 'marathon'},
        '2-nd map: handicap tikitakan -2.5': {'2.06': 'marathon'},
        '2-nd map: tikitakan will win': {'1.79': 'marathon'},
        '2-nd map: total even': {'1.76': 'marathon'},
        '2-nd map: total odd': {'2.02': 'marathon'},
        '2-nd map: total over 26.5': {'1.75': 'marathon'},
        '2-nd map: total under 26.5': {'2.03': 'marathon'},
        'brute handicap +1.5 maps': {'1.31': 'marathon'},
        'brute will win': {'2.05': 'marathon'},
        'correct score 0-2': {'3.34': 'marathon'},
        'correct score 1-2': {'3.40': 'marathon'},
        'correct score 2-0': {'4.10': 'marathon'},
        'correct score 2-1': {'3.75': 'marathon'},
        'handicap brute +1.5': {'1.909': 'marathon'},
        'handicap tikitakan -1.5': {'1.87': 'marathon'},
        'tikitakan handicap -1.5 maps': {'3.34': 'marathon'},
        'tikitakan will win': {'1.77': 'marathon'},
        'total even': {'1.90': 'marathon'},
        'total odd': {'1.90': 'marathon'},
        'total over 2.5': {'1.88': 'marathon'},
        'total over 68.5': {'1.89': 'marathon'},
        'total under 2.5': {'1.88': 'marathon'},
        'total under 68.5': {'1.89': 'marathon'}
    },
    'chiefs - truckers with attitude': {
        'chiefs handicap -1.5 maps': {'1.79': 'marathon'},
        'chiefs will win': {'1.184': 'marathon'},
        'correct score 0-2': {'12.25': 'marathon'},
        'correct score 1-2': {'7.30': 'marathon'},
        'correct score 2-0': {'1.79': 'marathon'},
        'correct score 2-1': {'3.06': 'marathon'},
        'total even': {'1.57': 'marathon'},
        'total odd': {'2.36': 'marathon'},
        'total over 2.5': {'2.36': 'marathon'},
        'total under 2.5': {'1.57': 'marathon'},
        'truckers with attitude handicap +1.5 maps': {'1.99': 'marathon'},
        'truckers with attitude will win': {'4.80': 'marathon'}
    },
    'cloud9 - furia': {
        '1-st map: cloud9 will win': {'2.57': 'marathon'},
        '1-st map: furia will win': {'1.48': 'marathon'},
        '1-st map: handicap cloud9 +3.5': {'1.85': 'marathon'},
        '1-st map: handicap furia -3.5': {'1.909': 'marathon'},
        '1-st map: most kills cloud9': {'2.94': 'marathon'},
        '1-st map: most kills equal number': {'26.00': 'marathon'},
        '1-st map: most kills furia': {'1.41': 'marathon'},
        '1-st map: most kills with handicap cloud9 +8.5': {'1.85': 'marathon'},
        '1-st map: most kills with handicap furia -8.5': {'1.909': 'marathon'},
        '1-st map: total even': {'1.77': 'marathon'},
        '1-st map: total kills cloud9 even': {'1.88': 'marathon'},
        '1-st map: total kills cloud9 odd': {'1.88': 'marathon'},
        '1-st map: total kills cloud9 over 86.5': {'1.87': 'marathon'},
        '1-st map: total kills cloud9 under 86.5': {'1.89': 'marathon'},
        '1-st map: total kills furia even': {'1.88': 'marathon'},
        '1-st map: total kills furia odd': {'1.88': 'marathon'},
        '1-st map: total kills furia over 94.5': {'1.87': 'marathon'},
        '1-st map: total kills furia under 94.5': {'1.89': 'marathon'},
        '1-st map: total kills odd': {'1.88': 'marathon'},
        '1-st map: total odd': {'2.01': 'marathon'},
        '1-st map: total over 26.5': {'1.83': 'marathon'},
        '1-st map: total under 26.5': {'1.93': 'marathon'},
        '2-nd map: cloud9 will win': {'2.57': 'marathon'},
        '2-nd map: furia will win': {'1.48': 'marathon'},
        '2-nd map: handicap cloud9 +3.5': {'1.85': 'marathon'},
        '2-nd map: handicap furia -3.5': {'1.909': 'marathon'},
        '2-nd map: most kills cloud9': {'2.94': 'marathon'},
        '2-nd map: most kills equal number': {'26.00': 'marathon'},
        '2-nd map: most kills furia': {'1.41': 'marathon'},
        '2-nd map: most kills with handicap cloud9 +8.5': {'1.85': 'marathon'},
        '2-nd map: most kills with handicap furia -8.5': {'1.909': 'marathon'},
        '2-nd map: total even': {'1.77': 'marathon'},
        '2-nd map: total kills cloud9 even': {'1.88': 'marathon'},
        '2-nd map: total kills cloud9 odd': {'1.88': 'marathon'},
        '2-nd map: total kills cloud9 over 86.5': {'1.87': 'marathon'},
        '2-nd map: total kills cloud9 under 86.5': {'1.89': 'marathon'},
        '2-nd map: total kills furia even': {'1.88': 'marathon'},
        '2-nd map: total kills furia odd': {'1.88': 'marathon'},
        '2-nd map: total kills furia over 94.5': {'1.87': 'marathon'},
        '2-nd map: total kills furia under 94.5': {'1.89': 'marathon'},
        '2-nd map: total kills odd': {'1.88': 'marathon'},
        '2-nd map: total odd': {'2.01': 'marathon'},
        '2-nd map: total over 26.5': {'1.83': 'marathon'},
        '2-nd map: total under 26.5': {'1.93': 'marathon'},
        'cloud9 handicap +1.5 maps': {'1.615': 'marathon'},
        'cloud9 will win': {'3.20': 'marathon'},
        'correct score 0-2': {'2.25': 'marathon'},
        'correct score 1-2': {'3.02': 'marathon'},
        'correct score 2-0': {'7.30': 'marathon'},
        'correct score 2-1': {'5.25': 'marathon'},
        'furia handicap -1.5 maps': {'2.25': 'marathon'},
        'furia will win': {'1.35': 'marathon'},
        'handicap cloud9 +10.5': {'1.44': 'marathon'},
        'handicap cloud9 +11.5': {'1.33': 'marathon'},
        'handicap cloud9 +3.5': {'2.60': 'marathon'},
        'handicap cloud9 +4.5': {'2.41': 'marathon'},
        'handicap cloud9 +5.5': {'2.22': 'marathon'},
        'handicap cloud9 +6.5': {'2.04': 'marathon'},
        'handicap cloud9 +7.5': {'1.87': 'marathon'},
        'handicap cloud9 +8.5': {'1.70': 'marathon'},
        'handicap cloud9 +9.5': {'1.56': 'marathon'},
        'handicap furia -10.5': {'2.74': 'marathon'},
        'handicap furia -11.5': {'3.25': 'marathon'},
        'handicap furia -3.5': {'1.48': 'marathon'},
        'handicap furia -4.5': {'1.55': 'marathon'},
        'handicap furia -5.5': {'1.64': 'marathon'},
        'handicap furia -6.5': {'1.76': 'marathon'},
        'handicap furia -7.5': {'1.909': 'marathon'},
        'handicap furia -8.5': {'2.12': 'marathon'},
        'handicap furia -9.5': {'2.39': 'marathon'},
        'most kills cloud9': {'3.90': 'marathon'},
        'most kills cloud9 or equal number': {'3.50': 'marathon'},
        'most kills equal number': {'32.00': 'marathon'},
        'most kills furia': {'1.25': 'marathon'},
        'most kills furia or equal number': {'1.21': 'marathon'},
        'most kills with handicap cloud9 +19.5': {'1.87': 'marathon'},
        'most kills with handicap furia -19.5': {'1.89': 'marathon'},
        'total even': {'1.90': 'marathon'},
        'total kills cloud9 even': {'1.88': 'marathon'},
        'total kills cloud9 odd': {'1.88': 'marathon'},
        'total kills cloud9 over 205.5': {'1.88': 'marathon'},
        'total kills cloud9 under 205.5': {'1.88': 'marathon'},
        'total kills even': {'1.88': 'marathon'},
        'total kills furia even': {'1.88': 'marathon'},
        'total kills furia odd': {'1.88': 'marathon'},
        'total kills furia over 223.5': {'1.88': 'marathon'},
        'total kills furia under 223.5': {'1.88': 'marathon'},
        'total kills odd': {'1.88': 'marathon'},
        'total kills over 422.5': {'1.88': 'marathon'},
        'total kills under 422.5': {'1.88': 'marathon'},
        'total odd': {'1.90': 'marathon'},
        'total over 2.5': {'2.06': 'marathon'},
        'total over 59.5': {'1.80': 'marathon'},
        'total over 60.5': {'1.833': 'marathon'},
        'total over 61.5': {'1.86': 'marathon'},
        'total over 62.5': {'1.89': 'marathon'},
        'total over 63.5': {'1.909': 'marathon'},
        'total over 64.5': {'1.94': 'marathon'},
        'total over 65.5': {'1.98': 'marathon'},
        'total under 2.5': {'1.73': 'marathon'},
        'total under 59.5': {'1.97': 'marathon'},
        'total under 60.5': {'1.93': 'marathon'},
        'total under 61.5': {'1.90': 'marathon'},
        'total under 62.5': {'1.89': 'marathon'},
        'total under 63.5': {'1.85': 'marathon'},
        'total under 64.5': {'1.82': 'marathon'},
        'total under 65.5': {'1.79': 'marathon'}
    },
    'cr4zy - lilmix': {
        'correct score 0-2': {'5.80': 'marathon'},
        'correct score 1-2': {'4.55': 'marathon'},
        'correct score 2-0': {'2.57': 'marathon'},
        'correct score 2-1': {'3.10': 'marathon'},
        'cr4zy handicap -1.5 maps': {'2.57': 'marathon'},
        'cr4zy will win': {'1.47': 'marathon'},
        'lilmix handicap +1.5 maps': {'1.49': 'marathon'},
        'lilmix will win': {'2.68': 'marathon'},
        'total even': {'1.80': 'marathon'},
        'total odd': {'1.97': 'marathon'},
        'total over 2.5': {'1.97': 'marathon'},
        'total under 2.5': {'1.80': 'marathon'}
    },
    'd13 - divine vendetta': {
        'correct score 0-2': {'5.60': 'marathon'},
        'correct score 1-2': {'4.50': 'marathon'},
        'correct score 2-0': {'2.63': 'marathon'},
        'correct score 2-1': {'3.10': 'marathon'},
        'd13 handicap -1.5 maps': {'2.63': 'marathon'},
        'd13 will win': {'1.50': 'marathon'},
        'divine vendetta handicap +1.5 maps': {'1.47': 'marathon'},
        'divine vendetta will win': {'2.59': 'marathon'},
        'total even': {'1.82': 'marathon'},
        'total odd': {'1.95': 'marathon'},
        'total over 2.5': {'1.95': 'marathon'},
        'total under 2.5': {'1.82': 'marathon'}
    },
    'divine vendetta - vici gaming': {
        'correct score 0-2': {'1.65': 'marathon'},
        'correct score 1-2': {'3.22': 'marathon'},
        'correct score 2-0': {'12.75': 'marathon'},
        'correct score 2-1': {'9.10': 'marathon'},
        'divine vendetta handicap +1.5 maps': {'2.20': 'marathon'},
        'divine vendetta will win': {'5.75': 'marathon'},
        'total even': {'1.50': 'marathon'},
        'total odd': {'2.54': 'marathon'},
        'total over 2.5': {'2.54': 'marathon'},
        'total under 2.5': {'1.50': 'marathon'},
        'vici gaming handicap -1.5 maps': {'1.65': 'marathon'},
        'vici gaming will win': {'1.137': 'marathon'}
    },
    'energy - sinister5': {
        'correct score 0-2': {'3.70': 'marathon'},
        'correct score 1-2': {'3.56': 'marathon'},
        'correct score 2-0': {'3.68': 'marathon'},
        'correct score 2-1': {'3.56': 'marathon'},
        'energy handicap +1.5 maps': {'1.27': 'marathon'},
        'energy will win': {'1.90': 'marathon'},
        'sinister5 handicap -1.5 maps': {'3.70': 'marathon'},
        'sinister5 will win': {'1.90': 'marathon'},
        'total even': {'1.88': 'marathon'},
        'total odd': {'1.88': 'marathon'},
        'total over 2.5': {'1.88': 'marathon'},
        'total under 2.5': {'1.88': 'marathon'}
    },
    'espada - pact': {
        'correct score 0-2': {'4.90': 'marathon'},
        'correct score 1-2': {'4.15': 'marathon'},
        'correct score 2-0': {'2.90': 'marathon'},
        'correct score 2-1': {'3.18': 'marathon'},
        'espada handicap -1.5 maps': {'2.90': 'marathon'},
        'espada will win': {'1.60': 'marathon'},
        'pact handicap +1.5 maps': {'1.40': 'marathon'},
        'pact will win': {'2.34': 'marathon'},
        'total even': {'1.85': 'marathon'},
        'total odd': {'1.92': 'marathon'},
        'total over 2.5': {'1.92': 'marathon'},
        'total under 2.5': {'1.85': 'marathon'}
    },
    'evil geniuses - liquid': {
        '1-st map: evil geniuses will win': {'1.87': 'marathon'},
        '1-st map: handicap evil geniuses +2.5': {'1.65': 'marathon'},
        '1-st map: handicap liquid -2.5': {'2.18': 'marathon'},
        '1-st map: liquid will win': {'1.89': 'marathon'},
        '1-st map: most kills equal number': {'24.00': 'marathon'},
        '1-st map: most kills evil geniuses': {'1.909': 'marathon'},
        '1-st map: most kills liquid': {'1.92': 'marathon'},
        '1-st map: most kills with handicap evil geniuses -0.5': {'1.909': 'marathon'},
        '1-st map: most kills with handicap liquid +0.5': {'1.85': 'marathon'},
        '1-st map: total even': {'1.76': 'marathon'},
        '1-st map: total kills even': {'1.88': 'marathon'},
        '1-st map: total kills evil geniuses even': {'1.88': 'marathon'},
        '1-st map: total kills evil geniuses odd': {'1.88': 'marathon'},
        '1-st map: total kills evil geniuses over 92.5': {'1.87': 'marathon'},
        '1-st map: total kills evil geniuses under 92.5': {'1.89': 'marathon'},
        '1-st map: total kills liquid even': {'1.88': 'marathon'},
        '1-st map: total kills liquid odd': {'1.88': 'marathon'},
        '1-st map: total kills liquid over 92.5': {'1.87': 'marathon'},
        '1-st map: total kills liquid under 92.5': {'1.89': 'marathon'},
        '1-st map: total kills odd': {'1.88': 'marathon'},
        '1-st map: total kills over 186.5': {'1.90': 'marathon'},
        '1-st map: total kills under 186.5': {'1.86': 'marathon'},
        '1-st map: total odd': {'2.02': 'marathon'},
        '1-st map: total over 26.5': {'1.75': 'marathon'},
        '1-st map: total under 26.5': {'2.03': 'marathon'},
        '2-nd map: evil geniuses will win': {'1.87': 'marathon'},
        '2-nd map: handicap evil geniuses +2.5': {'1.65': 'marathon'},
        '2-nd map: handicap liquid -2.5': {'2.18': 'marathon'},
        '2-nd map: liquid will win': {'1.89': 'marathon'},
        '2-nd map: most kills equal number': {'24.00': 'marathon'},
        '2-nd map: most kills evil geniuses': {'1.909': 'marathon'},
        '2-nd map: most kills liquid': {'1.92': 'marathon'},
        '2-nd map: most kills with handicap evil geniuses -0.5': {'1.909': 'marathon'},
        '2-nd map: most kills with handicap liquid +0.5': {'1.85': 'marathon'},
        '2-nd map: total even': {'1.76': 'marathon'},
        '2-nd map: total kills even': {'1.88': 'marathon'},
        '2-nd map: total kills evil geniuses even': {'1.88': 'marathon'},
        '2-nd map: total kills evil geniuses odd': {'1.88': 'marathon'},
        '2-nd map: total kills evil geniuses over 92.5': {'1.87': 'marathon'},
        '2-nd map: total kills evil geniuses under 92.5': {'1.89': 'marathon'},
        '2-nd map: total kills liquid even': {'1.88': 'marathon'},
        '2-nd map: total kills liquid odd': {'1.88': 'marathon'},
        '2-nd map: total kills liquid over 92.5': {'1.87': 'marathon'},
        '2-nd map: total kills liquid under 92.5': {'1.89': 'marathon'},
        '2-nd map: total kills odd': {'1.88': 'marathon'},
        '2-nd map: total kills over 186.5': {'1.90': 'marathon'},
        '2-nd map: total kills under 186.5': {'1.86': 'marathon'},
        '2-nd map: total odd': {'2.02': 'marathon'},
        '2-nd map: total over 26.5': {'1.75': 'marathon'},
        '2-nd map: total under 26.5': {'2.03': 'marathon'},
        'correct score 0-2': {'3.72': 'marathon'},
        'correct score 1-2': {'3.60': 'marathon'},
        'correct score 2-0': {'3.64': 'marathon'},
        'correct score 2-1': {'3.54': 'marathon'},
        'evil geniuses handicap -1.5 maps': {'3.64': 'marathon'},
        'evil geniuses will win': {'1.88': 'marathon'},
        'handicap evil geniuses +0.5': {'1.83': 'marathon'},
        'handicap evil geniuses +1.5': {'1.76': 'marathon'},
        'handicap evil geniuses -0.5': {'1.90': 'marathon'},
        'handicap evil geniuses -1.5': {'1.97': 'marathon'},
        'handicap evil geniuses -2.5': {'2.08': 'marathon'},
        'handicap evil geniuses -3.5': {'2.18': 'marathon'},
        'handicap evil geniuses 0': {'1.87': 'marathon'},
        'handicap liquid +0.5': {'1.88': 'marathon'},
        'handicap liquid +1.5': {'1.81': 'marathon'},
        'handicap liquid +2.5': {'1.73': 'marathon'},
        'handicap liquid +3.5': {'1.666': 'marathon'},
        'handicap liquid -0.5': {'1.95': 'marathon'},
        'handicap liquid -1.5': {'2.04': 'marathon'},
        'handicap liquid 0': {'1.909': 'marathon'},
        'liquid handicap +1.5 maps': {'1.27': 'marathon'},
        'liquid will win': {'1.92': 'marathon'},
        'most kills equal number': {'29.00': 'marathon'},
        'most kills evil geniuses': {'1.89': 'marathon'},
        'most kills evil geniuses or equal number': {'1.78': 'marathon'},
        'most kills liquid': {'1.909': 'marathon'},
        'most kills liquid or equal number': {'1.80': 'marathon'},
        'most kills with handicap evil geniuses -0.5': {'1.90': 'marathon'},
        'most kills with handicap liquid +0.5': {'1.86': 'marathon'},
        'total even': {'1.90': 'marathon'},
        'total kills even': {'1.88': 'marathon'},
        'total kills evil geniuses even': {'1.88': 'marathon'},
        'total kills evil geniuses odd': {'1.88': 'marathon'},
        'total kills evil geniuses over 233.5': {'1.88': 'marathon'},
        'total kills evil geniuses under 233.5': {'1.88': 'marathon'},
        'total kills liquid even': {'1.88': 'marathon'},
        'total kills liquid odd': {'1.88': 'marathon'},
        'total kills liquid over 233.5': {'1.88': 'marathon'},
        'total kills liquid under 233.5': {'1.88': 'marathon'},
        'total kills odd': {'1.88': 'marathon'},
        'total kills over 473.5': {'1.88': 'marathon'},
        'total kills under 473.5': {'1.88': 'marathon'},
        'total odd': {'1.90': 'marathon'},
        'total over 2.5': {'1.88': 'marathon'},
        'total over 65.5': {'1.82': 'marathon'},
        'total over 66.5': {'1.85': 'marathon'},
        'total over 67.5': {'1.86': 'marathon'},
        'total over 68.5': {'1.89': 'marathon'},
        'total over 69.5': {'1.90': 'marathon'},
        'total over 70.5': {'1.94': 'marathon'},
        'total over 71.5': {'1.99': 'marathon'},
        'total under 2.5': {'1.88': 'marathon'},
        'total under 65.5': {'1.95': 'marathon'},
        'total under 66.5': {'1.909': 'marathon'},
        'total under 67.5': {'1.90': 'marathon'},
        'total under 68.5': {'1.89': 'marathon'},
        'total under 69.5': {'1.86': 'marathon'},
        'total under 70.5': {'1.82': 'marathon'},
        'total under 71.5': {'1.78': 'marathon'}
    },
    'fnatic - heroic': {
        '1-st map: fnatic will win': {'1.77': 'marathon'},
        '1-st map: handicap fnatic -2.5': {'2.03': 'marathon'},
        '1-st map: handicap heroic +2.5': {'1.75': 'marathon'},
        '1-st map: heroic will win': {'2.01': 'marathon'},
        '1-st map: most kills equal number': {'24.00': 'marathon'},
        '1-st map: most kills fnatic': {'1.75': 'marathon'},
        '1-st map: most kills heroic': {'2.11': 'marathon'},
        '1-st map: most kills with handicap fnatic -2.5': {'1.909': 'marathon'},
        '1-st map: most kills with handicap heroic +2.5': {'1.85': 'marathon'},
        '1-st map: total even': {'1.76': 'marathon'},
        '1-st map: total kills even': {'1.88': 'marathon'},
        '1-st map: total kills fnatic even': {'1.88': 'marathon'},
        '1-st map: total kills fnatic odd': {'1.88': 'marathon'},
        '1-st map: total kills fnatic over 93.5': {'1.88': 'marathon'},
        '1-st map: total kills fnatic under 93.5': {'1.88': 'marathon'},
        '1-st map: total kills heroic even': {'1.88': 'marathon'},
        '1-st map: total kills heroic odd': {'1.88': 'marathon'},
        '1-st map: total kills heroic over 91.5': {'1.88': 'marathon'},
        '1-st map: total kills heroic under 91.5': {'1.88': 'marathon'},
        '1-st map: total kills odd': {'1.88': 'marathon'},
        '1-st map: total kills over 185.5': {'1.87': 'marathon'},
        '1-st map: total kills under 185.5': {'1.89': 'marathon'},
        '1-st map: total odd': {'2.02': 'marathon'},
        '1-st map: total over 26.5': {'1.75': 'marathon'},
        '1-st map: total under 26.5': {'2.03': 'marathon'},
        '2-nd map: fnatic will win': {'1.77': 'marathon'},
        '2-nd map: handicap fnatic -2.5': {'2.03': 'marathon'},
        '2-nd map: handicap heroic +2.5': {'1.75': 'marathon'},
        '2-nd map: heroic will win': {'2.01': 'marathon'},
        '2-nd map: most kills equal number': {'24.00': 'marathon'},
        '2-nd map: most kills fnatic': {'1.75': 'marathon'},
        '2-nd map: most kills heroic': {'2.11': 'marathon'},
        '2-nd map: most kills with handicap fnatic -2.5': {'1.909': 'marathon'},
        '2-nd map: most kills with handicap heroic +2.5': {'1.85': 'marathon'},
        '2-nd map: total even': {'1.76': 'marathon'},
        '2-nd map: total kills even': {'1.88': 'marathon'},
        '2-nd map: total kills fnatic even': {'1.88': 'marathon'},
        '2-nd map: total kills fnatic odd': {'1.88': 'marathon'},
        '2-nd map: total kills fnatic over 93.5': {'1.88': 'marathon'},
        '2-nd map: total kills fnatic under 93.5': {'1.88': 'marathon'},
        '2-nd map: total kills heroic even': {'1.88': 'marathon'},
        '2-nd map: total kills heroic odd': {'1.88': 'marathon'},
        '2-nd map: total kills heroic over 91.5': {'1.88': 'marathon'},
        '2-nd map: total kills heroic under 91.5': {'1.88': 'marathon'},
        '2-nd map: total kills odd': {'1.88': 'marathon'},
        '2-nd map: total kills over 185.5': {'1.87': 'marathon'},
        '2-nd map: total kills under 185.5': {'1.89': 'marathon'},
        '2-nd map: total odd': {'2.02': 'marathon'},
        '2-nd map: total over 26.5': {'1.75': 'marathon'},
        '2-nd map: total under 26.5': {'2.03': 'marathon'},
        'correct score 0-2': {'4.20': 'marathon'},
        'correct score 1-2': {'3.80': 'marathon'},
        'correct score 2-0': {'3.28': 'marathon'},
        'correct score 2-1': {'3.35': 'marathon'},
        'fnatic handicap -1.5 maps': {'3.28': 'marathon'},
        'fnatic will win': {'1.74': 'marathon'},
        'handicap fnatic -0.5': {'1.76': 'marathon'},
        'handicap fnatic -1.5': {'1.83': 'marathon'},
        'handicap fnatic -2.5': {'1.90': 'marathon'},
        'handicap fnatic -3.5': {'2.00': 'marathon'},
        'handicap fnatic -4.5': {'2.11': 'marathon'},
        'handicap fnatic -5.5': {'2.28': 'marathon'},
        'handicap fnatic 0': {'1.72': 'marathon'},
        'handicap heroic +0.5': {'2.04': 'marathon'},
        'handicap heroic +1.5': {'1.95': 'marathon'},
        'handicap heroic +2.5': {'1.88': 'marathon'},
        'handicap heroic +3.5': {'1.79': 'marathon'},
        'handicap heroic +4.5': {'1.71': 'marathon'},
        'handicap heroic +5.5': {'1.61': 'marathon'},
        'handicap heroic 0': {'2.09': 'marathon'},
        'heroic handicap +1.5 maps': {'1.32': 'marathon'},
        'heroic will win': {'2.09': 'marathon'},
        'most kills equal number': {'29.00': 'marathon'},
        'most kills fnatic': {'1.66': 'marathon'},
        'most kills fnatic or equal number': {'1.571': 'marathon'},
        'most kills heroic': {'2.22': 'marathon'},
        'most kills heroic or equal number': {'2.07': 'marathon'},
        'most kills with handicap fnatic -4.5': {'1.86': 'marathon'},
        'most kills with handicap heroic +4.5': {'1.90': 'marathon'},
        'total even': {'1.90': 'marathon'},
        'total kills even': {'1.88': 'marathon'},
        'total kills fnatic even': {'1.88': 'marathon'},
        'total kills fnatic odd': {'1.88': 'marathon'},
        'total kills fnatic over 234.5': {'1.88': 'marathon'},
        'total kills fnatic under 234.5': {'1.88': 'marathon'},
        'total kills heroic even': {'1.88': 'marathon'},
        'total kills heroic odd': {'1.88': 'marathon'},
        'total kills heroic over 229.5': {'1.88': 'marathon'},
        'total kills heroic under 229.5': {'1.88': 'marathon'},
        'total kills odd': {'1.88': 'marathon'},
        'total kills over 469.5': {'1.88': 'marathon'},
        'total kills under 469.5': {'1.88': 'marathon'},
        'total odd': {'1.90': 'marathon'},
        'total over 2.5': {'1.88': 'marathon'},
        'total over 65.5': {'1.83': 'marathon'},
        'total over 66.5': {'1.85': 'marathon'},
        'total over 67.5': {'1.86': 'marathon'},
        'total over 68.5': {'1.89': 'marathon'},
        'total over 69.5': {'1.909': 'marathon'},
        'total over 70.5': {'1.94': 'marathon'},
        'total over 71.5': {'1.99': 'marathon'},
        'total under 2.5': {'1.88': 'marathon'},
        'total under 65.5': {'1.93': 'marathon'},
        'total under 66.5': {'1.909': 'marathon'},
        'total under 67.5': {'1.90': 'marathon'},
        'total under 68.5': {'1.89': 'marathon'},
        'total under 69.5': {'1.85': 'marathon'},
        'total under 70.5': {'1.82': 'marathon'},
        'total under 71.5': {'1.78': 'marathon'}
    },
    'godsent - og': {
        '1-st map: godsent will win': {'1.74': 'marathon'},
        '1-st map: handicap godsent -2.5': {'2.01': 'marathon'},
        '1-st map: handicap og +2.5': {'1.77': 'marathon'},
        '1-st map: most kills equal number': {'24.00': 'marathon'},
        '1-st map: most kills godsent': {'1.81': 'marathon'},
        '1-st map: most kills og': {'2.03': 'marathon'},
        '1-st map: most kills with handicap godsent -1.5': {'1.89': 'marathon'},
        '1-st map: most kills with handicap og +1.5': {'1.87': 'marathon'},
        '1-st map: og will win': {'2.04': 'marathon'},
        '1-st map: total even': {'1.75': 'marathon'},
        '1-st map: total kills even': {'1.88': 'marathon'},
        '1-st map: total kills godsent even': {'1.88': 'marathon'},
        '1-st map: total kills godsent odd': {'1.88': 'marathon'},
        '1-st map: total kills godsent over 93.5': {'1.90': 'marathon'},
        '1-st map: total kills godsent under 93.5': {'1.86': 'marathon'},
        '1-st map: total kills odd': {'1.88': 'marathon'},
        '1-st map: total kills og even': {'1.88': 'marathon'},
        '1-st map: total kills og odd': {'1.88': 'marathon'},
        '1-st map: total kills og over 91.5': {'1.84': 'marathon'},
        '1-st map: total kills og under 91.5': {'1.92': 'marathon'},
        '1-st map: total kills over 185.5': {'1.86': 'marathon'},
        '1-st map: total kills under 185.5': {'1.90': 'marathon'},
        '1-st map: total odd': {'2.03': 'marathon'},
        '1-st map: total over 27.5': {'2.10': 'marathon'},
        '1-st map: total under 27.5': {'1.70': 'marathon'},
        '2-nd map: godsent will win': {'1.90': 'marathon'},
        '2-nd map: handicap godsent +2.5': {'1.666': 'marathon'},
        '2-nd map: handicap og -2.5': {'2.16': 'marathon'},
        '2-nd map: most kills equal number': {'24.00': 'marathon'},
        '2-nd map: most kills godsent': {'1.81': 'marathon'},
        '2-nd map: most kills og': {'2.03': 'marathon'},
        '2-nd map: most kills with handicap godsent -1.5': {'1.89': 'marathon'},
        '2-nd map: most kills with handicap og +1.5': {'1.87': 'marathon'},
        '2-nd map: og will win': {'1.86': 'marathon'},
        '2-nd map: total even': {'1.76': 'marathon'},
        '2-nd map: total kills even': {'1.88': 'marathon'},
        '2-nd map: total kills godsent even': {'1.88': 'marathon'},
        '2-nd map: total kills godsent odd': {'1.88': 'marathon'},
        '2-nd map: total kills godsent over 93.5': {'1.90': 'marathon'},
        '2-nd map: total kills godsent under 93.5': {'1.86': 'marathon'},
        '2-nd map: total kills odd': {'1.88': 'marathon'},
        '2-nd map: total kills og even': {'1.88': 'marathon'},
        '2-nd map: total kills og odd': {'1.88': 'marathon'},
        '2-nd map: total kills og over 91.5': {'1.84': 'marathon'},
        '2-nd map: total kills og under 91.5': {'1.92': 'marathon'},
        '2-nd map: total kills over 185.5': {'1.86': 'marathon'},
        '2-nd map: total kills under 185.5': {'1.90': 'marathon'},
        '2-nd map: total odd': {'2.02': 'marathon'},
        '2-nd map: total over 26.5': {'1.70': 'marathon'},
        '2-nd map: total under 26.5': {'2.10': 'marathon'},
        'correct score 0-2': {'3.98': 'marathon'},
        'correct score 1-2': {'3.68': 'marathon'},
        'correct score 2-0': {'3.44': 'marathon'},
        'correct score 2-1': {'3.44': 'marathon'},
        'godsent handicap +1.5 maps': {'1.27': 'marathon'},
        'godsent handicap -1.5 maps': {'3.32': 'marathon'},
        'godsent will win': {'1.81': 'marathon'},
        'handicap godsent +0.5': {'1.76': 'marathon'},
        'handicap godsent -0.5': {'1.83': 'marathon'},
        'handicap godsent -1.5': {'1.90': 'marathon'},
        'handicap godsent -2.5': {'1.99': 'marathon'},
        'handicap godsent -3.5': {'2.08': 'marathon'},
        'handicap godsent 0': {'1.79': 'marathon'},
        'handicap og +0.5': {'1.95': 'marathon'},
        'handicap og +1.5': {'1.88': 'marathon'},
        'handicap og +2.5': {'1.80': 'marathon'},
        'handicap og +3.5': {'1.727': 'marathon'},
        'handicap og -0.5': {'2.04': 'marathon'},
        'handicap og 0': {'2.00': 'marathon'},
        'most kills equal number': {'29.00': 'marathon'},
        'most kills godsent': {'1.74': 'marathon'},
        'most kills godsent or equal number': {'1.65': 'marathon'},
        'most kills og': {'2.09': 'marathon'},
        'most kills og or equal number': {'1.96': 'marathon'},
        'most kills with handicap godsent -3.5': {'1.89': 'marathon'},
        'most kills with handicap og +3.5': {'1.87': 'marathon'},
        'og handicap +1.5 maps': {'1.32': 'marathon'},
        'og handicap -1.5 maps': {'3.70': 'marathon'},
        'og will win': {'2.00': 'marathon'},
        'total even': {'1.88': 'marathon'},
        'total kills even': {'1.88': 'marathon'},
        'total kills godsent even': {'1.88': 'marathon'},
        'total kills godsent odd': {'1.88': 'marathon'},
        'total kills godsent over 234.5': {'1.88': 'marathon'},
        'total kills godsent under 234.5': {'1.88': 'marathon'},
        'total kills odd': {'1.88': 'marathon'},
        'total kills og even': {'1.88': 'marathon'},
        'total kills og odd': {'1.88': 'marathon'},
        'total kills og over 231.5': {'1.88': 'marathon'},
        'total kills og under 231.5': {'1.88': 'marathon'},
        'total kills over 471.5': {'1.88': 'marathon'},
        'total kills under 471.5': {'1.88': 'marathon'},
        'total odd': {'1.88': 'marathon'},
        'total over 2.5': {'1.88': 'marathon'},
        'total over 66.5': {'1.83': 'marathon'},
        'total over 67.5': {'1.84': 'marathon'},
        'total over 68.5': {'1.86': 'marathon'},
        'total over 69.5': {'1.89': 'marathon'},
        'total over 70.5': {'1.92': 'marathon'},
        'total over 71.5': {'1.97': 'marathon'},
        'total over 72.5': {'2.02': 'marathon'},
        'total under 2.5': {'1.88': 'marathon'},
        'total under 66.5': {'1.93': 'marathon'},
        'total under 67.5': {'1.92': 'marathon'},
        'total under 68.5': {'1.90': 'marathon'},
        'total under 69.5': {'1.89': 'marathon'},
        'total under 70.5': {'1.84': 'marathon'},
        'total under 71.5': {'1.80': 'marathon'},
        'total under 72.5': {'1.76': 'marathon'}
    },
    'grazur - lethal divide': {
        'correct score 0-2': {'2.69': 'marathon'},
        'correct score 1-2': {'3.125': 'marathon'},
        'correct score 2-0': {'5.45': 'marathon'},
        'correct score 2-1': {'4.40': 'marathon'},
        'grazur handicap +1.5 maps': {'1.45': 'marathon'},
        'grazur will win': {'2.53': 'marathon'},
        'lethal divide handicap -1.5 maps': {'2.69': 'marathon'},
        'lethal divide will win': {'1.52': 'marathon'},
        'total even': {'1.83': 'marathon'},
        'total odd': {'1.94': 'marathon'},
        'total over 2.5': {'1.94': 'marathon'},
        'total under 2.5': {'1.83': 'marathon'}
    },
    'ground zero - rooster': {
        'correct score 0-2': {'2.53': 'marathon'},
        'correct score 1-2': {'3.08': 'marathon'},
        'correct score 2-0': {'5.95': 'marathon'},
        'correct score 2-1': {'4.65': 'marathon'},
        'ground zero handicap +1.5 maps': {'1.50': 'marathon'},
        'ground zero will win': {'2.72': 'marathon'},
        'rooster handicap -1.5 maps': {'2.53': 'marathon'},
        'rooster will win': {'1.46': 'marathon'},
        'total even': {'1.79': 'marathon'},
        'total odd': {'1.98': 'marathon'},
        'total over 2.5': {'1.98': 'marathon'},
        'total under 2.5': {'1.79': 'marathon'}
    },
    'hard legion - sprout': {
        'correct score 0-2': {'2.57': 'marathon'},
        'correct score 1-2': {'3.08': 'marathon'},
        'correct score 2-0': {'5.85': 'marathon'},
        'correct score 2-1': {'4.55': 'marathon'},
        'hard legion handicap +1.5 maps': {'1.49': 'marathon'},
        'hard legion will win': {'2.68': 'marathon'},
        'sprout handicap -1.5 maps': {'2.57': 'marathon'},
        'sprout will win': {'1.47': 'marathon'},
        'total even': {'1.80': 'marathon'},
        'total odd': {'1.97': 'marathon'},
        'total over 2.5': {'1.97': 'marathon'},
        'total under 2.5': {'1.80': 'marathon'}
    },
    'invictus gaming - lucid dream': {
        'correct score 0-2': {'7.70': 'marathon'},
        'correct score 1-2': {'5.40': 'marathon'},
        'correct score 2-0': {'2.19': 'marathon'},
        'correct score 2-1': {'3.02': 'marathon'},
        'invictus gaming handicap -1.5 maps': {'2.19': 'marathon'},
        'invictus gaming will win': {'1.33': 'marathon'},
        'lucid dream handicap +1.5 maps': {'1.65': 'marathon'},
        'lucid dream will win': {'3.32': 'marathon'},
        'total even': {'1.72': 'marathon'},
        'total odd': {'2.08': 'marathon'},
        'total over 2.5': {'2.08': 'marathon'},
        'total under 2.5': {'1.72': 'marathon'}
    },
    'invictus gaming - mazaalai': {
        '1-st map: handicap invictus gaming -4.5': {'1.97': 'marathon'},
        '1-st map: handicap mazaalai +4.5': {'1.80': 'marathon'},
        '1-st map: invictus gaming will win': {'1.35': 'marathon'},
        '1-st map: mazaalai will win': {'3.10': 'marathon'},
        '1-st map: total even': {'1.78': 'marathon'},
        '1-st map: total odd': {'1.99': 'marathon'},
        '1-st map: total over 26.5': {'1.909': 'marathon'},
        '1-st map: total under 26.5': {'1.85': 'marathon'},
        '2-nd map: handicap invictus gaming -4.5': {'1.97': 'marathon'},
        '2-nd map: handicap mazaalai +4.5': {'1.80': 'marathon'},
        '2-nd map: invictus gaming will win': {'1.35': 'marathon'},
        '2-nd map: mazaalai will win': {'3.10': 'marathon'},
        '2-nd map: total even': {'1.78': 'marathon'},
        '2-nd map: total odd': {'1.99': 'marathon'},
        '2-nd map: total over 26.5': {'1.909': 'marathon'},
        '2-nd map: total under 26.5': {'1.85': 'marathon'},
        'correct score 0-2': {'11.00': 'marathon'},
        'correct score 1-2': {'6.70': 'marathon'},
        'correct score 2-0': {'1.87': 'marathon'},
        'correct score 2-1': {'3.04': 'marathon'},
        'handicap invictus gaming -9.5': {'1.95': 'marathon'},
        'handicap mazaalai +9.5': {'1.833': 'marathon'},
        'invictus gaming handicap -1.5 maps': {'1.87': 'marathon'},
        'invictus gaming will win': {'1.22': 'marathon'},
        'mazaalai handicap +1.5 maps': {'1.90': 'marathon'},
        'mazaalai will win': {'4.30': 'marathon'},
        'total even': {'1.90': 'marathon'},
        'total odd': {'1.90': 'marathon'},
        'total over 2.5': {'2.28': 'marathon'},
        'total over 58.5': {'1.909': 'marathon'},
        'total under 2.5': {'1.60': 'marathon'},
        'total under 58.5': {'1.87': 'marathon'}
    },
    'ldlc - secret': {
        '1-st map: handicap ldlc +3.5': {'1.68': 'marathon'},
        '1-st map: handicap secret -3.5': {'2.13': 'marathon'},
        '1-st map: ldlc will win': {'2.26': 'marathon'},
        '1-st map: secret will win': {'1.61': 'marathon'},
        '1-st map: total even': {'1.77': 'marathon'},
        '1-st map: total odd': {'2.01': 'marathon'},
        '1-st map: total over 26.5': {'1.78': 'marathon'},
        '1-st map: total under 26.5': {'1.99': 'marathon'},
        '2-nd map: handicap ldlc +3.5': {'1.68': 'marathon'},
        '2-nd map: handicap secret -3.5': {'2.13': 'marathon'},
        '2-nd map: ldlc will win': {'2.26': 'marathon'},
        '2-nd map: secret will win': {'1.61': 'marathon'},
        '2-nd map: total even': {'1.77': 'marathon'},
        '2-nd map: total odd': {'2.01': 'marathon'},
        '2-nd map: total over 26.5': {'1.78': 'marathon'},
        '2-nd map: total under 26.5': {'1.99': 'marathon'},
        'correct score 0-2': {'2.70': 'marathon'},
        'correct score 1-2': {'3.125': 'marathon'},
        'correct score 2-0': {'5.45': 'marathon'},
        'correct score 2-1': {'4.35': 'marathon'},
        'handicap ldlc +5.5': {'1.87': 'marathon'},
        'handicap secret -5.5': {'1.909': 'marathon'},
        'ldlc handicap +1.5 maps': {'1.444': 'marathon'},
        'ldlc will win': {'2.53': 'marathon'},
        'secret handicap -1.5 maps': {'2.70': 'marathon'},
        'secret will win': {'1.52': 'marathon'},
        'total even': {'1.90': 'marathon'},
        'total odd': {'1.90': 'marathon'},
        'total over 2.5': {'1.94': 'marathon'},
        'total over 65.5': {'1.89': 'marathon'},
        'total under 2.5': {'1.83': 'marathon'},
        'total under 65.5': {'1.89': 'marathon'}
    },
    'lucid dream - tiger': {
        'correct score 0-2': {'2.33': 'marathon'},
        'correct score 1-2': {'3.02': 'marathon'},
        'correct score 2-0': {'6.85': 'marathon'},
        'correct score 2-1': {'5.05': 'marathon'},
        'lucid dream handicap +1.5 maps': {'1.58': 'marathon'},
        'lucid dream will win': {'3.04': 'marathon'},
        'tiger handicap -1.5 maps': {'2.33': 'marathon'},
        'tiger will win': {'1.38': 'marathon'},
        'total even': {'1.76': 'marathon'},
        'total odd': {'2.03': 'marathon'},
        'total over 2.5': {'2.03': 'marathon'},
        'total under 2.5': {'1.76': 'marathon'}
    },
    'lvlup - the dice': {
        'correct score 0-2': {'5.05': 'marathon'},
        'correct score 1-2': {'4.20': 'marathon'},
        'correct score 2-0': {'2.84': 'marathon'},
        'correct score 2-1': {'3.16': 'marathon'},
        'lvlup handicap -1.5 maps': {'2.84': 'marathon'},
        'lvlup will win': {'1.571': 'marathon'},
        'the dice handicap +1.5 maps': {'1.41': 'marathon'},
        'the dice will win': {'2.40': 'marathon'},
        'total even': {'1.85': 'marathon'},
        'total odd': {'1.92': 'marathon'},
        'total over 2.5': {'1.92': 'marathon'},
        'total under 2.5': {'1.85': 'marathon'}
    },
    'mazaalai - tyloo': {
        'correct score 0-2': {'1.61': 'marathon'},
        'correct score 1-2': {'3.28': 'marathon'},
        'correct score 2-0': {'13.75': 'marathon'},
        'correct score 2-1': {'9.50': 'marathon'},
        'mazaalai handicap +1.5 maps': {'2.27': 'marathon'},
        'mazaalai will win': {'6.10': 'marathon'},
        'total even': {'1.48': 'marathon'},
        'total odd': {'2.60': 'marathon'},
        'total over 2.5': {'2.60': 'marathon'},
        'total under 2.5': {'1.48': 'marathon'},
        'tyloo handicap -1.5 maps': {'1.61': 'marathon'},
        'tyloo will win': {'1.125': 'marathon'}
    },
    'new england whalers - recon 5': {
        'correct score 0-2': {'5.20': 'marathon'},
        'correct score 1-2': {'4.30': 'marathon'},
        'correct score 2-0': {'2.77': 'marathon'},
        'correct score 2-1': {'3.14': 'marathon'},
        'new england whalers handicap -1.5 maps': {'2.77': 'marathon'},
        'new england whalers will win': {'1.55': 'marathon'},
        'recon 5 handicap +1.5 maps': {'1.43': 'marathon'},
        'recon 5 will win': {'2.45': 'marathon'},
        'total even': {'1.833': 'marathon'},
        'total odd': {'1.93': 'marathon'},
        'total over 2.5': {'1.93': 'marathon'},
        'total under 2.5': {'1.833': 'marathon'}
    },
    'nexus gaming - saw': {
        'nexus gaming will win': {'2.79': 'marathon'},
        'saw will win': {'1.44': 'marathon'},
        'total even': {'1.666': 'marathon'},
        'total odd': {'2.16': 'marathon'},
        'total over 2.5': {'2.16': 'marathon'},
        'total under 2.5': {'1.666': 'marathon'}
    },
    'ninjas in pyjamas - north': {
        '1-st map: handicap ninjas in pyjamas -4.5': {'2.02': 'marathon'},
        '1-st map: handicap north +4.5': {'1.76': 'marathon'},
        '1-st map: most kills equal number': {'26.00': 'marathon'},
        '1-st map: most kills ninjas in pyjamas': {'1.40': 'marathon'},
        '1-st map: most kills north': {'2.99': 'marathon'},
        '1-st map: most kills with handicap ninjas in pyjamas -8.5': {'1.90': 'marathon'},
        '1-st map: most kills with handicap north +8.5': {'1.86': 'marathon'},
        '1-st map: ninjas in pyjamas will win': {'1.37': 'marathon'},
        '1-st map: north will win': {'2.99': 'marathon'},
        '1-st map: total even': {'1.78': 'marathon'},
        '1-st map: total kills even': {'1.88': 'marathon'},
        '1-st map: total kills ninjas in pyjamas even': {'1.88': 'marathon'},
        '1-st map: total kills ninjas in pyjamas odd': {'1.88': 'marathon'},
        '1-st map: total kills ninjas in pyjamas over 94.5': {'1.87': 'marathon'},
        '1-st map: total kills ninjas in pyjamas under 94.5': {'1.89': 'marathon'},
        '1-st map: total kills north even': {'1.88': 'marathon'},
        '1-st map: total kills north odd': {'1.88': 'marathon'},
        '1-st map: total kills north over 86.5': {'1.88': 'marathon'},
        '1-st map: total kills north under 86.5': {'1.88': 'marathon'},
        '1-st map: total kills odd': {'1.88': 'marathon'},
        '1-st map: total kills over 181.5': {'1.86': 'marathon'},
        '1-st map: total kills under 181.5': {'1.90': 'marathon'},
        '1-st map: total odd': {'1.99': 'marathon'},
        '1-st map: total over 26.5': {'1.89': 'marathon'},
        '1-st map: total under 26.5': {'1.87': 'marathon'},
        '2-nd map: handicap ninjas in pyjamas -4.5': {'2.02': 'marathon'},
        '2-nd map: handicap north +4.5': {'1.76': 'marathon'},
        '2-nd map: most kills equal number': {'26.00': 'marathon'},
        '2-nd map: most kills ninjas in pyjamas': {'1.40': 'marathon'},
        '2-nd map: most kills north': {'2.99': 'marathon'},
        '2-nd map: most kills with handicap ninjas in pyjamas -8.5': {'1.90': 'marathon'},
        '2-nd map: most kills with handicap north +8.5': {'1.86': 'marathon'},
        '2-nd map: ninjas in pyjamas will win': {'1.37': 'marathon'},
        '2-nd map: north will win': {'2.99': 'marathon'},
        '2-nd map: total even': {'1.78': 'marathon'},
        '2-nd map: total kills even': {'1.88': 'marathon'},
        '2-nd map: total kills ninjas in pyjamas even': {'1.88': 'marathon'},
        '2-nd map: total kills ninjas in pyjamas odd': {'1.88': 'marathon'},
        '2-nd map: total kills ninjas in pyjamas over 94.5': {'1.87': 'marathon'},
        '2-nd map: total kills ninjas in pyjamas under 94.5': {'1.89': 'marathon'},
        '2-nd map: total kills north even': {'1.88': 'marathon'},
        '2-nd map: total kills north odd': {'1.88': 'marathon'},
        '2-nd map: total kills north over 86.5': {'1.88': 'marathon'},
        '2-nd map: total kills north under 86.5': {'1.88': 'marathon'},
        '2-nd map: total kills odd': {'1.88': 'marathon'},
        '2-nd map: total kills over 181.5': {'1.86': 'marathon'},
        '2-nd map: total kills under 181.5': {'1.90': 'marathon'},
        '2-nd map: total odd': {'1.99': 'marathon'},
        '2-nd map: total over 26.5': {'1.89': 'marathon'},
        '2-nd map: total under 26.5': {'1.87': 'marathon'},
        'correct score 0-2': {'10.00': 'marathon'},
        'correct score 1-2': {'6.45': 'marathon'},
        'correct score 2-0': {'1.93': 'marathon'},
        'correct score 2-1': {'3.02': 'marathon'},
        'handicap ninjas in pyjamas -10.5': {'2.30': 'marathon'},
        'handicap ninjas in pyjamas -11.5': {'2.67': 'marathon'},
        'handicap ninjas in pyjamas -5.5': {'1.44': 'marathon'},
        'handicap ninjas in pyjamas -6.5': {'1.533': 'marathon'},
        'handicap ninjas in pyjamas -7.5': {'1.66': 'marathon'},
        'handicap ninjas in pyjamas -8.5': {'1.82': 'marathon'},
        'handicap ninjas in pyjamas -9.5': {'2.01': 'marathon'},
        'handicap north +10.5': {'1.60': 'marathon'},
        'handicap north +11.5': {'1.46': 'marathon'},
        'handicap north +5.5': {'2.74': 'marathon'},
        'handicap north +6.5': {'2.46': 'marathon'},
        'handicap north +7.5': {'2.19': 'marathon'},
        'handicap north +8.5': {'1.97': 'marathon'},
        'handicap north +9.5': {'1.78': 'marathon'},
        'most kills equal number': {'33.00': 'marathon'},
        'most kills ninjas in pyjamas': {'1.23': 'marathon'},
        'most kills ninjas in pyjamas or equal number': {'1.188': 'marathon'},
        'most kills north': {'4.10': 'marathon'},
        'most kills north or equal number': {'3.66': 'marathon'},
        'most kills with handicap ninjas in pyjamas -19.5': {'1.86': 'marathon'},
        'most kills with handicap north +19.5': {'1.90': 'marathon'},
        'ninjas in pyjamas handicap -1.5 maps': {'1.93': 'marathon'},
        'ninjas in pyjamas will win': {'1.24': 'marathon'},
        'north handicap +1.5 maps': {'1.833': 'marathon'},
        'north will win': {'4.05': 'marathon'},
        'total even': {'1.90': 'marathon'},
        'total kills even': {'1.88': 'marathon'},
        'total kills ninjas in pyjamas even': {'1.88': 'marathon'},
        'total kills ninjas in pyjamas odd': {'1.88': 'marathon'},
        'total kills ninjas in pyjamas over 223.5': {'1.88': 'marathon'},
        'total kills ninjas in pyjamas under 223.5': {'1.88': 'marathon'},
        'total kills north even': {'1.88': 'marathon'},
        'total kills north odd': {'1.88': 'marathon'},
        'total kills north over 205.5': {'1.88': 'marathon'},
        'total kills north under 205.5': {'1.88': 'marathon'},
        'total kills odd': {'1.88': 'marathon'},
        'total kills over 422.5': {'1.88': 'marathon'},
        'total kills under 422.5': {'1.88': 'marathon'},
        'total odd': {'1.90': 'marathon'},
        'total over 2.5': {'2.23': 'marathon'},
        'total over 55.5': {'1.63': 'marathon'},
        'total over 56.5': {'1.72': 'marathon'},
        'total over 57.5': {'1.80': 'marathon'},
        'total over 58.5': {'1.89': 'marathon'},
        'total over 59.5': {'1.92': 'marathon'},
        'total over 60.5': {'1.97': 'marathon'},
        'total over 61.5': {'1.99': 'marathon'},
        'total under 2.5': {'1.63': 'marathon'},
        'total under 55.5': {'2.22': 'marathon'},
        'total under 56.5': {'2.07': 'marathon'},
        'total under 57.5': {'1.97': 'marathon'},
        'total under 58.5': {'1.89': 'marathon'},
        'total under 59.5': {'1.84': 'marathon'},
        'total under 60.5': {'1.80': 'marathon'},
        'total under 61.5': {'1.78': 'marathon'}
    },
    'sangal - tricked': {
        'correct score 0-2': {'2.42': 'marathon'},
        'correct score 1-2': {'3.04': 'marathon'},
        'correct score 2-0': {'6.40': 'marathon'},
        'correct score 2-1': {'4.85': 'marathon'},
        'sangal handicap +1.5 maps': {'1.54': 'marathon'},
        'sangal will win': {'2.875': 'marathon'},
        'total even': {'1.78': 'marathon'},
        'total odd': {'2.00': 'marathon'},
        'total over 2.5': {'2.00': 'marathon'},
        'total under 2.5': {'1.78': 'marathon'},
        'tricked handicap -1.5 maps': {'2.42': 'marathon'},
        'tricked will win': {'1.42': 'marathon'}
    },
    'tenerife titans - winstrike': {
        '1-st map: handicap tenerife titans +4.5': {'2.02': 'marathon'},
        '1-st map: handicap winstrike -4.5': {'1.76': 'marathon'},
        '1-st map: tenerife titans will win': {'3.78': 'marathon'},
        '1-st map: total even': {'1.78': 'marathon'},
        '1-st map: total odd': {'1.99': 'marathon'},
        '1-st map: total over 26.5': {'2.04': 'marathon'},
        '1-st map: total under 26.5': {'1.74': 'marathon'},
        '1-st map: winstrike will win': {'1.25': 'marathon'},
        '2-nd map: handicap tenerife titans +4.5': {'2.02': 'marathon'},
        '2-nd map: handicap winstrike -4.5': {'1.76': 'marathon'},
        '2-nd map: tenerife titans will win': {'3.78': 'marathon'},
        '2-nd map: total even': {'1.78': 'marathon'},
        '2-nd map: total odd': {'1.99': 'marathon'},
        '2-nd map: total over 26.5': {'2.04': 'marathon'},
        '2-nd map: total under 26.5': {'1.74': 'marathon'},
        '2-nd map: winstrike will win': {'1.25': 'marathon'},
        'correct score 0-2': {'1.60': 'marathon'},
        'correct score 1-2': {'3.28': 'marathon'},
        'correct score 2-0': {'14.00': 'marathon'},
        'correct score 2-1': {'9.70': 'marathon'},
        'handicap tenerife titans +10.5': {'1.93': 'marathon'},
        'handicap winstrike -10.5': {'1.85': 'marathon'},
        'tenerife titans handicap +1.5 maps': {'2.28': 'marathon'},
        'tenerife titans will win': {'6.10': 'marathon'},
        'total even': {'1.90': 'marathon'},
        'total odd': {'1.90': 'marathon'},
        'total over 2.5': {'2.61': 'marathon'},
        'total over 55.5': {'1.87': 'marathon'},
        'total under 2.5': {'1.47': 'marathon'},
        'total under 55.5': {'1.909': 'marathon'},
        'winstrike handicap -1.5 maps': {'1.60': 'marathon'},
        'winstrike will win': {'1.124': 'marathon'}
    },
    'vindictive - white rabbit': {
        'correct score 0-2': {'6.65': 'marathon'},
        'correct score 1-2': {'4.95': 'marathon'},
        'correct score 2-0': {'2.375': 'marathon'},
        'correct score 2-1': {'3.02': 'marathon'},
        'total even': {'1.76': 'marathon'},
        'total odd': {'2.02': 'marathon'},
        'total over 2.5': {'2.02': 'marathon'},
        'total under 2.5': {'1.76': 'marathon'},
        'vindictive handicap -1.5 maps': {'2.375': 'marathon'},
        'vindictive will win': {'1.40': 'marathon'},
        'white rabbit handicap +1.5 maps': {'1.56': 'marathon'},
        'white rabbit will win': {'2.95': 'marathon'}
    }
}
