bets =  {'ahq - asking questions': {'ahq handicap -1.5 maps': {'2.93': 'marathon'},
                            'ahq will win': {'1.61': 'marathon'},
                            'asking questions handicap +1.5 maps': {'1.39': 'marathon'},
                            'asking questions will win': {'2.32': 'marathon'},
                            'correct score 0-2': {'4.85': 'marathon'},
                            'correct score 1-2': {'4.10': 'marathon'},
                            'correct score 2-0': {'2.93': 'marathon'},
                            'correct score 2-1': {'3.20': 'marathon'},
                            'total even': {'1.85': 'marathon'},
                            'total odd': {'1.92': 'marathon'},
                            'total over 2.5': {'1.92': 'marathon'},
                            'total under 2.5': {'1.85': 'marathon'}},
 'aim4r - w2c': {'aim4r handicap +1.5 maps': {'1.44': 'marathon'},
                 'aim4r will win': {'2.50': 'marathon'},
                 'correct score 0-2': {'2.73': 'marathon'},
                 'correct score 1-2': {'3.14': 'marathon'},
                 'correct score 2-0': {'5.30': 'marathon'},
                 'correct score 2-1': {'4.333': 'marathon'},
                 'total even': {'1.83': 'marathon'},
                 'total odd': {'1.94': 'marathon'},
                 'total over 2.5': {'1.94': 'marathon'},
                 'total under 2.5': {'1.83': 'marathon'},
                 'w2c handicap -1.5 maps': {'2.73': 'marathon'},
                 'w2c will win': {'1.53': 'marathon'}},
 'apeks - nemiga gaming': {'apeks handicap +1.5 maps': {'1.73': 'marathon'},
                           'apeks will win': {'3.38': 'marathon'},
                           'correct score 0-2': {'2.06': 'marathon'},
                           'correct score 1-2': {'3.24': 'marathon'},
                           'correct score 2-0': {'6.30': 'marathon'},
                           'correct score 2-1': {'6.60': 'marathon'},
                           'nemiga gaming handicap -1.5 maps': {'2.06': 'marathon'},
                           'nemiga gaming will win': {'1.32': 'marathon'},
                           'total even': {'1.57': 'marathon'},
                           'total odd': {'2.36': 'marathon'},
                           'total over 2.5': {'2.36': 'marathon'},
                           'total under 2.5': {'1.57': 'marathon'}},
 'avant - paradox': {'avant handicap -1.5 maps': {'1.909': 'marathon'},
                     'avant will win': {'1.23': 'marathon'},
                     'correct score 0-2': {'10.25': 'marathon'},
                     'correct score 1-2': {'6.55': 'marathon'},
                     'correct score 2-0': {'1.909': 'marathon'},
                     'correct score 2-1': {'3.04': 'marathon'},
                     'paradox handicap +1.5 maps': {'1.86': 'marathon'},
                     'paradox will win': {'4.20': 'marathon'},
                     'total even': {'1.615': 'marathon'},
                     'total odd': {'2.25': 'marathon'},
                     'total over 2.5': {'2.25': 'marathon'},
                     'total under 2.5': {'1.615': 'marathon'}},
 'big - vitality': {'1-st map: big will win': {'1.78': 'marathon'},
                    '1-st map: handicap big -2.5': {'2.04': 'marathon'},
                    '1-st map: handicap vitality +2.5': {'1.74': 'marathon'},
                    '1-st map: most kills big': {'1.81': 'marathon'},
                    '1-st map: most kills equal number': {'24.00': 'marathon'},
                    '1-st map: most kills vitality': {'2.03': 'marathon'},
                    '1-st map: most kills with handicap big -1.5': {'1.89': 'marathon'},
                    '1-st map: most kills with handicap vitality +1.5': {'1.87': 'marathon'},
                    '1-st map: total even': {'1.76': 'marathon'},
                    '1-st map: total kills big even': {'1.88': 'marathon'},
                    '1-st map: total kills big odd': {'1.88': 'marathon'},
                    '1-st map: total kills big over 93.5': {'1.90': 'marathon'},
                    '1-st map: total kills big under 93.5': {'1.86': 'marathon'},
                    '1-st map: total kills even': {'1.88': 'marathon'},
                    '1-st map: total kills odd': {'1.88': 'marathon'},
                    '1-st map: total kills over 185.5': {'1.86': 'marathon'},
                    '1-st map: total kills under 185.5': {'1.90': 'marathon'},
                    '1-st map: total kills vitality even': {'1.88': 'marathon'},
                    '1-st map: total kills vitality odd': {'1.88': 'marathon'},
                    '1-st map: total kills vitality over 91.5': {'1.84': 'marathon'},
                    '1-st map: total kills vitality under 91.5': {'1.92': 'marathon'},
                    '1-st map: total odd': {'2.02': 'marathon'},
                    '1-st map: total over 26.5': {'1.75': 'marathon'},
                    '1-st map: total under 26.5': {'2.03': 'marathon'},
                    '1-st map: vitality will win': {'1.99': 'marathon'},
                    '2-nd map: big will win': {'1.78': 'marathon'},
                    '2-nd map: handicap big -2.5': {'2.04': 'marathon'},
                    '2-nd map: handicap vitality +2.5': {'1.74': 'marathon'},
                    '2-nd map: most kills big': {'1.81': 'marathon'},
                    '2-nd map: most kills equal number': {'24.00': 'marathon'},
                    '2-nd map: most kills vitality': {'2.03': 'marathon'},
                    '2-nd map: most kills with handicap big -1.5': {'1.89': 'marathon'},
                    '2-nd map: most kills with handicap vitality +1.5': {'1.87': 'marathon'},
                    '2-nd map: total even': {'1.76': 'marathon'},
                    '2-nd map: total kills big even': {'1.88': 'marathon'},
                    '2-nd map: total kills big odd': {'1.88': 'marathon'},
                    '2-nd map: total kills big over 93.5': {'1.90': 'marathon'},
                    '2-nd map: total kills big under 93.5': {'1.86': 'marathon'},
                    '2-nd map: total kills even': {'1.88': 'marathon'},
                    '2-nd map: total kills odd': {'1.88': 'marathon'},
                    '2-nd map: total kills over 185.5': {'1.86': 'marathon'},
                    '2-nd map: total kills under 185.5': {'1.90': 'marathon'},
                    '2-nd map: total kills vitality even': {'1.88': 'marathon'},
                    '2-nd map: total kills vitality odd': {'1.88': 'marathon'},
                    '2-nd map: total kills vitality over 91.5': {'1.84': 'marathon'},
                    '2-nd map: total kills vitality under 91.5': {'1.92': 'marathon'},
                    '2-nd map: total odd': {'2.02': 'marathon'},
                    '2-nd map: total over 26.5': {'1.75': 'marathon'},
                    '2-nd map: total under 26.5': {'2.03': 'marathon'},
                    '2-nd map: vitality will win': {'1.99': 'marathon'},
                    'big handicap -1.5 maps': {'3.32': 'marathon'},
                    'big will win': {'1.75': 'marathon'},
                    'correct score 0-2': {'4.15': 'marathon'},
                    'correct score 1-2': {'3.78': 'marathon'},
                    'correct score 2-0': {'3.32': 'marathon'},
                    'correct score 2-1': {'3.36': 'marathon'},
                    'handicap big +0.5': {'1.71': 'marathon'},
                    'handicap big -0.5': {'1.77': 'marathon'},
                    'handicap big -1.5': {'1.85': 'marathon'},
                    'handicap big -2.5': {'1.92': 'marathon'},
                    'handicap big -3.5': {'2.01': 'marathon'},
                    'handicap big -4.5': {'2.14': 'marathon'},
                    'handicap big -5.5': {'2.30': 'marathon'},
                    'handicap big 0': {'1.74': 'marathon'},
                    'handicap vitality +0.5': {'2.02': 'marathon'},
                    'handicap vitality +1.5': {'1.93': 'marathon'},
                    'handicap vitality +2.5': {'1.86': 'marathon'},
                    'handicap vitality +3.5': {'1.78': 'marathon'},
                    'handicap vitality +4.5': {'1.69': 'marathon'},
                    'handicap vitality +5.5': {'1.60': 'marathon'},
                    'handicap vitality -0.5': {'2.11': 'marathon'},
                    'handicap vitality 0': {'2.06': 'marathon'},
                    'most kills big': {'1.74': 'marathon'},
                    'most kills big or equal number': {'1.65': 'marathon'},
                    'most kills equal number': {'29.00': 'marathon'},
                    'most kills vitality': {'2.09': 'marathon'},
                    'most kills vitality or equal number': {'1.96': 'marathon'},
                    'most kills with handicap big -3.5': {'1.89': 'marathon'},
                    'most kills with handicap vitality +3.5': {'1.87': 'marathon'},
                    'total even': {'1.90': 'marathon'},
                    'total kills big even': {'1.88': 'marathon'},
                    'total kills big odd': {'1.88': 'marathon'},
                    'total kills big over 234.5': {'1.88': 'marathon'},
                    'total kills big under 234.5': {'1.88': 'marathon'},
                    'total kills even': {'1.88': 'marathon'},
                    'total kills odd': {'1.88': 'marathon'},
                    'total kills over 471.5': {'1.88': 'marathon'},
                    'total kills under 471.5': {'1.88': 'marathon'},
                    'total kills vitality even': {'1.88': 'marathon'},
                    'total kills vitality odd': {'1.88': 'marathon'},
                    'total kills vitality over 231.5': {'1.88': 'marathon'},
                    'total kills vitality under 231.5': {'1.88': 'marathon'},
                    'total odd': {'1.90': 'marathon'},
                    'total over 2.5': {'1.88': 'marathon'},
                    'total over 64.5': {'1.80': 'marathon'},
                    'total over 65.5': {'1.83': 'marathon'},
                    'total over 66.5': {'1.85': 'marathon'},
                    'total over 67.5': {'1.86': 'marathon'},
                    'total over 68.5': {'1.89': 'marathon'},
                    'total over 69.5': {'1.909': 'marathon'},
                    'total over 70.5': {'1.94': 'marathon'},
                    'total over 71.5': {'1.99': 'marathon'},
                    'total under 2.5': {'1.88': 'marathon'},
                    'total under 64.5': {'1.97': 'marathon'},
                    'total under 65.5': {'1.93': 'marathon'},
                    'total under 66.5': {'1.909': 'marathon'},
                    'total under 67.5': {'1.90': 'marathon'},
                    'total under 68.5': {'1.89': 'marathon'},
                    'total under 69.5': {'1.85': 'marathon'},
                    'total under 70.5': {'1.82': 'marathon'},
                    'total under 71.5': {'1.78': 'marathon'},
                    'vitality handicap +1.5 maps': {'1.32': 'marathon'},
                    'vitality will win': {'2.08': 'marathon'}},
 'chiefs - truckers with attitude': {'chiefs handicap -1.5 maps': {'1.65': 'marathon'},
                                     'chiefs will win': {'1.137': 'marathon'},
                                     'correct score 0-2': {'12.75': 'marathon'},
                                     'correct score 1-2': {'9.10': 'marathon'},
                                     'correct score 2-0': {'1.65': 'marathon'},
                                     'correct score 2-1': {'3.22': 'marathon'},
                                     'total even': {'1.50': 'marathon'},
                                     'total odd': {'2.54': 'marathon'},
                                     'total over 2.5': {'2.54': 'marathon'},
                                     'total under 2.5': {'1.50': 'marathon'},
                                     'truckers with attitude handicap +1.5 maps': {'2.20': 'marathon'},
                                     'truckers with attitude will win': {'5.75': 'marathon'}},
 'd13 - divine vendetta': {'correct score 0-2': {'4.50': 'marathon'},
                           'correct score 1-2': {'3.92': 'marathon'},
                           'correct score 2-0': {'3.10': 'marathon'},
                           'correct score 2-1': {'3.28': 'marathon'},
                           'd13 handicap -1.5 maps': {'3.10': 'marathon'},
                           'd13 will win': {'1.68': 'marathon'},
                           'divine vendetta handicap +1.5 maps': {'1.35': 'marathon'},
                           'divine vendetta will win': {'2.19': 'marathon'},
                           'total even': {'1.87': 'marathon'},
                           'total odd': {'1.90': 'marathon'},
                           'total over 2.5': {'1.90': 'marathon'},
                           'total under 2.5': {'1.87': 'marathon'}},
 'divine vendetta - vici gaming': {'correct score 0-2': {'1.72': 'marathon'},
                                   'correct score 1-2': {'3.10': 'marathon'},
                                   'correct score 2-0': {'13.50': 'marathon'},
                                   'correct score 2-1': {'7.90': 'marathon'},
                                   'divine vendetta handicap +1.5 maps': {'2.08': 'marathon'},
                                   'divine vendetta will win': {'5.20': 'marathon'},
                                   'total even': {'1.53': 'marathon'},
                                   'total odd': {'2.44': 'marathon'},
                                   'total over 2.5': {'2.44': 'marathon'},
                                   'total under 2.5': {'1.53': 'marathon'},
                                   'vici gaming handicap -1.5 maps': {'1.72': 'marathon'},
                                   'vici gaming will win': {'1.161': 'marathon'}},
 'evil geniuses - liquid': {'1-st map: evil geniuses will win': {'1.88': 'marathon'},
                            '1-st map: handicap evil geniuses +2.5': {'1.65': 'marathon'},
                            '1-st map: handicap liquid -2.5': {'2.18': 'marathon'},
                            '1-st map: liquid will win': {'1.88': 'marathon'},
                            '1-st map: most kills equal number': {'24.00': 'marathon'},
                            '1-st map: most kills evil geniuses': {'1.909': 'marathon'},
                            '1-st map: most kills liquid': {'1.92': 'marathon'},
                            '1-st map: most kills with handicap evil geniuses -0.5': {'1.909': 'marathon'},
                            '1-st map: most kills with handicap liquid +0.5': {'1.85': 'marathon'},
                            '1-st map: total even': {'1.76': 'marathon'},
                            '1-st map: total kills even': {'1.88': 'marathon'},
                            '1-st map: total kills evil geniuses even': {'1.88': 'marathon'},
                            '1-st map: total kills evil geniuses odd': {'1.88': 'marathon'},
                            '1-st map: total kills evil geniuses over 92.5': {'1.87': 'marathon'},
                            '1-st map: total kills evil geniuses under 92.5': {'1.89': 'marathon'},
                            '1-st map: total kills liquid even': {'1.88': 'marathon'},
                            '1-st map: total kills liquid odd': {'1.88': 'marathon'},
                            '1-st map: total kills liquid over 92.5': {'1.87': 'marathon'},
                            '1-st map: total kills liquid under 92.5': {'1.89': 'marathon'},
                            '1-st map: total kills odd': {'1.88': 'marathon'},
                            '1-st map: total kills over 186.5': {'1.90': 'marathon'},
                            '1-st map: total kills under 186.5': {'1.86': 'marathon'},
                            '1-st map: total odd': {'2.02': 'marathon'},
                            '1-st map: total over 26.5': {'1.75': 'marathon'},
                            '1-st map: total under 26.5': {'2.03': 'marathon'},
                            '2-nd map: evil geniuses will win': {'1.88': 'marathon'},
                            '2-nd map: handicap evil geniuses +2.5': {'1.65': 'marathon'},
                            '2-nd map: handicap liquid -2.5': {'2.18': 'marathon'},
                            '2-nd map: liquid will win': {'1.88': 'marathon'},
                            '2-nd map: most kills equal number': {'24.00': 'marathon'},
                            '2-nd map: most kills evil geniuses': {'1.909': 'marathon'},
                            '2-nd map: most kills liquid': {'1.92': 'marathon'},
                            '2-nd map: most kills with handicap evil geniuses -0.5': {'1.909': 'marathon'},
                            '2-nd map: most kills with handicap liquid +0.5': {'1.85': 'marathon'},
                            '2-nd map: total even': {'1.76': 'marathon'},
                            '2-nd map: total kills even': {'1.88': 'marathon'},
                            '2-nd map: total kills evil geniuses even': {'1.88': 'marathon'},
                            '2-nd map: total kills evil geniuses odd': {'1.88': 'marathon'},
                            '2-nd map: total kills evil geniuses over 92.5': {'1.87': 'marathon'},
                            '2-nd map: total kills evil geniuses under 92.5': {'1.89': 'marathon'},
                            '2-nd map: total kills liquid even': {'1.88': 'marathon'},
                            '2-nd map: total kills liquid odd': {'1.88': 'marathon'},
                            '2-nd map: total kills liquid over 92.5': {'1.87': 'marathon'},
                            '2-nd map: total kills liquid under 92.5': {'1.89': 'marathon'},
                            '2-nd map: total kills odd': {'1.88': 'marathon'},
                            '2-nd map: total kills over 186.5': {'1.90': 'marathon'},
                            '2-nd map: total kills under 186.5': {'1.86': 'marathon'},
                            '2-nd map: total odd': {'2.02': 'marathon'},
                            '2-nd map: total over 26.5': {'1.75': 'marathon'},
                            '2-nd map: total under 26.5': {'2.03': 'marathon'},
                            'correct score 0-2': {'3.70': 'marathon'},
                            'correct score 1-2': {'3.58': 'marathon'},
                            'correct score 2-0': {'3.66': 'marathon'},
                            'correct score 2-1': {'3.55': 'marathon'},
                            'evil geniuses handicap -1.5 maps': {'3.66': 'marathon'},
                            'evil geniuses will win': {'1.89': 'marathon'},
                            'handicap evil geniuses +0.5': {'1.84': 'marathon'},
                            'handicap evil geniuses +1.5': {'1.77': 'marathon'},
                            'handicap evil geniuses -0.5': {'1.909': 'marathon'},
                            'handicap evil geniuses -1.5': {'2.00': 'marathon'},
                            'handicap evil geniuses -2.5': {'2.09': 'marathon'},
                            'handicap evil geniuses -3.5': {'2.19': 'marathon'},
                            'handicap evil geniuses 0': {'1.88': 'marathon'},
                            'handicap liquid +0.5': {'1.87': 'marathon'},
                            'handicap liquid +1.5': {'1.79': 'marathon'},
                            'handicap liquid +2.5': {'1.72': 'marathon'},
                            'handicap liquid +3.5': {'1.66': 'marathon'},
                            'handicap liquid -0.5': {'1.94': 'marathon'},
                            'handicap liquid -1.5': {'2.02': 'marathon'},
                            'handicap liquid 0': {'1.90': 'marathon'},
                            'liquid handicap +1.5 maps': {'1.27': 'marathon'},
                            'liquid will win': {'1.909': 'marathon'},
                            'most kills equal number': {'29.00': 'marathon'},
                            'most kills evil geniuses': {'1.89': 'marathon'},
                            'most kills evil geniuses or equal number': {'1.78': 'marathon'},
                            'most kills liquid': {'1.909': 'marathon'},
                            'most kills liquid or equal number': {'1.80': 'marathon'},
                            'most kills with handicap evil geniuses -0.5': {'1.90': 'marathon'},
                            'most kills with handicap liquid +0.5': {'1.86': 'marathon'},
                            'total even': {'1.90': 'marathon'},
                            'total kills even': {'1.88': 'marathon'},
                            'total kills evil geniuses even': {'1.88': 'marathon'},
                            'total kills evil geniuses odd': {'1.88': 'marathon'},
                            'total kills evil geniuses over 233.5': {'1.88': 'marathon'},
                            'total kills evil geniuses under 233.5': {'1.88': 'marathon'},
                            'total kills liquid even': {'1.88': 'marathon'},
                            'total kills liquid odd': {'1.88': 'marathon'},
                            'total kills liquid over 233.5': {'1.88': 'marathon'},
                            'total kills liquid under 233.5': {'1.88': 'marathon'},
                            'total kills odd': {'1.88': 'marathon'},
                            'total kills over 473.5': {'1.88': 'marathon'},
                            'total kills under 473.5': {'1.88': 'marathon'},
                            'total odd': {'1.90': 'marathon'},
                            'total over 2.5': {'1.88': 'marathon'},
                            'total over 65.5': {'1.82': 'marathon'},
                            'total over 66.5': {'1.85': 'marathon'},
                            'total over 67.5': {'1.86': 'marathon'},
                            'total over 68.5': {'1.89': 'marathon'},
                            'total over 69.5': {'1.90': 'marathon'},
                            'total over 70.5': {'1.94': 'marathon'},
                            'total over 71.5': {'1.99': 'marathon'},
                            'total under 2.5': {'1.88': 'marathon'},
                            'total under 65.5': {'1.95': 'marathon'},
                            'total under 66.5': {'1.909': 'marathon'},
                            'total under 67.5': {'1.90': 'marathon'},
                            'total under 68.5': {'1.89': 'marathon'},
                            'total under 69.5': {'1.86': 'marathon'},
                            'total under 70.5': {'1.82': 'marathon'},
                            'total under 71.5': {'1.78': 'marathon'}},
 'grazur - lethal divide': {'correct score 0-2': {'2.69': 'marathon'},
                            'correct score 1-2': {'3.125': 'marathon'},
                            'correct score 2-0': {'5.45': 'marathon'},
                            'correct score 2-1': {'4.40': 'marathon'},
                            'grazur handicap +1.5 maps': {'1.45': 'marathon'},
                            'grazur will win': {'2.53': 'marathon'},
                            'lethal divide handicap -1.5 maps': {'2.69': 'marathon'},
                            'lethal divide will win': {'1.52': 'marathon'},
                            'total even': {'1.83': 'marathon'},
                            'total odd': {'1.94': 'marathon'},
                            'total over 2.5': {'1.94': 'marathon'},
                            'total under 2.5': {'1.83': 'marathon'}},
 'ground zero - rooster': {'correct score 0-2': {'2.54': 'marathon'},
                           'correct score 1-2': {'3.08': 'marathon'},
                           'correct score 2-0': {'5.95': 'marathon'},
                           'correct score 2-1': {'4.60': 'marathon'},
                           'ground zero handicap +1.5 maps': {'1.50': 'marathon'},
                           'ground zero will win': {'2.72': 'marathon'},
                           'rooster handicap -1.5 maps': {'2.54': 'marathon'},
                           'rooster will win': {'1.46': 'marathon'},
                           'total even': {'1.80': 'marathon'},
                           'total odd': {'1.97': 'marathon'},
                           'total over 2.5': {'1.97': 'marathon'},
                           'total under 2.5': {'1.80': 'marathon'}},
 'invictus gaming - lucid dream': {'correct score 0-2': {'9.00': 'marathon'},
                                   'correct score 1-2': {'5.95': 'marathon'},
                                   'correct score 2-0': {'2.03': 'marathon'},
                                   'correct score 2-1': {'3.02': 'marathon'},
                                   'invictus gaming handicap -1.5 maps': {'2.03': 'marathon'},
                                   'invictus gaming will win': {'1.27': 'marathon'},
                                   'lucid dream handicap +1.5 maps': {'1.76': 'marathon'},
                                   'lucid dream will win': {'3.76': 'marathon'},
                                   'total even': {'1.666': 'marathon'},
                                   'total odd': {'2.16': 'marathon'},
                                   'total over 2.5': {'2.16': 'marathon'},
                                   'total under 2.5': {'1.666': 'marathon'}},
 'invictus gaming - mazaalai': {'1-st map: handicap invictus gaming -4.5': {'1.97': 'marathon'},
                                '1-st map: handicap mazaalai +4.5': {'1.80': 'marathon'},
                                '1-st map: invictus gaming will win': {'1.35': 'marathon'},
                                '1-st map: mazaalai will win': {'3.10': 'marathon'},
                                '1-st map: total even': {'1.78': 'marathon'},
                                '1-st map: total odd': {'1.99': 'marathon'},
                                '1-st map: total over 26.5': {'1.909': 'marathon'},
                                '1-st map: total under 26.5': {'1.85': 'marathon'},
                                '2-nd map: handicap invictus gaming -4.5': {'1.97': 'marathon'},
                                '2-nd map: handicap mazaalai +4.5': {'1.80': 'marathon'},
                                '2-nd map: invictus gaming will win': {'1.35': 'marathon'},
                                '2-nd map: mazaalai will win': {'3.10': 'marathon'},
                                '2-nd map: total even': {'1.78': 'marathon'},
                                '2-nd map: total odd': {'1.99': 'marathon'},
                                '2-nd map: total over 26.5': {'1.909': 'marathon'},
                                '2-nd map: total under 26.5': {'1.85': 'marathon'},
                                'correct score 0-2': {'10.75': 'marathon'},
                                'correct score 1-2': {'6.75': 'marathon'},
                                'correct score 2-0': {'1.87': 'marathon'},
                                'correct score 2-1': {'3.04': 'marathon'},
                                'handicap invictus gaming -9.5': {'1.95': 'marathon'},
                                'handicap mazaalai +9.5': {'1.83': 'marathon'},
                                'invictus gaming handicap -1.5 maps': {'1.87': 'marathon'},
                                'invictus gaming will win': {'1.22': 'marathon'},
                                'mazaalai handicap +1.5 maps': {'1.90': 'marathon'},
                                'mazaalai will win': {'4.30': 'marathon'},
                                'total even': {'1.90': 'marathon'},
                                'total odd': {'1.90': 'marathon'},
                                'total over 2.5': {'2.28': 'marathon'},
                                'total over 58.5': {'1.909': 'marathon'},
                                'total under 2.5': {'1.60': 'marathon'},
                                'total under 58.5': {'1.87': 'marathon'}},
 'lucid dream - tiger': {'correct score 0-2': {'2.33': 'marathon'},
                         'correct score 1-2': {'3.02': 'marathon'},
                         'correct score 2-0': {'6.85': 'marathon'},
                         'correct score 2-1': {'5.05': 'marathon'},
                         'lucid dream handicap +1.5 maps': {'1.58': 'marathon'},
                         'lucid dream will win': {'3.04': 'marathon'},
                         'tiger handicap -1.5 maps': {'2.33': 'marathon'},
                         'tiger will win': {'1.38': 'marathon'},
                         'total even': {'1.76': 'marathon'},
                         'total odd': {'2.03': 'marathon'},
                         'total over 2.5': {'2.03': 'marathon'},
                         'total under 2.5': {'1.76': 'marathon'}},
 'mazaalai - tyloo': {'correct score 0-2': {'1.62': 'marathon'},
                      'correct score 1-2': {'3.26': 'marathon'},
                      'correct score 2-0': {'13.50': 'marathon'},
                      'correct score 2-1': {'9.40': 'marathon'},
                      'mazaalai handicap +1.5 maps': {'2.24': 'marathon'},
                      'mazaalai will win': {'6.00': 'marathon'},
                      'total even': {'1.48': 'marathon'},
                      'total odd': {'2.58': 'marathon'},
                      'total over 2.5': {'2.58': 'marathon'},
                      'total under 2.5': {'1.48': 'marathon'},
                      'tyloo handicap -1.5 maps': {'1.62': 'marathon'},
                      'tyloo will win': {'1.129': 'marathon'}}}
