bets =  {'ago - nordavind': {'1-st map: ago will win': {'2.25': '1xbet'},
                     '1-st map: ago will win in round 1': {'1.91': '1xbet'},
                     '1-st map: ago will win in round 16': {'1.91': '1xbet'},
                     '1-st map: handicap ago +2.5': {'1.77': '1xbet'},
                     '1-st map: handicap ago +3.5': {'1.59': '1xbet'},
                     '1-st map: handicap ago +4.5': {'1.45': '1xbet'},
                     '1-st map: handicap ago +5.5': {'1.33': '1xbet'},
                     '1-st map: handicap ago +6.5': {'1.23': '1xbet'},
                     '1-st map: handicap ago -2.5': {'2.94': '1xbet'},
                     '1-st map: handicap ago -3.5': {'3.46': '1xbet'},
                     '1-st map: handicap ago -4.5': {'4.08': '1xbet'},
                     '1-st map: handicap nordavind +2.5': {'1.37': '1xbet'},
                     '1-st map: handicap nordavind +3.5': {'1.28': '1xbet'},
                     '1-st map: handicap nordavind +4.5': {'1.21': '1xbet'},
                     '1-st map: handicap nordavind -2.5': {'1.98': '1xbet'},
                     '1-st map: handicap nordavind -3.5': {'2.27': '1xbet'},
                     '1-st map: handicap nordavind -4.5': {'2.635': '1xbet'},
                     '1-st map: handicap nordavind -5.5': {'3.14': '1xbet'},
                     '1-st map: handicap nordavind -6.5': {'3.88': '1xbet'},
                     '1-st map: individual total 1 over 11.5': {'1.195': '1xbet'},
                     '1-st map: individual total 1 over 13.5': {'1.344': '1xbet'},
                     '1-st map: individual total 1 over 14.5': {'1.435': '1xbet'},
                     '1-st map: individual total 1 under 11.5': {'4.1': '1xbet'},
                     '1-st map: individual total 1 under 13.5': {'2.94': '1xbet'},
                     '1-st map: individual total 1 under 14.5': {'2.57': '1xbet'},
                     '1-st map: nordavind will win': {'1.61': '1xbet'},
                     '1-st map: nordavind will win in round 1': {'1.83': '1xbet'},
                     '1-st map: nordavind will win in round 16': {'1.83': '1xbet'},
                     '1-st map: total over 24.5': {'1.23': '1xbet'},
                     '1-st map: total over 25.5': {'1.368': '1xbet'},
                     '1-st map: total over 26.5': {'1.56': '1xbet'},
                     '1-st map: total over 27.5': {'1.91': '1xbet'},
                     '1-st map: total over 28.5': {'2.43': '1xbet'},
                     '1-st map: total over 29.5': {'3.38': '1xbet'},
                     '1-st map: total under 24.5': {'3.88': '1xbet'},
                     '1-st map: total under 25.5': {'2.96': '1xbet'},
                     '1-st map: total under 26.5': {'2.33': '1xbet'},
                     '1-st map: total under 27.5': {'1.83': '1xbet'},
                     '1-st map: total under 28.5': {'1.52': '1xbet'},
                     '1-st map: total under 29.5': {'1.29': '1xbet'},
                     'ago will win': {'2.29': '1xbet'},
                     'nordavind will win': {'1.6': '1xbet'}},
 'ahq e-sports - asking questions': {'1-st map: ahq e-sports will win': {'1.8': '1xbet'},
                                     '1-st map: asking questions will win': {'1.955': '1xbet'},
                                     '2-nd map: ahq e-sports will win': {'1.8': '1xbet'},
                                     '2-nd map: asking questions will win': {'1.955': '1xbet'},
                                     'ahq e-sports will win': {'1.73': '1xbet'},
                                     'asking questions will win': {'2.005': '1xbet'}},
 'aim4r hasteka - w2c': {'1-st map: aim4r hasteka will win': {'2.28': '1xbet'},
                         '1-st map: w2c will win': {'1.59': '1xbet'},
                         '2-nd map: aim4r hasteka will win': {'2.28': '1xbet'},
                         '2-nd map: w2c will win': {'1.59': '1xbet'},
                         'aim4r hasteka will win': {'2.63': '1xbet'},
                         'w2c will win': {'1.31': '1xbet'}},
 'apeks - nemiga gaming': {'1-st map: ace': {'5': '1xbet'},
                           '1-st map: ace - no': {'1.15': '1xbet'},
                           '1-st map: apeks will win': {'2.83': '1xbet'},
                           '1-st map: apeks will win in round 1': {'1.96': '1xbet'},
                           '1-st map: apeks will win in round 16': {'1.96': '1xbet'},
                           '1-st map: bomb planted in round 1': {'1.6': '1xbet'},
                           '1-st map: bomb planted in round 1 - no': {'2.25': '1xbet'},
                           '1-st map: bomb planted in round 16': {'1.6': '1xbet'},
                           '1-st map: bomb planted in round 16 - no': {'2.25': '1xbet'},
                           '1-st map: first frag in 1 round — apeks': {'1.9': '1xbet'},
                           '1-st map: first frag in 1 round — nemiga gaming': {'1.85': '1xbet'},
                           '1-st map: first frag in 16 round — apeks': {'1.9': '1xbet'},
                           '1-st map: first frag in 16 round — nemiga gaming': {'1.85': '1xbet'},
                           '1-st map: handicap apeks +2.5': {'2.11': '1xbet'},
                           '1-st map: handicap apeks +3.5': {'1.87': '1xbet'},
                           '1-st map: handicap apeks +4.5': {'1.67': '1xbet'},
                           '1-st map: handicap nemiga gaming -2.5': {'1.68': '1xbet'},
                           '1-st map: handicap nemiga gaming -3.5': {'1.87': '1xbet'},
                           '1-st map: handicap nemiga gaming -4.5': {'2.12': '1xbet'},
                           '1-st map: nemiga gaming to win 1st and 16th rounds': {'3': '1xbet'},
                           '1-st map: nemiga gaming will win': {'1.4': '1xbet'},
                           '1-st map: nemiga gaming will win in round 1': {'1.79': '1xbet'},
                           '1-st map: nemiga gaming will win in round 16': {'1.79': '1xbet'},
                           '1-st map: total over 25.5': {'1.61': '1xbet'},
                           '1-st map: total over 26.5': {'1.896': '1xbet'},
                           '1-st map: total rounds even': {'1.75': '1xbet'},
                           '1-st map: total rounds even - no': {'2.01': '1xbet'},
                           '1-st map: total under 25.5': {'2.23': '1xbet'},
                           '1-st map: total under 26.5': {'1.845': '1xbet'},
                           '1-st map: will there be overtime? - no': {'1.05': '1xbet'},
                           '1-st map: will there be overtime? - yes': {'8.5': '1xbet'},
                           'apeks handicap +1.5 maps': {'1.784': '1xbet'},
                           'apeks handicap -1.5 maps': {'6.2': '1xbet'},
                           'apeks will win': {'3.42': '1xbet'},
                           'method of 1-st map: bomb defused in round 1': {'3.5': '1xbet'},
                           'method of 1-st map: bomb exploded in 1 round': {'15': '1xbet'},
                           'method of 1-st map: opponents to be killed in round 1': {'1.3': '1xbet'},
                           'method of 1-st map: win on time in round 1': {'100': '1xbet'},
                           'nemiga gaming handicap +1.5 maps': {'1.1': '1xbet'},
                           'nemiga gaming handicap -1.5 maps': {'1.87': '1xbet'},
                           'nemiga gaming will win': {'1.3': '1xbet'},
                           'round 1-st map: total frags in 1 round over 7.5': {'2.25': '1xbet'},
                           'round 1-st map: total frags in 1 round under 7.5': {'1.6': '1xbet'},
                           'round 1-st map: total frags in 16 round over 7.5': {'2.25': '1xbet'},
                           'round 1-st map: total frags in 16 round under 7.5': {'1.6': '1xbet'},
                           'total over 2.5': {'2.38': '1xbet'},
                           'total under 2.5': {'1.54': '1xbet'},
                           'total — even': {'1.54': '1xbet'},
                           'total — odd': {'2.38': '1xbet'}},
 'big - vitality': {'1-st map: big will win': {'1.81': '1xbet'},
                    '1-st map: big will win in round 1': {'1.86': '1xbet'},
                    '1-st map: big will win in round 16': {'1.86': '1xbet'},
                    '1-st map: handicap big +2.5': {'1.49': '1xbet'},
                    '1-st map: handicap big +3.5': {'1.38': '1xbet'},
                    '1-st map: handicap big +4.5': {'1.29': '1xbet'},
                    '1-st map: handicap big +5.5': {'1.21': '1xbet'},
                    '1-st map: handicap big -2.5': {'2.27': '1xbet'},
                    '1-st map: handicap big -3.5': {'2.6': '1xbet'},
                    '1-st map: handicap big -4.5': {'3.04': '1xbet'},
                    '1-st map: handicap big -5.5': {'3.7': '1xbet'},
                    '1-st map: handicap vitality +2.5': {'1.59': '1xbet'},
                    '1-st map: handicap vitality +3.5': {'1.456': '1xbet'},
                    '1-st map: handicap vitality +4.5': {'1.35': '1xbet'},
                    '1-st map: handicap vitality +5.5': {'1.25': '1xbet'},
                    '1-st map: handicap vitality -2.5': {'2.51': '1xbet'},
                    '1-st map: handicap vitality -3.5': {'2.9': '1xbet'},
                    '1-st map: handicap vitality -4.5': {'3.38': '1xbet'},
                    '1-st map: handicap vitality -5.5': {'4.1': '1xbet'},
                    '1-st map: individual total 1 over 10.5': {'1.23': '1xbet'},
                    '1-st map: individual total 1 over 11.5': {'1.325': '1xbet'},
                    '1-st map: individual total 1 over 12.5': {'1.425': '1xbet'},
                    '1-st map: individual total 1 over 13.5': {'1.55': '1xbet'},
                    '1-st map: individual total 1 over 14.5': {'1.696': '1xbet'},
                    '1-st map: individual total 1 under 10.5': {'3.7': '1xbet'},
                    '1-st map: individual total 1 under 11.5': {'3.04': '1xbet'},
                    '1-st map: individual total 1 under 12.5': {'2.6': '1xbet'},
                    '1-st map: individual total 1 under 13.5': {'2.27': '1xbet'},
                    '1-st map: individual total 1 under 14.5': {'2.01': '1xbet'},
                    '1-st map: individual total 2 over 10.5': {'1.195': '1xbet'},
                    '1-st map: individual total 2 over 11.5': {'1.27': '1xbet'},
                    '1-st map: individual total 2 over 12.5': {'1.352': '1xbet'},
                    '1-st map: individual total 2 under 10.5': {'4.1': '1xbet'},
                    '1-st map: individual total 2 under 11.5': {'3.38': '1xbet'},
                    '1-st map: individual total 2 under 12.5': {'2.9': '1xbet'},
                    '1-st map: total over 24.5': {'1.29': '1xbet'},
                    '1-st map: total over 25.5': {'1.45': '1xbet'},
                    '1-st map: total over 26.5': {'1.68': '1xbet'},
                    '1-st map: total over 27.5': {'2.05': '1xbet'},
                    '1-st map: total over 28.5': {'2.63': '1xbet'},
                    '1-st map: total over 29.5': {'3.78': '1xbet'},
                    '1-st map: total under 24.5': {'3.38': '1xbet'},
                    '1-st map: total under 25.5': {'2.63': '1xbet'},
                    '1-st map: total under 26.5': {'2.11': '1xbet'},
                    '1-st map: total under 27.5': {'1.72': '1xbet'},
                    '1-st map: total under 28.5': {'1.45': '1xbet'},
                    '1-st map: total under 29.5': {'1.24': '1xbet'},
                    '1-st map: vitality will win': {'1.955': '1xbet'},
                    '1-st map: vitality will win in round 1': {'1.88': '1xbet'},
                    '1-st map: vitality will win in round 16': {'1.88': '1xbet'},
                    '1-st map: will there be overtime? - no': {'1.09': '1xbet'},
                    '1-st map: will there be overtime? - yes': {'6.55': '1xbet'},
                    'big handicap +1.5 maps': {'1.25': '1xbet'},
                    'big handicap -1.5 maps': {'3.175': '1xbet'},
                    'big will win': {'1.79': '1xbet'},
                    'total over 2.5': {'1.848': '1xbet'},
                    'total under 2.5': {'1.84': '1xbet'},
                    'total — even': {'1.84': '1xbet'},
                    'total — odd': {'1.9': '1xbet'},
                    'vitality handicap +1.5 maps': {'1.315': '1xbet'},
                    'vitality handicap -1.5 maps': {'3.7': '1xbet'},
                    'vitality will win': {'1.99': '1xbet'}},
 'bravos - sws gaming': {'1-st map: bravos will win': {'1.525': '1xbet'},
                         '1-st map: sws gaming will win': {'2.43': '1xbet'},
                         '2-nd map: bravos will win': {'1.53': '1xbet'},
                         '2-nd map: sws gaming will win': {'2.42': '1xbet'},
                         'bravos will win': {'1.425': '1xbet'},
                         'sws gaming will win': {'2.775': '1xbet'}},
 'chiefs - twa': {'1-st map: chiefs will win': {'1.25': '1xbet'},
                  '1-st map: chiefs will win in round 1': {'1.76': '1xbet'},
                  '1-st map: chiefs will win in round 16': {'1.75': '1xbet'},
                  '1-st map: handicap chiefs -2.5': {'1.44': '1xbet'},
                  '1-st map: handicap chiefs -3.5': {'1.57': '1xbet'},
                  '1-st map: handicap chiefs -4.5': {'1.74': '1xbet'},
                  '1-st map: handicap chiefs -5.5': {'1.98': '1xbet'},
                  '1-st map: handicap chiefs -6.5': {'2.31': '1xbet'},
                  '1-st map: handicap chiefs -7.5': {'2.77': '1xbet'},
                  '1-st map: handicap twa +2.5': {'2.66': '1xbet'},
                  '1-st map: handicap twa +3.5': {'2.31': '1xbet'},
                  '1-st map: handicap twa +4.5': {'2.02': '1xbet'},
                  '1-st map: handicap twa +5.5': {'1.77': '1xbet'},
                  '1-st map: handicap twa +6.5': {'1.57': '1xbet'},
                  '1-st map: handicap twa +7.5': {'1.41': '1xbet'},
                  '1-st map: total over 23.5': {'1.33': '1xbet'},
                  '1-st map: total over 24.5': {'1.5': '1xbet'},
                  '1-st map: total over 25.5': {'1.74': '1xbet'},
                  '1-st map: total over 26.5': {'2.08': '1xbet'},
                  '1-st map: total over 27.5': {'2.57': '1xbet'},
                  '1-st map: total under 23.5': {'3.14': '1xbet'},
                  '1-st map: total under 24.5': {'2.48': '1xbet'},
                  '1-st map: total under 25.5': {'2.02': '1xbet'},
                  '1-st map: total under 26.5': {'1.7': '1xbet'},
                  '1-st map: total under 27.5': {'1.47': '1xbet'},
                  '1-st map: twa will win': {'3.74': '1xbet'},
                  '1-st map: twa will win in round 1': {'1.99': '1xbet'},
                  '1-st map: twa will win in round 16': {'2.01': '1xbet'},
                  '2-nd map: chiefs will win': {'1.25': '1xbet'},
                  '2-nd map: chiefs will win in round 1': {'1.75': '1xbet'},
                  '2-nd map: handicap chiefs -2.5': {'1.43': '1xbet'},
                  '2-nd map: handicap chiefs -3.5': {'1.55': '1xbet'},
                  '2-nd map: handicap chiefs -4.5': {'1.72': '1xbet'},
                  '2-nd map: handicap chiefs -5.5': {'1.96': '1xbet'},
                  '2-nd map: handicap chiefs -6.5': {'2.27': '1xbet'},
                  '2-nd map: handicap twa +2.5': {'2.7': '1xbet'},
                  '2-nd map: handicap twa +3.5': {'2.35': '1xbet'},
                  '2-nd map: handicap twa +4.5': {'2.05': '1xbet'},
                  '2-nd map: handicap twa +5.5': {'1.79': '1xbet'},
                  '2-nd map: handicap twa +6.5': {'1.59': '1xbet'},
                  '2-nd map: total over 23.5': {'1.34': '1xbet'},
                  '2-nd map: total over 24.5': {'1.51': '1xbet'},
                  '2-nd map: total over 25.5': {'1.75': '1xbet'},
                  '2-nd map: total over 26.5': {'2.09': '1xbet'},
                  '2-nd map: total over 27.5': {'2.6': '1xbet'},
                  '2-nd map: total under 23.5': {'3.09': '1xbet'},
                  '2-nd map: total under 24.5': {'2.45': '1xbet'},
                  '2-nd map: total under 25.5': {'2.01': '1xbet'},
                  '2-nd map: total under 26.5': {'1.69': '1xbet'},
                  '2-nd map: total under 27.5': {'1.46': '1xbet'},
                  '2-nd map: twa will win': {'3.74': '1xbet'},
                  '2-nd map: twa will win in round 1': {'2.01': '1xbet'},
                  'chiefs handicap +1.5 maps': {'1.04': '1xbet'},
                  'chiefs handicap -1.5 maps': {'1.55': '1xbet'},
                  'chiefs will win': {'1.15': '1xbet'},
                  'total over 2.5': {'2.81': '1xbet'},
                  'total under 2.5': {'1.4': '1xbet'},
                  'total — even': {'1.4': '1xbet'},
                  'total — odd': {'2.81': '1xbet'},
                  'twa handicap +1.5 maps': {'2.35': '1xbet'},
                  'twa handicap -1.5 maps': {'9.2': '1xbet'},
                  'twa will win': {'5.2': '1xbet'}},
 'cr4zy - nemiga gaming': {'1-st map: cr4zy will win': {'3.66': '1xbet'},
                           '1-st map: cr4zy will win in round 1': {'1.99': '1xbet'},
                           '1-st map: cr4zy will win in round 16': {'2.01': '1xbet'},
                           '1-st map: handicap cr4zy +2.5': {'2.66': '1xbet'},
                           '1-st map: handicap cr4zy +3.5': {'2.31': '1xbet'},
                           '1-st map: handicap cr4zy +4.5': {'2.01': '1xbet'},
                           '1-st map: handicap cr4zy +5.5': {'1.76': '1xbet'},
                           '1-st map: handicap cr4zy +6.5': {'1.56': '1xbet'},
                           '1-st map: handicap cr4zy +7.5': {'1.4': '1xbet'},
                           '1-st map: handicap nemiga gaming -2.5': {'1.44': '1xbet'},
                           '1-st map: handicap nemiga gaming -3.5': {'1.57': '1xbet'},
                           '1-st map: handicap nemiga gaming -4.5': {'1.75': '1xbet'},
                           '1-st map: handicap nemiga gaming -5.5': {'1.99': '1xbet'},
                           '1-st map: handicap nemiga gaming -6.5': {'2.33': '1xbet'},
                           '1-st map: handicap nemiga gaming -7.5': {'2.81': '1xbet'},
                           '1-st map: nemiga gaming will win': {'1.26': '1xbet'},
                           '1-st map: nemiga gaming will win in round 1': {'1.76': '1xbet'},
                           '1-st map: nemiga gaming will win in round 16': {'1.75': '1xbet'},
                           '1-st map: total over 23.5': {'1.33': '1xbet'},
                           '1-st map: total over 24.5': {'1.5': '1xbet'},
                           '1-st map: total over 25.5': {'1.73': '1xbet'},
                           '1-st map: total over 26.5': {'2.06': '1xbet'},
                           '1-st map: total over 27.5': {'2.57': '1xbet'},
                           '1-st map: total under 23.5': {'3.14': '1xbet'},
                           '1-st map: total under 24.5': {'2.48': '1xbet'},
                           '1-st map: total under 25.5': {'2.03': '1xbet'},
                           '1-st map: total under 26.5': {'1.71': '1xbet'},
                           '1-st map: total under 27.5': {'1.47': '1xbet'},
                           '2-nd map: cr4zy will win': {'3.66': '1xbet'},
                           '2-nd map: cr4zy will win in round 1': {'1.99': '1xbet'},
                           '2-nd map: handicap cr4zy +3.5': {'2.33': '1xbet'},
                           '2-nd map: handicap cr4zy +4.5': {'2.02': '1xbet'},
                           '2-nd map: handicap cr4zy +5.5': {'1.77': '1xbet'},
                           '2-nd map: handicap cr4zy +6.5': {'1.57': '1xbet'},
                           '2-nd map: handicap cr4zy +7.5': {'1.41': '1xbet'},
                           '2-nd map: handicap nemiga gaming -3.5': {'1.56': '1xbet'},
                           '2-nd map: handicap nemiga gaming -4.5': {'1.74': '1xbet'},
                           '2-nd map: handicap nemiga gaming -5.5': {'1.98': '1xbet'},
                           '2-nd map: handicap nemiga gaming -6.5': {'2.31': '1xbet'},
                           '2-nd map: handicap nemiga gaming -7.5': {'2.77': '1xbet'},
                           '2-nd map: nemiga gaming will win': {'1.26': '1xbet'},
                           '2-nd map: nemiga gaming will win in round 1': {'1.76': '1xbet'},
                           '2-nd map: total over 23.5': {'1.34': '1xbet'},
                           '2-nd map: total over 24.5': {'1.51': '1xbet'},
                           '2-nd map: total over 25.5': {'1.74': '1xbet'},
                           '2-nd map: total over 26.5': {'2.08': '1xbet'},
                           '2-nd map: total over 27.5': {'2.57': '1xbet'},
                           '2-nd map: total under 23.5': {'3.09': '1xbet'},
                           '2-nd map: total under 24.5': {'2.45': '1xbet'},
                           '2-nd map: total under 25.5': {'2.02': '1xbet'},
                           '2-nd map: total under 26.5': {'1.7': '1xbet'},
                           '2-nd map: total under 27.5': {'1.47': '1xbet'},
                           'cr4zy handicap +1.5 maps': {'2.35': '1xbet'},
                           'cr4zy handicap -1.5 maps': {'9.2': '1xbet'},
                           'cr4zy will win': {'5.2': '1xbet'},
                           'nemiga gaming handicap +1.5 maps': {'1.04': '1xbet'},
                           'nemiga gaming handicap -1.5 maps': {'1.55': '1xbet'},
                           'nemiga gaming will win': {'1.15': '1xbet'},
                           'total over 2.5': {'2.81': '1xbet'},
                           'total under 2.5': {'1.4': '1xbet'},
                           'total — even': {'1.4': '1xbet'},
                           'total — odd': {'2.81': '1xbet'}},
 'cream real betis - neverest': {'1-st map: cream real betis will win': {'1.59': '1xbet'},
                                 '1-st map: neverest will win': {'2.28': '1xbet'},
                                 '2-nd map: cream real betis will win': {'1.59': '1xbet'},
                                 '2-nd map: neverest will win': {'2.28': '1xbet'},
                                 'cream real betis will win': {'1.51': '1xbet'},
                                 'neverest will win': {'2.504': '1xbet'}},
 'd13 - divine vendetta': {'1-st map: d13 will win': {'1.62': '1xbet'},
                           '1-st map: d13 will win in round 1': {'1.83': '1xbet'},
                           '1-st map: d13 will win in round 16': {'1.83': '1xbet'},
                           '1-st map: divine vendetta will win': {'2.232': '1xbet'},
                           '1-st map: divine vendetta will win in round 1': {'1.91': '1xbet'},
                           '1-st map: divine vendetta will win in round 16': {'1.91': '1xbet'},
                           '1-st map: handicap d13 -2.5': {'1.94': '1xbet'},
                           '1-st map: handicap d13 -3.5': {'2.19': '1xbet'},
                           '1-st map: handicap divine vendetta +2.5': {'1.8': '1xbet'},
                           '1-st map: handicap divine vendetta +3.5': {'1.63': '1xbet'},
                           '1-st map: total over 26.5': {'1.81': '1xbet'},
                           '1-st map: total over 27.5': {'2.21': '1xbet'},
                           '1-st map: total under 26.5': {'1.93': '1xbet'},
                           '1-st map: total under 27.5': {'1.62': '1xbet'},
                           '2-nd map: d13 will win': {'1.63': '1xbet'},
                           '2-nd map: d13 will win in round 1': {'1.83': '1xbet'},
                           '2-nd map: d13 will win in round 16': {'1.83': '1xbet'},
                           '2-nd map: divine vendetta will win': {'2.21': '1xbet'},
                           '2-nd map: divine vendetta will win in round 1': {'1.91': '1xbet'},
                           '2-nd map: divine vendetta will win in round 16': {'1.91': '1xbet'},
                           '2-nd map: handicap d13 -2.5': {'1.94': '1xbet'},
                           '2-nd map: handicap d13 -3.5': {'2.19': '1xbet'},
                           '2-nd map: handicap divine vendetta +2.5': {'1.8': '1xbet'},
                           '2-nd map: handicap divine vendetta +3.5': {'1.63': '1xbet'},
                           '2-nd map: total over 26.5': {'1.82': '1xbet'},
                           '2-nd map: total over 27.5': {'2.23': '1xbet'},
                           '2-nd map: total under 26.5': {'1.92': '1xbet'},
                           '2-nd map: total under 27.5': {'1.61': '1xbet'},
                           'd13 handicap +1.5 maps': {'1.19': '1xbet'},
                           'd13 handicap -1.5 maps': {'2.43': '1xbet'},
                           'd13 will win': {'1.55': '1xbet'},
                           'divine vendetta handicap +1.5 maps': {'1.52': '1xbet'},
                           'divine vendetta handicap -1.5 maps': {'4.34': '1xbet'},
                           'divine vendetta will win': {'2.408': '1xbet'},
                           'total over 2.5': {'2.14': '1xbet'},
                           'total under 2.5': {'1.66': '1xbet'},
                           'total — even': {'1.66': '1xbet'},
                           'total — odd': {'2.14': '1xbet'}},
 'divine vendetta - vici gaming': {'1-st map: divine vendetta will win': {'4.04': '1xbet'},
                                   '1-st map: divine vendetta will win in round 1': {'2.02': '1xbet'},
                                   '1-st map: divine vendetta will win in round 16': {'2.02': '1xbet'},
                                   '1-st map: handicap divine vendetta +4.5': {'2.14': '1xbet'},
                                   '1-st map: handicap divine vendetta +5.5': {'1.86': '1xbet'},
                                   '1-st map: handicap divine vendetta +6.5': {'1.63': '1xbet'},
                                   '1-st map: handicap vici gaming -4.5': {'1.66': '1xbet'},
                                   '1-st map: handicap vici gaming -5.5': {'1.88': '1xbet'},
                                   '1-st map: handicap vici gaming -6.5': {'2.19': '1xbet'},
                                   '1-st map: total over 25.5': {'1.79': '1xbet'},
                                   '1-st map: total over 26.5': {'2.14': '1xbet'},
                                   '1-st map: total under 25.5': {'1.96': '1xbet'},
                                   '1-st map: total under 26.5': {'1.66': '1xbet'},
                                   '1-st map: vici gaming will win': {'1.22': '1xbet'},
                                   '1-st map: vici gaming will win in round 1': {'1.74': '1xbet'},
                                   '1-st map: vici gaming will win in round 16': {'1.74': '1xbet'},
                                   '2-nd map: divine vendetta will win': {'4.04': '1xbet'},
                                   '2-nd map: divine vendetta will win in round 1': {'2.01': '1xbet'},
                                   '2-nd map: divine vendetta will win in round 16': {'2.02': '1xbet'},
                                   '2-nd map: handicap divine vendetta +4.5': {'2.16': '1xbet'},
                                   '2-nd map: handicap divine vendetta +5.5': {'1.87': '1xbet'},
                                   '2-nd map: handicap divine vendetta +6.5': {'1.64': '1xbet'},
                                   '2-nd map: handicap vici gaming -4.5': {'1.65': '1xbet'},
                                   '2-nd map: handicap vici gaming -5.5': {'1.87': '1xbet'},
                                   '2-nd map: handicap vici gaming -6.5': {'2.17': '1xbet'},
                                   '2-nd map: total over 25.5': {'1.8': '1xbet'},
                                   '2-nd map: total over 26.5': {'2.16': '1xbet'},
                                   '2-nd map: total under 25.5': {'1.94': '1xbet'},
                                   '2-nd map: total under 26.5': {'1.65': '1xbet'},
                                   '2-nd map: vici gaming will win': {'1.22': '1xbet'},
                                   '2-nd map: vici gaming will win in round 1': {'1.75': '1xbet'},
                                   '2-nd map: vici gaming will win in round 16': {'1.74': '1xbet'},
                                   'divine vendetta handicap +1.5 maps': {'2.57': '1xbet'},
                                   'divine vendetta handicap -1.5 maps': {'10': '1xbet'},
                                   'divine vendetta will win': {'5.9': '1xbet'},
                                   'total over 2.5': {'2.99': '1xbet'},
                                   'total under 2.5': {'1.36': '1xbet'},
                                   'total — even': {'1.36': '1xbet'},
                                   'total — odd': {'2.99': '1xbet'},
                                   'vici gaming handicap +1.5 maps': {'1.03': '1xbet'},
                                   'vici gaming handicap -1.5 maps': {'1.47': '1xbet'},
                                   'vici gaming will win': {'1.12': '1xbet'}},
 'evil geniuses - liquid': {'1-st map: evil geniuses will win': {'1.896': '1xbet'},
                            '1-st map: evil geniuses will win in round 1': {'1.87': '1xbet'},
                            '1-st map: evil geniuses will win in round 16': {'1.87': '1xbet'},
                            '1-st map: handicap evil geniuses +2.5': {'1.54': '1xbet'},
                            '1-st map: handicap evil geniuses +3.5': {'1.42': '1xbet'},
                            '1-st map: handicap evil geniuses +4.5': {'1.32': '1xbet'},
                            '1-st map: handicap evil geniuses +5.5': {'1.23': '1xbet'},
                            '1-st map: handicap evil geniuses -2.5': {'2.35': '1xbet'},
                            '1-st map: handicap evil geniuses -3.5': {'2.73': '1xbet'},
                            '1-st map: handicap evil geniuses -4.5': {'3.2': '1xbet'},
                            '1-st map: handicap evil geniuses -5.5': {'3.78': '1xbet'},
                            '1-st map: handicap liquid +2.5': {'1.55': '1xbet'},
                            '1-st map: handicap liquid +3.5': {'1.42': '1xbet'},
                            '1-st map: handicap liquid +4.5': {'1.32': '1xbet'},
                            '1-st map: handicap liquid +5.5': {'1.24': '1xbet'},
                            '1-st map: handicap liquid -2.5': {'2.38': '1xbet'},
                            '1-st map: handicap liquid -3.5': {'2.73': '1xbet'},
                            '1-st map: handicap liquid -4.5': {'3.2': '1xbet'},
                            '1-st map: handicap liquid -5.5': {'3.88': '1xbet'},
                            '1-st map: individual total 1 over 10.5': {'1.225': '1xbet'},
                            '1-st map: individual total 1 over 11.5': {'1.296': '1xbet'},
                            '1-st map: individual total 1 over 12.5': {'1.39': '1xbet'},
                            '1-st map: individual total 1 over 13.5': {'1.51': '1xbet'},
                            '1-st map: individual total 1 over 14.5': {'1.64': '1xbet'},
                            '1-st map: individual total 1 under 10.5': {'3.78': '1xbet'},
                            '1-st map: individual total 1 under 11.5': {'3.2': '1xbet'},
                            '1-st map: individual total 1 under 12.5': {'2.73': '1xbet'},
                            '1-st map: individual total 1 under 13.5': {'2.35': '1xbet'},
                            '1-st map: individual total 1 under 14.5': {'2.09': '1xbet'},
                            '1-st map: individual total 2 over 10.5': {'1.215': '1xbet'},
                            '1-st map: individual total 2 over 11.5': {'1.296': '1xbet'},
                            '1-st map: individual total 2 over 12.5': {'1.39': '1xbet'},
                            '1-st map: individual total 2 under 10.5': {'3.88': '1xbet'},
                            '1-st map: individual total 2 under 11.5': {'3.2': '1xbet'},
                            '1-st map: individual total 2 under 12.5': {'2.73': '1xbet'},
                            '1-st map: liquid will win': {'1.856': '1xbet'},
                            '1-st map: liquid will win in round 1': {'1.87': '1xbet'},
                            '1-st map: liquid will win in round 16': {'1.87': '1xbet'},
                            '1-st map: total over 24.5': {'1.3': '1xbet'},
                            '1-st map: total over 25.5': {'1.46': '1xbet'},
                            '1-st map: total over 26.5': {'1.7': '1xbet'},
                            '1-st map: total over 27.5': {'2.06': '1xbet'},
                            '1-st map: total over 28.5': {'2.66': '1xbet'},
                            '1-st map: total over 29.5': {'3.78': '1xbet'},
                            '1-st map: total under 24.5': {'3.32': '1xbet'},
                            '1-st map: total under 25.5': {'2.6': '1xbet'},
                            '1-st map: total under 26.5': {'2.08': '1xbet'},
                            '1-st map: total under 27.5': {'1.71': '1xbet'},
                            '1-st map: total under 28.5': {'1.44': '1xbet'},
                            '1-st map: total under 29.5': {'1.24': '1xbet'},
                            '1-st map: will there be overtime? - no': {'1.09': '1xbet'},
                            '1-st map: will there be overtime? - yes': {'6.55': '1xbet'},
                            'evil geniuses handicap +1.5 maps': {'1.29': '1xbet'},
                            'evil geniuses handicap -1.5 maps': {'3.38': '1xbet'},
                            'evil geniuses will win': {'1.856': '1xbet'},
                            'liquid handicap +1.5 maps': {'1.29': '1xbet'},
                            'liquid handicap -1.5 maps': {'3.38': '1xbet'},
                            'liquid will win': {'1.912': '1xbet'},
                            'total over 2.5': {'1.925': '1xbet'},
                            'total under 2.5': {'1.81': '1xbet'},
                            'total — even': {'1.81': '1xbet'},
                            'total — odd': {'1.93': '1xbet'}},
 'fnatic - godsent': {'1-st map: fnatic will win': {'1.53': '1xbet'},
                      '1-st map: fnatic will win in round 1': {'1.82': '1xbet'},
                      '1-st map: fnatic will win in round 16': {'1.82': '1xbet'},
                      '1-st map: godsent will win': {'2.42': '1xbet'},
                      '1-st map: godsent will win in round 1': {'1.92': '1xbet'},
                      '1-st map: godsent will win in round 16': {'1.92': '1xbet'},
                      '1-st map: handicap fnatic +2.5': {'1.32': '1xbet'},
                      '1-st map: handicap fnatic +3.5': {'1.25': '1xbet'},
                      '1-st map: handicap fnatic -2.5': {'1.86': '1xbet'},
                      '1-st map: handicap fnatic -3.5': {'2.11': '1xbet'},
                      '1-st map: handicap fnatic -4.5': {'2.43': '1xbet'},
                      '1-st map: handicap fnatic -5.5': {'2.85': '1xbet'},
                      '1-st map: handicap fnatic -6.5': {'3.46': '1xbet'},
                      '1-st map: handicap godsent +2.5': {'1.88': '1xbet'},
                      '1-st map: handicap godsent +3.5': {'1.68': '1xbet'},
                      '1-st map: handicap godsent +4.5': {'1.52': '1xbet'},
                      '1-st map: handicap godsent +5.5': {'1.39': '1xbet'},
                      '1-st map: handicap godsent +6.5': {'1.28': '1xbet'},
                      '1-st map: handicap godsent -2.5': {'3.2': '1xbet'},
                      '1-st map: handicap godsent -3.5': {'3.7': '1xbet'},
                      '1-st map: individual total 1 over 12.5': {'1.23': '1xbet'},
                      '1-st map: individual total 1 over 14.5': {'1.38': '1xbet'},
                      '1-st map: individual total 1 under 12.5': {'3.7': '1xbet'},
                      '1-st map: individual total 1 under 14.5': {'2.77': '1xbet'},
                      '1-st map: individual total 2 over 10.5': {'1.36': '1xbet'},
                      '1-st map: individual total 2 over 11.5': {'1.485': '1xbet'},
                      '1-st map: individual total 2 over 12.5': {'1.63': '1xbet'},
                      '1-st map: individual total 2 over 9.5': {'1.26': '1xbet'},
                      '1-st map: individual total 2 under 10.5': {'2.85': '1xbet'},
                      '1-st map: individual total 2 under 11.5': {'2.43': '1xbet'},
                      '1-st map: individual total 2 under 12.5': {'2.11': '1xbet'},
                      '1-st map: individual total 2 under 9.5': {'3.46': '1xbet'},
                      '1-st map: total over 24.5': {'1.32': '1xbet'},
                      '1-st map: total over 25.5': {'1.49': '1xbet'},
                      '1-st map: total over 26.5': {'1.74': '1xbet'},
                      '1-st map: total over 27.5': {'2.12': '1xbet'},
                      '1-st map: total over 28.5': {'2.73': '1xbet'},
                      '1-st map: total over 29.5': {'3.88': '1xbet'},
                      '1-st map: total under 24.5': {'3.2': '1xbet'},
                      '1-st map: total under 25.5': {'2.51': '1xbet'},
                      '1-st map: total under 26.5': {'2.02': '1xbet'},
                      '1-st map: total under 27.5': {'1.67': '1xbet'},
                      '1-st map: total under 28.5': {'1.42': '1xbet'},
                      '1-st map: total under 29.5': {'1.23': '1xbet'},
                      '1-st map: will there be overtime? - no': {'1.08': '1xbet'},
                      '1-st map: will there be overtime? - yes': {'6.9': '1xbet'},
                      'fnatic handicap +1.5 maps': {'1.13': '1xbet'},
                      'fnatic handicap -1.5 maps': {'2.29': '1xbet'},
                      'fnatic will win': {'1.43': '1xbet'},
                      'godsent handicap +1.5 maps': {'1.544': '1xbet'},
                      'godsent handicap -1.5 maps': {'5.4': '1xbet'},
                      'godsent will win': {'2.745': '1xbet'},
                      'half, 1-st map: 2 half - handicap +fnatic -3.5': {'3.32': '1xbet'},
                      'half, 1-st map: 2 half - handicap +godsent -1.5': {'3.04': '1xbet'},
                      'total over 2.5': {'2.032': '1xbet'},
                      'total under 2.5': {'1.72': '1xbet'},
                      'total — even': {'1.72': '1xbet'},
                      'total — odd': {'2.05': '1xbet'}},
 'forze - nordavind': {'1-st map: forze will win': {'1.58': '1xbet'},
                       '1-st map: forze will win in round 1': {'1.83': '1xbet'},
                       '1-st map: forze will win in round 16': {'1.82': '1xbet'},
                       '1-st map: handicap forze -2.5': {'1.89': '1xbet'},
                       '1-st map: handicap forze -3.5': {'2.12': '1xbet'},
                       '1-st map: handicap forze -4.5': {'2.43': '1xbet'},
                       '1-st map: handicap nordavind +2.5': {'1.85': '1xbet'},
                       '1-st map: handicap nordavind +3.5': {'1.67': '1xbet'},
                       '1-st map: handicap nordavind +4.5': {'1.52': '1xbet'},
                       '1-st map: nordavind will win': {'2.304': '1xbet'},
                       '1-st map: nordavind will win in round 1': {'1.91': '1xbet'},
                       '1-st map: nordavind will win in round 16': {'1.92': '1xbet'},
                       '1-st map: total over 25.5': {'1.55': '1xbet'},
                       '1-st map: total over 26.5': {'1.82': '1xbet'},
                       '1-st map: total over 27.5': {'2.23': '1xbet'},
                       '1-st map: total under 25.5': {'2.35': '1xbet'},
                       '1-st map: total under 26.5': {'1.92': '1xbet'},
                       '1-st map: total under 27.5': {'1.61': '1xbet'},
                       '2-nd map: forze will win': {'1.57': '1xbet'},
                       '2-nd map: forze will win in round 1': {'1.82': '1xbet'},
                       '2-nd map: forze will win in round 16': {'1.82': '1xbet'},
                       '2-nd map: handicap forze -2.5': {'1.87': '1xbet'},
                       '2-nd map: handicap forze -3.5': {'2.11': '1xbet'},
                       '2-nd map: handicap forze -4.5': {'2.4': '1xbet'},
                       '2-nd map: handicap nordavind +2.5': {'1.87': '1xbet'},
                       '2-nd map: handicap nordavind +3.5': {'1.68': '1xbet'},
                       '2-nd map: handicap nordavind +4.5': {'1.53': '1xbet'},
                       '2-nd map: nordavind will win': {'2.325': '1xbet'},
                       '2-nd map: nordavind will win in round 1': {'1.92': '1xbet'},
                       '2-nd map: nordavind will win in round 16': {'1.92': '1xbet'},
                       '2-nd map: total over 25.5': {'1.56': '1xbet'},
                       '2-nd map: total over 26.5': {'1.83': '1xbet'},
                       '2-nd map: total over 27.5': {'2.25': '1xbet'},
                       '2-nd map: total under 25.5': {'2.33': '1xbet'},
                       '2-nd map: total under 26.5': {'1.91': '1xbet'},
                       '2-nd map: total under 27.5': {'1.6': '1xbet'},
                       'forze handicap +1.5 maps': {'1.17': '1xbet'},
                       'forze handicap -1.5 maps': {'2.33': '1xbet'},
                       'forze will win': {'1.5': '1xbet'},
                       'nordavind handicap +1.5 maps': {'1.54': '1xbet'},
                       'nordavind handicap -1.5 maps': {'4.64': '1xbet'},
                       'nordavind will win': {'2.53': '1xbet'},
                       'total over 2.5': {'2.17': '1xbet'},
                       'total under 2.5': {'1.64': '1xbet'},
                       'total — even': {'1.64': '1xbet'},
                       'total — odd': {'2.17': '1xbet'}},
 'global - knockturnal': {'1-st map: global will win': {'1.1': '1xbet'},
                          '1-st map: knockturnal will win': {'6.3': '1xbet'},
                          'global will win': {'1.1': '1xbet'},
                          'knockturnal will win': {'6.5': '1xbet'}},
 'gobananas - royalty': {'1-st map: gobananas will win': {'1.51': '1xbet'},
                         '1-st map: royalty will win': {'2.475': '1xbet'},
                         'gobananas will win': {'1.53': '1xbet'},
                         'royalty will win': {'2.448': '1xbet'}},
 'grazur - lethal divide': {'1-st map: grazur will win': {'2.28': '1xbet'},
                            '1-st map: lethal divide will win': {'1.59': '1xbet'},
                            '2-nd map: grazur will win': {'2.304': '1xbet'},
                            '2-nd map: lethal divide will win': {'1.58': '1xbet'},
                            'grazur will win': {'2.71': '1xbet'},
                            'lethal divide will win': {'1.445': '1xbet'}},
 'ground zero gaming - rooster': {'1-st map: ground zero gaming will win': {'2.352': '1xbet'},
                                  '1-st map: ground zero gaming will win in round 1': {'1.92': '1xbet'},
                                  '1-st map: ground zero gaming will win in round 16': {'1.92': '1xbet'},
                                  '1-st map: handicap ground zero gaming +2.5': {'1.88': '1xbet'},
                                  '1-st map: handicap ground zero gaming +3.5': {'1.69': '1xbet'},
                                  '1-st map: handicap ground zero gaming +4.5': {'1.54': '1xbet'},
                                  '1-st map: handicap ground zero gaming +5.5': {'1.41': '1xbet'},
                                  '1-st map: handicap ground zero gaming +6.5': {'1.3': '1xbet'},
                                  '1-st map: handicap ground zero gaming -2.5': {'3.04': '1xbet'},
                                  '1-st map: handicap rooster +2.5': {'1.35': '1xbet'},
                                  '1-st map: handicap rooster -2.5': {'1.86': '1xbet'},
                                  '1-st map: handicap rooster -3.5': {'2.09': '1xbet'},
                                  '1-st map: handicap rooster -4.5': {'2.38': '1xbet'},
                                  '1-st map: handicap rooster -5.5': {'2.77': '1xbet'},
                                  '1-st map: handicap rooster -6.5': {'3.32': '1xbet'},
                                  '1-st map: rooster will win': {'1.56': '1xbet'},
                                  '1-st map: rooster will win in round 1': {'1.82': '1xbet'},
                                  '1-st map: rooster will win in round 16': {'1.82': '1xbet'},
                                  '1-st map: total over 24.5': {'1.37': '1xbet'},
                                  '1-st map: total over 25.5': {'1.56': '1xbet'},
                                  '1-st map: total over 26.5': {'1.83': '1xbet'},
                                  '1-st map: total over 27.5': {'2.25': '1xbet'},
                                  '1-st map: total over 28.5': {'2.9': '1xbet'},
                                  '1-st map: total under 24.5': {'2.94': '1xbet'},
                                  '1-st map: total under 25.5': {'2.33': '1xbet'},
                                  '1-st map: total under 26.5': {'1.91': '1xbet'},
                                  '1-st map: total under 27.5': {'1.6': '1xbet'},
                                  '1-st map: total under 28.5': {'1.38': '1xbet'},
                                  '2-nd map: ground zero gaming will win': {'2.37': '1xbet'},
                                  '2-nd map: ground zero gaming will win in round 1': {'1.92': '1xbet'},
                                  '2-nd map: handicap ground zero gaming +2.5': {'1.89': '1xbet'},
                                  '2-nd map: handicap ground zero gaming +3.5': {'1.71': '1xbet'},
                                  '2-nd map: handicap ground zero gaming +4.5': {'1.55': '1xbet'},
                                  '2-nd map: handicap ground zero gaming +5.5': {'1.42': '1xbet'},
                                  '2-nd map: handicap ground zero gaming -2.5': {'3.04': '1xbet'},
                                  '2-nd map: handicap rooster +2.5': {'1.35': '1xbet'},
                                  '2-nd map: handicap rooster -2.5': {'1.85': '1xbet'},
                                  '2-nd map: handicap rooster -3.5': {'2.06': '1xbet'},
                                  '2-nd map: handicap rooster -4.5': {'2.35': '1xbet'},
                                  '2-nd map: handicap rooster -5.5': {'2.73': '1xbet'},
                                  '2-nd map: rooster will win': {'1.55': '1xbet'},
                                  '2-nd map: rooster will win in round 1': {'1.82': '1xbet'},
                                  '2-nd map: total over 24.5': {'1.38': '1xbet'},
                                  '2-nd map: total over 25.5': {'1.56': '1xbet'},
                                  '2-nd map: total over 26.5': {'1.84': '1xbet'},
                                  '2-nd map: total over 27.5': {'2.25': '1xbet'},
                                  '2-nd map: total over 28.5': {'2.94': '1xbet'},
                                  '2-nd map: total under 24.5': {'2.9': '1xbet'},
                                  '2-nd map: total under 25.5': {'2.33': '1xbet'},
                                  '2-nd map: total under 26.5': {'1.9': '1xbet'},
                                  '2-nd map: total under 27.5': {'1.6': '1xbet'},
                                  '2-nd map: total under 28.5': {'1.37': '1xbet'},
                                  'ground zero gaming handicap +1.5 maps': {'1.59': '1xbet'},
                                  'ground zero gaming handicap -1.5 maps': {'4.8': '1xbet'},
                                  'ground zero gaming will win': {'2.655': '1xbet'},
                                  'rooster handicap +1.5 maps': {'1.16': '1xbet'},
                                  'rooster handicap -1.5 maps': {'2.27': '1xbet'},
                                  'rooster will win': {'1.46': '1xbet'},
                                  'total over 2.5': {'2.19': '1xbet'},
                                  'total under 2.5': {'1.63': '1xbet'},
                                  'total — even': {'1.63': '1xbet'},
                                  'total — odd': {'2.19': '1xbet'}},
 'hellraisers - syman': {'1-st map: handicap hellraisers +2.5': {'1.65': '1xbet'},
                         '1-st map: handicap hellraisers +3.5': {'1.51': '1xbet'},
                         '1-st map: handicap hellraisers +4.5': {'1.39': '1xbet'},
                         '1-st map: handicap hellraisers +5.5': {'1.3': '1xbet'},
                         '1-st map: handicap hellraisers +6.5': {'1.21': '1xbet'},
                         '1-st map: handicap hellraisers -2.5': {'2.51': '1xbet'},
                         '1-st map: handicap hellraisers -3.5': {'2.9': '1xbet'},
                         '1-st map: handicap hellraisers -4.5': {'3.32': '1xbet'},
                         '1-st map: handicap hellraisers -5.5': {'3.98': '1xbet'},
                         '1-st map: handicap syman +2.5': {'1.49': '1xbet'},
                         '1-st map: handicap syman +3.5': {'1.38': '1xbet'},
                         '1-st map: handicap syman +4.5': {'1.3': '1xbet'},
                         '1-st map: handicap syman +5.5': {'1.22': '1xbet'},
                         '1-st map: handicap syman -2.5': {'2.16': '1xbet'},
                         '1-st map: handicap syman -3.5': {'2.45': '1xbet'},
                         '1-st map: handicap syman -4.5': {'2.85': '1xbet'},
                         '1-st map: handicap syman -5.5': {'3.32': '1xbet'},
                         '1-st map: handicap syman -6.5': {'4.1': '1xbet'},
                         '1-st map: hellraisers will win': {'2.005': '1xbet'},
                         '1-st map: hellraisers will win in round 1': {'1.89': '1xbet'},
                         '1-st map: hellraisers will win in round 16': {'1.89': '1xbet'},
                         '1-st map: individual total 1 over 10.5': {'1.205': '1xbet'},
                         '1-st map: individual total 1 over 12.5': {'1.352': '1xbet'},
                         '1-st map: individual total 1 under 10.5': {'3.98': '1xbet'},
                         '1-st map: individual total 1 under 12.5': {'2.9': '1xbet'},
                         '1-st map: syman will win': {'1.77': '1xbet'},
                         '1-st map: syman will win in round 1': {'1.85': '1xbet'},
                         '1-st map: syman will win in round 16': {'1.85': '1xbet'},
                         '1-st map: total over 23.5': {'1.22': '1xbet'},
                         '1-st map: total over 24.5': {'1.35': '1xbet'},
                         '1-st map: total over 25.5': {'1.53': '1xbet'},
                         '1-st map: total over 26.5': {'1.79': '1xbet'},
                         '1-st map: total over 27.5': {'2.19': '1xbet'},
                         '1-st map: total over 28.5': {'2.85': '1xbet'},
                         '1-st map: total over 29.5': {'4.1': '1xbet'},
                         '1-st map: total under 23.5': {'3.98': '1xbet'},
                         '1-st map: total under 24.5': {'3.04': '1xbet'},
                         '1-st map: total under 25.5': {'2.405': '1xbet'},
                         '1-st map: total under 26.5': {'1.96': '1xbet'},
                         '1-st map: total under 27.5': {'1.63': '1xbet'},
                         '1-st map: total under 28.5': {'1.39': '1xbet'},
                         '1-st map: total under 29.5': {'1.21': '1xbet'},
                         'hellraisers will win': {'2.01': '1xbet'},
                         'syman will win': {'1.775': '1xbet'}},
 'heroic - og': {'1-st map: handicap heroic +2.5': {'1.49': '1xbet'},
                 '1-st map: handicap heroic +3.5': {'1.38': '1xbet'},
                 '1-st map: handicap heroic +4.5': {'1.29': '1xbet'},
                 '1-st map: handicap heroic +5.5': {'1.21': '1xbet'},
                 '1-st map: handicap heroic -2.5': {'2.25': '1xbet'},
                 '1-st map: handicap heroic -3.5': {'2.57': '1xbet'},
                 '1-st map: handicap heroic -4.5': {'3.04': '1xbet'},
                 '1-st map: handicap heroic -5.5': {'3.62': '1xbet'},
                 '1-st map: handicap og +2.5': {'1.6': '1xbet'},
                 '1-st map: handicap og +3.5': {'1.47': '1xbet'},
                 '1-st map: handicap og +4.5': {'1.35': '1xbet'},
                 '1-st map: handicap og +5.5': {'1.26': '1xbet'},
                 '1-st map: handicap og -2.5': {'2.51': '1xbet'},
                 '1-st map: handicap og -3.5': {'2.9': '1xbet'},
                 '1-st map: handicap og -4.5': {'3.38': '1xbet'},
                 '1-st map: handicap og -5.5': {'4.1': '1xbet'},
                 '1-st map: heroic will win': {'1.8': '1xbet'},
                 '1-st map: heroic will win in round 1': {'1.86': '1xbet'},
                 '1-st map: heroic will win in round 16': {'1.86': '1xbet'},
                 '1-st map: individual total 1 over 10.5': {'1.195': '1xbet'},
                 '1-st map: individual total 1 over 12.5': {'1.352': '1xbet'},
                 '1-st map: individual total 1 over 13.5': {'1.456': '1xbet'},
                 '1-st map: individual total 1 over 14.5': {'1.584': '1xbet'},
                 '1-st map: individual total 1 under 10.5': {'4.1': '1xbet'},
                 '1-st map: individual total 1 under 12.5': {'2.9': '1xbet'},
                 '1-st map: individual total 1 under 13.5': {'2.51': '1xbet'},
                 '1-st map: individual total 1 under 14.5': {'2.19': '1xbet'},
                 '1-st map: individual total 2 over 10.5': {'1.24': '1xbet'},
                 '1-st map: individual total 2 over 11.5': {'1.325': '1xbet'},
                 '1-st map: individual total 2 over 12.5': {'1.435': '1xbet'},
                 '1-st map: individual total 2 under 10.5': {'3.62': '1xbet'},
                 '1-st map: individual total 2 under 11.5': {'3.04': '1xbet'},
                 '1-st map: individual total 2 under 12.5': {'2.57': '1xbet'},
                 '1-st map: og will win': {'1.955': '1xbet'},
                 '1-st map: og will win in round 1': {'1.88': '1xbet'},
                 '1-st map: og will win in round 16': {'1.88': '1xbet'},
                 '1-st map: total over 24.5': {'1.3': '1xbet'},
                 '1-st map: total over 25.5': {'1.46': '1xbet'},
                 '1-st map: total over 26.5': {'1.7': '1xbet'},
                 '1-st map: total over 27.5': {'2.06': '1xbet'},
                 '1-st map: total over 28.5': {'2.66': '1xbet'},
                 '1-st map: total over 29.5': {'3.78': '1xbet'},
                 '1-st map: total under 24.5': {'3.32': '1xbet'},
                 '1-st map: total under 25.5': {'2.6': '1xbet'},
                 '1-st map: total under 26.5': {'2.08': '1xbet'},
                 '1-st map: total under 27.5': {'1.71': '1xbet'},
                 '1-st map: total under 28.5': {'1.44': '1xbet'},
                 '1-st map: total under 29.5': {'1.24': '1xbet'},
                 '1-st map: will there be overtime? - no': {'1.09': '1xbet'},
                 '1-st map: will there be overtime? - yes': {'6.55': '1xbet'},
                 'heroic handicap +1.5 maps': {'1.248': '1xbet'},
                 'heroic handicap -1.5 maps': {'3.09': '1xbet'},
                 'heroic will win': {'1.7': '1xbet'},
                 'og handicap +1.5 maps': {'1.34': '1xbet'},
                 'og handicap -1.5 maps': {'3.7': '1xbet'},
                 'og will win': {'2.11': '1xbet'},
                 'total over 2.5': {'1.92': '1xbet'},
                 'total under 2.5': {'1.81': '1xbet'},
                 'total — even': {'1.81': '1xbet'},
                 'total — odd': {'1.93': '1xbet'}},
 'hyper - rbg': {'1-st map: hyper will win': {'2.696': '1xbet'},
                 '1-st map: rbg will win': {'1.435': '1xbet'},
                 '2-nd map: hyper will win': {'2.69': '1xbet'},
                 '2-nd map: rbg will win': {'1.44': '1xbet'},
                 'hyper will win': {'2.01': '1xbet'},
                 'rbg will win': {'1.32': '1xbet'}},
 'invictus gaming - lucid dream': {'1-st map: handicap invictus gaming -2.5': {'1.68': '1xbet'},
                                   '1-st map: handicap invictus gaming -3.5': {'1.86': '1xbet'},
                                   '1-st map: handicap invictus gaming -4.5': {'2.11': '1xbet'},
                                   '1-st map: handicap lucid dream +2.5': {'2.11': '1xbet'},
                                   '1-st map: handicap lucid dream +3.5': {'1.88': '1xbet'},
                                   '1-st map: handicap lucid dream +4.5': {'1.68': '1xbet'},
                                   '1-st map: invictus gaming will win': {'1.42': '1xbet'},
                                   '1-st map: invictus gaming will win in round 1': {'1.8': '1xbet'},
                                   '1-st map: invictus gaming will win in round 16': {'1.8': '1xbet'},
                                   '1-st map: lucid dream will win': {'2.75': '1xbet'},
                                   '1-st map: lucid dream will win in round 1': {'1.94': '1xbet'},
                                   '1-st map: lucid dream will win in round 16': {'1.94': '1xbet'},
                                   '1-st map: total over 26.5': {'1.89': '1xbet'},
                                   '1-st map: total under 26.5': {'1.85': '1xbet'},
                                   '2-nd map: handicap invictus gaming -2.5': {'1.67': '1xbet'},
                                   '2-nd map: handicap invictus gaming -3.5': {'1.85': '1xbet'},
                                   '2-nd map: handicap invictus gaming -4.5': {'2.09': '1xbet'},
                                   '2-nd map: handicap lucid dream +2.5': {'2.12': '1xbet'},
                                   '2-nd map: handicap lucid dream +3.5': {'1.89': '1xbet'},
                                   '2-nd map: handicap lucid dream +4.5': {'1.69': '1xbet'},
                                   '2-nd map: invictus gaming will win': {'1.41': '1xbet'},
                                   '2-nd map: invictus gaming will win in round 1': {'1.79': '1xbet'},
                                   '2-nd map: invictus gaming will win in round 16': {'1.79': '1xbet'},
                                   '2-nd map: lucid dream will win': {'2.79': '1xbet'},
                                   '2-nd map: lucid dream will win in round 1': {'1.96': '1xbet'},
                                   '2-nd map: lucid dream will win in round 16': {'1.96': '1xbet'},
                                   '2-nd map: total over 25.5': {'1.61': '1xbet'},
                                   '2-nd map: total over 26.5': {'1.9': '1xbet'},
                                   '2-nd map: total under 25.5': {'2.23': '1xbet'},
                                   '2-nd map: total under 26.5': {'1.84': '1xbet'},
                                   'invictus gaming handicap +1.5 maps': {'1.11': '1xbet'},
                                   'invictus gaming handicap -1.5 maps': {'1.94': '1xbet'},
                                   'invictus gaming will win': {'1.325': '1xbet'},
                                   'lucid dream handicap +1.5 maps': {'1.8': '1xbet'},
                                   'lucid dream handicap -1.5 maps': {'5.9': '1xbet'},
                                   'lucid dream will win': {'3.24': '1xbet'},
                                   'total over 2.5': {'2.33': '1xbet'},
                                   'total under 2.5': {'1.56': '1xbet'},
                                   'total — even': {'1.56': '1xbet'},
                                   'total — odd': {'2.33': '1xbet'}},
 'invictus gaming - mazaalai': {'1-st map: handicap invictus gaming -3.5': {'1.66': '1xbet'},
                                '1-st map: handicap invictus gaming -4.5': {'1.86': '1xbet'},
                                '1-st map: handicap invictus gaming -5.5': {'2.14': '1xbet'},
                                '1-st map: handicap mazaalai +3.5': {'2.14': '1xbet'},
                                '1-st map: handicap mazaalai +4.5': {'1.88': '1xbet'},
                                '1-st map: handicap mazaalai +5.5': {'1.66': '1xbet'},
                                '1-st map: invictus gaming will win': {'1.31': '1xbet'},
                                '1-st map: invictus gaming will win in round 1': {'1.77': '1xbet'},
                                '1-st map: invictus gaming will win in round 16': {'1.77': '1xbet'},
                                '1-st map: mazaalai will win': {'3.28': '1xbet'},
                                '1-st map: mazaalai will win in round 1': {'1.98': '1xbet'},
                                '1-st map: mazaalai will win in round 16': {'1.98': '1xbet'},
                                '1-st map: total over 25.5': {'1.68': '1xbet'},
                                '1-st map: total over 26.5': {'1.99': '1xbet'},
                                '1-st map: total under 25.5': {'2.11': '1xbet'},
                                '1-st map: total under 26.5': {'1.76': '1xbet'},
                                '2-nd map: handicap invictus gaming -3.5': {'1.65': '1xbet'},
                                '2-nd map: handicap invictus gaming -4.5': {'1.84': '1xbet'},
                                '2-nd map: handicap invictus gaming -5.5': {'2.11': '1xbet'},
                                '2-nd map: handicap mazaalai +3.5': {'2.16': '1xbet'},
                                '2-nd map: handicap mazaalai +4.5': {'1.9': '1xbet'},
                                '2-nd map: handicap mazaalai +5.5': {'1.68': '1xbet'},
                                '2-nd map: invictus gaming will win': {'1.3': '1xbet'},
                                '2-nd map: invictus gaming will win in round 1': {'1.77': '1xbet'},
                                '2-nd map: invictus gaming will win in round 16': {'1.76': '1xbet'},
                                '2-nd map: mazaalai will win': {'3.36': '1xbet'},
                                '2-nd map: mazaalai will win in round 1': {'1.98': '1xbet'},
                                '2-nd map: mazaalai will win in round 16': {'1.99': '1xbet'},
                                '2-nd map: total over 25.5': {'1.69': '1xbet'},
                                '2-nd map: total over 26.5': {'2.01': '1xbet'},
                                '2-nd map: total under 25.5': {'2.09': '1xbet'},
                                '2-nd map: total under 26.5': {'1.75': '1xbet'},
                                'invictus gaming handicap +1.5 maps': {'1.06': '1xbet'},
                                'invictus gaming handicap -1.5 maps': {'1.68': '1xbet'},
                                'invictus gaming will win': {'1.2': '1xbet'},
                                'mazaalai handicap +1.5 maps': {'2.11': '1xbet'},
                                'mazaalai handicap -1.5 maps': {'7.9': '1xbet'},
                                'mazaalai will win': {'4.32': '1xbet'},
                                'total over 2.5': {'2.6': '1xbet'},
                                'total under 2.5': {'1.46': '1xbet'},
                                'total — even': {'1.46': '1xbet'},
                                'total — odd': {'2.6': '1xbet'}},
 'kinship - thunder logic': {'1-st map: kinship will win': {'1.592': '1xbet'},
                             '1-st map: thunder logic will win': {'2.27': '1xbet'},
                             '2-nd map: kinship will win': {'1.59': '1xbet'},
                             '2-nd map: thunder logic will win': {'2.28': '1xbet'},
                             'kinship will win': {'1.51': '1xbet'},
                             'thunder logic will win': {'2.5': '1xbet'}},
 'kova - veto': {'1-st map: kova will win': {'1.41': '1xbet'},
                 '1-st map: veto will win': {'2.79': '1xbet'},
                 '2-nd map: kova will win': {'1.41': '1xbet'},
                 '2-nd map: veto will win': {'2.79': '1xbet'},
                 'kova will win': {'1.22': '1xbet'},
                 'veto will win': {'3.32': '1xbet'}},
 'lucid dream - tiger': {'1-st map: handicap lucid dream +2.5': {'2.02': '1xbet'},
                         '1-st map: handicap lucid dream +3.5': {'1.8': '1xbet'},
                         '1-st map: handicap lucid dream +4.5': {'1.62': '1xbet'},
                         '1-st map: handicap tiger -2.5': {'1.74': '1xbet'},
                         '1-st map: handicap tiger -3.5': {'1.94': '1xbet'},
                         '1-st map: handicap tiger -4.5': {'2.21': '1xbet'},
                         '1-st map: lucid dream will win': {'2.592': '1xbet'},
                         '1-st map: lucid dream will win in round 1': {'1.93': '1xbet'},
                         '1-st map: lucid dream will win in round 16': {'1.94': '1xbet'},
                         '1-st map: tiger will win': {'1.47': '1xbet'},
                         '1-st map: tiger will win in round 1': {'1.81': '1xbet'},
                         '1-st map: tiger will win in round 16': {'1.8': '1xbet'},
                         '1-st map: total over 26.5': {'1.86': '1xbet'},
                         '1-st map: total under 26.5': {'1.88': '1xbet'},
                         '2-nd map: handicap lucid dream +2.5': {'2.03': '1xbet'},
                         '2-nd map: handicap lucid dream +3.5': {'1.81': '1xbet'},
                         '2-nd map: handicap lucid dream +4.5': {'1.63': '1xbet'},
                         '2-nd map: handicap tiger -2.5': {'1.73': '1xbet'},
                         '2-nd map: handicap tiger -3.5': {'1.93': '1xbet'},
                         '2-nd map: handicap tiger -4.5': {'2.19': '1xbet'},
                         '2-nd map: lucid dream will win': {'2.59': '1xbet'},
                         '2-nd map: lucid dream will win in round 1': {'1.93': '1xbet'},
                         '2-nd map: lucid dream will win in round 16': {'1.93': '1xbet'},
                         '2-nd map: tiger will win': {'1.47': '1xbet'},
                         '2-nd map: tiger will win in round 1': {'1.81': '1xbet'},
                         '2-nd map: tiger will win in round 16': {'1.81': '1xbet'},
                         '2-nd map: total over 26.5': {'1.87': '1xbet'},
                         '2-nd map: total under 26.5': {'1.87': '1xbet'},
                         'lucid dream handicap +1.5 maps': {'1.72': '1xbet'},
                         'lucid dream handicap -1.5 maps': {'5.4': '1xbet'},
                         'lucid dream will win': {'3.016': '1xbet'},
                         'tiger handicap +1.5 maps': {'1.13': '1xbet'},
                         'tiger handicap -1.5 maps': {'2.05': '1xbet'},
                         'tiger will win': {'1.368': '1xbet'},
                         'total over 2.5': {'2.27': '1xbet'},
                         'total under 2.5': {'1.59': '1xbet'},
                         'total — even': {'1.59': '1xbet'},
                         'total — odd': {'2.27': '1xbet'}},
 'mazaalai - tyloo': {'1-st map: handicap mazaalai +4.5': {'2.17': '1xbet'},
                      '1-st map: handicap mazaalai +5.5': {'1.88': '1xbet'},
                      '1-st map: handicap mazaalai +6.5': {'1.65': '1xbet'},
                      '1-st map: handicap tyloo -4.5': {'1.64': '1xbet'},
                      '1-st map: handicap tyloo -5.5': {'1.86': '1xbet'},
                      '1-st map: handicap tyloo -6.5': {'2.16': '1xbet'},
                      '1-st map: mazaalai will win': {'4.16': '1xbet'},
                      '1-st map: mazaalai will win in round 1': {'2.02': '1xbet'},
                      '1-st map: mazaalai will win in round 16': {'2.02': '1xbet'},
                      '1-st map: total over 25.5': {'1.8': '1xbet'},
                      '1-st map: total over 26.5': {'2.16': '1xbet'},
                      '1-st map: total under 25.5': {'1.94': '1xbet'},
                      '1-st map: total under 26.5': {'1.65': '1xbet'},
                      '1-st map: tyloo will win': {'1.21': '1xbet'},
                      '1-st map: tyloo will win in round 1': {'1.74': '1xbet'},
                      '1-st map: tyloo will win in round 16': {'1.74': '1xbet'},
                      '2-nd map: handicap mazaalai +4.5': {'2.19': '1xbet'},
                      '2-nd map: handicap mazaalai +5.5': {'1.9': '1xbet'},
                      '2-nd map: handicap mazaalai +6.5': {'1.66': '1xbet'},
                      '2-nd map: handicap tyloo -4.5': {'1.63': '1xbet'},
                      '2-nd map: handicap tyloo -5.5': {'1.84': '1xbet'},
                      '2-nd map: handicap tyloo -6.5': {'2.14': '1xbet'},
                      '2-nd map: mazaalai will win': {'4.16': '1xbet'},
                      '2-nd map: mazaalai will win in round 1': {'2.02': '1xbet'},
                      '2-nd map: mazaalai will win in round 16': {'2.02': '1xbet'},
                      '2-nd map: total over 25.5': {'1.82': '1xbet'},
                      '2-nd map: total over 26.5': {'2.17': '1xbet'},
                      '2-nd map: total under 25.5': {'1.92': '1xbet'},
                      '2-nd map: total under 26.5': {'1.64': '1xbet'},
                      '2-nd map: tyloo will win': {'1.21': '1xbet'},
                      '2-nd map: tyloo will win in round 1': {'1.74': '1xbet'},
                      '2-nd map: tyloo will win in round 16': {'1.74': '1xbet'},
                      'mazaalai handicap +1.5 maps': {'2.63': '1xbet'},
                      'mazaalai handicap -1.5 maps': {'10': '1xbet'},
                      'mazaalai will win': {'6.2': '1xbet'},
                      'total over 2.5': {'3.04': '1xbet'},
                      'total under 2.5': {'1.35': '1xbet'},
                      'total — even': {'1.35': '1xbet'},
                      'total — odd': {'3.04': '1xbet'},
                      'tyloo handicap +1.5 maps': {'1.03': '1xbet'},
                      'tyloo handicap -1.5 maps': {'1.45': '1xbet'},
                      'tyloo will win': {'1.11': '1xbet'}},
 'mistaken - zigma': {'1-st map: mistaken will win': {'3.74': '1xbet'},
                      '1-st map: zigma will win': {'1.25': '1xbet'},
                      '2-nd map: mistaken will win': {'3.74': '1xbet'},
                      '2-nd map: zigma will win': {'1.25': '1xbet'},
                      'mistaken will win': {'5.15': '1xbet'},
                      'zigma will win': {'1.15': '1xbet'}},
 'nemiga gaming - sprout': {'1-st map: handicap nemiga gaming +2.5': {'1.91': '1xbet'},
                            '1-st map: handicap nemiga gaming +3.5': {'1.72': '1xbet'},
                            '1-st map: handicap nemiga gaming +4.5': {'1.56': '1xbet'},
                            '1-st map: handicap nemiga gaming +5.5': {'1.42': '1xbet'},
                            '1-st map: handicap nemiga gaming +6.5': {'1.31': '1xbet'},
                            '1-st map: handicap nemiga gaming +7.5': {'1.22': '1xbet'},
                            '1-st map: handicap nemiga gaming -2.5': {'3.09': '1xbet'},
                            '1-st map: handicap nemiga gaming -3.5': {'3.62': '1xbet'},
                            '1-st map: handicap sprout +2.5': {'1.34': '1xbet'},
                            '1-st map: handicap sprout +3.5': {'1.26': '1xbet'},
                            '1-st map: handicap sprout -2.5': {'1.83': '1xbet'},
                            '1-st map: handicap sprout -3.5': {'2.05': '1xbet'},
                            '1-st map: handicap sprout -4.5': {'2.33': '1xbet'},
                            '1-st map: handicap sprout -5.5': {'2.73': '1xbet'},
                            '1-st map: handicap sprout -6.5': {'3.26': '1xbet'},
                            '1-st map: handicap sprout -7.5': {'3.98': '1xbet'},
                            '1-st map: nemiga gaming will win': {'2.4': '1xbet'},
                            '1-st map: nemiga gaming will win in round 1': {'1.92': '1xbet'},
                            '1-st map: nemiga gaming will win in round 16': {'1.92': '1xbet'},
                            '1-st map: sprout will win': {'1.54': '1xbet'},
                            '1-st map: sprout will win in round 1': {'1.82': '1xbet'},
                            '1-st map: sprout will win in round 16': {'1.82': '1xbet'},
                            '1-st map: total over 23.5': {'1.24': '1xbet'},
                            '1-st map: total over 24.5': {'1.37': '1xbet'},
                            '1-st map: total over 25.5': {'1.56': '1xbet'},
                            '1-st map: total over 26.5': {'1.83': '1xbet'},
                            '1-st map: total over 27.5': {'2.25': '1xbet'},
                            '1-st map: total over 28.5': {'2.94': '1xbet'},
                            '1-st map: total over 29.5': {'4.22': '1xbet'},
                            '1-st map: total under 23.5': {'3.78': '1xbet'},
                            '1-st map: total under 24.5': {'2.94': '1xbet'},
                            '1-st map: total under 25.5': {'2.33': '1xbet'},
                            '1-st map: total under 26.5': {'1.91': '1xbet'},
                            '1-st map: total under 27.5': {'1.6': '1xbet'},
                            '1-st map: total under 28.5': {'1.37': '1xbet'},
                            '1-st map: total under 29.5': {'1.2': '1xbet'},
                            '2-nd map: handicap nemiga gaming +2.5': {'1.92': '1xbet'},
                            '2-nd map: handicap nemiga gaming -2.5': {'3.09': '1xbet'},
                            '2-nd map: handicap nemiga gaming -3.5': {'3.62': '1xbet'},
                            '2-nd map: handicap sprout +2.5': {'1.34': '1xbet'},
                            '2-nd map: handicap sprout +3.5': {'1.26': '1xbet'},
                            '2-nd map: handicap sprout -2.5': {'1.82': '1xbet'},
                            '2-nd map: nemiga gaming will win': {'2.42': '1xbet'},
                            '2-nd map: sprout will win': {'1.53': '1xbet'},
                            '2-nd map: total over 23.5': {'1.24': '1xbet'},
                            '2-nd map: total over 24.5': {'1.38': '1xbet'},
                            '2-nd map: total over 25.5': {'1.57': '1xbet'},
                            '2-nd map: total over 26.5': {'1.85': '1xbet'},
                            '2-nd map: total over 27.5': {'2.27': '1xbet'},
                            '2-nd map: total under 23.5': {'3.78': '1xbet'},
                            '2-nd map: total under 24.5': {'2.9': '1xbet'},
                            '2-nd map: total under 25.5': {'2.31': '1xbet'},
                            '2-nd map: total under 26.5': {'1.89': '1xbet'},
                            '2-nd map: total under 27.5': {'1.59': '1xbet'},
                            'nemiga gaming handicap +1.5 maps': {'1.605': '1xbet'},
                            'nemiga gaming handicap -1.5 maps': {'4.8': '1xbet'},
                            'nemiga gaming will win': {'2.685': '1xbet'},
                            'sprout handicap +1.5 maps': {'1.16': '1xbet'},
                            'sprout handicap -1.5 maps': {'2.23': '1xbet'},
                            'sprout will win': {'1.45': '1xbet'},
                            'total over 2.5': {'2.21': '1xbet'},
                            'total under 2.5': {'1.62': '1xbet'},
                            'total — even': {'1.62': '1xbet'},
                            'total — odd': {'2.21': '1xbet'}},
 'third impact - valkyrie': {'1-st map: third impact will win': {'1.55': '1xbet'},
                             '1-st map: valkyrie will win': {'2.37': '1xbet'},
                             '2-nd map: third impact will win': {'1.55': '1xbet'},
                             '2-nd map: valkyrie will win': {'2.37': '1xbet'},
                             'third impact will win': {'1.45': '1xbet'},
                             'valkyrie will win': {'2.69': '1xbet'}}}
