bets =  {'ago - nordavind': {'1-st map: handicap ago +2.5': {'1.85': 'parimatch'},
                     '1-st map: handicap ago +3.5': {'1.62': 'parimatch'},
                     '1-st map: handicap ago -2.5': {'2.48': 'parimatch'},
                     '1-st map: handicap nordavind +2.5': {'1.50': 'parimatch'},
                     '1-st map: handicap nordavind -2.5': {'1.90': 'parimatch'},
                     '1-st map: handicap nordavind -3.5': {'2.20': 'parimatch'},
                     '1-st map: total over 25.5': {'1.50': 'parimatch'},
                     '1-st map: total over 26.5': {'1.72': 'parimatch'},
                     '1-st map: total over 27.5': {'2.15': 'parimatch'},
                     '1-st map: total under 25.5': {'2.48': 'parimatch'},
                     '1-st map: total under 26.5': {'2.05': 'parimatch'},
                     '1-st map: total under 27.5': {'1.65': 'parimatch'},
                     'win of the 1st': {'1.70': 'parimatch'},
                     'win of the 2nd': {'2.08': 'parimatch'}},
 'ahq - asking questions': {'win of the 1st': {'1.75': 'parimatch'},
                            'win of the 2nd': {'2.01': 'parimatch'}},
 'aim4r - w2c': {'win of the 1st': {'1.50': 'parimatch'},
                 'win of the 2nd': {'2.48': 'parimatch'}},
 'apeks - nemiga': {'1-st map: handicap apeks +2.5': {'2.25': 'parimatch'},
                    '1-st map: handicap apeks +3.5': {'1.95': 'parimatch'},
                    '1-st map: handicap apeks +4.5': {'1.70': 'parimatch'},
                    '1-st map: handicap nemiga -2.5': {'1.60': 'parimatch'},
                    '1-st map: handicap nemiga -3.5': {'1.80': 'parimatch'},
                    '1-st map: handicap nemiga -4.5': {'2.08': 'parimatch'},
                    '1-st map: total over 25.5': {'1.65': 'parimatch'},
                    '1-st map: total over 26.5': {'1.92': 'parimatch'},
                    '1-st map: total over 27.5': {'2.48': 'parimatch'},
                    '1-st map: total under 25.5': {'2.15': 'parimatch'},
                    '1-st map: total under 26.5': {'1.82': 'parimatch'},
                    '1-st map: total under 27.5': {'1.50': 'parimatch'},
                    '1-st map: win of the 1st': {'2.80': 'parimatch'},
                    '1-st map: win of the 2nd': {'1.40': 'parimatch'},
                    'apeks handicap +1.5 maps': {'1.77': 'parimatch'},
                    'nemiga handicap -1.5 maps': {'1.97': 'parimatch'},
                    'total over 2.5': {'2.25': 'parimatch'},
                    'total under 2.5': {'1.60': 'parimatch'},
                    'win of the 1st': {'3.30': 'parimatch'},
                    'win of the 2nd': {'1.30': 'parimatch'}},
 'avant - paradox': {'1-st map: handicap avant -3.5': {'1.72': 'parimatch'},
                     '1-st map: handicap avant -4.5': {'1.97': 'parimatch'},
                     '1-st map: handicap avant -5.5': {'2.25': 'parimatch'},
                     '1-st map: handicap paradox +3.5': {'2.05': 'parimatch'},
                     '1-st map: handicap paradox +4.5': {'1.77': 'parimatch'},
                     '1-st map: handicap paradox +5.5': {'1.60': 'parimatch'},
                     '1-st map: total over 25.5': {'1.70': 'parimatch'},
                     '1-st map: total over 26.5': {'1.95': 'parimatch'},
                     '1-st map: total over 27.5': {'2.48': 'parimatch'},
                     '1-st map: total under 25.5': {'2.08': 'parimatch'},
                     '1-st map: total under 26.5': {'1.80': 'parimatch'},
                     '1-st map: total under 27.5': {'1.50': 'parimatch'},
                     '1-st map: win of the 1st': {'1.35': 'parimatch'},
                     '1-st map: win of the 2nd': {'3.05': 'parimatch'},
                     'avant handicap -1.5 maps': {'1.82': 'parimatch'},
                     'paradox handicap +1.5 maps': {'1.92': 'parimatch'},
                     'total over 2.5': {'2.35': 'parimatch'},
                     'total under 2.5': {'1.55': 'parimatch'},
                     'win of the 1st': {'1.25': 'parimatch'},
                     'win of the 2nd': {'3.75': 'parimatch'}},
 'big - vitality': {'1-st map: handicap big +2.5': {'1.55': 'parimatch'},
                    '1-st map: handicap big -2.5': {'2.00': 'parimatch'},
                    '1-st map: handicap big -3.5': {'2.30': 'parimatch'},
                    '1-st map: handicap vitality +2.5': {'1.76': 'parimatch'},
                    '1-st map: handicap vitality +3.5': {'1.58': 'parimatch'},
                    '1-st map: handicap vitality -2.5': {'2.35': 'parimatch'},
                    '1-st map: total over 25.5': {'1.47': 'parimatch'},
                    '1-st map: total over 26.5': {'1.77': 'parimatch'},
                    '1-st map: total over 27.5': {'2.15': 'parimatch'},
                    '1-st map: total under 25.5': {'2.55': 'parimatch'},
                    '1-st map: total under 26.5': {'1.97': 'parimatch'},
                    '1-st map: total under 27.5': {'1.65': 'parimatch'},
                    '1-st map: win of the 1st': {'2.01': 'parimatch'},
                    '1-st map: win of the 2nd': {'1.75': 'parimatch'},
                    'big handicap -1.5 maps': {'3.05': 'parimatch'},
                    'total over 2.5': {'1.95': 'parimatch'},
                    'total under 2.5': {'1.80': 'parimatch'},
                    'vitality handicap +1.5 maps': {'1.35': 'parimatch'},
                    'win of the 1st': {'2.15': 'parimatch'},
                    'win of the 2nd': {'1.65': 'parimatch'}},
 'bmth - royalty': {'1-st map: away win': {'1.55': 'parimatch'},
                    '1-st map: handicap bmth +2.5': {'2.01': 'parimatch'},
                    '1-st map: handicap bmth +3.5': {'1.76': 'parimatch'},
                    '1-st map: handicap bmth +4.5': {'1.55': 'parimatch'},
                    '1-st map: handicap royalty -2.5': {'1.75': 'parimatch'},
                    '1-st map: handicap royalty -3.5': {'2.00': 'parimatch'},
                    '1-st map: handicap royalty -4.5': {'2.35': 'parimatch'},
                    '1-st map: home win': {'2.35': 'parimatch'},
                    '1-st map: total over 25.5': {'1.57': 'parimatch'},
                    '1-st map: total over 26.5': {'1.87': 'parimatch'},
                    '1-st map: total over 27.5': {'2.35': 'parimatch'},
                    '1-st map: total under 25.5': {'2.31': 'parimatch'},
                    '1-st map: total under 26.5': {'1.87': 'parimatch'},
                    '1-st map: total under 27.5': {'1.55': 'parimatch'},
                    'away win': {'2.35': 'parimatch'},
                    'bmth handicap +0.5 maps': {'1.55': 'parimatch'},
                    'draw': {'2.00': 'parimatch'},
                    'home win': {'5.21': 'parimatch'},
                    'royalty handicap -0.5 maps': {'2.35': 'parimatch'}},
 'bmth - spassion': {'1-st map: away win': {'1.95': 'parimatch'},
                     '1-st map: handicap bmth +2.5': {'1.73': 'parimatch'},
                     '1-st map: handicap bmth +3.5': {'1.55': 'parimatch'},
                     '1-st map: handicap bmth -2.5': {'2.30': 'parimatch'},
                     '1-st map: handicap spassion +2.5': {'1.58': 'parimatch'},
                     '1-st map: handicap spassion -2.5': {'2.03': 'parimatch'},
                     '1-st map: handicap spassion -3.5': {'2.35': 'parimatch'},
                     '1-st map: home win': {'1.80': 'parimatch'},
                     '1-st map: total over 25.5': {'1.57': 'parimatch'},
                     '1-st map: total over 26.5': {'1.87': 'parimatch'},
                     '1-st map: total over 27.5': {'2.35': 'parimatch'},
                     '1-st map: total under 25.5': {'2.31': 'parimatch'},
                     '1-st map: total under 26.5': {'1.87': 'parimatch'},
                     '1-st map: total under 27.5': {'1.55': 'parimatch'},
                     'away win': {'3.53': 'parimatch'},
                     'bmth handicap +0.5 maps': {'1.31': 'parimatch'},
                     'draw': {'1.90': 'parimatch'},
                     'home win': {'3.25': 'parimatch'},
                     'spassion handicap -0.5 maps': {'3.25': 'parimatch'}},
 'bmth - unknown gods': {'1-st map: away win': {'1.95': 'parimatch'},
                         '1-st map: handicap bmth +2.5': {'1.73': 'parimatch'},
                         '1-st map: handicap bmth +3.5': {'1.55': 'parimatch'},
                         '1-st map: handicap bmth -2.5': {'2.30': 'parimatch'},
                         '1-st map: handicap unknown gods +2.5': {'1.58': 'parimatch'},
                         '1-st map: handicap unknown gods -2.5': {'2.03': 'parimatch'},
                         '1-st map: handicap unknown gods -3.5': {'2.35': 'parimatch'},
                         '1-st map: home win': {'1.80': 'parimatch'},
                         '1-st map: total over 25.5': {'1.57': 'parimatch'},
                         '1-st map: total over 26.5': {'1.87': 'parimatch'},
                         '1-st map: total over 27.5': {'2.37': 'parimatch'},
                         '1-st map: total under 25.5': {'2.31': 'parimatch'},
                         '1-st map: total under 26.5': {'1.87': 'parimatch'},
                         '1-st map: total under 27.5': {'1.54': 'parimatch'},
                         'away win': {'3.53': 'parimatch'},
                         'bmth handicap +0.5 maps': {'1.31': 'parimatch'},
                         'draw': {'1.90': 'parimatch'},
                         'home win': {'3.25': 'parimatch'},
                         'unknown gods handicap -0.5 maps': {'3.25': 'parimatch'}},
 'bravos - sws': {'win of the 1st': {'1.40': 'parimatch'},
                  'win of the 2nd': {'2.82': 'parimatch'}},
 'brute - tikitakan': {'1-st map: handicap brute +2.5': {'1.75': 'parimatch'},
                       '1-st map: handicap tikitakan -2.5': {'2.01': 'parimatch'},
                       '1-st map: total over 26.5': {'1.77': 'parimatch'},
                       '1-st map: total under 26.5': {'1.97': 'parimatch'},
                       '1-st map: win of the 1st': {'1.77': 'parimatch'},
                       '1-st map: win of the 2nd': {'1.97': 'parimatch'},
                       'brute handicap +1.5 maps': {'1.33': 'parimatch'},
                       'tikitakan handicap -1.5 maps': {'3.15': 'parimatch'},
                       'total over 2.5': {'1.92': 'parimatch'},
                       'total under 2.5': {'1.82': 'parimatch'},
                       'win of the 1st': {'1.70': 'parimatch'},
                       'win of the 2nd': {'2.08': 'parimatch'}},
 'chiefs - twa': {'1-st map: handicap chiefs -3.5': {'1.55': 'parimatch'},
                  '1-st map: handicap chiefs -4.5': {'1.75': 'parimatch'},
                  '1-st map: handicap chiefs -5.5': {'2.00': 'parimatch'},
                  '1-st map: handicap twa +3.5': {'2.35': 'parimatch'},
                  '1-st map: handicap twa +4.5': {'2.01': 'parimatch'},
                  '1-st map: handicap twa +5.5': {'1.76': 'parimatch'},
                  '1-st map: total over 25.5': {'1.80': 'parimatch'},
                  '1-st map: total over 26.5': {'2.08': 'parimatch'},
                  '1-st map: total over 27.5': {'2.65': 'parimatch'},
                  '1-st map: total under 25.5': {'1.95': 'parimatch'},
                  '1-st map: total under 26.5': {'1.70': 'parimatch'},
                  '1-st map: total under 27.5': {'1.44': 'parimatch'},
                  '1-st map: win of the 1st': {'3.75': 'parimatch'},
                  '1-st map: win of the 2nd': {'1.25': 'parimatch'},
                  'chiefs handicap -1.5 maps': {'1.55': 'parimatch'},
                  'total over 2.5': {'2.55': 'parimatch'},
                  'total under 2.5': {'1.47': 'parimatch'},
                  'twa handicap +1.5 maps': {'2.35': 'parimatch'},
                  'win of the 1st': {'5.00': 'parimatch'},
                  'win of the 2nd': {'1.15': 'parimatch'}},
 'cr4zy - nemiga': {'1-st map: handicap cr4zy +3.5': {'2.35': 'parimatch'},
                    '1-st map: handicap cr4zy +4.5': {'2.01': 'parimatch'},
                    '1-st map: handicap cr4zy +5.5': {'1.76': 'parimatch'},
                    '1-st map: handicap nemiga -3.5': {'1.55': 'parimatch'},
                    '1-st map: handicap nemiga -4.5': {'1.75': 'parimatch'},
                    '1-st map: handicap nemiga -5.5': {'2.00': 'parimatch'},
                    '1-st map: total over 25.5': {'1.80': 'parimatch'},
                    '1-st map: total over 26.5': {'2.08': 'parimatch'},
                    '1-st map: total over 27.5': {'2.65': 'parimatch'},
                    '1-st map: total under 25.5': {'1.95': 'parimatch'},
                    '1-st map: total under 26.5': {'1.70': 'parimatch'},
                    '1-st map: total under 27.5': {'1.44': 'parimatch'},
                    '1-st map: win of the 1st': {'3.75': 'parimatch'},
                    '1-st map: win of the 2nd': {'1.25': 'parimatch'},
                    'cr4zy handicap +1.5 maps': {'2.35': 'parimatch'},
                    'nemiga handicap -1.5 maps': {'1.55': 'parimatch'},
                    'total over 2.5': {'2.55': 'parimatch'},
                    'total under 2.5': {'1.47': 'parimatch'},
                    'win of the 1st': {'5.00': 'parimatch'},
                    'win of the 2nd': {'1.15': 'parimatch'}},
 'cream real betis latam - neverest': {'win of the 1st': {'1.50': 'parimatch'},
                                       'win of the 2nd': {'2.48': 'parimatch'}},
 'd13 - divine vendetta': {'1-st map: handicap d13 -2.5': {'2.00': 'parimatch'},
                           '1-st map: handicap divine vendetta +2.5': {'1.76': 'parimatch'},
                           '1-st map: total over 26.5': {'1.77': 'parimatch'},
                           '1-st map: total under 26.5': {'1.97': 'parimatch'},
                           '1-st map: win of the 1st': {'1.75': 'parimatch'},
                           '1-st map: win of the 2nd': {'2.01': 'parimatch'},
                           'd13 handicap -1.5 maps': {'3.05': 'parimatch'},
                           'divine vendetta handicap +1.5 maps': {'1.35': 'parimatch'},
                           'total over 2.5': {'1.95': 'parimatch'},
                           'total under 2.5': {'1.80': 'parimatch'},
                           'win of the 1st': {'1.65': 'parimatch'},
                           'win of the 2nd': {'2.15': 'parimatch'}},
 'divine vendetta - vici gaming': {'1-st map: handicap divine vendetta +4.5': {'2.01': 'parimatch'},
                                   '1-st map: handicap vici gaming -4.5': {'1.75': 'parimatch'},
                                   '1-st map: total over 25.5': {'1.80': 'parimatch'},
                                   '1-st map: total under 25.5': {'1.95': 'parimatch'},
                                   '1-st map: win of the 1st': {'1.25': 'parimatch'},
                                   '1-st map: win of the 2nd': {'3.75': 'parimatch'},
                                   'divine vendetta handicap +1.5 maps': {'2.35': 'parimatch'},
                                   'total over 2.5': {'2.55': 'parimatch'},
                                   'total under 2.5': {'1.47': 'parimatch'},
                                   'vici gaming handicap -1.5 maps': {'1.55': 'parimatch'},
                                   'win of the 1st': {'1.15': 'parimatch'},
                                   'win of the 2nd': {'5.00': 'parimatch'}},
 'divizon - planetkey dynamics': {'away win': {'4.00': 'parimatch'},
                                  'draw': {'2.04': 'parimatch'},
                                  'home win': {'2.65': 'parimatch'}},
 'eternal - imperium': {'win of the 1st': {'1.95': 'parimatch'},
                        'win of the 2nd': {'1.80': 'parimatch'}},
 'evil geniuses - liquid': {'1-st map: handicap evil geniuses +2.5': {'1.68': 'parimatch'},
                            '1-st map: handicap evil geniuses +3.5': {'1.50': 'parimatch'},
                            '1-st map: handicap evil geniuses -2.5': {'2.11': 'parimatch'},
                            '1-st map: handicap liquid +2.5': {'1.68': 'parimatch'},
                            '1-st map: handicap liquid -2.5': {'2.11': 'parimatch'},
                            '1-st map: handicap liquid -3.5': {'2.48': 'parimatch'},
                            '1-st map: total over 25.5': {'1.48': 'parimatch'},
                            '1-st map: total over 26.5': {'1.72': 'parimatch'},
                            '1-st map: total over 27.5': {'2.11': 'parimatch'},
                            '1-st map: total under 25.5': {'2.55': 'parimatch'},
                            '1-st map: total under 26.5': {'2.05': 'parimatch'},
                            '1-st map: total under 27.5': {'1.68': 'parimatch'},
                            '1-st map: win of the 1st': {'1.87': 'parimatch'},
                            '1-st map: win of the 2nd': {'1.87': 'parimatch'},
                            'evil geniuses handicap +1.5 maps': {'1.27': 'parimatch'},
                            'liquid handicap -1.5 maps': {'3.55': 'parimatch'},
                            'total over 2.5': {'2.01': 'parimatch'},
                            'total under 2.5': {'1.75': 'parimatch'},
                            'win of the 1st': {'1.87': 'parimatch'},
                            'win of the 2nd': {'1.87': 'parimatch'}},
 'ex-polar ace - oceanus': {'win of the 1st': {'1.30': 'parimatch'},
                            'win of the 2nd': {'3.33': 'parimatch'}},
 'fnatic - godsent': {'1-st map: handicap fnatic -2.5': {'1.80': 'parimatch'},
                      '1-st map: handicap fnatic -3.5': {'2.11': 'parimatch'},
                      '1-st map: handicap fnatic -4.5': {'2.48': 'parimatch'},
                      '1-st map: handicap godsent +2.5': {'1.95': 'parimatch'},
                      '1-st map: handicap godsent +3.5': {'1.68': 'parimatch'},
                      '1-st map: handicap godsent +4.5': {'1.50': 'parimatch'},
                      '1-st map: total over 25.5': {'1.55': 'parimatch'},
                      '1-st map: total over 26.5': {'1.82': 'parimatch'},
                      '1-st map: total over 27.5': {'2.20': 'parimatch'},
                      '1-st map: total under 25.5': {'2.35': 'parimatch'},
                      '1-st map: total under 26.5': {'1.92': 'parimatch'},
                      '1-st map: total under 27.5': {'1.62': 'parimatch'},
                      '1-st map: win of the 1st': {'1.60': 'parimatch'},
                      '1-st map: win of the 2nd': {'2.25': 'parimatch'},
                      'fnatic handicap -1.5 maps': {'2.62': 'parimatch'},
                      'godsent handicap +1.5 maps': {'1.45': 'parimatch'},
                      'total over 2.5': {'2.01': 'parimatch'},
                      'total under 2.5': {'1.75': 'parimatch'},
                      'win of the 1st': {'1.50': 'parimatch'},
                      'win of the 2nd': {'2.48': 'parimatch'}},
 'forze - nordavind': {'1-st map: handicap forze -2.5': {'1.75': 'parimatch'},
                       '1-st map: handicap forze -3.5': {'2.00': 'parimatch'},
                       '1-st map: handicap forze -4.5': {'2.35': 'parimatch'},
                       '1-st map: handicap nordavind +2.5': {'2.01': 'parimatch'},
                       '1-st map: handicap nordavind +3.5': {'1.76': 'parimatch'},
                       '1-st map: handicap nordavind +4.5': {'1.55': 'parimatch'},
                       '1-st map: total over 25.5': {'1.57': 'parimatch'},
                       '1-st map: total over 26.5': {'1.85': 'parimatch'},
                       '1-st map: total over 27.5': {'2.20': 'parimatch'},
                       '1-st map: total under 25.5': {'2.31': 'parimatch'},
                       '1-st map: total under 26.5': {'1.90': 'parimatch'},
                       '1-st map: total under 27.5': {'1.62': 'parimatch'},
                       '1-st map: win of the 1st': {'2.35': 'parimatch'},
                       '1-st map: win of the 2nd': {'1.55': 'parimatch'},
                       'forze handicap -1.5 maps': {'2.42': 'parimatch'},
                       'nordavind handicap +1.5 maps': {'1.52': 'parimatch'},
                       'total over 2.5': {'2.01': 'parimatch'},
                       'total under 2.5': {'1.75': 'parimatch'},
                       'win of the 1st': {'2.62': 'parimatch'},
                       'win of the 2nd': {'1.45': 'parimatch'}},
 'global - knockturnal': {'win of the 1st': {'1.10': 'parimatch'},
                          'win of the 2nd': {'6.23': 'parimatch'}},
 'grazur - lethal divide': {'win of the 1st': {'2.48': 'parimatch'},
                            'win of the 2nd': {'1.50': 'parimatch'}},
 'ground zero - rooster': {'1-st map: handicap ground zero +2.5': {'1.95': 'parimatch'},
                           '1-st map: handicap ground zero +3.5': {'1.68': 'parimatch'},
                           '1-st map: handicap ground zero +4.5': {'1.50': 'parimatch'},
                           '1-st map: handicap rooster -2.5': {'1.80': 'parimatch'},
                           '1-st map: handicap rooster -3.5': {'2.11': 'parimatch'},
                           '1-st map: handicap rooster -4.5': {'2.48': 'parimatch'},
                           '1-st map: total over 25.5': {'1.55': 'parimatch'},
                           '1-st map: total over 26.5': {'1.82': 'parimatch'},
                           '1-st map: total over 27.5': {'2.20': 'parimatch'},
                           '1-st map: total under 25.5': {'2.35': 'parimatch'},
                           '1-st map: total under 26.5': {'1.92': 'parimatch'},
                           '1-st map: total under 27.5': {'1.62': 'parimatch'},
                           '1-st map: win of the 1st': {'2.25': 'parimatch'},
                           '1-st map: win of the 2nd': {'1.60': 'parimatch'},
                           'ground zero handicap +1.5 maps': {'1.45': 'parimatch'},
                           'rooster handicap -1.5 maps': {'2.62': 'parimatch'},
                           'total over 2.5': {'2.01': 'parimatch'},
                           'total under 2.5': {'1.75': 'parimatch'},
                           'win of the 1st': {'2.48': 'parimatch'},
                           'win of the 2nd': {'1.50': 'parimatch'}},
 'hard legion - havu': {'1-st map: handicap hard legion +2.5': {'1.76': 'parimatch'},
                        '1-st map: handicap hard legion +3.5': {'1.58': 'parimatch'},
                        '1-st map: handicap hard legion -2.5': {'2.35': 'parimatch'},
                        '1-st map: handicap havu +2.5': {'1.55': 'parimatch'},
                        '1-st map: handicap havu -2.5': {'2.00': 'parimatch'},
                        '1-st map: handicap havu -3.5': {'2.30': 'parimatch'},
                        '1-st map: total over 25.5': {'1.47': 'parimatch'},
                        '1-st map: total over 26.5': {'1.77': 'parimatch'},
                        '1-st map: total over 27.5': {'2.15': 'parimatch'},
                        '1-st map: total under 25.5': {'2.55': 'parimatch'},
                        '1-st map: total under 26.5': {'1.97': 'parimatch'},
                        '1-st map: total under 27.5': {'1.65': 'parimatch'},
                        '1-st map: win of the 1st': {'1.75': 'parimatch'},
                        '1-st map: win of the 2nd': {'2.01': 'parimatch'},
                        'hard legion handicap +1.5 maps': {'1.35': 'parimatch'},
                        'havu handicap -1.5 maps': {'3.05': 'parimatch'},
                        'total over 2.5': {'1.95': 'parimatch'},
                        'total under 2.5': {'1.80': 'parimatch'},
                        'win of the 1st': {'1.65': 'parimatch'},
                        'win of the 2nd': {'2.15': 'parimatch'}},
 'hellraisers - syman': {'1-st map: handicap hellraisers +2.5': {'1.68': 'parimatch'},
                         '1-st map: handicap hellraisers +3.5': {'1.50': 'parimatch'},
                         '1-st map: handicap hellraisers -2.5': {'2.11': 'parimatch'},
                         '1-st map: handicap syman +2.5': {'1.68': 'parimatch'},
                         '1-st map: handicap syman -2.5': {'2.11': 'parimatch'},
                         '1-st map: handicap syman -3.5': {'2.48': 'parimatch'},
                         '1-st map: total over 25.5': {'1.45': 'parimatch'},
                         '1-st map: total over 26.5': {'1.72': 'parimatch'},
                         '1-st map: total over 27.5': {'2.11': 'parimatch'},
                         '1-st map: total under 25.5': {'2.62': 'parimatch'},
                         '1-st map: total under 26.5': {'2.05': 'parimatch'},
                         '1-st map: total under 27.5': {'1.68': 'parimatch'},
                         'win of the 1st': {'1.87': 'parimatch'},
                         'win of the 2nd': {'1.87': 'parimatch'}},
 'heroic - og': {'1-st map: handicap heroic +2.5': {'1.65': 'parimatch'},
                 '1-st map: handicap heroic -2.5': {'2.08': 'parimatch'},
                 '1-st map: handicap heroic -3.5': {'2.42': 'parimatch'},
                 '1-st map: handicap og +2.5': {'1.70': 'parimatch'},
                 '1-st map: handicap og +3.5': {'1.52': 'parimatch'},
                 '1-st map: handicap og -2.5': {'2.15': 'parimatch'},
                 '1-st map: total over 25.5': {'1.45': 'parimatch'},
                 '1-st map: total over 26.5': {'1.72': 'parimatch'},
                 '1-st map: total over 27.5': {'2.12': 'parimatch'},
                 '1-st map: total under 25.5': {'2.62': 'parimatch'},
                 '1-st map: total under 26.5': {'2.05': 'parimatch'},
                 '1-st map: total under 27.5': {'1.67': 'parimatch'},
                 '1-st map: win of the 1st': {'1.85': 'parimatch'},
                 '1-st map: win of the 2nd': {'1.90': 'parimatch'},
                 'heroic handicap -1.5 maps': {'3.45': 'parimatch'},
                 'og handicap +1.5 maps': {'1.28': 'parimatch'},
                 'total over 2.5': {'1.87': 'parimatch'},
                 'total under 2.5': {'1.87': 'parimatch'},
                 'win of the 1st': {'1.80': 'parimatch'},
                 'win of the 2nd': {'1.95': 'parimatch'}},
 'hyper - rbg': {'win of the 1st': {'2.82': 'parimatch'},
                 'win of the 2nd': {'1.40': 'parimatch'}},
 'invictus gaming - lucid dream': {'1-st map: handicap invictus gaming -4.5': {'1.90': 'parimatch'},
                                   '1-st map: handicap lucid dream +4.5': {'1.85': 'parimatch'},
                                   '1-st map: total over 26.5': {'2.00': 'parimatch'},
                                   '1-st map: total under 26.5': {'1.76': 'parimatch'},
                                   '1-st map: win of the 1st': {'3.30': 'parimatch'},
                                   '1-st map: win of the 2nd': {'1.30': 'parimatch'},
                                   'invictus gaming handicap -1.5 maps': {'1.77': 'parimatch'},
                                   'lucid dream handicap +1.5 maps': {'2.05': 'parimatch'},
                                   'total over 2.5': {'2.42': 'parimatch'},
                                   'total under 2.5': {'1.52': 'parimatch'},
                                   'win of the 1st': {'4.20': 'parimatch'},
                                   'win of the 2nd': {'1.20': 'parimatch'}},
 'invictus gaming - mazaalai': {'1-st map: handicap invictus gaming -4.5': {'1.90': 'parimatch'},
                                '1-st map: handicap mazaalai +4.5': {'1.85': 'parimatch'},
                                '1-st map: total over 26.5': {'2.00': 'parimatch'},
                                '1-st map: total under 26.5': {'1.76': 'parimatch'},
                                '1-st map: win of the 1st': {'3.30': 'parimatch'},
                                '1-st map: win of the 2nd': {'1.30': 'parimatch'},
                                'invictus gaming handicap -1.5 maps': {'1.70': 'parimatch'},
                                'mazaalai handicap +1.5 maps': {'2.08': 'parimatch'},
                                'total over 2.5': {'2.42': 'parimatch'},
                                'total under 2.5': {'1.52': 'parimatch'},
                                'win of the 1st': {'4.20': 'parimatch'},
                                'win of the 2nd': {'1.20': 'parimatch'}},
 'kova - veto': {'win of the 1st': {'1.30': 'parimatch'},
                 'win of the 2nd': {'3.33': 'parimatch'}},
 'lucid dream - tiger': {'1-st map: handicap lucid dream +3.5': {'1.87': 'parimatch'},
                         '1-st map: handicap tiger -3.5': {'1.87': 'parimatch'},
                         '1-st map: total over 26.5': {'1.90': 'parimatch'},
                         '1-st map: total under 26.5': {'1.85': 'parimatch'},
                         '1-st map: win of the 1st': {'1.45': 'parimatch'},
                         '1-st map: win of the 2nd': {'2.62': 'parimatch'},
                         'lucid dream handicap +1.5 maps': {'1.68': 'parimatch'},
                         'tiger handicap -1.5 maps': {'2.11': 'parimatch'},
                         'total over 2.5': {'2.20': 'parimatch'},
                         'total under 2.5': {'1.62': 'parimatch'},
                         'win of the 1st': {'1.35': 'parimatch'},
                         'win of the 2nd': {'3.05': 'parimatch'}},
 'mazaalai - tyloo': {'1-st map: handicap mazaalai +5.5': {'1.95': 'parimatch'},
                      '1-st map: handicap tyloo -5.5': {'1.80': 'parimatch'},
                      '1-st map: total over 25.5': {'1.90': 'parimatch'},
                      '1-st map: total under 25.5': {'1.85': 'parimatch'},
                      '1-st map: win of the 1st': {'1.20': 'parimatch'},
                      '1-st map: win of the 2nd': {'4.20': 'parimatch'},
                      'mazaalai handicap +1.5 maps': {'2.62': 'parimatch'},
                      'total over 2.5': {'2.95': 'parimatch'},
                      'total under 2.5': {'1.37': 'parimatch'},
                      'tyloo handicap -1.5 maps': {'1.44': 'parimatch'},
                      'win of the 1st': {'1.10': 'parimatch'},
                      'win of the 2nd': {'6.25': 'parimatch'}},
 'mistaken - zigma': {'win of the 1st': {'5.00': 'parimatch'},
                      'win of the 2nd': {'1.15': 'parimatch'}},
 'purple haze - rembaza': {'1-st map: away win': {'1.75': 'parimatch'},
                           '1-st map: handicap purple haze +2.5': {'1.55': 'parimatch'},
                           '1-st map: handicap purple haze -2.5': {'2.00': 'parimatch'},
                           '1-st map: handicap purple haze -3.5': {'2.30': 'parimatch'},
                           '1-st map: handicap rembaza +2.5': {'1.76': 'parimatch'},
                           '1-st map: handicap rembaza +3.5': {'1.58': 'parimatch'},
                           '1-st map: handicap rembaza -2.5': {'2.35': 'parimatch'},
                           '1-st map: home win': {'2.01': 'parimatch'},
                           '1-st map: total over 25.5': {'1.47': 'parimatch'},
                           '1-st map: total over 26.5': {'1.77': 'parimatch'},
                           '1-st map: total over 27.5': {'2.15': 'parimatch'},
                           '1-st map: total under 25.5': {'2.55': 'parimatch'},
                           '1-st map: total under 26.5': {'1.97': 'parimatch'},
                           '1-st map: total under 27.5': {'1.65': 'parimatch'},
                           'away win': {'3.00': 'parimatch'},
                           'draw': {'1.90': 'parimatch'},
                           'home win': {'3.88': 'parimatch'},
                           'purple haze handicap -0.5 maps': {'3.00': 'parimatch'},
                           'rembaza handicap +0.5 maps': {'1.36': 'parimatch'}},
 'purple haze - veterani': {'1-st map: away win': {'1.55': 'parimatch'},
                            '1-st map: handicap purple haze -2.5': {'1.75': 'parimatch'},
                            '1-st map: handicap purple haze -3.5': {'2.00': 'parimatch'},
                            '1-st map: handicap purple haze -4.5': {'2.35': 'parimatch'},
                            '1-st map: handicap veterani +2.5': {'2.01': 'parimatch'},
                            '1-st map: handicap veterani +3.5': {'1.76': 'parimatch'},
                            '1-st map: handicap veterani +4.5': {'1.55': 'parimatch'},
                            '1-st map: home win': {'2.35': 'parimatch'},
                            '1-st map: total over 25.5': {'1.50': 'parimatch'},
                            '1-st map: total over 26.5': {'1.72': 'parimatch'},
                            '1-st map: total over 27.5': {'2.15': 'parimatch'},
                            '1-st map: total under 25.5': {'2.48': 'parimatch'},
                            '1-st map: total under 26.5': {'2.05': 'parimatch'},
                            '1-st map: total under 27.5': {'1.65': 'parimatch'},
                            'away win': {'2.40': 'parimatch'},
                            'draw': {'2.00': 'parimatch'},
                            'home win': {'4.98': 'parimatch'},
                            'purple haze handicap -0.5 maps': {'2.40': 'parimatch'},
                            'veterani handicap +0.5 maps': {'1.53': 'parimatch'}},
 'purple haze - wesq': {'1-st map: away win': {'1.30': 'parimatch'},
                        '1-st map: handicap purple haze -3.5': {'1.68': 'parimatch'},
                        '1-st map: handicap purple haze -4.5': {'1.90': 'parimatch'},
                        '1-st map: handicap purple haze -5.5': {'2.20': 'parimatch'},
                        '1-st map: handicap wesq +3.5': {'2.11': 'parimatch'},
                        '1-st map: handicap wesq +4.5': {'1.85': 'parimatch'},
                        '1-st map: handicap wesq +5.5': {'1.62': 'parimatch'},
                        '1-st map: home win': {'3.30': 'parimatch'},
                        '1-st map: total over 25.5': {'1.75': 'parimatch'},
                        '1-st map: total over 26.5': {'2.00': 'parimatch'},
                        '1-st map: total over 27.5': {'2.55': 'parimatch'},
                        '1-st map: total under 25.5': {'2.01': 'parimatch'},
                        '1-st map: total under 26.5': {'1.76': 'parimatch'},
                        '1-st map: total under 27.5': {'1.47': 'parimatch'},
                        'away win': {'1.57': 'parimatch'},
                        'draw': {'2.66': 'parimatch'},
                        'home win': {'9.58': 'parimatch'},
                        'purple haze handicap -0.5 maps': {'1.57': 'parimatch'},
                        'wesq handicap +0.5 maps': {'2.31': 'parimatch'}},
 'reckoning - wolf': {'win of the 1st': {'1.42': 'parimatch'},
                      'win of the 2nd': {'2.74': 'parimatch'}},
 'rembaza - veterani': {'1-st map: away win': {'2.25': 'parimatch'},
                        '1-st map: handicap rembaza -2.5': {'1.80': 'parimatch'},
                        '1-st map: handicap rembaza -3.5': {'2.11': 'parimatch'},
                        '1-st map: handicap rembaza -4.5': {'2.48': 'parimatch'},
                        '1-st map: handicap veterani +2.5': {'1.95': 'parimatch'},
                        '1-st map: handicap veterani +3.5': {'1.68': 'parimatch'},
                        '1-st map: handicap veterani +4.5': {'1.50': 'parimatch'},
                        '1-st map: home win': {'1.60': 'parimatch'},
                        '1-st map: total over 25.5': {'1.50': 'parimatch'},
                        '1-st map: total over 26.5': {'1.72': 'parimatch'},
                        '1-st map: total over 27.5': {'2.15': 'parimatch'},
                        '1-st map: total under 25.5': {'2.48': 'parimatch'},
                        '1-st map: total under 26.5': {'2.05': 'parimatch'},
                        '1-st map: total under 27.5': {'1.65': 'parimatch'},
                        'away win': {'4.89': 'parimatch'},
                        'draw': {'1.95': 'parimatch'},
                        'home win': {'2.50': 'parimatch'},
                        'rembaza handicap -0.5 maps': {'2.50': 'parimatch'},
                        'veterani handicap +0.5 maps': {'1.49': 'parimatch'}},
 'rembaza - wesq': {'1-st map: away win': {'3.75': 'parimatch'},
                    '1-st map: handicap rembaza -3.5': {'1.55': 'parimatch'},
                    '1-st map: handicap rembaza -4.5': {'1.75': 'parimatch'},
                    '1-st map: handicap rembaza -5.5': {'2.00': 'parimatch'},
                    '1-st map: handicap wesq +3.5': {'2.35': 'parimatch'},
                    '1-st map: handicap wesq +4.5': {'2.01': 'parimatch'},
                    '1-st map: handicap wesq +5.5': {'1.76': 'parimatch'},
                    '1-st map: home win': {'1.25': 'parimatch'},
                    '1-st map: total over 25.5': {'1.80': 'parimatch'},
                    '1-st map: total over 26.5': {'2.08': 'parimatch'},
                    '1-st map: total over 27.5': {'2.65': 'parimatch'},
                    '1-st map: total under 25.5': {'1.95': 'parimatch'},
                    '1-st map: total under 26.5': {'1.70': 'parimatch'},
                    '1-st map: total under 27.5': {'1.44': 'parimatch'},
                    'away win': {'13.6': 'parimatch'},
                    'draw': {'2.65': 'parimatch'},
                    'home win': {'1.50': 'parimatch'},
                    'rembaza handicap -0.5 maps': {'1.50': 'parimatch'},
                    'wesq handicap +0.5 maps': {'2.48': 'parimatch'}},
 'royalty - spassion': {'1-st map: away win': {'2.25': 'parimatch'},
                        '1-st map: handicap royalty -2.5': {'1.80': 'parimatch'},
                        '1-st map: handicap royalty -3.5': {'2.11': 'parimatch'},
                        '1-st map: handicap royalty -4.5': {'2.48': 'parimatch'},
                        '1-st map: handicap spassion +2.5': {'1.95': 'parimatch'},
                        '1-st map: handicap spassion +3.5': {'1.68': 'parimatch'},
                        '1-st map: handicap spassion +4.5': {'1.50': 'parimatch'},
                        '1-st map: home win': {'1.60': 'parimatch'},
                        '1-st map: total over 25.5': {'1.57': 'parimatch'},
                        '1-st map: total over 26.5': {'1.87': 'parimatch'},
                        '1-st map: total over 27.5': {'2.37': 'parimatch'},
                        '1-st map: total under 25.5': {'2.31': 'parimatch'},
                        '1-st map: total under 26.5': {'1.87': 'parimatch'},
                        '1-st map: total under 27.5': {'1.54': 'parimatch'},
                        'away win': {'4.89': 'parimatch'},
                        'draw': {'1.95': 'parimatch'},
                        'home win': {'2.50': 'parimatch'},
                        'royalty handicap -0.5 maps': {'2.50': 'parimatch'},
                        'spassion handicap +0.5 maps': {'1.49': 'parimatch'}},
 'royalty - unknown gods': {'1-st map: away win': {'2.25': 'parimatch'},
                            '1-st map: handicap royalty -2.5': {'1.80': 'parimatch'},
                            '1-st map: handicap royalty -3.5': {'2.11': 'parimatch'},
                            '1-st map: handicap royalty -4.5': {'2.48': 'parimatch'},
                            '1-st map: handicap unknown gods +2.5': {'1.95': 'parimatch'},
                            '1-st map: handicap unknown gods +3.5': {'1.68': 'parimatch'},
                            '1-st map: handicap unknown gods +4.5': {'1.50': 'parimatch'},
                            '1-st map: home win': {'1.60': 'parimatch'},
                            '1-st map: total over 25.5': {'1.57': 'parimatch'},
                            '1-st map: total over 26.5': {'1.87': 'parimatch'},
                            '1-st map: total over 27.5': {'2.35': 'parimatch'},
                            '1-st map: total under 25.5': {'2.31': 'parimatch'},
                            '1-st map: total under 26.5': {'1.87': 'parimatch'},
                            '1-st map: total under 27.5': {'1.55': 'parimatch'},
                            'away win': {'4.89': 'parimatch'},
                            'draw': {'1.95': 'parimatch'},
                            'home win': {'2.50': 'parimatch'},
                            'royalty handicap -0.5 maps': {'2.50': 'parimatch'},
                            'unknown gods handicap +0.5 maps': {'1.49': 'parimatch'}},
 'spassion - unknown gods': {'1-st map: away win': {'1.87': 'parimatch'},
                             '1-st map: handicap spassion +2.5': {'1.68': 'parimatch'},
                             '1-st map: handicap spassion -2.5': {'2.11': 'parimatch'},
                             '1-st map: handicap spassion -3.5': {'2.48': 'parimatch'},
                             '1-st map: handicap unknown gods +2.5': {'1.68': 'parimatch'},
                             '1-st map: handicap unknown gods +3.5': {'1.50': 'parimatch'},
                             '1-st map: handicap unknown gods -2.5': {'2.11': 'parimatch'},
                             '1-st map: home win': {'1.87': 'parimatch'},
                             '1-st map: total over 25.5': {'1.57': 'parimatch'},
                             '1-st map: total over 26.5': {'1.87': 'parimatch'},
                             '1-st map: total over 27.5': {'2.35': 'parimatch'},
                             '1-st map: total under 25.5': {'2.31': 'parimatch'},
                             '1-st map: total under 26.5': {'1.87': 'parimatch'},
                             '1-st map: total under 27.5': {'1.55': 'parimatch'},
                             'away win': {'3.43': 'parimatch'},
                             'draw': {'1.87': 'parimatch'},
                             'home win': {'3.44': 'parimatch'},
                             'spassion handicap +0.5 maps': {'1.28': 'parimatch'},
                             'unknown gods handicap -0.5 maps': {'3.44': 'parimatch'}},
 'third impact - valkyrie': {'win of the 1st': {'1.30': 'parimatch'},
                             'win of the 2nd': {'3.33': 'parimatch'}},
 'veterani - wesq': {'1-st map: away win': {'1.35': 'parimatch'},
                     '1-st map: handicap veterani -3.5': {'1.72': 'parimatch'},
                     '1-st map: handicap veterani -4.5': {'1.97': 'parimatch'},
                     '1-st map: handicap veterani -5.5': {'2.25': 'parimatch'},
                     '1-st map: handicap wesq +3.5': {'2.05': 'parimatch'},
                     '1-st map: handicap wesq +4.5': {'1.77': 'parimatch'},
                     '1-st map: handicap wesq +5.5': {'1.60': 'parimatch'},
                     '1-st map: home win': {'3.05': 'parimatch'},
                     '1-st map: total over 25.5': {'1.70': 'parimatch'},
                     '1-st map: total over 26.5': {'1.95': 'parimatch'},
                     '1-st map: total over 27.5': {'2.48': 'parimatch'},
                     '1-st map: total under 25.5': {'2.08': 'parimatch'},
                     '1-st map: total under 26.5': {'1.80': 'parimatch'},
                     '1-st map: total under 27.5': {'1.50': 'parimatch'},
                     'away win': {'1.72': 'parimatch'},
                     'draw': {'2.40': 'parimatch'},
                     'home win': {'8.39': 'parimatch'},
                     'veterani handicap -0.5 maps': {'1.72': 'parimatch'},
                     'wesq handicap +0.5 maps': {'2.05': 'parimatch'}}}
