sport = {'football': {'spal - udinese(favorit - https://www.favorit.com.ua/en/bets/#event=27058297&tours=17337,17282,17635)': {'1-st half asian total over 0.75': '1.62',
                                                                                                                       '1-st half asian total over 1.25': '1.86',
                                                                                                                       '1-st half asian total over 1.75': '2.69',
                                                                                                                       '1-st half asian total over 2.25': '1.84',
                                                                                                                       '1-st half asian total over 2.75': '2.44',
                                                                                                                       '1-st half asian total over 3.25': '3.30',
                                                                                                                       '1-st half asian total under 0.75': '2.22',
                                                                                                                       '1-st half asian total under 1.25': '1.88',
                                                                                                                       '1-st half asian total under 1.75': '1.43',
                                                                                                                       '1-st half asian total under 2.25': '1.97',
                                                                                                                       '1-st half asian total under 2.75': '1.56',
                                                                                                                       '1-st half asian total under 3.25': '1.34',
                                                                                                                       '1-st half boths to score no': '1.28',
                                                                                                                       '1-st half boths to score yes': '3.45',
                                                                                                                       '1-st half corners result draw': '5.40',
                                                                                                                       '1-st half draw will win': '2.51',
                                                                                                                       '1-st half first to score no goal': '3.55',
                                                                                                                       '1-st half half with most goals 3-way': '3.30',
                                                                                                                       '1-st half last to score no goal': '3.55',
                                                                                                                       '1-st half number of goals 5+ 1': '2.25',
                                                                                                                       '1-st half number of goals 5+ 2': '3.10',
                                                                                                                       '1-st half number of goals 5+ 3': '6.60',
                                                                                                                       '1-st half number of goals 5+ 4': '18.50',
                                                                                                                       '1-st half number of goals 5+ 5+': '50.00',
                                                                                                                       '1-st half number of goals 5+ no goal': '3.55',
                                                                                                                       '1-st half over 0.5 and 2nd half over 0.5 no': '1.86',
                                                                                                                       '1-st half over 0.5 and 2nd half over 0.5 yes': '1.88',
                                                                                                                       '1-st half over 1.5 and 2nd half over 1.5 no': '1.10',
                                                                                                                       '1-st half over 1.5 and 2nd half over 1.5 yes': '6.30',
                                                                                                                       '1-st half spal asian handicap +0.25': '1.87',
                                                                                                                       '1-st half spal asian handicap +0.75': '1.37',
                                                                                                                       '1-st half spal asian handicap -0.25': '3.35',
                                                                                                                       '1-st half spal corners handicap +1.0': '1.51',
                                                                                                                       '1-st half spal corners handicap +1.5': '1.63',
                                                                                                                       '1-st half spal corners result': '2.71',
                                                                                                                       '1-st half spal first to score': '3.20',
                                                                                                                       '1-st half spal half with most goals': '4.10',
                                                                                                                       '1-st half spal handicap +0.5': '1.58',
                                                                                                                       '1-st half spal handicap +1.0': '1.16',
                                                                                                                       '1-st half spal handicap +1.5': '1.10',
                                                                                                                       '1-st half spal handicap +2.0': '1.10',
                                                                                                                       '1-st half spal handicap +2.5': '1.08',
                                                                                                                       '1-st half spal handicap -0.5': '4.20',
                                                                                                                       '1-st half spal handicap -1.0': '11.00',
                                                                                                                       '1-st half spal handicap -1.5': '13.00',
                                                                                                                       '1-st half spal handicap 0.0': '2.65',
                                                                                                                       '1-st half spal last to score': '3.20',
                                                                                                                       '1-st half spal number of goals 0': '1.63',
                                                                                                                       '1-st half spal number of goals 1': '2.41',
                                                                                                                       '1-st half spal number of goals 2': '8.60',
                                                                                                                       '1-st half spal number of goals 3': '46.00',
                                                                                                                       '1-st half spal number of goals 4': '100',
                                                                                                                       '1-st half spal number of goals 5+': '100',
                                                                                                                       '1-st half spal total over 0.5': '2.19',
                                                                                                                       '1-st half spal total over 1.0': '5.80',
                                                                                                                       '1-st half spal total over 1.5': '8.60',
                                                                                                                       '1-st half spal total over 2.0': '9.80',
                                                                                                                       '1-st half spal total over 2.5': '12.00',
                                                                                                                       '1-st half spal total under 0.5': '1.63',
                                                                                                                       '1-st half spal total under 1.0': '1.11',
                                                                                                                       '1-st half spal total under 1.5': '1.05',
                                                                                                                       '1-st half spal total under 2.0': '1.05',
                                                                                                                       '1-st half spal total under 2.5': '1.03',
                                                                                                                       '1-st half spal will win': '4.20',
                                                                                                                       '1-st half spal yellow cards handicap +1.0': '1.32',
                                                                                                                       '1-st half spal yellow cards handicap -1.0': '3.45',
                                                                                                                       '1-st half spal yellow сards result': '2.24',
                                                                                                                       '1-st half total corners over 10.0': '1.52',
                                                                                                                       '1-st half total corners over 10.5': '1.68',
                                                                                                                       '1-st half total corners over 11.0': '1.88',
                                                                                                                       '1-st half total corners over 11.5': '2.14',
                                                                                                                       '1-st half total corners over 12.0': '2.40',
                                                                                                                       '1-st half total corners over 5.0': '1.70',
                                                                                                                       '1-st half total corners over 5.5': '1.76',
                                                                                                                       '1-st half total corners under 10.0': '2.37',
                                                                                                                       '1-st half total corners under 10.5': '2.07',
                                                                                                                       '1-st half total corners under 11.0': '1.82',
                                                                                                                       '1-st half total corners under 11.5': '1.63',
                                                                                                                       '1-st half total corners under 12.0': '1.51',
                                                                                                                       '1-st half total corners under 5.0': '1.95',
                                                                                                                       '1-st half total corners under 5.5': '1.88',
                                                                                                                       '1-st half total even': '1.77',
                                                                                                                       '1-st half total odd': '1.98',
                                                                                                                       '1-st half total over 0.5': '1.25',
                                                                                                                       '1-st half total over 1.0': '1.49',
                                                                                                                       '1-st half total over 1.5': '2.24',
                                                                                                                       '1-st half total over 2.0': '3.75',
                                                                                                                       '1-st half total over 2.5': '4.70',
                                                                                                                       '1-st half total over 3.0': '2.98',
                                                                                                                       '1-st half total over 3.5': '3.60',
                                                                                                                       '1-st half total over 4.0': '6.30',
                                                                                                                       '1-st half total over 4.5': '7.00',
                                                                                                                       '1-st half total over 5.0': '12.00',
                                                                                                                       '1-st half total under 0.5': '3.55',
                                                                                                                       '1-st half total under 1.0': '2.50',
                                                                                                                       '1-st half total under 1.5': '1.60',
                                                                                                                       '1-st half total under 2.0': '1.24',
                                                                                                                       '1-st half total under 2.5': '1.16',
                                                                                                                       '1-st half total under 3.0': '1.40',
                                                                                                                       '1-st half total under 3.5': '1.29',
                                                                                                                       '1-st half total under 4.0': '1.12',
                                                                                                                       '1-st half total under 4.5': '1.10',
                                                                                                                       '1-st half total under 5.0': '1.03',
                                                                                                                       '1-st half total yellow cards over 1.5': '1.67',
                                                                                                                       '1-st half total yellow cards over 3.5': '1.98',
                                                                                                                       '1-st half total yellow cards over 5.0': '1.75',
                                                                                                                       '1-st half total yellow cards over 5.5': '2.12',
                                                                                                                       '1-st half total yellow cards under 1.5': '1.99',
                                                                                                                       '1-st half total yellow cards under 3.5': '1.68',
                                                                                                                       '1-st half total yellow cards under 5.0': '1.96',
                                                                                                                       '1-st half total yellow cards under 5.5': '1.64',
                                                                                                                       '1-st half udinese asian handicap +0.25': '1.29',
                                                                                                                       '1-st half udinese asian handicap -0.25': '1.87',
                                                                                                                       '1-st half udinese asian handicap -0.75': '2.95',
                                                                                                                       '1-st half udinese corners handicap -1.0': '2.24',
                                                                                                                       '1-st half udinese corners handicap -1.5': '2.10',
                                                                                                                       '1-st half udinese corners result': '1.80',
                                                                                                                       '1-st half udinese first to score': '2.08',
                                                                                                                       '1-st half udinese half with most goals': '3.75',
                                                                                                                       '1-st half udinese handicap +0.5': '1.20',
                                                                                                                       '1-st half udinese handicap +1.0': '1.02',
                                                                                                                       '1-st half udinese handicap +1.5': '1.01',
                                                                                                                       '1-st half udinese handicap -0.5': '2.30',
                                                                                                                       '1-st half udinese handicap -1.0': '4.80',
                                                                                                                       '1-st half udinese handicap -1.5': '6.10',
                                                                                                                       '1-st half udinese handicap -2.0': '7.20',
                                                                                                                       '1-st half udinese handicap -2.5': '8.30',
                                                                                                                       '1-st half udinese handicap 0.0': '1.44',
                                                                                                                       '1-st half udinese last to score': '2.08',
                                                                                                                       '1-st half udinese number of goals 0': '2.23',
                                                                                                                       '1-st half udinese number of goals 1': '2.11',
                                                                                                                       '1-st half udinese number of goals 2': '4.85',
                                                                                                                       '1-st half udinese number of goals 3': '16.50',
                                                                                                                       '1-st half udinese number of goals 4': '75.00',
                                                                                                                       '1-st half udinese number of goals 5+': '100',
                                                                                                                       '1-st half udinese total over 0.5': '1.61',
                                                                                                                       '1-st half udinese total over 1.0': '2.75',
                                                                                                                       '1-st half udinese total over 1.5': '4.30',
                                                                                                                       '1-st half udinese total over 2.0': '3.75',
                                                                                                                       '1-st half udinese total over 2.5': '5.00',
                                                                                                                       '1-st half udinese total over 3.0': '12.50',
                                                                                                                       '1-st half udinese total over 3.5': '14.50',
                                                                                                                       '1-st half udinese total under 0.5': '2.23',
                                                                                                                       '1-st half udinese total under 1.0': '1.42',
                                                                                                                       '1-st half udinese total under 1.5': '1.19',
                                                                                                                       '1-st half udinese total under 2.0': '1.27',
                                                                                                                       '1-st half udinese total under 2.5': '1.17',
                                                                                                                       '1-st half udinese total under 3.0': '1.03',
                                                                                                                       '1-st half udinese total under 3.5': '1.02',
                                                                                                                       '1-st half udinese will win': '2.30',
                                                                                                                       '1-st half udinese yellow cards handicap +1.0': '1.22',
                                                                                                                       '1-st half udinese yellow cards handicap -1.0': '3.10',
                                                                                                                       '1-st half udinese yellow сards result': '2.41',
                                                                                                                       '1-st half yellow сards result draw': '4.05',
                                                                                                                       '2-nd half asian total over 0.75': '1.62',
                                                                                                                       '2-nd half asian total over 1.25': '1.86',
                                                                                                                       '2-nd half asian total over 1.75': '2.69',
                                                                                                                       '2-nd half asian total over 2.25': '1.84',
                                                                                                                       '2-nd half asian total over 2.75': '2.44',
                                                                                                                       '2-nd half asian total over 3.25': '3.30',
                                                                                                                       '2-nd half asian total under 0.75': '2.22',
                                                                                                                       '2-nd half asian total under 1.25': '1.88',
                                                                                                                       '2-nd half asian total under 1.75': '1.43',
                                                                                                                       '2-nd half asian total under 2.25': '1.97',
                                                                                                                       '2-nd half asian total under 2.75': '1.56',
                                                                                                                       '2-nd half asian total under 3.25': '1.34',
                                                                                                                       '2-nd half boths to score no': '1.28',
                                                                                                                       '2-nd half boths to score yes': '3.45',
                                                                                                                       '2-nd half corners result draw': '5.40',
                                                                                                                       '2-nd half draw will win': '2.51',
                                                                                                                       '2-nd half first to score no goal': '3.55',
                                                                                                                       '2-nd half half with most goals 3-way': '2.06',
                                                                                                                       '2-nd half last to score no goal': '3.55',
                                                                                                                       '2-nd half number of goals 5+ 1': '2.25',
                                                                                                                       '2-nd half number of goals 5+ 2': '3.10',
                                                                                                                       '2-nd half number of goals 5+ 3': '6.60',
                                                                                                                       '2-nd half number of goals 5+ 4': '18.50',
                                                                                                                       '2-nd half number of goals 5+ 5+': '50.00',
                                                                                                                       '2-nd half number of goals 5+ no goal': '3.55',
                                                                                                                       '2-nd half spal asian handicap +0.25': '1.87',
                                                                                                                       '2-nd half spal asian handicap +0.75': '1.37',
                                                                                                                       '2-nd half spal asian handicap -0.25': '3.35',
                                                                                                                       '2-nd half spal corners handicap +1.0': '1.51',
                                                                                                                       '2-nd half spal corners handicap +1.5': '1.63',
                                                                                                                       '2-nd half spal corners result': '2.71',
                                                                                                                       '2-nd half spal first to score': '3.20',
                                                                                                                       '2-nd half spal half with most goals': '3.00',
                                                                                                                       '2-nd half spal handicap +0.5': '1.58',
                                                                                                                       '2-nd half spal handicap +1.0': '1.16',
                                                                                                                       '2-nd half spal handicap +1.5': '1.10',
                                                                                                                       '2-nd half spal handicap +2.0': '1.10',
                                                                                                                       '2-nd half spal handicap +2.5': '1.08',
                                                                                                                       '2-nd half spal handicap -0.5': '4.20',
                                                                                                                       '2-nd half spal handicap -1.0': '11.00',
                                                                                                                       '2-nd half spal handicap -1.5': '13.00',
                                                                                                                       '2-nd half spal handicap 0.0': '2.65',
                                                                                                                       '2-nd half spal last to score': '3.20',
                                                                                                                       '2-nd half spal number of goals 0': '1.63',
                                                                                                                       '2-nd half spal number of goals 1': '2.41',
                                                                                                                       '2-nd half spal number of goals 2': '8.60',
                                                                                                                       '2-nd half spal number of goals 3': '46.00',
                                                                                                                       '2-nd half spal number of goals 4': '100',
                                                                                                                       '2-nd half spal number of goals 5+': '100',
                                                                                                                       '2-nd half spal total over 0.5': '2.19',
                                                                                                                       '2-nd half spal total over 1.0': '5.80',
                                                                                                                       '2-nd half spal total over 1.5': '8.60',
                                                                                                                       '2-nd half spal total over 2.0': '9.80',
                                                                                                                       '2-nd half spal total over 2.5': '12.00',
                                                                                                                       '2-nd half spal total under 0.5': '1.63',
                                                                                                                       '2-nd half spal total under 1.0': '1.11',
                                                                                                                       '2-nd half spal total under 1.5': '1.05',
                                                                                                                       '2-nd half spal total under 2.0': '1.05',
                                                                                                                       '2-nd half spal total under 2.5': '1.03',
                                                                                                                       '2-nd half spal will win': '4.20',
                                                                                                                       '2-nd half spal yellow cards handicap +1.0': '1.32',
                                                                                                                       '2-nd half spal yellow cards handicap -1.0': '3.45',
                                                                                                                       '2-nd half spal yellow сards result': '2.24',
                                                                                                                       '2-nd half total corners over 10.0': '1.52',
                                                                                                                       '2-nd half total corners over 10.5': '1.68',
                                                                                                                       '2-nd half total corners over 11.0': '1.88',
                                                                                                                       '2-nd half total corners over 11.5': '2.14',
                                                                                                                       '2-nd half total corners over 12.0': '2.40',
                                                                                                                       '2-nd half total corners over 5.0': '1.70',
                                                                                                                       '2-nd half total corners over 5.5': '1.76',
                                                                                                                       '2-nd half total corners under 10.0': '2.37',
                                                                                                                       '2-nd half total corners under 10.5': '2.07',
                                                                                                                       '2-nd half total corners under 11.0': '1.82',
                                                                                                                       '2-nd half total corners under 11.5': '1.63',
                                                                                                                       '2-nd half total corners under 12.0': '1.51',
                                                                                                                       '2-nd half total corners under 5.0': '1.95',
                                                                                                                       '2-nd half total corners under 5.5': '1.88',
                                                                                                                       '2-nd half total even': '1.77',
                                                                                                                       '2-nd half total odd': '1.98',
                                                                                                                       '2-nd half total over 0.5': '1.25',
                                                                                                                       '2-nd half total over 1.0': '1.49',
                                                                                                                       '2-nd half total over 1.5': '2.24',
                                                                                                                       '2-nd half total over 2.0': '3.75',
                                                                                                                       '2-nd half total over 2.5': '4.70',
                                                                                                                       '2-nd half total over 3.0': '2.98',
                                                                                                                       '2-nd half total over 3.5': '3.60',
                                                                                                                       '2-nd half total over 4.0': '6.30',
                                                                                                                       '2-nd half total over 4.5': '7.00',
                                                                                                                       '2-nd half total over 5.0': '12.00',
                                                                                                                       '2-nd half total under 0.5': '3.55',
                                                                                                                       '2-nd half total under 1.0': '2.50',
                                                                                                                       '2-nd half total under 1.5': '1.60',
                                                                                                                       '2-nd half total under 2.0': '1.24',
                                                                                                                       '2-nd half total under 2.5': '1.16',
                                                                                                                       '2-nd half total under 3.0': '1.40',
                                                                                                                       '2-nd half total under 3.5': '1.29',
                                                                                                                       '2-nd half total under 4.0': '1.12',
                                                                                                                       '2-nd half total under 4.5': '1.10',
                                                                                                                       '2-nd half total under 5.0': '1.03',
                                                                                                                       '2-nd half total yellow cards over 1.5': '1.67',
                                                                                                                       '2-nd half total yellow cards over 3.5': '1.98',
                                                                                                                       '2-nd half total yellow cards over 5.0': '1.75',
                                                                                                                       '2-nd half total yellow cards over 5.5': '2.12',
                                                                                                                       '2-nd half total yellow cards under 1.5': '1.99',
                                                                                                                       '2-nd half total yellow cards under 3.5': '1.68',
                                                                                                                       '2-nd half total yellow cards under 5.0': '1.96',
                                                                                                                       '2-nd half total yellow cards under 5.5': '1.64',
                                                                                                                       '2-nd half udinese asian handicap +0.25': '1.29',
                                                                                                                       '2-nd half udinese asian handicap -0.25': '1.87',
                                                                                                                       '2-nd half udinese asian handicap -0.75': '2.95',
                                                                                                                       '2-nd half udinese corners handicap -1.0': '2.24',
                                                                                                                       '2-nd half udinese corners handicap -1.5': '2.10',
                                                                                                                       '2-nd half udinese corners result': '1.80',
                                                                                                                       '2-nd half udinese first to score': '2.08',
                                                                                                                       '2-nd half udinese half with most goals': '2.40',
                                                                                                                       '2-nd half udinese handicap +0.5': '1.20',
                                                                                                                       '2-nd half udinese handicap +1.0': '1.02',
                                                                                                                       '2-nd half udinese handicap +1.5': '1.01',
                                                                                                                       '2-nd half udinese handicap -0.5': '2.30',
                                                                                                                       '2-nd half udinese handicap -1.0': '4.80',
                                                                                                                       '2-nd half udinese handicap -1.5': '6.10',
                                                                                                                       '2-nd half udinese handicap -2.0': '7.20',
                                                                                                                       '2-nd half udinese handicap -2.5': '8.30',
                                                                                                                       '2-nd half udinese handicap 0.0': '1.44',
                                                                                                                       '2-nd half udinese last to score': '2.08',
                                                                                                                       '2-nd half udinese number of goals 0': '2.23',
                                                                                                                       '2-nd half udinese number of goals 1': '2.11',
                                                                                                                       '2-nd half udinese number of goals 2': '4.85',
                                                                                                                       '2-nd half udinese number of goals 3': '16.50',
                                                                                                                       '2-nd half udinese number of goals 4': '75.00',
                                                                                                                       '2-nd half udinese number of goals 5+': '100',
                                                                                                                       '2-nd half udinese total over 0.5': '1.61',
                                                                                                                       '2-nd half udinese total over 1.0': '2.75',
                                                                                                                       '2-nd half udinese total over 1.5': '4.30',
                                                                                                                       '2-nd half udinese total over 2.0': '3.75',
                                                                                                                       '2-nd half udinese total over 2.5': '5.00',
                                                                                                                       '2-nd half udinese total over 3.0': '12.50',
                                                                                                                       '2-nd half udinese total over 3.5': '14.50',
                                                                                                                       '2-nd half udinese total under 0.5': '2.23',
                                                                                                                       '2-nd half udinese total under 1.0': '1.42',
                                                                                                                       '2-nd half udinese total under 1.5': '1.19',
                                                                                                                       '2-nd half udinese total under 2.0': '1.27',
                                                                                                                       '2-nd half udinese total under 2.5': '1.17',
                                                                                                                       '2-nd half udinese total under 3.0': '1.03',
                                                                                                                       '2-nd half udinese total under 3.5': '1.02',
                                                                                                                       '2-nd half udinese will win': '2.30',
                                                                                                                       '2-nd half udinese yellow cards handicap +1.0': '1.22',
                                                                                                                       '2-nd half udinese yellow cards handicap -1.0': '3.10',
                                                                                                                       '2-nd half udinese yellow сards result': '2.41',
                                                                                                                       '2-nd half yellow сards result draw': '4.05',
                                                                                                                       'any to win exactly by 1 no 1': '1.46',
                                                                                                                       'any to win exactly by 1 yes 1': '2.36',
                                                                                                                       'any to win exactly by 2 no 2': '1.15',
                                                                                                                       'any to win exactly by 2 yes 2': '4.20',
                                                                                                                       'asian total over 0.75': '1.62',
                                                                                                                       'asian total over 1.25': '1.86',
                                                                                                                       'asian total over 1.75': '2.69',
                                                                                                                       'asian total over 2.25': '1.84',
                                                                                                                       'asian total over 2.75': '2.44',
                                                                                                                       'asian total over 3.25': '3.30',
                                                                                                                       'asian total under 0.75': '2.22',
                                                                                                                       'asian total under 1.25': '1.88',
                                                                                                                       'asian total under 1.75': '1.43',
                                                                                                                       'asian total under 2.25': '1.97',
                                                                                                                       'asian total under 2.75': '1.56',
                                                                                                                       'asian total under 3.25': '1.34',
                                                                                                                       'at least one half will be a draw no': '2.61',
                                                                                                                       'at least one half will be a draw yes': '1.46',
                                                                                                                       'away no bet draw': '1.74',
                                                                                                                       'both halves under 1.5 goals no': '1.60',
                                                                                                                       'both halves under 1.5 goals yes': '2.24',
                                                                                                                       'boths to score in both halves no': '1.01',
                                                                                                                       'boths to score in both halves yes': '12.50',
                                                                                                                       'boths to score no': '1.28',
                                                                                                                       'boths to score over 1.5 goals no': '1.09',
                                                                                                                       'boths to score over 1.5 goals yes': '6.50',
                                                                                                                       'boths to score under 1.5 goals no': '1.60',
                                                                                                                       'boths to score under 1.5 goals yes': '2.24',
                                                                                                                       'boths to score yes': '3.45',
                                                                                                                       'corners result draw': '5.40',
                                                                                                                       'draw will lose': '1.10',
                                                                                                                       'draw will win': '2.51',
                                                                                                                       'first goal 1-10 min no': '1.11',
                                                                                                                       'first goal 1-10 min yes': '5.25',
                                                                                                                       'first goal 1-2 min no': '1.01',
                                                                                                                       'first goal 1-2 min yes': '12.00',
                                                                                                                       'first goal 1-20 min no': '1.38',
                                                                                                                       'first goal 1-20 min yes': '2.80',
                                                                                                                       'first goal 1-30 min no': '1.75',
                                                                                                                       'first goal 1-30 min yes': '1.95',
                                                                                                                       'first goal 1-32 min no': '1.85',
                                                                                                                       'first goal 1-32 min yes': '1.85',
                                                                                                                       'first goal 1-5 min no': '1.02',
                                                                                                                       'first goal 1-5 min yes': '9.00',
                                                                                                                       'first to happen goal or substitution goal': '1.45',
                                                                                                                       'first to happen goal or substitution substitution': '2.65',
                                                                                                                       'first to score no goal': '3.55',
                                                                                                                       'half with most goals 3-way half1=half2': '3.50',
                                                                                                                       'hat trick scored yes': '15.00',
                                                                                                                       'home no bet draw': '2.46',
                                                                                                                       'ht or ft 1': '2.91',
                                                                                                                       'ht or ft 2': '1.74',
                                                                                                                       'ht or ft and total goals over 1.5 1': '3.35',
                                                                                                                       'ht or ft and total goals over 1.5 2': '1.95',
                                                                                                                       'ht or ft and total goals over 1.5 x': '2.33',
                                                                                                                       'ht or ft and total goals over 2.5 1': '4.75',
                                                                                                                       'ht or ft and total goals over 2.5 2': '2.73',
                                                                                                                       'ht or ft and total goals over 2.5 x': '4.35',
                                                                                                                       'ht or ft and total goals over 3.5 1': '9.70',
                                                                                                                       'ht or ft and total goals over 3.5 2': '5.20',
                                                                                                                       'ht or ft and total goals over 3.5 x': '7.10',
                                                                                                                       'ht or ft and total goals over 4.5 1': '19.50',
                                                                                                                       'ht or ft and total goals over 4.5 2': '10.50',
                                                                                                                       'ht or ft and total goals over 4.5 x': '17.00',
                                                                                                                       'ht or ft and total goals under 1.5 1': '10.00',
                                                                                                                       'ht or ft and total goals under 1.5 2': '6.60',
                                                                                                                       'ht or ft and total goals under 1.5 x': '4.10',
                                                                                                                       'ht or ft and total goals under 2.5 1': '5.30',
                                                                                                                       'ht or ft and total goals under 2.5 2': '3.35',
                                                                                                                       'ht or ft and total goals under 2.5 x': '2.25',
                                                                                                                       'ht or ft and total goals under 3.5 1': '3.35',
                                                                                                                       'ht or ft and total goals under 3.5 2': '2.11',
                                                                                                                       'ht or ft and total goals under 3.5 x': '1.88',
                                                                                                                       'ht or ft and total goals under 4.5 1': '2.88',
                                                                                                                       'ht or ft and total goals under 4.5 2': '1.76',
                                                                                                                       'ht or ft and total goals under 4.5 x': '1.63',
                                                                                                                       'ht or ft x': '1.70',
                                                                                                                       'injury time goal no': '1.19',
                                                                                                                       'injury time goal yes': '4.30',
                                                                                                                       'last goal 60-ft min no': '2.40',
                                                                                                                       'last goal 60-ft min yes': '1.50',
                                                                                                                       'last goal 72-ft min no': '1.85',
                                                                                                                       'last goal 72-ft min yes': '1.85',
                                                                                                                       'last goal 75-ft min no': '1.70',
                                                                                                                       'last goal 75-ft min yes': '2.00',
                                                                                                                       'last to score no goal': '3.55',
                                                                                                                       'number of goals 5+ 1': '2.25',
                                                                                                                       'number of goals 5+ 2': '3.10',
                                                                                                                       'number of goals 5+ 3': '6.60',
                                                                                                                       'number of goals 5+ 4': '18.50',
                                                                                                                       'number of goals 5+ 5+': '50.00',
                                                                                                                       'number of goals 5+ no goal': '3.55',
                                                                                                                       'own goal no': '1.04',
                                                                                                                       'own goal yes': '9.00',
                                                                                                                       'penalty in the match no': '1.42',
                                                                                                                       'penalty in the match yes': '2.70',
                                                                                                                       'player to score alessandro murgia': '5.00',
                                                                                                                       'player to score andrea petagna': '2.50',
                                                                                                                       'player to score kevin lasagna': '2.80',
                                                                                                                       'player to score lucas castro': '6.00',
                                                                                                                       'player to score mirko valdifiori': '10.00',
                                                                                                                       'player to score rodrigo de paul': '3.00',
                                                                                                                       'player to score seko fofana': '5.00',
                                                                                                                       'player to score simone missiroli': '8.00',
                                                                                                                       'player to score stefano okaka': '3.50',
                                                                                                                       'player to score walace': '7.00',
                                                                                                                       'red card no': '1.28',
                                                                                                                       'red card yes': '3.45',
                                                                                                                       'spal asian handicap +0.25': '1.87',
                                                                                                                       'spal asian handicap +0.75': '1.37',
                                                                                                                       'spal asian handicap -0.25': '3.35',
                                                                                                                       'spal away no bet': '2.02',
                                                                                                                       'spal corners handicap +1.0': '1.51',
                                                                                                                       'spal corners handicap +1.5': '1.63',
                                                                                                                       'spal corners result': '2.71',
                                                                                                                       'spal first to score': '3.20',
                                                                                                                       'spal half with most goals half1=half2': '2.01',
                                                                                                                       'spal handicap +0.5': '1.58',
                                                                                                                       'spal handicap +1.0': '1.16',
                                                                                                                       'spal handicap +1.5': '1.10',
                                                                                                                       'spal handicap +2.0': '1.10',
                                                                                                                       'spal handicap +2.5': '1.08',
                                                                                                                       'spal handicap -0.5': '4.20',
                                                                                                                       'spal handicap -1.0': '11.00',
                                                                                                                       'spal handicap -1.5': '13.00',
                                                                                                                       'spal handicap 0.0': '2.65',
                                                                                                                       'spal last to score': '3.20',
                                                                                                                       'spal leading at halftime and not to win': '11.50',
                                                                                                                       'spal not to lose and over 2.5 goals': '4.85',
                                                                                                                       'spal number of goals 0': '1.63',
                                                                                                                       'spal number of goals 1': '2.41',
                                                                                                                       'spal number of goals 2': '8.60',
                                                                                                                       'spal number of goals 3': '46.00',
                                                                                                                       'spal number of goals 4': '100',
                                                                                                                       'spal number of goals 5+': '100',
                                                                                                                       'spal time of 1-st corner 0-15': '1.77',
                                                                                                                       'spal time of 1-st corner 16-30': '2.93',
                                                                                                                       'spal time of 1-st corner 31-ht': '5.30',
                                                                                                                       'spal time of 1-st corner 46-60': '17.00',
                                                                                                                       'spal time of 1-st corner 61-75': '38.00',
                                                                                                                       'spal time of 1-st corner 76-ft': '70.00',
                                                                                                                       'spal to receive first yellow card': '1.81',
                                                                                                                       'spal to score in both halves': '5.70',
                                                                                                                       'spal to take first corner': '1.97',
                                                                                                                       'spal to win both halves': '15.50',
                                                                                                                       'spal to win by 1 goal or draw  no spal': '1.61',
                                                                                                                       'spal to win by 1 goal or draw  yes spal': '2.09',
                                                                                                                       'spal to win by 2 goals no spal': '1.03',
                                                                                                                       'spal to win by 2 goals yes spal': '9.70',
                                                                                                                       'spal to win either half': '2.39',
                                                                                                                       'spal to win from behind': '15.00',
                                                                                                                       'spal to win to nil yes': '6.50',
                                                                                                                       'spal total corners over 4.5': '1.63',
                                                                                                                       'spal total corners over 5.0': '1.94',
                                                                                                                       'spal total corners under 4.5': '2.14',
                                                                                                                       'spal total corners under 5.0': '1.77',
                                                                                                                       'spal total over 0.5': '2.19',
                                                                                                                       'spal total over 1.0': '5.80',
                                                                                                                       'spal total over 1.5': '8.60',
                                                                                                                       'spal total over 2.0': '9.80',
                                                                                                                       'spal total over 2.5': '12.00',
                                                                                                                       'spal total under 0.5': '1.63',
                                                                                                                       'spal total under 1.0': '1.11',
                                                                                                                       'spal total under 1.5': '1.05',
                                                                                                                       'spal total under 2.0': '1.05',
                                                                                                                       'spal total under 2.5': '1.03',
                                                                                                                       'spal total yellow cards over 2.5': '1.83',
                                                                                                                       'spal total yellow cards under 2.5': '1.88',
                                                                                                                       'spal will lose': '1.58',
                                                                                                                       'spal will win': '4.20',
                                                                                                                       'spal yellow cards handicap +1.0': '1.32',
                                                                                                                       'spal yellow cards handicap -1.0': '3.45',
                                                                                                                       'spal yellow сards result': '2.24',
                                                                                                                       'time of first corner 0-15': '1.11',
                                                                                                                       'time of first corner 16-30': '4.10',
                                                                                                                       'time of first corner 31-ht': '20.00',
                                                                                                                       'time of first corner 46-60': '100',
                                                                                                                       'time of first corner 61-75': '100',
                                                                                                                       'time of first corner 76-ft': '100',
                                                                                                                       'time of first goal 0-15': '3.35',
                                                                                                                       'time of first goal 16-30': '3.80',
                                                                                                                       'time of first goal 31-ht': '4.20',
                                                                                                                       'time of first goal 46-60': '6.80',
                                                                                                                       'time of first goal 61-75': '10.50',
                                                                                                                       'time of first goal 76-ft': '13.00',
                                                                                                                       'time of first yellow card 3-way 1 26 min': '1.81',
                                                                                                                       'time of first yellow card 3-way 27 ft min': '1.81',
                                                                                                                       'time of first yellow card 3-way no card': '27.00',
                                                                                                                       'time of last goal 0-15': '30.00',
                                                                                                                       'time of last goal 16-30': '18.50',
                                                                                                                       'time of last goal 31-ht': '9.50',
                                                                                                                       'time of last goal 46-60': '6.30',
                                                                                                                       'time of last goal 61-75': '4.10',
                                                                                                                       'time of last goal 76-ft': '1.93',
                                                                                                                       'time of the first corner 1 7 min no': '1.85',
                                                                                                                       'time of the first corner 1 7 min yes': '1.85',
                                                                                                                       'to receive first yellow card no card': '27.00',
                                                                                                                       'to score double no': '1.25',
                                                                                                                       'to score double yes': '3.70',
                                                                                                                       'to take first corner no corner': '251',
                                                                                                                       'total corners odd/even even': '1.87',
                                                                                                                       'total corners odd/even odd': '1.87',
                                                                                                                       'total corners over 10.0': '1.52',
                                                                                                                       'total corners over 10.5': '1.68',
                                                                                                                       'total corners over 11.0': '1.88',
                                                                                                                       'total corners over 11.5': '2.14',
                                                                                                                       'total corners over 12.0': '2.40',
                                                                                                                       'total corners over 5.0': '1.70',
                                                                                                                       'total corners over 5.5': '1.76',
                                                                                                                       'total corners under 10.0': '2.37',
                                                                                                                       'total corners under 10.5': '2.07',
                                                                                                                       'total corners under 11.0': '1.82',
                                                                                                                       'total corners under 11.5': '1.63',
                                                                                                                       'total corners under 12.0': '1.51',
                                                                                                                       'total corners under 5.0': '1.95',
                                                                                                                       'total corners under 5.5': '1.88',
                                                                                                                       'total even': '1.77',
                                                                                                                       'total goal minutes over 110.5': '1.85',
                                                                                                                       'total goal minutes over 120.5': '1.90',
                                                                                                                       'total goal minutes over 130.5': '2.20',
                                                                                                                       'total goal minutes under 110.5': '1.90',
                                                                                                                       'total goal minutes under 120.5': '1.85',
                                                                                                                       'total goal minutes under 130.5': '1.62',
                                                                                                                       'total odd': '1.98',
                                                                                                                       'total over 0.5': '1.25',
                                                                                                                       'total over 1.0': '1.49',
                                                                                                                       'total over 1.5': '2.24',
                                                                                                                       'total over 2.0': '3.75',
                                                                                                                       'total over 2.5': '4.70',
                                                                                                                       'total over 3.0': '2.98',
                                                                                                                       'total over 3.5': '3.60',
                                                                                                                       'total over 4.0': '6.30',
                                                                                                                       'total over 4.5': '7.00',
                                                                                                                       'total over 5.0': '12.00',
                                                                                                                       'total under 0.5': '3.55',
                                                                                                                       'total under 1.0': '2.50',
                                                                                                                       'total under 1.5': '1.60',
                                                                                                                       'total under 2.0': '1.24',
                                                                                                                       'total under 2.5': '1.16',
                                                                                                                       'total under 3.0': '1.40',
                                                                                                                       'total under 3.5': '1.29',
                                                                                                                       'total under 4.0': '1.12',
                                                                                                                       'total under 4.5': '1.10',
                                                                                                                       'total under 5.0': '1.03',
                                                                                                                       'total yellow cards over 1.5': '1.67',
                                                                                                                       'total yellow cards over 3.5': '1.98',
                                                                                                                       'total yellow cards over 5.0': '1.75',
                                                                                                                       'total yellow cards over 5.5': '2.12',
                                                                                                                       'total yellow cards under 1.5': '1.99',
                                                                                                                       'total yellow cards under 3.5': '1.68',
                                                                                                                       'total yellow cards under 5.0': '1.96',
                                                                                                                       'total yellow cards under 5.5': '1.64',
                                                                                                                       'udinese asian handicap +0.25': '1.29',
                                                                                                                       'udinese asian handicap -0.25': '1.87',
                                                                                                                       'udinese asian handicap -0.75': '2.95',
                                                                                                                       'udinese corners handicap -1.0': '2.24',
                                                                                                                       'udinese corners handicap -1.5': '2.10',
                                                                                                                       'udinese corners result': '1.80',
                                                                                                                       'udinese first to score': '2.08',
                                                                                                                       'udinese half with most goals half1=half2': '2.57',
                                                                                                                       'udinese handicap +0.5': '1.20',
                                                                                                                       'udinese handicap +1.0': '1.02',
                                                                                                                       'udinese handicap +1.5': '1.01',
                                                                                                                       'udinese handicap -0.5': '2.30',
                                                                                                                       'udinese handicap -1.0': '4.80',
                                                                                                                       'udinese handicap -1.5': '6.10',
                                                                                                                       'udinese handicap -2.0': '7.20',
                                                                                                                       'udinese handicap -2.5': '8.30',
                                                                                                                       'udinese handicap 0.0': '1.44',
                                                                                                                       'udinese home no bet': '1.51',
                                                                                                                       'udinese last to score': '2.08',
                                                                                                                       'udinese leading at halftime and not to win': '14.50',
                                                                                                                       'udinese not to lose and over 2.5 goals': '2.80',
                                                                                                                       'udinese number of goals 0': '2.23',
                                                                                                                       'udinese number of goals 1': '2.11',
                                                                                                                       'udinese number of goals 2': '4.85',
                                                                                                                       'udinese number of goals 3': '16.50',
                                                                                                                       'udinese number of goals 4': '75.00',
                                                                                                                       'udinese number of goals 5+': '100',
                                                                                                                       'udinese time of 1-st corner 0-15': '1.56',
                                                                                                                       'udinese time of 1-st corner 16-30': '2.96',
                                                                                                                       'udinese time of 1-st corner 31-ht': '6.30',
                                                                                                                       'udinese time of 1-st corner 46-60': '24.00',
                                                                                                                       'udinese time of 1-st corner 61-75': '60.00',
                                                                                                                       'udinese time of 1-st corner 76-ft': '100',
                                                                                                                       'udinese to receive first yellow card': '1.88',
                                                                                                                       'udinese to score in both halves': '3.30',
                                                                                                                       'udinese to take first corner': '1.64',
                                                                                                                       'udinese to win both halves': '6.10',
                                                                                                                       'udinese to win by 1 goal or draw  no udinese': '1.86',
                                                                                                                       'udinese to win by 1 goal or draw  yes udinese': '1.78',
                                                                                                                       'udinese to win by 2 goals no udinese': '1.13',
                                                                                                                       'udinese to win by 2 goals yes udinese': '5.30',
                                                                                                                       'udinese to win either half': '1.54',
                                                                                                                       'udinese to win from behind': '7.70',
                                                                                                                       'udinese to win to nil yes': '3.20',
                                                                                                                       'udinese total corners over 5.5': '1.65',
                                                                                                                       'udinese total corners over 6.0': '1.93',
                                                                                                                       'udinese total corners under 5.5': '2.12',
                                                                                                                       'udinese total corners under 6.0': '1.78',
                                                                                                                       'udinese total over 0.5': '1.61',
                                                                                                                       'udinese total over 1.0': '2.75',
                                                                                                                       'udinese total over 1.5': '4.30',
                                                                                                                       'udinese total over 2.0': '3.75',
                                                                                                                       'udinese total over 2.5': '5.00',
                                                                                                                       'udinese total over 3.0': '12.50',
                                                                                                                       'udinese total over 3.5': '14.50',
                                                                                                                       'udinese total under 0.5': '2.23',
                                                                                                                       'udinese total under 1.0': '1.42',
                                                                                                                       'udinese total under 1.5': '1.19',
                                                                                                                       'udinese total under 2.0': '1.27',
                                                                                                                       'udinese total under 2.5': '1.17',
                                                                                                                       'udinese total under 3.0': '1.03',
                                                                                                                       'udinese total under 3.5': '1.02',
                                                                                                                       'udinese total yellow cards over 2.5': '1.92',
                                                                                                                       'udinese total yellow cards under 2.5': '1.79',
                                                                                                                       'udinese will lose': '1.49',
                                                                                                                       'udinese will win': '2.30',
                                                                                                                       'udinese yellow cards handicap +1.0': '1.22',
                                                                                                                       'udinese yellow cards handicap -1.0': '3.10',
                                                                                                                       'udinese yellow сards result': '2.41',
                                                                                                                       'yellow сards result draw': '4.05'}}}
