bets = {'4 zoomers - infinity esports': {'Draw Full Time No': '1.25',
                                  'Draw Full Time Yes': '3.70',
                                  'Handicap winner Full Time 4 Zoomers (-1.5)': '1.25',
                                  'Handicap winner Full Time Infinity eSports (+1.5)': '3.70',
                                  'Odd / Even Game 1 Even': '1.90',
                                  'Odd / Even Game 1 Odd': '1.90',
                                  'Which team will be the first to make a frag? Game 1 4 Zoomers': '1.71',
                                  'Which team will be the first to make a frag? Game 1 Infinity eSports': '2.06',
                                  'Winner Game 1 4 Zoomers': '1.14',
                                  'Winner Game 1 Infinity eSports': '5.10',
                                  'url': 'https://www.favorit.com.ua/en/bets/#event=27092399&tours=2459582'},
 'beastcoast - infinity esports': {'Draw Full Time No': '1.34',
                                   'Draw Full Time Yes': '3.10',
                                   'Handicap winner Full Time Beastcoast (-1.5)': '1.40',
                                   'Handicap winner Full Time Infinity eSports (+1.5)': '2.80',
                                   'Odd / Even Game 1 Even': '1.90',
                                   'Odd / Even Game 1 Odd': '1.90',
                                   'Which team will be the first to make a frag? Game 1 Beastcoast': '1.74',
                                   'Which team will be the first to make a frag? Game 1 Infinity eSports': '2.02',
                                   'Winner Game 1 Beastcoast': '1.18',
                                   'Winner Game 1 Infinity eSports': '4.45',
                                   'url': 'https://www.favorit.com.ua/en/bets/#event=27092386&tours=2459582'},
 'cr4zy - thunder predator': {'Draw Full Time No': '1.75',
                              'Draw Full Time Yes': '2.00',
                              'Handicap winner Full Time CR4ZY (+1.5)': '1.38',
                              'Handicap winner Full Time CR4ZY (-1.5)': '3.80',
                              'Handicap winner Full Time Thunder Predator (+1.5)': '1.24',
                              'Handicap winner Full Time Thunder Predator (-1.5)': '2.90',
                              'Odd / Even Game 1 Even': '1.90',
                              'Odd / Even Game 1 Odd': '1.90',
                              'Which team will be the first to make a frag? Game 1 CR4ZY': '1.88',
                              'Which team will be the first to make a frag? Game 1 Thunder Predator': '1.86',
                              'Winner Game 1 CR4ZY': '2.00',
                              'Winner Game 1 Thunder Predator': '1.75',
                              'url': 'https://www.favorit.com.ua/en/bets/#event=27092393&tours=2459582'}}
