bets = {'4 zoomers - infinity': {'    Result         4 Zoomers To Win   ': '1.33',
                          '    Result         4 Zoomers To Win or Infinity To Win   ': '1.27',
                          '    Result         Draw   ': '3.60',
                          '    Result         Infinity To Win   ': '25.00',
                          '    Result         Infinity To Win or Draw   ': '3.15',
                          '4 zoomers will win': '1.33',
                          'infinity will win': '3.60',
                          'url': 'https://www.marathonbet.com/en/betting/e-Sports/Dota+2/The+Great+American+Rivalry/Main+Event/Best+of+2+maps/4+Zoomers+vs+Infinity+-+9764074'},
 'angel alliance - starluck.fly': {'    Correct Score          Angel Alliance     (2 - 0)  ': '5.25',
                                   '    Correct Score          Angel Alliance     (2 - 1)  ': '4.20',
                                   '    Correct Score          StarLucK.Fly     (0 - 2)  ': '2.81',
                                   '    Correct Score          StarLucK.Fly     (1 - 2)  ': '3.125',
                                   '    To Win Match With Handicap By Maps          Angel Alliance     (+1.5)  ': '1.44',
                                   '    To Win Match With Handicap By Maps          StarLucK.Fly     (-1.5)  ': '2.81',
                                   '    Total Maps          Over     (2.5)  ': '1.95',
                                   '    Total Maps          Under     (2.5)  ': '1.86',
                                   '    Total Maps        Even ': '1.86',
                                   '    Total Maps        Odd ': '1.95',
                                   'angel alliance will win': '2.45',
                                   'starluck.fly will win': '1.55',
                                   'url': 'https://www.marathonbet.com/en/betting/e-Sports/Dota+2/Libertango+Cup/Main+Event/Best+of+3+maps/Angel+Alliance+vs+StarLucK.Fly+-+9764184'},
 'beastcoast - infinity': {'    Result         Draw   ': '2.95',
                           '    Result         Infinity To Win   ': '18.00',
                           '    Result         Infinity To Win or Draw   ': '2.54',
                           '    Result         beastcoast To Win   ': '1.48',
                           '    Result         beastcoast To Win or Infinity To Win   ': '1.37',
                           'beastcoast will win': '1.48',
                           'infinity will win': '2.95',
                           'url': 'https://www.marathonbet.com/en/betting/e-Sports/Dota+2/The+Great+American+Rivalry/Main+Event/Best+of+2+maps/beastcoast+vs+Infinity+-+9764073'},
 'cr4zy - thunder predator': {'    Result         CR4ZY To Win   ': '4.15',
                              '    Result         CR4ZY To Win or Draw   ': '1.31',
                              '    Result         CR4ZY To Win or Thunder Predator To Win   ': '1.85',
                              '    Result         Draw   ': '1.90',
                              '    Result         Thunder Predator To Win   ': '3.32',
                              '    Result         Thunder Predator To Win or Draw   ': '1.21',
                              'cr4zy will win': '4.15',
                              'thunder predator will win': '1.90',
                              'url': 'https://www.marathonbet.com/en/betting/e-Sports/Dota+2/The+Great+American+Rivalry/Main+Event/Best+of+2+maps/CR4ZY+vs+Thunder+Predator+-+9764075'},
 'ehome - vici gaming': {'    1st Map Result         EHOME To Win   ': '2.16',
                         '    1st Map Result         Vici Gaming To Win   ': '1.666',
                         '    2nd Map Result         EHOME To Win   ': '2.16',
                         '    2nd Map Result         Vici Gaming To Win   ': '1.666',
                         '    Correct Score          EHOME     (2 - 0)  ': '5.05',
                         '    Correct Score          EHOME     (2 - 1)  ': '4.10',
                         '    Correct Score          Vici Gaming     (0 - 2)  ': '2.91',
                         '    Correct Score          Vici Gaming     (1 - 2)  ': '3.14',
                         '    To Win Match With Handicap By Maps          EHOME     (+1.5)  ': '1.42',
                         '    To Win Match With Handicap By Maps          Vici Gaming     (-1.5)  ': '2.91',
                         '    Total Maps          Over     (2.5)  ': '1.94',
                         '    Total Maps          Under     (2.5)  ': '1.87',
                         '    Total Maps        Even ': '1.87',
                         '    Total Maps        Odd ': '1.94',
                         'ehome will win': '2.36',
                         'url': 'https://www.marathonbet.com/en/betting/e-Sports/Dota+2/Dota+Pit+League/Main+Event/Best+of+3+maps/EHOME+vs+Vici+Gaming+-+9769339',
                         'vici gaming will win': '1.59'},
 'execration - veteran': {'    1st Map Result         Execration To Win   ': '2.67',
                          '    1st Map Result         Veteran To Win   ': '1.45',
                          '    2nd Map Result         Execration To Win   ': '2.67',
                          '    2nd Map Result         Veteran To Win   ': '1.45',
                          '    Correct Score          Execration     (2 - 0)  ': '7.90',
                          '    Correct Score          Execration     (2 - 1)  ': '5.40',
                          '    Correct Score          Veteran     (0 - 2)  ': '2.19',
                          '    Correct Score          Veteran     (1 - 2)  ': '2.98',
                          '    To Win Match With Handicap By Maps          Execration     (+1.5)  ': '1.68',
                          '    To Win Match With Handicap By Maps          Veteran     (-1.5)  ': '2.19',
                          '    Total Maps          Over     (2.5)  ': '2.11',
                          '    Total Maps          Under     (2.5)  ': '1.73',
                          '    Total Maps        Even ': '1.73',
                          '    Total Maps        Odd ': '2.11',
                          'execration will win': '3.38',
                          'url': 'https://www.marathonbet.com/en/betting/e-Sports/Dota+2/Moon+Studio+Asian+League/Main+Event/Best+of+3+maps/Execration+vs+Veteran+-+9769404',
                          'veteran will win': '1.32'},
 'invictus gaming - cdec gaming': {'    1st Map Result         CDEC Gaming To Win   ': '1.68',
                                   '    1st Map Result         Invictus Gaming To Win   ': '2.13',
                                   '    2nd Map Result         CDEC Gaming To Win   ': '1.68',
                                   '    2nd Map Result         Invictus Gaming To Win   ': '2.13',
                                   '    Correct Score          CDEC Gaming     (0 - 2)  ': '2.95',
                                   '    Correct Score          CDEC Gaming     (1 - 2)  ': '3.16',
                                   '    Correct Score          Invictus Gaming     (2 - 0)  ': '4.95',
                                   '    Correct Score          Invictus Gaming     (2 - 1)  ': '4.05',
                                   '    To Win Match With Handicap By Maps          CDEC Gaming     (-1.5)  ': '2.95',
                                   '    To Win Match With Handicap By Maps          Invictus Gaming     (+1.5)  ': '1.41',
                                   '    Total Maps          Over     (2.5)  ': '1.94',
                                   '    Total Maps          Under     (2.5)  ': '1.87',
                                   '    Total Maps        Even ': '1.87',
                                   '    Total Maps        Odd ': '1.94',
                                   'cdec gaming will win': '1.60',
                                   'invictus gaming will win': '2.34',
                                   'url': 'https://www.marathonbet.com/en/betting/e-Sports/Dota+2/Dota+Pit+League/Main+Event/Best+of+3+maps/Invictus+Gaming+vs+CDEC+Gaming+-+9769340'},
 'neon - 496 gaming': {'    1st Map Result         496 Gaming To Win   ': '3.26',
                       '    1st Map Result         Neon To Win   ': '1.32',
                       '    2nd Map Result         496 Gaming To Win   ': '3.26',
                       '    2nd Map Result         Neon To Win   ': '1.32',
                       '    Correct Score          496 Gaming     (0 - 2)  ': '12.25',
                       '    Correct Score          496 Gaming     (1 - 2)  ': '7.10',
                       '    Correct Score          Neon     (2 - 0)  ': '1.81',
                       '    Correct Score          Neon     (2 - 1)  ': '3.04',
                       '    To Win Match With Handicap By Maps          496 Gaming     (+1.5)  ': '2.01',
                       '    To Win Match With Handicap By Maps          Neon     (-1.5)  ': '1.81',
                       '    Total Maps          Over     (2.5)  ': '2.38',
                       '    Total Maps          Under     (2.5)  ': '1.59',
                       '    Total Maps        Even ': '1.59',
                       '    Total Maps        Odd ': '2.38',
                       '496 gaming will win': '4.80',
                       'neon will win': '1.185',
                       'url': 'https://www.marathonbet.com/en/betting/e-Sports/Dota+2/Moon+Studio+Asian+League/Main+Event/Best+of+3+maps/Neon+vs+496+Gaming+-+9769398'},
 'symmetric - goodfellaz': {'    Correct Score          GoodFellaz     (0 - 2)  ': '1.99',
                            '    Correct Score          GoodFellaz     (1 - 2)  ': '2.99',
                            '    Correct Score          Symmetric     (2 - 0)  ': '9.70',
                            '    Correct Score          Symmetric     (2 - 1)  ': '6.10',
                            '    To Win Match With Handicap By Maps          GoodFellaz     (-1.5)  ': '1.99',
                            '    To Win Match With Handicap By Maps          Symmetric     (+1.5)  ': '1.82',
                            '    Total Maps          Over     (2.5)  ': '2.23',
                            '    Total Maps          Under     (2.5)  ': '1.66',
                            '    Total Maps        Even ': '1.66',
                            '    Total Maps        Odd ': '2.23',
                            'goodfellaz will win': '1.25',
                            'symmetric will win': '3.95',
                            'url': 'https://www.marathonbet.com/en/betting/e-Sports/Dota+2/Libertango+Cup/Main+Event/Best+of+3+maps/Symmetric+vs+GoodFellaz+-+9764183'}}
