bets = {'4 zoomers - infinity esports': {'1x2. 1 map. 4 Zoomers': '1.1',
                                  '1x2. 1 map. Infinity eSports': '6.3',
                                  '1x2. 2 map. 4 Zoomers': '1.1',
                                  '1x2. 2 map. Infinity eSports': '6.3',
                                  '1x2. 4 Zoomers': '1.216',
                                  '1x2. Draw': '4.82',
                                  '1x2. Infinity eSports': '12.5',
                                  'Team To Perform Next Frag. 1 map. Next Frag 10 - Team 4 Zoomers': '1.72',
                                  'Team To Perform Next Frag. 1 map. Next Frag 10 - Team Infinity eSports': '2.05',
                                  'Team To Perform Next Frag. 1 map. Next Frag 20 - Team 4 Zoomers': '1.6',
                                  'Team To Perform Next Frag. 1 map. Next Frag 20 - Team Infinity eSports': '2.25',
                                  'Team To Perform Next Frag. 1 map. Next Frag 30 - Team 4 Zoomers': '1.51',
                                  'Team To Perform Next Frag. 1 map. Next Frag 30 - Team Infinity eSports': '2.45',
                                  'Team To Perform Next Frag. 1 map. Next Frag 40 - Team 4 Zoomers': '1.62',
                                  'Team To Perform Next Frag. 1 map. Next Frag 40 - Team Infinity eSports': '2.21',
                                  'Team To Perform Next Frag. 1 map. Next Frag 50 - Team 4 Zoomers': '1.65',
                                  'Team To Perform Next Frag. 1 map. Next Frag 50 - Team Infinity eSports': '2.16',
                                  'Team To Perform Next Frag. 2 map. Next Frag 10 - Team 4 Zoomers': '1.72',
                                  'Team To Perform Next Frag. 2 map. Next Frag 10 - Team Infinity eSports': '2.05',
                                  'Team To Perform Next Frag. 2 map. Next Frag 20 - Team 4 Zoomers': '1.6',
                                  'Team To Perform Next Frag. 2 map. Next Frag 20 - Team Infinity eSports': '2.25',
                                  'Team To Perform Next Frag. 2 map. Next Frag 30 - Team 4 Zoomers': '1.51',
                                  'Team To Perform Next Frag. 2 map. Next Frag 30 - Team Infinity eSports': '2.45',
                                  'Team To Perform Next Frag. 2 map. Next Frag 40 - Team 4 Zoomers': '1.62',
                                  'Team To Perform Next Frag. 2 map. Next Frag 40 - Team Infinity eSports': '2.21',
                                  'Team To Perform Next Frag. 2 map. Next Frag 50 - Team 4 Zoomers': '1.65',
                                  'Team To Perform Next Frag. 2 map. Next Frag 50 - Team Infinity eSports': '2.16',
                                  'Total Maps Handicap. 4 Zoomers Handicap -1.5 Maps': '1.21',
                                  'Total Maps Handicap. 4 Zoomers Handicap 0.5 Maps': '1.01',
                                  'Total Maps Handicap. Infinity eSports Handicap -0.5 Maps': '12',
                                  'Total Maps Handicap. Infinity eSports Handicap 1.5 Maps': '3.9',
                                  'Who Will Beat Roshan. 1 map. 1 Roshan Will Be Beaten By 4 Zoomers': '1.25',
                                  'Who Will Beat Roshan. 1 map. 1 Roshan Will Be Beaten By Infinity eSports': '3.7',
                                  'Who Will Beat Roshan. 2 map. 1 Roshan Will Be Beaten By 4 Zoomers': '1.25',
                                  'Who Will Beat Roshan. 2 map. 1 Roshan Will Be Beaten By Infinity eSports': '3.7',
                                  'url': 'https://1x-bet.com/en/line/Esports/2108178-Dota-2-The-Great-American-Rivalry-Division-1/78736985-4-Zoomers-Infinity-eSports/'},
 'angel alliance - starluck.fly': {'1x2. 1 map. Angel Alliance': '2.04',
                                   '1x2. 1 map. StarLucK.Fly': '1.73',
                                   '1x2. 2 map. Angel Alliance': '2.04',
                                   '1x2. 2 map. StarLucK.Fly': '1.73',
                                   '1x2. Angel Alliance': '2.2',
                                   '1x2. StarLucK.Fly': '1.65',
                                   'url': 'https://1x-bet.com/en/line/Esports/2110439-Dota-2-Libertango-Cup/78817908-Angel-Alliance-StarLucKFly/'},
 'anti-mage - tusk': {'1x2. Anti-Mage': '1.05',
                      '1x2. Tusk': '8.7',
                      'url': 'https://1x-bet.com/en/line/Esports/1534671-Dota-2-Arcana-Vote/78685989-Anti-Mage-Tusk/'},
 'beastcoast - infinity esports': {'1x2. 1 map. BeastCoast': '1.21',
                                   '1x2. 1 map. Infinity eSports': '4.16',
                                   '1x2. 2 map. BeastCoast': '1.22',
                                   '1x2. 2 map. Infinity eSports': '4.04',
                                   '1x2. BeastCoast': '1.43',
                                   '1x2. Draw': '3.38',
                                   '1x2. Infinity eSports': '9.3',
                                   'Team To Perform Next Frag. 1 map. Next Frag 10 - Team BeastCoast': '1.75',
                                   'Team To Perform Next Frag. 1 map. Next Frag 10 - Team Infinity eSports': '2.01',
                                   'Team To Perform Next Frag. 1 map. Next Frag 20 - Team BeastCoast': '1.64',
                                   'Team To Perform Next Frag. 1 map. Next Frag 20 - Team Infinity eSports': '2.17',
                                   'Team To Perform Next Frag. 1 map. Next Frag 30 - Team BeastCoast': '1.57',
                                   'Team To Perform Next Frag. 1 map. Next Frag 30 - Team Infinity eSports': '2.31',
                                   'Team To Perform Next Frag. 1 map. Next Frag 40 - Team BeastCoast': '1.66',
                                   'Team To Perform Next Frag. 1 map. Next Frag 40 - Team Infinity eSports': '2.14',
                                   'Team To Perform Next Frag. 1 map. Next Frag 50 - Team BeastCoast': '1.69',
                                   'Team To Perform Next Frag. 1 map. Next Frag 50 - Team Infinity eSports': '2.09',
                                   'Team To Perform Next Frag. 2 map. Next Frag 10 - Team BeastCoast': '1.75',
                                   'Team To Perform Next Frag. 2 map. Next Frag 10 - Team Infinity eSports': '2.01',
                                   'Team To Perform Next Frag. 2 map. Next Frag 20 - Team BeastCoast': '1.65',
                                   'Team To Perform Next Frag. 2 map. Next Frag 20 - Team Infinity eSports': '2.16',
                                   'Team To Perform Next Frag. 2 map. Next Frag 30 - Team BeastCoast': '1.57',
                                   'Team To Perform Next Frag. 2 map. Next Frag 30 - Team Infinity eSports': '2.31',
                                   'Team To Perform Next Frag. 2 map. Next Frag 40 - Team BeastCoast': '1.67',
                                   'Team To Perform Next Frag. 2 map. Next Frag 40 - Team Infinity eSports': '2.12',
                                   'Team To Perform Next Frag. 2 map. Next Frag 50 - Team BeastCoast': '1.69',
                                   'Team To Perform Next Frag. 2 map. Next Frag 50 - Team Infinity eSports': '2.09',
                                   'Total Maps Handicap. BeastCoast Handicap -1.5 Maps': '1.43',
                                   'Total Maps Handicap. BeastCoast Handicap 0.5 Maps': '1.04',
                                   'Total Maps Handicap. Infinity eSports Handicap -0.5 Maps': '9.2',
                                   'Total Maps Handicap. Infinity eSports Handicap 1.5 Maps': '2.695',
                                   'Who Will Beat Roshan. 1 map. 1 Roshan Will Be Beaten By BeastCoast': '1.34',
                                   'Who Will Beat Roshan. 1 map. 1 Roshan Will Be Beaten By Infinity eSports': '3.09',
                                   'Who Will Beat Roshan. 2 map. 1 Roshan Will Be Beaten By BeastCoast': '1.35',
                                   'Who Will Beat Roshan. 2 map. 1 Roshan Will Be Beaten By Infinity eSports': '3.04',
                                   'url': 'https://1x-bet.com/en/line/Esports/2108178-Dota-2-The-Great-American-Rivalry-Division-1/78736317-BeastCoast-Infinity-eSports/'},
 "bloodseeker - nature's prophet": {'1x2. Bloodseeker': '3.84',
                                    "1x2. Nature's Prophet": '1.24',
                                    'url': 'https://1x-bet.com/en/line/Esports/1534671-Dota-2-Arcana-Vote/78685991-Bloodseeker-Natures-Prophet/'},
 'cr4zy - thunder predator': {'1x2. 1 map. CR4ZY': '1.9',
                              '1x2. 1 map. Thunder Predator': '1.85',
                              '1x2. 2 map. CR4ZY': '1.9',
                              '1x2. 2 map. Thunder Predator': '1.85',
                              '1x2. CR4ZY': '3.26',
                              '1x2. Draw': '2.15',
                              '1x2. Thunder Predator': '3.06',
                              'Team To Perform Next Frag. 1 map. Next Frag 10 - Team CR4ZY': '1.88',
                              'Team To Perform Next Frag. 1 map. Next Frag 10 - Team Thunder Predator': '1.86',
                              'Team To Perform Next Frag. 1 map. Next Frag 20 - Team CR4ZY': '1.86',
                              'Team To Perform Next Frag. 1 map. Next Frag 20 - Team Thunder Predator': '1.88',
                              'Team To Perform Next Frag. 1 map. Next Frag 30 - Team CR4ZY': '1.85',
                              'Team To Perform Next Frag. 1 map. Next Frag 30 - Team Thunder Predator': '1.89',
                              'Team To Perform Next Frag. 1 map. Next Frag 40 - Team CR4ZY': '1.89',
                              'Team To Perform Next Frag. 1 map. Next Frag 40 - Team Thunder Predator': '1.85',
                              'Team To Perform Next Frag. 1 map. Next Frag 50 - Team CR4ZY': '1.87',
                              'Team To Perform Next Frag. 1 map. Next Frag 50 - Team Thunder Predator': '1.87',
                              'Team To Perform Next Frag. 2 map. Next Frag 10 - Team CR4ZY': '1.88',
                              'Team To Perform Next Frag. 2 map. Next Frag 10 - Team Thunder Predator': '1.86',
                              'Team To Perform Next Frag. 2 map. Next Frag 20 - Team CR4ZY': '1.86',
                              'Team To Perform Next Frag. 2 map. Next Frag 20 - Team Thunder Predator': '1.88',
                              'Team To Perform Next Frag. 2 map. Next Frag 30 - Team CR4ZY': '1.85',
                              'Team To Perform Next Frag. 2 map. Next Frag 30 - Team Thunder Predator': '1.89',
                              'Team To Perform Next Frag. 2 map. Next Frag 40 - Team CR4ZY': '1.89',
                              'Team To Perform Next Frag. 2 map. Next Frag 40 - Team Thunder Predator': '1.85',
                              'Team To Perform Next Frag. 2 map. Next Frag 50 - Team CR4ZY': '1.87',
                              'Team To Perform Next Frag. 2 map. Next Frag 50 - Team Thunder Predator': '1.87',
                              'Total Maps Handicap. CR4ZY Handicap -1.5 Maps': '3.26',
                              'Total Maps Handicap. CR4ZY Handicap 0.5 Maps': '1.344',
                              'Total Maps Handicap. Thunder Predator Handicap -0.5 Maps': '3.04',
                              'Total Maps Handicap. Thunder Predator Handicap 1.5 Maps': '1.31',
                              'Who Will Beat Roshan. 1 map. 1 Roshan Will Be Beaten By CR4ZY': '1.9',
                              'Who Will Beat Roshan. 1 map. 1 Roshan Will Be Beaten By Thunder Predator': '1.84',
                              'Who Will Beat Roshan. 2 map. 1 Roshan Will Be Beaten By CR4ZY': '1.9',
                              'Who Will Beat Roshan. 2 map. 1 Roshan Will Be Beaten By Thunder Predator': '1.84',
                              'url': 'https://1x-bet.com/en/line/Esports/2108178-Dota-2-The-Great-American-Rivalry-Division-1/78736532-CR4ZY-Thunder-Predator/'},
 'disruptor - timbersaw': {'1x2. Disruptor': '1.835',
                           '1x2. Timbersaw': '1.91',
                           'url': 'https://1x-bet.com/en/line/Esports/1534671-Dota-2-Arcana-Vote/78685990-Disruptor-Timbersaw/'},
 'ehome - vici gaming': {'1x2. 1 map. EHOME': '2.136',
                         '1x2. 1 map. Vici Gaming': '1.67',
                         '1x2. 2 map. EHOME': '2.136',
                         '1x2. 2 map. Vici Gaming': '1.67',
                         '1x2. EHOME': '2.28',
                         '1x2. Vici Gaming': '1.6',
                         'Team To Perform Next Frag. 1 map. Next Frag 10 - Team EHOME': '1.91',
                         'Team To Perform Next Frag. 1 map. Next Frag 10 - Team Vici Gaming': '1.83',
                         'Team To Perform Next Frag. 1 map. Next Frag 20 - Team EHOME': '1.91',
                         'Team To Perform Next Frag. 1 map. Next Frag 20 - Team Vici Gaming': '1.83',
                         'Team To Perform Next Frag. 1 map. Next Frag 30 - Team EHOME': '1.92',
                         'Team To Perform Next Frag. 1 map. Next Frag 30 - Team Vici Gaming': '1.82',
                         'Team To Perform Next Frag. 1 map. Next Frag 40 - Team EHOME': '1.93',
                         'Team To Perform Next Frag. 1 map. Next Frag 40 - Team Vici Gaming': '1.81',
                         'Team To Perform Next Frag. 1 map. Next Frag 50 - Team EHOME': '1.91',
                         'Team To Perform Next Frag. 1 map. Next Frag 50 - Team Vici Gaming': '1.83',
                         'Team To Perform Next Frag. 2 map. Next Frag 10 - Team EHOME': '1.91',
                         'Team To Perform Next Frag. 2 map. Next Frag 10 - Team Vici Gaming': '1.83',
                         'Team To Perform Next Frag. 2 map. Next Frag 20 - Team EHOME': '1.91',
                         'Team To Perform Next Frag. 2 map. Next Frag 20 - Team Vici Gaming': '1.83',
                         'Team To Perform Next Frag. 2 map. Next Frag 30 - Team EHOME': '1.92',
                         'Team To Perform Next Frag. 2 map. Next Frag 30 - Team Vici Gaming': '1.82',
                         'Team To Perform Next Frag. 2 map. Next Frag 40 - Team EHOME': '1.93',
                         'Team To Perform Next Frag. 2 map. Next Frag 40 - Team Vici Gaming': '1.81',
                         'Team To Perform Next Frag. 2 map. Next Frag 50 - Team EHOME': '1.91',
                         'Team To Perform Next Frag. 2 map. Next Frag 50 - Team Vici Gaming': '1.83',
                         'Total Maps Even/Odd. Total Maps - Even': '1.76',
                         'Total Maps Even/Odd. Total Maps - Odd': '1.99',
                         'Total Maps Handicap. EHOME Handicap -1.5 Maps': '4.22',
                         'Total Maps Handicap. EHOME Handicap 1.5 Maps': '1.43',
                         'Total Maps Handicap. Vici Gaming Handicap -1.5 Maps': '2.7',
                         'Total Maps Handicap. Vici Gaming Handicap 1.5 Maps': '1.2',
                         'Total Maps. Total Maps Over 2.5': '1.99',
                         'Total Maps. Total Maps Under 2.5': '1.76',
                         'Who Will Beat Roshan. 1 map. 1 Roshan Will Be Beaten By EHOME': '2.06',
                         'Who Will Beat Roshan. 1 map. 1 Roshan Will Be Beaten By Vici Gaming': '1.71',
                         'Who Will Beat Roshan. 2 map. 1 Roshan Will Be Beaten By EHOME': '2.06',
                         'Who Will Beat Roshan. 2 map. 1 Roshan Will Be Beaten By Vici Gaming': '1.71',
                         'url': 'https://1x-bet.com/en/line/Esports/2108629-Dota-2-OGA-Dota-PIT-Season-2-China/78825640-EHOME-Vici-Gaming/'},
 'ethereal - destiny': {'1x2. 1 map. Destiny': '1.85',
                        '1x2. 1 map. ETHEREAL': '1.9',
                        '1x2. 2 map. Destiny': '1.85',
                        '1x2. 2 map. ETHEREAL': '1.9',
                        '1x2. Destiny': '1.84',
                        '1x2. ETHEREAL': '1.936',
                        'url': 'https://1x-bet.com/en/line/Esports/2109420-Dota-2-Masters-Tournament-Season-9/78816290-ETHEREAL-Destiny/'},
 'execration - veteran': {'1x2. 1 map. Execration': '2.97',
                          '1x2. 1 map. Veteran': '1.37',
                          '1x2. 2 map. Execration': '2.97',
                          '1x2. 2 map. Veteran': '1.37',
                          '1x2. Execration': '3.72',
                          '1x2. Veteran': '1.26',
                          'url': 'https://1x-bet.com/en/line/Esports/2110852-Dota-2-Moon-Studio-Asian-League-Southeast-Asia-Qualifier/78804900-Execration-Veteran/'},
 'gorillaz-pride - spirits': {'1x2. 1 map. Gorillaz-Pride': '1.69',
                              '1x2. 1 map. Spirits': '2.1',
                              '1x2. 2 map. Gorillaz-Pride': '1.69',
                              '1x2. 2 map. Spirits': '2.1',
                              '1x2. Draw': '2.03',
                              '1x2. Gorillaz-Pride': '2.75',
                              '1x2. Spirits': '4.16',
                              'url': 'https://1x-bet.com/en/line/Esports/2110240-Dota-2-The-Great-American-Rivalry-Division-2/78811384-Gorillaz-Pride-Spirits/'},
 'immortal gaming - vampire': {'1x2. 1 map. Immortal Gaming': '1.83',
                               '1x2. 1 map. Vampire': '1.925',
                               '1x2. 2 map. Immortal Gaming': '1.83',
                               '1x2. 2 map. Vampire': '1.925',
                               '1x2. Immortal Gaming': '1.81',
                               '1x2. Vampire': '1.955',
                               'url': 'https://1x-bet.com/en/line/Esports/2109420-Dota-2-Masters-Tournament-Season-9/78816291-Immortal-Gaming-Vampire/'},
 'internal discord - agn': {'1x2. 1 map. AGN': '1.39',
                            '1x2. 1 map. Internal Discord': '2.875',
                            '1x2. 2 map. AGN': '1.39',
                            '1x2. 2 map. Internal Discord': '2.875',
                            '1x2. AGN': '1.84',
                            '1x2. Draw': '2.616',
                            '1x2. Internal Discord': '5.75',
                            'url': 'https://1x-bet.com/en/line/Esports/2102691-Dota-2-LPL-Pro-League-Season-2/78819072-Internal-Discord-AGN/'},
 'invictus gaming - cdec': {'1x2. 1 map. CDEC': '1.67',
                            '1x2. 1 map. Invictus Gaming': '2.136',
                            '1x2. 2 map. CDEC': '1.67',
                            '1x2. 2 map. Invictus Gaming': '2.136',
                            '1x2. CDEC': '1.6',
                            '1x2. Invictus Gaming': '2.295',
                            'Team To Perform Next Frag. 1 map. Next Frag 10 - Team CDEC': '1.83',
                            'Team To Perform Next Frag. 1 map. Next Frag 10 - Team Invictus Gaming': '1.91',
                            'Team To Perform Next Frag. 1 map. Next Frag 20 - Team CDEC': '1.83',
                            'Team To Perform Next Frag. 1 map. Next Frag 20 - Team Invictus Gaming': '1.91',
                            'Team To Perform Next Frag. 1 map. Next Frag 30 - Team CDEC': '1.82',
                            'Team To Perform Next Frag. 1 map. Next Frag 30 - Team Invictus Gaming': '1.92',
                            'Team To Perform Next Frag. 1 map. Next Frag 40 - Team CDEC': '1.81',
                            'Team To Perform Next Frag. 1 map. Next Frag 40 - Team Invictus Gaming': '1.93',
                            'Team To Perform Next Frag. 1 map. Next Frag 50 - Team CDEC': '1.83',
                            'Team To Perform Next Frag. 1 map. Next Frag 50 - Team Invictus Gaming': '1.91',
                            'Team To Perform Next Frag. 2 map. Next Frag 10 - Team CDEC': '1.83',
                            'Team To Perform Next Frag. 2 map. Next Frag 10 - Team Invictus Gaming': '1.91',
                            'Team To Perform Next Frag. 2 map. Next Frag 20 - Team CDEC': '1.83',
                            'Team To Perform Next Frag. 2 map. Next Frag 20 - Team Invictus Gaming': '1.91',
                            'Team To Perform Next Frag. 2 map. Next Frag 30 - Team CDEC': '1.82',
                            'Team To Perform Next Frag. 2 map. Next Frag 30 - Team Invictus Gaming': '1.92',
                            'Team To Perform Next Frag. 2 map. Next Frag 40 - Team CDEC': '1.81',
                            'Team To Perform Next Frag. 2 map. Next Frag 40 - Team Invictus Gaming': '1.93',
                            'Team To Perform Next Frag. 2 map. Next Frag 50 - Team CDEC': '1.83',
                            'Team To Perform Next Frag. 2 map. Next Frag 50 - Team Invictus Gaming': '1.91',
                            'Total Maps Even/Odd. Total Maps - Even': '1.76',
                            'Total Maps Even/Odd. Total Maps - Odd': '1.99',
                            'Total Maps Handicap. CDEC Handicap -1.5 Maps': '2.66',
                            'Total Maps Handicap. CDEC Handicap 1.5 Maps': '1.19',
                            'Total Maps Handicap. Invictus Gaming Handicap -1.5 Maps': '4.34',
                            'Total Maps Handicap. Invictus Gaming Handicap 1.5 Maps': '1.44',
                            'Total Maps. Total Maps Over 2.5': '1.99',
                            'Total Maps. Total Maps Under 2.5': '1.76',
                            'Who Will Beat Roshan. 1 map. 1 Roshan Will Be Beaten By CDEC': '1.71',
                            'Who Will Beat Roshan. 1 map. 1 Roshan Will Be Beaten By Invictus Gaming': '2.06',
                            'Who Will Beat Roshan. 2 map. 1 Roshan Will Be Beaten By CDEC': '1.71',
                            'Who Will Beat Roshan. 2 map. 1 Roshan Will Be Beaten By Invictus Gaming': '2.06',
                            'url': 'https://1x-bet.com/en/line/Esports/2108629-Dota-2-OGA-Dota-PIT-Season-2-China/78828257-Invictus-Gaming-CDEC/'},
 'magnus - huskar': {'1x2. Huskar': '1.355',
                     '1x2. Magnus': '3.03',
                     'url': 'https://1x-bet.com/en/line/Esports/1534671-Dota-2-Arcana-Vote/78685993-Magnus-Huskar/'},
 'neon esports - 496 gaming': {'1x2. 1 map. 496 Gaming': '3.28',
                               '1x2. 1 map. Neon Esports': '1.31',
                               '1x2. 2 map. 496 Gaming': '3.28',
                               '1x2. 2 map. Neon Esports': '1.31',
                               '1x2. 496 Gaming': '4.5',
                               '1x2. Neon Esports': '1.19',
                               'url': 'https://1x-bet.com/en/line/Esports/2110852-Dota-2-Moon-Studio-Asian-League-Southeast-Asia-Qualifier/78804905-Neon-Esports-496-Gaming/'},
 'neon esports - reckoning.esports': {'1x2. 1 map. Neon Esports': '1.26',
                                      '1x2. 1 map. ReckoninG.Esports': '3.66',
                                      '1x2. 2 map. Neon Esports': '1.26',
                                      '1x2. 2 map. ReckoninG.Esports': '3.66',
                                      '1x2. Neon Esports': '1.13',
                                      '1x2. ReckoninG.Esports': '5.65',
                                      'url': 'https://1x-bet.com/en/line/Esports/2110852-Dota-2-Moon-Studio-Asian-League-Southeast-Asia-Qualifier/78804902-Neon-Esports-ReckoninGEsports/'},
 'panda - cobra': {'1x2. 1 map. Cobra': '1.77',
                   '1x2. 1 map. Panda': '2.005',
                   '1x2. 2 map. Cobra': '1.77',
                   '1x2. 2 map. Panda': '2.005',
                   '1x2. Cobra': '1.72',
                   '1x2. Panda': '2.08',
                   'url': 'https://1x-bet.com/en/line/Esports/2109420-Dota-2-Masters-Tournament-Season-9/78835718-Panda-Cobra/'},
 'skywrath mage - riki': {'1x2. Riki': '1.05',
                          '1x2. Skywrath Mage': '8.7',
                          'url': 'https://1x-bet.com/en/line/Esports/1534671-Dota-2-Arcana-Vote/78686005-Skywrath-Mage-Riki/'},
 'sniper - clinkz': {'1x2. Clinkz': '10.5',
                     '1x2. Sniper': '1.03',
                     'url': 'https://1x-bet.com/en/line/Esports/1534671-Dota-2-Arcana-Vote/78686003-Sniper-Clinkz/'},
 'symmetric - goodfellaz': {'1x2. 1 map. Goodfellaz': '1.37',
                            '1x2. 1 map. Symmetric': '2.97',
                            '1x2. 2 map. Goodfellaz': '1.37',
                            '1x2. 2 map. Symmetric': '2.97',
                            '1x2. Goodfellaz': '1.24',
                            '1x2. Symmetric': '3.9',
                            'url': 'https://1x-bet.com/en/line/Esports/2110439-Dota-2-Libertango-Cup/78817876-Symmetric-Goodfellaz/'},
 'team honor - immortal gaming': {'1x2. 1 map. Immortal Gaming': '1.975',
                                  '1x2. 1 map. Team Honor': '1.78',
                                  '1x2. 2 map. Immortal Gaming': '1.975',
                                  '1x2. 2 map. Team Honor': '1.78',
                                  '1x2. Immortal Gaming': '2.06',
                                  '1x2. Team Honor': '1.74',
                                  'url': 'https://1x-bet.com/en/line/Esports/2109420-Dota-2-Masters-Tournament-Season-9/78835720-Team-Honor-Immortal-Gaming/'},
 'team honor - team sincere': {'1x2. 1 map. Team Honor': '1.9',
                               '1x2. 1 map. Team Sincere': '1.85',
                               '1x2. 2 map. Team Honor': '1.9',
                               '1x2. 2 map. Team Sincere': '1.85',
                               '1x2. Team Honor': '1.936',
                               '1x2. Team Sincere': '1.84',
                               'url': 'https://1x-bet.com/en/line/Esports/2109420-Dota-2-Masters-Tournament-Season-9/78816293-Team-Honor-Team-Sincere/'},
 'team oracle - neet uprising': {'1x2. 1 map. Neet Uprising': '1.77',
                                 '1x2. 1 map. Team Oracle': '2.005',
                                 '1x2. 2 map. Neet Uprising': '1.77',
                                 '1x2. 2 map. Team Oracle': '2.005',
                                 '1x2. Draw': '2.265',
                                 '1x2. Neet Uprising': '2.75',
                                 '1x2. Team Oracle': '3.42',
                                 'url': 'https://1x-bet.com/en/line/Esports/2102691-Dota-2-LPL-Pro-League-Season-2/78819071-Team-Oracle-Neet-Uprising/'},
 'vampire - team sincere': {'1x2. 1 map. Team Sincere': '1.85',
                            '1x2. 1 map. Vampire': '1.9',
                            '1x2. 2 map. Team Sincere': '1.85',
                            '1x2. 2 map. Vampire': '1.9',
                            '1x2. Team Sincere': '1.84',
                            '1x2. Vampire': '1.936',
                            'url': 'https://1x-bet.com/en/line/Esports/2109420-Dota-2-Masters-Tournament-Season-9/78835715-Vampire-Team-Sincere/'},
 'vengeful spirit - necrophos': {'1x2. Necrophos': '1.25',
                                 '1x2. Vengeful Spirit': '3.74',
                                 'url': 'https://1x-bet.com/en/line/Esports/1534671-Dota-2-Arcana-Vote/78686004-Vengeful-Spirit-Necrophos/'}}
