bets = {'4 zoomers - infinity': {'1-st map: 4 zoomers Handicap value. –12.5. Handicap coefficient': '1.87',
                          '1-st map: Total. 47.5. Over': '1.87',
                          '1-st map: Total. 47.5. Under': '1.87',
                          '1-st map: infinity Handicap value. +12.5. Handicap coefficient': '1.87',
                          '4 zoomers Handicap value. –0.5. Handicap coefficient': '1.30',
                          'Away win': '12.0',
                          'Draw': '3.78',
                          'Home win': '1.30',
                          'infinity Handicap value. +0.5. Handicap coefficient': '3.30',
                          'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1'},
 '496 - veteran': {'Away win': '4.20',
                   'Draw': '2.05',
                   'Home win': '2.55',
                   'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational'},
 'anti-mage - tusk': {'Win of the 1st team': '1.05',
                      'Win of the 2nd team': '8.54',
                      'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'army geniuses - adversity': {'Away win': '16.0',
                               'Draw': '5.00',
                               'Home win': '1.17',
                               'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational'},
 'beastcoast - infinity': {'1-st map: Total. 46.5. Over': '1.87',
                           '1-st map: Total. 46.5. Under': '1.87',
                           '1-st map: beastcoast Handicap value. –11.5. Handicap coefficient': '1.87',
                           '1-st map: infinity Handicap value. +11.5. Handicap coefficient': '1.87',
                           'Away win': '10.0',
                           'Draw': '2.78',
                           'Home win': '1.52',
                           'beastcoast Handicap value. –0.5. Handicap coefficient': '1.52',
                           'infinity Handicap value. +0.5. Handicap coefficient': '2.43',
                           'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1'},
 'bloodseeker - natures prophet': {'Win of the 1st team': '3.54',
                                   'Win of the 2nd team': '1.27',
                                   'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'cr4zy - thunder predator': {'1-st map: Total. 45.5. Over': '1.87',
                              '1-st map: Total. 45.5. Under': '1.87',
                              '1-st map: cr4zy Handicap value. –4.5. Handicap coefficient': '2.15',
                              '1-st map: thunder predator Handicap value. +4.5. Handicap coefficient': '1.65',
                              'Away win': '3.45',
                              'Draw': '1.86',
                              'Home win': '3.45',
                              'cr4zy Handicap value. –0.5. Handicap coefficient': '3.45',
                              'thunder predator Handicap value. +0.5. Handicap coefficient': '1.28',
                              'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1'},
 'disruptor - timbersaw': {'Win of the 1st team': '1.75',
                           'Win of the 2nd team': '2.01',
                           'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'execration - veteran': {'Win of the 1st team': '3.90',
                          'Win of the 2nd team': '1.23',
                          'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier'},
 'five brothers - space': {'Win of the 1st team': '1.80',
                           'Win of the 2nd team': '1.95',
                           'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation'},
 'magnus - huskar': {'Win of the 1st team': '2.48',
                     'Win of the 2nd team': '1.50',
                     'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'neon - 496': {'Win of the 1st team': '1.18',
                'Win of the 2nd team': '4.50',
                'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier'},
 'neon - reckoning': {'Win of the 1st team': '1.13',
                      'Win of the 2nd team': '5.42',
                      'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league-sea-qualifier'},
 'nine - army geniuses': {'Away win': '1.55',
                          'Draw': '2.77',
                          'Home win': '9.00',
                          'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-razer-sea-invitational'},
 'royal never give up - cdec': {'1-st map: Total. 43.5. Over': '1.70',
                                '1-st map: Total. 43.5. Under': '2.08',
                                '1-st map: Total. 45.5. Over': '1.87',
                                '1-st map: Total. 45.5. Under': '1.87',
                                '1-st map: Total. 47.5. Over': '2.08',
                                '1-st map: Total. 47.5. Under': '1.70',
                                '1-st map: cdec Handicap value. +3.5. Handicap coefficient': '1.77',
                                '1-st map: cdec Handicap value. +4.5. Handicap coefficient': '1.72',
                                '1-st map: cdec Handicap value. –4.5. Handicap coefficient': '2.31',
                                '1-st map: royal never give up Handicap value. +4.5. Handicap coefficient': '1.57',
                                '1-st map: royal never give up Handicap value. –3.5. Handicap coefficient': '1.97',
                                '1-st map: royal never give up Handicap value. –4.5. Handicap coefficient': '2.05',
                                'Total. 2.5. Over': '1.90',
                                'Total. 2.5. Under': '1.85',
                                'Win of the 1st team': '1.75',
                                'Win of the 2nd team': '2.01',
                                'cdec Handicap value. +1.5. Handicap coefficient': '1.30',
                                'royal never give up Handicap value. –1.5. Handicap coefficient': '3.30',
                                'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-dpl-cda'},
 'skywrath mage - riki': {'Win of the 1st team': '8.54',
                          'Win of the 2nd team': '1.05',
                          'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'sniper - clinkz': {'Win of the 1st team': '1.03',
                     'Win of the 2nd team': '10.1',
                     'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'space - rockets': {'Win of the 1st team': '1.80',
                     'Win of the 2nd team': '1.95',
                     'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation'},
 't1 - neon': {'1-st map: Total. 50.5. Over': '1.70',
               '1-st map: Total. 50.5. Under': '2.08',
               '1-st map: Total. 52.5. Over': '1.87',
               '1-st map: Total. 52.5. Under': '1.87',
               '1-st map: Total. 54.5. Over': '2.08',
               '1-st map: Total. 54.5. Under': '1.70',
               '1-st map: neon Handicap value. +3.5. Handicap coefficient': '1.75',
               '1-st map: neon Handicap value. +4.5. Handicap coefficient': '1.67',
               '1-st map: neon Handicap value. –4.5. Handicap coefficient': '2.25',
               '1-st map: t1 Handicap value. +4.5. Handicap coefficient': '1.60',
               '1-st map: t1 Handicap value. –3.5. Handicap coefficient': '2.01',
               '1-st map: t1 Handicap value. –4.5. Handicap coefficient': '2.10',
               'Away win': '3.45',
               'Draw': '1.90',
               'Home win': '3.30',
               'neon Handicap value. +0.5. Handicap coefficient': '1.30',
               't1 Handicap value. –0.5. Handicap coefficient': '3.30',
               'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-one-esports-sea-league'},
 'vengeful spirit - necrophos': {'Win of the 1st team': '3.71',
                                 'Win of the 2nd team': '1.25',
                                 'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'viper - templar assassin': {'Win of the 1st team': '5.66',
                              'Win of the 2nd team': '1.12',
                              'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'virtus.pro - flytomoon': {'1-st map: Total. 45.5. Over': '1.70',
                            '1-st map: Total. 45.5. Under': '2.08',
                            '1-st map: Total. 47.5. Over': '1.87',
                            '1-st map: Total. 47.5. Under': '1.87',
                            '1-st map: Total. 49.5. Over': '2.08',
                            '1-st map: Total. 49.5. Under': '1.70',
                            '1-st map: flytomoon Handicap value. +4.5. Handicap coefficient': '1.57',
                            '1-st map: flytomoon Handicap value. –3.5. Handicap coefficient': '1.97',
                            '1-st map: flytomoon Handicap value. –4.5. Handicap coefficient': '2.05',
                            '1-st map: virtus.pro Handicap value. +3.5. Handicap coefficient': '1.77',
                            '1-st map: virtus.pro Handicap value. +4.5. Handicap coefficient': '1.72',
                            '1-st map: virtus.pro Handicap value. –4.5. Handicap coefficient': '2.31',
                            'Total. 4.5. Over': '2.63',
                            'Total. 4.5. Under': '1.45',
                            'Win of the 1st team': '2.01',
                            'Win of the 2nd team': '1.75',
                            'flytomoon Handicap value. –1.5. Handicap coefficient': '2.48',
                            'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-parimatch-league',
                            'virtus.pro Handicap value. +1.5. Handicap coefficient': '1.50'}}
