bets = {'4 zoomers - infinity': {'1-st map: 4 zoomers Handicap value. –12.5. Handicap coefficient': '1.87',
                          '1-st map: Total. 47.5. Over': '1.87',
                          '1-st map: Total. 47.5. Under': '1.87',
                          '1-st map: infinity Handicap value. +12.5. Handicap coefficient': '1.87',
                          '4 zoomers Handicap value. –0.5. Handicap coefficient': '1.30',
                          'Away win': '12.0',
                          'Draw': '3.78',
                          'Home win': '1.30',
                          'infinity Handicap value. +0.5. Handicap coefficient': '3.30',
                          'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1'},
 'anti-mage - tusk': {'Win of the 1st team': '1.05',
                      'Win of the 2nd team': '8.54',
                      'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'beastcoast - infinity': {'1-st map: Total. 46.5. Over': '1.87',
                           '1-st map: Total. 46.5. Under': '1.87',
                           '1-st map: beastcoast Handicap value. –11.5. Handicap coefficient': '1.87',
                           '1-st map: infinity Handicap value. +11.5. Handicap coefficient': '1.87',
                           'Away win': '10.0',
                           'Draw': '2.78',
                           'Home win': '1.52',
                           'beastcoast Handicap value. –0.5. Handicap coefficient': '1.52',
                           'infinity Handicap value. +0.5. Handicap coefficient': '2.43',
                           'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1'},
 'bloodseeker - natures prophet': {'Win of the 1st team': '4.00',
                                   'Win of the 2nd team': '1.22',
                                   'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'cr4zy - thunder predator': {'1-st map: Total. 45.5. Over': '1.87',
                              '1-st map: Total. 45.5. Under': '1.87',
                              '1-st map: cr4zy Handicap value. –4.5. Handicap coefficient': '2.15',
                              '1-st map: thunder predator Handicap value. +4.5. Handicap coefficient': '1.65',
                              'Away win': '3.45',
                              'Draw': '1.86',
                              'Home win': '3.45',
                              'cr4zy Handicap value. –0.5. Handicap coefficient': '3.45',
                              'thunder predator Handicap value. +0.5. Handicap coefficient': '1.28',
                              'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-1'},
 'disruptor - timbersaw': {'Win of the 1st team': '1.82',
                           'Win of the 2nd team': '1.92',
                           'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'ehome - vici gaming': {'1-st map: Total. 44.5. Over': '1.70',
                         '1-st map: Total. 44.5. Under': '2.08',
                         '1-st map: Total. 46.5. Over': '1.87',
                         '1-st map: Total. 46.5. Under': '1.87',
                         '1-st map: Total. 48.5. Over': '2.05',
                         '1-st map: Total. 48.5. Under': '1.72',
                         '1-st map: ehome Handicap value. +3.5. Handicap coefficient': '1.87',
                         '1-st map: ehome Handicap value. +4.5. Handicap coefficient': '1.80',
                         '1-st map: ehome Handicap value. +5.5. Handicap coefficient': '1.72',
                         '1-st map: vici gaming Handicap value. –3.5. Handicap coefficient': '1.87',
                         '1-st map: vici gaming Handicap value. –4.5. Handicap coefficient': '1.95',
                         '1-st map: vici gaming Handicap value. –5.5. Handicap coefficient': '2.05',
                         'Total. 2.5. Over': '1.95',
                         'Total. 2.5. Under': '1.80',
                         'Win of the 1st team': '2.35',
                         'Win of the 2nd team': '1.55',
                         'ehome Handicap value. +1.5. Handicap coefficient': '1.35',
                         'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-oga-dota-pit-cn',
                         'vici gaming Handicap value. –1.5. Handicap coefficient': '3.05'},
 'ethereal - destiny': {'Win of the 1st team': '1.80',
                        'Win of the 2nd team': '1.95',
                        'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-masters-tournament'},
 'execration - veteran': {'Win of the 1st team': '3.54',
                          'Win of the 2nd team': '1.27',
                          'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-lpl-pro'},
 'honor - immortal': {'Win of the 1st team': '1.75',
                      'Win of the 2nd team': '2.01',
                      'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-masters-tournament'},
 'honor - sincere': {'Win of the 1st team': '1.80',
                     'Win of the 2nd team': '1.95',
                     'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-masters-tournament'},
 'immortal - vampire': {'Win of the 1st team': '1.75',
                        'Win of the 2nd team': '2.01',
                        'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-masters-tournament'},
 'invictus gaming - cdec': {'1-st map: Total. 43.5. Over': '1.70',
                            '1-st map: Total. 43.5. Under': '2.08',
                            '1-st map: Total. 45.5. Over': '1.87',
                            '1-st map: Total. 45.5. Under': '1.87',
                            '1-st map: Total. 47.5. Over': '2.05',
                            '1-st map: Total. 47.5. Under': '1.72',
                            '1-st map: cdec Handicap value. –3.5. Handicap coefficient': '1.82',
                            '1-st map: cdec Handicap value. –4.5. Handicap coefficient': '1.90',
                            '1-st map: cdec Handicap value. –5.5. Handicap coefficient': '2.00',
                            '1-st map: invictus gaming Handicap value. +3.5. Handicap coefficient': '1.92',
                            '1-st map: invictus gaming Handicap value. +4.5. Handicap coefficient': '1.85',
                            '1-st map: invictus gaming Handicap value. +5.5. Handicap coefficient': '1.76',
                            'Total. 2.5. Over': '2.00',
                            'Total. 2.5. Under': '1.76',
                            'Win of the 1st team': '2.25',
                            'Win of the 2nd team': '1.60',
                            'cdec Handicap value. –1.5. Handicap coefficient': '2.90',
                            'invictus gaming Handicap value. +1.5. Handicap coefficient': '1.38',
                            'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-oga-dota-pit-cn'},
 'magnus - huskar': {'Win of the 1st team': '2.82',
                     'Win of the 2nd team': '1.40',
                     'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'neon - 496': {'Win of the 1st team': '1.18',
                'Win of the 2nd team': '4.50',
                'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-lpl-pro'},
 'neon - reckoning': {'Win of the 1st team': '1.13',
                      'Win of the 2nd team': '5.42',
                      'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-lpl-pro'},
 'panda - cobra': {'Win of the 1st team': '2.00',
                   'Win of the 2nd team': '1.76',
                   'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-masters-tournament'},
 'skywrath mage - riki': {'Win of the 1st team': '8.54',
                          'Win of the 2nd team': '1.05',
                          'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'sniper - clinkz': {'Win of the 1st team': '1.03',
                     'Win of the 2nd team': '10.1',
                     'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'vampire - sincere': {'Win of the 1st team': '1.95',
                       'Win of the 2nd team': '1.80',
                       'url': 'https://www.parimatch.com/en/sport/kibersport/dota-2-masters-tournament'},
 'vengeful spirit - necrophos': {'Win of the 1st team': '3.71',
                                 'Win of the 2nd team': '1.25',
                                 'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'},
 'viper - templar assassin': {'Win of the 1st team': '5.66',
                              'Win of the 2nd team': '1.12',
                              'url': 'https://www.parimatch.com/en/sport/kibersport/specialnye-stavki-dota-2-arcana-vote'}}
