sport = {
    'dota':{
 'invictus gaming - cdec(parimatch - https://1x-bet.com/en/line/Esports/2104750-Dota-2-ESL-Meisterschaft-2020-Season-1/78878303-airGERlich-Euronics-Gaming/)': {'1-st map: Total. 43.5. Over': '1.70',
                            '1-st map: Total. 43.5. Under': '2.08',
                            '1-st map: Total. 45.5. Over': '1.87',
                            '1-st map: Total. 45.5. Under': '1.87',
                            '1-st map: Total. 47.5. Over': '2.05',
                            '1-st map: Total. 47.5. Under': '1.72',
                            '1-st map: cdec Handicap value. –3.5. Handicap coefficient': '1.82',
                            '1-st map: cdec Handicap value. –4.5. Handicap coefficient': '1.90',
                            '1-st map: cdec Handicap value. –5.5. Handicap coefficient': '2.00',
                            '1-st map: invictus gaming Handicap value. +3.5. Handicap coefficient': '1.92',
                            '1-st map: invictus gaming Handicap value. +4.5. Handicap coefficient': '1.85',
                            '1-st map: invictus gaming Handicap value. +5.5. Handicap coefficient': '1.76',
                            'Total. 2.5. Over': '2.00',
                            'Total. 2.5. Under': '1.76',
                            'Win of the 1st team': '2.25',
                            'Win of the 2nd team': '1.60',
                            'cdec Handicap value. –1.5. Handicap coefficient': '2.90',
                            'invictus gaming Handicap value. +1.5. Handicap coefficient': '1.38'}}}
